force-app/main/default/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address built from populated fields

Uses a custom label to contain a carriage return for substitution</description>
        <formula>TRIM( 
IF (ISBLANK(Street_Name__c),&quot;&quot;,  SUBSTITUTE(Street_Name__c,  SUBSTITUTE($Label.CR,&quot;-&quot;,&quot;&quot;), &quot; &quot;) &amp; &quot;, &quot;) 
&amp;
City__c + &quot; &quot;
&amp;
State__c + &quot; &quot; 
&amp;
Post_Code__c) 
&amp;
IF (ISBLANK(TEXT(Country2__c)),&quot;&quot;, &quot;, &quot; + TEXT(Country2__c))</formula>
        <label>Full Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City/town</description>
        <inlineHelpText>Please provide the city/town of the address.</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this address is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <description>Post code of the address</description>
        <inlineHelpText>Please provide the post code of the address</inlineHelpText>
        <label>Post Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the address is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the address.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State of the address</description>
        <inlineHelpText>Please provide the state of the address.</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the address.</description>
        <inlineHelpText>Please enter the address type</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mailing</fullName>
                    <default>true</default>
                    <label>Mailing</label>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                    <isActive>false</isActive>
                    <label>Fax</label>
                </value>
                <value>
                    <fullName>Landline</fullName>
                    <isActive>false</isActive>
                    <label>Landline</label>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                    <isActive>false</isActive>
                    <label>Mobile</label>
                </value>
                <value>
                    <fullName>Postal</fullName>
                    <isActive>false</isActive>
                    <label>Postal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliation__c.object
<CustomObject>
    <description>Links a person (Contact) with an entity, e.g. company (or organisational unit), club, school etc.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact (person) of the affiliation to an account (organisation)</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the email address is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the affiliation</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFL-{0000000}</displayFormat>
        <label>Affiliation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <recordTypes>
        <fullName>Agent</fullName>
        <active>true</active>
        <description>An agent to Monash, e.g. for course applications.</description>
        <label>Agent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>An applicant for a course or program at Monash</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Point_Affiliation__c.object
<CustomObject>
    <description>Link between a contact point (Email, Phone, Address) and Affiliation of a person (Contact)</description>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The address this contact point refers to. One of phone, email, address, and social is mandatory.</description>
        <inlineHelpText>Please provide the address for this contact point affiliation.</inlineHelpText>
        <label>Address</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The selected Address is not related to the contact</errorMessage>
            <filterItems>
                <field>Address__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Contact Point Affiliations</relationshipLabel>
        <relationshipName>Contact_Point_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Affiliation__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The affiliation a contact point refers to.</description>
        <inlineHelpText>Please provide the affiliation record the contact point should be linked to.</inlineHelpText>
        <label>Affiliation</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Affiliation must be for the same Contact</errorMessage>
            <filterItems>
                <field>Affiliation__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Affiliation__c</referenceTo>
        <relationshipLabel>Contact Point Affiliations</relationshipLabel>
        <relationshipName>Contact_Point_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The Contact the contact point affiliation relates to.</description>
        <inlineHelpText>Please provide the contact for the contact point affiliation.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Point Affiliations</relationshipLabel>
        <relationshipName>Contact_Point_Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The email this contact point refers to. One of phone, email, address, and social is mandatory.</description>
        <inlineHelpText>Please provide an email for the affiliation.</inlineHelpText>
        <label>Email</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Email address must be a child of the Contact</errorMessage>
            <filterItems>
                <field>Email__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Email__c</referenceTo>
        <relationshipLabel>Contact Point Affiliations</relationshipLabel>
        <relationshipName>Contact_Point_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The phone this contact point refers to. One of phone, email, address, and social is mandatory.</description>
        <inlineHelpText>Please provide the phone this contact point refers to.</inlineHelpText>
        <label>Phone</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Phone number number be a child of the Contact</errorMessage>
            <filterItems>
                <field>Phone__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Contact Point Affiliations</relationshipLabel>
        <relationshipName>Contact_Point_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Not Implemented</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contact Point Affiliation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Point Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this email address is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Addresses</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the email address is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the email address</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Email</label>
    <nameField>
        <label>Email Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Name__c.object
<CustomObject>
    <description>Name of a person (Contact)</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this name is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Names</relationshipLabel>
        <relationshipName>Names</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the name is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the name.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Name</label>
    <nameField>
        <displayFormat>NAM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this phone number is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Phone Numbers</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the phone number is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the phone number</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <label>Phone Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Person360TestDataFactory.cls
/**
 * @description       : Test Data Factory for the Person 360 structure
 * @author            : Nick Guia
 * @last modified on  : 18-07-2023
 * @last modified by  : Nick Guia
**/
@isTest
public without sharing class Person360TestDataFactory {

    private Boolean isMock = false;
    
    public Person360TestDataFactory(Boolean shouldMock) {
        this.isMock = shouldMock;
    }

    /**
    * @description generate a Person 360 instance. Will insert an affiliation account
    * @author Nick Guia | 17-07-2023 
    * @param Contact con : try to use unique names on your contact; should have FN and LN
    * @return Person360 
    **/
    public Person360 createPerson360(Contact con) {
        return createPerson360(con, createAgencyAccount());
    }

    /**
    * @description create an Agency type account
    * @author Nick Guia | 17-07-2023 
    * @return Account 
    **/
    public Account createAgencyAccount() {
        return new Account(
            Id = isMock ? fflib_IDGenerator.generate(Account.SObjectType) : null,
            Name = 'Person 360 Pty Ltd',
            Phone = '987654',
            Email__c = 'p360.australia@test.org',
            Website = 'www.p360-australia.com',
            Street__c = 'Collins St',
            City__c = 'Melbourne',
            State__c = 'VIC',
            Post_Code__c = '3000',
            ShippingStreet = 'Collins St',
            ShippingCity = 'Melbourne',
            ShippingState = 'VIC',
            ShippingPostalCode = '3000',
            ShippingCountry = 'Australia',
            Monash_AM_Web_Status__c = true,
            Callista_Org_Unit_Code__c = 'CRM-AGENT',
            Monash_AM_Campus__c = 'Australia',
            RecordTypeId = AccountUtility.ACCOUNT_AGENCY_REC_TYPE,
            Status__c = 'Appointed'
        );
    }

    /**
    * @description generate a Person 360 instance
    * @author Nick Guia | 17-07-2023 
    * @param Contact con : try to use unique names on your contact; should have FN and LN
    * @param Account affiliationAccount : Account to be linked to Affiliation (required)
    * @return Person360 
    **/
    public Person360 createPerson360(Contact con, Account affiliationAccount) {

        Person360.Person360Builder builder = new Person360.Person360Builder(con);

        // affiliation
        builder.withAffiliation(affiliationAccount?.Id, 'Applicant');

        // address
        builder.buildAddress()
                .withClassification('Private')
                .withStreetName('Collins St')
                .withCity('Melbourne')
                .withState('VIC')
                .withPostCode('3000')
                .withCountry('Australia')
                .withType('Mailing')
                .withSource('Contact supplied');
        // phone
        builder.buildPhone()
                .withClassification('Private')
                .withPhoneNumber('+61 497000000')
                .withType('Mobile')
                .withSource('Contact supplied');
        // email
        builder.buildEmail()
                .withClassification('Private')
                .withEmailId('person360.testdatafactory@test.org')
                .withSource('Contact supplied');
        // name
        builder.buildName()
                .withSalutation('Mr')
                .withName(con.FirstName, 'MiddleName', con.LastName)
                .withSuffix('Jr')
                .withType('Common')
                .withSource('Contact supplied');

        if(this.isMock) {
            mockFields(builder);
        } else {
            // bypass the builder and set default start dates on each contact points
            // this is so that we can keep the triggers muted since start date is required
            // TODO : add withStartDate() on ContactPointBuilderFactory
            for(String cpKey : builder.contactPointMap.keySet()) {
                List<SObject> cpList = builder.contactPointMap.get(cpKey);
                
                for(SObject cpRec : cpList) {
                    // assume all api names are the same
                    cpRec.put('Start_Date__c', Date.today());
                }
            }
        }

        return builder.build();
    }

    /**
    * @description mocks the IDs and read-only fields
    * @author Nick Guia | 17-07-2023 
    * @param Person360.Person360Builder builder 
    **/
    private void mockFields(Person360.Person360Builder builder) {

        builder.conRec.Id = (builder.conRec.Id == null) ? fflib_IDGenerator.generate(Contact.SObjectType) : builder.conRec.Id;
        builder.accRec.Id = fflib_IDGenerator.generate(Account.SObjectType);
        builder.affRec.Id = fflib_IDGenerator.generate(Affiliation__c.SObjectType);

        Map<String, String> cpaTypeMap = new Map<String, String>{
            'Phone__c' => 'Phone',
            'Email__c' => 'Email',
            'Address__c' => 'Address'
        };

        // generate mock Ids for contact points and CPAs
        for(String cpType : builder.contactPointMap.keySet()) {

            List<SObject> lstSObj = builder.contactPointMap.get(cpType);

            // ignore the CPAs in the builder - create a new one
            List<Contact_Point_Affiliation__c> lstCPA = new List<Contact_Point_Affiliation__c>();

            for(SObject iCp : lstSObj) {
                iCp.put('Id', fflib_IDGenerator.generate(iCp.getSObjectType()));
                // link CP to Contact
                iCp.put('Contact__c', builder.conRec.Id);
                iCp.put('Start_Date__c', Date.today());

                if(cpType != 'Name__c') { // Do not create CPA for Names
                    Contact_Point_Affiliation__c cpa = new Contact_Point_Affiliation__c();
                    // link CPA to contact
                    cpa.put('Contact__c', builder.conRec.Id);
                    // link CPA to affiliation
                    cpa.put('Affiliation__c', builder.affRec.Id);
                    // link CPA to CP; assumption is that SObjectType = Lookup field API
                    cpa.put(cpType, iCp.Id); 
                    // populate the rest of the mocks
                    cpa = (Contact_Point_Affiliation__c) fflib_ApexMocksUtils.setReadOnlyFields(
                        cpa,
                        Contact_Point_Affiliation__c.class,
                        new Map<SObjectField, Object> {
                            Contact_Point_Affiliation__c.Id => fflib_IDGenerator.generate(Contact_Point_Affiliation__c.SObjectType),
                            Contact_Point_Affiliation__c.Type__c => cpaTypeMap.get(cpType)
                        }
                    );
                    lstCPA.add(cpa);
                }
            }

            builder.cpaMap.put(cpType, lstCPA);
        }
    }
}