force-app/main/default/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address built from populated fields

Uses a custom label to contain a carriage return for substitution</description>
        <formula>TRIM( 
IF (ISBLANK(Street_Name__c),&quot;&quot;,  SUBSTITUTE(Street_Name__c,  SUBSTITUTE($Label.CR,&quot;-&quot;,&quot;&quot;), &quot; &quot;) &amp; &quot;, &quot;) 
&amp;
City__c + &quot; &quot;
&amp;
State__c + &quot; &quot; 
&amp;
Post_Code__c) 
&amp;
IF (ISBLANK(TEXT(Country2__c)),&quot;&quot;, &quot;, &quot; + TEXT(Country2__c))</formula>
        <label>Full Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_set_by__c</fullName>
        <description>Use as indicator if the record (only if Is_Primary__c changed) has been modified by user or system.</description>
        <label>Primary set by</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PrimaryAddressCalculator.cls
/**
 * @description       : For calculating the Primary Address record
 * @date              : 28-07-2023
 * @group             : Person 360
 * @author            : Nick Guia
 * @last modified on  : 22-08-2023
 * @last modified by  : Nick Guia
 * @see https://monash-esol.atlassian.net/wiki/spaces/MCE/pages/289931356/Contact+Point+Primary+Calculator
**/
public inherited sharing class PrimaryAddressCalculator extends PrimaryContactPointCalculator {


    public PrimaryAddressCalculator(List<Address__c> records, Boolean isStudent) {
        super(records, isStudent);
    }

    /**
    * @description instantiate the concrete implementation of Address sorting
    * @author Nick Guia | 11-09-2023 
    **/
    protected override ContactPointComparable createContactPointComparable(SObject contactPoint) {
        return new AddressComparable((Address__c) contactPoint);
    }

    /**
    * @description checks if there are any user-overriden primary
    * @author Nick Guia | 28-07-2023 
    **/
    protected override void maybeSetPrimaryByPrioritisedAttributes() {

        for(Address__c address : (List<Address__c>) super.contactPoints) {
            // CONDITION 1 : if there is any "user override" primary, re-tag it as primary
            if(address.Primary_set_by__c == 'user') {
                setPrimary(address);
                super.isPrimarySetByUser = true;
                break;
            }

            /**
             * Assume that we should always sort by roll up rank without the client class indicating the "shouldSort()" option.
             * This is because this rule supersedes student records and we also anticipate that queries don't always "ORDER BY" callista rank,
             * but typically with dates
             */
            addRollupRankSortableList(address);
        }
    }

    /**
    * @description rules for calculating a primary address.
    * @author Nick Guia | 28-07-2023 
    **/
    protected override void calculatePrimary() {

        if(!super.isPrimarySetByUser) {
            
            Address__c primary;

            if(super.isStudent) {
                // CONDITION 2 : if a student, mark the first callista address as primary
                primary = (Address__c) super.getHighestRollupRank();
            }

            if(primary == null) {
                // CONDITION 3 : if not a student OR without a callista address, pick the latest
                primary = (Address__c) super.contactPoints[0];
            }
            
            setPrimary(primary);
        }
    }
}