force-app/main/default/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address built from populated fields

Uses a custom label to contain a carriage return for substitution</description>
        <formula>TRIM( 
IF (ISBLANK(Street_Name__c),&quot;&quot;,  SUBSTITUTE(Street_Name__c,  SUBSTITUTE($Label.CR,&quot;-&quot;,&quot;&quot;), &quot; &quot;) &amp; &quot;, &quot;) 
&amp;
City__c + &quot; &quot;
&amp;
State__c + &quot; &quot; 
&amp;
Post_Code__c) 
&amp;
IF (ISBLANK(TEXT(Country2__c)),&quot;&quot;, &quot;, &quot; + TEXT(Country2__c))</formula>
        <label>Full Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This defines the date until the address is valid for.</description>
        <inlineHelpText>Please provide the date the address is valid through, or leave it empty if it is not known or not end dated.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether an address is active, usually when end date is in the past or the start date is in the future. This value Is automatically (by a scheduled process) set to &quot;false&quot; if End_Date__c is populated and in the past or the Start_Date__c is in the future.
If manually set/changed to &quot;True&quot; (&quot;False&quot;), then the End_Date__c is automatically removed (added with the current date).</description>
        <inlineHelpText>Please indicate whether the address is active or not (inactive).</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A soft delete flag. An overnight purge process removes these records.</description>
        <inlineHelpText>A soft delete flag, queued for purging</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the address is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the address.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This defines the date until the email address is valid for.</description>
        <inlineHelpText>Please provide the date the email address is valid through, or leave it empty if it is not known or not end dated.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether an email address is active, usually when end date is in the past or the start date is in the future. This value Is automatically (by a scheduled process) set to &quot;false&quot; if End_Date__c is populated and in the past or the Start_Date__c is in the future.
If manually set/changed to &quot;True&quot; (&quot;False&quot;), then the End_Date__c is automatically removed (added with the current date).</description>
        <inlineHelpText>Please indicate whether the email address is active or not (inactive).</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Deleted In Source from Channel</description>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the email address is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the email address</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unreachable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the email is not reachable (hard bounce) and emails attempted to be sent cannot be delivered. This checkbox is enabled if an email address has a status of &quot;HELD&quot; in Marketing Cloud, that is emails are not sent anymore.</description>
        <inlineHelpText>Indicates if the email address cannot be reached anymore.</inlineHelpText>
        <label>Unreachable</label>
        <type>Checkbox</type>
    </fields>
    <label>Email</label>
    <nameField>
        <label>Email Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Name__c.object
<CustomObject>
    <description>Name of a person (Contact)</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This defines the date until the name is valid for.</description>
        <inlineHelpText>Please provide the date the name is valid through, or leave it empty if it is not known or not end dated.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether a name is active, usually when end date is in the past or the start date is in the future. This value Is automatically (by a scheduled process) set to &quot;false&quot; if End_Date__c is populated and in the past or the Start_Date__c is in the future.
If manually set/changed to &quot;True&quot; (&quot;False&quot;), then the End_Date__c is automatically removed (added with the current date).</description>
        <inlineHelpText>Please indicate whether the name is active or not (inactive).</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the name is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the name.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Name</label>
    <nameField>
        <displayFormat>NAM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This defines the date until the phone number is valid for.</description>
        <inlineHelpText>Please provide the date the phone number is valid through, or leave it empty if it is not known or not end dated.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether a phone number is active, usually when end date is in the past or the start date is in the future. This value Is automatically (by a scheduled process) set to &quot;false&quot; if End_Date__c is populated and in the past or the Start_Date__c is in the future.
If manually set/changed to &quot;True&quot; (&quot;False&quot;), then the End_Date__c is automatically removed (added with the current date).</description>
        <inlineHelpText>Please indicate whether the phone number is active or not (inactive).</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A soft delete flag on the record. 

An overnight purge process removes the record.</description>
        <inlineHelpText>Soft deleted, queued for purging</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the phone number is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the phone number</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <label>Phone Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social__c.object
<CustomObject>
    <description>Social media handles of a person (Contact)</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This defines the date until the social handle is valid for.</description>
        <inlineHelpText>Please provide the date the social handle is valid through, or leave it empty if it is not known or not end dated.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether a social handle is active, usually when end date is in the past or the start date is in the future. This value Is automatically (by a scheduled process) set to &quot;false&quot; if End_Date__c is populated and in the past or the Start_Date__c is in the future.
If manually set/changed to &quot;True&quot; (&quot;False&quot;), then the End_Date__c is automatically removed (added with the current date).</description>
        <inlineHelpText>Please indicate whether the soical handle is active or not (inactive).</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the social handle is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the social handle</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Social Handle</label>
    <nameField>
        <label>Social Handle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Handles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Person360ToggleIsActiveHelper.cls
/**
 * @description       : Person 360 Toggle IsActive helper class
 * @author            : J.Mapanao
 * @group             : Person 360
 * @last modified on  : 2021-12-01
 * @last modified by  : Stefan Scheit
 * @revision
 *  2019-03-21 - J.Mapanao - Initial version    
 *  2019-06-06 - P.Victoriano - Updated Toggling to accomodate for backdated
 *  2020-02-06 - P.Victoriano - Add IsActive sticking
 *  2021-12-01 - Stefan Scheit - Added logic for 'unreachalbe__c' field (on Email__c records)
**/
public class Person360ToggleIsActiveHelper extends BaseClass {
    public List<SObject> records {get; set;}
    public List<SObject> recordsToUpdate {get; set;}
    public Person360ToggleIsActiveHelper() {
        super(new List<Schema.sObjectType> {
            Name__c.sObjectType,
            Email__c.sObjectType,
            Phone__c.sObjectType,
            Address__c.sObjectType,
            Social__c.sObjectType
        });
        records = new List<SObject>();
        recordsToUpdate = new List<SObject>();
    }

    public virtual void init(SObject record) {
        this.records.add(record);
    }

    public virtual void init(List<SObject> records) {
        this.records = records;
    }

    public virtual void startMapping() {
        if (records != null) {
            for (SObject sObj : records) {
                evaluateIsActiveFieldValue(sObj);
                recordsToUpdate.add(sObj);
            }
        }
    }
    /**
     * evaluateIsActiveFieldValue Checks if IsActive is toggled and let it stick
     */
    public SObject evaluateIsActiveFieldValue(SObject sObj, SOBJect oldSObj) {
        Boolean isActiveVal = (Boolean)sObj.get('Is_Active__c');
        Boolean oldisActiveVal = (Boolean)oldSObj.get('Is_Active__c');
        //IS Active flag is toggled
        if(isActiveVal == false && (isActiveVal != oldisActiveVal)) {
            // do nothing
            nebula.logger.fine('Manual Change End date auto populated');
        } else {
            //Other fields toggled compute for IsActive Flag
            evaluateIsActiveFieldValue(sObj);
        }
        return sObj;
    }
    /**
    * evaluateIsActiveFieldValue Defaults IsActive Flag
    */
    public SObject evaluateIsActiveFieldValue(SObject sObj) {
        Date startDateVal = (Date)sObj.get('Start_Date__c');
        Date endDateVal = (Date)sObj.get('End_Date__c');
        Boolean isActiveVal = (Boolean)sObj.get('Is_Active__c');
        Boolean isDeleted = false; // default as it does not apply to all contact points
        Boolean isUnreachable = false; // default as only Email__c defines this field

        // set 'isDeleted' flags from record(s), only applicable to Address__c, Email__c, and Phone__c
        SobjectType sobjType = sObj.getSObjectType();
        if(sobjType == Schema.Address__c.getSObjectType() || sobjType == Schema.Email__c.getSObjectType() || sobjType == Schema.Phone__c.getSObjectType() ) {
            // update isDeleted if it is set
            isDeleted = (null != sObj.get('Is_Deleted__c')) ? (Boolean)sObj.get('Is_Deleted__c') : false;
        }
        
        // set 'isUnreachable' flag from record(s), only applicable for Email__c
        if(sobjType == Schema.Email__c.getSObjectType()) {
            // update isUnreachable if it is set
            isUnreachable = (null != sObj.get('Unreachable__c')) ? (Boolean)sObj.get('Unreachable__c') : false;
        }
        
        // evaluate whether to set record as active
        if(isDeleted || isUnreachable) {
            // set active field to false if the record is flagged as (logically) deleted or unreachable
            Person360Helper.addFieldValue(sObj, 'Is_Active__c', false);
        } else {
            // Inactive: start date > today
            if ((startDateVal != null &&startDateVal > Date.today()) && (isActiveVal != null && isActiveVal)) {
                Person360Helper.addFieldValue(sObj,'Is_Active__c', false);
            }
            // Inactive: end date <= today
            else if ((endDateVal != null && endDateVal <= Date.today()) && (isActiveVal != null && isActiveVal)) {
                Person360Helper.addFieldValue(sObj,'Is_Active__c', false);
            }
            // Active: start date <= today AND end date > today or blank
            else if ((startDateVal != null && startDateVal <= Date.today()) && (endDateVal == null || endDateVal > Date.today()) && (isActiveVal != null && !isActiveVal)) {
                Person360Helper.addFieldValue(sObj,'Is_Active__c', true);
            } 
        }
        return sObj;
    }

    public void processRecords() {
        if (recordsToUpdate != null && !recordsToUpdate.isEmpty()) {
            for (SObject sObj : recordsToUpdate) {
                push(sObj);
            }
            BaseClass.ResultSet lResultSet = commitRecordsPartial();
        }
    }
}