force-app/main/default/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address built from populated fields

Uses a custom label to contain a carriage return for substitution</description>
        <formula>TRIM( 
IF (ISBLANK(Street_Name__c),&quot;&quot;,  SUBSTITUTE(Street_Name__c,  SUBSTITUTE($Label.CR,&quot;-&quot;,&quot;&quot;), &quot; &quot;) &amp; &quot;, &quot;) 
&amp;
City__c + &quot; &quot;
&amp;
State__c + &quot; &quot; 
&amp;
Post_Code__c) 
&amp;
IF (ISBLANK(TEXT(Country2__c)),&quot;&quot;, &quot;, &quot; + TEXT(Country2__c))</formula>
        <label>Full Address</label>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c.object
<CustomObject>
    <label>Email</label>
    <nameField>
        <label>Email Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Name__c.object
<CustomObject>
    <description>Name of a person (Contact)</description>
    <label>Name</label>
    <nameField>
        <displayFormat>NAM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone__c.object
<CustomObject>
    <label>Phone</label>
    <nameField>
        <label>Phone Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Social__c.object
<CustomObject>
    <description>Social media handles of a person (Contact)</description>
    <label>Social Handle</label>
    <nameField>
        <label>Social Handle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Handles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Person360DAOTest.cls
@isTest
private class Person360DAOTest {

    /**
     * Test Contact Record
     */
    static testMethod void sObjectTest() {

        Person360DAO dao = new Person360DAO();
        //
        dao.initialize('Contact', 'Group1');
        System.assertEquals(Contact.sObjectType, dao.getSObject().getSObjectType(), 'Object Type Error');
        //
        dao.addFieldValue('LastName', 'TestLastName');
        Contact con = (Contact)dao.getSObject().clone();
        dao.clearCache();
        System.assertEquals(null, dao.getSObject(), 'Contact Failed Cache');
        dao.setSObject(con);
        System.assertEquals('TestLastName', dao.getSObject().get('LastName'), 'Contact Failed');
        //
        dao.clearCache();
        dao.initialize('Name__c', 'Group2');
        System.assertEquals(Name__c.sObjectType, dao.getSObject().getSObjectType(), 'Object Type Error');
        //
        dao.clearCache();
        dao.initialize('Email__c', 'Group3');
        System.assertEquals(Email__c.sObjectType, dao.getSObject().getSObjectType(), 'Object Type Error');
        //
        dao.clearCache();
        dao.initialize('Phone__c', 'Group4');
        System.assertEquals(Phone__c.sObjectType, dao.getSObject().getSObjectType(), 'Object Type Error');
        //
        dao.clearCache();
        dao.initialize('Address__c', 'Group5');
        System.assertEquals(Address__c.sObjectType, dao.getSObject().getSObjectType(), 'Object Type Error');
        //
        dao.clearCache();
        dao.initialize('Social__c', 'Group6');
        System.assertEquals(Social__c.sObjectType, dao.getSObject().getSObjectType(), 'Object Type Error');
        //Double the Grouping Test
        dao.clearCache();
        dao.initialize('Email__c', 'Group3');
        System.assertEquals(Email__c.sObjectType, dao.getSObject().getSObjectType(), 'Object Type Error');
        //
        dao.clearCache();
        dao.initialize('Phone__c', 'Group4');
        System.assertEquals(Phone__c.sObjectType, dao.getSObject().getSObjectType(), 'Object Type Error');
        //
        dao.clearCache();
        dao.initialize('Address__c', 'Group5');
        System.assertEquals(Address__c.sObjectType, dao.getSObject().getSObjectType(), 'Object Type Error');
        //
        dao.clearCache();
        dao.initialize('Social__c', 'Group6');
        System.assertEquals(Social__c.sObjectType, dao.getSObject().getSObjectType(), 'Object Type Error');
    }

}