force-app/main/default/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Channel lookup field for the Contact Point object record</description>
        <label>Channel</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Address channels must be for the same Contact record</errorMessage>
            <filterItems>
                <field>Channel__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <filterItems>
                <field>Channel__c.Type__c</field>
                <operation>notEqual</operation>
                <value>EMERCONT</value>
            </filterItems>
            <infoMessage>Search for all non-emergency contact channels for this contact</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City/town</description>
        <inlineHelpText>Please provide the city/town of the address.</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <description>Post code of the address</description>
        <inlineHelpText>Please provide the post code of the address</inlineHelpText>
        <label>Post Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source of the address.</description>
        <inlineHelpText>Please enter source of the address, i.e. how were the details obtained.</inlineHelpText>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Source</valueSetName>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c.object
<CustomObject>
    <description>Communication Channels</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deleted_In_Source__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Record has been deleted in the source system.</description>
        <inlineHelpText>Record has been deleted in the source system.</inlineHelpText>
        <label>Deleted In Source</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System Field - indicates that the record was processed into Contact Point records</description>
        <inlineHelpText>System Field - indicates that the record was processed into Contact Point records</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone_2__c</fullName>
        <label>Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <description>Source System of the record.</description>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Channel lookup field for the Contact Point object record</description>
        <inlineHelpText>Lookup to Channel for Callista sourced records</inlineHelpText>
        <label>Channel</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Email channels must be for the same Contact record</errorMessage>
            <filterItems>
                <field>Channel__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <filterItems>
                <field>Channel__c.Type__c</field>
                <operation>notEqual</operation>
                <value>EMERCONT</value>
            </filterItems>
            <infoMessage>Search for all non-emergency contact channels for this contact</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source of the email address.</description>
        <inlineHelpText>Please enter source of the email address, i.e. how were the details obtained.</inlineHelpText>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Source</valueSetName>
        </valueSet>
    </fields>
    <label>Email</label>
    <nameField>
        <label>Email Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Emergency_Contact__c.object
<CustomObject>
    <description>Emergency contact details for the student</description>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Callista source data for the Emergency Contact</description>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Emergency Contacts</relationshipLabel>
        <relationshipName>Emergency_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Address field</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Address Field

ISO Country List for Emergency Contacts</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <description>Primary phone number</description>
        <inlineHelpText>Primary phone number</inlineHelpText>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <description>Address field</description>
        <inlineHelpText>Address field</inlineHelpText>
        <label>Post Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Emergency Contact</label>
    <nameField>
        <displayFormat>EC-{00000000}</displayFormat>
        <label>Emergency Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emergency Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Feature_Switch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Allow features to be enabled or disabled based on a Boolean switch</description>
    <fields>
        <fullName>Format_Mobile__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Parse mobile phone numbers against the PHONE_NUMBER_FORMAT system setting custom metadata. A match will result in a basic reformatting of the number, including the possible addition of a country code.</description>
        <inlineHelpText>Parse mobile phone numbers against the PHONE_NUMBER_FORMAT system setting custom metadata.</inlineHelpText>
        <label>Format Mobile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Process_Emergency_Contacts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Create Emergency Contacts records from Channel staging records</description>
        <label>Process Emergency Contacts</label>
        <type>Checkbox</type>
    </fields>
    <label>Feature Switch</label>
</CustomObject>

force-app/main/default/objects/Person360Muting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>On/Off Settings for Person360</description>
    <fields>
        <fullName>EnableChannelBreakUp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>On/Off toggle for Channel Break up to ( Address__c, Email__c, Phone__c)</description>
        <inlineHelpText>On/Off toggle for Channel Break up to ( Address__c, Email__c, Phone__c)</inlineHelpText>
        <label>Enable Channel Break Up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Roll_Down__c</fullName>
        <defaultValue>false</defaultValue>
        <description>On/Off toggle the Roll Down Logic for Person360 (Contact to Name__c, Address__c, Email__c, Phone__c)</description>
        <inlineHelpText>On/Off toggle the Roll Down Logic for Person360 (Contact to Name__c, Address__c, Email__c, Phone__c)</inlineHelpText>
        <label>Enable Roll Down</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Roll_Up__c</fullName>
        <defaultValue>false</defaultValue>
        <description>On/Off toggle the Roll Up Logic for Person360 (Name__c or Address__c or Email__c or Phone__c to Contact)</description>
        <inlineHelpText>On/Off toggle the Roll Up Logic for Person360 (Name__c or Address__c or Email__c or Phone__c to Contact)</inlineHelpText>
        <label>Enable Roll Up</label>
        <type>Checkbox</type>
    </fields>
    <label>Person360Muting</label>
</CustomObject>

force-app/main/default/objects/Phone__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Channel lookup field for the Contact Point object record</description>
        <label>Channel</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Phone channels must be for the same Contact record</errorMessage>
            <filterItems>
                <field>Channel__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <filterItems>
                <field>Channel__c.Type__c</field>
                <operation>notEqual</operation>
                <value>EMERCONT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated as a result of successfully being matched against a PHONE_NUMBER_FORMAT system setting regular expression.</description>
        <inlineHelpText>The country regex the phone number was successfully formatted against.</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source of the phone number.</description>
        <inlineHelpText>Please enter source of the phone number, i.e. how were the details obtained.</inlineHelpText>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Source</valueSetName>
        </valueSet>
    </fields>
    <label>Phone</label>
    <nameField>
        <label>Phone Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c.object
<CustomObject>
    <description>Store states information. Source: shop.monash</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Contact_Point_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Undefined</fullName>
        <default>true</default>
        <label>Undefined</label>
    </customValue>
    <customValue>
        <fullName>Contact supplied</fullName>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
    </customValue>
    <customValue>
        <fullName>Third party provided</fullName>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Callista</fullName>
    </customValue>
    <customValue>
        <fullName>Other Monash Platform</fullName>
        <isActive>false</isActive>
        <label>Other Monash Platform</label>
    </customValue>
    <customValue>
        <fullName>In person</fullName>
        <isActive>false</isActive>
        <label>In person</label>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
        <isActive>false</isActive>
        <label>Email</label>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <isActive>false</isActive>
        <label>Web</label>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
        <isActive>false</isActive>
        <label>Phone</label>
    </customValue>
    <description>Indicates how the information was acquired.</description>
    <masterLabel>Contact Point Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country_List_1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Samoa, American</fullName>
        <label>American Samoa</label>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
        <label>Bahamas (the)</label>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
        <label>Bolivia (Plurinational State of)</label>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <description>As per ISO 3166</description>
    <masterLabel>Country List 1</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ChannelEventUtility_Test.cls
/**
 * @description       : Test class for ChannelEventUtility.cls
 *
 * Date         Author          Modification
 * 2024-07-01   Martin Cadman   Support for EC relationship transform
 * 2024-06-13   Martin Cadman   Moved to Assert. Added Emergency Contact test and coverage.
 * 2021-07-16   P.Victoriano    Fixed Null Pointer exception [EPCP-1419]
 * 2020-10-14   Stefan Scheit   Copied from ContactPointUtility, increased code coverage
 * 2020-05-04   JM Mapanao      Added logic to populate Contact Point's Source__c field to 'Callista' when Channel__c.Source_System__c equals to 'callista'
 * 2019-08-04   Paul Victoriano Initial Version
 * 
 **/
@isTest(isParallel = true)
private class ChannelEventUtility_Test {

    static Contact contactRecord {
        get; set;
    }

    @testSetup 
    static void setupData() {
        //Enable Roll up / down and break up
        Person360Muting__c cs = Person360Muting__c.getOrgDefaults();
        cs.Enable_Roll_Down__c = true;
        cs.Enable_Roll_Up__c = true;
        cs.EnableChannelBreakUp__c = true;
        upsert cs;
        
        // Switch on mobile phone formatting.
        Feature_Switch__c fs = new Feature_Switch__c();
        fs.Format_Mobile__c = true;
        fs.Process_Emergency_Contacts__c = true;
        insert fs;
        
    }

    @isTest
    static void validate_channelContactInsert() {
        // GIVEN: Set up Channel Record
        String sChannel = '{"Source_System__c":"callista","City__c":"Melbourne","Country__c":"Australia","Deleted_In_Source__c":false,"Email__c":"ptest@email.com.test","IsDeleted":false,"Is_Processed__c":false,"Mobile_Phone__c":"0456787652","Phone_2__c":"0456787652","Phone__c":"0456787652","Post_Code__c":"3000","Primary__c":false,"Rollup_Rank__c":40.00,"Start_Date__c":"2019-04-03","State__c":"VIC","Street__c":"1 Collins Street","Type__c":"HOME","attributes":{"type":"Channel__c"}}';
        Channel__c ch = (Channel__c)JSON.deserialize(sChannel, Channel__c.class);
        //WHEN: A channel record is inserted
        Test.startTest();
        setupDataManual();
        ch.Contact__c = contactRecord.Id;
        insert ch;
        Assert.isNotNull(ch.Id, 'Error inserting Channel Record');
        Test.stopTest();
        // THEN: Address was broken up successfully
        Address__c addressCheck = [SELECT Street_Name__c FROM Address__c WHERE Contact__c = :contactRecord.Id AND Street_Name__c = :ch.Street__c LIMIT 1];
        Assert.areEqual(ch.Street__c, addressCheck.Street_Name__c, 'Error on Channel Break up Address');
        // THEN: Email was broken up successfully
        Email__c emailCheck = [SELECT Name FROM Email__c WHERE Contact__c = :contactRecord.Id AND Name = :ch.Email__c LIMIT 1];
        Assert.areEqual(ch.Email__c, emailCheck.Name, 'Error on Channel Break up Email');
        // THEN: Phone TODO
    }

    @isTest
    static void validate_channelContactUpsert() {
        //Set up Channel Record
        String sChannel = '{"City__c":"Melbourne","Country__c":"Australia","Deleted_In_Source__c":false,"Email__c":"ptest@email.com.test","IsDeleted":false,"Is_Processed__c":false,"Mobile_Phone__c":"0456787652","Phone_2__c":"0456787652","Phone__c":"0456787652","Post_Code__c":"3000","Primary__c":false,"Rollup_Rank__c":40.00,"Start_Date__c":"2019-04-03","State__c":"VIC","Street__c":"1 Collins Street","Type__c":"HOME","attributes":{"type":"Channel__c"}}';
        Channel__c ch = (Channel__c)JSON.deserialize(sChannel, Channel__c.class);
        setupDataManual();
        ch.Contact__c = contactRecord.Id;
        insert ch;
        Assert.isNotNull(ch.Id, 'Error inserting Channel Record');
        //
        Test.startTest();
        //When
        ch.Email__c = 'ptestupdate@test.com';
        update ch;
        Assert.isNotNull(ch.Id, 'Error inserting Channel Record');
        Test.stopTest();
        //Then
        Contact recCheck = [SELECT Personal_Email__c, Phone, MobilePhone, Email, MailingStreet, MailingCity, MailingState, MailingPostalCode, MailingCountry
                            FROM Contact
                            WHERE Id = :contactRecord.Id LIMIT 1];
        Assert.areEqual(ch.Email__c,
                            recCheck.Personal_Email__c,
                            'Error on Channel Break up Email');
        //System.assertEquals(ch.Phone__c,recCheck.Phone,'Error on Channel Break up Phone');
        Assert.areEqual(ch.Street__c,
                        recCheck.MailingStreet,
                        'Error on Channel Break up Address');
    }

    @isTest
    static void validate_massChannelContact() {
        List<Channel__c> channelUpdates = new List<Channel__c>();
        //Set up Channel Record
        String sChannel = '{"City__c":"Melbourne","Country__c":"Australia","Mobile_Phone__c":"0456787653","Phone_2__c":"0456787652","Phone__c":"0456787651","Post_Code__c":"3000","Primary__c":false,"Rollup_Rank__c":40.00,"Start_Date__c":"2019-04-03","State__c":"VIC","Street__c":"1 Collins Street","Type__c":"HOME","attributes":{"type":"Channel__c"}}';
        Channel__c ch = (Channel__c)JSON.deserialize(sChannel, Channel__c.class);
        setupDataManual();
        for (Integer ix = 0; ix < 10; ix++) {
            ch.Email__c = String.format('test{0}@test.com', new LIST<String> {'' + ix});
            ch.Contact__c = contactRecord.Id;
            channelUpdates.add(ch.clone());
        }
        //
        Test.startTest();
        //When
        insert channelUpdates;
        Test.getEventBus().deliver();
        Test.stopTest();
        //Then
        Assert.isNotNull(channelUpdates, 'Error Mass Insert');
        Assert.areEqual(channelUpdates.size(),[select count() from channel__c where contact__c = :contactRecord.Id]);
    }

    /**
     * quick test coverage for MIM
     */
    @isTest
    static void validate_findNewContactPointChannel() {
        setupDataManual();
        Channel__c primaryChannel = TestHelper.createChannel(contactRecord);
        insert primaryChannel;
        // WHEN: the channel is processed
        Test.startTest();
        Test.getEventBus().deliver();
        // AND: another (same data) channel is processed
        Channel__c newChannel = TestHelper.createChannel(contactRecord);
        newChannel.Deleted_In_Source__c = true;
        insert newChannel;
        Test.getEventBus().deliver();
        // AND: the primary is recalculated
        String channelField = String.valueOf(Channel__c.sobjectType.fields.Address_Key__c);
        Set<String> channelFieldNames = new Set<String> {
            channelField
        };
        // Name, Contact__c are expected in the method that follows
        List<Sobject> sobjList = [SELECT Id, Name, Contact__c, Street_Name__c, City__c, State__c, Country2__c FROM Address__c WHERE Contact__c = :contactRecord.Id];
        ChannelEventUtility.findNewContactPointChannel(sobjList, channelFieldNames);
        Test.stopTest();
    }

    /**
     * Evaluate address key generation
     */
    @isTest 
    static void validate_RetrieveChannelAddresskey() {
        // GIVEN: an address record
        Address__c addr = new Address__c();
        addr.Street_Name__c = '100 Bourke St';
        addr.City__c = 'Melbourne';
        addr.State__c = 'Victoria';
        addr.Country2__c = 'Australia';
        // WHEN: obtaining the address key
        Test.startTest();
        String testString = ChannelEventUtility.retrieveChannelAddresskey(addr);
        Test.stopTest();
        // THEN: address key was returned
        Assert.isTrue(String.isNotBlank(testString),'Address key was not generated, it is empty.');
        Assert.isTrue(testString.contains(addr.City__c),'Address key does not contain the city as part of it.');
    }

    /**
     * @description byPassAddressByMetadata Test for Bypass
     * @author pvic0002
     */
    @isTest
    static void validate_byPassAddressByMetadata() {
        Test.startTest();
        // GIVEN: an address record
        Boolean isIncluded = true;
        Address__c addr = new Address__c();
        addr.Street_Name__c = 'ADDRESS INSERTED FOR TCSI 2021 REPORTING';
        addr.City__c = 'PLEASE UPDATE TO SHOW CORRECT OS-HOME';
        addr.State__c = 'ADDRESS';
        addr.Country2__c = 'Australia';
        // WHEN: checking if address is excluded
        ChannelEventUtility evtUtil = new ChannelEventUtility(new Set<Id>(),new Set<Id>());
        // STEP1: Retrieve Metadata mapping
        evtUtil.retrieveChannelByPass();
        // STEP2: Perform validation
        isIncluded = evtUtil.breakDownBypass(addr,'Address__c');
        // THEN: expected address is excluded
        Assert.isFalse(isIncluded, 'Address was not excluded.');
        Test.stopTest();
    }
    
    @isTest
    /*
     * GIVEN
     *    A emergency contact channel
     * WHEN
     *    The channel is inserted
     * THEN
     *    An emergency contact is created and linked to the channel contact and channel itself
     **/
    static void validate_EmergencyContact() {
        // Mapped channel data 
        String sChannel = '{"City__c":"Melbourne","Country__c":"Australia","Email__c":"ectest@email.com.test","Mobile_Phone__c":"0456787111","Phone__c":"0456787222","Fullname__c":"Greg Test","Relationship_unverified__c":"Brother","Relationship__c":"Brother","Type__c":"EMERCONT","attributes":{"type":"Channel__c"}}';
        Channel__c aChannel = (Channel__c)JSON.deserialize(sChannel, Channel__c.class);
		setupDataManual();
        aChannel.Contact__c = contactRecord.Id;

        test.startTest();
        insert aChannel;
        Test.getEventBus().deliver();
        test.stopTest();

        channel__c retChannel = [select id, type__c, Relationship__c, fullname__c, country__c, contact__c from channel__c where id = :aChannel.id];
        Assert.areEqual(retChannel.type__c,'EMERCONT'); // Confirms insert
        
        Emergency_contact__c ec = [select id, channel__c, contact__c, relationship__c, emergency_contact_name__c, country__c from emergency_contact__c where channel__c = :retchannel.id][0];
        Assert.areEqual(retChannel.Relationship__c.toLowerCase(), ec.relationship__c.toLowerCase());
        Assert.areEqual(retChannel.fullname__c, ec.emergency_contact_name__c);
        Assert.areEqual(retChannel.country__c, ec.country__c);
        Assert.areEqual(retChannel.contact__c, ec.contact__c); // linked corectly
    }

    /**
     * Set up data manually
     */
    private static void setupDataManual() {
        contactRecord = new Contact();
        contactRecord.Title = 'OAM';
        contactRecord.Salutation = 'Mr.';
        contactRecord.FirstName = 'testFirstName';
        contactRecord.MiddleName = 'testMiddleName';
        contactRecord.LastName = 'testLastName';
        contactRecord.Suffix = 'testSuffix';
        contactRecord.Person_ID_unique__c = '12345678';
        insert contactRecord;
    }
}