force-app/main/default/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address built from populated fields

Uses a custom label to contain a carriage return for substitution</description>
        <formula>TRIM( 
IF (ISBLANK(Street_Name__c),&quot;&quot;,  SUBSTITUTE(Street_Name__c,  SUBSTITUTE($Label.CR,&quot;-&quot;,&quot;&quot;), &quot; &quot;) &amp; &quot;, &quot;) 
&amp;
City__c + &quot; &quot;
&amp;
State__c + &quot; &quot; 
&amp;
Post_Code__c) 
&amp;
IF (ISBLANK(TEXT(Country2__c)),&quot;&quot;, &quot;, &quot; + TEXT(Country2__c))</formula>
        <label>Full Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City/town</description>
        <inlineHelpText>Please provide the city/town of the address.</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <description>Defines how the address is classified, i.e. in which context it is used.
 Classification of the address which is used to roll-up the address to the Contact, if certain conditions are met.</description>
        <inlineHelpText>Please provide a classification of the address.</inlineHelpText>
        <label>Classification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Classification</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this address is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country2__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This defines the date until the address is valid for.</description>
        <inlineHelpText>Please provide the date the address is valid through, or leave it empty if it is not known or not end dated.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_System_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique ID used to identify records in an external system.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID used to identify records in an external system.</inlineHelpText>
        <label>External System ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether an address is active, usually when end date is in the past or the start date is in the future. This value Is automatically (by a scheduled process) set to &quot;false&quot; if End_Date__c is populated and in the past or the Start_Date__c is in the future.
If manually set/changed to &quot;True&quot; (&quot;False&quot;), then the End_Date__c is automatically removed (added with the current date).</description>
        <inlineHelpText>Please indicate whether the address is active or not (inactive).</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Global primary (by Contact), as such only a single Address__c record can be flagged as primary per Contact Lookup.
If selected manually, all other records (for the Contact) will be marked as non-primary (false)
If none are selected, the entry with the latest Start_Date__c will be automatically marked as primary.</description>
        <inlineHelpText>Please indicate whether the address is primary for this Contact.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <description>Post code of the address</description>
        <inlineHelpText>Please provide the post code of the address</inlineHelpText>
        <label>Post Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source of the address.</description>
        <inlineHelpText>Please enter source of the address, i.e. how were the details obtained.</inlineHelpText>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the address is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the address.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State of the address</description>
        <inlineHelpText>Please provide the state of the address.</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <description>Name of the street (and type)</description>
        <inlineHelpText>Please provide the street name and type, e.g. Duerdin St, Wellington Road, Margaret Court</inlineHelpText>
        <label>Street Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the address.</description>
        <inlineHelpText>Please enter the address type</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mailing</fullName>
                    <default>true</default>
                    <label>Mailing</label>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                    <isActive>false</isActive>
                    <label>Fax</label>
                </value>
                <value>
                    <fullName>Landline</fullName>
                    <isActive>false</isActive>
                    <label>Landline</label>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                    <isActive>false</isActive>
                    <label>Mobile</label>
                </value>
                <value>
                    <fullName>Postal</fullName>
                    <isActive>false</isActive>
                    <label>Postal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c.object
<CustomObject>
    <description>Store states information. Source: shop.monash</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Contact_Point_Classification.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Private</fullName>
    </customValue>
    <customValue>
        <fullName>Monash</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <description>Classification values for contact points (Email, Address, Phone)</description>
    <masterLabel>Contact Point Classification</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Contact_Point_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Undefined</fullName>
        <default>true</default>
        <label>Undefined</label>
    </customValue>
    <customValue>
        <fullName>Contact supplied</fullName>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
    </customValue>
    <customValue>
        <fullName>Third party provided</fullName>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Callista</fullName>
    </customValue>
    <customValue>
        <fullName>Other Monash Platform</fullName>
        <isActive>false</isActive>
        <label>Other Monash Platform</label>
    </customValue>
    <customValue>
        <fullName>In person</fullName>
        <isActive>false</isActive>
        <label>In person</label>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
        <isActive>false</isActive>
        <label>Email</label>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <isActive>false</isActive>
        <label>Web</label>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
        <isActive>false</isActive>
        <label>Phone</label>
    </customValue>
    <description>Indicates how the information was acquired.</description>
    <masterLabel>Contact Point Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EngageDedupeMonashAddressHandler.cls
/**
 * @author          Mark Johnson: UC Innovation
 * @description     Processes creation of addresses from processing of an Interim object.
 * @revision        10/09/2019 - Mark Johnson - Initial version
 */

public class EngageDedupeMonashAddressHandler {


    /*******************************************************************************
    * @author       Mark Johnson - UC Innovation
    * @date         10/9/2019
    * @description  Constructs list of addresses from the interim record for insertion into the system.
    *******************************************************************************/
    public void createAddressListToUpdateAndInsert(Map<String, Object> params) {

        // Processing Address for current interim-contact pair
        ucinn_ascendv2__Interim__c currentInterim = (ucinn_ascendv2__Interim__c)params.get('currentInterim');
        Integer preferredAddressNumber = 0;

        if (currentInterim.ucinn_ascendv2__Preferred_Address__c != null) {
            List<String> splitString = currentInterim.ucinn_ascendv2__Preferred_Address__c.split(' ');

            if (splitString.size() > 1 && splitString[1].isNumeric()) {
                preferredAddressNumber = Integer.valueOf(splitString[1]);
            }
        }

        Set<String> supportedAddressType = EngageDedupeUtils.getPicklistValues(Address__c.Type__c.getDescribe().getPicklistValues());

        List<Map<String, Object>> initialAddressProcessingList = createInitialProcessingWrapper(currentInterim, 3);
        Map<Integer, EngageDedupeWrapper.InterimAddressWrapper> interimAddressWrapperMap = new Map<Integer, EngageDedupeWrapper.InterimAddressWrapper>();

        for (Integer addressIndex = 0; addressIndex < initialAddressProcessingList.size(); addressIndex++) {
            Map<String, Object> addressMap = initialAddressProcessingList[addressIndex];
            String addressType = (String) addressMap.get('type');
            String addressImportId = (String) addressMap.get('addressImportId');
            Date addressDateCreated = (Date) addressMap.get('addressDateCreated');
            Date addressDateFrom = (Date) addressMap.get('addressDateFrom');
            Date addressDateLastChanged = (Date) addressMap.get('addressDateLastChanged');
            Date addressDateTo = (Date) addressMap.get('addressDateTo');
            String addressSource = (String) addressMap.get('addressSource');
            String classification;

            Integer addressNumber = addressIndex + 1;

            //Mappings as specified by Travis (ERDA). Potentially create setting to manipulate this.
            if (addressType == 'Business' || addressType == 'Ministerial' || addressType == 'Electorate' || addressType == 'GovernmentAPH') {
                addressType = null;
                classification = 'Business';
            } else if (addressType == 'Home') {
                addressType = null;
                classification = 'Private';
            } else if (addressType == 'Mailing') {
                addressType = 'Mailing';
                classification = 'Private';
            } else {
                classification = 'Private';
            }

            if (!isEmptyAddress(addressMap)) {
                Boolean isValid = validateAddress(addressMap);
                String addressLines = concatenateAddressLines(addressMap);
                Boolean isPreferred = ((preferredAddressNumber == addressNumber) && isValid);

                if (!isValid) {
                    appendManuallyReviewReason(currentInterim, 'Invalid Address ' + addressNumber);
                } else if (!String.isBlank(addressType) && !supportedAddressType.contains(addressType)) {
                    appendManuallyReviewReason(currentInterim, 'Invalid Address ' + addressNumber + ' Type');
                } else {
                    EngageDedupeWrapper.InterimAddressWrapper interimAddressWrapper = new EngageDedupeWrapper.InterimAddressWrapper(addressType,
                                                                                                                addressLines,
                                                                                                                (String) addressMap.get('city'),
                                                                                                                (String) addressMap.get('state'),
                                                                                                                (String) addressMap.get('post'),
                                                                                                                (String) addressMap.get('country'),
                                                                                                                false,
                                                                                                                isPreferred,
                                                                                                                isValid,
                                                                                                                addressImportId,
                                                                                                                addressDateCreated,
                                                                                                                addressDateFrom,
                                                                                                                addressDateLastChanged,
                                                                                                                addressDateTo,
                                                                                                                addressSource,
                                                                                                                classification);

                    interimAddressWrapperMap.put(addressNumber, interimAddressWrapper);
                }
            }
        }

        params.put('interimAddressWrapperMap', interimAddressWrapperMap);
        updateAddresses(params);
    }



    /*******************************************************************************
    * @author       Mark Johnson - UC Innovation
    * @date         10/9/2019
    * @description  Creation of wrapper used to store address.
    *******************************************************************************/
    private List<Map<String, Object>> createInitialProcessingWrapper(ucinn_ascendv2__Interim__c currentInterim, Integer namespacedFieldCount) {
        List<Map<String, Object>> initialAddressProcessingList = new List<Map<String, Object>>();

        for (Integer addressIndex = 1; addressIndex < (namespacedFieldCount + 1); addressIndex++) {
            Map<String, Object> addressWrapper = new Map<String, Object>();

            addressWrapper.put('line1', currentInterim.get('ucinn_ascendv2__Address_' + addressIndex + '_Line_1__c'));
            addressWrapper.put('line2', currentInterim.get('ucinn_ascendv2__Address_' + addressIndex + '_Line_2__c'));
            addressWrapper.put('line3', currentInterim.get('ucinn_ascendv2__Address_' + addressIndex + '_Line_3__c'));
            addressWrapper.put('line4', currentInterim.get('ucinn_ascendv2__Address_' + addressIndex + '_Line_4__c'));

            addressWrapper.put('type', currentInterim.get('ucinn_ascendv2__Address_' + addressIndex + '_Type__c'));
            addressWrapper.put('city', currentInterim.get('ucinn_ascendv2__City_' + addressIndex + '__c'));
            addressWrapper.put('state', currentInterim.get('ucinn_ascendv2__State_' + addressIndex + '__c'));
            addressWrapper.put('post', currentInterim.get('ucinn_ascendv2__Postal_Code_' + addressIndex + '__c'));
            addressWrapper.put('country', currentInterim.get('ucinn_ascendv2__Country_' + addressIndex + '__c'));
            addressWrapper.put('addressImportId', currentInterim.get('Address_' + addressIndex + '_Import_ID__c'));
            addressWrapper.put('addressDateCreated', currentInterim.get('Address_' + addressIndex + '_Date_Created__c'));
            addressWrapper.put('addressDateFrom', currentInterim.get('Address_' + addressIndex + '_Date_From__c'));
            addressWrapper.put('addressDateLastChanged', currentInterim.get('Address_' + addressIndex + '_Date_Last_Changed__c'));
            addressWrapper.put('addressDateTo', currentInterim.get('Address_' + addressIndex + '_Date_To__c'));
            //addressWrapper.put('addressSource', currentInterim.get('Address_' + addressIndex + '_Source__c'));
            addressWrapper.put('addressSource', currentInterim.get('ucinn_ascendv2__Source_File__c'));

            initialAddressProcessingList.add(addressWrapper);
        }

        return initialAddressProcessingList;
    }



    /*******************************************************************************
    * @author       Mark Johnson - UC Innovation
    * @date         10/9/2019
    * @description  Construct lists of addresses to perform DML on.
    *******************************************************************************/
    public virtual void updateAddresses(Map<String, Object> params) {
        Map<Integer, EngageDedupeWrapper.InterimAddressWrapper> interimAddressWrapperMap = (Map<Integer, EngageDedupeWrapper.InterimAddressWrapper>)params.get('interimAddressWrapperMap');

        List<Address__c> addressesToInsertStaging = new List<Address__c>();

        ucinn_ascendv2__Interim__c currentInterim = (ucinn_ascendv2__Interim__c)params.get('currentInterim');
        Contact currentContact = (Contact)params.get('currentContact');
        String recordSource = (String)params.get('recordSource');
        List<Address__c> addressesToInsert = (List<Address__c>)params.get('addressesToInsert');
        List<Address__c> addressesToUpdate = (List<Address__c>)params.get('addressesToUpdate');

        for (Integer addressNumber : interimAddressWrapperMap.keySet()) {
            EngageDedupeWrapper.InterimAddressWrapper interimAddressWrapper = interimAddressWrapperMap.get(addressNumber);

            for (Address__c curAddress : currentContact.Addresses__r) {
                if (interimAddressWrapper.addressFound != true) {
                    interimAddressWrapper.addressFound = compareAddress(interimAddressWrapper, curAddress);
                }
                if(interimAddressWrapper.addressFound == true && curAddress.Is_Active__c==false){
                	  curAddress.End_Date__c= null;
                    addressesToUpdate.add(curAddress);
                }
            }

            if (interimAddressWrapper.addressFound != true) {
                Address__c addressToInsert = setupAddressList(interimAddressWrapper, currentContact.Id, recordSource);
                addressesToInsertStaging.add(addressToInsert);
            }
        }

        if (String.isBlank(currentInterim.ucinn_ascendv2__Manual_Review_Reason__c)) {
            addressesToInsert.addAll(addressesToInsertStaging);
        }
    }


    /*******************************************************************************
    * @author       Mark Johnson - UC Innovation
    * @date         10/9/2019
    * @description  Where address validation can occur.
    *******************************************************************************/
    public static Boolean validateAddress(Map<String, Object> params) {
        //Currrently no specific validation logic for Monash.
        return true;
    }


    /*******************************************************************************
    * @author       Mark Johnson - UC Innovation
    * @date         10/9/2019
    * @description  Basic comparison to find exact duplicates previously loaded.
    *******************************************************************************/
    public static Boolean compareAddress(EngageDedupeWrapper.InterimAddressWrapper interimAddress, Address__c contactAddress) {

        //Basic comparison to find exact duplicates previously loaded.
        if (interimAddress.addressStreet == contactAddress.Street_Name__c &&
            interimAddress.addressCity == contactAddress.City__c &&
            interimAddress.addressState == contactAddress.State__c &&
            interimAddress.addressPostalCode == contactAddress.Post_Code__c &&
            interimAddress.addressCountry == contactAddress.Country2__c) {
            return true;
        } else {
            return false;
        }
    }

    /*******************************************************************************
    * @author       Mark Johnson - UC Innovation
    * @date         10/9/2019
    * @description  Creation of map used to replace pre-existing values on interim with mapped values.
    *******************************************************************************/
    public static Address__c setupAddressList(EngageDedupeWrapper.InterimAddressWrapper interimAddress, Id conId, String recSource) {
        Address__c newAddress = new Address__c();

        newAddress.Type__c = interimAddress.addressType;
        newAddress.City__c = interimAddress.addressCity;
        newAddress.State__c = interimAddress.addressState;
        newAddress.Country2__c = interimAddress.addressCountry;
        newAddress.Post_Code__c = interimAddress.addressPostalCode;
        newAddress.Street_Name__c = interimAddress.addressStreet;
        newAddress.Contact__c = conId;
        newAddress.Is_Primary__c = interimAddress.addressPreferred;
        newAddress.Is_Active__c = true;
        newAddress.External_System_ID__c = interimAddress.addressImportId;
        newAddress.CreatedDate = interimAddress.addressDateCreated;
        newAddress.Start_Date__c = interimAddress.addressDateFrom;
        newAddress.End_Date__c = interimAddress.addressDateTo;
        newAddress.LastModifiedDate = interimAddress.addressDateLastChanged;
        newAddress.Classification__c = interimAddress.classification;

        if (!String.isEmpty(interimAddress.addressSource)) {
            newAddress.Source__c = interimAddress.addressSource;
        } else {
            newAddress.Source__c = 'Internal';
        }

        //Must have creation date later than last modified date.
        EngageDedupeUtils.fixCreationDate(newAddress);

        return newAddress;
    }

    /*******************************************************************************
    * @author       Mark Johnson - UC Innovation
    * @date         10/9/2019
    * @description  Appends manual review reason to interim, when issues are found with data.
    *******************************************************************************/
    private void appendManuallyReviewReason(ucinn_ascendv2__Interim__c interimRec, String newReason) {
        interimRec.ucinn_ascendv2__Status__c = 'Manual Review';

        if (interimRec.ucinn_ascendv2__Manual_Review_Reason__c != null) {
            if (!interimRec.ucinn_ascendv2__Manual_Review_Reason__c.contains(newReason)) {
                interimRec.ucinn_ascendv2__Manual_Review_Reason__c = interimRec.ucinn_ascendv2__Manual_Review_Reason__c + ', ' + newReason;
            }
        } else {
            interimRec.ucinn_ascendv2__Manual_Review_Reason__c = newReason;
        }
    }

    /*******************************************************************************
    * @author       Mark Johnson - UC Innovation
    * @date         10/9/2019
    * @description  Returns true if an address is empty.
    *******************************************************************************/
    private Boolean isEmptyAddress(Map<String, Object> addressMap) {
        if (String.isEmpty((String) addressMap.get('line1')) &&
            String.isEmpty((String) addressMap.get('line2')) &&
            String.isEmpty((String) addressMap.get('line3')) &&
            String.isEmpty((String) addressMap.get('line4')) &&
            String.isEmpty((String) addressMap.get('type')) &&
            String.isEmpty((String) addressMap.get('city')) &&
            String.isEmpty((String) addressMap.get('state')) &&
            String.isEmpty((String) addressMap.get('post')) &&
            String.isEmpty((String) addressMap.get('country'))) {
            return true;
        }

        return false;
    }

    /*******************************************************************************
    * @author       Mark Johnson - UC Innovation
    * @date         10/9/2019
    * @description  Used to concatenate address lines, based on ERDA requirements for RE.
    *******************************************************************************/
    private String concatenateAddressLines(Map<String, Object> addressMap) {
        String addressLines = '';

        List<String> addressLinesToConcatenate = new List<String> { (String) addressMap.get('line1'),
                                                                    (String) addressMap.get('line2'),
                                                                    (String) addressMap.get('line3'),
                                                                    (String) addressMap.get('line4')
                                                                };

        for (String addressLine : addressLinesToConcatenate) {
            if (!String.isEmpty(addressLine)) {
                if (String.isEmpty(addressLines)) {
                    addressLines += addressLine.trim();
                } else {
                    addressLines += (', ' + addressLine.trim());
                }
            }
        }

        return addressLines;
    }


}