force-app/main/default/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address built from populated fields

Uses a custom label to contain a carriage return for substitution</description>
        <formula>TRIM( 
IF (ISBLANK(Street_Name__c),&quot;&quot;,  SUBSTITUTE(Street_Name__c,  SUBSTITUTE($Label.CR,&quot;-&quot;,&quot;&quot;), &quot; &quot;) &amp; &quot;, &quot;) 
&amp;
City__c + &quot; &quot;
&amp;
State__c + &quot; &quot; 
&amp;
Post_Code__c) 
&amp;
IF (ISBLANK(TEXT(Country2__c)),&quot;&quot;, &quot;, &quot; + TEXT(Country2__c))</formula>
        <label>Full Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Channel lookup field for the Contact Point object record</description>
        <label>Channel</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Address channels must be for the same Contact record</errorMessage>
            <filterItems>
                <field>Channel__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <filterItems>
                <field>Channel__c.Type__c</field>
                <operation>notEqual</operation>
                <value>EMERCONT</value>
            </filterItems>
            <infoMessage>Search for all non-emergency contact channels for this contact</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City/town</description>
        <inlineHelpText>Please provide the city/town of the address.</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this address is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A soft delete flag. An overnight purge process removes these records.</description>
        <inlineHelpText>A soft delete flag, queued for purging</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <description>Post code of the address</description>
        <inlineHelpText>Please provide the post code of the address</inlineHelpText>
        <label>Post Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source of the address.</description>
        <inlineHelpText>Please enter source of the address, i.e. how were the details obtained.</inlineHelpText>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the address is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the address.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c.object
<CustomObject>
    <description>Communication Channels</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deleted_In_Source__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Record has been deleted in the source system.</description>
        <inlineHelpText>Record has been deleted in the source system.</inlineHelpText>
        <label>Deleted In Source</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System Field - indicates that the record was processed into Contact Point records</description>
        <inlineHelpText>System Field - indicates that the record was processed into Contact Point records</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone_2__c</fullName>
        <label>Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Channel lookup field for the Contact Point object record</description>
        <inlineHelpText>Lookup to Channel for Callista sourced records</inlineHelpText>
        <label>Channel</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Email channels must be for the same Contact record</errorMessage>
            <filterItems>
                <field>Channel__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <filterItems>
                <field>Channel__c.Type__c</field>
                <operation>notEqual</operation>
                <value>EMERCONT</value>
            </filterItems>
            <infoMessage>Search for all non-emergency contact channels for this contact</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this email address is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Addresses</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Deleted In Source from Channel</description>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source of the email address.</description>
        <inlineHelpText>Please enter source of the email address, i.e. how were the details obtained.</inlineHelpText>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the email address is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the email address</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Email</label>
    <nameField>
        <label>Email Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person360Muting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>On/Off Settings for Person360</description>
    <fields>
        <fullName>EnableChannelBreakUp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>On/Off toggle for Channel Break up to ( Address__c, Email__c, Phone__c)</description>
        <inlineHelpText>On/Off toggle for Channel Break up to ( Address__c, Email__c, Phone__c)</inlineHelpText>
        <label>Enable Channel Break Up</label>
        <type>Checkbox</type>
    </fields>
    <label>Person360Muting</label>
</CustomObject>

force-app/main/default/objects/Phone__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Channel lookup field for the Contact Point object record</description>
        <label>Channel</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Phone channels must be for the same Contact record</errorMessage>
            <filterItems>
                <field>Channel__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <filterItems>
                <field>Channel__c.Type__c</field>
                <operation>notEqual</operation>
                <value>EMERCONT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this phone number is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Phone Numbers</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated as a result of successfully being matched against a PHONE_NUMBER_FORMAT system setting regular expression.</description>
        <inlineHelpText>The country regex the phone number was successfully formatted against.</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>Phones</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A soft delete flag on the record. 

An overnight purge process removes the record.</description>
        <inlineHelpText>Soft deleted, queued for purging</inlineHelpText>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source of the phone number.</description>
        <inlineHelpText>Please enter source of the phone number, i.e. how were the details obtained.</inlineHelpText>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Source</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the phone number is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the phone number</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <label>Phone Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c.object
<CustomObject>
    <description>Store states information. Source: shop.monash</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Contact_Point_Source.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Undefined</fullName>
        <default>true</default>
        <label>Undefined</label>
    </customValue>
    <customValue>
        <fullName>Contact supplied</fullName>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
    </customValue>
    <customValue>
        <fullName>Third party provided</fullName>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
    </customValue>
    <customValue>
        <fullName>Callista</fullName>
    </customValue>
    <customValue>
        <fullName>Other Monash Platform</fullName>
        <isActive>false</isActive>
        <label>Other Monash Platform</label>
    </customValue>
    <customValue>
        <fullName>In person</fullName>
        <isActive>false</isActive>
        <label>In person</label>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
        <isActive>false</isActive>
        <label>Email</label>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <isActive>false</isActive>
        <label>Web</label>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
        <isActive>false</isActive>
        <label>Phone</label>
    </customValue>
    <description>Indicates how the information was acquired.</description>
    <masterLabel>Contact Point Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country_List_1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Samoa, American</fullName>
        <label>American Samoa</label>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
        <label>Bahamas (the)</label>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
        <label>Bolivia (Plurinational State of)</label>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <description>As per ISO 3166</description>
    <masterLabel>Country List 1</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Person360PurgeBatch_Test.cls
/**
 * @description     Test class for Person360PurgeBatch.cls
 * @author          J.Mapanao
 * @date            20.APR.2020
 * 
 * @revision
 *                  20.APR.2020 - J.Mapanao - Initial Created
 */
@isTest(isParallel=false) // due to schedule evaluations
private class Person360PurgeBatch_Test {

    @testSetup static void setupData() {
        //Enable Roll up / down and break up
        Person360Muting__c cs = Person360Muting__c.getOrgDefaults();
        cs.EnableChannelBreakUp__c = false;
        upsert cs;
    }

    static testMethod void testDeleteContact() {
        List<Contact> contactList = new List<Contact>();

        // Create test contact data
        for(Integer i = 0 ; i < 25 ; i++) {
            Contact tempContact = createContactStub();
            tempContact.FirstName = 'TestFirstName' + i;
            tempContact.MiddleName = 'TestMiddleName' + i;
            tempContact.LastName = 'TestLastName' + i;
            tempContact.Person_ID_unique__c = 'UniquePID' + i;
            contactList.add(tempContact);
        }
        insert contactList;
        List<Contact> queryAllContacts = [
            SELECT Id, FirstName, MiddleName, LastName,
                    (SELECT Id FROM Addresses__r),
                    (SELECT Id FROM Phones__r),
                    (SELECT Id FROM Emails__r)
            FROM Contact
            WHERE Id IN: contactList
        ];
        for (Contact con : queryAllContacts) {
            System.assertNotEquals(null, con.Addresses__r);
            System.assertNotEquals(null, con.Phones__r);
            System.assertNotEquals(null, con.Emails__r);
        }

        // Update some of the test contact data
        // and set Deleted_In_Source__c = true
        List<Contact> contactsToDeleteByBatch = new List<Contact>();
        for (Integer i = 7 ; i < 15 ; i++) {
            Contact tempContact = new Contact(
                Id = queryAllContacts[i].Id,
                Deleted_In_Source__c = true
            );
            contactsToDeleteByBatch.add(tempContact);
        }
        update contactsToDeleteByBatch;
        Test.startTest();
        Database.executeBatch(new Person360PurgeBatch());
        Test.stopTest();
        
        LogUtilityException.debug('Person360PurgeBatch finished.');
        List<Contact> contactsLeft = [SELECT Id FROM Contact];
        System.assertEquals(17, contactsLeft.size(), 'ERROR... Some of the contacts not been deleted.');
    }

    /**
     * Make sure the Person360PurgeBatch.cls batch apex will pick up
     * and delete all Address__c records WHERE Is_Deleted__c = true
     */
    static testMethod void testDeleteAddress() {
        List<Contact> contactList = new List<Contact>();

        // Create test data for contact records and its contact points
        // like Address, Email, and Phone (via contact trigger rolldown)
        for(Integer i = 0 ; i < 15 ; i++) {
            Contact tempContact = createContactStub();
            tempContact.FirstName = 'TestFirstName' + i;
            tempContact.MiddleName = 'TestMiddleName' + i;
            tempContact.LastName = 'TestLastName' + i;
            tempContact.Person_ID_unique__c = 'UniquePID' + i;
            contactList.add(tempContact);
        }
        insert contactList;
        List<Contact> queryAllContacts = [
            SELECT Id, FirstName, MiddleName, LastName,
                    (SELECT Id FROM Addresses__r),
                    (SELECT Id FROM Phones__r),
                    (SELECT Id FROM Emails__r)
            FROM Contact
            WHERE Id IN: contactList
        ];
        for (Contact con : queryAllContacts) {
            System.assertNotEquals(null, con.Addresses__r);
            System.assertNotEquals(null, con.Phones__r);
            System.assertNotEquals(null, con.Emails__r);
        }

        // Create test data of Channel
        List<Channel__c> channels = new List<Channel__c>();
        for (Contact con : queryAllContacts) {
            channels.add(
                new Channel__c(
                    City__c = 'Melbourne',
                    Country__c = 'Australia',
                    Deleted_In_Source__c = true,
                    Email__c = 'ptest@monash.edu.test',
                    Is_Processed__c = false,
                    Mobile_Phone__c = '0456787652',
                    Phone_2__c = '0456787652',
                    Phone__c = '0456787652',
                    Post_Code__c = '3000',
                    Start_Date__c = Date.today().addDays(-150),
                    State__c = 'VIC',
                    Street__c = '1 Collins Street',
                    Type__c = 'HOME',
                    Contact__c = con.Id
                )
            );
        }
        insert channels;

        List<Address__c> addressList = new List<Address__c>();
        for (Channel__c channel : channels) {
            addressList.add(
                new Address__c(
                    Contact__c = channel.Contact__c,
                    Street_Name__c = channel.Street__c,
                    City__c = channel.City__c,
                    State__c = channel.State__c,
                    Post_Code__c = channel.Post_Code__c,
                    Country2__c = channel.Country__c,
                    Start_Date__c = channel.Start_Date__c,
                    End_Date__c = null,
                    Is_Active__c = false,
                    Is_Primary__c = false,
                    Classification__c = 'Private',
                    Source__c = 'Undefined',
                    Is_Deleted__c = true,
                    Channel__c = channel.Id
                )
            );
        }
        TriggerCommon.disableTrigger('Address__c');
        insert addressList;
        TriggerCommon.enableTrigger('Address__c');

        Test.startTest();
        Database.executeBatch(new Person360PurgeBatch(1));
        Test.stopTest();
        List<Address__c> checkAddressList = [SELECT Id FROM Address__c WHERE Is_Deleted__c = true];
        System.assertEquals(0, checkAddressList.size(), 'ERROR... Addresses where Is_Deleted__c = true not deleted.');
    }

    /**
     * Make sure the Person360PurgeBatch.cls batch apex will pick up
     * and delete all Phone__c records WHERE Is_Deleted__c = true
     */
    static testMethod void testDeletePhone() {
        List<Contact> contactList = new List<Contact>();

        // Create test data for contact records and its contact points
        // like Address, Email, and Phone (via contact trigger rolldown)
        for(Integer i = 0 ; i < 15 ; i++) {
            Contact tempContact = createContactStub();
            tempContact.FirstName = 'TestFirstName' + i;
            tempContact.MiddleName = 'TestMiddleName' + i;
            tempContact.LastName = 'TestLastName' + i;
            tempContact.Person_ID_unique__c = 'UniquePID' + i;
            contactList.add(tempContact);
        }
        insert contactList;
        List<Contact> queryAllContacts = [
            SELECT Id, FirstName, MiddleName, LastName,
                    (SELECT Id FROM Addresses__r),
                    (SELECT Id FROM Phones__r),
                    (SELECT Id FROM Emails__r)
            FROM Contact
            WHERE Id IN: contactList
        ];
        for (Contact con : queryAllContacts) {
            System.assertNotEquals(null, con.Addresses__r);
            System.assertNotEquals(null, con.Phones__r);
            System.assertNotEquals(null, con.Emails__r);
        }

        // Create test data of Channel
        List<Channel__c> channels = new List<Channel__c>();
        for (Contact con : queryAllContacts) {
            channels.add(
                new Channel__c(
                    City__c = 'Melbourne',
                    Country__c = 'Australia',
                    Deleted_In_Source__c = true,
                    Email__c = 'ptest@monash.edu.test',
                    Is_Processed__c = false,
                    Mobile_Phone__c = '0456787652',
                    Phone_2__c = '0456787652',
                    Phone__c = '0456787652',
                    Post_Code__c = '3000',
                    Start_Date__c = Date.today().addDays(-150),
                    State__c = 'VIC',
                    Street__c = '1 Collins Street',
                    Type__c = 'HOME',
                    Contact__c = con.Id
                )
            );
        }
        insert channels;

        List<Phone__c> phoneList = new List<Phone__c>();
        for (Channel__c channel : channels) {
            phoneList.add(
                new Phone__c(
                    Name = String.valueOf(channel.Mobile_Phone__c),
                    Contact__c = channel.Contact__c,
                    Start_Date__c = channel.Start_Date__c,
                    End_Date__c = null,
                    Classification__c = 'Private',
                    Source__c = 'Undefined',
                    Is_Primary__c = false,
                    Is_Active__c = false,
                    Is_Deleted__c = true,
                    Channel__c = channel.Id
                )
            );
        }
        TriggerCommon.disableTrigger('Phone__c');
        insert phoneList;
        TriggerCommon.enableTrigger('Phone__c');

        Test.startTest();
        Database.executeBatch(new Person360PurgeBatch(2));
        Test.stopTest();
        List<Phone__c> checkPhoneList = [SELECT Id FROM Phone__c WHERE Is_Deleted__c = true];
        System.assertEquals(0, checkPhoneList.size(), 'ERROR... Phones where Is_Deleted__c = true not deleted.');
    }

    /**
     * Make sure the Person360PurgeBatch.cls batch apex will pick up
     * and delete all Email__c records WHERE Is_Deleted__c = true
     */
    static testMethod void testDeleteEmail() {
        List<Contact> contactList = new List<Contact>();

        // Create test data for contact records and its contact points
        // like Address, Email, and Phone (via contact trigger rolldown)
        for(Integer i = 0 ; i < 15 ; i++) {
            Contact tempContact = createContactStub();
            tempContact.FirstName = 'TestFirstName' + i;
            tempContact.MiddleName = 'TestMiddleName' + i;
            tempContact.LastName = 'TestLastName' + i;
            tempContact.Person_ID_unique__c = 'UniquePID' + i;
            contactList.add(tempContact);
        }
        insert contactList;
        List<Contact> queryAllContacts = [
            SELECT Id, FirstName, MiddleName, LastName,
                    (SELECT Id FROM Addresses__r),
                    (SELECT Id FROM Phones__r),
                    (SELECT Id FROM Emails__r)
            FROM Contact
            WHERE Id IN: contactList
        ];
        for (Contact con : queryAllContacts) {
            System.assertNotEquals(null, con.Addresses__r);
            System.assertNotEquals(null, con.Phones__r);
            System.assertNotEquals(null, con.Emails__r);
        }

        // Create test data of Channel
        List<Channel__c> channels = new List<Channel__c>();
        for (Contact con : queryAllContacts) {
            channels.add(
                new Channel__c(
                    City__c = 'Melbourne',
                    Country__c = 'Australia',
                    Deleted_In_Source__c = true,
                    Email__c = 'ptest@monash.edu.test',
                    Is_Processed__c = false,
                    Mobile_Phone__c = '0456787652',
                    Phone_2__c = '0456787652',
                    Phone__c = '0456787652',
                    Post_Code__c = '3000',
                    Start_Date__c = Date.today().addDays(-150),
                    State__c = 'VIC',
                    Street__c = '1 Collins Street',
                    Type__c = 'HOME',
                    Contact__c = con.Id
                )
            );
        }
        insert channels;

        List<Email__c> emailList = new List<Email__c>();
        for (Channel__c channel : channels) {
            emailList.add(
                new Email__c(
                    Name = channel.Email__c,
                    Contact__c = channel.Contact__c,
                    Start_Date__c = channel.Start_Date__c,
                    End_Date__c = null,
                    Classification__c = 'Private',
                    Source__c = 'Undefined',
                    Is_Primary__c = false,
                    Is_Active__c = false,
                    Is_Deleted__c = true,
                    Channel__c = channel.Id
                )
            );
        }
        TriggerCommon.disableTrigger('Email__c');
        insert emailList;
        TriggerCommon.enableTrigger('Email__c');

        Test.startTest();
        Database.executeBatch(new Person360PurgeBatch(3));
        Test.stopTest();
        List<Email__c> checkEmailList = [SELECT Id FROM Email__c WHERE Is_Deleted__c = true];
        System.assertEquals(0, checkEmailList.size(), 'ERROR... Emails where Is_Deleted__c = true not deleted.');
    }

    static testmethod void testPerson360Purge_ScheduleAndUnSchedule() {
        Person360PurgeBatch myBatch = new Person360PurgeBatch();
        myBatch.schedule();
        Test.StartTest();
        myBatch.unschedule();
        Test.stopTest();
    }

    /**
     * Set up data manually
     */
    private static Contact createContactStub() {

        Contact temp_Contact = new Contact();
        temp_Contact.Birthdate = Date.today().addYears(- 20);
        temp_Contact.Citizenship__c = 'INTERNATIONAL';
        temp_Contact.Citizenship_Code__c = '4';
        temp_Contact.Residency_Status__c = 'Australian Permanent Resident';
        temp_Contact.Email = 'test@test.com';
        temp_Contact.Personal_Email__c = 'test@test.com';
        temp_Contact.Monash_Email_Address__c = 'test@test.com';
        temp_Contact.Business_Email_Address__c = 'test@test.com';
        temp_Contact.Title = 'OAM';
        temp_Contact.Salutation = 'Mr.';
        temp_Contact.FirstName = 'testFirstName';
        temp_Contact.MiddleName = 'testMiddleName';
        temp_Contact.LastName = 'testLastName';
        temp_Contact.Suffix = 'testSuffix';
        temp_Contact.Gender__c = 'None';
        temp_Contact.Phone = '+61390008000';
        temp_Contact.MobilePhone = '+61400111222';
        temp_Contact.HomePhone = '+61390008001';
        temp_Contact.OtherPhone = '+61390008002';
        temp_Contact.AssistantPhone = '+61390008003';
        temp_Contact.Fax = '+61390008999';
        temp_Contact.MailingStreet = '350 Bourke Street';
        temp_Contact.MailingCity = 'Melbourne';
        temp_Contact.MailingState = 'Victoria';
        temp_Contact.MailingPostalCode = '3000';
        temp_Contact.MailingCountry = 'Australia';
        temp_Contact.OtherStreet = '111 Bourke Street';
        temp_Contact.OtherCity = 'Melbourne';
        temp_Contact.OtherState = 'Victoria';
        temp_Contact.OtherPostalCode = '3000';
        temp_Contact.OtherCountry = 'Australia';

        return temp_Contact;
    }
}