force-app/main/default/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <description>Defines how the address is classified, i.e. in which context it is used.
 Classification of the address which is used to roll-up the address to the Contact, if certain conditions are met.</description>
        <inlineHelpText>Please provide a classification of the address.</inlineHelpText>
        <label>Classification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Classification</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this address is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the address.</description>
        <inlineHelpText>Please enter the address type</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mailing</fullName>
                    <default>true</default>
                    <label>Mailing</label>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                    <isActive>false</isActive>
                    <label>Fax</label>
                </value>
                <value>
                    <fullName>Landline</fullName>
                    <isActive>false</isActive>
                    <label>Landline</label>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                    <isActive>false</isActive>
                    <label>Mobile</label>
                </value>
                <value>
                    <fullName>Postal</fullName>
                    <isActive>false</isActive>
                    <label>Postal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliation__c.object
<CustomObject>
    <description>Links a person (Contact) with an entity, e.g. company (or organisational unit), club, school etc.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The contact (person) of the affiliation to an account (organisation)</description>
        <inlineHelpText>Please provide the account of the affiliation.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact (person) of the affiliation to an account (organisation)</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFL-{0000000}</displayFormat>
        <label>Affiliation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Point_Affiliation__c.object
<CustomObject>
    <description>Link between a contact point (Email, Phone, Address) and Affiliation of a person (Contact)</description>
    <fields>
        <fullName>Affiliation__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>The affiliation a contact point refers to.</description>
        <inlineHelpText>Please provide the affiliation record the contact point should be linked to.</inlineHelpText>
        <label>Affiliation</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Affiliation must be for the same Contact</errorMessage>
            <filterItems>
                <field>Affiliation__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Affiliation__c</referenceTo>
        <relationshipLabel>Contact Point Affiliations</relationshipLabel>
        <relationshipName>Contact_Point_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <description>The type or classification of the contact point this CPA record is linked to,

Note that for legacy mixed records this will show only 1 type, the first identified</description>
        <formula>CASE(Type__c,
&quot;Phone&quot;, text(Phone__r.Type__c),
&quot;Email&quot;, text(Email__r.Classification__c),
&quot;Address&quot;, text(Address__r.Type__c), 
Type__c)</formula>
        <inlineHelpText>The classification of the linked-to contact point</inlineHelpText>
        <label>Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The Contact the contact point affiliation relates to.</description>
        <inlineHelpText>Please provide the contact for the contact point affiliation.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Point Affiliations</relationshipLabel>
        <relationshipName>Contact_Point_Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The email this contact point refers to. One of phone, email, address, and social is mandatory.</description>
        <inlineHelpText>Please provide an email for the affiliation.</inlineHelpText>
        <label>Email</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Email address must be a child of the Contact</errorMessage>
            <filterItems>
                <field>Email__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Email__c</referenceTo>
        <relationshipLabel>Contact Point Affiliations</relationshipLabel>
        <relationshipName>Contact_Point_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The phone this contact point refers to. One of phone, email, address, and social is mandatory.</description>
        <inlineHelpText>Please provide the phone this contact point refers to.</inlineHelpText>
        <label>Phone</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Phone number number be a child of the Contact</errorMessage>
            <filterItems>
                <field>Phone__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Contact Point Affiliations</relationshipLabel>
        <relationshipName>Contact_Point_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of contact point record this CPA is linked to  - Address, Phone or Email.

Note that this will not support the legacy mixed contact point affiliation records and will report on the first found.</description>
        <formula>If (not isblank(Phone__c), &quot;Phone&quot;,
If (not isblank(Email__c), &quot;Email&quot;,
If (not isblank(Address__c), &quot;Address&quot;, &quot;Invalid&quot;)))</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Contact Point Affiliation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Point Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <description>Defines how the email address is classified, i.e. in which context it is used.
 Classification of the email which is used to roll-up the email address to the Contact, if certain conditions are met.</description>
        <inlineHelpText>Please provide a classification of the email address.</inlineHelpText>
        <label>Classification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Classification</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this email address is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Addresses</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Email</label>
    <nameField>
        <label>Email Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Feature_Switch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Allow features to be enabled or disabled based on a Boolean switch</description>
    <fields>
        <fullName>Generate_UK_for_CPA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Populate the composite key on contact point affiliations, enforcing a single CP relationship with an Affiliation. &quot;Puesdo-polymorphic&quot;</description>
        <inlineHelpText>Populate the composite key on contact point affiliations</inlineHelpText>
        <label>Generate UK for CPA</label>
        <type>Checkbox</type>
    </fields>
    <label>Feature Switch</label>
</CustomObject>

force-app/main/default/objects/Phone__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <description>Defines how the phone number is classified, i.e. in which context it is used.
 Classification of the phone which is used to roll-up the phone number to the Contact, if certain conditions are met.</description>
        <inlineHelpText>Please provide a classification of the phone number</inlineHelpText>
        <label>Classification</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Contact_Point_Classification</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this phone number is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Phone Numbers</relationshipLabel>
        <relationshipName>Phones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the phone number.

The order of the values is important as it drives some of the primary record selection behaviour.</description>
        <inlineHelpText>Please enter the phone number type</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Landline</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Undefined</fullName>
                    <default>true</default>
                    <label>Undefined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Phone</label>
    <nameField>
        <label>Phone Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Contact_Point_Classification.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Private</fullName>
    </customValue>
    <customValue>
        <fullName>Monash</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <description>Classification values for contact points (Email, Address, Phone)</description>
    <masterLabel>Contact Point Classification</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactPointAffiliationServices.cls
public class ContactPointAffiliationServices {
    
   /*
    * @author Martin Cadman
    * @date   29.05.2023
    * @description Build a human friend name for a contact point affiliation.
    *              The name consists of fields from the vaious relationships. It is not unique but should be helpful when viewed per contact
    *              CRM Id + Account OrgUnit + Affiliation Type + CPA Type
    */
	public class buildName extends TriggerAbstract {
		Set<id> contactIds = new Set<id>();
		Set<id> affiliationIds = new Set<id>();
	
		public override void process(SObject rec) {
			Contact_Point_Affiliation__c newCPA = (Contact_Point_Affiliation__c)rec;

            records.add(newCPA);
            contactIds.add(newCPA.Contact__c);
            affiliationIds.add(newCPA.Affiliation__c);
        }

        public override void process(SObject rec, SObject oldRec) {
			Contact_Point_Affiliation__c newCPA = (Contact_Point_Affiliation__c)rec;

            records.add(newCPA);
            contactIds.add(newCPA.Contact__c);
            affiliationIds.add(newCPA.Affiliation__c);
        }
        
        public override void execute() {   
            try {
                if (!records.isEmpty()) {
                    Set<Contact_Point_Affiliation__c> sCPA = new Set<Contact_Point_Affiliation__c>((List<Contact_Point_Affiliation__c>)records);

//                    This approach did not work for new records, so individual queries are required
//                    map<id, Contact_Point_Affiliation__c> mCPA = new Map<id, Contact_Point_Affiliation__c>([select id, name, affiliation__c, affiliation__r.recordtype.name, contact__r.crm_id__c, affiliation__r.account__r.Callista_Org_Unit_Code__c, 
//                                                                      type__c, classification__c
//                                                                 from Contact_Point_Affiliation__c where id in :sCPA]);

                    Map<id, Contact> mc = new Map<id, Contact>([select id, crm_id__c from contact where id in :contactIds]);
                    Map<id, Affiliation__c> ma = new Map<id, Affiliation__c>([select id, account__r.Callista_Org_Unit_Code__c, recordtype.name 
                                                 from affiliation__c 
                                                where id IN :affiliationIds]);
                    
                    for (Contact_Point_Affiliation__c uCPA : sCPA) {
                        if (mc.containsKey(uCPA.contact__c)) {
                            uCPA.name = mc.get(uCPA.contact__c).crm_id__c;
                        } 
                        if (ma.containsKey(uCPA.affiliation__c)) {
                            // Org Unit may not always be relevant to the affiliation
                            String ou = ma.get(uCPA.affiliation__c).account__r.Callista_Org_Unit_Code__c;
                            If (String.isNotEmpty(ou)) {
                            	uCPA.name += '/' + ou;
                            }
                        	uCPA.name += '/' + ma.get(uCPA.affiliation__c).recordtype.name;
                        } 

                        if (cpaIsMixed(uCPA)) {
                            uCPA.name += '/Mixed';
                        } else { 
                            uCPA.name += '/' + uCPA.type__c;
                        }
                    }                    
                }
			} catch (Exception ex) {
				logUtilityException.logException(ex);
            }        
        }
    }

   /*
    * @author Martin Cadman
    * @date   29.05.2023
    * @description If the feature switch is enabled, this before-trigger method will generate a unique key based on the affiltion and an individual contact point.
    *              The feature switch also stops the validation rule from firing, limiting the number of CP lookups to one.
    */
	public class buildUniqueId extends TriggerAbstract {
		Feature_Switch__c fs = Feature_Switch__c.getInstance();

		public override void process(SObject rec) {
			if (fs.Generate_UK_for_CPA__c) {
    			records.add(rec);
            }
        }

        public override void process(SObject rec, SObject oldRec) {
			Contact_Point_Affiliation__c newCPA = (Contact_Point_Affiliation__c)rec;
            Contact_Point_Affiliation__c oldCPA = (Contact_Point_Affiliation__c)oldRec;
            
            if (fs.Generate_UK_for_CPA__c) {
                if (CommonUtilities.fieldHasChanged('phone__c', newCPA, oldCPA) ||
                    CommonUtilities.fieldHasChanged('email__c', newCPA, oldCPA) ||
                    CommonUtilities.fieldHasChanged('address__c', newCPA, oldCPA) ||
                    CommonUtilities.fieldHasChanged('affiliation__c', newCPA, oldCPA) ||
                    String.isEmpty(newCPA.composite_key__c)) {
	                records.add(newCPA);
                }
            }
        }

        public override void execute() {   
            try {
                if (!records.isEmpty()) {
                    Set<Contact_Point_Affiliation__c> CPAs = new Set<Contact_Point_Affiliation__c>((List<Contact_Point_Affiliation__c>)records);
                    for (Contact_Point_Affiliation__c cpa : CPAs) {
						cpa.composite_Key__c = String.valueOf(cpa.affiliation__c);
                        Switch on cpaGetType(cpa) {
                            when 'phone' {
								cpa.composite_Key__c += cpa.phone__c;
                            }
                            when 'address' {
								cpa.composite_Key__c += cpa.address__c;
                            }
                            when 'email' {
                                cpa.composite_Key__c += cpa.email__c;
                            }
                            when else {
                                cpa.composite_Key__c = cpa.id; // This will never happen
                            }
                        }
                    }                        
                }
			} catch (Exception ex) {
				logUtilityException.logException(ex);
            }
        }
    }
    
    
    // Helper to determine the type of CPA a record is based
    public static String cpaGetType (Contact_Point_Affiliation__c cpa) {
        if (cpaIsType(cpa,'email__c'))  {return 'email';}
        if (cpaIsType(cpa,'phone__c')) {return 'phone';}
        if (cpaIsType(cpa,'address__c')) {return 'address';}
        return '';
    }

    // Helper to determine the type of CPA a record is based on field population
    public static boolean cpaIsType (Contact_Point_Affiliation__c cpa, String field) {
        if (String.isNotEmpty((String)cpa.get(field))) {
            return true;
		}
        return false;
    }
    
	// Helper to determine if the CPA record mixed (legacy)
    public static boolean cpaIsMixed (Contact_Point_Affiliation__c cpa) {
		Integer n = 0;
        if (cpaIsType(cpa,'email__c'))  {n++;}
        if (cpaIsType(cpa,'phone__c')) {n++;}
        if (cpaIsType(cpa,'address__c')) {n++;}
        return (n>1);
    }
}