force-app/main/default/objects/Affiliation__c.object
<CustomObject>
    <description>Links a person (Contact) with an entity, e.g. company (or organisational unit), club, school etc.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The contact (person) of the affiliation to an account (organisation)</description>
        <inlineHelpText>Please provide the account of the affiliation.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact (person) of the affiliation to an account (organisation)</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position_Level__c</fullName>
        <description>To apply an additional level of detail to the affiliation</description>
        <inlineHelpText>To apply an additional level of detail to the affiliation</inlineHelpText>
        <label>Position Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Committee Member</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Alumni</fullName>
                </value>
                <value>
                    <fullName>Alumni No Degree</fullName>
                </value>
                <value>
                    <fullName>Associate Dean</fullName>
                </value>
                <value>
                    <fullName>Senior Leader</fullName>
                </value>
                <value>
                    <fullName>Founder/Entrepreneur</fullName>
                </value>
                <value>
                    <fullName>Senior Professional</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Estate Bequestor</fullName>
                </value>
                <value>
                    <fullName>Estate Executor</fullName>
                </value>
                <value>
                    <fullName>Estate Testator</fullName>
                </value>
                <value>
                    <fullName>MITI placements</fullName>
                </value>
                <value>
                    <fullName>WIL placements</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the email address is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the affiliation</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFL-{0000000}</displayFormat>
        <label>Affiliation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <recordTypes>
        <fullName>Alumni</fullName>
        <active>true</active>
        <description>Alumni or former student of Monash</description>
        <label>Alumni</label>
    </recordTypes>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>An applicant for a course or program at Monash</description>
        <label>Applicant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Achieved__c</fullName>
        <label>Date Achieved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Faculty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>(Managing/owning) faculty of the qualification (for university degrees).
Note: relevant for Monash Tertiary Education only.</description>
        <label>Faculty</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Faculty</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Qualifications (Organization)</relationshipLabel>
        <relationshipName>Contact_Qualifications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Level of Completion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ATTEMPTED BUT WAS NOT COMPLETED</fullName>
                </value>
                <value>
                    <fullName>CURRENTLY STUDYING</fullName>
                </value>
                <value>
                    <fullName>DISCONTINUED</fullName>
                </value>
                <value>
                    <fullName>SUCCESSFULLY COMPLETED AND OBTAINED</fullName>
                </value>
                <value>
                    <fullName>Completed Alternative Exit</fullName>
                    <isActive>false</isActive>
                    <label>Completed Alternative Exit</label>
                </value>
                <value>
                    <fullName>Completed not graduated</fullName>
                    <isActive>false</isActive>
                    <label>Completed not graduated</label>
                </value>
                <value>
                    <fullName>Graduated</fullName>
                    <isActive>false</isActive>
                    <label>Graduated</label>
                </value>
                <value>
                    <fullName>Graduated but no Grad Date in Callista</fullName>
                    <isActive>false</isActive>
                    <label>Graduated but no Grad Date in Callista</label>
                </value>
                <value>
                    <fullName>Study Abroad/CIC</fullName>
                    <isActive>false</isActive>
                    <label>Study Abroad/CIC</label>
                </value>
                <value>
                    <fullName>WILL BE COMPLETED BY ADMISSION</fullName>
                    <isActive>false</isActive>
                    <label>WILL BE COMPLETED BY ADMISSION</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Faculty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Faculty record (via Org Unit)</description>
        <label>Faculty</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Account.Callista_Org_Unit_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Faculty</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Monash Organisation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Course start date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Course is Active ? Active/Inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attempt__c.object
<CustomObject>
    <description>Course attempt represents the courses a Contact is related to.</description>
    <fields>
        <fullName>Achieved_Credit_Points__c</fullName>
        <description>Total credit points achieved</description>
        <inlineHelpText>Total credit points achieved</inlineHelpText>
        <label>Achieved CP</label>
        <summarizedField>Unit_Attempt__c.Achieved_Credit_Points__c</summarizedField>
        <summaryFilterItems>
            <field>Unit_Attempt__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed, Duplicate</value>
        </summaryFilterItems>
        <summaryForeignKey>Unit_Attempt__c.Course_Attempt__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Reference to the contact who pursues this course</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to the course (incl. version) of the course attempt</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Value does not match the type of allowed courses an attempt record can be related to.</errorMessage>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Course-All</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short Course</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short_Course</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Course Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Attempts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Monash_Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Monash Account record where Prospective Student&apos;s Roles will be associated with.</description>
    <fields>
        <fullName>Id__c</fullName>
        <description>Id of Global Monash Account</description>
        <label>Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Global Monash Account</label>
</CustomObject>

force-app/main/default/objects/Unit_Attempt__c.object
<CustomObject>
    <description>Unit (Subject) enrolment of the student.</description>
    <fields>
        <fullName>Achieved_Credit_Points__c</fullName>
        <description>Credit points granted if the unit attempt was passed</description>
        <label>Achieved Credit Points</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <description>Parent course attempt which the unit attempt is associated with.</description>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Unit Attempts</relationshipLabel>
        <relationshipName>Unit_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Unit Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AffiliationService.cls
/**
 * @author       Ajitabh
 * @date         22.Nov.2016
 * @description  Service class for Affiliation creation
 * @revision     22.Nov.2016    Ajitabh,  - Initial version
 *               17.Aug.2022   Inderpal      added row lock handling PENGAGE-2392
 */
public class AffiliationService {
     public static void createAffiliationforCDCExp(list<sObject> sobjectList, List<Affiliation__c> affliationList, Integer retryCount){
        if(retryCount == 0){
			Schema.SObjectType sObjectType = sobjectList.getSObjectType();
			Id recordTypeId = Schema.SObjectType.Affiliation__c.getRecordTypeInfosByName().get('Alumni').getRecordTypeId();
			id monashAccGlobalId= Global_Monash_Account__c.getOrgDefaults().id__c;
			
			affliationList = new List<Affiliation__c>();
			set<string>accIds = new set<string>();
			set<string>conIds = new set<string>();
			if(String.valueOf(sObjectType) =='Contact_Qualification__c'){
				List<Contact_Qualification__c> conQualList = (List<Contact_Qualification__c>) sobjectList;    	
				for(Contact_Qualification__c cq: conQualList){
					if(cq.Faculty__c ==null){
						accIds.add(monashAccGlobalId);                    
					}
					else{
						accIds.add(cq.Faculty__c); 
					}
					conIds.add(cq.Contact__c);
				}
			}  
			if(String.valueOf(sObjectType) =='Course_Attempt__c'){
				List<Course_Attempt__C> caList = (List<Course_Attempt__c>) sobjectList;    	
				for(Course_Attempt__c cq: caList){
					if(cq.Course__r.Faculty__c !=null){
						accIds.add(cq.Course__r.Faculty__c);
					}
					else{
						accIds.add(monashAccGlobalId); 
					}
					conIds.add(cq.Contact__c);
				}    
			}
			list<Affiliation__c> existingAff=[select id,Account__c,Contact__c,
											  Position_Level__c from Affiliation__c 
											  where Account__c IN:accIds and Contact__c IN: conIds ];
			Map<String,Affiliation__c> mapAff = new Map<String,Affiliation__c>();
			for(Affiliation__c eA : existingAff)
			{
				String key = eA.Account__c+'_'+eA.Contact__c;
				mapAff.put(key,eA);
			}
			for(sObject sobj: sobjectList){
				if(string.valueOf(sobj.getSObjectType())=='Contact_Qualification__c'){
					Contact_Qualification__c cq= (Contact_Qualification__c) sobj ;
					String key = cq.Faculty__c ==null ? monashAccGlobalId+'_'+cq.Contact__c : cq.Faculty__c+'_'+cq.Contact__c;
					if (!mapAff.containsKey(key)){
						Affiliation__c af = new Affiliation__c();
						af.Account__c = cq.Faculty__c !=null ? cq.Faculty__c : monashAccGlobalId;
						af.RecordTypeId=recordTypeId;
						af.Contact__c= cq.Contact__c;
						af.Position_Level__c='Alumni';
						af.Start_Date__c =system.today();
						affliationList.add(af); 
						af.Start_Date__c =cq.Date_Achieved__c !=null ? cq.Date_Achieved__c : system.today();
						mapAff.put(key,af);
					}
				}
				
				if(string.valueOf(sobj.getSObjectType())=='Course_Attempt__c'){
					Course_Attempt__c cq= (Course_Attempt__c) sobj ;
					String key = cq.Course__r.Faculty__c ==null ? monashAccGlobalId+'_'+cq.Contact__c  : cq.Course__r.Faculty__c+'_'+cq.Contact__c;
					if (!mapAff.containsKey(key)){
						Affiliation__c af = new Affiliation__c();
						af.RecordTypeId=recordTypeId;
						af.Account__c = cq.Course__r.Faculty__c !=null ? cq.Course__r.Faculty__c : monashAccGlobalId ;
						af.Contact__c= cq.Contact__c;
						af.Position_Level__c='Alumni No Degree';
						af.Start_Date__c =system.today();
						affliationList.add(af);  
						mapAff.put(key,af);
					}
				}
			}
		}
		try {
            Database.SaveResult[] insertResults = Database.insert(affliationList, false);

            Database.SaveResult aResult = null;
            List<Affiliation__c> retryAffliationList = new List<Affiliation__c>();
            for (Integer i=0; i<insertResults.size(); i++) {
                aResult = insertResults[i];
                if (!aResult.isSuccess()) {
                    for (Database.Error err : aResult.getErrors()) {
                        Switch on (err.getStatusCode()) {
                            when UNABLE_TO_LOCK_ROW {
                                if (retryCount < 3) {
                                    retryAffliationList.add(affliationList[i]);
                                } else {
                                    LogUtilityException.addLogEvent('createAffiliationforCDCExp','Affiliation', err, 'AffiliationsService.createAffiliationforCDCExp() [Retry Post Insert]');  
                                }
                            }
                            when else {
                                LogUtilityException.addLogEvent('createAffiliationforCDCExp','Affiliation', err, 'AffiliationsService.createAffiliationforCDCExp() [Retry Post Insert]');  
                            }
                        }
                    } 
                } 
            }

            if (retryAffliationList.size() > 0) {
                createAffiliationforCDCExp(null, retryAffliationList, retryCount++);
            }

        } catch(Exception exc) {
            LogUtilityException.addLogEvent('createAffiliationforCDCExp','Affiliation', exc, 'AffiliationsService.createAffiliationforCDCExp() [Retry Post Insert]');
        }
    }

   /**
    * @author          Ajitabh
    * @method     perform Alumni no degree logic
    * @revision        
    */
    public static void performAlumniNoDegreeLogic(set<String>caIds){
        List<Course_Attempt__C> eligibleCaList= new List<Course_Attempt__C>();
        List<Course_Attempt__C> caList= new List<Course_Attempt__C>();
        List<String> contactProfile = new List<String>();          
        List<Contact> updateContactList = new List<Contact>();
        set<string> conIds= new set<string>();
        
        //query all the course attempt where parent Course has sublevel in ('41','42','77','78')
        //calculate total achieved credit points for completed unit attempts for a Course attempt
        If(!caIds.isEmpty()){
            for(Course_Attempt__C ca : [select id,Contact__c,(select id, Achieved_Credit_Points__c from Unit_Attempts__r where 
                                                              Status__c='Completed'),Course__c,Course__r.Faculty__c,Course__r.Type__c,
                                        Course__r.Sub_Level__c from Course_Attempt__C where (id IN: CAIds) and 
                                        (Course__r.Type__c='Course-All' and Course__r.Sub_Level__c IN ('41','42','77','78'))]){
                                            decimal creditScore=0;
                                            for(Unit_Attempt__c  ua : ca.Unit_Attempts__r){
                                                creditScore=creditScore+ua.Achieved_Credit_Points__c;
                                            }    
                                            if(creditScore >= 18){
                                                eligibleCaList.add(ca);  
                                                conIds.add(ca.Contact__c);
                                            }   
                                        }
        }
        if(eligibleCaList.size()>0){
            createAffiliationforCDCExp(eligibleCaList, null, 0);
        }
        Map<Id,Contact> contactDetails = new Map<Id,Contact>([SELECT Id, Contact_Profile__c FROM Contact WHERE Id in :conIds]);   
        for(Contact con : contactDetails.values()){
            if(con.Contact_Profile__c != null){
                contactProfile.addAll(con.Contact_Profile__c.split(';'));
            }
            if(!contactProfile.contains('Alumni No Degree')){
                contactProfile.add('Alumni No Degree');
                con.Contact_Profile__c='';
                for(integer i=0;i< contactProfile.size();i++){
                    con.Contact_Profile__c=con.Contact_Profile__c+contactProfile[i]+';';         
                }
                updateContactList.add(con);
            }
            contactProfile.clear();    
        } 
        if(updateContactList.size()>0){
            update updateContactList;
        }           
    }
    
    /**
    * @author     Mac Domingo
    * @method     Set Default Values in Affiliation
    * @revision        
    */
    public void setDefaults(Affiliation__c rec){
        populateCompositeKey(rec);    //compositeKey
    }
    /**
    * @author     Mac Domingo
    * @method     Updates the value of the Composite Key field in the Affiliation object
    * @revision        
    */
    public void generateNewCompositeKey(Affiliation__c rec){
        populateCompositeKey(rec);    //compositeKey
    }
    /**
    * @author     Mac Domingo
    * @method     Set Default Values of CompositeKey field in Affiliation object
    * @revision        
    */
    public void populateCompositeKey(Affiliation__c rec){
        Id applicantrecordTypeId = Schema.SObjectType.Affiliation__c.getRecordTypeInfosByName().get('Applicant').getRecordTypeId();
        if(applicantrecordTypeId == rec.RecordTypeId){
            rec.Composite_Key__c = ContactPointUtility.getAffiliationKey(rec);
        }        
    }
}