force-app/main/default/objects/Affiliation__c.object
<CustomObject>
    <description>Links a person (Contact) with an entity, e.g. company (or organisational unit), club, school etc.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact (person) of the affiliation to an account (organisation)</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ready_to_Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Validate Archive Status</description>
        <label>Ready to Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <description>To store the Role of the linked Affiliation</description>
        <label>Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Chair</fullName>
                </value>
                <value>
                    <fullName>Co-Founder</fullName>
                </value>
                <value>
                    <fullName>Founder</fullName>
                </value>
                <value>
                    <fullName>Current Employee</fullName>
                </value>
                <value>
                    <fullName>Former Employee</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Senior Management</fullName>
                </value>
                <value>
                    <fullName>Strategic Relationship</fullName>
                </value>
                <value>
                    <fullName>Educator/Guest</fullName>
                </value>
                <value>
                    <fullName>Regional Manager</fullName>
                </value>
                <value>
                    <fullName>Associate Dean</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <description>indicates if the Affiliation record is active or not, based on the end date.</description>
        <formula>IF( 

AND( 
 NOT(ISNULL(End_Date__c)),
 TODAY() &gt;= End_Date__c
), 

FALSE, 
TRUE)</formula>
        <inlineHelpText>indicates if the Affiliation record is active or not, based on the end date.</inlineHelpText>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFL-{0000000}</displayFormat>
        <label>Affiliation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Archiving_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Fields_to_query__c</fullName>
        <description>Sets the fields to query for a certain object that needs archiving/purging</description>
        <label>Fields to query</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Filter_Criteria_Long__c</fullName>
        <description>Specifies the condition of the SOQL query that will be formed</description>
        <label>Filter Criteria Long</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Filter_criteria__c</fullName>
        <description>Sets the where clause of the sObject that needs to have their records archived/purged</description>
        <label>Filter criteria</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This will turn on/off sobjects that needs to use the Archiving functionality</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_of_years_to_archive__c</fullName>
        <description>Sets the number of years to archive the record</description>
        <label>No of years to archive</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_years_to_purge__c</fullName>
        <description>Sets the number of years to purge a standard enquiry</description>
        <label>No of years to purge</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>The name of the sObject that we want to include in the archive</description>
        <label>Object Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Identifies the status of the record that will be purged/archived</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Archiving Setting</label>
    <pluralLabel>Archiving Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Channel__c.object
<CustomObject>
    <description>Communication Channels</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Channels</relationshipLabel>
        <relationshipName>Channels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ready_to_Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Archive Status</description>
        <label>Ready to Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Channel (which maps to Callista Address Type)
it supports Callista types + the &quot;MAILING&quot; type (which is used by the Lead Management).</description>
        <inlineHelpText>Type of Channel - CRM Users are not expected to select Callista values</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HOME</fullName>
                    <label>Home</label>
                </value>
                <value>
                    <fullName>MAILING</fullName>
                    <label>Mailing</label>
                </value>
                <value>
                    <fullName>POSTAL</fullName>
                    <label>Postal</label>
                </value>
                <value>
                    <fullName>POSTAL-EXT</fullName>
                    <label>Postal Extended</label>
                </value>
                <value>
                    <fullName>OS-POSTAL</fullName>
                    <label>Overseas Postal</label>
                </value>
                <value>
                    <fullName>OS-HOME</fullName>
                    <label>Overseas Home</label>
                </value>
                <value>
                    <fullName>AP-EMAIL</fullName>
                    <label>Application Email</label>
                </value>
                <value>
                    <fullName>GRADUATION-APPL</fullName>
                    <label>Graduation Email</label>
                </value>
                <value>
                    <fullName>EMERCONT</fullName>
                    <label>Emergency Contact</label>
                </value>
                <value>
                    <fullName>BILLING</fullName>
                    <isActive>false</isActive>
                    <label>Billing</label>
                </value>
                <value>
                    <fullName>BUSINESS</fullName>
                    <isActive>false</isActive>
                    <label>Business</label>
                </value>
                <value>
                    <fullName>DEFAULT</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
                <value>
                    <fullName>LEGAL</fullName>
                    <isActive>false</isActive>
                    <label>Legal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Channel</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Roles__c.object
<CustomObject>
    <description>Custom version of Contact Roles</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Captures the related contact</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>Initial results are limited to contacts at the school only. Remove the filter to search all contacts</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Roles</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ready_to_Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Archive Status</description>
        <label>Ready to Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Resigned</fullName>
                </value>
                <value>
                    <fullName>Incoming - Unregistered</fullName>
                </value>
                <value>
                    <fullName>Outgoing - Registered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Role</label>
    <nameField>
        <displayFormat>ROL-{00000}</displayFormat>
        <label>Affiliation Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomIterable.cls
/**
 * @author          mac.domingo@monash.edu
 * @description     EPCP-2899 - Enquiry Archiving Framework. Iterable class that will build the following:
 *                              - SOQL query based on the values in the Archiving Setting custom metadata
 *                              - IterableWrapper that will be used in the ArchivingBatch
 * @date            15-08-2023
 * @group           Platforms
 * @revision
 *     2023-15-08 Mac Domingo Created
 *     2024-04-08 Mac Domingo - Changed custom metadata to include Long Filter Criteria for Faculties
*/
public class CustomIterable implements Iterator<IterableWrapper> {
    private List<IterableWrapper> itWrapperList = new List<IterableWrapper>();
    private Integer i = 0;
    private List<Archiving_Setting__mdt> activeSettingsList = new List<Archiving_Setting__mdt>();

    public CustomIterable() {
        initializeSettings();
        processActiveSettings();
    }

    private void initializeSettings() {
    	// If running a test, load test metadata records
        if (Test.isRunningTest()) {
            List<Archiving_Setting__mdt> predefinedSettings = new List<Archiving_Setting__mdt>{
                createArchivingSetting('Case', 'Case', 'RecordType.Name = \'Standard Enquiry\' AND Status = \'Solved\'', 'Id, Archive_Date__c, Purge_Date__c, ClosedDate', false),
                createArchivingSetting('Role', 'Roles__c', 'Status__c = \'Accepted\'', 'Id, Ready_to_Archive__c', true),
                createArchivingSetting('Channel', 'Channel__c', 'Type__c = \'Mailing\'', 'Id, Ready_to_Archive__c', true),
                createArchivingSetting('Affiliation', 'Affiliation__c', 'Contact__r.LastName = \'TestApplicant\'', 'Id, Ready_to_Archive__c, Contact__c', true),
                createArchivingSetting('IER', 'et4ae5__IndividualEmailResult__c', 'Name = \'IamTest\'', 'Id, Ready_to_Archive__c', true)
            };
            activeSettingsList.addAll(predefinedSettings);
            return; // Skip querying real metadata in tests
        }

        // Fetch active settings from Custom Metadata if not in test
        List<Archiving_Setting__mdt> dbSettings = [
            SELECT Id, Object_Name__c, IsActive__c, Fields_to_query__c, Filter_Criteria_Long__c, No_of_years_to_archive__c, No_of_years_to_purge__c 
            FROM Archiving_Setting__mdt
            WHERE IsActive__c = TRUE
        ];
    
        activeSettingsList.addAll(dbSettings);
    }

    private Archiving_Setting__mdt createArchivingSetting(String label, String objectName, String filterCriteria, String fieldsToQuery, Boolean isActive) {
        Archiving_Setting__mdt setting = new Archiving_Setting__mdt();
        setting.MasterLabel = label;
        setting.DeveloperName = label;
        setting.Object_Name__c = objectName;
        setting.Filter_Criteria_Long__c = filterCriteria;
        setting.Filter_criteria__c = filterCriteria;
        setting.Fields_to_query__c = fieldsToQuery;
        setting.No_of_years_to_archive__c = 1;
        setting.No_of_years_to_purge__c = 1;
        setting.IsActive__c = isActive;
        return setting;
    }

    private void processActiveSettings() {
        for (Archiving_Setting__mdt settings : activeSettingsList) {
            String strWhereClause = settings.Filter_Criteria_Long__c;
            Nebula.Logger.info('##### strWhereClause ' + strWhereClause);

            Set<String> queryFields = parseFields(settings.Fields_to_query__c);
            Nebula.Logger.info('##### queryFields ' + queryFields);

            String dynamicSearchToQuery = buildSOQLQuery(settings.Object_Name__c, strWhereClause, queryFields);

            if (!String.isEmpty(dynamicSearchToQuery)) {
                executeQuery(dynamicSearchToQuery, settings);
            }
        }
    }

    private Set<String> parseFields(String fieldsToQuery) {
        return String.isEmpty(fieldsToQuery) ? new Set<String>() : new Set<String>(fieldsToQuery.replace(' ', '').split(','));
    }

    private String buildSOQLQuery(String objectName, String whereClause, Set<String> fields) {
        return 'SELECT ' + String.join(new List<String>(fields), ', ') + 
               ' FROM ' + objectName + 
               ' WHERE ' + whereClause;
    }

    private void executeQuery(String query, Archiving_Setting__mdt settings) {
        try {
            List<SObject> records = Database.query(query);
            for (SObject record : records) {
                IterableWrapper itWrap = new IterableWrapper();
                itWrap.objectName = String.valueOf(record.getSObjectType().getDescribe().getName());
                itWrap.yrsToArchive = Integer.valueOf(settings.No_of_years_to_archive__c);
				itWrap.yrsToPurge = Integer.valueOf(settings.No_of_years_to_purge__c);
                itWrap.objRecord = record;
                itWrapperList.add(itWrap);
            }
            Nebula.Logger.info('****** itWrapperList: ' + itWrapperList);
        } catch (Exception e) {
            Nebula.Logger.info('Error executing query: ' + e.getMessage());
        }
    }

    public Boolean hasNext() {
        return i < itWrapperList.size();
    }

    public IterableWrapper next() {
        if (i < itWrapperList.size()) {
            return itWrapperList[i++];
        }
        return null;
    }
}