force-app/main/default/objects/AO_Form_Submission__c.object
<CustomObject>
    <fields>
        <fullName>AO_Program_Form_Map__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Program Form Map</description>
        <label>Program Form Map</label>
        <referenceTo>AO_Program_Form_Map__c</referenceTo>
        <relationshipLabel>Form Submission</relationshipLabel>
        <relationshipName>Form_Submission</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AO_Submitted_Date__c</fullName>
        <description>Date when Form is submitted by Student</description>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <label>Form Submission</label>
    <nameField>
        <displayFormat>FS-{0000000}</displayFormat>
        <label>Form Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Submission</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AO_Program_Form_Map__c.object
<CustomObject>
    <description>Object to relate forms to programs, this allows to enable single forms to multiple programs</description>
    <fields>
        <fullName>AO_Encoded_Id__c</fullName>
        <description>This field stores encoded Id of Program form map</description>
        <label>Encoded Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AO_Form_Name__c</fullName>
        <description>Display Form&apos;s display name</description>
        <formula>AO_Form__r.AO_Form_Display_Name__c</formula>
        <label>Form Name</label>
        <type>Text</type>
    </fields>
    <label>Program Form Map</label>
    <nameField>
        <displayFormat>PFM-{0000000}</displayFormat>
        <label>Program Form Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Form Map</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attempt__c.object
<CustomObject>
    <description>Course attempt represents the courses a Contact is related to.</description>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to the course (incl. version) of the course attempt</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Value does not match the type of allowed courses an attempt record can be related to.</errorMessage>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Course-All</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short Course</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short_Course</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Course Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Attempts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ContentDocumentTriggerHandler_Test.cls
/**
 * @author : [Babyshark]
 * @description : Test class for ContentDocumentTriggerHandler
 * @group : Abroad Outbound
 * @date : 16/09/2024
 * @rev
 * 
 */ 
@IsTest(isParallel=true)
private class ContentDocumentTriggerHandler_Test {
    
    @TestSetup
    static void makeData(){
        AOTestDataFactory.setupForms();
        
        List<Account> accs = TestHelper.createStudent(1);
        insert accs;
        
        List<Contact> cons = TestHelper.createStudentContacts(1, accs);
        cons[0].Preferred_Name__c = 'Preferred';
        insert cons;
        
        List<Course__c> course = TestHelper.createCoursesWithType(1, 'Course-All');
        insert course;
        
        List<Course_Attempt__c> attempts = TestHelper.createCourseAttempts(1, cons[0].Id, course[0].Id);
        insert attempts;
      
    }

    /**
     * @description - Test Attached file deletion from Submitted form 
     * @revision    
     */
    @IsTest
    static void testSubmitForm() {
        //GIVEN - Form has been successfully constructed and User has necessary permission
        
        AO_Program_Form_Map__c formM = [SELECT Id, AO_Form_Name__c, AO_Encoded_Id__c FROM AO_Program_Form_Map__c LIMIT 1];
        
        // WHEN - Get the form
        	Test.startTest();
            AoFormClientController.Form formResult = AoFormClientController.getForm(null, null, formM.AO_Encoded_Id__c , null);
            System.debug(formResult);
            List<AoFormClientController.Answer> answers = new List<AoFormClientController.Answer>();
    
            AoFormClientController.FormElement sectionResult = formResult.childElements[0];
            AoFormClientController.FormElement elem01Result = sectionResult.sectionDefinition.childElements[0];
            AoFormClientController.FormElement elem02Result = formResult.childElements[1];
            AoFormClientController.FormElement elem03Result = formResult.childElements[2];
            AoFormClientController.Answer elem1Answer = new AoFormClientController.Answer();
            elem1Answer.elementId = elem01Result.id; 
            elem1Answer.label=elem01Result.label;
            elem1Answer.name = elem01Result.name; 
            elem1Answer.type = elem01Result.type;
            elem1Answer.value= 'Preferred name';
            answers.add(elem1Answer);
    
            AoFormClientController.Answer elem2Answer = new AoFormClientController.Answer();
            elem2Answer.elementId = elem01Result.id; 
            elem2Answer.label=elem01Result.label;
            elem2Answer.name = elem01Result.name; 
            elem2Answer.type = elem01Result.type;
            elem2Answer.value= '01';
            answers.add(elem2Answer);
    
            AoFormClientController.Answer elem3Answer = new AoFormClientController.Answer();
            elem3Answer.elementId = elem01Result.id; 
            elem3Answer.label=elem01Result.label;
            elem3Answer.name = elem01Result.name; 
            elem3Answer.type = elem01Result.type;
            elem3Answer.value= 'Picklist';
            Id networkId = [SELECT Id FROM Network LIMIT 1].Id;

                
            ContentVersion newFile = new ContentVersion();
            newFile.PathOnClient = 'TestFile';
            newFile.Title = 'TestFile';
            newFile.VersionData = Blob.valueOf('sample content');
            
            insert newFile;
            ContentDocument contentDocumentId = [SELECT Id FROM ContentDocument WHERE Title='TestFile' LIMIT 1];
            Map<Object,Object> file = new Map<Object,Object>{'documentId' => contentDocumentId.Id, 'name' => 'TestFile'};
            AoFormClientController.Answer elem4Answer = new AoFormClientController.Answer();
            elem3Answer.elementId = 'e45ytfgytfgy'; 
            elem3Answer.label= 'Upload File';
            elem3Answer.name = 'Upload File'; 
            elem3Answer.type = 'file upload';
            elem3Answer.value= new List<Object>{file};
            answers.add(elem3Answer);
        
            Id formSubmissionId = AoFormClientController.submitForm(null, answers, null, formM.AO_Encoded_Id__c , false);
            System.debug('formSubmissionId-->'+formSubmissionId);
            Assert.isNotNull(formSubmissionId, 'Form Submission unsuccessful');
            
            DELETE contentDocumentId;
        	Test.stopTest();
            // THEN - Verify the form
            Assert.isNotNull(formSubmissionId, 'Form Submission unsuccessful');
        	Assert.areEqual(Date.Today(),[SELECT AO_Submitted_Date__c FROM AO_Form_Submission__c WHERE Id= :formSubmissionId].AO_Submitted_Date__c, 'Submitted Date mismatch');
            
    }
}