force-app/main/default/objects/AO_Form_Submission__c.object
<CustomObject>
    <fields>
        <fullName>AO_Status__c</fullName>
        <description>Status to be captured for Form Submission</description>
        <label>Form Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <isActive>false</isActive>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Re-process</fullName>
                    <isActive>false</isActive>
                    <label>Re-process</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Submission</label>
    <nameField>
        <displayFormat>FS-{0000000}</displayFormat>
        <label>Form Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Submission</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AOFormSubmissionTriggerHandler.cls
/**
 * @author Ibrahim Rumi
 * @date 29-05-2024
 * @group Monash Abroad
 * @description Trigger handler for AO_Form_Submission__c object (Monash Abroad)
 **/
public with sharing class AOFormSubmissionTriggerHandler {

     /**
     * @description - handler class to create a program applicant when a form submission record is created
     * @revision    
     */
    public class createProgramApplicant extends TriggerAbstract {

        public Map<id,AO_Form_Submission__c> fsMap = new Map<id,AO_Form_Submission__c>();
        public override void process(SObject sobj) {
			AO_Form_Submission__c newObj = (AO_Form_Submission__c) sobj;
            if(newObj.AO_Status__c == AOFormSubmissionHelper.SUBMITTED || newObj.AO_Status__c == AOFormSubmissionHelper.DRAFT){
                fsMap.put(newObj.id,newObj);
            }
		}
        
        public override void process(SObject sobj, SObject oldRec) {
        	AO_Form_Submission__c newObj = (AO_Form_Submission__c) sobj;
            AO_Form_Submission__c oldObj = (AO_Form_Submission__c) oldRec;
            
            if(oldObj.AO_Status__c != newObj.AO_Status__c &&
               newObj.AO_Status__c == AOFormSubmissionHelper.SUBMITTED ){
                fsMap.put(newObj.id,newObj);
            }
        }

        public override void execute() {
			try {
				AOFormSubmissionHelper.handleFormSubmissions(fsMap);
			} catch(Exception e) {
				nebula.logger.exception(e.getMessage(), e);
                
			}
        }

    }
}