force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent for Submission</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Data Validation Ready</fullName>
                </value>
                <value>
                    <fullName>Failed Data validation</fullName>
                </value>
                <value>
                    <fullName>Submission on Hold (Duplicate Contact)</fullName>
                </value>
                <value>
                    <fullName>Agent Declaration Accepted</fullName>
                </value>
                <value>
                    <fullName>Sent Draft Application to Applicant</fullName>
                </value>
                <value>
                    <fullName>Applicant Declaration Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Qualification_Provided__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <label>Contact Qualification</label>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Qualification_Type__c</fullName>
        <formula>Contact_Qualification__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Qualification Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>Sequence number to send to callista for a particular contact qualification type</description>
        <label>Sequence Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application Qualification Provided</label>
    <nameField>
        <displayFormat>AQP-{000000}</displayFormat>
        <label>Application Qualification Provided ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Qualifications Provided</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Qualification_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the country at which the qualification is obtained</description>
        <label>Qualification Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qualification_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Qualification Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Level of Completion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ATTEMPTED BUT WAS NOT COMPLETED</fullName>
                </value>
                <value>
                    <fullName>CURRENTLY STUDYING</fullName>
                </value>
                <value>
                    <fullName>DISCONTINUED</fullName>
                </value>
                <value>
                    <fullName>SUCCESSFULLY COMPLETED AND OBTAINED</fullName>
                </value>
                <value>
                    <fullName>Completed Alternative Exit</fullName>
                    <isActive>false</isActive>
                    <label>Completed Alternative Exit</label>
                </value>
                <value>
                    <fullName>Completed not graduated</fullName>
                    <isActive>false</isActive>
                    <label>Completed not graduated</label>
                </value>
                <value>
                    <fullName>Graduated</fullName>
                    <isActive>false</isActive>
                    <label>Graduated</label>
                </value>
                <value>
                    <fullName>Graduated but no Grad Date in Callista</fullName>
                    <isActive>false</isActive>
                    <label>Graduated but no Grad Date in Callista</label>
                </value>
                <value>
                    <fullName>Study Abroad/CIC</fullName>
                    <isActive>false</isActive>
                    <label>Study Abroad/CIC</label>
                </value>
                <value>
                    <fullName>WILL BE COMPLETED BY ADMISSION</fullName>
                    <isActive>false</isActive>
                    <label>WILL BE COMPLETED BY ADMISSION</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Attribute__c.object
<CustomObject>
    <description>This allows the definition of various country attributes (e.g. mapping to ISO codes, ABS codes, Australian border, department of education codes, restricted countries, flags for different user groups which can be used to drive sharing of records etc.)</description>
    <fields>
        <fullName>ISO_Alpha_2__c</fullName>
        <description>The two-letter ISO alpha country representation.

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2</description>
        <inlineHelpText>The two-letter ISO alpha country representation.</inlineHelpText>
        <label>ISO Alpha-2</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist__c.object
<CustomObject>
    <description>Capture documents relevant to different processes that requires documents for verification</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to Application</description>
        <inlineHelpText>Link to Application</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Document Checklist</relationshipLabel>
        <relationshipName>Document_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Link to Contact Qualification</description>
        <inlineHelpText>Link to Contact Qualification</inlineHelpText>
        <label>Contact Qualification</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Contact__c</field>
                <operation>equals</operation>
                <valueField>Contact_Qualification__c.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipLabel>Document Checklist</relationshipLabel>
        <relationshipName>Document_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Request_Type__c</fullName>
        <description>Capture document request type to map documents with Callista</description>
        <label>Document Request Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Document Checklists</relationshipLabel>
        <relationshipName>Document_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Used to sort the rules results in order</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Meta data for checklist life-cycle</description>
        <inlineHelpText>Meta data for checklist life-cycle</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Insufficient</fullName>
                </value>
                <value>
                    <fullName>AutoCancelled</fullName>
                    <label>Auto Cancelled</label>
                </value>
                <value>
                    <fullName>ManualCancelled</fullName>
                    <label>Manual Cancelled</label>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Checklist</label>
    <nameField>
        <displayFormat>DC{YYYY}-{000000}</displayFormat>
        <label>Checklist Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklists</pluralLabel>
    <recordTypes>
        <fullName>Application_Assessment</fullName>
        <active>true</active>
        <description>Type of checklist relevant for assessing applications</description>
        <label>Application Assessment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Offer_Acceptance</fullName>
        <active>true</active>
        <description>Document checklist necessary for accepting offers.</description>
        <label>Offer Acceptance</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist_Comment__c.object
<CustomObject>
    <description>Comment holder for document checklist</description>
    <fields>
        <fullName>Cancelled_Date__c</fullName>
        <description>Cancelled Date of the comment</description>
        <label>Cancelled Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the document comment cancelled</description>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>Comment content details</description>
        <label>Content</label>
        <length>100000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Document_Checklist__c</fullName>
        <description>Linked checklist where the comment is for.</description>
        <label>Document Checklist</label>
        <referenceTo>Document_Checklist__c</referenceTo>
        <relationshipLabel>Document Checklist Comments</relationshipLabel>
        <relationshipName>Document_Checklist_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NotesSeen__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to tag new notes and whether it has already been seen by community users.</description>
        <label>Notes Seen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Date__c</fullName>
        <description>Comment request date from callista</description>
        <label>Request Date</label>
        <type>DateTime</type>
    </fields>
    <label>Document Checklist Comment</label>
    <nameField>
        <displayFormat>DCC{YYYY}-{000000}</displayFormat>
        <label>Document Checklist Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklist Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DocumentChecklistsSelector.cls
/**
 * @author      Kristian Vegerano
 * @description Selector class for document checklist object processes
 * @group       Selectors
 * @revision    31/05/2019 - Kristian Vegerano - Created
 */
public with sharing class DocumentChecklistsSelector extends BaseSelector {
    /**
     * Constructors
     */
    public DocumentChecklistsSelector() {
        super(false);
    }
    
    public DocumentChecklistsSelector(Boolean newOverrideObjectPermissions) {
        super(newOverrideObjectPermissions);
    }
    
    /**
     * @author      Kristian Vegerano
     * @date        31/05/2019
     * @description Returns the object type
     */
    public Schema.SObjectType getSObjectType() {
        return Document_Checklist__c.sObjectType;
    }
    
    /**
     * @author      Kristian Vegerano
     * @description Return ORDER BY clause for the query
     * @revision    17/05/2019 - Kristian Vegerano - Created
     */
    public override String getOrderBy() {
        return 'Sort_Order__c ASC';
    }

    /**
     * @author      Kristian Vegerano
     * @date        31/05/2019
     * @description Query document checklists by ids
     */
    public List<Document_Checklist__c> selectById(Set<Id> idSet) {
        return (List<Document_Checklist__c>) selectSObjectsById(idSet);
    }
    
    /**
     * @author      Kristian Vegerano
     * @date        31/05/2019
     * @description Query document checklists by parent application's ids
     */
    public List<Document_Checklist__c> selectApplicationAssessmentByApplicationIds(Set<Id> applicationIdSet) {
        assertIsAccessible();

        ApplicationsSelector applicationSelector = new ApplicationsSelector(overrideObjectPermissions);
        applicationSelector.assertIsAccessible();
        ContactQualificationsSelector contactQualificationsSelector = new ContactQualificationsSelector(overrideObjectPermissions);
        contactQualificationsSelector.assertIsAccessible();

        Id applicationAssessmentRecordTypeId = Schema.SObjectType.Document_Checklist__c.getRecordTypeInfosByDeveloperName().get('Application_Assessment').getRecordTypeId();
        String queryString = String.format('SELECT {0}, {1}, {2}, {3} FROM {4} WHERE Application__c IN :applicationIdSet AND RecordTypeId = :applicationAssessmentRecordTypeId ORDER BY {5}',
                                           new List<String>{getFieldListString(),
                                                            applicationSelector.getRelatedFieldListString('Application__r'),
                                                            'Contact_Qualification__r.Qualification_Type__c,Contact_Qualification__r.Name, Contact_Qualification__r.Qualification_Country__r.ISO_Alpha_2__c',
                                                            '(SELECT Id, CreatedDate, Document_Checklist__c, Content__c, NotesSeen__c FROM Document_Checklist_Comments__r ORDER BY CreatedDate DESC)',
                                                            getSObjectName(),
                                                            getOrderBy()});
        return Database.query(queryString);
    }

    /**
     * @author      Kristian Vegerano
     * @date        31/05/2019
     * @description Query document checklists by parent application's ids
     */
    public List<Document_Checklist__c> selectByIdWithApplicationDetails(Set<Id> applicationChecklistIds) {
        assertIsAccessible();

        ApplicationsSelector applicationSelector = new ApplicationsSelector(overrideObjectPermissions);
        applicationSelector.assertIsAccessible();

        String queryString = String.format('SELECT {0}, {1} FROM {2} WHERE Id IN :applicationChecklistIds ORDER BY {3}', 
                                           new List<String>{getFieldListString(),
                                                            applicationSelector.getRelatedFieldListString('Application__r'),
                                                            getSObjectName(),
                                                            getOrderBy()});
        return Database.query(queryString);
    }
    
    /**
     * @author      Kristian Vegerano
     * @description Query document checklists by parent sbqq quote's ids
     * @revision    13/02/2020 - Kristian Vegerano - Created
     */
    public List<Document_Checklist__c> selectOfferAcceptanceByQuoteIds(Set<Id> opportunityIdSet) {
        assertIsAccessible();

        OpportunitiesSelector opportunitySelector = new OpportunitiesSelector(overrideObjectPermissions);
        opportunitySelector.assertIsAccessible();

        Id offerAcceptanceRecordTypeId = Schema.SObjectType.Document_Checklist__c.getRecordTypeInfosByDeveloperName().get('Offer_Acceptance').getRecordTypeId();
        String queryString = String.format('SELECT {0}, {1}, {2} FROM {3} WHERE Opportunity__c IN :opportunityIdSet AND RecordTypeId = :offerAcceptanceRecordTypeId ORDER BY {4}', 
                                           new List<String>{getFieldListString(),
                                                            opportunitySelector.getRelatedFieldListString('Opportunity__r'),
                                                            '(SELECT Id, CreatedDate, Document_Checklist__c, Content__c, NotesSeen__c FROM Document_Checklist_Comments__r ORDER BY CreatedDate DESC)',
                                                            getSObjectName(),
                                                            getOrderBy()});        
        return Database.query(queryString);
    }

    /**
     * @author      Vishal Gupta
     * @date        22/10/2024
     * @param applicationId
     * @param docRequestType
     * @param sequenceNumber
     * @return List<Document_Checklist__c>
     * @description Query document checklists by application id, doc request type and Sequence Number if given
     */
    public List<Document_Checklist__c> selectApplicationAssessmentByApplicationIdAndSequenceNumber(Id applicationId, String docRequestType, Integer sequenceNumber) {
        assertIsAccessible();
        String applicationQualQuery = '';
        Set<String> status = new Set<String>{'Requested', 'Submitted', 'Insufficient'};
        String docCommentsQuery = '(SELECT Id, Content__c, Cancelled__c, Cancelled_Date__c, Request_Date__c FROM Document_Checklist_Comments__r ORDER BY CreatedDate DESC)';
        if(sequenceNumber != null) {
            applicationQualQuery = ' AND Contact_Qualification__c IN (SELECT Contact_Qualification__c FROM Application_Qualification_Provided__c WHERE Application__c = :applicationId and Sequence_Number__c = :sequenceNumber) ';
        }
        Id applicationAssessmentRecordTypeId = Schema.SObjectType.Document_Checklist__c.getRecordTypeInfosByDeveloperName().get('Application_Assessment').getRecordTypeId();
        String queryString = String.format('SELECT {0}, {1} FROM {2} WHERE Application__c = :applicationId AND Document_Request_Type__c = :docRequestType AND Status__c in :status {3} ORDER BY {4}',
                                           new List<String>{getFieldListString(),
                                                            docCommentsQuery,
                                                            getSObjectName(),
                                                            applicationQualQuery,
                                                            getOrderBy()});
        return Database.query(queryString);
    }
}