force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/MyAppApplicationAuthenticator.cls
/**
 * @File Name          : MyAppApplicationAuthenticator.cls
 * @Description        : My.App authentication if the record is related to logged in user
 * @Author             : Vishal Gupta
 * @Group              : My.App
 * @date               : 28/3/2025
 **/
public with sharing class MyAppApplicationAuthenticator implements IMyAppApplicantChecker {
    private Application__c app;
    public MyAppApplicationAuthenticator(Application__c application) {
        this.app = application;
    }

    /**
     * @author      Vishal Gupta
     * @description  Implement the getApplicantId method
     * @revision    28/3/2025 - Initial Version
    */
    public Id getApplicantId() {
        return app.Applicant__c;
    }

    /**
     * @author      Vishal Gupta
     * @description Implement the isRecordRelatedToCurrentUser method
     * @revision    28/3/2025 - Initial Version
    */
    public Boolean isRecordRelatedToCurrentUser() {
        Id currentUserId = UserInfo.getUserId();
        User currentUser = [SELECT ContactId FROM User WHERE Id = :currentUserId LIMIT 1];
        return getApplicantId() == currentUser.ContactId;
    }
}