force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c.object
<CustomObject>
    <description>Payment for pledges or gifts.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiry_Month__c</fullName>
        <label>Credit Card Expiry Month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <description>This will be the record create date. Can populate automatically. Will be used for data migration.</description>
        <label>Payment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                    <default>true</default>
                    <label>Not Processed</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Refund Processed</fullName>
                </value>
                <value>
                    <fullName>Refund Not Processed</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                    <isActive>false</isActive>
                    <label>Refunded</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Receipt__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger for the workflow which sends the receipt email</description>
        <label>Send Receipt</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PY-{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentRequestTriggerHandler_Test.cls
/**
 * @author 		Sachin Shetty
 * @date 		AUG.05.2025
 * @description Test class for PaymentRequestTrigger trigger
 * @group       Apex Class
 * @revision
 *  			AUG.05.2025		Sachin Shetty	- Created
 */
@isTest (isParallel=true)
public class PaymentRequestTriggerHandler_Test {
    
    @testSetup static void createTestData() {
        TriggerCommon.disableTrigger('Course__c');
        TriggerCommon.disableTrigger('Account');
        TriggerCommon.disableTrigger('Contact');
        TriggerCommon.disableTrigger('Application__c');
        
        Course__c course = PDTestHelper.createCourse();
        Course_Offering__c co = PDTestHelper.createCourseOffering();    
        co.Course__c = course.Id;
        update co;
        Contact contact = PDTestHelper.createContact();
        Case enquiry = PDTestHelper.createEnquiry();
        Application__c application = PDTestHelper.createApplication(contact, enquiry);
        PDTestHelper.createMagentoSettings();
        Payment__c payment = PDTestHelper.createPayment(co, contact, application);
        ChargentOrders__ChargentOrder__c chOrder = PDTestHelper.createChargentOrder(payment);
        
        TriggerCommon.enableTrigger('Application__c');
        TriggerCommon.enableTrigger('Contact');
        TriggerCommon.enableTrigger('Account');        
        TriggerCommon.enableTrigger('Course__c');
    }
            
    @isTest
    static void testPaymentRequestUpdateToPaid() {
        
        // GIVEN : Test data for payment are created
		ChargentOrders__ChargentOrder__c chOrder = [SELECT Id FROM ChargentOrders__ChargentOrder__c LIMIT 1];
        ChargentOrders__Payment_Request__c paymentRequest = PDTestHelper.createPaymentRequest(chOrder);
        
        // WHEN : The payment request - Status is set to 'Paid'
        Test.startTest();
        
            // Update to paid status to trigger the automation
            paymentRequest.ChargentOrders__Status__c = 'Paid';
            update paymentRequest;
            
        Test.stopTest();
        
        // THEN : Check that the fields on payment record as set to reflect proper status
        Payment__c payment = [SELECT Payment_Date__c, Credit_Card_Expiry_Month__c, Payment_Status__c, Send_Receipt__c FROM Payment__c LIMIT 1];
        Assert.areEqual('Processed', payment.Payment_Status__c, 'Payment status should be Processed');
        Assert.isTrue(payment.Send_Receipt__c, 'Payment send receipt should be set to True');
    }
    
    @isTest
    static void testPaymentRequestUpdateToNonPaid() {
        
        // GIVEN : Test data for payment are created
        ChargentOrders__ChargentOrder__c chOrder = [SELECT Id FROM ChargentOrders__ChargentOrder__c LIMIT 1];
        ChargentOrders__Payment_Request__c paymentRequest = PDTestHelper.createPaymentRequest(chOrder);
        
        // WHEN : The payment request - Status is set to 'Failed'
        Test.startTest();
        
            // Update to paid status to trigger the automation
            paymentRequest.ChargentOrders__Status__c = 'Failed';
            update paymentRequest;
            
        Test.stopTest();
        
        // THEN : Check that the fields on payment record as set to reflect proper status
        Payment__c payment = [SELECT Payment_Status__c, Send_Receipt__c FROM Payment__c LIMIT 1];
        Assert.areEqual('Not Processed', payment.Payment_Status__c, 'Payment status should be Processed');
        Assert.isFalse(payment.Send_Receipt__c, 'Payment send receipt should be set to False');
    }
}