force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Course Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Title__c</fullName>
        <label>Course Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to course code, filtering out Unit Set courses</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>notEqual</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>ACP Courses</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managing_Faculty_Text__c</fullName>
        <description>For partitioning sharing rules. Populated by a PB.</description>
        <label>Managing Faculty</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Managing_Faculty__c</fullName>
        <description>The owner or manager of the selected course</description>
        <formula>Course__r.Faculty_Description__c</formula>
        <label>Managing Faculty</label>
        <type>Text</type>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Used to force uniqueness on course code. Updated from workflow.</description>
        <externalId>true</externalId>
        <label>Course Code Unique</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Managing_Faculty__c</fullName>
        <label>Managing Faculty/School/Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>a</fullName>
                </value>
                <value>
                    <fullName>Faculty of Art, Design &amp; Architecture</fullName>
                </value>
                <value>
                    <fullName>Faculty of Arts</fullName>
                </value>
                <value>
                    <fullName>Faculty of Business &amp; Economics</fullName>
                </value>
                <value>
                    <fullName>Faculty of Education</fullName>
                </value>
                <value>
                    <fullName>Faculty of Engineering</fullName>
                </value>
                <value>
                    <fullName>Faculty of Information Technology</fullName>
                </value>
                <value>
                    <fullName>Faculty of Law</fullName>
                </value>
                <value>
                    <fullName>Faculty of Medicine, Nursing &amp; Health Sciences</fullName>
                </value>
                <value>
                    <fullName>Faculty of Pharmacy &amp; Pharmaceutical Sciences</fullName>
                </value>
                <value>
                    <fullName>Faculty of Science</fullName>
                </value>
                <value>
                    <fullName>Monash Centre for Professional Development</fullName>
                </value>
                <value>
                    <fullName>Monash College</fullName>
                </value>
                <value>
                    <fullName>Monash College Diplomas</fullName>
                </value>
                <value>
                    <fullName>Monash Injury Research Institute</fullName>
                </value>
                <value>
                    <fullName>Monash Sustainable Development Institute</fullName>
                </value>
                <value>
                    <fullName>Monash University English Language Centre</fullName>
                </value>
                <value>
                    <fullName>Monash University Foundation Year</fullName>
                </value>
                <value>
                    <fullName>Monash University Foundation Year MUFY</fullName>
                </value>
                <value>
                    <fullName>PPA</fullName>
                </value>
                <value>
                    <fullName>School of Clinical Sciences (SCS)</fullName>
                </value>
                <value>
                    <fullName>Monash Centre for Health Research and Implementation (MCHRI)</fullName>
                </value>
                <value>
                    <fullName>MNHS Student Academic Support Unit (SASU)</fullName>
                </value>
                <value>
                    <fullName>The School of Public Health and Preventive Medicine (SPHPM)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of course being offered</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Academic_Course</fullName>
                    <label>Academic Course</label>
                </value>
                <value>
                    <fullName>Short_Course</fullName>
                    <label>Professional Development</label>
                </value>
                <value>
                    <fullName>Course-All</fullName>
                </value>
                <value>
                    <fullName>Unit Set</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attempt__c.object
<CustomObject>
    <description>Course attempt represents the courses a Contact is related to.</description>
    <fields>
        <fullName>Application_Course_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The application course preference related to this course attempt (eg. Originating ACP)</description>
        <label>Application Course Preference</label>
        <referenceTo>Application_Course_Preference__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Reference to the contact who pursues this course</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Contains the course code (without the version). It is derived from the Course lookup relationship.</description>
        <formula>Course__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Title__c</fullName>
        <description>Title of the course being attempted.</description>
        <formula>Course__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to the course (incl. version) of the course attempt</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Value does not match the type of allowed courses an attempt record can be related to.</errorMessage>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Course-All</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short Course</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short_Course</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Course Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Attempts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry_Interest__c.object
<CustomObject>
    <description>stores one or more interests registered against an Enquiry</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>all enquiry interests are derived from a case record</description>
        <label>Enquiry</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course_Title__c</fullName>
        <description>for use in the console sidebar view</description>
        <formula>IF(
NOT(ISBLANK(Course__r.Course_Description__c )),
Course__r.Course_Description__c,
   IF(NOT(ISBLANK(Course_Title_Text__c)), Course_Title_Text__c,
&quot;&quot;))</formula>
        <label>Course Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>if person is interested in a specific course, this field links to that course record.</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Depreciated__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managing_Faculty__c</fullName>
        <description>Migrated over from original UniCRM, this field captures either the manually selected Faculty of interest if the Faculty picklist is used, or the inferred faculty of interest if a course is selected.</description>
        <label>Managing Faculty</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enquiry Interest</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Enquiry Interest Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiry Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person_Note__c.object
<CustomObject>
    <description>Subset of notes from SMS, used to id students or authorised significant others</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Person Notes</relationshipLabel>
        <relationshipName>Person_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Important__c</fullName>
        <defaultValue>true</defaultValue>
        <description>if checked, then this will drive the console component to set notes notification button to red with white text</description>
        <inlineHelpText>if checked, then this will drive the console component to set notes notification button to red with white text</inlineHelpText>
        <label>Important</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SPECIAL CARE</fullName>
                    <default>true</default>
                    <label>SPECIAL CARE</label>
                </value>
                <value>
                    <fullName>Humanitarian</fullName>
                </value>
                <value>
                    <fullName>Natural Disaster</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Person Note</label>
    <nameField>
        <label>Person Note Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Person Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Console_CourseInfo_CE_Test.cls
/**
* @author Angelo Rivera
* @date 05.09.19
* @group Test Class
* @description  Custom Controller Extension for use in custom service console component(s).<br/>
*               Specifically, the component that surfaces course and application information
* @revision     15/12/2019 - APRivera - removed references of API_ResultWrapper (API.Monash) <br/>
*/
@isTest(isParallel=true)
private class Console_CourseInfo_CE_Test {

    @testSetup
    static void setupTestData(){
        // if test data required, establish here
        TestHelper.calabrioSetUp();
        List<contact> contacts = TestHelper.createOrphanContactRecords(2);
        integer offset = 1;
        for(contact c : contacts) {
            c.birthdate = date.newInstance(1975,1,1);
            c.Person_Id_unique__c = String.valueOf(12345+offset);
            offset++;
        }
        insert contacts;
        system.assertNotEquals(null, contacts[0].id,'contacts didnt insert as expected');

        // add some person notes
        List<Person_Note__c> notes = new List<Person_note__c>();
        for(contact c : contacts) notes.add(new Person_note__c(contact__c = c.id, type__c = 'type', important__c = true, notes__c = 'test note'));
        insert notes;
        system.assertNotEquals(null, notes[0].id,'notes didnt insert as expected');

        List<Case> cases = TestHelper.webToCaseForms(2);
        cases[0].contactId = contacts[0].id;
        cases[0].Enquiry_Type__c = CaseServices.CURRENT_COURSE;
        cases[0].Course_code__c = '123';
        cases[0].Managing_Faculty__c = 'Arts';
        cases[0].Status = 'Open';
        cases[0].Course_Linked__c = false;

        cases[1].contactId = contacts[0].id;
        cases[1].Enquiry_Type__c = CaseServices.CURRENT_COURSE;
        cases[1].Course_code__c = 'COMPLETED';
        insert cases;

        // append some enquiry interests
        List<course__c> courses = TestHelper.createCourses(2);
        courses[0].name = '123445';
        insert courses;
        system.assertNotEquals(null, courses[0].id,'courses didnt insert as expected');

        List<Enquiry_Interest__c> interests = new List<Enquiry_Interest__c>();
        for(contact c : contacts){
            for(course__c course : courses){
                for(case cse : cases)
                    interests.add(new Enquiry_Interest__c(course__c = course.id, person__c = c.id, case__c = cse.id));
            }
        }

        insert interests;
        system.assertNotEquals(null, interests[0].id,'interests didnt insert as expected');

        Course__c testCourse = new Course__c(Name = 'TestCourse', Managing_Faculty__c = 'TestFaculty', Type__c='Course-All');
        insert testCourse;

        Application_Course_Preference__c acp = new Application_Course_Preference__c(Name='Test', Managing_Faculty_Text__c='TestFaculty', Course__c=testCourse.id, Course_Title__c='TestCourse', Course_Code__c='LC001', Outcome_Status__c='IN_PROGRESS',
                Offer_Response_Status__c='PENDING',Applicant__c=contacts[0].id);
        insert acp;

        Course_Attempt__c ca = new Course_Attempt__c(Name='Test', Course__c=testCourse.id, Course_Attempt_Status__c='Enrolled', Attendance_Type__c='FT', Attendance_Mode__c='IN', Location__c='Clayton',
                Contact__c = contacts[0].id);
        insert ca;

    }

    static testMethod void testCourseInfoLogic(){

        PageReference pg = Page.Console_courseInfo_v2;
        Test.setCurrentPage(pg);

        Case cse = [select id, Status, Managing_Faculty__c, Course_Linked__c from case where case.contact.Person_ID__c != null limit 1];
        ApexPages.StandardController stdCase = new ApexPages.StandardController(cse);

        Console_CourseInfo_CE con = new Console_CourseInfo_CE(stdCase);

        Test.startTest();
        con.initalLoad();
        Boolean res = con.renderTable;
        con.unlinkFromCase();

        course__c crse = [select id,name from course__c where name = 'TestCourse' limit 1];
        con.courseIdSelected = crse.name + ':' + 'LC001';
        con.linkToCase();
        Test.stopTest();
        //System.assertNotEquals(cse.Managing_Faculty__c, null);
    }

    static testMethod void testCourseInfoLogic1(){

        PageReference pg = Page.Console_courseInfo_v2;
        Test.setCurrentPage(pg);

        Case cse = [select id, Course_code__c from case where case.contact.Person_ID__c != null and Course_code__c ='COMPLETED' limit 1];
        ApexPages.StandardController stdCase = new ApexPages.StandardController(cse);

        Test.startTest();
        Console_CourseInfo_CE con = new Console_CourseInfo_CE(stdCase);
        con.initalLoad();

        course__c crse = [select id,name from course__c where name = '123445' limit 1];
        con.courseIdSelected = crse.name + ':' + 'COMPLETED';
        con.linkToCase();
        Test.stopTest();
        //System.assertNotEquals(cse.Course_code__c, null);
    }

}