force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Campus_Location__c</fullName>
        <description>This is used by Custom metadata to determine the Application fee amount</description>
        <label>Campus Location Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                    <isActive>false</isActive>
                    <label>South Africa</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Existing_Aus_disability_support__c</fullName>
        <inlineHelpText>Whether or not the applicant has registered for disability support in an Australian tertiary institution in the last 5 years?</inlineHelpText>
        <label>Existing Australian disability support?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>Display GTE Risk Rating From Country Object</description>
        <formula>TEXT(Submission_Location_Country__r.GTE_Risk_Rating__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GTE Risk Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HasDisabilities__c</fullName>
        <label>HasDisabilities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residency_Status__c</fullName>
        <description>Used to define the applicant&apos;s/applications residency status at the point in time of the application.</description>
        <inlineHelpText>Used to define the applicant&apos;s/applications residency status at the point in time of the application.</inlineHelpText>
        <label>Residency Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DOM-AUS</fullName>
                    <label>I am an Australian Citizen (with or without dual citizenship)</label>
                </value>
                <value>
                    <fullName>DOM-NZ</fullName>
                    <label>I am a New Zealand Citizen</label>
                </value>
                <value>
                    <fullName>DOM-SUN</fullName>
                    <label>I am a Malaysian Citizen or a Malaysian Permanent Resident (i.e. I hold a Malaysian PR visa)</label>
                </value>
                <value>
                    <fullName>DOM-PR</fullName>
                    <label>I am an Australian Permanent Resident (i.e. I hold an Australian PR visa)</label>
                </value>
                <value>
                    <fullName>DOM-SA</fullName>
                    <label>I am a South African Citizen</label>
                </value>
                <value>
                    <fullName>DOM-HV</fullName>
                    <label>I hold an Australian Permanent Humanitarian Visa</label>
                </value>
                <value>
                    <fullName>INTRNTNL</fullName>
                    <label>I hold or will be getting an Australian Student Visa</label>
                </value>
                <value>
                    <fullName>INT-TEP</fullName>
                    <label>I hold a non-student Australian Temporary Visa (e.g. spouse visa or work visa)</label>
                </value>
                <value>
                    <fullName>INT-SUN-P</fullName>
                    <label>I hold a Malaysian Student or Temporary Pass</label>
                </value>
                <value>
                    <fullName>INT-SUN</fullName>
                    <label>I will be getting a Malaysian Student or Temporary Pass</label>
                </value>
                <value>
                    <fullName>INT-SA</fullName>
                    <label>I hold or will be getting a South African Student/Study Visa</label>
                </value>
                <value>
                    <fullName>DOM-IDN</fullName>
                    <label>I am an Indonesian Citizen</label>
                </value>
                <value>
                    <fullName>DOM-IDN-PR</fullName>
                    <label>I am an Indonesian Permanent Resident</label>
                </value>
                <value>
                    <fullName>INT-IDN-P</fullName>
                    <label>I currently have a visa to study in Indonesia</label>
                </value>
                <value>
                    <fullName>INT-IDN</fullName>
                    <label>I will be getting a visa to study in Indonesia</label>
                </value>
                <value>
                    <fullName>&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;</fullName>
                    <isActive>false</isActive>
                    <label>&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;</label>
                </value>
                <value>
                    <fullName>https://myapp.monash.edu/admissions/a244a000000SH9A/</fullName>
                    <isActive>false</isActive>
                    <label>https://myapp.monash.edu/admissions/a244a000000SH9A/</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Location_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the country for the submission location of the application</description>
        <label>Submission Location Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>ACP</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to course code, filtering out Unit Set courses</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>notEqual</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>ACP Courses</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preference_Number__c</fullName>
        <description>previous label: Pref#</description>
        <label>Preference Rank</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Attribute__c.object
<CustomObject>
    <description>This allows the definition of various country attributes (e.g. mapping to ISO codes, ABS codes, Australian border, department of education codes, restricted countries, flags for different user groups which can be used to drive sharing of records etc.)</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>The ISO country name</description>
        <inlineHelpText>The ISO country name</inlineHelpText>
        <label>ISO Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>Countries and some regional areas will receive a Monash GTE risk rating based on a variety of risk-related data and known environmental factors. The rating will inform the appropriate GTE assessment action taken by the Admissions office.</description>
        <inlineHelpText>The Monash GTE risk rating based on a variety of risk-related data</inlineHelpText>
        <label>GTE Risk Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Description__c</fullName>
        <externalId>true</externalId>
        <label>Course Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Country_List_1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Samoa, American</fullName>
        <label>American Samoa</label>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
        <label>Bahamas (the)</label>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
        <label>Bolivia (Plurinational State of)</label>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <description>As per ISO 3166</description>
    <masterLabel>Country List 1</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EncumbranceOutcomeController_Test.cls
/**
* @description Test class for EncumbranceOutcomeController
* @author      Sravani Naramsetti
* @date        05/02/2025
* @group       Admissions
*/
@isTest(isParallel=true)
public class EncumbranceOutcomeController_Test {
	@testsetup
    public static void setup() {
		//create contact
        contact applicant = StudFirst_TestHelper.createApplicant();
        insert applicant;
        //create country
        Country_Attribute__c country =  new Country_Attribute__c();
        country.Country__c = 'India';
        country.GTE_Risk_Rating__c = '2';
        insert country;        
		//create application
        Application__c app = StudFirst_TestHelper.createInternationalApplication(applicant, country);
        app.HasDisabilities__c = 'Yes';
        app.Residency_Status__c = 'INTRNTNL';
        app.Existing_Aus_disability_support__c = 'No';
        app.Campus_Location__c = 'Australia';
        app.Submission_Location_Country__c = country.Id;
        insert app;
        //create course
        Course__c Course = StudFirst_TestHelper.createCourse();
        course.Course_Description__c = 'Master of Advanced Manufacturing Technology';
        insert Course;
        //create course offering
        Course_Offering__c courseOffering = StudFirst_TestHelper.createCourseOffering(course);
        insert courseOffering;
        //create application course preference
        Application_Course_Preference__c coursePref = StudFirst_TestHelper.createCoursePreferences(app, applicant, courseOffering, course);
        coursePref.Preference_Number__c = '1';
        insert new List<Application_Course_Preference__c>{coursePref};
    }
    
    @isTest
    public static void revokedEncumbranceExists() {
        Contact ct = [Select Id from Contact LIMIT 1];
        //GIVEN: a ACP under Assessment
        Encumbrance__c enc = StudFirst_TestHelper.createEncumbranceAdmin(ct.Id);
        enc.eff_type__c = 'RVK_SRVC';
        enc.IsActive__c = true;
        insert enc;
        Application_Course_Preference__c acp = [Select Id from Application_Course_Preference__c LIMIT 1];
        Test.startTest();
        //WHEN: 'Offer/Conditional Offer' made and has Active 'RVK_SRVC' encumbrance on Contact
        List<EncumbranceOutcomeController.ValidationResponse> resp=EncumbranceOutcomeController.encumbrancesOutcomeCheck(new List<Id>{acp.Id});
        //THEN: hasEncumbrance is true
        Assert.areEqual(resp[0].hasEncumbrance,true);
        Test.stopTest();
    }
    
    @isTest
    public static void withdrawnEncumbranceExists() {
        Contact ct = [Select Id from Contact LIMIT 1];
        //GIVEN: a ACP under Assessment
        Encumbrance__c enc = StudFirst_TestHelper.createEncumbranceAdmin(ct.Id);
        enc.eff_type__c = 'SUS_SRVC';
        enc.IsActive__c = true;
        insert enc;
        Application_Course_Preference__c acp = [Select Id from Application_Course_Preference__c LIMIT 1];
        Test.startTest();
        //WHEN: 'Offer/Conditional Offer' made and has Active 'SUS_SRVC' encumbrance on Contact
        List<EncumbranceOutcomeController.ValidationResponse> resp=EncumbranceOutcomeController.encumbrancesOutcomeCheck(new List<Id>{acp.Id});
        //THEN: isBlocked is true
        Assert.areEqual(resp[0].isBlocked,true);
        Test.stopTest();
    }
    
    @isTest
    public static void excCourseExists() {
        Contact ct = [Select Id from Contact LIMIT 1];
        //GIVEN: a ACP under Assessment
        Encumbrance__c enc = StudFirst_TestHelper.createEncumbranceAdmin(ct.Id);
        enc.eff_type__c = 'EXC_COURSE';
        enc.IsActive__c = true;
        enc.enc_course_code__c = 'M00001';
        insert enc;
        Application_Course_Preference__c acp = [Select Id from Application_Course_Preference__c LIMIT 1];
        Test.startTest();
        //WHEN: 'Offer/Conditional Offer' made and has Active 'EXC_COURSE' encumbrance on Contact
        List<EncumbranceOutcomeController.ValidationResponse> resp=EncumbranceOutcomeController.encumbrancesOutcomeCheck(new List<Id>{acp.Id});
        //THEN: isBlocked is false
        Assert.areEqual(resp[0].isBlocked,false);
        Test.stopTest();
    }
    
    @isTest
    public static void excCourseGroupExists() {
        Contact ct = [Select Id from Contact LIMIT 1];
        //GIVEN: a ACP under Assessment
        course_group__c cg = new course_group__c (Course_Group__c='ABCD_1234',Type__c='Combined',Responsible_Org_Unit_Code__c='Fish',Is_Active__c=true);
        insert cg;
        Encumbrance__c enc = StudFirst_TestHelper.createEncumbranceAdmin(ct.Id);
        enc.eff_type__c = 'EXC_CRS_GP';
        enc.IsActive__c = true;
        enc.enc_course_code__c = 'M00001';
        enc.enc_course_group__c = cg.Id;
        insert enc;
        
        Application_Course_Preference__c acp = [Select Id from Application_Course_Preference__c LIMIT 1];
        Test.startTest();
        //WHEN: 'Offer/Conditional Offer' made and has Active 'EXC_CRS_GP' encumbrance on Contact
        List<EncumbranceOutcomeController.ValidationResponse> resp=EncumbranceOutcomeController.encumbrancesOutcomeCheck(new List<Id>{acp.Id});
        //THEN: isBlocked is false
        Assert.areEqual(resp[0].isBlocked,false);
        Test.stopTest();
    }
    
    @isTest
    public static void revokedEncumbranceAndCourseCodeExists() {
        Contact ct = [Select Id from Contact LIMIT 1];
        //GIVEN: a ACP under Assessment
        Encumbrance__c enc = StudFirst_TestHelper.createEncumbranceAdmin(ct.Id);
        enc.eff_type__c = 'RVK_SRVC';
        enc.IsActive__c = true;
        
        Encumbrance__c enc1 = StudFirst_TestHelper.createEncumbranceAdmin(ct.Id);
        enc1.eff_type__c = 'EXC_COURSE';
        enc1.IsActive__c = true;
        enc1.enc_course_code__c = 'M00001';
        
        Encumbrance__c enc2 = StudFirst_TestHelper.createEncumbranceAdmin(ct.Id);
        enc2.eff_type__c = 'RVK_SRVC';
        enc2.IsActive__c = true;
        insert new List<Encumbrance__c>{enc,enc1,enc2};
        Application_Course_Preference__c acp = [Select Id from Application_Course_Preference__c LIMIT 1];
        Test.startTest();
        //WHEN: 'Offer/Conditional Offer' made and has Active 'RVK_SRVC' and 'EXC_COURSE' encumbrance on Contact
        List<EncumbranceOutcomeController.ValidationResponse> resp=EncumbranceOutcomeController.encumbrancesOutcomeCheck(new List<Id>{acp.Id});
        //THEN: hasEncumbrance is true and isBlocked is true
        Assert.areEqual(resp[0].hasEncumbrance,true);
        Assert.areEqual(resp[0].isBlocked,true);
        Test.stopTest();
    }
}