force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>ACP</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to course code, filtering out Unit Set courses</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>notEqual</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>ACP Courses</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Qualification_Provided__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <label>Contact Qualification</label>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Application Qualification Provided</label>
    <nameField>
        <displayFormat>AQP-{000000}</displayFormat>
        <label>Application Qualification Provided ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Qualifications Provided</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Work_Experience_Provided__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Work Experiences Provided</relationshipLabel>
        <relationshipName>Application_Work_Experiences_Provided</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Experience__c</fullName>
        <label>Work Experience</label>
        <referenceTo>Work_Experience__c</referenceTo>
        <relationshipLabel>Application Provided On</relationshipLabel>
        <relationshipName>Application_Work_Experiences_Provided</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Work Experience Provided</label>
    <nameField>
        <displayFormat>AWEP-{000000}</displayFormat>
        <label>App. Work Experience Provided Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Work Experiences Provided</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position Held</description>
        <label>Position Held</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualification Lookup</label>
        <referenceTo>Qualification__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Attribute__c.object
<CustomObject>
    <description>This allows the definition of various country attributes (e.g. mapping to ISO codes, ABS codes, Australian border, department of education codes, restricted countries, flags for different user groups which can be used to drive sharing of records etc.)</description>
    <fields>
        <fullName>Callista_Code__c</fullName>
        <description>The unique identifier for the country record in Callista</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier for a country record in Callista</inlineHelpText>
        <label>Callista Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The ISO country name</description>
        <inlineHelpText>The ISO country name</inlineHelpText>
        <label>ISO Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_1</valueSetName>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Callista_Code__c</fullName>
        <externalId>true</externalId>
        <label>Callista Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <displayFormat>QUAL-{000}</displayFormat>
        <label>Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Person_First_Name__c</fullName>
        <label>Contact Person First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>Work Experiences</relationshipLabel>
        <relationshipName>Work_Experiences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employer_Name__c</fullName>
        <label>Employer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Work Experience</label>
    <nameField>
        <displayFormat>WEX-{000000}</displayFormat>
        <label>Work Experience ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Country_List_1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Samoa, American</fullName>
        <label>American Samoa</label>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
        <label>Bahamas (the)</label>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
        <label>Bolivia (Plurinational State of)</label>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <description>As per ISO 3166</description>
    <masterLabel>Country List 1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country_List_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Adelie Land (France)</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua And Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Australian External Territories, NEC</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius And Saba</fullName>
        <label>Bonaire, Sint Eustatius and Saba</label>
    </customValue>
    <description>As per Callista</description>
    <masterLabel>Country List 2</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/APNGApplicationSelector_Test.cls
/**
 * @description       : Test classes for APNGApplicationSelector
 * @author            : Ben Greenland
 * @group             :
 * @last modified on  : 2024-10-04
 * @last modified by  : Ben Greenland
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   2024-10-03   Ben Greenland   Initial Version
 **/

@isTest(isparallel=true)
private class APNGApplicationSelector_Test {
	@TestSetup
	static void makeData() {
		TriggerCommon.disableTrigger('Country_Attribute__c');
		TriggerCommon.disableTrigger('Account');
		TriggerCommon.disableTrigger('Contact');
		TriggerCommon.disableTrigger('User');
		AgentPortalTestDataBuilder.AgentPortalUser portalUser = new AgentPortalTestDataBuilder.AgentPortalUser().build();
		System.runAs(portalUser.testUser) {
			Country_Attribute__c country = new Country_Attribute__c(
				Name = 'INDIA',
				Callista_Code__c = '7103',
				Country__c = 'INDIA'
			);
			insert country;

			Country_Attribute__c country1 = new Country_Attribute__c(
				Name = 'AUSTRALIA',
				Callista_Code__c = BDPConstants.AUSTRALIA_CALLISTA_CODE,
				Country__c = 'Australia'
			);
			insert country1;

			insert new Bypass_Mute_Request__c(Bypass_All_Flows__c = false);
			Contact applicant = StudFirst_TestHelper.createInternationalApplicant();
			insert applicant;
			Application__c application = StudFirst_TestHelper.createInternationalApplication(applicant, country);
			insert application;
			Course__c course = StudFirst_TestHelper.createCourse();
			insert course;
			Course_Offering__c courseOffering = StudFirst_TestHelper.createCourseOffering(course);
			insert courseOffering;
			Qualification__c qual = StudFirst_TestHelper.createQualification('Master of puppets');
			insert qual;
			Contact_Qualification__c contactQual = StudFirst_TestHelper.createContactQualification(
				applicant,
				qual,
				'Tertiary Education'
			);
			insert contactQual;
			// create the apq
			Application_Qualification_Provided__c aqp = new Application_Qualification_Provided__c(
				Contact_Qualification__c = contactQual.Id,
				Application__c = application.id
			);
			insert aqp;

			Application_Course_Preference__c acp = StudFirst_TestHelper.createCoursePreferences(
				application,
				applicant,
				courseOffering,
				course
			);
			insert acp;

			Work_Experience__c wex = StudFirst_TestHelper.createWorkExperience(applicant);
			wex.Position__c = 'Cat';
			wex.Employer_Name__c = 'Bunnings';
			wex.Contact_Person_First_Name__c = 'Bobo';
			insert wex;
			Application_Work_Experience_Provided__c awep = new Application_Work_Experience_Provided__c(
				Application__c = application.Id,
				Work_Experience__c = wex.Id
			);
			insert awep;
		}
		TriggerCommon.enableTrigger('Country_Attribute__c');
		TriggerCommon.enableTrigger('Account');
		TriggerCommon.enableTrigger('Contact');
		TriggerCommon.enableTrigger('User');
	}

	@IsTest
	static void testgetApplicationDetails() {
		//GIVEN : an application with Course Preferences
		Application__c app = [SELECT Id, Name FROM Application__c LIMIT 1];
		Test.startTest();
		System.runAs(new AgentPortalTestDataFactory.AgentPortalTestDataFactoryUtil().getAgentUser()) {
			//WHEN : I retrieve the Course Preference wrapper as agent
			APNGApplicationPayload.ApplicationDetails ApplicationDetails = APNGApplicationSelector.getApplicationDetails(
				app.Name
			);
			//THEN : the Course Preference wrapper should contain the Course Preferences
			Assert.areEqual(app.Id, ApplicationDetails.details.id, 'Id does not match');
			Assert.isNotNull(ApplicationDetails.coursePreferences, 'Course Preferences should not be null');
		}
		Test.stopTest();
	}

	@IsTest
	static void testgetApplicationDetailsNotFound() {
		//GIVEN : an application with Course Preferences
		Test.startTest();
		//WHEN : AGENT user retrieves the Course Preference wrapper with a nonexistant name
		System.runAs(new AgentPortalTestDataFactory.AgentPortalTestDataFactoryUtil().getAgentUser()) {
			try {
				APNGApplicationSelector.getApplicationDetails('Somthingbad');
				//THEN : the Course Preference wrapper should be null
			} catch (Exception e) {
				Assert.isTrue(
					e.getMessage().contains('Application not found'),
					'Application not found exception should be thrown'
				);
			}
		}
		Test.stopTest();
	}

	@IsTest
	static void getContactQualificationsByApplicationId() {
		//GIVEN : an application with qualifications
		Application__c app = [SELECT Id, Name FROM Application__c LIMIT 1];
		Test.startTest();
		//WHEN : I retrieve the Qualification wrapper as agent
		System.runAs(new AgentPortalTestDataFactory.AgentPortalTestDataFactoryUtil().getAgentUser()) {
			APNGApplicationPayload.Qualifications quals = APNGApplicationSelector.getContactQualificationsByApplicationId(
				app.Name
			);
			//THEN : the Qualification wrapper should contain the Qualification data
			Assert.isTrue(quals.recordCount > 0, 'There should be at least one Qualifications');
		}
		Test.stopTest();
	}

	@IsTest
	static void getContactQualificationsByApplicationIdException() {
		Test.startTest();
		//GIVEN an getAgentUser requesting qualifications with a bad Application Name
		System.runAs(new AgentPortalTestDataFactory.AgentPortalTestDataFactoryUtil().getAgentUser()) {
			try {
				//WHEN : I retrieve the Qualification wrapper as agent
				APNGApplicationSelector.getContactQualificationsByApplicationId('oops');
			}
			//THEN  : an Exception should be thrown
			catch (Exception e) {
				Assert.isTrue(
					e.getMessage().contains('Application not found'),
					'Application not found exception should be thrown'
				);
			}
		}
		Test.stopTest();
	}

	@IsTest
	static void getWorkExperiencesByApplicationIdTest() {
		//GIVEN : an application with Work Experience Records
		Application__c app = [SELECT Id, Name FROM Application__c LIMIT 1];
		Test.startTest();
		//WHEN : I retrieve the Work Experience wrapper as agent
		System.runAs(new AgentPortalTestDataFactory.AgentPortalTestDataFactoryUtil().getAgentUser()) {
			APNGApplicationPayload.WorkExperiences quals = APNGApplicationSelector.getWorkExperiencesByApplicationId(
				app.Name
			);
			//THEN : the Work Experience wrapper should contain the Work Experience data
			Assert.isTrue(quals.recordCount > 0, 'There should be at least one Qualifications');
		}
		Test.stopTest();
	}

	@IsTest
	static void getWorkExperiencesByApplicationIdException() {
		Test.startTest();
		//GIVEN an getAgentUser requesting qualifications with a bad Application Name
		System.runAs(new AgentPortalTestDataFactory.AgentPortalTestDataFactoryUtil().getAgentUser()) {
			try {
				//WHEN : I retrieve the Work Experience records as agent
				APNGApplicationSelector.getWorkExperiencesByApplicationId('oops');
			}
			//THEN  : an Exception should be thrown
			catch (Exception e) {
				Assert.isTrue(
					e.getMessage().contains('Application not found'),
					'Application not found exception should be thrown'
				);
			}
		}
		Test.stopTest();
	}
}