force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Submission_Progress__c</fullName>
        <description>Defines the progress of submission that the applicant is going through.</description>
        <label>Submission Progress</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Study__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Declaration</fullName>
                    <default>true</default>
                    <label>Declaration</label>
                </value>
                <value>
                    <fullName>Personal Details</fullName>
                </value>
                <value>
                    <fullName>Study Preferences</fullName>
                </value>
                <value>
                    <fullName>Credentials</fullName>
                </value>
                <value>
                    <fullName>Scholarship</fullName>
                </value>
                <value>
                    <fullName>Application Details</fullName>
                </value>
                <value>
                    <fullName>Research Program</fullName>
                </value>
                <value>
                    <fullName>English Proficiency</fullName>
                </value>
                <value>
                    <fullName>Qualifications</fullName>
                </value>
                <value>
                    <fullName>Awards, Prizes &amp; Scholarship</fullName>
                </value>
                <value>
                    <fullName>Employment &amp; Research Experience</fullName>
                </value>
                <value>
                    <fullName>Referees</fullName>
                </value>
                <value>
                    <fullName>Publications</fullName>
                </value>
                <value>
                    <fullName>Creative Works</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>Theatre Performance</fullName>
                </value>
                <value>
                    <fullName>Exhibitions</fullName>
                </value>
                <value>
                    <fullName>Additional Supporting Information</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Application Fee</fullName>
                </value>
                <value>
                    <fullName>Submit</fullName>
                </value>
                <value>
                    <fullName>Validate &amp; Submit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/submissionProgressPicklist.cls
global class submissionProgressPicklist extends VisualEditor.DynamicPickList{
    
    global static List<VisualEditor.DataRow> getAllOptions()
    {
        Schema.DescribeFieldResult fieldResult = Application__c.Submission_Progress__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<VisualEditor.DataRow> dataRows = new List<VisualEditor.DataRow>();
        
        for( Schema.PicklistEntry f : ple)
        {
            VisualEditor.DataRow option = new VisualEditor.DataRow(f.getLabel(), f.getValue());
            dataRows.add(option);
        }
        return dataRows;
    }
    
    global override VisualEditor.DataRow getDefaultValue(){
        
        List<VisualEditor.DataRow> allOptions = getAllOptions();
        return allOptions[0];        
    }
    
    global override VisualEditor.DynamicPickListRows getValues() {
        List<VisualEditor.DataRow> allOptions = getAllOptions();        
        VisualEditor.DynamicPickListRows myValues = new VisualEditor.DynamicPickListRows();
        myValues.addAllRows(allOptions);
        return myValues;
    }
}