force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Campus_Location__c</fullName>
        <description>This is used by Custom metadata to determine the Application fee amount</description>
        <label>Campus Location Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                    <isActive>false</isActive>
                    <label>South Africa</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Existing_Aus_disability_support__c</fullName>
        <inlineHelpText>Whether or not the applicant has registered for disability support in an Australian tertiary institution in the last 5 years?</inlineHelpText>
        <label>Existing Australian disability support?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>Display GTE Risk Rating From Country Object</description>
        <formula>TEXT(Submission_Location_Country__r.GTE_Risk_Rating__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GTE Risk Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HasDisabilities__c</fullName>
        <label>HasDisabilities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Residency_Status__c</fullName>
        <description>Used to define the applicant&apos;s/applications residency status at the point in time of the application.</description>
        <inlineHelpText>Used to define the applicant&apos;s/applications residency status at the point in time of the application.</inlineHelpText>
        <label>Residency Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DOM-AUS</fullName>
                    <label>I am an Australian Citizen (with or without dual citizenship)</label>
                </value>
                <value>
                    <fullName>DOM-NZ</fullName>
                    <label>I am a New Zealand Citizen</label>
                </value>
                <value>
                    <fullName>DOM-SUN</fullName>
                    <label>I am a Malaysian Citizen or a Malaysian Permanent Resident (i.e. I hold a Malaysian PR visa)</label>
                </value>
                <value>
                    <fullName>DOM-PR</fullName>
                    <label>I am an Australian Permanent Resident (i.e. I hold an Australian PR visa)</label>
                </value>
                <value>
                    <fullName>DOM-SA</fullName>
                    <label>I am a South African Citizen</label>
                </value>
                <value>
                    <fullName>DOM-HV</fullName>
                    <label>I hold an Australian Permanent Humanitarian Visa</label>
                </value>
                <value>
                    <fullName>INTRNTNL</fullName>
                    <label>I hold or will be getting an Australian Student Visa</label>
                </value>
                <value>
                    <fullName>INT-TEP</fullName>
                    <label>I hold a non-student Australian Temporary Visa (e.g. spouse visa or work visa)</label>
                </value>
                <value>
                    <fullName>INT-SUN-P</fullName>
                    <label>I hold a Malaysian Student or Temporary Pass</label>
                </value>
                <value>
                    <fullName>INT-SUN</fullName>
                    <label>I will be getting a Malaysian Student or Temporary Pass</label>
                </value>
                <value>
                    <fullName>INT-SA</fullName>
                    <label>I hold or will be getting a South African Student/Study Visa</label>
                </value>
                <value>
                    <fullName>DOM-IDN</fullName>
                    <label>I am an Indonesian Citizen</label>
                </value>
                <value>
                    <fullName>DOM-IDN-PR</fullName>
                    <label>I am an Indonesian Permanent Resident</label>
                </value>
                <value>
                    <fullName>INT-IDN-P</fullName>
                    <label>I currently have a visa to study in Indonesia</label>
                </value>
                <value>
                    <fullName>INT-IDN</fullName>
                    <label>I will be getting a visa to study in Indonesia</label>
                </value>
                <value>
                    <fullName>&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;</fullName>
                    <isActive>false</isActive>
                    <label>&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;</label>
                </value>
                <value>
                    <fullName>https://myapp.monash.edu/admissions/a244a000000SH9A/</fullName>
                    <isActive>false</isActive>
                    <label>https://myapp.monash.edu/admissions/a244a000000SH9A/</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Location_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the country for the submission location of the application</description>
        <label>Submission Location Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Qualification_Provided__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <label>Contact Qualification</label>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>GTE Risk Rating for Qualifications Provided for Application</description>
        <formula>TEXT(Contact_Qualification__r.Qualification_Country__r.GTE_Risk_Rating__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GTE Risk Rating</label>
        <type>Text</type>
    </fields>
    <label>Application Qualification Provided</label>
    <nameField>
        <displayFormat>AQP-{000000}</displayFormat>
        <label>Application Qualification Provided ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Qualifications Provided</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Document__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to application record if relevant</description>
        <inlineHelpText>Link to application record if relevant</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Document</label>
    <nameField>
        <displayFormat>CNDC-{000000}</displayFormat>
        <label>Contact Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>Display GTE Risk Rating From Country Object</description>
        <formula>TEXT(Qualification_Country__r.GTE_Risk_Rating__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GTE Risk Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualification Lookup</label>
        <referenceTo>Qualification__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Attribute__c.object
<CustomObject>
    <description>This allows the definition of various country attributes (e.g. mapping to ISO codes, ABS codes, Australian border, department of education codes, restricted countries, flags for different user groups which can be used to drive sharing of records etc.)</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>The ISO country name</description>
        <inlineHelpText>The ISO country name</inlineHelpText>
        <label>ISO Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>Countries and some regional areas will receive a Monash GTE risk rating based on a variety of risk-related data and known environmental factors. The rating will inform the appropriate GTE assessment action taken by the Admissions office.</description>
        <inlineHelpText>The Monash GTE risk rating based on a variety of risk-related data</inlineHelpText>
        <label>GTE Risk Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Country_List_1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Samoa, American</fullName>
        <label>American Samoa</label>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
        <label>Bahamas (the)</label>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
        <label>Bolivia (Plurinational State of)</label>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <description>As per ISO 3166</description>
    <masterLabel>Country List 1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country_List_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Adelie Land (France)</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua And Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Australian External Territories, NEC</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius And Saba</fullName>
        <label>Bonaire, Sint Eustatius and Saba</label>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <description>As per Callista</description>
    <masterLabel>Country List 2</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/assessmentsDSSandGTECheck_Test.cls
/**
 *  Test coverage written for the assessmentsDSSandGTECheck
    @author  Suman Gunaganti
 */
@isTest
public with sharing class assessmentsDSSandGTECheck_Test {
    @testsetup static void setup() {
        Account ac = new Account(Name='ABC');
        //insert ac;
        contact applicant = StudFirst_TestHelper.createApplicant();
        insert applicant;
        
        Country_Attribute__c country =  new Country_Attribute__c();
        country.Country__c = 'India';
        country.GTE_Risk_Rating__c = '2';
        insert country;        

        Application__c app = StudFirst_TestHelper.createInternationalApplication(applicant, country);
        app.HasDisabilities__c = 'Yes';
        app.Residency_Status__c = 'INTRNTNL';
        app.Existing_Aus_disability_support__c = 'No';
        app.Campus_Location__c = 'Australia';
        app.Submission_Location_Country__c = country.Id;
        insert app;
        
        Qualification__c qual = StudFirst_TestHelper.createQualification('custom qual');
        insert qual;
        
        Contact_Qualification__c cqual = StudFirst_TestHelper.createContactQualification(applicant, qual, 'Secondary Education');
        cqual.Qualification_Country__c = country.Id;
        insert cqual;
        
        Application_Qualification_Provided__c aqp = StudFirst_TestHelper.createAppQualProvided(app.Id, cqual.Id);
        insert aqp;
        
        Contact_Document__c cd = StudFirst_TestHelper.createContactDocument(applicant.id, cqual.id);
        cd.Document_Type__c = 'SECSCH_RES';
        insert cd;
        
        Course__c Course = StudFirst_TestHelper.createCourse();
        course.Course_Description__c = 'Master of Advanced Manufacturing Technology';
        insert Course;
        
        Course_Offering__c courseOffering = StudFirst_TestHelper.createCourseOffering(course);
        insert courseOffering;
        
        Application_Course_Preference__c coursePref = StudFirst_TestHelper.createCoursePreferences(app, applicant, courseOffering, course);
        coursePref.Preference_Number__c = '1';
        insert coursePref;
    }
    static testmethod void testDSSandGTECheck(){
        Map<Id,Application_Course_Preference__c> acps = new Map<Id,Application_Course_Preference__c>([select id from Application_Course_Preference__c LIMIT 1]);
        List<Id> acpIds = new List<id>();
        acpIds.addAll(acps.keySet());
        List<assessmentsDSSandGTECheck.DSSandGTECheckResponse> response = assessmentsDSSandGTECheck.DSSandGTECheck(acpIds);
        System.assertEquals('Required', response.get(0).isDSSCheckRequired);
    }

    static testmethod void testDSSandGTECheckGTECountry(){
        Map<Id,Application_Course_Preference__c> acps = new Map<Id,Application_Course_Preference__c>([select id from Application_Course_Preference__c LIMIT 1]);
        List<Id> acpIds = new List<id>();
        acpIds.addAll(acps.keySet());
        List<assessmentsDSSandGTECheck.DSSandGTECheckResponse> response = assessmentsDSSandGTECheck.DSSandGTECheck(acpIds);
        System.assertEquals('Required', response.get(0).isGTECheckRequired);
        System.assertEquals('India and Nepal', response.get(0).GTEReviewGroup);
    }
    
    static testmethod void testDSSandGTECheckGTECountryGTENotRequired(){
        Course__c course = [SELECT Course_Description__c FROM Course__c LIMIT 1];
        course.Course_Description__c = 'Bachelor of Engineering';
        update course;
        Application_Course_Preference__c acp = [select id from Application_Course_Preference__c LIMIT 1];
        List<Id> acpIds = new List<id>{acp.id};
        List<assessmentsDSSandGTECheck.DSSandGTECheckResponse> response = assessmentsDSSandGTECheck.DSSandGTECheck(acpIds);
        System.assertEquals('Required', response.get(0).isGTECheckRequired);
    }
}