force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>ACP</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to course code, filtering out Unit Set courses</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>notEqual</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>ACP Courses</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Qualification_Provided__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <label>Contact Qualification</label>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Application Qualification Provided</label>
    <nameField>
        <displayFormat>AQP-{000000}</displayFormat>
        <label>Application Qualification Provided ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Qualifications Provided</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Document__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to application record if relevant</description>
        <inlineHelpText>Link to application record if relevant</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Qualification</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are no Qualifications assigned to this contact</errorMessage>
            <filterItems>
                <field>$Source.Contact__c</field>
                <operation>equals</operation>
                <valueField>Contact_Qualification__c.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipLabel>Qualification Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Contact Document</label>
    <nameField>
        <displayFormat>CNDC-{000000}</displayFormat>
        <label>Contact Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualification Lookup</label>
        <referenceTo>Qualification__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Qualification__c.object
<CustomObject>
    <label>Qualification</label>
    <nameField>
        <displayFormat>QUAL-{000}</displayFormat>
        <label>Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CancelAdmissionApplicationTest.cls
@isTest
public class CancelAdmissionApplicationTest {
    TestMethod
    private static void cancelApplication()
    {
        // create community user
        User applicant = StudFirst_TestHelper.createCommunityUser();
        Contact c = [SELECT id FROM Contact WHERE id =: applicant.contactId];
            
        System.runAs(applicant)
        {
            // create application
            Application__c application = StudFirst_TestHelper.createApplication(c.Id);
            insert application;
    
            // Course
            Course__c course = StudFirst_TestHelper.createCourse();
            insert course;
    
            // offering
            Course_Offering__c offering = StudFirst_TestHelper.createCourseOffering(course);
            insert offering;
    
            // create ACP
            Application_Course_Preference__c acp = StudFirst_TestHelper.createCoursePreferences(application, c, offering, course);
            insert acp;
            
            // create Cd
            Contact_Document__c cd = StudFirst_TestHelper.createContactDocument(c.Id);
            insert cd;
            
            // create Qualification
            Qualification__c qual = StudFirst_TestHelper.createQualification('English');
            insert qual;
            
            // Create Contact Qualifications
            Contact_Qualification__c contactQual = StudFirst_TestHelper.createContactQualification(c, qual, 'English Test');
            insert contactQual;
            
            Application_Qualification_Provided__c appQualProvided = StudFirst_TestHelper.createAppQualProvided(application.id, contactQual.id);
            insert appQualProvided;
            /*
            List<ContentDocument> fileList = [SELECT id FROM ContentDocument];
            System.assertEquals(0, fileList.size(), 'fileList is not deleted');
            
            
            // Create a file
            ContentDocument file = FileUploadController_Test.createTestDocument(true);
            String docTypeValue = FileUploadController_Test.getDocumentTypeValue(0);
            String docSubType = '';
            String comments = 'testing some comments ';
            Map<String, Object> mapResults = FileUploadController.saveFileAndContactDocument(file.Id, c.Id, application.Id, docTypeValue, docSubType, comments);
            */
        
            List<application__c> appList = [SELECT id FROM application__c where applicant__c = :c.id];
            System.assertEquals(1, appList.size(), '1) appList is not created');
            
            List<Application_Course_Preference__c> acpList = [SELECT id FROM Application_Course_Preference__c where applicant__c = :c.id];
            System.assertEquals(1, acpList.size(), '1) acpList is not created');
            
            List<Contact_Qualification__c> conQualList = [SELECT id FROM Contact_Qualification__c where contact__c = :c.id];
            System.assertEquals(1, conQualList.size(), '1) conQualList is not created');
            
            List<Contact_Document__c> conDocList = [SELECT id FROM Contact_Document__c where contact__c = :c.id];
            System.assertEquals(1, conDocList.size(), '1) conDocList is not created');
            
            Test.startTest();
            // Cancel the application
            appHomeDraftCC.cancelApplication(application);
            Test.stopTest();
            // Process builder will run and will delete the apps and acps and contact children
            
            appList = [SELECT id FROM application__c where applicant__c = :c.id];
            System.assertEquals(0, appList.size(), '2) appList is not deleted');
            
            acpList = [SELECT id FROM Application_Course_Preference__c where applicant__c = :c.id];
            System.assertEquals(0, acpList.size(), '2) acpList is not deleted');
            
            conQualList = [SELECT id FROM Contact_Qualification__c where contact__c = :c.id];
            System.assertEquals(0, conQualList.size(), '2) conQualList is not deleted');
        }
    }
}