force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Australian_Immigration_Office_Issued__c</fullName>
        <description>Indicates which Australian immigration office issued the visa to the applicant</description>
        <inlineHelpText>Which Australian Immigration Office issued your visa?</inlineHelpText>
        <label>Australian Immigration Office Issued</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campus_Location__c</fullName>
        <description>This is used by Custom metadata to determine the Application fee amount</description>
        <label>Campus Location Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                    <isActive>false</isActive>
                    <label>South Africa</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Passport_Number__c</fullName>
        <description>To capture the passport number of the applicant</description>
        <label>Passport Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visa_Number__c</fullName>
        <description>Capture the visa number</description>
        <label>Visa Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visa_Start_Date__c</fullName>
        <description>Capture the Visa validity start date</description>
        <label>Visa Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Visa_Type__c</fullName>
        <description>Capture the type of visa</description>
        <label>Visa Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>010</fullName>
                    <label>010 - BRIDGING A THAT APPLY FOR OTHER SUBCLASSES</label>
                </value>
                <value>
                    <fullName>010 ESOS</fullName>
                    <label>010 ESOS - BRIDGING A FOR SUBCLASS 570, 571, 572, 573, 574 OR 575</label>
                </value>
                <value>
                    <fullName>020</fullName>
                    <label>020 - BRIDGING B THAT APPLY FOR OTHER SUBCLASSES</label>
                </value>
                <value>
                    <fullName>020 ESOS</fullName>
                    <label>020 ESOS - BRIDGING B FOR SUBCLASS 570, 571, 572, 573, 574 OR 575</label>
                </value>
                <value>
                    <fullName>030</fullName>
                    <label>030 - BRIDGING C THAT APPLY FOR OTHER SUBCLASSES</label>
                </value>
                <value>
                    <fullName>030 ESOS</fullName>
                    <label>030 ESOS - BRIDGING C FOR SUBCLASS 570, 571, 572, 573, 574 OR 575</label>
                </value>
                <value>
                    <fullName>040</fullName>
                    <label>040 - BRIDGING D (PROSPECTIVE APPLICANT)</label>
                </value>
                <value>
                    <fullName>041</fullName>
                    <label>041 - BRIDGING D (NON APPLICANT)</label>
                </value>
                <value>
                    <fullName>050</fullName>
                    <label>050 - BRIDGING E (GENERAL) THAT APPLY FOR OTHERS SUBCLASSES</label>
                </value>
                <value>
                    <fullName>050 ESOS</fullName>
                    <label>050 ESOS - BRIDGING E FOR SUBCLASS 570, 571, 572, 573, 574 OR 575</label>
                </value>
                <value>
                    <fullName>051</fullName>
                    <label>051 - BRIDGING E (PROTECTION VISA APPLICANT)</label>
                </value>
                <value>
                    <fullName>060</fullName>
                    <label>060 - BRIDGING F</label>
                </value>
                <value>
                    <fullName>070</fullName>
                    <label>070 - BRIDGING (REMOVAL PENDING)</label>
                </value>
                <value>
                    <fullName>121</fullName>
                    <label>121 - EMPLOYER NOMINATION SCHEME</label>
                </value>
                <value>
                    <fullName>132</fullName>
                    <label>132 - BUSINESS TALENT</label>
                </value>
                <value>
                    <fullName>159</fullName>
                    <label>159 - PROVISIONAL RESIDENT RETURN</label>
                </value>
                <value>
                    <fullName>160</fullName>
                    <label>160 - BUSINESS OWNER (PROVISIONAL)</label>
                </value>
                <value>
                    <fullName>161</fullName>
                    <label>161 - SENIOR EXECUTIVE (PROVISIONAL)</label>
                </value>
                <value>
                    <fullName>162</fullName>
                    <label>162 - INVESTOR (PROVISIONAL)</label>
                </value>
                <value>
                    <fullName>163</fullName>
                    <label>163 - STATE/TERRITORY SPONSORED BUSINESS OWNER (PROVISIONAL)</label>
                </value>
                <value>
                    <fullName>164</fullName>
                    <label>164 - STATE/TERRITORY SPONSORED SENIOR EXECUTIVE (PROVISIONAL)</label>
                </value>
                <value>
                    <fullName>165</fullName>
                    <label>165 - STATE/TERRITORY SPONSORED INVESTOR (PROVISIONAL)</label>
                </value>
                <value>
                    <fullName>173</fullName>
                    <label>173 - CONTRIBUTORY PARENT (TEMPORARY)</label>
                </value>
                <value>
                    <fullName>187</fullName>
                    <label>187 - REGIONAL SPONSORED MIGRATION SCHEME VISA</label>
                </value>
                <value>
                    <fullName>188</fullName>
                    <label>188 - BUSINESS INNOVATION AND INVESTMENT (PROVISIONAL)</label>
                </value>
                <value>
                    <fullName>300</fullName>
                    <label>300 - PROSPECTIVE MARRIAGE</label>
                </value>
                <value>
                    <fullName>302</fullName>
                    <label>302 - EMERGENCY (PERMANENT VISA APPLICANT)</label>
                </value>
                <value>
                    <fullName>303</fullName>
                    <label>303 - EMERGENCY (TEMPORARY VISA APPLICANT)</label>
                </value>
                <value>
                    <fullName>309</fullName>
                    <label>309 - SPOUSE</label>
                </value>
                <value>
                    <fullName>310</fullName>
                    <label>310 - INTERDEPENDENCY</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Document__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to application record if relevant</description>
        <inlineHelpText>Link to application record if relevant</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Upload_Successful__c</fullName>
        <defaultValue>false</defaultValue>
        <description>triggering field for callout to callista for files</description>
        <label>File Upload Successful</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <label>Filename</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Certified name change documents uploaded with the on-line graduation application.</fullName>
                </value>
                <value>
                    <fullName>Certified previous qualification documents uploaded with the on-line graduation application.</fullName>
                </value>
                <value>
                    <fullName>Course offer acceptance document</fullName>
                </value>
                <value>
                    <fullName>Credit application</fullName>
                </value>
                <value>
                    <fullName>Curriculum vitae</fullName>
                </value>
                <value>
                    <fullName>Diploma or degree certificate</fullName>
                </value>
                <value>
                    <fullName>Employment reference</fullName>
                </value>
                <value>
                    <fullName>HDR application summary</fullName>
                </value>
                <value>
                    <fullName>Higher Degree Research candidature offer or confirmation letter.</fullName>
                </value>
                <value>
                    <fullName>Image of artwork for Art and Design folio</fullName>
                </value>
                <value>
                    <fullName>Invitation Letter for Higher Dreams Application</fullName>
                </value>
                <value>
                    <fullName>Learning Portfolio</fullName>
                </value>
                <value>
                    <fullName>Open Universities exams special local invigilator verification</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other document type not listed</fullName>
                </value>
                <value>
                    <fullName>Prior Application details for HDR</fullName>
                </value>
                <value>
                    <fullName>Proof of change of name</fullName>
                </value>
                <value>
                    <fullName>Proof of Citizenship/Residency or Identity</fullName>
                </value>
                <value>
                    <fullName>Proof of employment</fullName>
                </value>
                <value>
                    <fullName>Proof of English language medium of instruction</fullName>
                </value>
                <value>
                    <fullName>Proof of professional registration</fullName>
                </value>
                <value>
                    <fullName>Research proposal</fullName>
                </value>
                <value>
                    <fullName>Results forecast from secondary school</fullName>
                </value>
                <value>
                    <fullName>Results from secondary school</fullName>
                </value>
                <value>
                    <fullName>Results from tertiary studies</fullName>
                </value>
                <value>
                    <fullName>Results of aptitude test</fullName>
                </value>
                <value>
                    <fullName>Results of English language test</fullName>
                </value>
                <value>
                    <fullName>Statement of Purpose</fullName>
                </value>
                <value>
                    <fullName>Unit outline from tertiary studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Document</label>
    <nameField>
        <displayFormat>CNDC-{000000}</displayFormat>
        <label>Contact Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The Qualificaiton Type</description>
        <label>Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/FileToCallista_Test.cls
/*******************************************************************************
* @author		Nitin Khandelwal
* @date         18.Sept.2018     
* @description  Test Class for FileToCallistaInterface Class
                Wtitten for a single callout
* @revision     
* 08/02/2022 - Vinothraja - SFTG-2365 Added code to bulkify logging during & after callouts
*******************************************************************************/
@isTest(isParallel=false)
public class FileToCallista_Test {
    
    @isTest static void testCallistaFileCreateSuccessful() {
        
        
        
        Contact newContact = new Contact();
        newContact.FirstName = 'TestContact';
        newContact.LastName = 'TestContact';
        newContact.Person_Id_Unique__c = 'IDA';
        insert newContact;
        
        Contact_Document__c condoc = new Contact_Document__c();
        condoc.Contact__c = newContact.id;
        condoc.Document_Type__c = 'PARENT_GUARDIAN';
        condoc.Filename__c = 'testdoc';
        condoc.File_Upload_Successful__c = false;
        insert condoc;
        
        
        Application__c application = new Application__c();
        application.Applicant__c = newContact.Id;
        application.Campus_Location__c = null;
        application.Visa_Type__c = null;
        application.Australian_Immigration_Office_Issued__c = null;
        application.Visa_Number__c = null;
        application.Passport_Number__c = null;
        application.Visa_Start_Date__c = null;
        application.Visa_End_Date__c = null;
        application.Refused_entry_visa_to_any_country__c = null;
        application.Breached_visa_condition__c = null;
        application.Medical_health_prevent_visa__c = null;
        application.Protection_visa_in_any_country__c = null;
        application.Convicted_of_crime_offence__c = null;
        insert application;
        
        
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        ContentVersion contentVersion_1 = new ContentVersion(
            Title='Header_Picture1', 
            PathOnClient ='/Header_Picture1.jpg',
            VersionData = bodyBlob, 
            origin = 'H'
        );
        insert contentVersion_1;
        
        ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1];
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = application.id;
        contentlink.contentdocumentid = contentVersion_2.contentdocumentid;
        contentlink.ShareType = 'V';
        insert contentlink;
        ContentDocumentLink contentlink1 = new ContentDocumentLink();
        contentlink1.LinkedEntityId = condoc.id;
        contentlink1.contentdocumentid = contentVersion_2.contentdocumentid;
        contentlink1.ShareType = 'V';
        insert contentlink1;
        // Query Contact Document
        List<Contact_Document__c> contactPortfolio = [ SELECT Id, File_Upload_Successful__c, 
                                                                Contact__c,
                                                                Comments__c,
                                                                Contact__r.Person_id__c,
                                                                Contact_Qualification__c,
                                                                Document_Type__c,
                                                                Document_Type_Name__c,
                                                                Filename__c,
                                                                Has_API_Request__c,
                                                                Has_API_Response__c,
                                                                API_Request__c,
                                                                Submitted__c,
                                                                Type__c
                                                FROM Contact_Document__c
                                                WHERE id = :condoc.id
                                        ];
        String contactDocRec = JSON.serialize(contactPortfolio[0]);

        //Query all the ContentDocumentLink
        ContentDocumentLink cdl = [SELECT id,
                                    ContentDocumentId,
                                    ContentDocument.LatestPublishedVersionId,
                                    LinkedEntityId  
                                    FROM 
                                    ContentDocumentLink 
                                    WHERE LinkedEntityId = :contactPortfolio[0].id LIMIT 1];
        String cdlRec = JSON.serialize(cdl);

        //Query the ContentDocument
        ContentDocument cd = [SELECT
                    id,
                    Title,
                    LatestPublishedVersionId,
                    FileExtension,
                    ArchivedById,
                    ArchivedDate,
                    ContentAssetId,
                    ContentModifiedDate,
                    ContentSize,
                    Description,
                    FileType,
                    IsArchived,
                    LastReferencedDate,
                    LastViewedDate,
                    OwnerId,
                    ParentId,
                    PublishStatus,
                    SharingOption,
                    SharingPrivacy
                                  FROM
                                  ContentDocument 
                                  WHERE id = :cdl.ContentDocumentId LIMIT 1];
        String cdRec = JSON.serialize(cd);
        Test.startTest();	
        CallistaFileApiMock mock = new CallistaFileApiMock();
        mock.responseCode = 200;
        Test.setMock(HttpCalloutMock.class, mock);
        List<FileToCallistaInterface> callistaRequests = new List<FileToCallistaInterface>();
        
        FileToCallistaInterface fci = new FileToCallistaInterface(contactDocRec, cdlRec, cdRec, application.id, null);
        callistaRequests.add(fci);
        fci.sendMessage();
        Test.stopTest();
        
    }
    
}