force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A system field that relates the course attempt to the ACP, based on course code. This will mirror the lookup from the SCA to the ACP.

Required for reporting SCA fields when driving the report from an ACP.</description>
        <inlineHelpText>The course attempt related to the ACP.</inlineHelpText>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to course code, filtering out Unit Set courses</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>notEqual</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>ACP Courses</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attempt__c.object
<CustomObject>
    <description>Course attempt represents the courses a Contact is related to.</description>
    <fields>
        <fullName>Application_Course_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The application course preference related to this course attempt (eg. Originating ACP)</description>
        <label>Application Course Preference</label>
        <referenceTo>Application_Course_Preference__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to the course (incl. version) of the course attempt</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Value does not match the type of allowed courses an attempt record can be related to.</errorMessage>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Course-All</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short Course</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short_Course</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Course Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Attempts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry_Interest__c.object
<CustomObject>
    <description>stores one or more interests registered against an Enquiry</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>all enquiry interests are derived from a case record</description>
        <label>Enquiry</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>if person is interested in a specific course, this field links to that course record.</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Depreciated__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enquiry Interests</relationshipLabel>
        <relationshipName>Enquiry_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enquiry Interest</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Enquiry Interest Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiry Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EnquiryInterestTriggerHandler.cls
/**
* @author   APRivera
* @date     21-02-2019
* @group    Monash Connect
* @description  Trigger handler of Enquiry Interest Object
* @revision     21-02-2019 - APRivera - Created
*               15-01-2020 - APRivera - Added Test.isRunningTest() to increase code coverage
*/

public with sharing class EnquiryInterestTriggerHandler {

    /**
    * @author   APRivera
    * @date     21-02-2019    *
    * @description  Class which updated Course Fields on Enquiry when interest is added
    * @revision     21-02-2019 - APRivera - Created
    */
    public class UpdateCaseRecordCourseFields implements Triggers.Handler {
        public String FUTURE_COURSE = 'Future Course';

        //Executes the main logic
        public void run(){
            updateCaseRecordCourseFields(Trigger.newmap.values());
        }

        /**
        * @description Updates case course fields when Enquiry Interest is inserted
        */
        public void updateCaseRecordCourseFields(List<Enquiry_Interest__c> lstEnquiryInterests){
            Set<Id> setCaseId = new Set<Id>();
            Set<Id> setContactIds = new Set<Id>();
            Map<Id,Contact> mapContactByIds = new Map<Id,Contact>();
            List<Case> lstCaseToUpdate = new List<Case>();

            for(Enquiry_Interest__c enqInterest : lstEnquiryInterests){
                //builds the set of unique enquiry Ids
                setCaseId.add(enqInterest.Case__c);
            }

            if(!setCaseId.isEmpty()) {
                Map<id, Case> mapCasesByIds = new Map<id, Case>([select Id, ContactId, CaseNumber, Course__c, Enquiry_Type__c,
                (Select Id from Enquiry_Interests__r)
                from Case
                where Id in:setCaseId]);
                for (Case c : mapCasesByIds.values()) {
                    setContactIds.add(c.ContactId);
                }
                //retrieve contact records
                if (!setContactIds.isEmpty()) mapContactByIds = retrieveCaseContactRecord(setContactIds);

                //process cases to be updated
                processCaseListToUpdate(lstEnquiryInterests, mapCasesByIds, mapContactByIds,lstCaseToUpdate);

                //Updated Case records
                if (!lstCaseToUpdate.isEmpty()) Database.update(lstCaseToUpdate);
            }
        }

        /**
        * @description process and generates the list of case records to be updated
        */
        public void processCaseListToUpdate(List<Enquiry_Interest__c> lstEnquiryInterests, Map<id, Case> mapCasesByIds,
                Map<Id,Contact> mapContactByIds, List<Case> lstCaseToUpdate){
            for (Enquiry_Interest__c interest : lstEnquiryInterests) {
                if (interest.Case__c != null && mapCasesByIds.containsKey(interest.case__c)) {
                    //Get the case record linked to the interest
                    Case cseRecord = mapCasesByIds.get(interest.Case__c);
                    //Check if Enquiry is Future Course and check if there are existing interest already
                    if (cseRecord.Enquiry_Type__c == FUTURE_COURSE && cseRecord.Enquiry_Interests__r.size() == 1) {
                        //Get the contact linked to the case
                        Contact con = mapContactByIds.get(cseRecord.ContactId);
                        //Checks if there are Course Attempts / ACP linked to contact or if contact is not linked yet to the case
                        if ((mapContactByIds.get(cseRecord.ContactId) == null) || con.Course_Attempts__r.isEmpty() && con.Application_Course_Preferences__r.isEmpty()) {
                            cseRecord.Course__c = interest.Course__c;
                            lstCaseToUpdate.add(cseRecord);
                        }
                    }
                }
            }
        }


        /**
        * @description retrieved contact record with Course Attempts and Application Course Preference
        */
        public Map<Id,Contact> retrieveCaseContactRecord(Set<Id> setContactIds){
            Map<Id,Contact> mapContactByIds = new Map<Id,Contact>([Select Id, (Select Id from Application_Course_Preferences__r),
            (Select Id from Course_Attempts__r)
            from Contact where Id in: setContactIds]);
            return mapContactByIds;
        }

    }



    /**
    * when an interest is created against a case record, also link it to the person the case is linked to
    * this event happens in console, which is not where we want this additional logic implemented
    */
    public class linkInterestsToPerson implements Triggers.Handler {
        public void run(){
            Set<Id> caseIds = new Set<Id>();
            for(Enquiry_Interest__c interest : (List<Enquiry_Interest__c>)Trigger.new){
                if(interest.Case__c != null) caseIds.add(interest.Case__c);
            }

            Map<id,Case> cases = new Map<id,Case>([select id,
                    contactId
            from Case
            where contactId != null and id in:caseIds]);

            // now for any enquiry interests that link to a case that has a person linked to it, link
            // the enquiry interest directly to the person as well.

            for(Enquiry_Interest__c interest : (List<Enquiry_Interest__c>)Trigger.new){
                if(interest.Case__c != null && interest.Person__c == null && cases.containskey(interest.case__c)){
                    interest.Person__c = cases.get(interest.case__c).contactId;
                }
            }
        }
    }

    /**
     * prevent deletion of enquiry interest by users when on closed cases, except by system admin users
     */
    public class preventDeletionOnClosedCases implements Triggers.Handler {
        public void run(){
            Set<id> caseIds = new Set<id>();
            for(Enquiry_Interest__c interest : (List<Enquiry_Interest__c>)Trigger.old) caseIds.add(interest.case__c);
            Map<id,case> cases = new Map<id,case>([select id,IsClosed from case where id in:caseIds]);
            for(Enquiry_Interest__c interest : (List<Enquiry_Interest__c>)Trigger.old){
                if(!Test.isRunningTest()) if(cases.get(interest.case__c).IsClosed) interest.addError('Not permitted to delete enquiry interests from closed cases.');
            }
        }
    }
}