force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent for Submission</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Data Validation Ready</fullName>
                </value>
                <value>
                    <fullName>Failed Data validation</fullName>
                </value>
                <value>
                    <fullName>Submission on Hold (Duplicate Contact)</fullName>
                </value>
                <value>
                    <fullName>Agent Declaration Accepted</fullName>
                </value>
                <value>
                    <fullName>Sent Draft Application to Applicant</fullName>
                </value>
                <value>
                    <fullName>Applicant Declaration Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>ACP</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Type__c</fullName>
        <description>PRODEV - This field is used by Marketing Cloud.</description>
        <formula>TEXT( Course_Offering__r.Course__r.Type__c )</formula>
        <label>Course Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to course code, filtering out Unit Set courses</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>notEqual</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>ACP Courses</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                    <label>WITHDRAWN</label>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Registered - EOI Only</fullName>
                </value>
                <value>
                    <fullName>Registered - Approved</fullName>
                </value>
                <value>
                    <fullName>Registered - Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Registered - Rejected</fullName>
                </value>
                <value>
                    <fullName>Registered - Invoice not processed</fullName>
                </value>
                <value>
                    <fullName>Registered - Invoiced</fullName>
                </value>
                <value>
                    <fullName>Registered - CCFund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Type__c</fullName>
        <label>Course Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Faculty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Faculty record (via Org Unit)</description>
        <label>Faculty</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Account.Callista_Org_Unit_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Faculty</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Monash Organisation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Course is Active ? Active/Inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Apply_GST__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Apply GST</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course_Type__c</fullName>
        <label>Course Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Faculty__c</fullName>
        <label>Faculty</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>EOI</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c.object
<CustomObject>
    <description>Payment for pledges or gifts.</description>
    <fields>
        <fullName>Application_Course_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Course Preference</label>
        <referenceTo>Application_Course_Preference__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Type__c</fullName>
        <description>Created for PD sharing and populated by a process builder.</description>
        <label>Course Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Not Processed</fullName>
                    <default>true</default>
                    <label>Not Processed</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Refund Processed</fullName>
                </value>
                <value>
                    <fullName>Refund Not Processed</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                    <isActive>false</isActive>
                    <label>Refunded</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PY-{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentASUpdateFields_FT.cls
/**
 * @description       : Merged test class for Payment related functionality
 * @author            : jackie.ho@monash.edu
 * @group             : 
 * @last modified on  : 31-07-2025
 * @last modified by  : Jackie Ho
 * @version           : 1.0
 */
@isTest(isParallel=true)
public with sharing class PaymentASUpdateFields_FT {
    @testSetup
    static void setupTestData() {
        // GIVEN: Common setup for all test methods
        insert new Bypass_Mute_Request__c(Bypass_All_Flows__c=false);

        // GIVEN: Create and insert test applicant with address details
        Contact applicant = StudFirst_TestHelper.createApplicant();
        applicant.MailingPostalCode = '3000';
        applicant.MailingStreet = '123 Main St';
        applicant.MailingCity = 'Clayton';
        applicant.MailingState = 'Victoria';
        applicant.MailingCountry = 'Australia';
        insert applicant;
        
        // GIVEN: Create and insert application
        Application__c application = StudFirst_TestHelper.createApplication(applicant);
        application.Status__c = 'Registered - Not paid';
        insert application;

        // GIVEN: Create and insert course
        Course__c course = StudFirst_TestHelper.createCourse();
        insert course;

        // Create and insert course offering with GST and faculty details
        Course_Offering__c courseOffering = StudFirst_TestHelper.createCourseOffering(course);
        courseOffering.Course_Type__c = 'Professional Development';
        courseOffering.Faculty__c = 'Faculty of Education';
        courseOffering.Apply_GST__c = true;
        insert courseOffering;

        // GIVEN: Create and insert application course preference
        Application_Course_Preference__c ACP = StudFirst_TestHelper.createCoursePreferences(application, applicant, courseOffering, course);
        insert ACP;

        // GIVEN: Create and insert payment with initial values
        Payment__c payment = StudFirst_TestHelper.createPayment(courseOffering, applicant, application);
        payment.Payment_Amount__c = 100;
        payment.Street__c = null;
        payment.Suburb__c = null;
        payment.State__c = null;
        payment.Postcode__c = null;
        payment.Application_Course_Preference__c = ACP.Id;
        insert payment;
    }
    
    /**
     * @description Test method for updating credit card payment and verifying ACP status update
     */
    @isTest
    static void testUpdateCreditCardPayment() {
        // WHEN: Update credit card payment
        Test.startTest();
        Payment__c payment = [SELECT Id, Payment_Status__c, Payment_Type__c, Application_Course_Preference__c, Application__c 
                             FROM Payment__c 
                             ORDER BY createddate DESC 
                             LIMIT 1];
        Application_Course_Preference__c ACP = [SELECT Id, Status__c 
                                                FROM Application_Course_Preference__c 
                                                WHERE Application__c = :payment.Application__c 
                                                LIMIT 1];
        ACP.Status__c = 'Registered - Not paid';
        update ACP;
        payment.Payment_Status__c = 'Processed';
        payment.Payment_Type__c = 'Credit_Card';
        update payment;
        Test.stopTest();

        ACP = [SELECT Id, Status__c 
               FROM Application_Course_Preference__c 
               WHERE Application__c = :payment.Application__c 
               LIMIT 1];
        Application__c application = [SELECT Id, Status__c FROM Application__c WHERE Id = :payment.Application__c];
        
        // THEN: Verify results
        Assert.areEqual('Registered', application.Status__c, 'Application Status should be updated');
        Assert.areEqual('Registered', ACP.Status__c, 'Application Course Preference Status should be updated');
    }

    /**
     * @description Test method for updating invoice payment and verifying ACP status update
     */
    @isTest
    static void testUpdateInvoicePayment() {
        // WHEN: Update invoice payment
        Test.startTest();
        Payment__c payment = [SELECT Id, Payment_Status__c, Payment_Type__c, Application_Course_Preference__c, Application__c 
                             FROM Payment__c 
                             ORDER BY createddate DESC 
                             LIMIT 1];
        Application_Course_Preference__c ACP = [SELECT Id, Status__c 
                                                FROM Application_Course_Preference__c 
                                                WHERE Id = :payment.Application_Course_Preference__c];
        ACP.Status__c = 'Registered - Invoice not processed';
        update ACP;
        payment.Payment_Status__c = 'Processed';
        payment.Payment_Type__c = 'Invoice';
        update payment;
        Test.stopTest();

        ACP = [SELECT Id, Status__c 
               FROM Application_Course_Preference__c 
               WHERE Id = :payment.Application_Course_Preference__c];
        Application__c application = [SELECT Id, Status__c 
                                     FROM Application__c 
                                     WHERE Id = :payment.Application__c];
        
        // THEN: Verify results
        Assert.areEqual('Registered', application.Status__c, 'Application Status should be updated');
        Assert.areEqual('Registered - Invoiced', ACP.Status__c, 'Application Course Preference Status should be updated');
    }

    /**
     * @description Test method for verifying course faculty and type are correctly set on payment
     */
    @isTest
    static void testUpdateCourseFacultyAndType() {
        // WHEN: Update course faculty and type
        Payment__c payment = [SELECT Id, Course_Faculty__c, Course_Type__c 
                             FROM Payment__c 
                             ORDER BY createddate DESC 
                             LIMIT 1];

        // THEN: Verify results
        Assert.areEqual('Faculty of Education', payment.Course_Faculty__c, 'Course Faculty should be updated');
        Assert.areEqual('Professional Development', payment.Course_Type__c, 'Course Type should be updated');
    }

    /**
     * @description Test method for verifying GST allocation calculation
     */
    @isTest
    static void testUpdateGSTAllocation() {
        // WHEN: Update GST allocation
        Payment__c payment = [SELECT Id, GST_Allocation__c 
                             FROM Payment__c 
                             ORDER BY createddate DESC 
                             LIMIT 1];

        // THEN: Verify results
        Assert.areEqual(9, payment.GST_Allocation__c, 'GST Allocation should be updated to include 10% GST');
    }

    /**
     * @description Test method for verifying payment address is correctly populated from contact
     */
    @isTest
    static void testUpdatePaymentAddress() {
        // WHEN: Update payment address
        Payment__c payment = [SELECT Id, Street__c, Suburb__c, State__c, Postcode__c, Country__c 
                             FROM Payment__c 
                             ORDER BY createddate DESC 
                             LIMIT 1];

        // THEN: Verify results
        Assert.areEqual('3000', payment.Postcode__c, 'Postcode should be updated');
        Assert.areEqual('123 Main St', payment.Street__c, 'Street should be updated');
        Assert.areEqual('Clayton', payment.Suburb__c, 'Suburb should be updated');
        Assert.areEqual('Victoria', payment.State__c, 'State should be updated');
        Assert.areEqual('Australia', payment.Country__c, 'Country should be updated');
    }
}