force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enquiry_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enquiry Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent for Submission</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Data Validation Ready</fullName>
                </value>
                <value>
                    <fullName>Failed Data validation</fullName>
                </value>
                <value>
                    <fullName>Submission on Hold (Duplicate Contact)</fullName>
                </value>
                <value>
                    <fullName>Agent Declaration Accepted</fullName>
                </value>
                <value>
                    <fullName>Sent Draft Application to Applicant</fullName>
                </value>
                <value>
                    <fullName>Applicant Declaration Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Course Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>ACP</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Type_Text__c</fullName>
        <description>Created for PD sharing and populated by a process builder. Course_Type__c is a formula field and can not use for sharing settings.</description>
        <label>Course Type Text</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to course code, filtering out Unit Set courses</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>notEqual</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>ACP Courses</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managing_Faculty_Text__c</fullName>
        <description>For partitioning sharing rules. Populated by a PB.</description>
        <label>Managing Faculty</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                    <label>WITHDRAWN</label>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Registered - EOI Only</fullName>
                </value>
                <value>
                    <fullName>Registered - Approved</fullName>
                </value>
                <value>
                    <fullName>Registered - Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Registered - Rejected</fullName>
                </value>
                <value>
                    <fullName>Registered - Invoice not processed</fullName>
                </value>
                <value>
                    <fullName>Registered - Invoiced</fullName>
                </value>
                <value>
                    <fullName>Registered - CCFund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Used to force uniqueness on course code. Updated from workflow.</description>
        <externalId>true</externalId>
        <label>Course Code Unique</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Course is Active ? Active/Inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <externalId>true</externalId>
        <label>Course Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Presenter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Presenter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>EOI</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Presenter__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Presenter</label>
</CustomObject>

force-app/main/default/classes/Console_ReportEnquiryNotEnrolled_Test.cls
/**
* @author Nadula Karunaratna
* @date 05-09-2017
* @group Professional Development
* @description Test class for Console_ReportEnquiryNotEnrolled
* @revision Nadula Karunaratna | 10-08-2018 | Added Faculty specific data 
* @revision Nadula Karunaratna | 16-01-2020 | Renamed with '_Test', Utilised "runAs" to test each faculty, increased code coverage from 43% to 86%
* @revision Cartick Sub - 18 May 2021 - PRODEV-686 - Improve test coverage; optimize code
*/

@isTest(isParallel=false) // User-based code fails when isParallel=true 
private class Console_ReportEnquiryNotEnrolled_Test {  

    @isTest static void TestGetLoginUserFaculty(){  
        // GIVEN
        // Get Professional Profile Id
        Profile PDProfile = [SELECT Id FROM Profile WHERE Name='Professional Development'];

        // Get Education Short Courses Team Role Id
        UserRole EDUuserRole = [select Id from UserRole where Name = 'Education Short Courses Team'];


        // Create a unique username
        String uniqueUserName = 'pdtestuser' + DateTime.now().getTime() + '@mailinator.com';  
        
        // Create a test Professional Development user    
        User u = new User(Alias = 'pdtuser', Email='pdtestuser@mailinator.com', EmailEncodingKey='UTF-8', LastName='Testuser', LanguageLocaleKey='en_US', LocaleSidKey='en_AU', ProfileId = PDProfile.Id, TimeZoneSidKey='Australia/Sydney', UserName=uniqueUserName, UserRoleId=EDUuserRole.Id);
        String faculty;

        // WHEN
        // Runs as the test PD user
        System.runAs(u){
            Test.startTest();
                Console_ReportEnquiryNotEnrolled x =  new Console_ReportEnquiryNotEnrolled();
                // The getLoginUserFaculty method is invoked
                faculty = x.getLoginUserFaculty();
            Test.stopTest();
            
            // THEN
            Assert.areEqual('Faculty of Education', faculty, 'getLoginUserFaculty method not running properly'); 
        }
        
        // Negative test
        Console_ReportEnquiryNotEnrolled x =  new Console_ReportEnquiryNotEnrolled();
        faculty = x.getLoginUserFaculty();                
        Assert.areEqual('All Faculties', faculty, 'getLoginUserFaculty method not running properly'); 
    }

    @isTest static void TestProcessData() {

        // Add Contacts
        Contact newContact1 = PDTestHelper.createContact2('Test','TEST1','test.test1@gmail.com');
        
        Contact newContact2 = PDTestHelper.createContactWithAddress('Test','TEST2','test.test2@gmail.com','Monash University,Level 2,700 Blackburn Road','Notting Hill','Victoria','3168','0399054000','0400123456');
        newContact2.Course_Code__c = 'PDD0001';
        newContact2.HasOptedOutOfEmail = false;
        update newContact2;

        Contact newContact3 = PDTestHelper.createContactWithAddress('Test','TEST3','test.test3@gmail.com','Monash University,Level 2,700 Blackburn Road','Notting Hill','Victoria','3168','0399054000','0400123456');
        Contact newContactPresenter1 = PDTestHelper.createContact2('Presenter','TEST1','Presenter.test1@gmail.com');

        // Add a Course with the Course Code, PDD0001
        Course__c course = PDTestHelper.createCourse();

        // Add a Course Offering for the above Course
        Course_Offering__c co = PDTestHelper.createCourseOfferingForCourse(course);
        co.Presenter__c = newContactPresenter1.Id;    
        update co;

        // Add Enquiries
        RecordType pdRecordType = [select Id from RecordType where Name = 'Professional Development' and SobjectType = 'Case' LIMIT 1]; 

        Case enq1 = new Case();      
        enq1.RecordTypeId = pdRecordType.Id;
        enq1.ContactId = newContact1.Id; 
        enq1.Status = 'Open';
        enq1.Course__c = course.Id;
        insert enq1; 

        Case enq2 = new Case();      
        enq2.RecordTypeId = pdRecordType.Id;
        enq2.ContactId = newContact2.Id;
        enq2.Status = 'Open';
        enq2.Course__c = course.Id;
        insert enq2; 

        Case enq3 = new Case();      
        enq3.RecordTypeId = pdRecordType.Id;
        enq3.ContactId = newContact3.Id;  
        enq3.Status = 'Open';
        enq3.Course__c = course.Id;
        insert enq3;   

        // Add an Application
        Application__c application = new Application__c();
        application.Status__c = 'Registered';
        application.Enquiry_Number__c = enq1.Id;
        application.Applicant__c = newContact1.Id;
        insert application;  

        // Add Application Course Preferences
        Application_Course_Preference__c acp = new Application_Course_Preference__c();
        acp.Applicant__c = newContact1.Id;
        acp.Status__c = 'Registered';
        acp.Course_Offering__c = co.Id;
        acp.Application__c = application.Id;
        acp.Course_Code__c = course.Name;
        acp.Course__c = course.Id;
        acp.Course_Type_Text__c = 'Short_Course';
        acp.Managing_Faculty_Text__c = 'Faculty of Education';
        insert acp;  

        Application_Course_Preference__c acp2 = new Application_Course_Preference__c();
        acp2.Applicant__c = newContact2.Id;
        acp2.Status__c = 'Registered - Not paid';
        acp.Course_Offering__c = co.Id;
        acp2.Application__c = application.Id;
        acp2.Course_Code__c = course.Name;
        acp2.Course__c = course.Id;
        acp2.Course_Type_Text__c = 'Short_Course';
        acp2.Managing_Faculty_Text__c = 'Faculty of Education';        
        insert acp2;          

        // URL Parameters
        Console_ReportEnquiryNotEnrolled testObj = new Console_ReportEnquiryNotEnrolled();
        testObj.getCriteria = '2021-01-01|2099-12-31|PDD0001|null|null|Faculty of Education';
        testObj.processData();
        
    }
}