force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent for Submission</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Data Validation Ready</fullName>
                </value>
                <value>
                    <fullName>Failed Data validation</fullName>
                </value>
                <value>
                    <fullName>Submission on Hold (Duplicate Contact)</fullName>
                </value>
                <value>
                    <fullName>Agent Declaration Accepted</fullName>
                </value>
                <value>
                    <fullName>Sent Draft Application to Applicant</fullName>
                </value>
                <value>
                    <fullName>Applicant Declaration Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                    <label>WITHDRAWN</label>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Registered - EOI Only</fullName>
                </value>
                <value>
                    <fullName>Registered - Approved</fullName>
                </value>
                <value>
                    <fullName>Registered - Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Registered - Rejected</fullName>
                </value>
                <value>
                    <fullName>Registered - Invoice not processed</fullName>
                </value>
                <value>
                    <fullName>Registered - Invoiced</fullName>
                </value>
                <value>
                    <fullName>Registered - CCFund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Qualification_Provided__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <label>Contact Qualification</label>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>Sequence number to send to callista for a particular contact qualification type</description>
        <label>Sequence Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application Qualification Provided</label>
    <nameField>
        <displayFormat>AQP-{000000}</displayFormat>
        <label>Application Qualification Provided ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Qualifications Provided</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>English_doc_required_during_assessment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For GR application id there is English doc required during assessment then this checkbox will be ticked</description>
        <label>English doc required during assessment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Qualification__c</fullName>
        <label>Other Qualification</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Level of Completion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ATTEMPTED BUT WAS NOT COMPLETED</fullName>
                </value>
                <value>
                    <fullName>CURRENTLY STUDYING</fullName>
                </value>
                <value>
                    <fullName>DISCONTINUED</fullName>
                </value>
                <value>
                    <fullName>SUCCESSFULLY COMPLETED AND OBTAINED</fullName>
                </value>
                <value>
                    <fullName>Completed Alternative Exit</fullName>
                    <isActive>false</isActive>
                    <label>Completed Alternative Exit</label>
                </value>
                <value>
                    <fullName>Completed not graduated</fullName>
                    <isActive>false</isActive>
                    <label>Completed not graduated</label>
                </value>
                <value>
                    <fullName>Graduated</fullName>
                    <isActive>false</isActive>
                    <label>Graduated</label>
                </value>
                <value>
                    <fullName>Graduated but no Grad Date in Callista</fullName>
                    <isActive>false</isActive>
                    <label>Graduated but no Grad Date in Callista</label>
                </value>
                <value>
                    <fullName>Study Abroad/CIC</fullName>
                    <isActive>false</isActive>
                    <label>Study Abroad/CIC</label>
                </value>
                <value>
                    <fullName>WILL BE COMPLETED BY ADMISSION</fullName>
                    <isActive>false</isActive>
                    <label>WILL BE COMPLETED BY ADMISSION</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title_of_Publication_Work_Chapter_Paper__c</fullName>
        <description>Title of Publication/Work/Chapter/Paper</description>
        <label>Title of Publication/Work/Chapter/Paper</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <recordTypes>
        <fullName>English_Test</fullName>
        <active>true</active>
        <label>English Test</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other_Qualification</fullName>
        <active>true</active>
        <label>Other Qualification</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist__c.object
<CustomObject>
    <description>Capture documents relevant to different processes that requires documents for verification</description>
    <fields>
        <fullName>Application_Course_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Course Preference</label>
        <referenceTo>Application_Course_Preference__c</referenceTo>
        <relationshipLabel>Document Checklists</relationshipLabel>
        <relationshipName>Document_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to Application</description>
        <inlineHelpText>Link to Application</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Document Checklist</relationshipLabel>
        <relationshipName>Document_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Link to Contact Qualification</description>
        <inlineHelpText>Link to Contact Qualification</inlineHelpText>
        <label>Contact Qualification</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Contact__c</field>
                <operation>equals</operation>
                <valueField>Contact_Qualification__c.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipLabel>Document Checklist</relationshipLabel>
        <relationshipName>Document_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup directly to Contact to enable filtering of Qualification and Work Experience records.</description>
        <inlineHelpText>Lookup directly to Contact to enable filtering of Qualification and Work Experience records.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Document Checklist</relationshipLabel>
        <relationshipName>Document_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Checklist</label>
    <nameField>
        <displayFormat>DC{YYYY}-{000000}</displayFormat>
        <label>Checklist Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist_Comment__c.object
<CustomObject>
    <description>Comment holder for document checklist</description>
    <fields>
        <fullName>Cancelled_Date__c</fullName>
        <description>Cancelled Date of the comment</description>
        <label>Cancelled Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the document comment cancelled</description>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>Comment content details</description>
        <label>Content</label>
        <length>100000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Document_Checklist__c</fullName>
        <description>Linked checklist where the comment is for.</description>
        <label>Document Checklist</label>
        <referenceTo>Document_Checklist__c</referenceTo>
        <relationshipLabel>Document Checklist Comments</relationshipLabel>
        <relationshipName>Document_Checklist_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notify_Email_Addresses__c</fullName>
        <description>Notify Email Addresses for Grad Research document request</description>
        <label>Notify Email Addresses</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Date__c</fullName>
        <description>Comment request date from callista</description>
        <label>Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Sequence_Number__c</fullName>
        <description>Request Sequence Number from Callista for Document request</description>
        <label>Request Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Document Checklist Comment</label>
    <nameField>
        <displayFormat>DCC{YYYY}-{000000}</displayFormat>
        <label>Document Checklist Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklist Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/GRDocumentRequestImpl.cls
/**
 * @description Implementation class for GRDocumentRequestImplFactory
 * @author      Vishal Gupta
 * @since       21.10.2024
 * @revision
 */
public with sharing class GRDocumentRequestImpl implements RESTlib_IClientImpl {
    private static List<Application_Course_Preference__c> lstACP = new List<Application_Course_Preference__c>();
    private static List<Document_Checklist__c> lstDocChecklist = new List<Document_Checklist__c>();
    private static Id applicationId;
    private static Integer claimSeqNumber;
    private static final String DOC_REQUEST_TYPE_ENGLISH = 'ENG-TEST';
    private static final String RECORD_TYPE_ENG = 'English_Test';
    private static final String DOC_REQUEST_TYPE_MISC = 'MISC-DOC';
    private static final String RECORD_TYPE_MISC = 'Other_Qualification';
    /**
     * @description Should return the concrete handler class of the client implementation
     * @return `RESTlib_ClientImplHandler`
     */
    public RESTlib_ClientImplHandler getHandleGet() {
        return null; // Not implemented yet
    }

    /**
     * @description Should return the concrete handler class of the client implementation
     * @return `RESTlib_ClientImplHandler`
     */
    public RESTlib_ClientImplHandler getHandlePost() {
        return new HandlePost();
    }

    /**
     * @description Should return the concrete handler class of the client implementation
     * @return `RESTlib_ClientImplHandler`
     */
    public RESTlib_ClientImplHandler getHandlePut() {
        return null; // Not implemented yet
    }

    /**
     * @description Should return the concrete handler class of the client implementation
     * @return `RESTlib_ClientImplHandler`
     */
    public RESTlib_ClientImplHandler getHandlePatch() {
        return null; // Not implemented yet
    }

    /**
     * @description Processes POST requests for document request,
     *              handling validation, processing request.
     * @author      Vishal Gupta
     * @since       21/10/2024
     */
    public with sharing virtual class HandlePost extends RESTlib_ClientImplHandler {
        private final Utils utils = new Utils();
        /**
         * @description Set request type
         * @return `Type`
         */
        public override Type getRequestType() {
            return GRDocumentRequestPayload.PostRequest.class;
        }

        /**
         * @description Set response type
         * @return `Type`
         */
        public override Type getResponseType() {
            return GRDocumentRequestPayload.PostResponse.class;
        }

        /**
         * @description Validation rules
         * @param reqObj Request
         * @throws RESTlib_Ex.InvalidRequestException Custom exception
         */
        public override void validate(RESTlib_Payload.Request reqObj) {
            String msg = '';
            try {
                GRDocumentRequestPayload.PostRequest req = (GRDocumentRequestPayload.PostRequest) reqObj;
                if(String.isBlank(req.applicantId)) {
                    msg = 'The applicant Id cannot be blank';
                    utils.logErrorWithRequest(msg);
                    throw new RESTlib_Ex.InvalidRequestException(msg);
                } 
    
                if(String.isBlank(req.hdrApplicationNumber)) {
                    msg = 'The HDR Application Number cannot be blank';
                    utils.logErrorWithRequest(msg);
                    throw new RESTlib_Ex.InvalidRequestException(msg);
                }
    
                if(String.isBlank(req.requestType)) {
                    msg = 'The Document request type cannot be blank';
                    utils.logErrorWithRequest(msg);
                    throw new RESTlib_Ex.InvalidRequestException(msg);
                }
    
                //get the ApplicationCoursePreference from HDR Application Id
                lstACP = new ApplicationCoursePreferenceSelector().selectByHDRApplicationAndApplicantId(req.hdrApplicationNumber, req.applicantId);
    
                if(lstACP.isEmpty()) {
                    msg = 'Application not found';
                    utils.logErrorWithRequest(msg);
                    throw new RESTlib_Ex.InvalidRequestException(msg);
                } else {
                    applicationId = lstACP[0].Application__c;
                    claimSeqNumber = req.claimSequenceNumber;
                    //get the Document checklist from Application Id and document type
                    lstDocChecklist = new DocumentChecklistsSelector().selectApplicationAssessmentByApplicationIdAndSequenceNumber(applicationId, req.requestType, req.claimSequenceNumber);
                }
    
                if(lstDocChecklist.isEmpty() && req.claimSequenceNumber != null && req.requestType != DOC_REQUEST_TYPE_ENGLISH && req.requestType != DOC_REQUEST_TYPE_MISC) {
                    msg = 'Document not found';
                    utils.logErrorWithRequest(msg);
                    throw new RESTlib_Ex.InvalidRequestException(msg);
                }

                if(lstDocChecklist.isEmpty() && req.requestType != DOC_REQUEST_TYPE_ENGLISH && req.requestType != DOC_REQUEST_TYPE_MISC) {
                    msg = 'Document not found';
                    utils.logErrorWithRequest(msg);
                    throw new RESTlib_Ex.InvalidRequestException(msg);
                }
            } catch (Exception ex) {
                Nebula.Logger.error(ex.getMessage(), ex);
                throw new RESTlib_Ex.InvalidRequestException(ex.getMessage());
            }
        }

        /**
         * @description Creates a Content Document based on the payload request
         * @param reqObj Request
         * @param responseObj Response
         * @return RESTlib_Payload.Response
         * @throws RESTlib_Ex.InvalidRequestException Custom exception
         */
        public override RESTlib_Payload.Response process(RESTlib_Payload.Request reqObj, RESTlib_Payload.Response responseObj) {
            nebula.Logger.finest('process').setRestRequestDetails(RestContext.request).addTag(RestContext.request.requestURI);
            GRDocumentRequestPayload.PostRequest req = (GRDocumentRequestPayload.PostRequest) reqObj;
            Datetime requestDate = req.requestDate != null ? Datetime.valueOfGmt(req.requestDate.replace('T',' ')) : null;
            GRDocumentRequestPayload.PostResponse resp = (GRDocumentRequestPayload.PostResponse) responseObj;
            //if there is cancelled date in the request then we have to find the existing comment and cancel it
            List<Document_Checklist_Comment__c> lstComments = new List<Document_Checklist_Comment__c>();
            try {
                if(!lstDocChecklist.isEmpty()) {
                    // if there is a cancelled date in the payload then cancel the checklist comment
                    if(req.cancelledDate != null && !lstDocChecklist[0].Document_Checklist_Comments__r.isEmpty()) {
                        for(Document_Checklist_Comment__c dcComment : lstDocChecklist[0].Document_Checklist_Comments__r) {
                            if(dcComment.Content__c == req.requestReason && !dcComment.Cancelled__c) {
                                dcComment.Cancelled__c = true;
                                dcComment.Cancelled_Date__c = Datetime.valueOfGmt(req.cancelledDate.replace('T',' '));
                                lstComments.add(dcComment);
                            }
                        }
                        update lstComments;
                        updateChecklist(lstDocChecklist[0], 'Submitted');
                        return resp;
                    }
                    //else insert the document checklist comment
                    insertDocChecklistComment(lstDocChecklist[0].Id, req.requestReason, requestDate, req.requestSequenceNumber, req.notifyEmailAddresses);
                    updateChecklist(lstDocChecklist[0], 'Insufficient');
                } else if(req.requestType == DOC_REQUEST_TYPE_ENGLISH || req.requestType == DOC_REQUEST_TYPE_MISC) {//if there is no checklist and the request type is either english/misc doc
                    List<Contact_Qualification__c> lstQual = getContactQualifications(RECORD_TYPE_ENG);//get the english contact qualification 
                    Contact_Qualification__c cq = new Contact_Qualification__c();
                    Id docChecklistId;
                    if(req.requestType == DOC_REQUEST_TYPE_ENGLISH) { 
                        //for english type of document request, we need to update the existing contact qualification                   
                        cq.Id = lstQual[0].Id;
                        cq.English_doc_required_during_assessment__c = true;
                        upsertContactQual(cq, lstQual[0].Contact__c, RECORD_TYPE_ENG);                    
                    } else if(req.requestType == DOC_REQUEST_TYPE_MISC) {
                        //create new misc doc    
                        cq.Title_of_Publication_Work_Chapter_Paper__c = String.isNotBlank(req.description) ? req.description.replaceFirst('MISC-DOC', '').replaceFirst('/','').trim() : req.requestReason;
                        cq.Other_Qualification__c = 'MISC-DOC';
                        upsertContactQual(cq, lstQual[0].Contact__c, RECORD_TYPE_MISC);
                    }
                    //run the checklist rules to create the doc checklist for eng/misc doc requirement
                    DocumentChecklistRuleServices rulesDocChecklistEngine = new DocumentChecklistRuleServices(new Set<Id>{applicationId});
                    rulesDocChecklistEngine.evaluateRules('Application Assessment');
                    List<Document_Checklist__c> resultChecklistItemsList = rulesDocChecklistEngine.resultChecklistItemsMap.get(applicationId).values();
                    upsert resultChecklistItemsList;
                    
                    //inserting the checklist comment
                    for(Document_Checklist__c dc : resultChecklistItemsList) {
                        if(dc.Contact_Qualification__c == cq.Id) {
                            docChecklistId = dc.Id;
                        }
                    }
                    if(docChecklistId != null) {
                        //insert the document checklist comment for english qualification only
                        insertDocChecklistComment(docChecklistId, req.requestReason, requestDate, req.requestSequenceNumber, req.notifyEmailAddresses);
                    }
                }
            } catch (Exception ex) {
                Nebula.Logger.error(ex.getMessage(), ex);
                throw new RESTlib_Ex.DeveloperException(ex.getMessage());
            }
            
            return resp;
        }

        /**
         * @description function to insert the checklist comments
         * @param checklistId
         * @param content
         * @param requestDate
         * @param reqSeqNum
         * @param notifyEmailAddresses
         */
        private void insertDocChecklistComment(Id checklistId, String content, DateTime requestDate, Integer reqSeqNum, String notifyEmailAddresses) {
            insert new Document_Checklist_Comment__c(
                Document_Checklist__c = checklistId,
                Content__c = content,
                Request_Date__c = requestDate,
                Request_Sequence_Number__c = reqSeqNum,
                Notify_Email_Addresses__c = notifyEmailAddresses
            );
        }

        /**
         * @description function to update the checklist
         * @param checklist
         * @param status
         */
        private void updateChecklist(Document_Checklist__c checklist, String status) {
            checklist.status__c = status;
            update checklist;
        }

        /**
         * @description function to upsert the Contact Qualifications options for Graduate Research
         * @param cq
         * @param contactId
         * @param recordTypeName
         */
        private void upsertContactQual(Contact_Qualification__c cq, Id contactId, String recordTypeName) {
            Boolean isExisting = false;
            if(cq.Id != null) {
                isExisting = true;
            }
            cq.recordTypeId = Schema.SObjectType.Contact_Qualification__c.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();
            cq.Contact__c = contactId;
                        
            Database.UpsertResult upr = Database.upsert(cq);
            if(!isExisting) {
                // new qualification, attach to current application
                Application_Qualification_Provided__c aqp = new Application_Qualification_Provided__c();
                aqp.Contact_Qualification__c = cq.Id;
                aqp.Sequence_Number__c = claimSeqNumber;
                aqp.Application__c = applicationId;
                Database.SaveResult sr = Database.insert(aqp);
            }
        }

        /**
         * @description function to retrieve the Contact Qualifications by recordTypeName
         * @param recordTypeName
         */
        public List<Contact_Qualification__c> getContactQualifications(String recordTypeName){
            Id recordTypeId = Schema.SObjectType.Contact_Qualification__c.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();
            List<Contact_Qualification__c> qualifications = new List<Contact_Qualification__c>();
            for(Contact_Qualification__c cq : new ContactQualificationsSelector().selectByApplicationId(new Set<Id>{applicationId})){
                if(cq.RecordTypeId == recordTypeId) {
                    qualifications.add(cq);
                }
            }
            
            return qualifications;
        }
    }

    /**
     * @description Classes for helper methods.
     */
    private with sharing class Utils {
        /**
        * @description  log error with request
        * @param message error message
        */
        private void logErrorWithRequest(String message) {
            nebula.Logger.error(message).setRestRequestDetails(RestContext.request).addTag(RestContext.request.requestURI);
        }
    } 
}