force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Campus_Location__c</fullName>
        <description>This is used by Custom metadata to determine the Application fee amount</description>
        <label>Campus Location Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                    <isActive>false</isActive>
                    <label>South Africa</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Guardian_Email_Address__c</fullName>
        <description>Email Address of the Parent/Guardian.</description>
        <label>Guardian Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Guardian_Full_Name__c</fullName>
        <description>Full Name of the Parent/Guardian for the applicant</description>
        <label>Guardian Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guardian_Phone_Number__c</fullName>
        <description>Parent/Guardian Phone Number</description>
        <label>Guardian Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Guardian_Relationship__c</fullName>
        <description>Relationship of the Parent/Guardian to the applicant.</description>
        <label>Guardian Relationship</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residency_Status__c</fullName>
        <description>Used to define the applicant&apos;s/applications residency status at the point in time of the application.</description>
        <inlineHelpText>Used to define the applicant&apos;s/applications residency status at the point in time of the application.</inlineHelpText>
        <label>Residency Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DOM-AUS</fullName>
                    <label>I am an Australian Citizen (with or without dual citizenship)</label>
                </value>
                <value>
                    <fullName>DOM-NZ</fullName>
                    <label>I am a New Zealand Citizen</label>
                </value>
                <value>
                    <fullName>DOM-SUN</fullName>
                    <label>I am a Malaysian Citizen or a Malaysian Permanent Resident (i.e. I hold a Malaysian PR visa)</label>
                </value>
                <value>
                    <fullName>DOM-PR</fullName>
                    <label>I am an Australian Permanent Resident (i.e. I hold an Australian PR visa)</label>
                </value>
                <value>
                    <fullName>DOM-SA</fullName>
                    <label>I am a South African Citizen</label>
                </value>
                <value>
                    <fullName>DOM-HV</fullName>
                    <label>I hold an Australian Permanent Humanitarian Visa</label>
                </value>
                <value>
                    <fullName>INTRNTNL</fullName>
                    <label>I hold or will be getting an Australian Student Visa</label>
                </value>
                <value>
                    <fullName>INT-TEP</fullName>
                    <label>I hold a non-student Australian Temporary Visa (e.g. spouse visa or work visa)</label>
                </value>
                <value>
                    <fullName>INT-SUN-P</fullName>
                    <label>I hold a Malaysian Student or Temporary Pass</label>
                </value>
                <value>
                    <fullName>INT-SUN</fullName>
                    <label>I will be getting a Malaysian Student or Temporary Pass</label>
                </value>
                <value>
                    <fullName>INT-SA</fullName>
                    <label>I hold or will be getting a South African Student/Study Visa</label>
                </value>
                <value>
                    <fullName>DOM-IDN</fullName>
                    <label>I am an Indonesian Citizen</label>
                </value>
                <value>
                    <fullName>DOM-IDN-PR</fullName>
                    <label>I am an Indonesian Permanent Resident</label>
                </value>
                <value>
                    <fullName>INT-IDN-P</fullName>
                    <label>I currently have a visa to study in Indonesia</label>
                </value>
                <value>
                    <fullName>INT-IDN</fullName>
                    <label>I will be getting a visa to study in Indonesia</label>
                </value>
                <value>
                    <fullName>&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;</fullName>
                    <isActive>false</isActive>
                    <label>&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;</label>
                </value>
                <value>
                    <fullName>https://myapp.monash.edu/admissions/a244a000000SH9A/</fullName>
                    <isActive>false</isActive>
                    <label>https://myapp.monash.edu/admissions/a244a000000SH9A/</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Under18Controller_Test.cls
/**
 * @author Trent De Laney
 * @date 18 Mar 2019 at 11:07:46 am
 * @group Test Class
 * @description Covers the class Under 18 Controller
 */
@isTest(isParallel=true)
private class Under18Controller_Test {

    @IsTest
    public static void testGetApplicationFields() {
        //Create a Contact
        Contact c = StudFirst_TestHelper.createApplicant();
        insert c;
        //Create an Application
        Application__c app = StudFirst_TestHelper.createApplication(c);

        app.Guardian_Full_Name__c = 'Test Guardian Name';
        app.Guardian_Phone_Number__c = '0422222222';
        app.Guardian_Email_Address__c = 'test@test.com';
        app.Guardian_Relationship__c = 'Father';

        app.Residency_Status__c = 'INT-TEP';
        app.Campus_Location__c = 'Australia';
        insert app;

        Map<String, Object> result = Under18Controller.getApplicationFields(app.Id);

        Application__c returnedApp = (Application__c) result.get('Application');
        Boolean international = (Boolean) result.get('International');

        System.assertEquals(app.Guardian_Full_Name__c, returnedApp.Guardian_Full_Name__c);
        System.assertEquals(app.Guardian_Phone_Number__c, returnedApp.Guardian_Phone_Number__c);
        System.assertEquals(app.Guardian_Relationship__c, returnedApp.Guardian_Relationship__c);
        System.assertEquals(app.Guardian_Email_Address__c, returnedApp.Guardian_Email_Address__c);
        System.assertEquals(true, international);
    }

    @IsTest
    public static void testSaveApplication() {
        Contact c = StudFirst_TestHelper.createApplicant();
        insert c;

        Application__c app = StudFirst_TestHelper.createApplication(c);
        insert app;

        app.Guardian_Full_Name__c = 'Test Guardian Name';
        app.Guardian_Phone_Number__c = '0422222222';
        app.Guardian_Email_Address__c = 'test@test.com';
        app.Guardian_Relationship__c = 'Father';

        Under18Controller.saveApplication(app);

        Application__c savedApp = [
                SELECT Id, Guardian_Email_Address__c
                FROM Application__c
                WHERE Id = :app.Id
        ];

        System.assertEquals(savedApp.Guardian_Email_Address__c, app.Guardian_Email_Address__c);
    }
}