force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup to the Agency account</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campus_Location__c</fullName>
        <description>This is used by Custom metadata to determine the Application fee amount</description>
        <label>Campus Location Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>South Africa</fullName>
                    <isActive>false</isActive>
                    <label>South Africa</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration_of_Study__c</fullName>
        <label>Duration of Study</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>One Semester</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Two Semester</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>From_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>a checkbox to determine whether the Application is from the my.app portal or from Callista migration.</description>
        <inlineHelpText>a checkbox to determine whether the Application is from the my.app portal or from Callista migration.</inlineHelpText>
        <label>From Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Furthest_Progress__c</fullName>
        <description>Furthest progress of the application, values will be the same as Submission Progress</description>
        <label>Furthest Progress</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to link which agreement the application is relevant to for Partner Nominated Applications</description>
        <label>Partner Agreement</label>
        <referenceTo>Partner_Agreement__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Controlled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field that determines if the application is being managed by the partner. The Applicant does not have access to this application yet.</description>
        <label>Partner Controlled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Name__c</fullName>
        <description>Hosts the partner name nominated by the application primarily for study abroad and exchange applications. The partner name is used to link the application to the correct partner application record on submission.</description>
        <label>Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residency_Status__c</fullName>
        <description>Used to define the applicant&apos;s/applications residency status at the point in time of the application.</description>
        <inlineHelpText>Used to define the applicant&apos;s/applications residency status at the point in time of the application.</inlineHelpText>
        <label>Residency Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DOM-AUS</fullName>
                    <label>I am an Australian Citizen (with or without dual citizenship)</label>
                </value>
                <value>
                    <fullName>DOM-NZ</fullName>
                    <label>I am a New Zealand Citizen</label>
                </value>
                <value>
                    <fullName>DOM-SUN</fullName>
                    <label>I am a Malaysian Citizen or a Malaysian Permanent Resident (i.e. I hold a Malaysian PR visa)</label>
                </value>
                <value>
                    <fullName>DOM-PR</fullName>
                    <label>I am an Australian Permanent Resident (i.e. I hold an Australian PR visa)</label>
                </value>
                <value>
                    <fullName>DOM-SA</fullName>
                    <label>I am a South African Citizen</label>
                </value>
                <value>
                    <fullName>DOM-HV</fullName>
                    <label>I hold an Australian Permanent Humanitarian Visa</label>
                </value>
                <value>
                    <fullName>INTRNTNL</fullName>
                    <label>I hold or will be getting an Australian Student Visa</label>
                </value>
                <value>
                    <fullName>INT-TEP</fullName>
                    <label>I hold a non-student Australian Temporary Visa (e.g. spouse visa or work visa)</label>
                </value>
                <value>
                    <fullName>INT-SUN-P</fullName>
                    <label>I hold a Malaysian Student or Temporary Pass</label>
                </value>
                <value>
                    <fullName>INT-SUN</fullName>
                    <label>I will be getting a Malaysian Student or Temporary Pass</label>
                </value>
                <value>
                    <fullName>INT-SA</fullName>
                    <label>I hold or will be getting a South African Student/Study Visa</label>
                </value>
                <value>
                    <fullName>DOM-IDN</fullName>
                    <label>I am an Indonesian Citizen</label>
                </value>
                <value>
                    <fullName>DOM-IDN-PR</fullName>
                    <label>I am an Indonesian Permanent Resident</label>
                </value>
                <value>
                    <fullName>INT-IDN-P</fullName>
                    <label>I currently have a visa to study in Indonesia</label>
                </value>
                <value>
                    <fullName>INT-IDN</fullName>
                    <label>I will be getting a visa to study in Indonesia</label>
                </value>
                <value>
                    <fullName>&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;</fullName>
                    <isActive>false</isActive>
                    <label>&lt;IMG SRC=&quot;javascript:alert(&apos;XSS&apos;);&quot;&gt;</label>
                </value>
                <value>
                    <fullName>https://myapp.monash.edu/admissions/a244a000000SH9A/</fullName>
                    <isActive>false</isActive>
                    <label>https://myapp.monash.edu/admissions/a244a000000SH9A/</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission_Progress__c</fullName>
        <description>Defines the progress of submission that the applicant is going through.</description>
        <label>Submission Progress</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Study__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Declaration</fullName>
                    <default>true</default>
                    <label>Declaration</label>
                </value>
                <value>
                    <fullName>Personal Details</fullName>
                </value>
                <value>
                    <fullName>Study Preferences</fullName>
                </value>
                <value>
                    <fullName>Credentials</fullName>
                </value>
                <value>
                    <fullName>Scholarship</fullName>
                </value>
                <value>
                    <fullName>Application Details</fullName>
                </value>
                <value>
                    <fullName>Research Program</fullName>
                </value>
                <value>
                    <fullName>English Proficiency</fullName>
                </value>
                <value>
                    <fullName>Qualifications</fullName>
                </value>
                <value>
                    <fullName>Awards, Prizes &amp; Scholarship</fullName>
                </value>
                <value>
                    <fullName>Employment &amp; Research Experience</fullName>
                </value>
                <value>
                    <fullName>Referees</fullName>
                </value>
                <value>
                    <fullName>Publications</fullName>
                </value>
                <value>
                    <fullName>Creative Works</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>Theatre Performance</fullName>
                </value>
                <value>
                    <fullName>Exhibitions</fullName>
                </value>
                <value>
                    <fullName>Additional Supporting Information</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Application Fee</fullName>
                </value>
                <value>
                    <fullName>Submit</fullName>
                </value>
                <value>
                    <fullName>Validate &amp; Submit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Study__c</fullName>
        <description>Type of Study indicating the application&apos;s study type in the context of Exchange/Study Abroad.</description>
        <label>Type of Study</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Study Abroad</fullName>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>Coursework</fullName>
                </value>
                <value>
                    <fullName>Graduate Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Agreement__c.object
<CustomObject>
    <description>Account child object to track agreements and quotas of a partner account</description>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Agreements</relationshipLabel>
        <relationshipName>Partner_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study_Type_Supported__c</fullName>
        <defaultValue>&apos;Exchange&apos;</defaultValue>
        <description>Study types supported on the Partner Agreement.</description>
        <label>Study Type Supported</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>Study Abroad</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <isActive>false</isActive>
                    <label>Agent</label>
                </value>
                <value>
                    <fullName>Provider</fullName>
                    <isActive>false</isActive>
                    <label>Provider</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Agreement</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Partner Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PartnerApplicationService.cls
/**
 * @author      Kristian Vegerano
 * @description Services class primarily used on partner experience pages
 * @group       Services
 * @revision    03/02/2021 - Kristian Vegerano - Created
 */ 
public with sharing class PartnerApplicationService {
    /**
     * @author      Kristian Vegerano
     * @description Retrieves current user (Partner User) details and details about the partner account's partner agreement details
     * @revision    27/02/2021 - Kristian Vegerano - Created
     */
    @AuraEnabled
    public static Map<String, Object> retrievePartnerUserDetails(String userId) {
        //Initialize variables
        Map<String, Object> resultMap = new Map<String, String>();

        try{
            //Query user details
            User currentUser = [SELECT Id, Contact.AccountId FROM User WHERE Id = :userId];

            //Retrieve partner agreement details - latest agreement
            Set<String> allowedApplicationTypes = new Set<String>();
            List<Partner_Agreement__c> partnerAgreementList = new List<Partner_Agreement__c>();
            for(Partner_Agreement__c loopPartnerAgreement : [SELECT Id, Study_Type_Supported__c, Expiry_Date__c 
                                                            FROM Partner_Agreement__c
                                                            WHERE Partner_Account__c = :currentUser.Contact.AccountId
                                                            ORDER BY CreatedDate ASC]){
                if(loopPartnerAgreement.Expiry_Date__c == null || System.TODAY() < loopPartnerAgreement.Expiry_Date__c){
                    if(loopPartnerAgreement.Study_Type_Supported__c != null){
                        allowedApplicationTypes.addAll(loopPartnerAgreement.Study_Type_Supported__c.split(';'));
                    }
                }
            }

            //Retrieve which study type has unit related to it
            Map<String, Set<String>> typeToUnitMap = retrieveAvailableVirtualCourseUnits();

            //add result to return
            resultMap.put('STATUS', 'SUCCESS');
            resultMap.put('ALLOWED_APP_TYPES', JSON.serialize(allowedApplicationTypes));
            resultMap.put('PARTNER_ACCOUNT_ID', JSON.serialize(currentUser.Contact.AccountId));
            resultMap.put('NOT_KNOWN_TO_MONASH_ID', JSON.serialize(Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Non_Student').getRecordTypeId()));    
            resultMap.put('STUDYTYPE_UNITS', JSON.serialize(typeToUnitMap)); 
        }catch(Exception ex){
            //add error
            resultMap.put('STATUS', 'ERROR');
            resultMap.put('MESSAGE', ex.getMessage());
        }

        //Return results
        return resultMap;
    }

    /**
     * @author      Kristian Vegerano
     * @description Creates an applicant, application and/or user lodged by the partner
     * @revision    27/02/2021 - Kristian Vegerano - Created
     *              31/03/2021 - Vinothraja - added Location param while Application creation
     *              07/06/2021 - SFTG-2007 - added citizenship type options and removed send to Student 
     */
    @AuraEnabled
    public static Map<String, Object> createApplication(String applicantJSON, String partnerAccountId, String applicationType, String studyDuration, String location, String citizenshipType) {
        //Initialize variables
        Map<String, Object> resultMap = new Map<String, String>();
        
        //Create a savepoint before all processing
        Savepoint registerUserSavePoint = Database.setSavepoint();

        try{
            Boolean hasExistingContact = false;
            //create applicant
            Contact newApplicant = (Contact)JSON.deserialize(applicantJSON, Contact.class);            
            
            //check if there are duplicates first name, last name, birthdate
            for(Contact matchedContact : [SELECT Id 
                                          FROM Contact
                                          WHERE First_Name__c = :newApplicant.First_Name__c
                                                AND Last_Name__c = :newApplicant.Last_Name__c
                                                AND Email = :newApplicant.Email
                                                AND BirthDate = :newApplicant.BirthDate
                                          ORDER BY CreatedDate ASC
                                          LIMIT 100]){
                hasExistingContact = true;
                newApplicant.Id = matchedContact.Id;
            }
            upsert newApplicant;

            //retrieve partner agreement for the partner account
            Id partnerAgreementId;
            String partnerName;
            for(Partner_Agreement__c loopAgreement : [SELECT Id, Partner_Account__r.Name FROM Partner_Agreement__c WHERE Partner_Account__c = :partnerAccountId LIMIT 1]){
                partnerAgreementId = loopAgreement.Id;
                partnerName = loopAgreement.Partner_Account__r.Name;
            }

            //create application
            Application__c newApplication = new Application__c(Agent__c = partnerAccountId,
                                                               Applicant__c = newApplicant.Id,
                                                               Submission_Progress__c = 'Study Preferences',
                                                               Furthest_Progress__c = 'Review',
                                                               Source_System__c = 'Partner',
                                                               Campus_Location__c = location,
                                                               Partner_Controlled__c = true,
                                                               Type_of_Study__c = applicationType,
                                                               Duration_of_Study__c = studyDuration,
                                                               Residency_Status__c = citizenshipType,
                                                               Partner_Agreement__c = partnerAgreementId,
                                                               Partner_Name__c = partnerName,
                                                               From_Portal__c = true);     
            StudyLocationController.setResidencySubStatuses(newApplication);
            StudyLocationController.setCountryOfCitizenship(newApplication);
            insert newApplication;

            // Proceed with generating user if theres no existing contact
            /*if(!hasExistingContact){
                //generate user
                if(isSendToStudent){
                    resultMap.putAll(ExperienceAuthenticationServices.generateUserResetApplicationProgressStatus(newApplication.Id));
                }
            }else{
                // Send email notification to the applicant for the new email
            }*/

            //add result to return
            resultMap.put('STATUS', 'SUCCESS');
            resultMap.put('APPLICANT', JSON.serialize(newApplicant));
            resultMap.put('APPLICATION', JSON.serialize(newApplication));
        }catch(Exception ex){
            //Rollback to when the user isnt created yet
            Database.rollback(registerUserSavePoint);

            //log error
            ExLog.add('PartnerApplicationService', 'Partner Experience', 'createApplication', ex);

            //add error
            resultMap.put('STATUS', 'ERROR');
            resultMap.put('MESSAGE', ex.getMessage());
        }

        //Return results
        return resultMap;
    }

    /**
     * @author      Kristian Vegerano
     * @description Retrieves available course study type to unit association metadata
     * @revision    12/05/2021 - Kristian Vegerano - Created
     */
    public static Map<String, Set<String>> retrieveAvailableVirtualCourseUnits(){
        //Retrieve available course - unit offering links (for virtual)
        Map<String, Set<String>> courseCodeMap = new Map<String, Set<String>>();
        for(Available_Virtual_Course_Unit__mdt loopCourseUnit : [SELECT Id, Course_Code__c, Unit_Code__c FROM Available_Virtual_Course_Unit__mdt]){
            if(!courseCodeMap.containsKey(loopCourseUnit.Course_Code__c)){
                courseCodeMap.put(loopCourseUnit.Course_Code__c, new Set<String>());
            }
            courseCodeMap.get(loopCourseUnit.Course_Code__c).add(loopCourseUnit.Unit_Code__c);
        }

        Set<String> checkedCourseCode = new Set<String>();
        Map<String, Set<String>> typeToUnitMap = new Map<String, Set<String>>();
        for(Course_Offering__c loopCourseOffering : [SELECT Id, Course_Code__c, Course_Title__c FROM Course_Offering__c WHERE Course_Code__c IN :courseCodeMap.keySet()]){
            //check if the course code has already been processed
            if(!checkedCourseCode.contains(loopCourseOffering.Course_Code__c)){
                String studyType;
                if(loopCourseOffering.Course_Title__c != null){
                    //check if the course offering description
                    if(loopCourseOffering.Course_Title__c.containsIgnoreCase(Constants.MONASH_ABROAD_SA_STUDY_TYPE)){
                        studyType = Constants.MONASH_ABROAD_SA_STUDY_TYPE;
                    }else if(loopCourseOffering.Course_Title__c.containsIgnoreCase(Constants.MONASH_ABROAD_EX_STUDY_TYPE)){
                        studyType = Constants.MONASH_ABROAD_EX_STUDY_TYPE;
                    }

                    //check if the course code map has a unit for the course offering's course code
                    if(!typeToUnitMap.containsKey(studyType)){
                        typeToUnitMap.put(studyType, new Set<String>());
                    }
                    //check if there is a unit related to the course code
                    if(courseCodeMap.containsKey(loopCourseOffering.Course_Code__c)){
                        typeToUnitMap.get(studyType).addAll(courseCodeMap.get(loopCourseOffering.Course_Code__c));
                    }
                }
            }
            checkedCourseCode.add(loopCourseOffering.Course_Code__c);
        }

        return typeToUnitMap;
    }
    
    /**
     * @author      Shalini Mendu
     * @description Retrieves Partner Agreement quota details
     * @revision   8/June/2021 - Created
     */
    @AuraEnabled
    public static  Map<String, Object> retrievePartnerAgreementDetails(String userId) {
        User currentUser = [SELECT Id, Contact.AccountId FROM User WHERE Id = :userId];
        List<Partner_Agreement__c> pa =[select Quota__c, Study_Type_Supported__c,Remaining_quota__c, Expiry_date__c from Partner_Agreement__c
        WHERE Partner_Account__c = :currentUser.Contact.AccountId AND Study_Type_Supported__c INCLUDES ('EXCHANGE')
        ];
        
        Map<String, Object> resMap = new Map<String,Object>();
        resMap.put('Quota', pa[0].quota__c);
        resMap.put('RemainingQuota', pa[0].Remaining_quota__c);
        resMap.put('ExpiryDate', pa[0].Expiry_date__c);
        return  resMap;
    }
}