force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Agent_Org_Unit_Code__c</fullName>
        <description>The SAP/Callista key for this Agency</description>
        <label>Agency Org Unit Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup to the Agency account</description>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Status__c</fullName>
        <description>Track the assessment process once an application is submitted by the applicant</description>
        <inlineHelpText>Track the assessment process once an application is submitted by the applicant</inlineHelpText>
        <label>Assessment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assessment_Flow_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Breached_visa_condition__c</fullName>
        <description>Indicates if the applicant has breached visa conditions in the past.</description>
        <inlineHelpText>Have you breached any visa conditions in any country?</inlineHelpText>
        <label>Breached visa condition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Callista_Application_Id__c</fullName>
        <externalId>true</externalId>
        <label>Callista Application Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Convicted_of_crime_offence__c</fullName>
        <description>Indicates if the applicant has been convicted of any crime or offence in any country.</description>
        <inlineHelpText>Have you been convicted of any crime or offence in any country?</inlineHelpText>
        <label>Convicted of crime/offence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Application Processing Fee Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee_Waiver_Redeemed__c</fullName>
        <description>Indicates if the Waiver code has been redeemed for Application fees</description>
        <label>Processing Fee Waiver Redeemed</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HasDisabilities__c</fullName>
        <label>HasDisabilities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Medical_health_prevent_visa__c</fullName>
        <description>Indicates if the applicant has any medical/health issues that may prevent them from obtaining a visa.</description>
        <inlineHelpText>Do you have any medical or health issues that may prevent you from obtaining your visa?</inlineHelpText>
        <label>Medical/health prevent visa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Protection_visa_in_any_country__c</fullName>
        <description>Indicates if the applicant has been issued a protection visa in any other country.</description>
        <inlineHelpText>Have you been issued a protection visa in any country to date?</inlineHelpText>
        <label>Protection visa in any country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Refused_entry_visa_to_any_country__c</fullName>
        <description>Indicates if the applicant has been refused an entry visa to any country.</description>
        <inlineHelpText>Have you been refused an entry visa to any country?</inlineHelpText>
        <label>Refused entry visa to any country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent for Submission</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Data Validation Ready</fullName>
                </value>
                <value>
                    <fullName>Failed Data validation</fullName>
                </value>
                <value>
                    <fullName>Submission on Hold (Duplicate Contact)</fullName>
                </value>
                <value>
                    <fullName>Agent Declaration Accepted</fullName>
                </value>
                <value>
                    <fullName>Sent Draft Application to Applicant</fullName>
                </value>
                <value>
                    <fullName>Applicant Declaration Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Progress__c</fullName>
        <description>Defines the progress of submission that the applicant is going through.</description>
        <label>Submission Progress</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Study__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Declaration</fullName>
                    <default>true</default>
                    <label>Declaration</label>
                </value>
                <value>
                    <fullName>Personal Details</fullName>
                </value>
                <value>
                    <fullName>Study Preferences</fullName>
                </value>
                <value>
                    <fullName>Credentials</fullName>
                </value>
                <value>
                    <fullName>Scholarship</fullName>
                </value>
                <value>
                    <fullName>Application Details</fullName>
                </value>
                <value>
                    <fullName>Research Program</fullName>
                </value>
                <value>
                    <fullName>English Proficiency</fullName>
                </value>
                <value>
                    <fullName>Qualifications</fullName>
                </value>
                <value>
                    <fullName>Awards, Prizes &amp; Scholarship</fullName>
                </value>
                <value>
                    <fullName>Employment &amp; Research Experience</fullName>
                </value>
                <value>
                    <fullName>Referees</fullName>
                </value>
                <value>
                    <fullName>Publications</fullName>
                </value>
                <value>
                    <fullName>Creative Works</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>Theatre Performance</fullName>
                </value>
                <value>
                    <fullName>Exhibitions</fullName>
                </value>
                <value>
                    <fullName>Additional Supporting Information</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Application Fee</fullName>
                </value>
                <value>
                    <fullName>Submit</fullName>
                </value>
                <value>
                    <fullName>Validate &amp; Submit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Study__c</fullName>
        <description>Type of Study indicating the application&apos;s study type in the context of Exchange/Study Abroad.</description>
        <label>Type of Study</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Study Abroad</fullName>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>Coursework</fullName>
                </value>
                <value>
                    <fullName>Graduate Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Welcome_Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Welcome Email Sent (MyApp)</label>
        <type>Checkbox</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Assessment_Flow_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Required</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting for docs</fullName>
        <label>Applicant Input Required</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Required</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinued</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Input Required</fullName>
    </customValue>
    <description>Assessment status values to track progress of assessment tasks</description>
    <masterLabel>Assessment Flow Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ApplicationASChangeApplicationRecord_FT.cls
/**
 * @description       : Test class for Application : AS : Change Application Record flow
 * @author            : rajesh.punjabi@monash.edu
 * @last modified on  : 24-02-2025
 * @last modified by  : rajesh.punjabi@monash.edu
**/
@isTest(isParallel=true)
public with sharing class ApplicationASChangeApplicationRecord_FT {

    /**
     * Sets up test data:
     * - Creates a test Contact (Applicant)
     * - Creates a test Account (Agent)
     * - Inserts an Application__c record
    */
    @testSetup 
    static void setup() {
        Contact testApplicant = new Contact(LastName = 'TestApplicantFlowTest', MailingCountry = 'Malaysia');
        insert testApplicant;  

        Account oAccount = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization').getRecordTypeId(),
            Name = 'ApplicationASChangeApplicationRecord_FT-1');
        insert oAccount;

        Application__c oApplication = new Application__c(
            Callista_Application_Id__c = 'FPB' + randomNumber(),
            Fee_Payment__c = false,
            Fee_Waiver_Redeemed__c = 'Test',
            Refused_entry_visa_to_any_country__c = 'Yes',
            Breached_visa_condition__c = 'Yes',
            Medical_health_prevent_visa__c = 'Yes',
            Protection_visa_in_any_country__c = 'Yes',
            Convicted_of_crime_offence__c = 'Yes',
            HasDisabilities__c = 'Yes',
            Submission_Progress__c = 'Submit',
            Assessment_Status__c = 'Required',
            Status__c = 'Submission on Hold (Duplicate Contact)',
            Type_of_Study__c = 'Coursework',
            Agent__c = oAccount.Id,
            Agent_Org_Unit_Code__c = 'AgentCode_123',
            Welcome_Email_Sent__c = false,
            Applicant__c = testApplicant.Id);
        insert oApplication;
    }

    /**
     * Test Welcome Email flag is set on record insert
    */
    @isTest
    public static void testSetWelcomeEmailFlagInsertSuccess() {
        
        // GIVEN: A new Application with eligible status and study type
        Application__c oApplication = new Application__c(
            Status__c = 'Sent for Submission',
            Type_of_Study__c = 'Coursework',
            Welcome_Email_Sent__c = false,
            Applicant__c = [SELECT Id FROM Contact WHERE LastName = 'TestApplicantFlowTest' LIMIT 1].Id);

        // WHEN: The record is inserted
        Test.startTest();
            insert oApplication;
        Test.stopTest();

        // THEN: The Welcome_Email_Sent__c flag should be set to true
        Application__c result = [SELECT Welcome_Email_Sent__c FROM Application__c WHERE Id = :oApplication.Id];
        Assert.areEqual(true, result.Welcome_Email_Sent__c, 'Welcome Email Sent should be set to true');
    }

    /**
     * Test Welcome Email flag is not set on insert
    */
    @isTest
    public static void testSetWelcomeEmailFlagInsertFailure1() {
        // GIVEN: A new Application with ineligible status
        Application__c oApplication = new Application__c(
            Status__c = 'Review',
            Type_of_Study__c = 'Coursework',
            Welcome_Email_Sent__c = false,
            Applicant__c = [SELECT Id FROM Contact WHERE LastName = 'TestApplicantFlowTest' LIMIT 1].Id);

        // WHEN: The record is inserted
        Test.startTest();
            insert oApplication;
        Test.stopTest();

        // THEN: The Welcome_Email_Sent__c flag should remain false
        Application__c result = [SELECT Welcome_Email_Sent__c FROM Application__c WHERE Id = :oApplication.Id];
        Assert.areNotEqual(true, result.Welcome_Email_Sent__c, 'Welcome Email Sent should not be set to true');
    }

    /**
     * Test Welcome Email flag is not set on insert
    */
    @isTest
    public static void testSetWelcomeEmailFlagInsertFailure2() {
        // GIVEN: A new Application with ineligible study type
        Application__c oApplication = new Application__c(
            Status__c = 'Sent for Submission',
            Type_of_Study__c = 'Graduate Research',
            Welcome_Email_Sent__c = false,
            Applicant__c = [SELECT Id FROM Contact WHERE LastName = 'TestApplicantFlowTest' LIMIT 1].Id);

        // WHEN: The record is inserted
        Test.startTest();
            insert oApplication;
        Test.stopTest();

        // THEN: The Welcome_Email_Sent__c flag should remain false
        Application__c result = [SELECT Welcome_Email_Sent__c FROM Application__c WHERE Id = :oApplication.Id];
        Assert.areNotEqual(true, result.Welcome_Email_Sent__c, 'Welcome Email Sent should not be set to true');
    }

    /**
     * Test Welcome Email flag is set on update
    */
    @isTest
    public static void testSetWelcomeEmailFlagUpdateSuccess() {
        
        // GIVEN: An existing Application with Welcome_Email_Sent__c = false
        Application__c oApplication = [SELECT Id, Status__c, Welcome_Email_Sent__c FROM Application__c LIMIT 1];
        oApplication.Status__c = 'Sent for Submission';

        // WHEN: The status is updated to 'Sent for Submission'
        Test.startTest();
            update oApplication;
        Test.stopTest();

        // THEN: The Welcome_Email_Sent__c flag should be set to true
        Application__c result = [SELECT Welcome_Email_Sent__c FROM Application__c WHERE Id = :oApplication.Id];
        Assert.areEqual(true, result.Welcome_Email_Sent__c, 'Welcome Email Sent should be set to true');
    }

    /**
     * Test Welcome Email flag is not set in update
    */
    @isTest
    public static void testSetWelcomeEmailFlagUpdateFailure1() {
        
        // GIVEN: An existing Application
        Application__c oApplication = [SELECT Id, Status__c, Welcome_Email_Sent__c FROM Application__c LIMIT 1];
        oApplication.Status__c = 'Review';

        
        // WHEN: The status is updated to an ineligible value
        Test.startTest();
            update oApplication;
        Test.stopTest();

        // THEN: The Welcome_Email_Sent__c flag should remain unchanged (false)
        Application__c result = [SELECT Welcome_Email_Sent__c FROM Application__c WHERE Id = :oApplication.Id];
        Assert.areNotEqual(true, result.Welcome_Email_Sent__c, 'Welcome Email Sent should not be set to true');
    }

    /**
     * Test Agent lookup is set to Null when Agent Org Unit Code is cleared
    */
    @isTest
    public static void testUpdateAgentLookupToNull() {
        
        // GIVEN: An Application with Agent and Agent Org Unit Code populated
        Application__c oApplication = [SELECT Id, Agent__c, Agent_Org_Unit_Code__c FROM Application__c LIMIT 1];
        oApplication.Agent_Org_Unit_Code__c = '';

        // WHEN: The Agent Org Unit Code is cleared
        Test.startTest();
            TriggerCommon.disableTrigger('Application__c');
            update oApplication;
            TriggerCommon.enableTrigger('Application__c');
        Test.stopTest();

        // THEN: The Agent__c field should be set to null
        Application__c result = [SELECT Agent__c FROM Application__c WHERE Id = :oApplication.Id];
        Assert.isNull(result.Agent__c, 'Agent field should be blank');
    }

    /**
     * Test application is deleted when status updated to cancel
    */
    @isTest
    public static void testRequestApplicationCancel() {
        
        // GIVEN: An Application in Draft status
        Application__c oApplication = [SELECT Id, Status__c FROM Application__c LIMIT 1];
        oApplication.Status__c = 'Draft';
        update oApplication;

        
        // WHEN: The status is changed to 'Cancelled'
        oApplication.Status__c = 'Cancelled';

        Test.startTest();
            update oApplication;
        Test.stopTest();

        // THEN: The record should be deleted
        List<Application__c> apps = [SELECT Id FROM Application__c];
        Assert.areEqual(0, apps.size(), 'Application should have been deleted');
    }

    /**
     * @description Helper method to generate a random number for unique test data
     * @return Integer between 0 and 9999
    */
    public static Integer randomNumber() {
        return Integer.valueOf(Math.random() * 9999);
    }
}