force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Access_and_Equity_Question__c</fullName>
        <description>Do you have a disability, mental health or ongoing medical condition that may affect your studies or may prevent you to undertake full-time study?</description>
        <inlineHelpText>Do you have a disability, mental health or ongoing medical condition that may affect your studies or may prevent you to undertake full-time study?</inlineHelpText>
        <label>Access and Equity Question</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Intention__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Intention</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee_Amount__c</fullName>
        <description>This is used to capture the application fee amount. The amount is determined by the metadata.</description>
        <label>Application Processing Fee Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fee_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Application Processing Fee Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HasDisabilities__c</fullName>
        <label>HasDisabilities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manual_Assessment_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be set if a user has selected to push the Application to Course Entry Check, when the Visa and/or Qualifications have been awaiting documents for greater than the configured time period.</description>
        <inlineHelpText>Course Entry Check entered with the Visa and/or Qualification tasks incomplete.</inlineHelpText>
        <label>Manual Assessment Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Task_Qualification__c</fullName>
        <label>Task: Qualification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assessment_Flow_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Visa__c</fullName>
        <description>Track if visa assessment needs to be conducted</description>
        <inlineHelpText>Track if visa assessment needs to be conducted</inlineHelpText>
        <label>Task: Visa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assessment_Flow_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Admissions_Process_Type__c</fullName>
        <label>Admissions Process Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callista_Unique_Key_ADM__c</fullName>
        <description>Person ID - Admission Appl - Course Code - Application Seq</description>
        <externalId>true</externalId>
        <label>ADM Unique Key</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Course_Start_Date__c</fullName>
        <label>Course Start Date</label>
        <type>Date</type>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Encumbrance__c.object
<CustomObject>
    <description>Links an Encumbrace to a Contact</description>
    <label>Encumbrance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encumbrance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Assessment_Flow_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Required</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting for docs</fullName>
        <label>Applicant Input Required</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Required</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinued</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Input Required</fullName>
    </customValue>
    <description>Assessment status values to track progress of assessment tasks</description>
    <masterLabel>Assessment Flow Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/asmAlertsACPCC.cls
/*
 * @author       Victor Cheng
 * @date         2018
 * @description  
 * @revision     Stefan Scheit (2018-09-15): Changed class to with sharing
 * @revision     Shalini Mendu - 28/2/2019 Fix for SFTDC-255
 *               Martin Cadman - Removed user query that was not utilised and generated errors
*/
public with sharing class asmAlertsACPCC {

    public static String MESSAGE = 'message';

    public static String APPLICATION_ID = 'applicationId';
    public static String CONTACT_ID = 'contactId';
    public static String IS_UNDER18_AT_APPLICATION = 'isUnder18AtApplication';
    public static String AGE_AT_COURSE_START = 'ageAtCourseStart';    
    public static String HAS_ENCUMBRANCES = 'hasEncumbrances';
    public static String APPLICATION_FEE_PAID = 'applicationFeePaid';
    public static String APPLICATION_FEE_AMOUNT = 'applicationFeeAmt';
    public static String HAS_ACCESS_EQUITY = 'hasAccessEquity';
    public static String GTE_ALERT_SUBMISSION_LOCATION = 'gteAlertSubmissionLocation';
    public static String GTE_ALERT_QUALIFICATION = 'gteAlertQualification';
    public static String CREDIT_INTENTION = 'creditIntention';
    public static String TASK_QUALIFICATION = 'taskQualification';
    public static String TASK_VISA = 'taskVisa';
    public static String MANUAL_ASSESSMENT_OVERRIDE = 'manualAssessmentOverride';
    public static String READMIT = 'readmit';
    public static String ADM_KEY = 'admkey';

    @AuraEnabled
    public static Map<String, Object> GetACPAlerts(Id acpId)
    {

        Map<String, Object> mapAlerts = new Map<String, Object>();

        if(acpId == NULL)
        {
            ExLog.add('asmAlertsACPCC', 'N/A', 'GetACPAlerts', 'ACP ID is null');
            mapAlerts.put(MESSAGE, 'Error:ACP Id is null');
        }
        else
        {
            List<Application_Course_Preference__c > listACPs = [SELECT id
                    , Application__c
                    , Applicant__c
                    , Course_Start_Date__c
                    , Admissions_Process_Type__c
                    , Callista_Unique_Key_ADM__c
            FROM Application_Course_Preference__c
            WHERE id =: acpId LIMIT 1];
            if(listACPs.size() != 1)
            {
                ExLog.add('asmAlertsACPCC', 'N/A', 'GetACPAlerts', 'Could not find ACP with Id ' + acpId);
                mapAlerts.put(MESSAGE, 'Error:ACP Id invalid');
            }
            else
            {
                // all good, continue
                Application_Course_Preference__c acp = listACPs[0];
                
                System.Debug('asmAlertsACP: ACP.application = ' + acp.Application__c);

                
                Id appId = acp.Application__c;                
                // application Id for debugging, house keeping
                mapAlerts.put(APPLICATION_ID, appId);
                
                Id contactId = acp.Applicant__c;
                mapAlerts.put(CONTACT_ID, contactId);

                if(listACPs[0].Admissions_Process_Type__c == 'RE-ADMIT'){
                    mapAlerts.put(READMIT, true);
                }

                if(String.isBlank(listACPs[0].Callista_Unique_Key_ADM__c)){
                    mapAlerts.put(ADM_KEY, true);
                }

                List<Application__c> listApplications = [SELECT id
                                                     , Applicant__c
                                                     , Fee_Payment__c     
                                                     , Credit_Intention__c
                                                     , HasDisabilities__c
                                                     , Submitted_Date__c
                                                     , Fee_Amount__c
                                                     , Task_Qualification__c
                                                     , Manual_Assessment_Override__c
                                                     , Task_Visa__c   
                                                     //, Access_and_Equity_Question__c
                                                     FROM Application__c
                                                     WHERE id =: appId LIMIT 1];
                if(listApplications.size() != 1)
                {
                    ExLog.add('asmAlertsACPCC', 'N/A', 'GetACPAlerts', 'Could not find Application with Id ' + appId);
                    mapAlerts.put(MESSAGE, 'Error:Application Id invalid');
                }
                else
                {          
                    Application__c application = listApplications[0];
                        
                    // encumbrances
                    mapAlerts.put(HAS_ENCUMBRANCES, HasAnyEncumbrance(contactId));
    
                    // application fee                    
	                mapAlerts.put(APPLICATION_FEE_PAID, application.Fee_Payment__c);

                    // fee amount - Fix for SFTDC-255
                    mapAlerts.put(APPLICATION_FEE_AMOUNT, application.Fee_Amount__c);

                    // GTE
                    for(assessmentsDSSandGTECheck.DSSandGTECheckResponse res : assessmentsDSSandGTECheck.DSSandGTECheck(new List<Id>{acpId})){
                        if(res.GTEcountry) 
                            mapAlerts.put(GTE_ALERT_SUBMISSION_LOCATION, res.GTEcountry);
                        if(res.GTEQual)
                            mapAlerts.put(GTE_ALERT_QUALIFICATION, res.GTEQual);
                    }
                    
                    // get contact for age calculations
                    List<Contact> listApplicants= [Select c.id, c.Birthdate From Contact c where c.id = :contactId];
        			if (listApplicants.size() == 1) {
                        Contact applicant = listApplicants[0];
                    
                        // under 18 at application
                        mapAlerts.put(IS_UNDER18_AT_APPLICATION, IsAppUnder18AtApplication(applicant.Birthdate, application.Submitted_Date__c));
                        mapAlerts.put(AGE_AT_COURSE_START, AgeAtCourseStart(applicant.Birthdate, acp.Course_Start_Date__c));
                    }
    
                    // Credit Application
                    mapAlerts.put(CREDIT_INTENTION, application.Credit_Intention__c);
                    
                    //TASK QUALIFICATION
                    if(application.Task_Qualification__c == 'Required' || application.Task_Qualification__c == 'In Progress' || application.Task_Qualification__c == 'Waiting for docs' || application.Task_Qualification__c == 'Failed')
                    mapAlerts.put(TASK_QUALIFICATION, true);

                    //TASK VISA
                    if(application.Task_Visa__c == 'Required' || application.Task_Visa__c == 'In Progress' || application.Task_Visa__c == 'Waiting for docs' || application.Task_Visa__c == 'Failed')
                    mapAlerts.put(TASK_VISA, true);

                    // Show alert in ACP record page when Manual Assessment Override (Application__c.Manual_Assessment_Override__c) field is equals to true
                    if (application.Manual_Assessment_Override__c == true)
                        mapAlerts.put(MANUAL_ASSESSMENT_OVERRIDE, true);
    
                    mapAlerts.put(MESSAGE, 'Alerts for ACP:' + acpId + ', application:' + appId +', start date:' + acp.Course_Start_Date__c);
                }               
            }
        }

        return mapAlerts;
    }


    public static Integer AgeAtCourseStart(Date birthDate, Date startDate)
    {
        if(startDate != null && birthDate != null)
        {
            Integer ageAtCourseStart = (birthDate.daysBetween(startDate)/365.2425).intValue();
            System.debug('!@#AgeAtCourseStart:: Age At Course Start ' + ageAtCourseStart);
            return ageAtCourseStart;
        }
        return -1;
    }
    
    public static Boolean IsAppUnder18AtApplication(Date birthDate, Date submittedDate)
    {
        Boolean isUnder18 = false;
        if(birthDate != null && submittedDate != null)
        {
            Decimal ageAtApplication = birthdate.daysBetween(submittedDate)/365.2425;
            System.debug('!@#$asmAlertsACPCC:: Age At Submission ' + ageAtApplication);
            if(ageAtApplication < MyApplicationUtilities.AGE_18)
            {
                isUnder18 = true;
            }
        }
        return isUnder18;   
    }

    private static Boolean HasAnyEncumbrance(Id contactId)
    {
        List<Encumbrance__c> listEncs = MyApplicationUtilities.getEncumbrancesByContact(contactId);
        if(listEncs.size() > 0)
            return true;
        return false;
    }
}