force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Admission_Category__c</fullName>
        <description>Admission Category is a Callista concept for defining groups of applicants with similar Admission Process requirements. Examples are UG-IS for Undergraduate international applications, VTAC-IS for International applications originated from VTAC not direct entry.</description>
        <inlineHelpText>Admission Category is a Callista concept for defining groups of applicants with similar Admission Process requirements. Examples are UG-IS for Undergraduate international applications, VTAC-IS for International applications originated from VTAC not direct</inlineHelpText>
        <label>Admission Category</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bulk_Data_Processing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bulk Data Processing</label>
        <referenceTo>Bulk_Data_Processing__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Course Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>ACP</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Title__c</fullName>
        <label>Course Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <label>Location</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                    <label>WITHDRAWN</label>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Registered - EOI Only</fullName>
                </value>
                <value>
                    <fullName>Registered - Approved</fullName>
                </value>
                <value>
                    <fullName>Registered - Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Registered - Rejected</fullName>
                </value>
                <value>
                    <fullName>Registered - Invoice not processed</fullName>
                </value>
                <value>
                    <fullName>Registered - Invoiced</fullName>
                </value>
                <value>
                    <fullName>Registered - CCFund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Set_Code__c</fullName>
        <label>Unit Set Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bulk_Data_Processing__c.object
<CustomObject>
    <fields>
        <fullName>Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipName>Offer_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Course_Campus__c</fullName>
        <label>Current Course Campus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Course_Code__c</fullName>
        <label>Current Course Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the offer request record assessment</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Review Required</fullName>
                </value>
                <value>
                    <fullName>Ready for Offer</fullName>
                </value>
                <value>
                    <fullName>Generate Offer</fullName>
                </value>
                <value>
                    <fullName>Processing Offer</fullName>
                </value>
                <value>
                    <fullName>Offer Error</fullName>
                </value>
                <value>
                    <fullName>Offer Created</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bulk Data Processing</label>
    <nameField>
        <displayFormat>BDP-{0000000}</displayFormat>
        <label>Transfer Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Data Processing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PLANNED</fullName>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calendar</label>
    <nameField>
        <label>Calendar</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Admission_Category__c</fullName>
        <externalId>true</externalId>
        <label>Admission Category</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Citizenship_Type__c</fullName>
        <label>Citizenship Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DOM-AUS</fullName>
                </value>
                <value>
                    <fullName>DOM-HV</fullName>
                </value>
                <value>
                    <fullName>DOM-NZ</fullName>
                </value>
                <value>
                    <fullName>DOM-PR</fullName>
                </value>
                <value>
                    <fullName>DOMESTIC</fullName>
                </value>
                <value>
                    <fullName>DOM-SA</fullName>
                </value>
                <value>
                    <fullName>INT-SA</fullName>
                </value>
                <value>
                    <fullName>INT-TEP</fullName>
                </value>
                <value>
                    <fullName>INTRNTNL</fullName>
                </value>
                <value>
                    <fullName>DOM-SUN</fullName>
                </value>
                <value>
                    <fullName>INT-SUN</fullName>
                </value>
                <value>
                    <fullName>INT-SUN-P</fullName>
                </value>
                <value>
                    <fullName>DOM-IDN</fullName>
                </value>
                <value>
                    <fullName>DOM-IDN-PR</fullName>
                </value>
                <value>
                    <fullName>INT-IDN-P</fullName>
                </value>
                <value>
                    <fullName>INT-IDN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <externalId>true</externalId>
        <label>Course Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Title__c</fullName>
        <label>Course Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <externalId>true</externalId>
        <label>Location Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>EOI</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Set_Code__c</fullName>
        <externalId>true</externalId>
        <label>Unit Set Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Suggested_Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <formula>Course_Offering__r.Active__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Admission_Category__c</fullName>
        <formula>Course_Offering__r.Admission_Category__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Admission Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bulk_Data_Processing__c</fullName>
        <label>Bulk Data Processing</label>
        <referenceTo>Bulk_Data_Processing__c</referenceTo>
        <relationshipLabel>Suggested Course Offerings</relationshipLabel>
        <relationshipName>Suggested_Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Calendar__c</fullName>
        <formula>Course_Offering__r.Calendar__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calendar</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Citizenship_Type__c</fullName>
        <formula>TEXT(Course_Offering__r.Citizenship_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Citizenship Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <formula>Course_Offering__r.Course_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>Suggested Course Offerings</relationshipLabel>
        <relationshipName>Suggested_Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <formula>Course_Offering__r.Location_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Set_Code__c</fullName>
        <formula>Course_Offering__r.Unit_Set_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Set Code</label>
        <type>Text</type>
    </fields>
    <label>Suggested Course Offering</label>
    <nameField>
        <label>Suggested Course Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suggested Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BDPCourseOfferingMatchingService_Test.cls
/**
 * @author David Browaeys
 * @description Test class for BDPCourseOfferingMatchingService
 * @group Bulk Data Processing
 */
@isTest(isParallel=true)
public inherited sharing class BDPCourseOfferingMatchingService_Test {
    @TestSetup
    static void makeData(){
        TriggerCommon.disableTrigger('Calendar__c');
        TriggerCommon.disableTrigger('Course_Offering__c');
        Country_Attribute__c country = (Country_Attribute__c)TestDataFactory.createSObject(new Country_Attribute__c(Name = 'MALAYSIA'), true); 
        Calendar__c calendar = (Calendar__c) TestDataFactory.createSObject(new Calendar__c(), true);
        Course_Offering__c co = (Course_Offering__c) TestDataFactory.createSObject(new Course_Offering__c(
            Calendar__c = calendar.Id, 
            Course_Title__c = 'Hello World',
            Admission_Category__c = 'UG-IS',
            Course_Code__c = 'DUP101',
            Location_Code__c = 'CLAYTON',
            Unit_Set_Code__c = 'U101',
            Active__c = true,
            Citizenship_Type__c = BDPConstants.DEFAULT_CITIZENSHIP
        ), true);
    }

	@isTest
    private static void testFindDuplicateMatch(){
        Calendar__c calendar = [SELECT Id FROM Calendar__c LIMIT 1 ];
        Course_Offering__c courseOffering = [SELECT Id, Course_Title__c, Calendar__c, Admission_Category__c, Course_Code__c, Location_Code__c, Unit_Set_Code__c, Active__c, Citizenship_Type__c FROM Course_Offering__c WHERE 
                                    Admission_Category__c = 'UG-IS' AND
                                    Calendar__c = :calendar.Id AND
                                    Course_Code__c = 'DUP101' AND 
                                    Location_Code__c = 'CLAYTON' AND
                                    Active__c = true AND
                                    Citizenship_Type__c =: BDPConstants.DEFAULT_CITIZENSHIP LIMIT 1];

        System.assert(courseOffering != null, 'Created the right CO!');

        TriggerCommon.disableTrigger('Application_Course_Preference__c');
        Application_Course_Preference__c acp = (Application_Course_Preference__c) TestDataFactory.createSObject(new Application_Course_Preference__c(Course_Offering__c = courseOffering.Id), true);

        Test.startTest();
            BDPCourseOfferingMatchingService service = new BDPCourseOfferingMatchingService();
            service.init();
            service.sobjectDao = (SObjectDao) Test.createStub(SObjectDao.class, new SObjectDaoMocks());
            TriggerCommon.disableTrigger('Bulk_Data_Processing__c');
            Bulk_Data_Processing__c[] bdps = (Bulk_Data_Processing__c[]) TestDataFactory.createSObjectList(
                    new Bulk_Data_Processing__c(
                        Status__c = 'New',
                        Current_Course_Campus__c = 'MALAYSIA', 
                        Current_Course_Code__c = 'DUP101',
                        Person_ID__c = '123456', 
                        Calendar__c = calendar.Id,
                        Transfer_From__c = acp.Id,
                        Transfer_Admission_Category__c = 'UG-IS', 
                        Transfer_Course_Campus__c = 'CLAYTON',  
                        Transfer_Unit_Set__c = 'U101',
                        Transfer_Course_Code__c = String.valueOf(Math.random()),
                        Transfer_Calendar__c = '2021/1')
                    , 1);
            bdps.addAll((Bulk_Data_Processing__c[]) TestDataFactory.createSObjectList(
                    new Bulk_Data_Processing__c(
                        Status__c = 'New',
                        Current_Course_Campus__c = 'CAUFIELD', 
                        Current_Course_Code__c = 'DUP101',
                        Person_ID__c = '123456', 
                        Calendar__c = calendar.Id,
                        Transfer_Admission_Category__c = 'UG-IS', 
                        Transfer_Course_Campus__c = 'CLAYTON',  
                        Transfer_Unit_Set__c = 'U101',
                        Transfer_Course_Code__c = String.valueOf(Math.random()),
                        Transfer_Calendar__c = '2021/1')
                    , 199));
            insert bdps;
            TriggerCommon.disableTrigger('Suggested_Course_Offering__c');
            service.execute(bdps);
            service.createSuggestedCourseOffering(bdps[0], courseOffering);
            service.commitAll();
        Test.stopTest();
        System.assert(service.suggestedCourseOfferings.size() > 0,'Found at least one match');
    }
    
    @isTest static void testHandleDuplicateResults(){
        TriggerCommon.disableTrigger('Bulk_Data_Processing__c');
        Bulk_Data_Processing__c bdp = (Bulk_Data_Processing__c)TestDataFactory.createSObject(new Bulk_Data_Processing__c(), 'TestDataFactorySettings.BulkDataProcessingDefaults', true);
		Test.startTest();
        BDPCourseOfferingMatchingService service = new BDPCourseOfferingMatchingService();
        service.init();
        service.handleDuplicateResults(bdp, new Suggested_Course_Offering__c[]{
            new Suggested_Course_Offering__c(),
            new Suggested_Course_Offering__c()
        });
        System.assert(service.bdpsUpdate.get(bdp.Id).Log__c == BDPConstants.MULTI_CO_FOUND_MSG, 'Multi. course offering found.');
        
        service.handleDuplicateResults(bdp, new Suggested_Course_Offering__c[]{
            new Suggested_Course_Offering__c()
        });
        System.assert(service.bdpsUpdate.get(bdp.Id).Log__c == null, 'One course offering  found.');
        
        service.handleDuplicateResults(bdp, new Suggested_Course_Offering__c[]{});
        System.assert(service.bdpsUpdate.get(bdp.Id).Log__c == BDPConstants.CO_NOT_FOUND_MSG, 'No course offering found.');
        Test.stopTest();
        
    }

    @isTest
    private static void testFindDuplicateNoMatch(){
        BDPCourseOfferingMatchingService service = new BDPCourseOfferingMatchingService();
        service.init();
        service.sobjectDao = (SObjectDao) Test.createStub(SObjectDao.class, new SObjectDaoMocks());
        service.execute(new Bulk_Data_Processing__c[]{
            (Bulk_Data_Processing__c) TestDataFactory.createSObject(new Bulk_Data_Processing__c(
                Person_ID__c = '123456', 
                Transfer_Course_Campus__c = 'KGHKUHIHU', 
                Transfer_Course_Code__c = 'jygiug'), 'TestDataFactorySettings.BulkDataProcessingDefaults', false)
        });
        System.assert(service.suggestedCourseOfferings.size() == 0,'No match found here');
    }
    
    private class SObjectDaoMocks implements System.StubProvider {

        public Object handleMethodCall(Object stubbedObject, String stubbedMethodName, 
                Type returnType, List<Type> listOfParamTypes, List<String> listOfParamNames, 
                List<Object> listOfArgs) {
            System.debug(stubbedObject);
            System.debug(stubbedMethodName);
            System.debug(returnType);
            System.debug(listOfParamTypes);
            System.debug(listOfParamNames);
            System.debug(listOfArgs);
            return null;
        }
    }
}