force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callista_Applicant_Id__c</fullName>
        <externalId>true</externalId>
        <label>Callista Applicant Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Callista_Application_Id__c</fullName>
        <externalId>true</externalId>
        <label>Callista Application Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Graduate_Research_Application_Type__c</fullName>
        <description>Graduate Research Application Type</description>
        <label>Graduate Research Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admission application only</fullName>
                </value>
                <value>
                    <fullName>Admission and Scholarship</fullName>
                </value>
                <value>
                    <fullName>Scholarship application only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>HDR parent application record for scholarship application only.</description>
        <label>Parent Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Study__c</fullName>
        <description>Type of Study indicating the application&apos;s study type in the context of Exchange/Study Abroad.</description>
        <label>Type of Study</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Study Abroad</fullName>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>Coursework</fullName>
                </value>
                <value>
                    <fullName>Graduate Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>API_Request__c</fullName>
        <description>API Request body to send to callista</description>
        <label>API Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>API_Response__c</fullName>
        <description>API response body to send to callista</description>
        <label>API Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callista_Applicant_Id__c</fullName>
        <formula>Application__r.Callista_Applicant_Id__c</formula>
        <label>Callista Applicant Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Callista_Application_Id__c</fullName>
        <formula>Application__r.Callista_Application_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Callista Application Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course_Title__c</fullName>
        <label>Course Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GradRes_Callista_Id__c</fullName>
        <description>Graduate Research Callista Id</description>
        <label>GradRes Callista Id</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Graduate_Research_Application_Type__c</fullName>
        <description>Graduate research application type in ACP</description>
        <label>Graduate Research Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admission and Scholarship</fullName>
                </value>
                <value>
                    <fullName>Admission</fullName>
                </value>
                <value>
                    <fullName>Scholarship</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Async_Process__e.object
<CustomObject>
    <description>Generic platform event that handles invocation of any Apex Class that implements IPlatformEventInvocable</description>
    <fields>
        <fullName>Parameter__c</fullName>
        <description>Parameter of the class to be invoked</description>
        <label>Parameter</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <description>Apex Class name to be invoked</description>
        <label>Process Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Async Process</label>
    <pluralLabel>Async Processes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Document__c.object
<CustomObject>
    <fields>
        <fullName>API_Request__c</fullName>
        <description>Field created to capture the api request for the related file record</description>
        <label>API Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>API_Response__c</fullName>
        <description>field creted to capture the response for the related file record submitted to callista</description>
        <label>API Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to application record if relevant</description>
        <inlineHelpText>Link to application record if relevant</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate which checklist item the document was uploaded against.</description>
        <label>Document Checklist</label>
        <referenceTo>Document_Checklist__c</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Document</label>
    <nameField>
        <displayFormat>CNDC-{000000}</displayFormat>
        <label>Contact Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist__c.object
<CustomObject>
    <description>Capture documents relevant to different processes that requires documents for verification</description>
    <fields>
        <fullName>Application_Course_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Course Preference</label>
        <referenceTo>Application_Course_Preference__c</referenceTo>
        <relationshipLabel>Document Checklists</relationshipLabel>
        <relationshipName>Document_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to Application</description>
        <inlineHelpText>Link to Application</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Document Checklist</relationshipLabel>
        <relationshipName>Document_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Checklist_Requirement__c</fullName>
        <description>Used to describe what the checklist item is for</description>
        <label>Checklist Requirement</label>
        <type>TextArea</type>
    </fields>
    <label>Document Checklist</label>
    <nameField>
        <displayFormat>DC{YYYY}-{000000}</displayFormat>
        <label>Checklist Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist_Comment__c.object
<CustomObject>
    <description>Comment holder for document checklist</description>
    <fields>
        <fullName>API_Request__c</fullName>
        <description>API Request body for document request patch to Callista</description>
        <label>API Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>API_Response__c</fullName>
        <description>API Response for doc request patch from Callista</description>
        <label>API Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the document comment cancelled</description>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Correlation_Id__c</fullName>
        <description>Correlation Id from Callsita for document req patch success response</description>
        <label>Correlation Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Checklist__c</fullName>
        <description>Linked checklist where the comment is for.</description>
        <label>Document Checklist</label>
        <referenceTo>Document_Checklist__c</referenceTo>
        <relationshipLabel>Document Checklist Comments</relationshipLabel>
        <relationshipName>Document_Checklist_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notify_Email_Addresses__c</fullName>
        <description>Notify Email Addresses for Grad Research document request</description>
        <label>Notify Email Addresses</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Sequence_Number__c</fullName>
        <description>Request Sequence Number from Callista for Document request</description>
        <label>Request Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Document Checklist Comment</label>
    <nameField>
        <displayFormat>DCC{YYYY}-{000000}</displayFormat>
        <label>Document Checklist Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklist Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/GRDocumentRequestPatchToCallistaService.cls
/*******************************************************************************
* @author       Vishal Gupta
* @date         4/11/2024
* @description  invoke callista interface v1/admissions/sms/applications/{applicationId}/hdr-document-requests/{requestSequenceNumber} to patch document request
* @revision      
* 4/11/2024 - Vishal Gupta - Created
*******************************************************************************/
public without sharing class GRDocumentRequestPatchToCallistaService extends UniCRMIntegrationPoint implements Database.AllowsCallouts {

    private static final String INTERFACE_NAME = 'IP12_GR_Callista_Document_Request_Patch';
    private static final String TAG = 'Callista document request patch callout';
    private static final String GRT_SCHOLARSHIP_APPLICATION_ONLY = 'Scholarship application only';
    private static final String GRADUATE_RESEARCH = 'Graduate Research';
    private final Set<String> documentChecklistCommentsFields = new Set<String>{
        'Request_Sequence_Number__c, API_Response__c, API_Request__c, Correlation_Id__c, Notify_Email_Addresses__c, Document_Checklist__r.Checklist_Requirement__c '
    };

    private Contact_Document__c conDoc;
    private String hdrDocId;
    private Document_Checklist_Comment__c checklistComment;
    private Application_Course_Preference__c acpInfo;
    private Application__c applicationInfo;

    /**
     * @author      Vishal Gupta
     * @description Constructor
     * @revision    4/11/2024 - Initial Version
     */
    public GRDocumentRequestPatchToCallistaService (Contact_Document__c conDoc, String hdrDocId) {
        this.conDoc = conDoc;
        this.hdrDocId = hdrDocId;
        this.doInit(INTERFACE_NAME);
    }

    /**
     * @author      Vishal Gupta
     * @description creates request body for the call out
     * @revision    4/11/2024 - Initial Version
     */
    public void createRequestBody(){
      
        try {
            String applicationId;
            Integer requestSeqNumber;
            //replace the applicationId and reqSeqNumber in endpoint : admissions/sms/applications/{applicationId}/hdr-document-requests/{requestSequenceNumber}
            Map<String, String> urlReplaceKeyValuePairs = new Map<String, String>();
            GRDocumentRequestPatchJSON reqJson = new GRDocumentRequestPatchJSON();
            GRDocumentRequestPatchJSON.HDRDocumentRequest hdrDocumentRequest = new GRDocumentRequestPatchJSON.HDRDocumentRequest();
            List<Application__c> applicationData = new ApplicationsSelector().selectByIdWithParentDetailsAndDocuments(new Set<Id>{conDoc.Application__c});
            if(!applicationData.isEmpty()) {
                applicationInfo = applicationData[0];
                List<Application_Course_Preference__c> lstACP = new ApplicationCoursePreferenceSelector().selectByApplicationIdWithParentDetails(new Set<Id>{conDoc.Application__c});
                     
                if(!lstACP.isEmpty() && !String.isBlank(lstACP[0].GradRes_Callista_Id__c)) {
                    acpInfo = lstACP[0];
                    hdrDocumentRequest.hdrApplicationNumber = Integer.valueOf(lstACP[0].GradRes_Callista_Id__c);
                }
                if(!String.isBlank(hdrDocId)) {
                    hdrDocumentRequest.smsDocumentId = Integer.valueOf(hdrDocId);
                }       
                hdrDocumentRequest.submittedDate = String.valueOf(Date.valueOf(conDoc.CreatedDate));
                if(applicationInfo.Type_of_Study__c == GRADUATE_RESEARCH 
                && applicationInfo.Graduate_Research_Application_Type__c == GRT_SCHOLARSHIP_APPLICATION_ONLY
                && applicationInfo.Parent_Application__c != null){
                    hdrDocumentRequest.applicantId = !String.isBlank(applicationInfo.Parent_Application__r.Callista_Applicant_Id__c) ? Integer.valueOf(applicationInfo.Parent_Application__r.Callista_Applicant_Id__c) : null;
                    applicationId = applicationInfo.Parent_Application__r.Callista_Application_Id__c;
                }else{
                    hdrDocumentRequest.applicantId = !String.isBlank(applicationInfo.Callista_Applicant_Id__c) ? Integer.valueOf(applicationInfo.Callista_Applicant_Id__c) : null;
                    applicationId = applicationInfo.Callista_Application_Id__c;
                }
                urlReplaceKeyValuePairs.put('{applicationId}', applicationId);//replacing the the value in URL

                List<Document_Checklist_Comment__c> comments = selectCommentsByChecklistId(conDoc.Document_Checklist__c);
                if(!comments.isEmpty()) {
                    checklistComment = comments[0];
                    requestSeqNumber = comments[0].Request_Sequence_Number__c != null ? Integer.valueOf(comments[0].Request_Sequence_Number__c) : null;
                }
                if(requestSeqNumber != null) {
                    hdrDocumentRequest.requestSequenceNumber = requestSeqNumber;
                    urlReplaceKeyValuePairs.put('{requestSequenceNumber}', String.valueOf(requestSeqNumber));
                }
                reqJson.hdrDocumentRequest = hdrDocumentRequest;       
            }
            this.jsonRequest = reqJson;
            this.constructEndPoint(urlReplaceKeyValuePairs);            
        }catch (Exception ex) {
            Nebula.Logger.error(ex.getMessage(), ex);
        }
        Nebula.Logger.saveLog();
    }

    /**
     * @author      Vishal Gupta
     * @description Read the web service call response & update fields on the Contact Document
     *              records after the call out
     * @revision    4/11/2024 - Initial Version
    */
    public void handleResponse()
    {
        try {
            String correlationId;
            if(checklistComment != null) {
                checklistComment.API_Request__c = jSON.serializePretty(jsonRequest);
                Map<String,Object> respBody = this.getResponseBody();
                checklistComment.API_Response__c = jSON.serialize(respBody);
                if (this.httpResponseCode == 200) {                    
                    if(respBody.containsKey('correlationId')) {
                        correlationId = String.valueOf(respBody.get('correlationId'));
                        checklistComment.Correlation_Id__c = correlationId;
                        Nebula.logger.info('correlationId returned from callista: ' + correlationId).addTag(TAG);

                                          
                    }                    
                } 
                else{
                    Nebula.Logger.info('Response from GRDocumentRequestPatchToCallistaService: '+string.valueOf(this.httpResponseCode)).addTag(TAG);
                }
                update checklistComment; 

                //form the email response and send to the assessor
                if(!String.isBlank(checklistComment.Notify_Email_Addresses__c) && correlationId != null) {
                    generateEmailResponse();
                }      
             }
        }catch (Exception ex) {
            Nebula.Logger.error(ex.getMessage(), ex);
        }
        Nebula.Logger.saveLog();
    }

    /**
     * @author      Vishal Gupta
     * @description form the email template and send it to the assessor
     * @revision    5/12/2024 - Initial Version
    */
    public void generateEmailResponse()
    {
        GRDocumentRequestEmailController emailJson = new GRDocumentRequestEmailController();
        try {
            if(checklistComment != null && applicationInfo != null && acpInfo != null) {
                List<Contact> applicantList = new ContactsSelector().selectById(new Set<Id>{applicationInfo.Applicant__c});
                if(!applicantList.isEmpty()) {
                    String title = applicantList[0].Salutation != null ?  applicantList[0].Salutation : '';
                    String firstName = applicantList[0].FirstName != null ?  applicantList[0].FirstName : '';
                    String lastName = applicantList[0].LastName;
                    emailJson.applicantName = title + ' ' + firstName + ' ' + lastName;
                    emailJson.personId = applicantList[0].Person_ID_unique__c;
                }

                emailJson.applicationId = acpInfo.GradRes_Callista_id__c;
                emailJson.applicationType = applicationInfo.Type_of_Study__c;
                emailJson.courseTitle = acpInfo.Course_Title__c;
                emailJson.documentType = checklistComment.Document_Checklist__r.Checklist_Requirement__c;
                emailJson.recipientEmail = checklistComment.Notify_Email_Addresses__c;
                String jsonRequestString = JSON.serializePretty(emailJson);
                //email will be sent via platform event flow as a workaround because with the current user execution mode, user doesnt have access to the org wide email 
                Async_Process__e event = new Async_Process__e(
                    Process_Name__c = 'GRDocumentRequestEmailController',
                    Parameter__c = jsonRequestString
                );
                // Fire the event
                Database.SaveResult result = EventBus.publish(event);
            }
        }catch (Exception ex) {
            Nebula.Logger.error(ex.getMessage(), ex);
        }
        Nebula.Logger.saveLog();
    }

    /**
     * @description query Document_Checklist_Comment__c record
     * @param documentChecklistId
     * @return `List<Document_Checklist_Comment__c>`
     */
    public List<Document_Checklist_Comment__c> selectCommentsByChecklistId(Id documentChecklistId) {
        DynamicSoqlBuilder soqlBuilder = DynamicSoqlBuilder.getInstance()
                                                            .setEnforced(false) // do not enforce sharing for elevated access
                                                            .validateFields(false); // no need to validate fields, they are static.
        String whereClause = 'Document_Checklist__c = :documentChecklistId AND Cancelled__c = false AND Correlation_Id__c = null ORDER BY Request_Sequence_Number__c DESC LIMIT 1';
        String soqlStr = soqlBuilder.querySObject('Document_Checklist_Comment__c')
            .queryFields(documentChecklistCommentsFields)
            .getQuery(whereClause);
        return Database.query(soqlStr);
    }
    
}