force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Admission_Application_Number__c</fullName>
        <label>Admission Application Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Admission_Application_Number__c</fullName>
        <description>Callista sync field</description>
        <label>Admission Application Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Course Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Qualification_Provided__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <label>Contact Qualification</label>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Date_Achieved__c</fullName>
        <description>Mirror&apos;s related Contact Qualification&apos;s Date Achieved field value</description>
        <formula>Contact_Qualification__r.Date_Achieved__c</formula>
        <label>Date Achieved</label>
        <type>Date</type>
    </fields>
    <label>Application Qualification Provided</label>
    <nameField>
        <displayFormat>AQP-{000000}</displayFormat>
        <label>Application Qualification Provided ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Qualifications Provided</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Date_Achieved__c</fullName>
        <label>Date Achieved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_date_of_completion__c</fullName>
        <inlineHelpText>Approximately when do you expect to complete your education and receive your qualification?</inlineHelpText>
        <label>Expected Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Listening__c</fullName>
        <description>Stores Listening score.</description>
        <inlineHelpText>Stores Listening score.</inlineHelpText>
        <label>Listening</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Qualification_Comments__c</fullName>
        <description>Comment section on Other Qualification Record Type</description>
        <label>Applicant Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualification Lookup</label>
        <referenceTo>Qualification__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reading__c</fullName>
        <description>Stores reading score</description>
        <inlineHelpText>Stores reading score</inlineHelpText>
        <label>Reading</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Result_Type__c</fullName>
        <label>Result Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <label>Score</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Speaking__c</fullName>
        <description>Stores speaking score</description>
        <inlineHelpText>Stores speaking score</inlineHelpText>
        <label>Speaking</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_of_Written_English__c</fullName>
        <description>Stores Written English score</description>
        <inlineHelpText>Stores Written English score</inlineHelpText>
        <label>Test of Written English</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verification_Status__c</fullName>
        <description>Default is UNKNOWN. If an external verification is done for that qualification, assessors update this field.While exchanging information with Callista, values will be as follows: Verified = VERIFIED, Unknown = UNKNOWN, Invalid OR Expired OR Unverified = UNVERIFIED</description>
        <label>Verification Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Unverified</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Score Verified</fullName>
                </value>
                <value>
                    <fullName>Fraudulent</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Writing__c</fullName>
        <description>Stores writing score</description>
        <inlineHelpText>Stores writing score</inlineHelpText>
        <label>Writing</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isTestCompleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Qualification Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Callista_Code__c</fullName>
        <externalId>true</externalId>
        <label>Callista Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_score_Type__c</fullName>
        <label>Sub score Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Listening</fullName>
                </value>
                <value>
                    <fullName>Reading</fullName>
                </value>
                <value>
                    <fullName>Speaking</fullName>
                </value>
                <value>
                    <fullName>Writing</fullName>
                </value>
                <value>
                    <fullName>Test of Written English</fullName>
                </value>
                <value>
                    <fullName>Essay Rating</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Qualification</label>
    <nameField>
        <displayFormat>QUAL-{000}</displayFormat>
        <label>Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Score__c.object
<CustomObject>
    <label>Score</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EnglishTestScoreInterface.cls
/*******************************************************************************
* @author:      Shalini Mendu
* @date:        11.Nov.2019
* @description: Business logic implementation for 'Update English Test score to Callisa'
*               interface.  Forms request JSON in object form, and initiates
*               actual request via inherited method from framework. - SFTN-154
* @revision: 6/2/2020 - SFTN-479-ACP Updates failing on English Test Scores
* @revision: 8/07/2025 - EPCP-4493 PB Migration to Flow
*
*******************************************************************************/
public  class EnglishTestScoreInterface extends UniCRMIntegrationPoint implements Queueable, Database.AllowsCallouts {

    public Id recordId{get;set;}
    public String personId{get;set;}
    Contact_Qualification__c cq = null;     

    //Constructor with Contact Qualification record Id
    public EnglishTestScoreInterface (Id recordId) {
        this.recordId = recordId;
        this.doInit('IP08_Callista_English_Test_Score');
        createRequestBody();
        
        //SFTN-479- Adding personId check 
        if(personId == null){
            ExLog.add('Unable to add English Test score as there is no Person ID for the Contact on the Contact Qualification record:'+recordId,'EnglishTestScoreInterface','execute','No PersonID');
            return;
        }
        buildURIWithParams(personId);
    }

    @InvocableMethod
    public static void fireOutboundRequest(List<Id> recordId){
        EnglishTestScoreInterface obj = new EnglishTestScoreInterface(recordId.get(0));
        if(obj.jsonRequest != null){
            System.enqueueJob(obj);
        }
    }

    // Build URI filling in a parameter which is the Contact.PersonID
    public void buildURIWithParams(String personId)
    {
        Map<String, String> urlReplaceKeyValuePairs = new Map<String, String>();
        urlReplaceKeyValuePairs.put('{0}', personId);
        this.constructEndPoint(urlReplaceKeyValuePairs);
    }
    //create Request body
    public void createRequestBody() {
        try {
            cq = [
                    SELECT Verification_Status__c, Contact__r.Person_ID_unique__c, isTestCompleted__c, Expected_date_of_completion__c, Date_Achieved__c, Expiry_Date__c,Score__c,
                            Result_Type__c, Qualification__r.Callista_Code__c, Other_Qualification_Comments__c, Qualification__r.Sub_score_Type__c,
                            Writing__c, Listening__c, READING__c, Speaking__c, Test_of_Written_English__c,
                    (SELECT Application__r.Id FROM Application_Qualifications__r )
                    FROM Contact_Qualification__c
                    where id = :recordId ];

            personId = cq.Contact__r.Person_ID_unique__c;

            EnglishTestScoreRequest req = new EnglishTestScoreRequest();
            req.type = 'testScore';
            req.testType = cq.Qualification__r!=null?cq.Qualification__r.Callista_Code__c:'';
            req.verificationStatus = cq.Verification_Status__c!=null?cq.Verification_Status__c.toUpperCase():null;
            req.completed = cq.isTestCompleted__c;
            req.plannedDate = cq.Expected_date_of_completion__c!=null?convertDate(cq.Expected_date_of_completion__c):null;
            req.achievedDate = cq.Date_Achieved__c!=null?convertDate(cq.Date_Achieved__c):null;
            req.expiryDate = cq.Expiry_Date__c!=null?convertDate(cq.Expiry_Date__c):null;

            String resType = cq.Result_Type__c!=null?cq.Result_Type__c:'';
            req.resultType =  (String.isNotBlank(resType) && resType.toUpperCase()=='SATISFACTORY'|| String.isNotBlank(resType) && resType.toUpperCase()=='UNSATISFACTORY')?resType.toUpperCase():null;
            req.comments = cq.Other_Qualification_Comments__c!=null?cq.Other_Qualification_Comments__c:'';

            try{
                //when cq.Score__c is an Integer
                req.overallScore = Integer.valueOf(cq.Score__c);
            } catch(Exception ee) {
                //when cq.Score__c is unable to parse as an Integer as it is a String
                req.grade =  cq.Score__c;
            }

            // Callout requires existing application
            String appId;
            if(!cq.Application_Qualifications__r.isEmpty()){
                appId = cq.Application_Qualifications__r[0]?.Application__r?.Id;  
            }  
            if(appId == null){
                return;
            }    
                
            String subscoreTypes = cq?.Qualification__r?.Sub_score_Type__c;

            List<Application__c> appList  = [
                    SELECT Id, (SELECT  Admission_Application_Number__c, Course_Code__c FROM Application_Course_Preferences__r)
                    FROM Application__c
                    WHERE ID = :appId
            ];
            List<EnglishTestScoreRequest.applications> appsLR = new List<EnglishTestScoreRequest.applications>();

            for(Application__c app:appList)
            {
                EnglishTestScoreRequest.applications appR = new EnglishTestScoreRequest.applications();
                appR.type = 'application';
                List<EnglishTestScoreRequest.coursePreferences> acpList =
                        new List<EnglishTestScoreRequest.coursePreferences>();
                for(Application_Course_Preference__c acp:app.Application_Course_Preferences__r)
                {
                    if(Integer.valueOf(acp.Admission_Application_Number__c) == null){
                        // Callout requires existing Admission_Application_Number__c
                        return;
                    }
                    EnglishTestScoreRequest.coursePreferences acpR = new EnglishTestScoreRequest.coursePreferences();
                    acpR.type =  'coursePreference';
                    acpR.admissionApplNumber = Integer.valueOf(acp.Admission_Application_Number__c);
                    acpR.courseCode = acp.Course_Code__c;
                    acpList.add(acpR);
                }
                appR.coursePreferences = acpList;
                appsLR.add(appR);
            }
            req.applications = appsLR;
            List<String> splitStr = new List<String>();
            if(String.isNotBlank(subscoreTypes))
            {
                if(subscoreTypes.contains(';'))
                    splitStr = subscoreTypes.split(';');
                else
                        splitStr.add(subscoreTypes);
            }

            List<EnglishTestScoreRequest.subscores> subscoresRL = new List<EnglishTestScoreRequest.subscores>();
            for(String sp:splitStr)
            {
                EnglishTestScoreRequest.subscores ss = new EnglishTestScoreRequest.subscores();
                ss.type = 'testSubscore';
                switch on sp
                {
                    When 'Reading'
                    {
                        ss.score = cq.READING__c;
                        ss.scoreType = String.isNotBlank(sp)?sp.toUpperCase():'';
                    }
                    When 'Writing'
                    {
                        ss.score = cq.WRITING__C;
                        ss.scoreType = String.isNotBlank(sp)?sp.toUpperCase():'';
                    }
                    When 'Listening'
                    {
                        ss.score = cq.Listening__c;
                        ss.scoreType = String.isNotBlank(sp)?sp.toUpperCase():'';
                    }
                    When 'Speaking'
                    {
                        ss.score = cq.Speaking__c;
                        ss.scoreType = String.isNotBlank(sp)?sp.toUpperCase():'';
                    }
                    When 'Test of Written English'
                    {   // Replacing it with a shorter version to overcome callista character limit of 10
                        ss.score = cq.Test_of_Written_English__c;
                        ss.scoreType = 'TWE'; 
                    }
                }
                subscoresRL.add(ss);
            }
            req.subscores = subscoresRL;
            this.jsonRequest = req;
            Nebula.Logger.info('Class: EnglishTestScoreInterface ConQual Id: ' + recordId +' reqBody = ' + JSON.serializePretty(jsonRequest));
        } catch (Exception ex) {
            Nebula.Logger.exception('Class: EnglishTestScoreInterface Method: createRequestBody for ConQual Id: '+ recordId +', Message: ' + ex.getMessage(), ex);
        }
        finally {
            Nebula.Logger.saveLog();
        }
    }

    //Queuable execute method
    public void execute(QueueableContext ctx) {
        this.ctx = ctx;
        //SFTN-479- Adding personId check 
        if(personId!=null) {
                if(!Test.isRunningTest() ) {
                this.sendMessage();
            }
            handleResponse();
        }
    }
    
    //handle response from the framework
    private void handleResponse() {
        try {
            Map<String, Object> respBody = this.getResponseBody();
            // check http response
            if (this.httpResponseCode == 200) {
                //successful response
                Nebula.Logger.info('EnglishTestScoreInterface\'s handleResponse method, ConQual Id: ' + this.recordId + ', Response Code = ' + this.httpResponseCode + ' respBody = ' + JSON.serializePretty(respBody));
            } else {
                //unsuccessful response
                Nebula.Logger.error('EnglishTestScoreInterface\'s handleResponse method, ConQual Id: ' + this.recordId + ', Response Code = ' + this.httpResponseCode + ' respBody = ' + JSON.serializePretty(respBody));
            }
        } catch (Exception ex) {
            // log exception
            Nebula.Logger.exception('Class: EnglishTestScoreInterface Method: handleResponse, Message: ' + ex.getMessage(), ex);
        }
        finally {
            Nebula.Logger.saveLog();
        }
    }

    // Date formatter
    public static String convertDate(Date dt) {
        String retDt = '';

        if(dt != null)
        {
            DateTime dtTime = Datetime.newInstance(dt.year(), dt.month(), dt.day());
            retDt = dtTime.format('yyyy-MM-dd');
        }
        return retDt;
    }

}