force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enquiry_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enquiry Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent for Submission</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Data Validation Ready</fullName>
                </value>
                <value>
                    <fullName>Failed Data validation</fullName>
                </value>
                <value>
                    <fullName>Submission on Hold (Duplicate Contact)</fullName>
                </value>
                <value>
                    <fullName>Agent Declaration Accepted</fullName>
                </value>
                <value>
                    <fullName>Sent Draft Application to Applicant</fullName>
                </value>
                <value>
                    <fullName>Applicant Declaration Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>ACP</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to course code, filtering out Unit Set courses</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>notEqual</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>ACP Courses</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                    <label>WITHDRAWN</label>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Registered - EOI Only</fullName>
                </value>
                <value>
                    <fullName>Registered - Approved</fullName>
                </value>
                <value>
                    <fullName>Registered - Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Registered - Rejected</fullName>
                </value>
                <value>
                    <fullName>Registered - Invoice not processed</fullName>
                </value>
                <value>
                    <fullName>Registered - Invoiced</fullName>
                </value>
                <value>
                    <fullName>Registered - CCFund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Description__c</fullName>
        <externalId>true</externalId>
        <label>Course Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Course is Active ? Active/Inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>EOI</fullName>
                </value>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                    <label>Available</label>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ImportApplicantDataViaCSVController_Test.cls
/*******************************************************************************
* @author       Nadula Karunaratna
* @date         05/09/2017
* @description  Test class for ImportApplicantDataViaCSVController_Test
*******************************************************************************/
@isTest(isParallel=true)
private class ImportApplicantDataViaCSVController_Test {

    //static testMethod void TestGetExistingContact() {

    //    //create test contact
    //    Contact newContact = PDTestHelper.createContact2('Nadula','TEST1','nadula.test1@gmail.com');

    //    //read test contact
    //    Contact testContact = ImportApplicantDataViaCSVController.getExistingContact('Nadula','TEST1','nadula.test1@gmail.com');

    //    System.assertEquals('nadula.test1@gmail.com',testContact.Email);

    //}

    static testMethod void TestSaveBulkApplicantData() {

        Course__c course = PDTestHelper.createCourse();
        Course_Offering__c co = PDTestHelper.createCourseOffering();
        co.Course__c = course.Id;
        update co; 

        String courseOfferingID = co.Id;
        String courseCode = course.Name;
        String courseName = course.Course_Description__c;

        //Main Applicant
        Contact newContact = PDTestHelper.createContact2('Nadula','TEST0','nadula.test0@gmail.com');

        //Bulk Applicants
        Contact newContact1 = PDTestHelper.createContact2('Nadula','TEST1','nadula.test1@gmail.com');
        Contact newContact2 = PDTestHelper.createContact2('Nadula','TEST2','nadula.test2@gmail.com');
        Contact newContact3 = PDTestHelper.createContact2('Nadula','TEST3','nadula.test3@gmail.com');

        //Enquiry
        Case enq = new Case();      
        enq.RecordType = [select Id from RecordType where Name = 'Professional Development' and SobjectType = 'Case']; //'0120l00000007Uk';
        enq.Contact = [select Id from Contact where Email = 'nadula.test0@gmail.com' and FirstName = 'Nadula' and LastName = 'TEST0']; //newContact.Id;
        enq.Status = 'Open';
        insert enq; //update enq;
        

        //Application       
        Application__c application = new Application__c();
        application.Status__c = 'Registered';
        application.Enquiry_Number__c = enq.Id;
        application.Applicant__c = newContact.Id;
        insert application;  
        String applicationID = application.Id;

        List <Contact> lstContacts;
        Contact conObj1;
        Contact conObj2;
        Contact conObj3;
        Contact conObj4;
        
        lstContacts = new List <Contact> ();
        
        conObj1 = new Contact();
        conObj1.put('FirstName', 'Nadula');
        conObj1.put('LastName', 'TEST1');
        conObj1.put('Email', 'nadula.test1@gmail.com');
        lstContacts.add(conObj1);
        
        conObj2 = new Contact();
        conObj2.put('FirstName', 'Nadula');
        conObj2.put('LastName', 'TEST2');
        conObj2.put('Email', 'nadula.test2@gmail.com');
        lstContacts.add(conObj2);
        
        conObj3 = new Contact();
        conObj3.put('FirstName', 'Nadula');
        conObj3.put('LastName', 'TEST3');
        conObj3.put('Email', 'nadula.test3@gmail.com');
        lstContacts.add(conObj3);

        conObj4 = new Contact();
        conObj4.put('FirstName', 'John');
        conObj4.put('LastName', 'Citizon');
        conObj4.put('Email', 'x100.john.c@gmail.com');
        lstContacts.add(conObj4);       

        Integer recordCount = 0;
        Boolean readSuccess = FALSE;
        Boolean displayUploadBlock = FALSE;        

        //ImportApplicantDataViaCSVController.saveBulkApplicantData(lstContacts,courseOfferingID,applicationID,courseCode,courseName);

        ImportApplicantDataViaCSVController test = new ImportApplicantDataViaCSVController();
        test.saveBulkApplicantData(lstContacts,courseOfferingID,applicationID,courseCode,courseName);
        
        List<Application_Course_Preference__c> acpList = [select Id from Application_Course_Preference__c where Application__c = :applicationID and Course_Offering__c = :courseOfferingID];
        System.assertEquals(4,acpList.size()); 

        //ImportApplicantDataViaCSVController.saveBulkApplicantData(lstContacts,'courseOfferingID',applicationID,courseCode,courseName);

        //ImportApplicantDataViaCSVController test = new ImportApplicantDataViaCSVController();
        test.saveBulkApplicantData(lstContacts,'courseOfferingID',applicationID,courseCode,courseName);

        List<Application_Course_Preference__c> acpList2 = [select Id from Application_Course_Preference__c where Application__c = :applicationID and Course_Offering__c = :'courseOfferingID'];
        System.assertEquals(0,acpList2.size());         
    }

    static testMethod void TestSaveData() {
        ImportApplicantDataViaCSVController test = new ImportApplicantDataViaCSVController();
        test.saveData(); 
    }    

    static testMethod void TestReadFromFile() {
        //ImportApplicantDataViaCSVController.readSuccess
        ImportApplicantDataViaCSVController test = new ImportApplicantDataViaCSVController();
        //test.csvFileBody = EncodingUtil.base64Decode('Salutation,FirstName,LastName,Email,MailingStreet,MailingCity,MailingState,MailingPostalCode,MailingCountry' + CSVParser.CRLF + 'Mr.,John,Citizon,john.c@mailinator.com,34 Barry Road,Melbourne,VIC,3005,Australia' + CSVParser.CRLF + 'Ms.,Julia 23,Gillard,127.j.gillard@mailinator.com,4225 Toorak Road,Preston,VIC,3045,Australia');
        
        //test.readFromFile();
        //List<String> contactDataLines = test.contactDataLines;
        test.contactDataAsString = '';
        test.csvFileBody = EncodingUtil.base64Decode('test');
        test.readFromFile();
    }

    static testMethod void TestEnableReUploadCSV() {
        ImportApplicantDataViaCSVController test = new ImportApplicantDataViaCSVController();
        test.enableReUploadCSV(); 
    }

    static testMethod void TestReadCSVFile() {
        ImportApplicantDataViaCSVController test = new ImportApplicantDataViaCSVController();
        test.contactDataAsString = 'Salutation,FirstName,LastName,Email,MailingStreet,MailingCity,MailingState,MailingPostalCode,MailingCountry' + CSVParser.CRLF + 'Mr.,John,Citizon,john.c@mailinator.com,34 Barry Road,Melbourne,VIC,3005,Australia' + CSVParser.CRLF + 'Ms.,Julia 23,Gillard,127.j.gillard@mailinator.com,4225 Toorak Road,Preston,VIC,3045,Australia';
        test.howManyApplicants = '3';
        test.readCSVFile();

        test.howManyApplicants = '2';
        test.readCSVFile();
        Boolean readSuccess = test.readSuccess;
        Boolean showDataPanel = test.showDataPanel;
        List <Contact> lstContactsData = test.lstContactsData;
        List<String> lstFieldNamesData = test.lstFieldNamesData;
    }

    //static testMethod getBulkContacts(){

    //}

}