force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Callista_Applicant_Id__c</fullName>
        <externalId>true</externalId>
        <label>Callista Applicant Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Study__c</fullName>
        <description>Type of Study indicating the application&apos;s study type in the context of Exchange/Study Abroad.</description>
        <label>Type of Study</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Study Abroad</fullName>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>Coursework</fullName>
                </value>
                <value>
                    <fullName>Graduate Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callista_Applicant_Id__c</fullName>
        <formula>Application__r.Callista_Applicant_Id__c</formula>
        <label>Callista Applicant Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>ACP</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to course code, filtering out Unit Set courses</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>notEqual</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>ACP Courses</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GradRes_Callista_Id__c</fullName>
        <description>Graduate Research Callista Id</description>
        <label>GradRes Callista Id</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Qualification_Provided__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <label>Contact Qualification</label>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipName>Application_Qualifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>Sequence number to send to callista for a particular contact qualification type</description>
        <label>Sequence Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application Qualification Provided</label>
    <nameField>
        <displayFormat>AQP-{000000}</displayFormat>
        <label>Application Qualification Provided ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Qualifications Provided</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Document__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to application record if relevant</description>
        <inlineHelpText>Link to application record if relevant</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Qualification</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are no Qualifications assigned to this contact</errorMessage>
            <filterItems>
                <field>$Source.Contact__c</field>
                <operation>equals</operation>
                <valueField>Contact_Qualification__c.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipLabel>Qualification Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Document_Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate which checklist item the document was uploaded against.</description>
        <label>Document Checklist</label>
        <referenceTo>Document_Checklist__c</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Document</label>
    <nameField>
        <displayFormat>CNDC-{000000}</displayFormat>
        <label>Contact Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <recordTypes>
        <fullName>English_Test</fullName>
        <active>true</active>
        <label>English Test</label>
    </recordTypes>
    <recordTypes>
        <fullName>Other_Qualification</fullName>
        <active>true</active>
        <label>Other Qualification</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist__c.object
<CustomObject>
    <description>Capture documents relevant to different processes that requires documents for verification</description>
    <fields>
        <fullName>Application_Course_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Course Preference</label>
        <referenceTo>Application_Course_Preference__c</referenceTo>
        <relationshipLabel>Document Checklists</relationshipLabel>
        <relationshipName>Document_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to Application</description>
        <inlineHelpText>Link to Application</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Document Checklist</relationshipLabel>
        <relationshipName>Document_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Link to Contact Qualification</description>
        <inlineHelpText>Link to Contact Qualification</inlineHelpText>
        <label>Contact Qualification</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Contact__c</field>
                <operation>equals</operation>
                <valueField>Contact_Qualification__c.Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipLabel>Document Checklist</relationshipLabel>
        <relationshipName>Document_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup directly to Contact to enable filtering of Qualification and Work Experience records.</description>
        <inlineHelpText>Lookup directly to Contact to enable filtering of Qualification and Work Experience records.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Document Checklist</relationshipLabel>
        <relationshipName>Document_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_DeveloperName__c</fullName>
        <description>Contains a copy the rule developer name that resulted in the creation of the checklist item.</description>
        <inlineHelpText>Contains a copy the rule developer name that resulted in the creation of the checklist item.</inlineHelpText>
        <label>Rule Developer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Document Checklist</label>
    <nameField>
        <displayFormat>DC{YYYY}-{000000}</displayFormat>
        <label>Checklist Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklists</pluralLabel>
    <recordTypes>
        <fullName>Application_Assessment</fullName>
        <active>true</active>
        <description>Type of checklist relevant for assessing applications</description>
        <label>Application Assessment</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist_Comment__c.object
<CustomObject>
    <description>Comment holder for document checklist</description>
    <fields>
        <fullName>Document_Checklist__c</fullName>
        <description>Linked checklist where the comment is for.</description>
        <label>Document Checklist</label>
        <referenceTo>Document_Checklist__c</referenceTo>
        <relationshipLabel>Document Checklist Comments</relationshipLabel>
        <relationshipName>Document_Checklist_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Document Checklist Comment</label>
    <nameField>
        <displayFormat>DCC{YYYY}-{000000}</displayFormat>
        <label>Document Checklist Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklist Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/GRDocumentRequestImpl_Test.cls
/**
 * @description Test class to cover GRDocumentRequestImpl
 * @author Vishal Gupta
 * @since 29/10/2024
 */
@IsTest(IsParallel=true)
public class GRDocumentRequestImpl_Test {
    /**
     * @description Sets up test data including a Contact, Application, and Document Checklist for testing.
     */
    @TestSetup
    private static void setupData() {
        User applicant = StudFirst_TestHelper.createCommunityUser();
        Contact c = [SELECT id FROM Contact WHERE id =: applicant.contactId];

        //create application
        Application__c app = StudFirst_TestHelper.createApplication(c.Id);
        app.Type_Of_Study__c = 'Graduate Research';
        app.Callista_Applicant_Id__c = 'testApplicantId';
        insert app;

        // Create Course
        Course__c course = StudFirst_TestHelper.createCourse();
        insert course;

        // Creare Course Offering
        Course_Offering__c courseOffering = StudFirst_TestHelper.createCourseOffering(course);
        insert courseOffering;

        //create Application_Course_Preference__c
        Application_Course_Preference__c coursePreference = StudFirst_TestHelper.createCoursePreferences(app, c, courseOffering, course);
        coursePreference.GradRes_Callista_Id__c = 'testhdrnumber';
        insert coursePreference;

        //create Contact_Qualification__c
        Map<Id, RecordType> qualifficationType = new Map<Id, RecordType>([SELECT Id FROM RecordType WHERE sObjectType = 'Contact_Qualification__c']);
        List<Contact_Qualification__c> lstCQ = new List<Contact_Qualification__c>();
        for(Id recordTypeId : qualifficationType.keyset()) {
            Contact_Qualification__c cq = new Contact_Qualification__c();
            cq.Contact__c = applicant.ContactId;
            cq.RecordTypeId = recordTypeId;
            lstCQ.add(cq);
        }
                
        insert lstCQ;

        // create the apq
        List<Application_Qualification_Provided__c> lstAqp = new List<Application_Qualification_Provided__c>();
        for(Contact_Qualification__c contQual : lstCQ) {
            Application_Qualification_Provided__c aqp = new Application_Qualification_Provided__c();
            aqp.Contact_Qualification__c = contQual.Id;
            aqp.Application__c = app.Id;
            aqp.Sequence_Number__c = 1;
            lstAqp.add(aqp);
        }
        
        insert lstAqp;

        // Create application checklist for visa
        Document_Checklist__c testChecklist = new Document_Checklist__c(
            Application__c = app.Id,
            RecordTypeId = Schema.SObjectType.Document_Checklist__c.getRecordTypeInfosByDeveloperName().get('Application_Assessment').getRecordTypeId(),
            Rule_DeveloperName__c = 'V2_Complete_Tertiary_Education_Check',
            Status__c = 'Requested',
            Unique_ID__c = String.valueOf(Date.today()),
            Document_Request_Type__c = 'MISC-DOC',
            Type__c = 'Qualification'
        );
        insert testChecklist;

        // Create a new Contact document for testing
        insert new Contact_Document__c(
            Contact__c = c.Id,
            Document_Type__c = 'OTHERDCTYP',
            Filename__c = 'Test_Issuer_Transcript.pdf',
            Application__c = app.Id,
            Document_Checklist__c = testChecklist.Id
        );
    }

    /**
     * @description Tests the handlePost method when provided with a valid request payload.
     */
    @IsTest
    private static void testHandlePost() {
        // Given : post request payload is valid and there are existing document checklist
        GRDocumentRequestPayload.PostRequest postRequestPayload = new GRDocumentRequestPayload.PostRequest();
        postRequestPayload.applicantId = 'testApplicantId';
        postRequestPayload.hdrApplicationNumber = 'testhdrnumber';
        postRequestPayload.requestType = 'MISC-DOC';

        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(postRequestPayload));
        RestContext.request = request;

        RestResponse response = new RestResponse();
        RestContext.response = response;
        // When : calling process method
        Test.startTest();
        RESTlib_ClientImplHandler clientImplHandler = new GRDocumentRequestImpl().getHandlePost();
        clientImplHandler.setPayloadType(GRDocumentRequestPayload.PostRequest.class, GRDocumentRequestPayload.PostResponse.class);
        clientImplHandler.execute();
        Test.stopTest();

        //then, it should create a checklist comment and change the checklist status to Insufficient
        Document_Checklist__c checklist = [SELECT Status__c FROM Document_Checklist__c WHERE Document_Request_Type__c = 'MISC-DOC' limit 1];
        Assert.areEqual('Insufficient', checklist.Status__c, 'Expected the checklist status changed as Insufficient');
    }
    /**
     * @description Tests the handlePost method when provided with a request of cancellation of a document request.
     */
    @IsTest
    private static void testHandlePostCancelComments() {
        // Given : post request payload is valid and there are existing document checklist
        GRDocumentRequestPayload.PostRequest postRequestPayload = new GRDocumentRequestPayload.PostRequest();
        postRequestPayload.applicantId = 'testApplicantId';
        postRequestPayload.hdrApplicationNumber = 'testhdrnumber';
        postRequestPayload.requestType = 'MISC-DOC';
        postRequestPayload.cancelledDate = '2024-04-01 10:47:25.000';
        postRequestPayload.requestReason = 'Test reason';

        Document_Checklist__c checklist = [SELECT Status__c FROM Document_Checklist__c WHERE Document_Request_Type__c = 'MISC-DOC' limit 1];
        Document_Checklist_Comment__c comments = new Document_Checklist_Comment__c();
        comments.Content__c = 'Test reason';
        comments.Document_Checklist__c = checklist.Id;
        insert comments;

        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(postRequestPayload));
        RestContext.request = request;

        RestResponse response = new RestResponse();
        RestContext.response = response;
        // When : calling process method with the cancellation request
        Test.startTest();
        RESTlib_ClientImplHandler clientImplHandler = new GRDocumentRequestImpl().getHandlePost();
        clientImplHandler.setPayloadType(GRDocumentRequestPayload.PostRequest.class, GRDocumentRequestPayload.PostResponse.class);
        clientImplHandler.execute();
        Test.stopTest();

        //then, it should revert a checklist comment and change the checklist status back to submitted
        Document_Checklist__c newChecklist = [SELECT Status__c FROM Document_Checklist__c WHERE Document_Request_Type__c = 'MISC-DOC' limit 1];
        Assert.areEqual('Submitted', newChecklist.Status__c, 'Expected the checklist status changed as Submitted');
    }
    /**
     * @description Tests the handlePost method when provided with a valid request of english document request.
     */
    @IsTest
    private static void testHandlePostEnglishChecklistRequired() {
        // Given : post request payload is valid and there are existing document checklist
        GRDocumentRequestPayload.PostRequest postRequestPayload = new GRDocumentRequestPayload.PostRequest();
        postRequestPayload.applicantId = 'testApplicantId';
        postRequestPayload.hdrApplicationNumber = 'testhdrnumber';
        postRequestPayload.requestType = 'ENG-TEST';
        postRequestPayload.description = 'test';

        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(postRequestPayload));
        RestContext.request = request;

        RestResponse response = new RestResponse();
        RestContext.response = response;
        // When : calling process method with requesting english document
        Test.startTest();
        RESTlib_ClientImplHandler clientImplHandler = new GRDocumentRequestImpl().getHandlePost();
        clientImplHandler.setPayloadType(GRDocumentRequestPayload.PostRequest.class, GRDocumentRequestPayload.PostResponse.class);
        clientImplHandler.execute();
        Test.stopTest();

        //then, it create the checklist for english document
        Contact_Qualification__c contactQualEng = [SELECT English_doc_required_during_assessment__c FROM Contact_Qualification__c WHERE RecordType.DeveloperName = 'English_Test' limit 1];
        Assert.areEqual(true, contactQualEng.English_doc_required_during_assessment__c, 'Expected the english test qualififcation document flag to true');
    }

    /**
     * @description Tests the handlePost method when provided with a valid request of misc document request.
     */
    @IsTest
    private static void testHandlePostMiscAdditionalDocument() {
        // Given : post request payload is valid and there are existing document checklist
        GRDocumentRequestPayload.PostRequest postRequestPayload = new GRDocumentRequestPayload.PostRequest();
        postRequestPayload.applicantId = 'testApplicantId';
        postRequestPayload.hdrApplicationNumber = 'testhdrnumber';
        postRequestPayload.requestType = 'MISC-DOC';
        postRequestPayload.claimSequenceNumber = 2;

        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(postRequestPayload));
        RestContext.request = request;

        RestResponse response = new RestResponse();
        RestContext.response = response;
        // When : calling process method requesting additional misc item
        Test.startTest();
        RESTlib_ClientImplHandler clientImplHandler = new GRDocumentRequestImpl().getHandlePost();
        clientImplHandler.setPayloadType(GRDocumentRequestPayload.PostRequest.class, GRDocumentRequestPayload.PostResponse.class);
        clientImplHandler.execute();
        Test.stopTest();

        //then, it create the checklist for misc document
        List<Contact_Qualification__c> contactQualMisc = [SELECT Id FROM Contact_Qualification__c WHERE RecordType.DeveloperName = 'Other_Qualification' ];
        Assert.areEqual(2, contactQualMisc.size(), 'Expected another misc document is created with checklist');
    }

    /**
     * @description Tests the handlePost method when provided withhout a valid request (blank application id).
     */
    @IsTest
    private static void testHandlePostBlankApplicationId() {
        // Given : post request payload is invalid
        GRDocumentRequestPayload.PostRequest postRequestPayload = new GRDocumentRequestPayload.PostRequest();

        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(postRequestPayload));
        RestContext.request = request;

        RestResponse response = new RestResponse();
        RestContext.response = response;
        //calling the unused method for test coverage
        new GRDocumentRequestImpl().getHandleGet();
        new GRDocumentRequestImpl().getHandlePut();
        new GRDocumentRequestImpl().getHandlePatch();

        // When : calling process method
        Test.startTest();
        RESTlib_ClientImplHandler clientImplHandler = new GRDocumentRequestImpl().getHandlePost();
        clientImplHandler.setPayloadType(GRDocumentRequestPayload.PostRequest.class, GRDocumentRequestPayload.PostResponse.class);
        clientImplHandler.execute();
        Test.stopTest();
        String responseBodyString = response.responseBody.toString();
        //then, it should throw the error
        GRDocumentRequestPayload.PostResponse customResponse =
                (GRDocumentRequestPayload.PostResponse) JSON.deserialize(responseBodyString, GRDocumentRequestPayload.PostResponse.class);
            Assert.isFalse(customResponse.success, 'Expected success to be false');
            Assert.areEqual('The applicant Id cannot be blank', customResponse.description, 'Expected error to match');
        
    }

    /**
     * @description Tests the handlePost method when provided withhout a valid request (blank hdr application number)
     */
    @IsTest
    private static void testHandlePostBlankHDRAppNum() {
        // Given : post request payload is invalid
        GRDocumentRequestPayload.PostRequest postRequestPayload = new GRDocumentRequestPayload.PostRequest();
        postRequestPayload.applicantId = 'test';
        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(postRequestPayload));
        RestContext.request = request;

        RestResponse response = new RestResponse();
        RestContext.response = response;
        // When : calling process method
        Test.startTest();
        RESTlib_ClientImplHandler clientImplHandler = new GRDocumentRequestImpl().getHandlePost();
        clientImplHandler.setPayloadType(GRDocumentRequestPayload.PostRequest.class, GRDocumentRequestPayload.PostResponse.class);
        clientImplHandler.execute();
        Test.stopTest();
        //then, it should throw the error
        String responseBodyString = response.responseBody.toString();
        GRDocumentRequestPayload.PostResponse customResponse =
                (GRDocumentRequestPayload.PostResponse) JSON.deserialize(responseBodyString, GRDocumentRequestPayload.PostResponse.class);
            Assert.isFalse(customResponse.success, 'Expected success to be false');
            Assert.areEqual('The HDR Application Number cannot be blank', customResponse.description, 'Expected code to match');
        
    }
    /**
     * @description Tests the handlePost method when provided withhout a valid request (blank request type).
     */
    @IsTest
    private static void testHandlePostBlankRequestType() {
        // Given : post request payload is invalid
        GRDocumentRequestPayload.PostRequest postRequestPayload = new GRDocumentRequestPayload.PostRequest();
        postRequestPayload.applicantId = 'test';
        postRequestPayload.hdrApplicationNumber = 'testhdrnumber';
        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(postRequestPayload));
        RestContext.request = request;

        RestResponse response = new RestResponse();
        RestContext.response = response;
        // When : calling process method
        Test.startTest();
        RESTlib_ClientImplHandler clientImplHandler = new GRDocumentRequestImpl().getHandlePost();
        clientImplHandler.setPayloadType(GRDocumentRequestPayload.PostRequest.class, GRDocumentRequestPayload.PostResponse.class);
        clientImplHandler.execute();
        Test.stopTest();
        String responseBodyString = response.responseBody.toString();
        //then, it should throw the error
        GRDocumentRequestPayload.PostResponse customResponse =
                (GRDocumentRequestPayload.PostResponse) JSON.deserialize(responseBodyString, GRDocumentRequestPayload.PostResponse.class);
            Assert.isFalse(customResponse.success, 'Expected success to be false');
            Assert.areEqual('The Document request type cannot be blank', customResponse.description, 'Expected code to match');
        
    }
    /**
     * @description Tests the handlePost method when provided withhout a valid request (no application found).
     */
    @IsTest
    private static void testHandlePostApplicationNotFoundError() {
        // Given : post request payload is invalid
        GRDocumentRequestPayload.PostRequest postRequestPayload = new GRDocumentRequestPayload.PostRequest();
        postRequestPayload.applicantId = 'test';
        postRequestPayload.hdrApplicationNumber = 'testhdrnumber';
        postRequestPayload.requestType = 'TERT-QUAL';
        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(JSON.serialize(postRequestPayload));
        RestContext.request = request;

        RestResponse response = new RestResponse();
        RestContext.response = response;
        // When : calling process method
        Test.startTest();
        RESTlib_ClientImplHandler clientImplHandler = new GRDocumentRequestImpl().getHandlePost();
        clientImplHandler.setPayloadType(GRDocumentRequestPayload.PostRequest.class, GRDocumentRequestPayload.PostResponse.class);
        clientImplHandler.execute();
        Test.stopTest();
        String responseBodyString = response.responseBody.toString();
        //then, it should throw the error
        GRDocumentRequestPayload.PostResponse customResponse =
                (GRDocumentRequestPayload.PostResponse) JSON.deserialize(responseBodyString, GRDocumentRequestPayload.PostResponse.class);
            Assert.isFalse(customResponse.success, 'Expected success to be false');
            Assert.areEqual('Application not found', customResponse.description, 'Expected error to match');
    }
}