force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Status__c</fullName>
        <description>Track the assessment process once an application is submitted by the applicant</description>
        <inlineHelpText>Track the assessment process once an application is submitted by the applicant</inlineHelpText>
        <label>Assessment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assessment_Flow_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Breached_visa_condition__c</fullName>
        <description>Indicates if the applicant has breached visa conditions in the past.</description>
        <inlineHelpText>Have you breached any visa conditions in any country?</inlineHelpText>
        <label>Breached visa condition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Callista_Application_Id__c</fullName>
        <externalId>true</externalId>
        <label>Callista Application Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Convicted_of_crime_offence__c</fullName>
        <description>Indicates if the applicant has been convicted of any crime or offence in any country.</description>
        <inlineHelpText>Have you been convicted of any crime or offence in any country?</inlineHelpText>
        <label>Convicted of crime/offence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Application Processing Fee Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee_Waiver_Redeemed__c</fullName>
        <description>Indicates if the Waiver code has been redeemed for Application fees</description>
        <label>Processing Fee Waiver Redeemed</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HasDisabilities__c</fullName>
        <label>HasDisabilities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Medical_health_prevent_visa__c</fullName>
        <description>Indicates if the applicant has any medical/health issues that may prevent them from obtaining a visa.</description>
        <inlineHelpText>Do you have any medical or health issues that may prevent you from obtaining your visa?</inlineHelpText>
        <label>Medical/health prevent visa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Protection_visa_in_any_country__c</fullName>
        <description>Indicates if the applicant has been issued a protection visa in any other country.</description>
        <inlineHelpText>Have you been issued a protection visa in any country to date?</inlineHelpText>
        <label>Protection visa in any country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Refused_entry_visa_to_any_country__c</fullName>
        <description>Indicates if the applicant has been refused an entry visa to any country.</description>
        <inlineHelpText>Have you been refused an entry visa to any country?</inlineHelpText>
        <label>Refused entry visa to any country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Progress__c</fullName>
        <description>Defines the progress of submission that the applicant is going through.</description>
        <label>Submission Progress</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Study__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Declaration</fullName>
                    <default>true</default>
                    <label>Declaration</label>
                </value>
                <value>
                    <fullName>Personal Details</fullName>
                </value>
                <value>
                    <fullName>Study Preferences</fullName>
                </value>
                <value>
                    <fullName>Credentials</fullName>
                </value>
                <value>
                    <fullName>Scholarship</fullName>
                </value>
                <value>
                    <fullName>Application Details</fullName>
                </value>
                <value>
                    <fullName>Research Program</fullName>
                </value>
                <value>
                    <fullName>English Proficiency</fullName>
                </value>
                <value>
                    <fullName>Qualifications</fullName>
                </value>
                <value>
                    <fullName>Awards, Prizes &amp; Scholarship</fullName>
                </value>
                <value>
                    <fullName>Employment &amp; Research Experience</fullName>
                </value>
                <value>
                    <fullName>Referees</fullName>
                </value>
                <value>
                    <fullName>Publications</fullName>
                </value>
                <value>
                    <fullName>Creative Works</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>Theatre Performance</fullName>
                </value>
                <value>
                    <fullName>Exhibitions</fullName>
                </value>
                <value>
                    <fullName>Additional Supporting Information</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Application Fee</fullName>
                </value>
                <value>
                    <fullName>Submit</fullName>
                </value>
                <value>
                    <fullName>Validate &amp; Submit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Admissions_Assessment_Status__c</fullName>
        <label>Admissions Lifecycle Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Course Entry Check</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Applicant Input Required</fullName>
                </value>
                <value>
                    <fullName>Internal Input Required</fullName>
                </value>
                <value>
                    <fullName>Additional Entry Requirements Check</fullName>
                </value>
                <value>
                    <fullName>Final Decision</fullName>
                </value>
                <value>
                    <fullName>Discontinued</fullName>
                </value>
                <value>
                    <fullName>Outcome Finalisation</fullName>
                    <isActive>false</isActive>
                    <label>Outcome Finalisation</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Status__c</fullName>
        <label>Assessment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Pre Assessment</fullName>
                </value>
                <value>
                    <fullName>Qualification Assessment</fullName>
                </value>
                <value>
                    <fullName>Assessment Outcome</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Callista_Application_Id__c</fullName>
        <formula>Application__r.Callista_Application_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Callista Application Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Credit__c</fullName>
        <description>Assessment status for Credit Assessments</description>
        <label>Task: Credit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assessment_Flow_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workflow_Status__c</fullName>
        <label>Workflow Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Assessment_Flow_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Required</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting for docs</fullName>
        <label>Applicant Input Required</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Required</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinued</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Input Required</fullName>
    </customValue>
    <description>Assessment status values to track progress of assessment tasks</description>
    <masterLabel>Assessment Flow Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ACPAutoSetAssessmentTaskFields_FT.cls
/**
 * @description       : Test Class for ACP_Auto_Set_Assessment_Task_Fields
 * @author            : sravani.naramsetti@monash.edu
 * @group             : 
 * @last modified on  : 31-05-2024
 * @last modified by  : sravani.naramsetti@monash.edu
**/
@isTest(isParallel=true)
public class ACPAutoSetAssessmentTaskFields_FT {
    
    /**
    * @description Update Task_Credit__c on ACP as Required when creditIntention is true
    * @author sravani.naramsetti@monash.edu | 31-05-2024 
    **/
    @isTest
    public static void updateACPTaskCredit_Test(){
        // GIVEN : When there is an ACP with Task_Credit__c not equals Required
        Contact testApplicant = new Contact(LastName = 'TestApplicant', MailingCountry = 'Malaysia');
        insert testApplicant;
        
        Application__c oApplication = new Application__c();
        oApplication.Callista_Application_Id__c = 'CAID-1239090';
        oApplication.Fee_Payment__c = false;
        oApplication.Fee_Waiver_Redeemed__c = 'Test';    
        oApplication.Refused_entry_visa_to_any_country__c = 'Yes';
        oApplication.Breached_visa_condition__c = 'Yes';
        oApplication.Medical_health_prevent_visa__c = 'Yes';
        oApplication.Protection_visa_in_any_country__c = 'Yes';
        oApplication.Convicted_of_crime_offence__c = 'Yes';
        oApplication.HasDisabilities__c = 'Yes';
        oApplication.Submission_Progress__c = 'Submit';
        oApplication.Assessment_Status__c = 'Required';
        oApplication.Applicant__c = testApplicant.Id;
        insert oApplication;
        
        Application_Course_Preference__c acp1 = new Application_Course_Preference__c();
        acp1.Admissions_Assessment_Status__c = 'Not Started';
        acp1.Application__c = oApplication.Id;
        acp1.Workflow_Status__c = 'In Progress';
        insert acp1;
        
        //WHEN :  creditIntention is true
        Map<String, Object> inputs = new Map<String, Object> {
          'varAppId' => oApplication.id,
          'varCreditIntention' => true
        };
        Flow.Interview flw = new Flow.Interview.ACP_Auto_Set_Assessment_Task_Fields(inputs);
        Test.startTest();
        flw.start();
        Test.stopTest();
        
        //THEN : Task_Credit__c on ACP will be 'Required'
        Application_Course_Preference__c acpRetrieved=[SELECT Id, Task_Credit__c FROM Application_Course_Preference__c WHERE Id=:acp1.Id];
        Assert.areEqual ('Required', acpRetrieved.Task_Credit__c);
    }
}