force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent for Submission</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Data Validation Ready</fullName>
                </value>
                <value>
                    <fullName>Failed Data validation</fullName>
                </value>
                <value>
                    <fullName>Submission on Hold (Duplicate Contact)</fullName>
                </value>
                <value>
                    <fullName>Agent Declaration Accepted</fullName>
                </value>
                <value>
                    <fullName>Sent Draft Application to Applicant</fullName>
                </value>
                <value>
                    <fullName>Applicant Declaration Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Document__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to application record if relevant</description>
        <inlineHelpText>Link to application record if relevant</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Assessment_Status__c</fullName>
        <description>Select -- None -- if document is good. Select Not Required if document is not required for assessment. Select Not Assessable for requesting new copy of the document.</description>
        <inlineHelpText>Select &apos;-- None --&apos; if document is good.
Select &apos;Not Required&apos; if document is not required for assessment.
Select &apos;Not Assessable&apos; for requesting new copy of the document.</inlineHelpText>
        <label>Document Assessment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Required</fullName>
                </value>
                <value>
                    <fullName>Not Assessable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate which checklist item the document was uploaded against.</description>
        <label>Document Checklist</label>
        <referenceTo>Document_Checklist__c</referenceTo>
        <relationshipLabel>Contact Documents</relationshipLabel>
        <relationshipName>Contact_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <label>Filename</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_Only__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Field to flag if the document should only be visible internally</description>
        <label>Internal Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Certified name change documents uploaded with the on-line graduation application.</fullName>
                </value>
                <value>
                    <fullName>Certified previous qualification documents uploaded with the on-line graduation application.</fullName>
                </value>
                <value>
                    <fullName>Course offer acceptance document</fullName>
                </value>
                <value>
                    <fullName>Credit application</fullName>
                </value>
                <value>
                    <fullName>Curriculum vitae</fullName>
                </value>
                <value>
                    <fullName>Diploma or degree certificate</fullName>
                </value>
                <value>
                    <fullName>Employment reference</fullName>
                </value>
                <value>
                    <fullName>HDR application summary</fullName>
                </value>
                <value>
                    <fullName>Higher Degree Research candidature offer or confirmation letter.</fullName>
                </value>
                <value>
                    <fullName>Image of artwork for Art and Design folio</fullName>
                </value>
                <value>
                    <fullName>Invitation Letter for Higher Dreams Application</fullName>
                </value>
                <value>
                    <fullName>Learning Portfolio</fullName>
                </value>
                <value>
                    <fullName>Open Universities exams special local invigilator verification</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other document type not listed</fullName>
                </value>
                <value>
                    <fullName>Prior Application details for HDR</fullName>
                </value>
                <value>
                    <fullName>Proof of change of name</fullName>
                </value>
                <value>
                    <fullName>Proof of Citizenship/Residency or Identity</fullName>
                </value>
                <value>
                    <fullName>Proof of employment</fullName>
                </value>
                <value>
                    <fullName>Proof of English language medium of instruction</fullName>
                </value>
                <value>
                    <fullName>Proof of professional registration</fullName>
                </value>
                <value>
                    <fullName>Research proposal</fullName>
                </value>
                <value>
                    <fullName>Results forecast from secondary school</fullName>
                </value>
                <value>
                    <fullName>Results from secondary school</fullName>
                </value>
                <value>
                    <fullName>Results from tertiary studies</fullName>
                </value>
                <value>
                    <fullName>Results of aptitude test</fullName>
                </value>
                <value>
                    <fullName>Results of English language test</fullName>
                </value>
                <value>
                    <fullName>Statement of Purpose</fullName>
                </value>
                <value>
                    <fullName>Unit outline from tertiary studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Document</label>
    <nameField>
        <displayFormat>CNDC-{000000}</displayFormat>
        <label>Contact Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist__c.object
<CustomObject>
    <description>Capture documents relevant to different processes that requires documents for verification</description>
    <fields>
        <fullName>Allowed_Document_Type__c</fullName>
        <description>Document Type that can bee offered to applicants for this checklist item</description>
        <inlineHelpText>Select allowed Document Types that can bee offered to applicants for this checklist item</inlineHelpText>
        <label>Allowed Document Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to Application</description>
        <inlineHelpText>Link to Application</inlineHelpText>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Document Checklist</relationshipLabel>
        <relationshipName>Document_Checklist</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Checklist_Requirement__c</fullName>
        <description>Used to describe what the checklist item is for</description>
        <label>Checklist Requirement</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <description>Capture document type to map documents with Callista</description>
        <label>Document Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Meta data for checklist life-cycle</description>
        <inlineHelpText>Meta data for checklist life-cycle</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Insufficient</fullName>
                </value>
                <value>
                    <fullName>AutoCancelled</fullName>
                    <label>Auto Cancelled</label>
                </value>
                <value>
                    <fullName>ManualCancelled</fullName>
                    <label>Manual Cancelled</label>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <description>Field use to map the type of the checklist to the task type required by work-relay.</description>
        <formula>IF(TEXT(Type__c) != &apos;&apos;, &apos;Task: &apos; + TEXT(Type__c), &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Task Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Process where the checklist is relevant</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Age</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Course Prerequisite</fullName>
                </value>
                <value>
                    <fullName>GTE</fullName>
                </value>
                <value>
                    <fullName>Name Change</fullName>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Residency</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Work Experience</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Under 18</fullName>
                </value>
                <value>
                    <fullName>OSHC</fullName>
                </value>
                <value>
                    <fullName>Offer Conditions</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>AdditionalVisa</fullName>
                </value>
                <value>
                    <fullName>AdditionalResidency</fullName>
                </value>
                <value>
                    <fullName>Unit Prerequisite</fullName>
                </value>
                <value>
                    <fullName>Course</fullName>
                </value>
                <value>
                    <fullName>Curriculum Vitae</fullName>
                </value>
                <value>
                    <fullName>Application Documents</fullName>
                </value>
                <value>
                    <fullName>Research Program</fullName>
                </value>
                <value>
                    <fullName>Previous Application</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Checklist</label>
    <nameField>
        <displayFormat>DC{YYYY}-{000000}</displayFormat>
        <label>Checklist Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactDocumentManager.cls
/**
 * @description Handles all process from contactDocTaggingManager.html (lwc)
 * @revisions    created - J.Mapanao - 28/07/2019
 * 08/10/2024 Kai-Fan Hsieh - DANO-230 - Added overload to saveFileAndContactDocumentChecklist to include document owner mismatch
 */
public with sharing class ContactDocumentManager {

    public static final String RESULT_KEY_FILENAME = 'FILENAME';
    public static final String RESULT_KEY_UPLOADEDDATE = 'UPLOADEDDATE';
    public static final String RESULT_KEY_CURRENTCHECKLISTITEM = 'CURRENTCHECKLISTITEM';
    public static final String RESULT_KEY_CHECKLISTITEM = 'CHECKLISTITEM';
    public static final String RESULT_KEY_CURRENTDOCUMENTTYPE = 'CURRENTDOCUMENTTYPE';
    public static final String RESULT_KEY_DOCTYPECHECKLISTITEMMAP = 'DOCTYPECHECKLISTITEMMAP';
    public static final String RESULT_KEY_CURRENTDOCASSESSMENTSTATUS = 'CURRENTDOCASSESSMENTSTATUS';
    public static final String RESULT_KEY_DOCASSESSMENTSTATUSOPTIONS = 'DOCASSESSMENTSTATUSOPTIONS';
    public static final String RESULT_KEY_DOCASSESSMENTSTATUSHELPTEXT = 'DOCASSESSMENTSTATUSHELPTEXT';

    public static final String RESULT_KEY_ERROR = 'ERROR';
    public static final String RESULT_KEY_SUCCESS = 'SUCCESS';

    public static String CHECKLIST_STATUS_REQUESTED = 'Requested';
    public static String CHECKLIST_STATUS_SUBMITTED = 'Submitted';
    public static String CHECKLIST_STATUS_INSUFFICIENT = 'Insufficient';
    public static String CHECKLIST_STATUS_NOT_REQUIRED = 'Not Required';

    public static String CHECKLIST_OTHER_VALUE = 'Other';
    public static String CHECKLIST_OTHER_LABEL = 'Other Documents';

    /**
     * @description init logic, getting all required information for contactDocTaggingManager.html (lwc)
     * @param       String contactDocumentId
     
    @AuraEnabled(cacheable=true)
    public static Object retrieveData(String contactDocumentId) {
        Object result;
        try {
            Map<String,Object> data = new Map<String,Object>();
            // Get contact document details
            List<Contact_Document__c> contactDocuments = getContactDocumentDetails(contactDocumentId);
            Contact_Document__c contactDocument = contactDocuments.get(0);
            
            // Get Help Text for Document Assessment Status field
            String documentAssessmentStatusHelpText = Contact_Document__c.Document_Assessment_Status__c.getDescribe().getInlineHelpText();
            data.put(RESULT_KEY_DOCASSESSMENTSTATUSHELPTEXT,documentAssessmentStatusHelpText);

            // Get all checklist items related to application
            List<Document_Checklist__c> applicationChecklists = getApplicationChecklist(contactDocument.Application__c);

            // Create File Name
            List<ContentDocumentLink> contentDocumentLinks = getContentDocumentLinks(getIds(contactDocuments));
            List<ContentDocument> contentDocuments = getContentDocuments(getIds(contentDocumentLinks));
            data.put(RESULT_KEY_FILENAME,contactDocument.Filename__c);
            data.put(RESULT_KEY_UPLOADEDDATE,contactDocument.LastModifiedDate);
            
            // Get current document assessment status
            Map<String,String> currentDocumentAssessmentStatus = getCurrentDocumentAssessmentStatus(contactDocument);
            data.put(RESULT_KEY_CURRENTDOCASSESSMENTSTATUS,currentDocumentAssessmentStatus);
            
            // Create document assessment status options
            Map<String,String> documentAssessmentStatusMap = getDocumentAssessmentStatusFieldMapping();
            data.put(RESULT_KEY_DOCASSESSMENTSTATUSOPTIONS,documentAssessmentStatusMap);
            
            // Get current checklist
            Map<String,String> currentChecklist = new Map<String,String>();
            currentChecklist = getCurrentApplicationChecklist(contactDocument);
            data.put(RESULT_KEY_CURRENTCHECKLISTITEM,currentChecklist);

            // Create checklist item picklist options
            Map<String,Object> checklistItemOptions = new Map<String,Object>();
            Map<String,String> checklistItemMap = createChecklistItemMap(applicationChecklists);
            checklistItemOptions.put(RESULT_KEY_CHECKLISTITEM,checklistItemMap);
            data.put(RESULT_KEY_CHECKLISTITEM,checklistItemMap);

            // Get current document type
            Map<String,String> currentDocumentType = new Map<String,String>();
            currentDocumentType = getCurrentDocumentType(contactDocument);
            data.put(RESULT_KEY_CURRENTDOCUMENTTYPE,currentDocumentType);

            // Create document type options
            Map<String,Object> documentTypeOptions = new Map<String,Object>();
            Map<String,Map<String,String>> documentTypeChecklistItemMap = createDocumentTypeChecklistItemMap(applicationChecklists);
            documentTypeOptions.put(RESULT_KEY_DOCTYPECHECKLISTITEMMAP,documentTypeChecklistItemMap);
            data.put(RESULT_KEY_DOCTYPECHECKLISTITEMMAP,documentTypeChecklistItemMap);

            result = data;
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, '###' + ex.getMessage());
            Map<String,Object> errorMap = new Map<String,Object>();
            errorMap.put(RESULT_KEY_ERROR, 'Something went wrong getting information. Please contact your administrator.');
            result = errorMap;
        }
        return result;
    }*/
    
    /**
     * @description init logic, getting all required information for contactDocTaggingManager.html (lwc)
     * @param       String contactDocumentId
     */
    @AuraEnabled(cacheable=true)
    public static Object retrieveDataDocumentChecklist(String contactDocumentId) {
        Object result;
        try {
            Map<String,Object> data = new Map<String,Object>();
            // Get contact document details
            List<Contact_Document__c> contactDocuments = getContactDocumentDetails(contactDocumentId);
            Contact_Document__c contactDocument = contactDocuments.get(0);
            data.put('IsInternalOnly', contactDocument.Internal_Only__c);
            
            // Get Help Text for Document Assessment Status field
            String documentAssessmentStatusHelpText = Contact_Document__c.Document_Assessment_Status__c.getDescribe().getInlineHelpText();
            data.put(RESULT_KEY_DOCASSESSMENTSTATUSHELPTEXT,documentAssessmentStatusHelpText);

            // Get all checklist items related to application
            List<Document_Checklist__c> applicationChecklists = getDocumentChecklist(contactDocument.Application__c);

            // Create File Name
            data.put(RESULT_KEY_FILENAME,contactDocument.Filename__c);
            data.put(RESULT_KEY_UPLOADEDDATE,contactDocument.LastModifiedDate);
            
            // Get current document assessment status
            Map<String,String> currentDocumentAssessmentStatus = getCurrentDocumentAssessmentStatus(contactDocument);
            data.put(RESULT_KEY_CURRENTDOCASSESSMENTSTATUS,currentDocumentAssessmentStatus);
            
            // Create document assessment status options
            Map<String,String> documentAssessmentStatusMap = getDocumentAssessmentStatusFieldMapping();
            data.put(RESULT_KEY_DOCASSESSMENTSTATUSOPTIONS,documentAssessmentStatusMap);
            
            // Get current checklist
            Map<String,String> currentChecklist = new Map<String,String>();
            currentChecklist = getCurrentApplicationChecklist(contactDocument);
            data.put(RESULT_KEY_CURRENTCHECKLISTITEM,currentChecklist);

            // Create checklist item picklist options
            Map<String,Object> checklistItemOptions = new Map<String,Object>();
            Map<String,String> checklistItemMap = createChecklistItemMap(applicationChecklists);
            checklistItemOptions.put(RESULT_KEY_CHECKLISTITEM,checklistItemMap);
            data.put(RESULT_KEY_CHECKLISTITEM,checklistItemMap);

            // Get current document type
            Map<String,String> currentDocumentType = new Map<String,String>();
            currentDocumentType = getCurrentDocumentType(contactDocument);
            data.put(RESULT_KEY_CURRENTDOCUMENTTYPE,currentDocumentType);

            // Create document type options
            Map<String,Object> documentTypeOptions = new Map<String,Object>();
            Map<String,Map<String,String>> documentTypeChecklistItemMap = createDocumentTypeChecklistItemMap(applicationChecklists);
            documentTypeOptions.put(RESULT_KEY_DOCTYPECHECKLISTITEMMAP,documentTypeChecklistItemMap);
            data.put(RESULT_KEY_DOCTYPECHECKLISTITEMMAP,documentTypeChecklistItemMap);

            result = data;
        } catch (Exception ex) {
            nebula.Logger.error(ex.getMessage(), ex);
            nebula.Logger.saveLog();
            Map<String,Object> errorMap = new Map<String,Object>();
            errorMap.put(RESULT_KEY_ERROR, 'Something went wrong getting information. Please contact your administrator.');
            result = errorMap;
        }
        return result;
    }

    private static List<Contact_Document__c> getContactDocumentDetails(String contactDocumentId) {
        return
        [
            SELECT  Id,
                    Application__c,
                    Document_Assessment_Status__c,
                    Document_Checklist__c,
                    Document_Checklist__r.Checklist_Requirement__c,
                    Document_Type__c,
                    Filename__c,
                    LastModifiedDate,
                    Internal_Only__c
            FROM    Contact_Document__c
            WHERE   Id =: contactDocumentId
        ];
    }
    
    private static List<Document_Checklist__c> getApplicationChecklist(String applicationId) {
        return
        [
            SELECT
                    Id,
                    Allowed_Document_Type__c,
                    Application__c,
                    Checklist_Requirement__c,
                    Task_Type__c
            FROM    Document_Checklist__c
            WHERE   Application__c =: applicationId
        ];
    }

    private static List<Document_Checklist__c> getDocumentChecklist(String applicationId) {
        return
        [
            SELECT
                    Id,
                    Allowed_Document_Type__c,
                    Application__c,
                    Checklist_Requirement__c,
                    Task_Type__c
            FROM    Document_Checklist__c
            WHERE   Application__c =: applicationId
        ];
    }
    
    private static List<Document_Checklist__c> getApplicationChecklist(Set<String> appChecklistItemIds) {
        return
        [
            SELECT
                    Id,
                    Allowed_Document_Type__c,
                    Application__c,
                    Checklist_Requirement__c,
                    Task_Type__c,
                    Status__c,
                    (SELECT Id, Name FROM Contact_Documents__r)
            FROM    Document_Checklist__c
            WHERE   Id =: appChecklistItemIds
        ];
    }

    private static List<Document_Checklist__c> getDocumentChecklist(Set<String> documentChecklistItemIds) {
        return
        [
            SELECT
                    Id,
                    Allowed_Document_Type__c,
                    Application__c,
                    Checklist_Requirement__c,
                    Type__c,
                    Task_Type__c,
                    Status__c,
                    (SELECT Id, Name FROM Contact_Documents__r WHERE Internal_Only__c = false)
            FROM    Document_Checklist__c
            WHERE   Id =: documentChecklistItemIds
        ];
    }

    private static List<ContentDocumentLink> getContentDocumentLinks(Set<String> contactDocumentIds) {
        return
        [
            SELECT
                    Id,
                    ContentDocumentId,
                    LinkedEntityId
            FROM    ContentDocumentLink
            WHERE   LinkedEntityId IN: contactDocumentIds
        ];
    }

    private static List<ContentDocument> getContentDocuments(Set<String> contentDocumentIds) {
        return
        [
            SELECT
                    Id,
                    Description,
                    FileExtension,
                    FileType,
                    Title,
                    LastModifiedDate
            FROM    ContentDocument
            WHERE   Id IN: contentDocumentIds
        ];
    }

    /**
     * @description Handles logic to create checklist item options
     * @param       List<Document_Checklist__c> applicationChecklists
     */
    private static Map<String,String> createChecklistItemMap(List<Document_Checklist__c> applicationChecklists) {
        Map<String,String> checklistItemMap = new Map<String,String>();
        for (Document_Checklist__c checklist : applicationChecklists) {
            checklistItemMap.put(checklist.Id,checklist.Checklist_Requirement__c);
        }
        checklistItemMap.put(CHECKLIST_OTHER_VALUE,CHECKLIST_OTHER_LABEL);
        return checklistItemMap;
    }
    
    /**
     * @description Handles logic to create document type options
     * @param       List<Document_Checklist__c> applicationChecklists
     */
    private static Map<String,Map<String,String>> createDocumentTypeChecklistItemMap(List<Document_Checklist__c> applicationChecklists) {
        Map<String,Map<String,String>> docTypeChecklistItemMap = new Map<String,Map<String,String>>();
        Map<String,String> contactDocumentTypeFieldMap = getContactDocumentTypeFieldMapping();
        for (Document_Checklist__c checklist : applicationChecklists) {
            List<String> allowedDocTypes = new List<String>();
            if (String.isNotBlank(checklist.Allowed_Document_Type__c)) {
                allowedDocTypes = checklist.Allowed_Document_Type__c.split(';');
            }
            Map<String,String> allowedDocTypesMap = new Map<String,String>();
            for (String adt : allowedDocTypes) {
                allowedDocTypesMap.put(adt, contactDocumentTypeFieldMap.get(adt));
            }
            docTypeChecklistItemMap.put(checklist.Id,allowedDocTypesMap);
        }
        

        return docTypeChecklistItemMap;
    }
    
    /**
     * @description Handles logic to get current application checklist from contact document
     * @param       Contact_Document__c contactDocument
     */
    private static Map<String,String> getCurrentApplicationChecklist(Contact_Document__c contactDocument) {
        Map<String,String> currentChecklistMap = new Map<String,String>();
        if (contactDocument.Document_Checklist__c != null) {
            currentChecklistMap.put(contactDocument.Document_Checklist__c,contactDocument.Document_Checklist__r.Checklist_Requirement__c);
        } else {
            currentChecklistMap.put(CHECKLIST_OTHER_VALUE,CHECKLIST_OTHER_LABEL);
        }
        return currentChecklistMap;
    }

    /**
     * @description Handles logic to get current document type from contact document
     * @param       Contact_Document__c contactDocument
     */
    private static Map<String,String> getCurrentDocumentType(Contact_Document__c contactDocument) {
        Map<String,String> currentDocumentTypeMap = new Map<String,String>();
        Map<String,String> contactDocumentTypeFieldMap = getContactDocumentTypeFieldMapping();
        if (String.isNotBlank(contactDocument.Document_Type__c)) {
            currentDocumentTypeMap.put(contactDocument.Document_Type__c,contactDocumentTypeFieldMap.get(contactDocument.Document_Type__c));
        }
        return currentDocumentTypeMap;
    }

    /**
     * @description Handles logic to get the current document assessment status
     * @param       Contact_Document__c contactDocument
     */
    private static Map<String,String> getCurrentDocumentAssessmentStatus(Contact_Document__c contactDocument) {
        Map<String,String> currentDocumentAssessmentStatusMap = new Map<String,String>();
        Map<String,String> documentAssessmentStatusFieldMap = getDocumentAssessmentStatusFieldMapping();
        if (String.isNotBlank(contactDocument.Document_Assessment_Status__c)) {
            currentDocumentAssessmentStatusMap.put(contactDocument.Document_Assessment_Status__c,documentAssessmentStatusFieldMap.get(contactDocument.Document_Assessment_Status__c));
        }
        return currentDocumentAssessmentStatusMap;
    }

    /**
     * @description Handles logic to create mapping of Contact_Document__c.Document_Type__c
     *              key = api value, value = label
     */
    private static Map<String,String> getContactDocumentTypeFieldMapping() {
        Map<String,String> contactDocumentTypeFieldMap = new Map<String,String>();
        Schema.DescribeFieldResult fieldResult = Contact_Document__c.Document_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : ple) {
            contactDocumentTypeFieldMap.put(f.getValue(),f.getLabel());
        }
        return contactDocumentTypeFieldMap;
    }

    /**
     * @description Handles logic to create mapping of Contact_Document__c.Document_Assessment_Status__c
     *              key = api value, value = label
     */
    private static Map<String,String> getDocumentAssessmentStatusFieldMapping() {
        Map<String,String> documentAssessmentStatusFieldMap = new Map<String,String>();
        Schema.DescribeFieldResult fieldResult = Contact_Document__c.Document_Assessment_Status__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : ple) {
            documentAssessmentStatusFieldMap.put(f.getValue(),f.getLabel());
        }
        return documentAssessmentStatusFieldMap;
    }

    /**
     * @description Handles logic dynamic creation of Set<String> for Ids
     * @param       List<sObject> sObjects
     */
    private static Set<String> getIds(List<sObject> sObjects) {
        Set<String> ids = new Set<String>();
        for (sObject sObj : sObjects) {
            ids.add((String)sObj.get('Id'));
        }
        return ids;
    }

    /**
     * @description Handles logic for DML
     * @param       String contactDocumentId
     * @param       String newChecklistItem
     * @param       String newDocumentType
     
    @AuraEnabled
    public static Object saveDocument(String contactDocumentId, String newChecklistItem, String newDocumentType, String contentDocuId, String documentAssessmentStatus) {
        Object result;
        Map<String,String> resultMap = new Map<String,String>();
        Savepoint sp = Database.setSavepoint();
        try {

            // Query details of contact document
            List<Contact_Document__c> contactDocuments = getContactDocumentDetails(contactDocumentId);
            
            // Get and store the current application checklist and document type (consider as old value)
            String oldChecklistItem = contactDocuments.get(0).Document_Checklist__c;
            String oldDocumentType = contactDocuments.get(0).Document_Type__c;

            // Set the new application checklist and document type and update
            contactDocuments.get(0).Document_Checklist__c = (newChecklistItem != CHECKLIST_OTHER_VALUE) ? newChecklistItem : null;
            contactDocuments.get(0).Document_Type__c = newDocumentType;
            contactDocuments.get(0).Document_Assessment_Status__c = (String.isNotBlank(documentAssessmentStatus)) ? documentAssessmentStatus : null;
            update contactDocuments;

            // Get the latest status of the application checklist
            Set<String> appChecklistItemIds = new Set<String>();
            if (newChecklistItem != CHECKLIST_OTHER_VALUE) {
                appChecklistItemIds.add(newChecklistItem);
            }
            
            if (String.isNotBlank(oldChecklistItem)) {
                appChecklistItemIds.add(oldChecklistItem);
            }
            List<Document_Checklist__c> applicationChecklists = getApplicationChecklist(appChecklistItemIds);

            Map<Id,Document_Checklist__c> appCheckToUpdateMap = new Map<Id,Document_Checklist__c>();
            for (Document_Checklist__c appCheckItem : applicationChecklists) {
                if (appCheckItem.Id == oldChecklistItem) {
                    if (appCheckItem.Status__c == CHECKLIST_STATUS_SUBMITTED && appCheckItem.Contact_Documents__r.size() == 0) {
                        appCheckItem.Status__c = CHECKLIST_STATUS_REQUESTED;
                        appCheckToUpdateMap.put(appCheckItem.Id,appCheckItem);
                    }
                }

                if (newChecklistItem != CHECKLIST_OTHER_VALUE && appCheckItem.Id == newChecklistItem) {
                    if ((appCheckItem.Status__c == CHECKLIST_STATUS_REQUESTED || appCheckItem.Status__c == CHECKLIST_STATUS_INSUFFICIENT) && appCheckItem.Contact_Documents__r.size() > 0) {
                        appCheckItem.Status__c = CHECKLIST_STATUS_SUBMITTED;
                        appCheckToUpdateMap.put(appCheckItem.Id,appCheckItem);
                    }
                }
            }

            // Update application checklist
            if (appCheckToUpdateMap.size() > 0) {
                update appCheckToUpdateMap.values();
            }
            
            // Remove Content Document Link from previous application checklist if not blank
            if (String.isNotBlank(oldChecklistItem)) {
                List<ContentDocumentLink> conDocLinks = getContentDocumentLinks(new Set<String>{oldChecklistItem});
                if (!conDocLinks.isEmpty()) {
                    delete conDocLinks;
                }
            }
            
            if (newChecklistItem != CHECKLIST_OTHER_VALUE) {
                ContentDocumentLink conDocLinkToInsert = new ContentDocumentLink(
                    ContentDocumentId = contentDocuId,
                    LinkedEntityId = newChecklistItem,
                    ShareType = 'I',
                    Visibility = 'AllUsers'
                );
                insert conDocLinkToInsert;
            }
            
            resultMap.put(RESULT_KEY_SUCCESS,'Record successfully updated.');
            result = resultMap;
        } catch (Exception ex) {
            System.debug('### ERROR:' + ex.getMessage());
            resultMap.put(RESULT_KEY_ERROR,'Something went wrong. Please contact your administrator.' + ex.getMessage() + '--' + ex.getStackTraceString());
            result = resultMap;
            Database.rollback(sp);
            return result;
        }
        return result;
    }*/

    /**
     * @description Saves the document with the new checklist
     * @param contactDocumentId - The ID of the contact document
     * @param newChecklistItem - The new checklist item
     * @param newDocumentType - The new document type
     * @param contentDocuId - The ID of the content document
     * @param documentAssessmentStatus - The status of the document assessment
     * @param isInternalOnly - Whether the document is internal only
     * @return  The result of the save operation
     */
    @AuraEnabled
    public static Object saveDocumentDocumentChecklist(String contactDocumentId, String newChecklistItem,
        String newDocumentType, String contentDocuId, String documentAssessmentStatus, Boolean isInternalOnly) {
        return saveDocumentDocumentChecklist(contactDocumentId, newChecklistItem, newDocumentType, contentDocuId, documentAssessmentStatus, isInternalOnly, null);
    }

    /**
     * @description Saves the document with the new checklist and document owner mismatch field
     * @param contactDocumentId - The ID of the contact document
     * @param newChecklistItem - The new checklist item
     * @param newDocumentType - The new document type
     * @param contentDocuId - The ID of the content document
     * @param documentAssessmentStatus - The status of the document assessment
     * @param isInternalOnly - Whether the document is internal only
     * @param documentOwnerMismatch - Whether the document owner is mismatch
     * @return  The result of the save operation
     */
    @AuraEnabled
    public static Object saveDocumentDocumentChecklistWithDocumentOwnerMismatch(String contactDocumentId, String newChecklistItem,
        String newDocumentType, String contentDocuId, String documentAssessmentStatus, Boolean isInternalOnly, Boolean documentOwnerMismatch) {
        return saveDocumentDocumentChecklist(contactDocumentId, newChecklistItem, newDocumentType, contentDocuId, documentAssessmentStatus, isInternalOnly, documentOwnerMismatch);
    }

    private static Object saveDocumentDocumentChecklist(String contactDocumentId, String newChecklistItem, String newDocumentType,
        String contentDocuId, String documentAssessmentStatus, Boolean isInternalOnly, Boolean documentOwnerMismatch) {
        Object result;
        Map<String,String> resultMap = new Map<String,String>();
        Savepoint sp = Database.setSavepoint();
        try {

            // Query details of contact document
            List<Contact_Document__c> contactDocuments = getContactDocumentDetails(contactDocumentId);
            
            // Get and store the current application checklist and document type (consider as old value)
            String oldChecklistItem = contactDocuments.get(0).Document_Checklist__c;

            // Set the new application checklist and document type and update
            contactDocuments.get(0).Document_Checklist__c = (newChecklistItem != CHECKLIST_OTHER_VALUE) ? newChecklistItem : null;
            contactDocuments.get(0).Document_Type__c = newDocumentType;
            contactDocuments.get(0).Document_Assessment_Status__c = (String.isNotBlank(documentAssessmentStatus)) ? documentAssessmentStatus : null;

            contactDocuments.get(0).Internal_Only__c = isInternalOnly;
            if(documentOwnerMismatch != null) {
                contactDocuments.get(0).Document_Owner_Mismatch__c = documentOwnerMismatch;
            }
            update contactDocuments;

            // Get the latest status of the application checklist
            Set<String> appChecklistItemIds = new Set<String>();
            if (newChecklistItem != CHECKLIST_OTHER_VALUE) {
                appChecklistItemIds.add(newChecklistItem);
            }
            
            if (String.isNotBlank(oldChecklistItem)) {
                appChecklistItemIds.add(oldChecklistItem);
            }
            List<Document_Checklist__c> applicationChecklists = getDocumentChecklist(appChecklistItemIds);

            Map<Id,Document_Checklist__c> appCheckToUpdateMap = new Map<Id,Document_Checklist__c>();
            for (Document_Checklist__c appCheckItem : applicationChecklists) {
                if (appCheckItem.Id == oldChecklistItem) {
                    if (appCheckItem.Status__c == CHECKLIST_STATUS_SUBMITTED && appCheckItem.Contact_Documents__r.size() == 0) {
                        appCheckItem.Status__c = CHECKLIST_STATUS_REQUESTED;
                        appCheckToUpdateMap.put(appCheckItem.Id,appCheckItem);
                    }
                }

                if (newChecklistItem != CHECKLIST_OTHER_VALUE && appCheckItem.Id == newChecklistItem) {
                    if ((appCheckItem.Status__c == CHECKLIST_STATUS_REQUESTED || appCheckItem.Status__c == CHECKLIST_STATUS_INSUFFICIENT) && appCheckItem.Contact_Documents__r.size() > 0) {
                        appCheckItem.Status__c = CHECKLIST_STATUS_SUBMITTED;
                        appCheckToUpdateMap.put(appCheckItem.Id,appCheckItem);
                    }
                }
            }

            // Update application checklist
            if (appCheckToUpdateMap.size() > 0) {
                update appCheckToUpdateMap.values();
            }
            
            // Remove Content Document Link from previous application checklist if not blank
            if (String.isNotBlank(oldChecklistItem)) {
                //Only delete links of the checklist is changed
                if(newChecklistItem != oldChecklistItem){
                    List<ContentDocumentLink> conDocLinks = new List<ContentDocumentLink>();
                    //Query link for the checklist and the current content document
                    for(ContentDocumentLink loopLink : [SELECT Id, ContentDocumentId, LinkedEntityId
                                                        FROM ContentDocumentLink 
                                                        WHERE LinkedEntityId = :oldChecklistItem
                                                            AND ContentDocumentId = :contentDocuId]){
                        conDocLinks.add(loopLink);
                    }
                    //delete outdated link records
                    if (!conDocLinks.isEmpty()) {
                        delete conDocLinks;
                    }
                }
            }
            
            //Check if checklist is changed and not equal to OTHER
            if (newChecklistItem != oldChecklistItem && newChecklistItem != CHECKLIST_OTHER_VALUE) {
                ContentDocumentLink conDocLinkToInsert = new ContentDocumentLink(
                    ContentDocumentId = contentDocuId,
                    LinkedEntityId = newChecklistItem,
                    ShareType = 'I',
                    Visibility = 'AllUsers'
                );
                insert conDocLinkToInsert;
            }
            
            resultMap.put(RESULT_KEY_SUCCESS,'Record successfully updated.');
            result = resultMap;
        } catch (Exception ex) {
            nebula.Logger.error(ex.getMessage(), ex);
            nebula.Logger.saveLog();
            resultMap.put(RESULT_KEY_ERROR,'Something went wrong. Please contact your administrator.' + ex.getMessage() + '--' + ex.getStackTraceString());
            result = resultMap;
            Database.rollback(sp);
            return result;
        }
        return result;
    }
}