force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent for Submission</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Data Validation Ready</fullName>
                </value>
                <value>
                    <fullName>Failed Data validation</fullName>
                </value>
                <value>
                    <fullName>Submission on Hold (Duplicate Contact)</fullName>
                </value>
                <value>
                    <fullName>Agent Declaration Accepted</fullName>
                </value>
                <value>
                    <fullName>Sent Draft Application to Applicant</fullName>
                </value>
                <value>
                    <fullName>Applicant Declaration Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ApplicationSuccessCC.cls
/*******************************************************************************
* @author       Ant Custodio
* @date         7.Apr.2017         
* @description  controller class for ApplicationSuccess.cmp
* @revision     
 * 19/07/2023 enhanced security
*******************************************************************************/
public without sharing class ApplicationSuccessCC {
	/*******************************************************************************
    * @author       Ant Custodio
    * @date         7.Apr.2017         
    * @description  retrieves the application using the URL parameters
    * @revision     
    *******************************************************************************/
    @AuraEnabled
    public static Application__c retrieveApplication (String applicationId) {
        Id currentUserId = UserInfo.getUserId();
        User currentUser = [SELECT ContactId, Profile.Name FROM User WHERE Id = :currentUserId];
        Boolean isCommunityUser = currentUser.Profile.Name == 'Customer Community General User';

    	Application__c applicationRecord = isCommunityUser ? getApplicationRecord(applicationId,currentUser.contactId) :  getApplicationRecord(applicationId); 

        return applicationRecord;
    }

    
        /**
        @author       Ant Ken McGuire
         @date        24.7.2023 
        Retrieves a single Application record based on the provided applicationId and applicant (contact).
        @param applicationId (String) The unique identifier of the Application record to retrieve.
        @param applicantId (String) The unique identifier of the applicant associated with the Application record.
        @return Application__c The Application record that corresponds to the provided applicationId. Returns null if no matching record is found.
        */

        private static Application__c getApplicationRecord(String applicationId, String applicantId) {
            return [SELECT Id, Name, Status__c FROM Application__c WHERE Id =: applicationId and  Applicant__c = :applicantId LIMIT 1];

        }

        /**
        @author       Ant Ken McGuire
         @date        24.7.2023 
        Retrieves a single Application record based on the provided applicationId
        @param applicationId (String) The unique identifier of the Application record to retrieve.
        @return Application__c The Application record that corresponds to the provided applicationId. Returns null if no matching record is found.
        */

        private static Application__c getApplicationRecord(String applicationId) {
            return [SELECT Id, Name, Status__c FROM Application__c WHERE Id =: applicationId  LIMIT 1 ];

        }

}