force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Assessment_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to state if assessment is required or not</description>
        <label>Assessment Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Workflow_Status__c</fullName>
        <label>Workflow Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Queue_Routing_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to make rule active or inactive</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Controls the order in which Rules are evaluated</description>
        <inlineHelpText>Controls the order in which Rules are evaluated</inlineHelpText>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <description>Stores the Queue where the ACP will be routed to</description>
        <label>Queue</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_BUSECO</fullName>
                    <label>CENTRAL ADMISSIONS - BUSECO</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_IT</fullName>
                    <label>CENTRAL ADMISSIONS - IT</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_MNHS</fullName>
                    <label>CENTRAL ADMISSIONS - MNHS</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_MADA</fullName>
                    <label>CENTRAL ADMISSIONS - MADA</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_ARTS</fullName>
                    <label>CENTRAL ADMISSIONS - ARTS</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_EDUCATION</fullName>
                    <label>CENTRAL ADMISSIONS - EDUCATION</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_ENGINEERING</fullName>
                    <label>CENTRAL ADMISSIONS - ENGINEERING</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_SCIENCE</fullName>
                    <label>CENTRAL ADMISSIONS - SCIENCE</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_LAW</fullName>
                    <label>CENTRAL ADMISSIONS - LAW</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_PHARMACY</fullName>
                    <label>CENTRAL ADMISSIONS - PHARMACY</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_MC</fullName>
                    <label>CENTRAL ADMISSIONS - MC</label>
                </value>
                <value>
                    <fullName>FACULTY_IT</fullName>
                    <label>FACULTY - IT</label>
                </value>
                <value>
                    <fullName>FACULTY_BUSECO</fullName>
                    <label>FACULTY - BUSECO</label>
                </value>
                <value>
                    <fullName>FACULTY_MNHS</fullName>
                    <label>FACULTY - MNHS</label>
                </value>
                <value>
                    <fullName>FACULTY_EDUCATION</fullName>
                    <label>FACULTY - EDUCATION</label>
                </value>
                <value>
                    <fullName>FACULTY_ARTS</fullName>
                    <label>FACULTY - ARTS</label>
                </value>
                <value>
                    <fullName>CENTRAL_ADMISSIONS_INDONESIA</fullName>
                    <label>CENTRAL ADMISSIONS - INDONESIA</label>
                </value>
                <value>
                    <fullName>FACULTY_MD</fullName>
                    <label>FACULTY - MD</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Queue Routing Rule</label>
    <nameField>
        <label>Queue Routing Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Queue Routing Rule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Queue_Routing_Rule_Condition__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <description>Application Course Preference field for this condition</description>
        <label>Field</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Admission_Category__c</fullName>
                    <label>Admission Category</label>
                </value>
                <value>
                    <fullName>Attendance_Mode__c</fullName>
                    <label>Attendance Mode</label>
                </value>
                <value>
                    <fullName>Course_Code__c</fullName>
                    <label>Course Code</label>
                </value>
                <value>
                    <fullName>Location_Code__c</fullName>
                    <label>Location Code</label>
                </value>
                <value>
                    <fullName>Managing_Faculty__c</fullName>
                    <label>Managing Faculty</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>Logical Operator for this condition</description>
        <label>Operator</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EQUALS</fullName>
                    <default>true</default>
                    <label>EQUALS</label>
                </value>
                <value>
                    <fullName>NOT EQUAL TO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Routing_Rule__c</fullName>
        <label>Queue Routing Rule</label>
        <referenceTo>Queue_Routing_Rule__c</referenceTo>
        <relationshipLabel>Queue Routing Rule Conditions</relationshipLabel>
        <relationshipName>Queue_Routing_Rule_Conditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value for this condition</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Queue Routing Rule Condition</label>
    <nameField>
        <displayFormat>QRRC-{000000}</displayFormat>
        <label>QRR Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queue Routing Rule Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ACPQueueRoutingPlatformEventHandler.cls
/**
 * @author       Sethu Venna
 * @date         Aug.2025
 * @description  Routes the ACP to the correct queue for Assessment
 */
public without sharing class ACPQueueRoutingPlatformEventHandler implements IPlatformEventInvocable {
    static final String LOG_TAG = 'ACP Routing';

    private static Map<Id, Group> queueIdMap;
    private static Map<String, Group> queueNameMap;
    List<Application_Course_Preference__c> lstACP;
    Set<Id> setACPId;


    /**
     * @description Queueable execute method
     * @param  payloads
     */
    public void execute(List<AsyncProcessPayload> payloads) {
        try {
            Nebula.Logger.setScenario('ACP Queue Routing');
            initialize(payloads);
            if(!setACPId.isEmpty()) {
                lstACP = (List<Application_Course_Preference__c>) new ApplicationCoursePreferenceSelector().selectSObjectsById(setACPId);
                routeACPtoQueues(lstACP);
            }
        } catch (Exception ex) {
            // route failures to unallocated queue & log error
            handleFailures(lstACP, ex.getMessage());
        } finally {
            Nebula.Logger.saveLog();
            Nebula.Logger.endScenario('ACP Queue Routing');
        }
    }

    private void initialize(List<AsyncProcessPayload> payloads) { 
            if(payloads != null) {
                setACPId = new Set<Id>();
                for(AsyncProcessPayload payload : payloads) {
                    Object tmpObj = (Object) payload.get('acpId');
                    setACPId.add(Id.valueof(String.valueOf(tmpObj)));
                }
            }
        }

    /**
     * @description     Check Managing Faculty and route ACPs to correct Queues.
     * @author          rajesh.punjabi@monash.edu | 17-07-2024
     * @param           lstACP
     * @modified
     *                  Jitender Padda | Jul.2024 - Dynamic routing based on config table
     **/
    public void routeACPtoQueues(List<Application_Course_Preference__c> lstACP) {
        List<Application_Course_Preference__c> lstACPtoUpdate = new List<Application_Course_Preference__c>();

        createQueueMaps();
        List<Queue_Routing_Rule_Condition__c> routingRuleConditions = getQueueRoutingRuleConditions();

        for (Application_Course_Preference__c oACP : lstACP) {
            Boolean hasRuleMatched = false;
            Boolean allConditionsMatch = true;

            // set current routing rule - first rule
            Queue_Routing_Rule__c currentRoutingRule = new Queue_Routing_Rule__c();
            setCurrentRoutingRule(currentRoutingRule, routingRuleConditions[0]);

            // NOTE: conditions are ordered by rule
            for (Queue_Routing_Rule_Condition__c routingRuleCondition : routingRuleConditions) {
                // if rule changed
                if (currentRoutingRule.Id != routingRuleCondition.Queue_Routing_Rule__c) {
                    // - check if previous rule conditions matched & set queue
                    if (allConditionsMatch) {
                        hasRuleMatched = evaluateRule(allConditionsMatch, oACP, currentRoutingRule);
                        break;
                    }

                    // - reset currentRoutingRule & allConditionsMatch
                    setCurrentRoutingRule(currentRoutingRule, routingRuleCondition);
                    allConditionsMatch = true;
                }

                if (allConditionsMatch) { // optimisation
                    // - check if rule condition matches
                    if (evaluateRuleCondition(oACP, routingRuleCondition) == false) {
                        allConditionsMatch = false;
                    }
                }

                // if last condition - check last rule
                if (routingRuleCondition.Id == getLastItem(routingRuleConditions).Id) {
                    // - check if conditions matched & set queue
                    hasRuleMatched = evaluateRule(allConditionsMatch, oACP, currentRoutingRule);
                }
            }

            // assign to unallocated as fallback
            if (hasRuleMatched == false) {
                handleUnmatched(oACP);
            }

			//oACP.Assessment_Flag__c = true;
			oACP.Workflow_Status__c = 'Pending';
            
            lstACPtoUpdate.add(oACP);
        }

        if (lstACPtoUpdate.size() > 0) {
            List<Database.SaveResult> saveResults = Database.update(lstACPtoUpdate, false, AccessLevel.SYSTEM_MODE);

            // route failures to unallocated queue
            handleExceptions(saveResults, lstACPtoUpdate);
        }
    }

    private void handleUnmatched(Application_Course_Preference__c oACP) {
        // assign to unallocated as fallback
        routeToUnallocatedQueue(oACP);
        Nebula.Logger.warn('No assignment rules matched', oACP.Id).addtag(LOG_TAG);
    }

    private void routeToUnallocatedQueue(Application_Course_Preference__c oACP) {
        //oACP.Assessment_Flag__c = true;
        oACP.Workflow_Status__c = 'Pending';
        oACP.OwnerId = queueNameMap.get('Unallocated_ACP_Queue').Id;
    }

    private void setCurrentRoutingRule(
        Queue_Routing_Rule__c currentRoutingRule,
        Queue_Routing_Rule_Condition__c routingRuleCondition
    ) {
        currentRoutingRule.Id = routingRuleCondition.Queue_Routing_Rule__c;
        currentRoutingRule.Name = routingRuleCondition.Queue_Routing_Rule__r.Name;
        currentRoutingRule.Queue__c = routingRuleCondition.Queue_Routing_Rule__r.Queue__c;
    }

    private SObject getLastItem(List<SObject> itemList) {
        return itemList[itemList.size() - 1];
    }

    private Boolean evaluateRule(
        Boolean allConditionsMatch,
        Application_Course_Preference__c oACP,
        Queue_Routing_Rule__c currentRoutingRule
    ) {
        if (allConditionsMatch) {
            route(oACP, currentRoutingRule);
            return true;
        }

        return false;
    }

    private void route(Application_Course_Preference__c oACP, Queue_Routing_Rule__c currentRoutingRule) {
        oACP.OwnerId = queueNameMap.get(currentRoutingRule.Queue__c).Id;

        // add logs for successfully routed ACPs
        Nebula.Logger.info('ACP Routing Rule Matched => ' + currentRoutingRule.Name, oACP.Id).addtag(LOG_TAG);
    }

    private Boolean evaluateRuleCondition(
        Application_Course_Preference__c oACP,
        Queue_Routing_Rule_Condition__c routingRuleCondition
    ) {
        String fieldValue = (String) oACP.get(routingRuleCondition.Field__c);
        String comparisonValue = routingRuleCondition.Value__c;

        switch on routingRuleCondition.Operator__c {
            when 'EQUALS' {
                return isEqual(fieldValue, comparisonValue);
            }
            when 'NOT EQUAL TO' {
                return !isEqual(fieldValue, comparisonValue);
            }
        }

        return false;
    }

    @TestVisible
    private Boolean isEqual(String fieldValue, String comparisonValue) {
        fieldValue = fieldValue?.toLowerCase();
        comparisonValue = comparisonValue?.toLowerCase();

        // use set contains if multiple values
        if(comparisonValue != null){
            if (comparisonValue?.contains(';')) {
                return new Set<String>(comparisonValue?.replaceAll('; ', ';')?.split(';'))
                    ?.contains(fieldValue);
            }
        }

        return fieldValue == comparisonValue ? true : false;
    }

    private static void createQueueMaps() {
        if (queueIdMap == null || queueNameMap == null) {
            queueIdMap = new Map<Id, Group>();
            queueNameMap = new Map<String, Group>();

            for (Group queue : [
                SELECT Id, DeveloperName
                FROM Group
                WHERE
                    Type = 'Queue'
                    AND (DeveloperName LIKE 'CENTRAL_ADMISSION_%'
                    OR DeveloperName = 'Unallocated_ACP_Queue'
                        OR DeveloperName LIKE 'FACULTY_%')
            ]) {
               
                queueNameMap.put(queue.DeveloperName, queue);
                queueIdMap.put(queue.Id, queue);
            }
        }
    }

    private static List<Queue_Routing_Rule_Condition__c> getQueueRoutingRuleConditions() {
        return [
            SELECT
                Id,
                Queue_Routing_Rule__r.Name,
                Queue_Routing_Rule__r.Queue__c,
                Queue_Routing_Rule__r.Order__c,
                Field__c,
                Operator__c,
                Value__c
            FROM Queue_Routing_Rule_Condition__c
            WHERE Queue_Routing_Rule__r.Active__c = TRUE
            ORDER BY Queue_Routing_Rule__r.Order__c
        ];
    }

    private void handleExceptions(
        List<Database.SaveResult> saveResults,
        List<Application_Course_Preference__c> lstACPtoUpdate
    ) {
        Database.SaveResult saveResult = null;
        List<Application_Course_Preference__c> failedACPList = new List<Application_Course_Preference__c>();

        for (Integer i = 0; i < saveResults.size(); i++) {
            saveResult = saveResults[i];
            if (!saveResult.isSuccess()) {
                for (Database.Error err : saveResult.getErrors()) {
                    failedACPList.add(lstACPtoUpdate[i]);
                }
            }
        }

        // route failures to unallocated queue
        if (failedACPList.size() > 0) {
            handleFailures(failedACPList, null);
        }
    }

    private void handleFailures(List<Application_Course_Preference__c> lstACP, String errorMsg) {
        for (Application_Course_Preference__c oACP : lstACP) {
            routeToUnallocatedQueue(oACP);

            // add error log
            errorMsg = errorMsg == null ? String.valueOf(oACP.getErrors()) : errorMsg;
            Nebula.Logger.error(errorMsg + '\r' + json.serializePretty(oACP), oACP.id).addtag(LOG_TAG);
        }

        TriggerCommon.disableTrigger('Application_Course_Preference__c');
        update lstACP;
        TriggerCommon.enableTrigger('Application_Course_Preference__c');
    }
}