force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Assessment_Status__c</fullName>
        <description>Track the assessment process once an application is submitted by the applicant</description>
        <inlineHelpText>Track the assessment process once an application is submitted by the applicant</inlineHelpText>
        <label>Assessment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assessment_Flow_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Breached_visa_condition__c</fullName>
        <description>Indicates if the applicant has breached visa conditions in the past.</description>
        <inlineHelpText>Have you breached any visa conditions in any country?</inlineHelpText>
        <label>Breached visa condition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Callista_Application_Id__c</fullName>
        <externalId>true</externalId>
        <label>Callista Application Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Convicted_of_crime_offence__c</fullName>
        <description>Indicates if the applicant has been convicted of any crime or offence in any country.</description>
        <inlineHelpText>Have you been convicted of any crime or offence in any country?</inlineHelpText>
        <label>Convicted of crime/offence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Application Processing Fee Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee_Waiver_Redeemed__c</fullName>
        <description>Indicates if the Waiver code has been redeemed for Application fees</description>
        <label>Processing Fee Waiver Redeemed</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>Display GTE Risk Rating From Country Object</description>
        <formula>TEXT(Submission_Location_Country__r.GTE_Risk_Rating__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GTE Risk Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HasDisabilities__c</fullName>
        <label>HasDisabilities</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Medical_health_prevent_visa__c</fullName>
        <description>Indicates if the applicant has any medical/health issues that may prevent them from obtaining a visa.</description>
        <inlineHelpText>Do you have any medical or health issues that may prevent you from obtaining your visa?</inlineHelpText>
        <label>Medical/health prevent visa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Protection_visa_in_any_country__c</fullName>
        <description>Indicates if the applicant has been issued a protection visa in any other country.</description>
        <inlineHelpText>Have you been issued a protection visa in any country to date?</inlineHelpText>
        <label>Protection visa in any country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Refused_entry_visa_to_any_country__c</fullName>
        <description>Indicates if the applicant has been refused an entry visa to any country.</description>
        <inlineHelpText>Have you been refused an entry visa to any country?</inlineHelpText>
        <label>Refused entry visa to any country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Location_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the country for the submission location of the application</description>
        <label>Submission Location Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Progress__c</fullName>
        <description>Defines the progress of submission that the applicant is going through.</description>
        <label>Submission Progress</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Study__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Declaration</fullName>
                    <default>true</default>
                    <label>Declaration</label>
                </value>
                <value>
                    <fullName>Personal Details</fullName>
                </value>
                <value>
                    <fullName>Study Preferences</fullName>
                </value>
                <value>
                    <fullName>Credentials</fullName>
                </value>
                <value>
                    <fullName>Scholarship</fullName>
                </value>
                <value>
                    <fullName>Application Details</fullName>
                </value>
                <value>
                    <fullName>Research Program</fullName>
                </value>
                <value>
                    <fullName>English Proficiency</fullName>
                </value>
                <value>
                    <fullName>Qualifications</fullName>
                </value>
                <value>
                    <fullName>Awards, Prizes &amp; Scholarship</fullName>
                </value>
                <value>
                    <fullName>Employment &amp; Research Experience</fullName>
                </value>
                <value>
                    <fullName>Referees</fullName>
                </value>
                <value>
                    <fullName>Publications</fullName>
                </value>
                <value>
                    <fullName>Creative Works</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>Theatre Performance</fullName>
                </value>
                <value>
                    <fullName>Exhibitions</fullName>
                </value>
                <value>
                    <fullName>Additional Supporting Information</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Application Fee</fullName>
                </value>
                <value>
                    <fullName>Submit</fullName>
                </value>
                <value>
                    <fullName>Validate &amp; Submit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Disability_Check__c</fullName>
        <label>Task: Disability Check</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assessment_Flow_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Fee__c</fullName>
        <description>Application fee check status flow</description>
        <inlineHelpText>Application fee check status flow</inlineHelpText>
        <label>Task: Fee</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assessment_Flow_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_GTE__c</fullName>
        <label>Task: GTE</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assessment_Flow_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Visa__c</fullName>
        <description>Track if visa assessment needs to be conducted</description>
        <inlineHelpText>Track if visa assessment needs to be conducted</inlineHelpText>
        <label>Task: Visa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assessment_Flow_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Attribute__c.object
<CustomObject>
    <description>This allows the definition of various country attributes (e.g. mapping to ISO codes, ABS codes, Australian border, department of education codes, restricted countries, flags for different user groups which can be used to drive sharing of records etc.)</description>
    <fields>
        <fullName>Active_Ind__c</fullName>
        <defaultValue>true</defaultValue>
        <description>An indicator for record status. Allows country records to be disabled from selection but retain historical data relationships.</description>
        <label>Active Ind</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>Countries and some regional areas will receive a Monash GTE risk rating based on a variety of risk-related data and known environmental factors. The rating will inform the appropriate GTE assessment action taken by the Admissions office.</description>
        <inlineHelpText>The Monash GTE risk rating based on a variety of risk-related data</inlineHelpText>
        <label>GTE Risk Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Assessment_Flow_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Required</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting for docs</fullName>
        <label>Applicant Input Required</label>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Required</fullName>
    </customValue>
    <customValue>
        <fullName>Discontinued</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Input Required</fullName>
    </customValue>
    <description>Assessment status values to track progress of assessment tasks</description>
    <masterLabel>Assessment Flow Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ApplicationBSSetAssessmentTaskFields_FT.cls
/**
 * @description       : Test class for Application_BS_Set_Assessment_Task_Fields Flow
 * @author            : rajesh.punjabi@monash.edu
 * @group             : 
 * @last modified on  : 28-05-2024
 * @last modified by  : rajesh.punjabi@monash.edu
**/
@isTest (isParallel=true)
public class ApplicationBSSetAssessmentTaskFields_FT {
    
    /**
    * @description Insert Event: Add new application.
    * @author rajesh.punjabi@monash.edu | 28-05-2024 
    **/
    @isTest
    private static void insertAssessmentTask_Test(){

        // GIVEN : Create Country and Application (Only GTE Task = required)
        Country_Attribute__c oCountry = new Country_Attribute__c();
        oCountry.Name = 'Iran-test';
        oCountry.GTE_Risk_Rating__c = '3';
        oCountry.Active_Ind__c = true;
        insert oCountry;
        
        Application__c oApplication = new Application__c();
        oApplication.Callista_Application_Id__c = 'CAID-1239090';
        oApplication.Fee_Payment__c = false;
        oApplication.Fee_Waiver_Redeemed__c = 'Test';    
        oApplication.Refused_entry_visa_to_any_country__c = 'Yes';
        oApplication.Breached_visa_condition__c = 'Yes';
        oApplication.Medical_health_prevent_visa__c = 'Yes';
        oApplication.Protection_visa_in_any_country__c = 'Yes';
        oApplication.Convicted_of_crime_offence__c = 'Yes';
        oApplication.HasDisabilities__c = 'Yes';
        oApplication.Submission_Location_Country__c = oCountry.Id;
        oApplication.Submission_Progress__c = 'Submit';
        oApplication.Assessment_Status__c = 'Required';
        
        Test.startTest();
        // WHEN : Push application with required status values.
        insert oApplication;
        Test.stopTest();
        
        // THEN : Verify if Task(s) status is required.
        Application__c oApplicationRecord = [SELECT Id, Task_Visa__c, Task_Disability_Check__c, Task_GTE__c, Task_Fee__c FROM Application__c WHERE Callista_Application_Id__c = 'CAID-1239090' LIMIT 1];
        Assert.areEqual (oApplicationRecord.Task_Disability_Check__c, 'Required', 'DSS Task is required for assessor.');
        Assert.areEqual (oApplicationRecord.Task_GTE__c, 'Required', 'GTE Task is required for assessor.');
		Assert.areEqual (oApplicationRecord.Task_Fee__c, 'Required', 'Fee Task is required for assessor.');
		Assert.areEqual (oApplicationRecord.Task_Visa__c, 'Required', 'Visa Task is required for assessor.');
    }
    
    /**
    * @description  Update Event: Update existing application.
    * @author rajesh.punjabi@monash.edu | 28-05-2024 
    **/
    @isTest
    private static void updateAssessmentTask1_Test(){

		// GIVEN : Create and update Country and Application (All GTE Task = required)
        Country_Attribute__c oCountry = new Country_Attribute__c();
        oCountry.Name = 'Iran-test';
        oCountry.GTE_Risk_Rating__c = '3';
        oCountry.Active_Ind__c = true;
        insert oCountry;
        
        Application__c oApplication = new Application__c();
		oApplication.Callista_Application_Id__c = 'CAID-1238080';
        oApplication.Fee_Payment__c = false;
        oApplication.Fee_Waiver_Redeemed__c = 'Test';    
        oApplication.Refused_entry_visa_to_any_country__c = 'Yes';
        oApplication.Breached_visa_condition__c = 'Yes';
        oApplication.Medical_health_prevent_visa__c = 'Yes';
        oApplication.Protection_visa_in_any_country__c = 'Yes';
        oApplication.Convicted_of_crime_offence__c = 'Yes';
        oApplication.HasDisabilities__c = 'Yes';
        oApplication.Submission_Location_Country__c = oCountry.Id;
        insert oApplication; 
        
        oApplication.Submission_Progress__c = 'Submit';
        oApplication.Assessment_Status__c = 'Required';
        
        Test.startTest();
        // WHEN : Update application with required status values.
        update oApplication;
        Test.stopTest();
        
        Application__c oApplicationRecord = [SELECT Id, Task_Visa__c, Task_Disability_Check__c, Task_GTE__c, Task_Fee__c FROM Application__c WHERE Callista_Application_Id__c = 'CAID-1238080' LIMIT 1];
        Assert.areEqual (oApplicationRecord.Task_Disability_Check__c, 'Required', 'DSS Task is required for assessor.');
        Assert.areEqual (oApplicationRecord.Task_GTE__c, 'Required', 'GTE Task is required for assessor.');
		Assert.areEqual (oApplicationRecord.Task_Fee__c, 'Required', 'Fee Task is required for assessor.');
		Assert.areEqual (oApplicationRecord.Task_Visa__c, 'Required', 'Visa Task is required for assessor.');
    }
    
    /**
    * @description Update application with GTE Risk Rating 1
    * @author rajesh.punjabi@monash.edu | 28-05-2024 
    **/
    @isTest
    private static void updateAssessmentTask2_Test(){
		
        // GIVEN : Create Country and Application (All Task = not required)
        Country_Attribute__c oCountry = new Country_Attribute__c();
        oCountry.Name = 'Iran-test';
        oCountry.GTE_Risk_Rating__c = '1';
        oCountry.Active_Ind__c = true;
        insert oCountry;
        
        Application__c oApplication = new Application__c();
		oApplication.Callista_Application_Id__c = 'CAID-1238081';
        oApplication.Fee_Payment__c = true;
        oApplication.Refused_entry_visa_to_any_country__c = 'No';
        oApplication.Breached_visa_condition__c = 'No';
        oApplication.Medical_health_prevent_visa__c = 'No';
        oApplication.Protection_visa_in_any_country__c = 'No';
        oApplication.Convicted_of_crime_offence__c = 'No';
        oApplication.HasDisabilities__c = 'No';
        oApplication.Submission_Location_Country__c = oCountry.Id;
        insert oApplication; 
        
        oApplication.Submission_Progress__c = 'Submit';
        oApplication.Assessment_Status__c = 'Required';
        
        Test.startTest();
        // WHEN : Update application with required status values.
        update oApplication;
        Test.stopTest();
        
        // THEN : Verify if Task(s) status is required.
        Application__c oApplicationRecord = [SELECT Id, Task_Visa__c, Task_Disability_Check__c, Task_GTE__c, Task_Fee__c FROM Application__c WHERE Callista_Application_Id__c = 'CAID-1238081' LIMIT 1];
        Assert.areEqual (oApplicationRecord.Task_Disability_Check__c, 'Not Required', 'DSS Task is required for assessor.');
        Assert.areEqual (oApplicationRecord.Task_GTE__c, 'Not Required', 'GTE Task is required for assessor.');
		Assert.areEqual (oApplicationRecord.Task_Fee__c, 'Not Required', 'Fee Task is required for assessor.');
		Assert.areEqual (oApplicationRecord.Task_Visa__c, 'Not Required', 'Visa Task is not required for assessor.');
    }
    
    /**
    * @description Update Application with GTE Risk Rating 3
    * @author rajesh.punjabi@monash.edu | 28-05-2024 
    **/
    @isTest
    private static void updateAssessmentTask3_Test(){
		
        // GIVEN : Create Country and Application (Only GTE Task = not required)
        Country_Attribute__c oCountry = new Country_Attribute__c();
        oCountry.Name = 'Iran-test';
        oCountry.GTE_Risk_Rating__c = '3';
        oCountry.Active_Ind__c = true;
        insert oCountry;
        
        Application__c oApplication = new Application__c();
		oApplication.Callista_Application_Id__c = 'CAID-1238080';
        oApplication.Fee_Payment__c = true;
        oApplication.Refused_entry_visa_to_any_country__c = 'No';
        oApplication.Breached_visa_condition__c = 'No';
        oApplication.Medical_health_prevent_visa__c = 'No';
        oApplication.Protection_visa_in_any_country__c = 'No';
        oApplication.Convicted_of_crime_offence__c = 'No';
        oApplication.HasDisabilities__c = 'No';
        oApplication.Submission_Location_Country__c = oCountry.Id;
        insert oApplication; 
        
        oApplication.Submission_Progress__c = 'Submit';
        oApplication.Assessment_Status__c = 'Required';
        
        Test.startTest();
        // WHEN : Update application with required status values.
        update oApplication;
        Test.stopTest();
        
        // THEN : Verify if Task(s) status is required.
        Application__c oApplicationRecord = [SELECT Id, Task_Visa__c, Task_Disability_Check__c, Task_GTE__c, Task_Fee__c FROM Application__c WHERE Callista_Application_Id__c = 'CAID-1238080' LIMIT 1];
        Assert.areEqual (oApplicationRecord.Task_Disability_Check__c, 'Not Required', 'DSS Task is not required for assessor.');
        Assert.areEqual (oApplicationRecord.Task_GTE__c, 'Required', 'DSS Task is required for assessor.');
       	Assert.areEqual (oApplicationRecord.Task_Fee__c, 'Not Required', 'Fee Task is required for assessor.');
		Assert.areEqual (oApplicationRecord.Task_Visa__c, 'Not Required', 'Visa Task is not required for assessor.');
    }
}