force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Access_and_Equity_Question__c</fullName>
        <description>Do you have a disability, mental health or ongoing medical condition that may affect your studies or may prevent you to undertake full-time study?</description>
        <inlineHelpText>Do you have a disability, mental health or ongoing medical condition that may affect your studies or may prevent you to undertake full-time study?</inlineHelpText>
        <label>Access and Equity Question</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Intention__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Intention</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Application Processing Fee Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>Display GTE Risk Rating From Country Object</description>
        <formula>TEXT(Submission_Location_Country__r.GTE_Risk_Rating__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GTE Risk Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission_Location_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the country for the submission location of the application</description>
        <label>Submission Location Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Course_Preference__c.object
<CustomObject>
    <description>A course preference represents a request to to gain admission to a specific course offering within Monash. It is submitted within an application, and tracks the lifecycle of being assessed for entry requirements, offer management and flows into enrolment.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Application No.</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Course Preferences</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Offering</label>
        <referenceTo>Course_Offering__c</referenceTo>
        <relationshipLabel>ACP</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to course code, filtering out Unit Set courses</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>notEqual</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>ACP Courses</relationshipLabel>
        <relationshipName>Application_Course_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Course Preference</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Course Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>Display GTE Risk Rating From Country Object</description>
        <formula>TEXT(Qualification_Country__r.GTE_Risk_Rating__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GTE Risk Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the country at which the qualification is obtained</description>
        <label>Qualification Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualification Lookup</label>
        <referenceTo>Qualification__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Attribute__c.object
<CustomObject>
    <description>This allows the definition of various country attributes (e.g. mapping to ISO codes, ABS codes, Australian border, department of education codes, restricted countries, flags for different user groups which can be used to drive sharing of records etc.)</description>
    <fields>
        <fullName>GTE_Risk_Rating__c</fullName>
        <description>Countries and some regional areas will receive a Monash GTE risk rating based on a variety of risk-related data and known environmental factors. The rating will inform the appropriate GTE assessment action taken by the Admissions office.</description>
        <inlineHelpText>The Monash GTE risk rating based on a variety of risk-related data</inlineHelpText>
        <label>GTE Risk Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Course start date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Encumbrance__c.object
<CustomObject>
    <description>Links an Encumbrace to a Contact</description>
    <label>Encumbrance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encumbrance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Overseas__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overseas</label>
        <type>Checkbox</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <displayFormat>QUAL-{000}</displayFormat>
        <label>Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/asmAlertsApplicationCC_Test.cls
@isTest(isParallel=true)
private class asmAlertsApplicationCC_Test {
    
    TestMethod
    static void test_NoApplicationId()
    {
        Map<String, Object> mapAlerts = asmAlertsApplicationCC.GetApplicationAlerts(null);
        System.Debug('asmAlertsApplicationCC_Test:test_NoApplicationId:' + mapAlerts);
        System.assertNotEquals('', mapAlerts.get(asmAlertsApplicationCC.MESSAGE));
    }
    
    TestMethod
    static void test_ApplicationNotFound()
    {
        Contact c = new Contact();
        c.FirstName = 'Tester';
        c.LastName = 'Surname';
        insert c;
        
        // search for a bad id
        Map<String, Object> mapAlerts = asmAlertsApplicationCC.GetApplicationAlerts(c.Id);
        System.Debug('asmAlertsApplicationCC_Test:test_ApplicationNotFound:' + mapAlerts);
        System.assertNotEquals('', mapAlerts.get(asmAlertsApplicationCC.MESSAGE));
    }
    
    TestMethod
    static void test_NoAlerts()
    {
        //Create a new Contact for testing
        Contact c = StudFirst_TestHelper.createApplicant();
        c.Citizenship__c = MyApplicationUtilities.DOMESTIC;
        
        Date dtToday = Date.today();
        c.Birthdate = dtToday.addYears(-20);
        insert c;
        
        // create application for contact
        Application__c app = StudFirst_TestHelper.createApplication(c.Id);
        app.Fee_Payment__c = true;
        insert app;
        // create course
        Course__c course = StudFirst_Testhelper.createCourse();
        insert course;        
        // create course offering
        Course_Offering__c courseOffering = StudFirst_TestHelper.createCourseOffering(course);
        insert courseOffering;                
        // create ACP
        Application_Course_Preference__c acp = StudFirst_TestHelper.createCoursePreferences(app, c, courseOffering, course);
        insert acp;        
        // test function
        Map<String, Object> mapAlerts = asmAlertsApplicationCC.GetApplicationAlerts(app.Id);
        System.Debug('asmAlertsApplicationCC_Test:test_NoAlerts:' + mapAlerts);
        
        // under 18
        Boolean under18AtApplication = (Boolean) mapAlerts.get(asmAlertsApplicationCC.IS_UNDER18_AT_APPLICATION);
        System.assertNotEquals(true, under18AtApplication);                
        // encumbrances
        Boolean hasEncumbrance = (Boolean) mapAlerts.get(asmAlertsApplicationCC.HAS_ENCUMBRANCES);
        System.assertNotEquals(true, hasEncumbrance);                
        // access equity
        Boolean accessEquity = (Boolean) mapAlerts.get(asmAlertsApplicationCC.HAS_ACCESS_EQUITY);
        System.assertNotEquals(true, accessEquity);        
        
        // fee paid
        Boolean feePaid = (Boolean) mapAlerts.get(asmAlertsApplicationCC.APPLICATION_FEE_PAID);
        System.assertEquals(true, feePaid);        
        
        // GTE location
        Boolean gteLocation = (Boolean)  mapAlerts.get(asmAlertsApplicationCC.GTE_ALERT_SUBMISSION_LOCATION);
        System.assertNotEquals(true, gteLocation);                    
        
        // GTE qualification
        Boolean gteQualification = (Boolean)  mapAlerts.get(asmAlertsApplicationCC.GTE_ALERT_QUALIFICATION);
        System.assertNotEquals(true, gteQualification);                    
        
        // Credit Intention
        Boolean creditIntention = (Boolean) mapAlerts.get(asmAlertsApplicationCC.CREDIT_INTENTION);
        System.assertNotEquals(true, creditIntention);        
    }

    TestMethod
    static void test_AllAlerts()
    {
        //Create a new Contact for testing
        Contact c = StudFirst_TestHelper.createApplicant();
        c.Citizenship__c = MyApplicationUtilities.DOMESTIC;
        
        Date dtToday = Date.today();
        // for under 18
        c.Birthdate = dtToday.addYears(-5);
        insert c;
        
        // create Country Attribute Object
        Country_Attribute__c countryAttr = StudFirst_TestHelper.createGTERiskCountryAttribute();
        countryAttr.GTE_Risk_Rating__c = '3';                
        insert countryAttr;
        
        // create application for contact
        Application__c app = StudFirst_TestHelper.createApplication(c.Id);
        
        // GTE submission location
        app.Submission_Location_Country__c = countryAttr.id;
        // for fee payment alert
        app.Fee_Payment__c = false;        
        // for application age alert
        app.Submitted_Date__c = dtToday;
        // for credit intention
        app.Credit_Intention__c = true;
        // for access/equity
        app.Access_and_Equity_Question__c = 'Yes';
        insert app;
        
        // create course
        Course__c course = StudFirst_Testhelper.createCourse();
        insert course;        
        // create course offering
        Course_Offering__c courseOffering = StudFirst_TestHelper.createCourseOffering(course);
        // for course age alert
        courseOffering.Start_Date__c = dtToday;
        insert courseOffering;                
        // create ACP
        Application_Course_Preference__c acp = StudFirst_TestHelper.createCoursePreferences(app, c, courseOffering, course);
        
        insert acp;        
        
		// create an admin encumbrance
        Encumbrance__c enc = StudFirst_TestHelper.createEncumbranceAdmin(c.id);
        insert enc;       
        
        // create GTE risk qualification
        Qualification__c qualification = StudFirst_TestHelper.createTertiaryQualification();
        qualification.Overseas__c = true;        
        insert qualification;
        Contact_Qualification__c cq = StudFirst_TestHelper.createContactQualification(c, qualification, 'Tertiary Education');
        cq.Qualification_Country__c = countryAttr.id;
        insert cq;
        
        
        // test function
        Map<String, Object> mapAlerts = asmAlertsApplicationCC.GetApplicationAlerts(app.Id);
        System.Debug('asmAlertsApplicationCC_Test:test_AllAlerts:' + mapAlerts);
        
        // under 18
        Boolean under18AtApplication = (Boolean) mapAlerts.get(asmAlertsApplicationCC.IS_UNDER18_AT_APPLICATION);
        System.assertEquals(true, under18AtApplication);                
        // encumbrances
        Boolean hasEncumbrance = (Boolean) mapAlerts.get(asmAlertsApplicationCC.HAS_ENCUMBRANCES);
        System.assertEquals(true, hasEncumbrance);                
        // access equity
        Boolean accessEquity = (Boolean) mapAlerts.get(asmAlertsApplicationCC.HAS_ACCESS_EQUITY);
        System.assertEquals(true, accessEquity);        
        
        // fee paid
        Boolean feePaid = (Boolean) mapAlerts.get(asmAlertsApplicationCC.APPLICATION_FEE_PAID);
        System.assertNotEquals(true, feePaid);        
        
        // GTE location
        // Boolean gteLocation = (Boolean)  mapAlerts.get(asmAlertsApplicationCC.GTE_ALERT_SUBMISSION_LOCATION);
        // System.assertEquals(false, gteLocation);                    
        
        // GTE qualification
        Boolean gteQualification = (Boolean)  mapAlerts.get(asmAlertsApplicationCC.GTE_ALERT_QUALIFICATION);
        System.assertEquals(true, gteQualification);                    
        
        // Credit Intention
        Boolean creditIntention = (Boolean) mapAlerts.get(asmAlertsApplicationCC.CREDIT_INTENTION);
        System.assertEquals(true, creditIntention);        
    }
    
}