force-app/main/default/objects/Application__c.object
<CustomObject>
    <description>A parent object for application course preferences, carrying admission application level attributes</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to the contact record of the Applicant</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>a checkbox to determine whether the Application is from the my.app portal or from Callista migration.</description>
        <inlineHelpText>a checkbox to determine whether the Application is from the my.app portal or from Callista migration.</inlineHelpText>
        <label>From Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Sent for Submission</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Registered - Not paid</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Data Validation Ready</fullName>
                </value>
                <value>
                    <fullName>Failed Data validation</fullName>
                </value>
                <value>
                    <fullName>Submission on Hold (Duplicate Contact)</fullName>
                </value>
                <value>
                    <fullName>Agent Declaration Accepted</fullName>
                </value>
                <value>
                    <fullName>Sent Draft Application to Applicant</fullName>
                </value>
                <value>
                    <fullName>Applicant Declaration Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Work_Experience_Provided__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Work Experiences Provided</relationshipLabel>
        <relationshipName>Application_Work_Experiences_Provided</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Experience__c</fullName>
        <label>Work Experience</label>
        <referenceTo>Work_Experience__c</referenceTo>
        <relationshipLabel>Application Provided On</relationshipLabel>
        <relationshipName>Application_Work_Experiences_Provided</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Work Experience Provided</label>
    <nameField>
        <displayFormat>AWEP-{000000}</displayFormat>
        <label>App. Work Experience Provided Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Work Experiences Provided</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Experience__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Work Experiences</relationshipLabel>
        <relationshipName>Work_Experiences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Work Experience</label>
    <nameField>
        <displayFormat>WEX-{000000}</displayFormat>
        <label>Work Experience ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ApplicationNavigationHomeController.cls
/**
 * @author Trent De Laney
 * @date 21 Feb 2019 at 3:33:55 pm
 * @group AuraController
 * @description Used to manage the front page of my.app and its associated "new application" functions.
 */
public with sharing class ApplicationNavigationHomeController {

    /********************************************************
    Internal Wrappers
    ********************************************************/
    /**
     * @author Trent De Laney
     * @date 21 Feb 2019 at 3:33:13 pm
     * @group Wrappers
     * @description Used for easy parsing on the Aura front end
     */
    public class AppStatusWrapper {
        public String appId;
        public String acpId;
        public String status;

        public AppStatusWrapper(String applicationId, String appStatus) {
            appId = applicationId;
            status = appStatus;
        }
    }

    public static final User userRecord = [
            SELECT Id, ContactId,
                    App_Salutation__c,
                    LastName,
                    App_Gender__c,
                    App_Birthdate__c,
                    Email,
                    App_Residency_Status__c,
                    Street,
                    City,
                    App_Address_Type__c,
                    State,
                    PostalCode,
                    MobilePhone,
                    Phone,
                    Country,
                    App_Home_Phone__c
            FROM User
            WHERE Id = :userInfo.getUserId()
            AND IsPortalEnabled = TRUE
    ];

    /********************************************************
    AURA FUNCTIONS
    ********************************************************/

    /**
    * @author Trent De Laney
    * @description Creates a new application in my.app portal
    * @date 21 Feb 2019 at 3:28:52 pm
    * @return String (appId)
    */
    @AuraEnabled
    public static String CreateApplication() {
        Application__c applicationRecord = new Application__c();
        applicationRecord.Applicant__c = userRecord.ContactId;
        String returnValue = '';
        try {
            List<Application__c> apps = [
                    SELECT Id
                    FROM Application__c
                    WHERE Status__c = 'Draft' AND Applicant__c = :userRecord.ContactId
            ];

            if (apps.size() > 0) {
                throw new AuraHandledException('You may only have 1 Application at a time');
            } else {
                applicationRecord.From_Portal__c = true; //R.Wilson added indicator for Callista Migration.
                applicationRecord.Status__c = 'Draft'; //R.Wilson added default status for PD merge.
                applicationRecord.Source_System__c = 'my.app';
                insert applicationRecord;

                //insert junction object records if there are any
                InsertChildRecords(applicationRecord.Id, userRecord.ContactId);

                returnValue = applicationRecord.Id;
            }

        } catch (Exception ex) {
            ExLog.add('Application Navigation Controller', '', ex.getMessage(), '');
            throw new AuraHandledException('Unable to update your details: ' + ex.getMessage());
        }
        return returnValue;
    }

    /**
    * @author Trent De Laney
    * @description Checks to see if the user has any drafts, if they do, don't allow record creation
    * @date 21 Feb 2019 at 3:29:39 pm
    * @return Boolean
    */
    @AuraEnabled
    public static Boolean HasDrafts() {
        List<Application__c> apps = [
                SELECT Id
                FROM Application__c
                WHERE Status__c = 'Draft' AND Applicant__c = :userRecord.ContactId
        ];

        if (apps.size() > 0) {
            return true;
        } else {
            return false;
        }
    }

    /**
    * @author Trent De Laney
    * @description Edits the application and navigates the user to the appropriate page in my.app
    * @date 21 Feb 2019 at 3:31:21 pm
    * @return String appStatus
    */
    @AuraEnabled
    public static String EditApplication() {
        List<Application__c> apps = [
                SELECT Id
                FROM Application__c
                WHERE Status__c = 'Draft' AND Applicant__c = :userRecord.ContactId
        ];

        if (apps.size() > 0) {
            String appId = apps[0].Id;
            String stat = MyApplicationUtilities.getApplicationStatusByAppId(appId);

            return JSON.serialize(new AppStatusWrapper(appId, stat));
        } else {
            throw new AuraHandledException('Cannot edit application as there are no drafts');
        }
    }

    /********************************************************
    PRIVATE FUNCTIONS
    ********************************************************/
    /**
    * @author Trent De Laney
    * @description Inserts the child records for previous applications to ensure they are linked for future submissions
    * @date 21 Feb 2019 at 3:32:12 pm
    * @param String appId, String contactId
    */
    private static void InsertChildRecords(String appId, String contactId) {
        //Get all work exp
        List<Work_Experience__c> workExp = [
                SELECT Id
                FROM Work_Experience__c
                WHERE Contact__c = :contactId
        ];

        if(workExp.size() > 0){
            //Create the new list to be inserted
            List<Application_Work_Experience_Provided__c> appWorkExp = new List<Application_Work_Experience_Provided__c>();
            for (Work_Experience__c work : workExp){
                Application_Work_Experience_Provided__c newAppWork = new Application_Work_Experience_Provided__c();
                newAppWork.Work_Experience__c = work.Id;
                newAppWork.Application__c = appId;
                appWorkExp.add(newAppWork);
            }

            insert appWorkExp;
        }
    }
}