force-app/main/default/objects/ASN_Teaching_Periods__mdt.object
<CustomObject>
    <description>Custom metadata type to maintain the Teaching periods group wise collection of the CI sequence numbers</description>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <description>Academic year configuration which is used to filter Unit Attempts</description>
        <label>Academic Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_CI_Sequence_Numbers__c</fullName>
        <description>To group CI sequence numbers</description>
        <label>Group CI Sequence Numbers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Location value where the teaching period is eligible for ASN submission</description>
        <inlineHelpText>Location value where the teaching period is exclusively eligible for ASN submission. (Wherein, null = any.)</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teaching_Period__c</fullName>
        <description>The teaching period which groups some CI sequence numbers</description>
        <label>Teaching Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ASN Teaching Periods</label>
    <pluralLabel>ASN Teaching Period</pluralLabel>
</CustomObject>

force-app/main/default/objects/Calendar__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Calendar Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <externalId>true</externalId>
        <label>Sequence Number</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Calendar Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Calendar</label>
    <nameField>
        <label>Calendar</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Title__c</fullName>
        <description>Course full title</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of course being offered</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Academic_Course</fullName>
                    <label>Academic Course</label>
                </value>
                <value>
                    <fullName>Short_Course</fullName>
                    <label>Professional Development</label>
                </value>
                <value>
                    <fullName>Course-All</fullName>
                </value>
                <value>
                    <fullName>Unit Set</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attempt__c.object
<CustomObject>
    <description>Course attempt represents the courses a Contact is related to.</description>
    <fields>
        <fullName>Achieved_Credit_Points__c</fullName>
        <description>Total credit points achieved</description>
        <inlineHelpText>Total credit points achieved</inlineHelpText>
        <label>Achieved CP</label>
        <summarizedField>Unit_Attempt__c.Achieved_Credit_Points__c</summarizedField>
        <summaryFilterItems>
            <field>Unit_Attempt__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed, Duplicate</value>
        </summaryFilterItems>
        <summaryForeignKey>Unit_Attempt__c.Course_Attempt__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Callista_External_Id__c</fullName>
        <description>Holds a concatenation of the Callista Person Id (from &apos;Contact.Person_Id_unique__c&apos;), and underscore(&apos;_&apos;), and the Course Code (from &apos;Course__c.Name&apos;). This is a unique combination (for academic courses).</description>
        <externalId>true</externalId>
        <inlineHelpText>This field is evaluated and set by the system.</inlineHelpText>
        <label>Callista_External_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to the course (incl. version) of the course attempt</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Value does not match the type of allowed courses an attempt record can be related to.</errorMessage>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Course-All</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short Course</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short_Course</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Attempts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Encumbrance__c.object
<CustomObject>
    <description>Links an Encumbrace to a Contact</description>
    <fields>
        <fullName>eff_type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAD-QUALS</fullName>
                </value>
                <value>
                    <fullName>ADM-ALERT</fullName>
                </value>
                <value>
                    <fullName>ATO-QRY</fullName>
                </value>
                <value>
                    <fullName>BLK-AD-MSA</fullName>
                </value>
                <value>
                    <fullName>BLK-COM-ST</fullName>
                </value>
                <value>
                    <fullName>BLK-EDSOA</fullName>
                </value>
                <value>
                    <fullName>BLK-FINAID</fullName>
                </value>
                <value>
                    <fullName>BLK-FN</fullName>
                </value>
                <value>
                    <fullName>BLK-HECS</fullName>
                </value>
                <value>
                    <fullName>BLK-MC-GEN</fullName>
                </value>
                <value>
                    <fullName>BLK-MISC-1</fullName>
                </value>
                <value>
                    <fullName>BLK-MUM-VS</fullName>
                </value>
                <value>
                    <fullName>BLK-NO-HEC</fullName>
                </value>
                <value>
                    <fullName>BLK-NO-PTB</fullName>
                </value>
                <value>
                    <fullName>BLK-OLA</fullName>
                </value>
                <value>
                    <fullName>BLK-OLA-MU</fullName>
                </value>
                <value>
                    <fullName>BLK-OSP</fullName>
                </value>
                <value>
                    <fullName>BLK-PPLAN</fullName>
                </value>
                <value>
                    <fullName>BLK-SCHOL1</fullName>
                </value>
                <value>
                    <fullName>BLK-SCHOL2</fullName>
                </value>
                <value>
                    <fullName>BLK-SF-MSA</fullName>
                </value>
                <value>
                    <fullName>BLK-SF-SUN</fullName>
                </value>
                <value>
                    <fullName>BLK-SPNS2</fullName>
                </value>
                <value>
                    <fullName>BLK-SSAF</fullName>
                </value>
                <value>
                    <fullName>BLK-STDFIN</fullName>
                </value>
                <value>
                    <fullName>BLK-SUS-FC</fullName>
                </value>
                <value>
                    <fullName>BLK-TFN</fullName>
                </value>
                <value>
                    <fullName>BLOCK-CBK</fullName>
                </value>
                <value>
                    <fullName>BLOCK-DEF</fullName>
                </value>
                <value>
                    <fullName>BLOCK-DISC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Encumbrance</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encumbrance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Attempt__c.object
<CustomObject>
    <description>Unit (Subject) enrolment of the student.</description>
    <fields>
        <fullName>ASN_Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System field for excluding unit attempts from the ASN form.</description>
        <inlineHelpText>A flag for specifically excluded unit attempts.</inlineHelpText>
        <label>ASN Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <description>The academic year which the unit is attempted (started) in.</description>
        <label>Academic Year</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Achieved_Credit_Points__c</fullName>
        <description>Credit points granted if the unit attempt was passed</description>
        <label>Achieved Credit Points</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CI_Sequence_Number__c</fullName>
        <description>Calendar sequence number</description>
        <label>CI Sequence Number</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calendar_Type__c</fullName>
        <description>Type of the academic calendar associated with the unit attempt. This is referrenced in forming the External ID of Unit Attempt.</description>
        <label>Calendar Type</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <description>Parent course attempt which the unit attempt is associated with.</description>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Unit Attempts</relationshipLabel>
        <relationshipName>Unit_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <description>Grade/Result given to the student on completed unit attempt.</description>
        <label>Result</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Teaching location code of the unit attempt.</description>
        <label>Location</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Student attemtping this specific unit attempt.</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Unit Attempts</relationshipLabel>
        <relationshipName>Unit_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teaching_Period__c</fullName>
        <label>Teaching Period</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Unit Title</description>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Code__c</fullName>
        <description>Code of the attempted unit.</description>
        <label>Unit Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Mode__c</fullName>
        <label>Unit Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit_Class__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ON</fullName>
                    <label>ON CAMPUS</label>
                </value>
                <value>
                    <fullName>OFF</fullName>
                    <label>OFF CAMPUS</label>
                </value>
                <value>
                    <fullName>COMPOSITE</fullName>
                    <label>ON/OFF CAMPUS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ASNController_Test.cls
@isTest
private class ASNController_Test {
    private final static String PERSON_ID = '12345678';
    private final static String COURSE_CODE = 'CODE01';

    @testSetup static void dataSetup() {

        // Disable some of the automation that occurs when contacts are created
        triggerCommon.disableTrigger('Contact');
        ucinn_ascendv2__Trigger_Handler__c disableEngageTrig = new ucinn_ascendv2__Trigger_Handler__c(ucinn_ascendv2__Object__c ='Contact',ucinn_ascendv2__Is_Active__c=False,ucinn_ascendv2__class__c='ascend_TRIG_Contact');
        insert disableEngageTrig;

        //create contact
        Contact con = TestHelper.createOrphanContactRecords(1)[0];
        con.LastName = 'ASNController';
        con.Person_ID_unique__c =PERSON_ID;
        con.SAP_Staff_Id__c = 'NoDupRules'; // this will filter the contact out of the most of the duplicate rules
        insert con;
        System.assertEquals(1, [SELECT COUNT() FROM Contact], 'An error occurred while creating setup Contact');

        String enchklbl = Label.ASN_Encumbrance_Check;
        List<String> effTypeList = new List<String>();
        if(String.isNotBlank(enchklbl))
        {
            effTypeList =  enchklbl.split(',');
        }
         // create an admin encumbrance
         Encumbrance__c enc = StudFirst_TestHelper.createEncumbranceAdmin(con.id);
         enc.eff_type__c = effTypeList[0];
         insert enc;

        //create course
        Course__c courseRec = TestHelper.createCoursesWithType(1, 'Course-All')[0];
        courseRec.Name = COURSE_CODE;
        insert courseRec;
        System.assertEquals(1, [SELECT COUNT() FROM Course__c], 'An error occurred while creating setup Course');

        //create course attempt
        Course_Attempt__c ca = TestHelper.createCourseAttempts(1, con.Id, courseRec.Id)[0];
        ca.Callista_External_Id__c = PERSON_ID + '_' + COURSE_CODE;
        insert ca;
        System.assertEquals(1, [SELECT COUNT() FROM Course_Attempt__c], 'An error occurred while creating setup Course Attempt');

        //create org unit
        Account ou = new Account(Callista_Org_Unit_Code__c = 'OrgUnitCode', name = 'Test Faculty', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Faculty').getRecordTypeId());
        insert ou;

        //create calendar
        Calendar__c cal = new Calendar__c(name='TestCalendar', sequence_number__c = 0001, Description__c = 'Hello',Type__c = '');
        insert cal;
        
        List<ASN_Teaching_Periods__mdt> mdt = [SELECT Teaching_Period__c,Academic_Year__c,Group_CI_Sequence_Numbers__c FROM ASN_Teaching_Periods__mdt WHERE Location__c = NULL];

        //create unit attempt for 'update' and 'delete' scenario
        Unit_Attempt__c ua = TestHelper.createUnitAttempts(1, ca.Id, con.Id)[0];
        ua.Unit_Code__c = 'ATS2560';
        ua.Academic_Year__c = '2018';
        ua.Unit_Mode__c = 'ON CAMPUS';
        ua.Calendar_Type__c = 'ADM-2';
        ua.CI_Sequence_Number__c = mdt[0].Group_CI_Sequence_Numbers__c.split(',')[0];
        ua.Teaching_Period__c = '2';
        ua.Student__c = con.Id;
        ua.Achieved_Credit_Points__c = 22;
        ua.Title__c = 'Nursing';
        ua.Grade__c = 'C';
        ua.ASN_Exclude__c = false;
        ua.Teaching_Calendar__c  = cal.Id;
     

        insert ua;
        System.assertEquals(1, [SELECT COUNT() FROM Unit_Attempt__c], 'An error occurred while creating setup Unit Attempt');
    }
    
    @isTest
    public static void testRetrieveTPAndUpdate()
    {
        User applicant = StudFirst_TestHelper.createCommunityUser();
        Contact con = [Select Id,LastName,FirstName,Email from Contact where Person_ID_unique__c='12345678' and LastName = 'ASNController'];
        System.runAs(applicant)
        {
            List<TeachingPeriod> tpList = ASNController.retrieveStudentTeachingPeriods(con.Id);
            tpList[0].studentUpdated = true;
            System.assert( tpList.size()>0);
            
            Boolean isSuccess = ASNController.updateUnitAttempts(tpList[0], con);
            // System.assertEquals(true , isSuccess); 
         }

    }

    @isTest
    public static void testRetriveConAndEnc()
    {
        User applicant = StudFirst_TestHelper.createCommunityUser();
        Contact con = [Select Id,LastName,FirstName,Email from Contact where Person_ID_unique__c='12345678' and LastName = 'ASNController'];
        System.runAs(applicant)
        {
            Contact retCon = ASNController.retrieveUserContact(applicant.Id);
            System.assert(retCon!=null);
            Boolean chkEnc = ASNController.checkEncumbrance(con.Id);
            System.assert(retCon!=null);
        }

    }
   
}