force-app/main/default/objects/Async_Process__e.object
<CustomObject>
    <description>Generic platform event that handles invocation of any Apex Class that implements IPlatformEventInvocable</description>
    <fields>
        <fullName>Parameter__c</fullName>
        <description>Parameter of the class to be invoked</description>
        <label>Parameter</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <description>Apex Class name to be invoked</description>
        <label>Process Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Async Process</label>
    <pluralLabel>Async Processes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Feature_Switch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Allow features to be enabled or disabled based on a Boolean switch</description>
    <fields>
        <fullName>Graduate_Research_Integration__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Toggle for Graduate Research API callouts</description>
        <label>Graduate Research Integration</label>
        <type>Checkbox</type>
    </fields>
    <label>Feature Switch</label>
</CustomObject>

force-app/main/default/classes/GRInvocablePostDocumentService.cls
/*******************************************************************************
    * @author       Sethu Venna
    * @date         05/10/2024
    * @description  This is invoked from a Process builder on Contact document object post application
    * submission
    * @revision     05/10/2024 - Initial Version
    *               7/11/2024  - Updated the feature switch for Grad Research Integration
*******************************************************************************/
public class GRInvocablePostDocumentService {
    /*******************************************************************************
    * @author       Sethu Venna
    * @date         05/10/2024
    * @param        contactDocIdList
    * @description  Invocable method from Contact Document Post Application Submission
    * to fire an Apex scheduler to submit documents post application submission
    * @revision     05/10/2024 - Initial Version
    *               7/11/2024  - Updated the feature switch for Grad Research Integration
    *******************************************************************************/
     @InvocableMethod
     public static void queueFileToSend(List<Id> contactDocIdList)
     {
         try
         {
             Feature_Switch__c fs = Feature_Switch__c.getInstance();
             if(!fs.Graduate_Research_Integration__c) {
                 return;//execute the integration only if the feature switch is turned on
             }
             for(Id conDocId : contactDocIdList)
             {
                 AsyncProcessPayload payload = new AsyncProcessPayload();
                 payload.put ('conDocId', conDocId);
                 Async_Process__e evt = new Async_Process__e (
                     Process_Name__c = 'ApplicationService.GRSendDocToCallistaPlatformEventService',
                     Parameter__c = payload.serialize()
                 );
                 EventBus.publish(evt);
             }
         }
         catch(Exception ex)
         {
             Nebula.Logger.error(ex.getMessage(), ex);
         }
         Nebula.Logger.saveLog();
     }
 }