force-app/main/default/objects/Bulk_Data_Processing__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bulk Data Processing</relationshipLabel>
        <relationshipName>Bulk_Data_Processing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipName>Offer_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Course_Campus__c</fullName>
        <label>Current Course Campus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Course_Code__c</fullName>
        <label>Current Course Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Condition__c</fullName>
        <label>Offer Condition</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Offer_Template__c</fullName>
        <label>Offer Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Student ID</inlineHelpText>
        <label>Person ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the offer request record assessment</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Review Required</fullName>
                </value>
                <value>
                    <fullName>Ready for Offer</fullName>
                </value>
                <value>
                    <fullName>Generate Offer</fullName>
                </value>
                <value>
                    <fullName>Processing Offer</fullName>
                </value>
                <value>
                    <fullName>Offer Error</fullName>
                </value>
                <value>
                    <fullName>Offer Created</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transfer_Admission_Category__c</fullName>
        <label>Transfer Admission Category</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transfer_Calendar__c</fullName>
        <externalId>true</externalId>
        <label>Transfer Calendar</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transfer_Course_Campus__c</fullName>
        <externalId>true</externalId>
        <label>Transfer Course Campus</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transfer_Course_Code__c</fullName>
        <externalId>true</externalId>
        <label>Transfer Course Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transfer_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfer To</label>
        <referenceTo>Application_Course_Preference__c</referenceTo>
        <relationshipName>Offer_Request1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transfer_Unit_Set__c</fullName>
        <externalId>true</externalId>
        <label>Transfer Unit Set</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Bulk Data Processing</label>
    <nameField>
        <displayFormat>BDP-{0000000}</displayFormat>
        <label>Transfer Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Data Processing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PLANNED</fullName>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calendar</label>
    <nameField>
        <label>Calendar</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BDPFilterService.cls
/**
 * Filter service class used in trigger evaluation for Bulk Data Processing object.  
 * @author David Browaeys
 * @group Bulk Data Processing
 */
public inherited sharing class BDPFilterService {
    @TestVisible private BDPFilterService(){}
    /**
     * Evaluate if record meet BDPFieldUpdateService criteria
     * @param  newRec new bdp state record
     * @param  oldRec old bdp state record
     * @return        true if meet criteria
     */
    public static Boolean meetBDPFieldUpdateService(Bulk_Data_Processing__c newRec,  Bulk_Data_Processing__c oldRec){
        return 	newRec.Calendar__c == null || newRec.Applicant__c == null || 
                    (oldRec != null && newRec.Person_ID__c != oldRec.Person_ID__c) || 
                    (oldRec != null && newRec.Transfer_Calendar__c != oldRec.Transfer_Calendar__c);
    }
    /**
     * Evaluate if record meet BDPCourseOfferingMatchingService criteria
     * @param  newRec new bdp state record
     * @param  oldRec old bdp state record
     * @return        true if meet criteria
     */
    public static Boolean meetBDPCourseOfferingMatchingService(Bulk_Data_Processing__c newRec,  Bulk_Data_Processing__c oldRec){
        return (newRec.Status__c == BDPConstants.BDP_NEW || newRec.Status__c == BDPConstants.REVIEW_REQUIRED) && newRec.Transfer_To__c == null &&
                        (oldRec == null || 
                        newRec.Transfer_Course_Code__c != oldRec.Transfer_Course_Code__c || 
                        newRec.Transfer_Course_Campus__c != oldRec.Transfer_Course_Campus__c ||
                        newRec.Transfer_Admission_Category__c != oldRec.Transfer_Admission_Category__c ||
                        newRec.Transfer_Calendar__c != oldRec.Transfer_Calendar__c ||
                        newRec.Transfer_Unit_Set__c != oldRec.Transfer_Unit_Set__c);
    }
    /**
     * Evaluate if record meet ACPMatchingService criteria
     * @param  newRec new bdp state record
     * @param  oldRec old bdp state record
     * @return        true if meet criteria
     */
    public static Boolean meetACPMatchingService(Bulk_Data_Processing__c newRec,  Bulk_Data_Processing__c oldRec){
        return newRec.Transfer_To__c != null && newRec.Transfer_To__c != oldRec.Transfer_To__c;
    }
    /**
     * Evaluate if record meet OfferTemplate criteria
     * @param  newRec new bdp state record
     * @param  oldRec old bdp state record
     * @return        true if meet criteria
     */
    public static Boolean meetOfferTemplateMatchingService(Bulk_Data_Processing__c newRec,  Bulk_Data_Processing__c oldRec){
        return newRec.Offer_Template__c != oldRec.Offer_Template__c;
    }
    /**
     * Evaluate if record meet BDPFetchOldACPService crtieria
     * @param  newRec new bdp state record
     * @param  oldRec old bdp state record
     * @return        true if meet criteria
     */
    public static Boolean meetBDPFetchOldACPService(Bulk_Data_Processing__c newRec,  Bulk_Data_Processing__c oldRec){
        return  (newRec.Status__c == BDPConstants.BDP_NEW || newRec.Status__c == BDPConstants.REVIEW_REQUIRED) && newRec.Current_Course_Code__c != null  && 
                    (oldRec == null || 
                    newRec.Applicant__c != oldRec.Applicant__c ||
                    newRec.Person_ID__c != oldRec.Person_ID__c || 
                    newRec.Current_Course_Code__c != oldRec.Current_Course_Code__c ||
                    newRec.Current_Course_Campus__c != oldRec.Current_Course_Campus__c);
    }

    /**
     * Evaluate if BDP's offer condition value has been changed
     * @param  newRec new bdp state record
     * @param  oldRec old bdp state record
     * @return Returns true if the offer condition has been changed
     */
    public static Boolean isOfferConditionChanged(Bulk_Data_Processing__c newRec,  Bulk_Data_Processing__c oldRec) {
        return (oldRec.Offer_Condition__c != newRec.Offer_Condition__c);
    }

    /**
     * Evaluate if BDP has a transfer to ACP
     * @param  bdp The Bulk Data Processing record
     * @return Returns true if the BDP record has a transfer to ACP
     */
    public static Boolean hasTransferToAcp(Bulk_Data_Processing__c bdp) {
        return bdp.Transfer_To__c != null;
    }
}