force-app/main/default/objects/Calendar__c.object
<CustomObject>
    <fields>
        <fullName>Calendar_Code__c</fullName>
        <description>Field created to get the details from callista</description>
        <externalId>true</externalId>
        <label>Calendar Code</label>
        <length>13</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PLANNED</fullName>
                </value>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calendar</label>
    <nameField>
        <label>Calendar</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Graduation_Application__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Reqs_Description_Graduand__c</fullName>
        <description>Graduands additional requirements free text</description>
        <label>Additional Reqs Description - Graduand</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Reqs_Description_Guest__c</fullName>
        <description>Guests additional requirements free text</description>
        <label>Additional Reqs Description - Guest</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Reqs_Graduand__c</fullName>
        <description>Graduands selected additional requirements</description>
        <label>Additional Reqs - Graduand</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auslan</fullName>
                </value>
                <value>
                    <fullName>Aisle seating</fullName>
                </value>
                <value>
                    <fullName>Wheelchair access</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Additional_Reqs_Guest__c</fullName>
        <description>Guests selected additional requirements</description>
        <label>Additional Reqs - Guest</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auslan</fullName>
                </value>
                <value>
                    <fullName>Aisle seating</fullName>
                </value>
                <value>
                    <fullName>Wheelchair access</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_Writeback_Pending__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When true, the next writeback will also trigger a document writeback</description>
        <label>Document Writeback Pending</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Graduation_Calendar__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Calendar representing the Graduation period</description>
        <label>Graduation Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Graduation Applications</relationshipLabel>
        <relationshipName>Graduation_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Comments__c</fullName>
        <description>Comments from staff</description>
        <label>Staff Comments</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current state of Application</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Internal Draft</fullName>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Person_Id__c</fullName>
        <description>Contact&apos;s Student ID</description>
        <formula>Student__r.Person_ID_unique__c</formula>
        <label>Student Person Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Personal_Email__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <description>Personal email of the student as entered on form</description>
        <label>Student Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Student_Testamur_Name_Change_Status__c</fullName>
        <description>Current state of the name change request</description>
        <label>Student Testamur Name Change Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Testamur_Name__c</fullName>
        <complianceGroup>PII</complianceGroup>
        <description>Student name as it will appear on the testamur</description>
        <label>Student Testamur Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Student contact associated with the Application</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Graduation Applications</relationshipLabel>
        <relationshipName>Graduation_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <description>Ensure that duplicate applications can&apos;t exist for a student</description>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Graduation Application</label>
    <nameField>
        <displayFormat>GAPP-{0000000}</displayFormat>
        <label>Graduation Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduation Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Graduation_Award__c.object
<CustomObject>
    <fields>
        <fullName>Bypass_Writeback_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, a platform event won&apos;t be fired when a watched field changes. Automatically cleared on writeback</description>
        <label>Bypass Writeback Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Callista_Writeback_Requested_Time__c</fullName>
        <description>Time of change that has triggered a writeback</description>
        <label>Callista Writeback Requested Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <description>Date the award was cancelled</description>
        <label>Cancellation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Cancellation_Succeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the cancellation request successfully posted to Callista</description>
        <label>Cancellation Succeeded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Graduation_Application__c</fullName>
        <description>Parent Graduation Application</description>
        <label>Graduation Application</label>
        <referenceTo>Graduation_Application__c</referenceTo>
        <relationshipLabel>Graduation Awards</relationshipLabel>
        <relationshipName>Graduation_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff_Comments__c</fullName>
        <description>Comments from staff</description>
        <label>Staff Comments</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Student_Person_Id__c</fullName>
        <description>Person Id from the student&apos;s contact record</description>
        <formula>Graduation_Application__r.Student__r.Person_ID_unique__c</formula>
        <label>Student Person Id</label>
        <type>Text</type>
    </fields>
    <label>Graduation Award</label>
    <nameField>
        <displayFormat>GAWARD-{0000000}</displayFormat>
        <label>Graduation Award Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduation Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/GraduationApplicationTriggerHandler.cls
/**
 * @description Trigger handler for Graduation_Application__c
 * @group       Grads
 * @revision    2024-09-06 - Tom Gangemi - Initial version
 * @revision    2025-08-18 - Tom Gangemi - Set Unique Key when un-cancelling applications
 */
public with sharing class GraduationApplicationTriggerHandler {

    /**
     * Update Unique Key when application status goes to or from cancelled
     */
    public class HandleStatusChange extends TriggerAbstract {

        public override void process(SObject rec, SObject oldRec) {
            Graduation_Application__c app = (Graduation_Application__c) rec;
            Graduation_Application__c oldApp = (Graduation_Application__c) oldRec;

            if(app.Status__c != oldApp.Status__c && (oldApp.Status__c == 'Cancelled' || app.Status__c == 'Cancelled')) {
                // Status changed to or from cancelled
                records.add(app);
            }
        }

        public override void execute() {
            if(this.records.size() > 0) {
                Graduation_Application__c[] apps = this.records;

                Set<Id> calendarIds = new Set<Id>();

                for(Graduation_Application__c app : apps) {
                    if(app.Status__c == 'Cancelled') {
                        // Clear Unique Key when application is cancelled
                        app.Unique_Key__c = null;
                    } else {
                        // Collect calendars for setting Unique Key
                        calendarIds.add(app.Graduation_Calendar__c);
                    }
                }
                if(!calendarIds.isEmpty()) {
                    Map<Id,Calendar__c> calendars = new Map<Id,Calendar__c>([
                        SELECT Calendar_Code__c FROM Calendar__c WHERE Id IN :calendarIds
                    ]);
                    for(Graduation_Application__c app : apps) {
                        if(app.Status__c != 'Cancelled') {
                            // Set Unique Key if application is no longer cancelled
                            Calendar__c cal = calendars.get(app.Graduation_Calendar__c);
                            if(cal != null) {
                                // Set Unique Key to Calendar Code + Application ID
                                app.Unique_Key__c = GradsUtils.createApplicationUniqueKey(
                                    cal.Calendar_Code__c, app.Student_Person_Id__c
                                );
                            }
                        }
                    }
                }
            }
        }

    }

    /**
     * Set Student Testamur Name to Contact Legal Name when change is rejected
     */
    public class HandleNameChange extends TriggerAbstract {
        public override void process(SObject rec, SObject oldRec) {
            Graduation_Application__c app = (Graduation_Application__c) rec;
            Graduation_Application__c oldApp = (Graduation_Application__c) oldRec;

            if(app.Student_Testamur_Name_Change_Status__c != oldApp.Student_Testamur_Name_Change_Status__c &&
                app.Student_Testamur_Name_Change_Status__c == 'Rejected')
            {
                records.add(app);
            }
        }
        public override void execute() {
            if(this.records.size() > 0) {
                Graduation_Application__c[] apps = this.records;
                Id[] contactIds = new Id[0];
                for(Graduation_Application__c app : apps) {
                    contactIds.add(app.Student__c);
                }
                Map<Id,Contact> contacts = new Map<Id,Contact>([
                    SELECT First_Name__c, Last_Name__c FROM Contact WHERE Id IN :contactIds
                ]);
                for(Graduation_Application__c app : apps) {
                    Contact contact = contacts.get(app.Student__c);
                    app.Student_Testamur_Name__c = contact.First_Name__c + ' ' + contact.Last_Name__c;
                }
            }
        }
    }

    /**
     * Detect if a monitored field has changed and set Callista_Writeback_Requested_Time__c
     */
    public class DetectWriteBackRequired extends TriggerAbstract {

        final Set<SObjectField> monitoredFields = new Set<SObjectField> {
            Graduation_Application__c.Additional_Reqs_Graduand__c,
            Graduation_Application__c.Additional_Reqs_Description_Graduand__c,
            Graduation_Application__c.Additional_Reqs_Guest__c,
            Graduation_Application__c.Additional_Reqs_Description_Guest__c,
            Graduation_Application__c.Student_Testamur_Name__c,
            Graduation_Application__c.Student_Testamur_Name_Change_Status__c,
            Graduation_Application__c.Student_Personal_Email__c,
            Graduation_Application__c.Status__c,
            Graduation_Application__c.Document_Writeback_Pending__c,
            Graduation_Application__c.Graduation_Calendar__c,
            Graduation_Application__c.Staff_Comments__c
        };

        public override void process(SObject rec) {
            process(rec, null);
        }

        public override void process(SObject rec, SObject oldRec) {
            Graduation_Application__c app = (Graduation_Application__c) rec;
            Graduation_Application__c oldApp = (Graduation_Application__c) oldRec;

            if(GradsUtils.getSyncConfig().triggerEnabled != true) {
                return;
            }

            if(app.Status__c != 'Applied' && app.Status__c != 'Cancelled') {
                return;
            }

            // Detect if record is new or any monitored fields have changed
            if(oldApp == null) {
                records.add(app);
                return;
            } else {
                for(SObjectField field : monitoredFields) {
                    if(app.get(field) != oldApp.get(field)) {
                        if(field == Graduation_Application__c.Student_Testamur_Name_Change_Status__c) {
                            // Name Change Status only considered if approved or rejected
                            String ncStatus = app.Student_Testamur_Name_Change_Status__c;
                            if(ncStatus != 'Approved' && ncStatus != 'Rejected') {
                                continue;
                            }
                        }
                        if(field == Graduation_Application__c.Document_Writeback_Pending__c) {
                            // Document Writeback Pending only considered if true
                            if(!app.Document_Writeback_Pending__c) {
                                continue;
                            }
                        }

                        records.add(app);

                        return;
                    }
                }
            }
        }

        public Boolean awardIsCancelled(Graduation_Award__c award) {
            return award.Cancellation_Date__c != null && award.Cancellation_Succeeded__c;
        }

        public override void execute() {
            if(this.records.size() > 0) {
                Graduation_Application__c[] apps = this.records;

                Graduation_Award__c[] childAwards = [
                    SELECT Cancellation_Date__c, Cancellation_Succeeded__c FROM Graduation_Award__c
                    WHERE Graduation_Application__c IN :apps AND Bypass_Writeback_Trigger__c = FALSE AND
                        (Cancellation_Date__c = NULL OR Cancellation_Succeeded__c = FALSE) // Don't writeback of already cancelled awards
                ];

                for(Graduation_Award__c award : childAwards) {
                    if(!awardIsCancelled(award)) {
                        award.Callista_Writeback_Requested_Time__c = Datetime.now();
                    }
                }
                update childAwards;
            }
            Nebula.Logger.saveLog(); // Save any debug logs
        }
    }
}