force-app/main/default/objects/Case_Unit_Attempt__c.object
<CustomObject>
    <description>Junction table of Case and Unit Attempts</description>
    <fields>
        <fullName>Approval_Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True when approval email has been sent (deprecated - use Sent_Emails__c)</description>
        <label>Approval Email Sent (deprecated)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assessment_Due_Date_New__c</fullName>
        <description>Assessment Due Date (New)</description>
        <label>Assessment Due Date (New)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Emails_Sent__c</fullName>
        <label>Emails Sent</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>approved</fullName>
                </value>
                <value>
                    <fullName>eligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enquiry__c</fullName>
        <description>Links to the Case</description>
        <label>Enquiry</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Unit Attempt</relationshipLabel>
        <relationshipName>Case_Unit_Attempt</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Closed_On_Create__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be marked as true if the record is created with an approved status. This is used to report how many records were auto-approved.</description>
        <label>Is Closed On Create</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Moodle_Assessment_ID__c</fullName>
        <description>&apos;Moodle Assessment ID&apos; will now capture the Assignment ID of the specific assessment task we will attempt to update from a students live Moodle activities.</description>
        <label>Moodle Assessment ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Moodle_Integration_Status__c</fullName>
        <description>&apos;Moodle Integration Status&apos; will convey a message to confirm whether the integration update attempt to update Moodle was successful or unsuccessful.</description>
        <label>Moodle Integration Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved Extension</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Eligible &amp; Exhausted Attempts</fullName>
                </value>
                <value>
                    <fullName>Approved Alternative Assessment</fullName>
                </value>
                <value>
                    <fullName>Approved Exemption</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Unit Attempt</label>
    <nameField>
        <displayFormat>CUA{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Unit Attempt</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseUnitAttemptTriggerHandler_Test.cls
/**
 * @author     Tom Gangemi
 * @group      Test Class
 * @revision   2022-09-21 - Tom Gangemi - Initial version
 */

@isTest
public class CaseUnitAttemptTriggerHandler_Test {

    @isTest static void testSpecConOnStatusChange() {
        Case cse = new Case(
            Subject = 'Test Spec Con Existing',
            Enquiry_Type__c = 'Special Consideration',
            Status = 'Solved',
            RecordTypeId = MonConCaseServices.SPECON_RECTYPEID,
            Origin = 'Web - Monash Forms'

        );
        TriggerCommon.disableTrigger('Case');
        insert cse;
        TriggerCommon.enableTrigger('Case');

        Case_Unit_Attempt__c cua = new Case_Unit_Attempt__c(
            Enquiry__c = cse.Id,
            RecordTypeId = SpecConServices.CUA_RT_ID,
            Status__c = 'Approved',
            Emails_Sent__c = '',
            Moodle_Integration_Status__c = 'Success',
            Assessment_Due_Date_New__c = Date.today().addDays(1)
        );
        SpecConServices.setEmailSent(cua, SpecConServices.EMAIL_TYPE_APPROVED);
        insert cua;

        cua.Status__c = 'Declined';
        update cua;

        Case_Unit_Attempt__c result  = [
            SELECT Emails_Sent__c, Moodle_Integration_Status__c, Assessment_Due_Date_New__c
            FROM Case_Unit_Attempt__c WHERE Id = :cua.Id
        ];
        Assert.isNull(result.Moodle_Integration_Status__c);
        Assert.isNull(result.Emails_Sent__c);
        Assert.isNull(result.Assessment_Due_Date_New__c);
    }

    @isTest static void testSpecConUpdateCaseOutcome() {
        Case cse = new Case(
            Subject = 'Test Spec Con Existing',
            Enquiry_Type__c = 'Special Consideration',
            Status = 'Solved',
            RecordTypeId = MonConCaseServices.SPECON_RECTYPEID,
            Origin = 'Web - Monash Forms'

        );
        TriggerCommon.disableTrigger('Case');
        insert cse;
        TriggerCommon.enableTrigger('Case');

        Case_Unit_Attempt__c cua = new Case_Unit_Attempt__c(
            Enquiry__c = cse.Id,
            RecordTypeId = SpecConServices.CUA_RT_ID
        );
        insert cua;

        Test.startTest();
        cua.Status__c = 'Approved Extension';
        update cua;
        Assert.areEqual(cua.Status__c, [SELECT Case_Outcome__c FROM Case WHERE Id = :cse.Id].Case_Outcome__c);

        cua.Status__c = null;
        update cua;
        Assert.areEqual(cua.Status__c, [SELECT Case_Outcome__c FROM Case WHERE Id = :cse.Id].Case_Outcome__c);
        Test.stopTest();
    }

    @isTest static void testUpdateExistingSpecConCUAs() {
        Contact cont1 = new Contact(
            LastName = 'Test1',
            Email = 'cua.test1@example.com',
            Person_ID_unique__c = '1808'
        );
        Contact cont2 = new Contact(
            LastName = 'Test2',
            Email = 'cua.test2@example.com',
            Person_ID_unique__c = '2909'
        );
        insert new Contact[]{cont1, cont2};

        Case approvedCase = new Case(
            Subject = 'Test Spec Con Existing',
            Enquiry_Type__c = 'Special Consideration',
            Status = 'Solved',
            ContactId = cont1.Id
        );
        Case existingCase = approvedCase.clone();
        existingCase.Status = 'Open';
        Case existingCase2 = existingCase.clone();
        existingCase2.ContactId = cont2.Id;

        TriggerCommon.disableTrigger('Case');
        insert new Case[]{approvedCase, existingCase, existingCase2};
        TriggerCommon.enableTrigger('Case');

        final String moodleAssessmentId = 'SC_TEST_555';

        Case_Unit_Attempt__c approvedCua = new Case_Unit_Attempt__c(
            Enquiry__c = approvedCase.Id,
            Status__c = 'Approved Extension',
            Moodle_Assessment_ID__c = moodleAssessmentId,
            RecordTypeId = SpecConServices.CUA_RT_ID
        );
        Case_Unit_Attempt__c existingCua = new Case_Unit_Attempt__c(
            Enquiry__c = existingCase.Id,
            Moodle_Assessment_ID__c = moodleAssessmentId,
            RecordTypeId = SpecConServices.CUA_RT_ID
        );
        Case_Unit_Attempt__c existingCua2 = existingCua.clone();
        existingCua2.Enquiry__c = existingCase2.Id;

        insert new Case_Unit_Attempt__c[]{approvedCua, existingCua, existingCua2};

        Test.startTest();
        Case newCase = existingCase.clone(false);
        insert newCase;

        Case_Unit_Attempt__c newCua = new Case_Unit_Attempt__c(
            Enquiry__c = newCase.Id,
            Moodle_Assessment_ID__c = moodleAssessmentId,
            RecordTypeId = SpecConServices.CUA_RT_ID
        );
        insert newCua;
        Test.stopTest();

        Map<Id,Case_Unit_Attempt__c> result = new Map<Id,Case_Unit_Attempt__c>([
            SELECT Status__c, Enquiry__r.Status, Enquiry__r.Case_Outcome__c FROM Case_Unit_Attempt__c
        ]);
        Assert.areEqual(4, result.size());
        Case_Unit_Attempt__c approvedCuaResult = result.get(approvedCua.Id);
        Case_Unit_Attempt__c existingCuaResult = result.get(existingCua.Id);
        Case_Unit_Attempt__c existingCuaResult2 = result.get(existingCua2.Id);
        Case_Unit_Attempt__c newCuaResult = result.get(newCua.Id);

        Assert.areEqual('Approved Extension', approvedCuaResult.Status__c);
        Assert.areEqual('Solved', approvedCuaResult.Enquiry__r.Status);

        Assert.areEqual('Withdrawn', existingCuaResult.Status__c);
        Assert.areEqual('Withdrawn', existingCuaResult.Enquiry__r.Case_Outcome__c);
        Assert.areEqual('Solved', existingCuaResult.Enquiry__r.Status);

        Assert.areEqual(null, existingCuaResult2.Status__c);
        Assert.areEqual('Open', existingCuaResult2.Enquiry__r.Status);

        Assert.areEqual(null, newCuaResult.Status__c);
        Assert.areEqual('Open', newCuaResult.Enquiry__r.Status);
    }

    @isTest static void testSpecConEmails() {
        // SpecConServices_Test provides a more thorough validation of SpecConServices
        Case_Unit_Attempt__c cuaNotClosed = SpecConServices_Test.createCua();
        cuaNotClosed.RecordTypeId = SpecConServices.CUA_RT_ID;
        Case_Unit_Attempt__c cuaClosed = cuaNotClosed.clone();
        cuaClosed.Is_Closed_On_Create__c = false;
        Case_Unit_Attempt__c[] cuas = new Case_Unit_Attempt__c[]{cuaClosed, cuaNotClosed};
        insert cuas;
        cuaClosed.Is_Closed_On_Create__c = true;
        update cuas;
        Map<Id,Case_Unit_Attempt__c> results = new Map<Id,Case_Unit_Attempt__c>(
            [SELECT Emails_Sent__c, Approval_Email_Sent__c FROM Case_Unit_Attempt__c WHERE Id IN :cuas]
        );
        Assert.isFalse(SpecConServices.getEmailSent(results.get(cuaNotClosed.Id), SpecConServices.EMAIL_TYPE_APPROVED));
        Assert.isTrue(SpecConServices.getEmailSent(results.get(cuaClosed.Id), SpecConServices.EMAIL_TYPE_APPROVED));
        EmailMessage[] emailResults = [SELECT FromAddress FROM EmailMessage WHERE ParentId = :cuaNotClosed.Enquiry__c];
        Assert.areEqual(1, emailResults.size());
        Assert.areEqual(SpecConServices.FROM_ADDRESS_REGULAR, emailResults[0].FromAddress);
    }

}