force-app/main/default/objects/Case_Unit_Attempt__c.object
<CustomObject>
    <description>Junction table of Case and Unit Attempts</description>
    <fields>
        <fullName>Assessment_Due_Date_New__c</fullName>
        <description>Assessment Due Date (New)</description>
        <label>Assessment Due Date (New)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assessment_Due_Date_Original__c</fullName>
        <description>Original Assessment Due Date</description>
        <label>Assessment Due Date (Original)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assessment_Name__c</fullName>
        <description>Name of the Assessment</description>
        <label>Assessment Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment_Type__c</fullName>
        <description>Assessment Type</description>
        <label>Assessment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Attempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to the Unit Attempt</description>
        <label>Unit Attempt</label>
        <referenceTo>Unit_Attempt__c</referenceTo>
        <relationshipLabel>Case Unit Attempt</relationshipLabel>
        <relationshipName>Case_Unit_Attempt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Code__c</fullName>
        <description>Unit Code</description>
        <label>Unit Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Unit Attempt</label>
    <nameField>
        <displayFormat>CUA{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Unit Attempt</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Attempt__c.object
<CustomObject>
    <description>Unit (Subject) enrolment of the student.</description>
    <fields>
        <fullName>Title__c</fullName>
        <description>Unit Title</description>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Code__c</fullName>
        <description>Code of the attempted unit.</description>
        <label>Unit Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Unit Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CopyToClipboardController.cls
/*
 * @author			ayush.agrawal@monash.edu
 * @description		SA-372 Copy to clipboard implementation for only Case Unit Attempt with a set number of
 * 					fields. Future possibility to make this generic.
 * @group			Student Administration
 */

public with sharing class CopyToClipboardController {

    @AuraEnabled(cacheable=true)
    public static String getRecordDetails(Id recordId) {
        try {
            Boolean nop;
            
            Case_Unit_Attempt__c cua = [SELECT
                                        Id,
                                        Assessment_Due_Date_New__c,
                                        Assessment_Due_Date_Original__c,
                                        Assessment_Name__c,
                                        Assessment_Type__c,
                                        Unit_Attempt__c,
                                        Unit_Attempt__r.Title__c,
                                        Unit_Attempt__r.Unit_Code__c,
                                        Unit_Code__c
                                        FROM Case_Unit_Attempt__c
                                        WHERE Id = :recordId
                                        LIMIT 1];
            
            return JSON.serialize(cua);
        } catch(Exception e) {
            throw new AuraHandledException('System exception occured. Please get in touch with your Salesforce Administrator.');
        }
    }
    
}