force-app/main/default/objects/Channel__c.object
<CustomObject>
    <description>Communication Channels</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Channels</relationshipLabel>
        <relationshipName>Channels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Channel (which maps to Callista Address Type)
it supports Callista types + the &quot;MAILING&quot; type (which is used by the Lead Management).</description>
        <inlineHelpText>Type of Channel - CRM Users are not expected to select Callista values</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HOME</fullName>
                    <label>Home</label>
                </value>
                <value>
                    <fullName>MAILING</fullName>
                    <label>Mailing</label>
                </value>
                <value>
                    <fullName>POSTAL</fullName>
                    <label>Postal</label>
                </value>
                <value>
                    <fullName>POSTAL-EXT</fullName>
                    <label>Postal Extended</label>
                </value>
                <value>
                    <fullName>OS-POSTAL</fullName>
                    <label>Overseas Postal</label>
                </value>
                <value>
                    <fullName>OS-HOME</fullName>
                    <label>Overseas Home</label>
                </value>
                <value>
                    <fullName>AP-EMAIL</fullName>
                    <label>Application Email</label>
                </value>
                <value>
                    <fullName>GRADUATION-APPL</fullName>
                    <label>Graduation Email</label>
                </value>
                <value>
                    <fullName>EMERCONT</fullName>
                    <label>Emergency Contact</label>
                </value>
                <value>
                    <fullName>BILLING</fullName>
                    <isActive>false</isActive>
                    <label>Billing</label>
                </value>
                <value>
                    <fullName>BUSINESS</fullName>
                    <isActive>false</isActive>
                    <label>Business</label>
                </value>
                <value>
                    <fullName>DEFAULT</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
                <value>
                    <fullName>LEGAL</fullName>
                    <isActive>false</isActive>
                    <label>Legal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Channel</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The Qualificaiton Type</description>
        <label>Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Used to force uniqueness on course code. Updated from workflow.</description>
        <externalId>true</externalId>
        <label>Course Code Unique</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Course_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the parent course master to group all courses with the same Course Code</description>
        <label>Course Master</label>
        <referenceTo>Course_Master__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of course being offered</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Academic_Course</fullName>
                    <label>Academic Course</label>
                </value>
                <value>
                    <fullName>Short_Course</fullName>
                    <label>Professional Development</label>
                </value>
                <value>
                    <fullName>Course-All</fullName>
                </value>
                <value>
                    <fullName>Unit Set</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Master__c.object
<CustomObject>
    <description>custom object to group all Courses with the same course code</description>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>A unique (case insensitive) string to group all Courses by Code</description>
        <label>Course Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Course Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Environment_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchy Custom Setting that should contain all the feature controls for the environment. i.e. Enabling/Disabling auto processing of exploding leads.</description>
    <fields>
        <fullName>Exploding_Leads_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this boolean field if Staged Prospective Student records should automatically &quot;Explode&quot; to create different object records.</inlineHelpText>
        <label>Exploding Leads Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Environment Settings</label>
</CustomObject>

force-app/main/default/objects/Lead_Course_Association__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <formula>Course_Master__r.Course_Code__c</formula>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Master__c</fullName>
        <description>Course Master of the Lead interest. This holds the latest version of the Course</description>
        <label>Course Master</label>
        <referenceTo>Course_Master__c</referenceTo>
        <relationshipLabel>Lead Courses Association</relationshipLabel>
        <relationshipName>Lead_Courses_Association</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Lead Courses Association</relationshipLabel>
        <relationshipName>Lead_Courses_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lead Course Association</label>
    <nameField>
        <displayFormat>LCA-{0000}</displayFormat>
        <label>Lead Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Courses Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Roles__c.object
<CustomObject>
    <description>Custom version of Contact Roles</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Captures the related contact</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <infoMessage>Initial results are limited to contacts at the school only. Remove the filter to search all contacts</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Roles</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Role</label>
    <nameField>
        <displayFormat>ROL-{00000}</displayFormat>
        <label>Affiliation Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Prospective_Student__c.object
<CustomObject>
    <description>Staging object to capture prospective student data in a de-normalised form, which would be normalised into the Contact 360 data model through further processing post insertion.</description>
    <fields>
        <fullName>Acquisition_Source_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Acquisition Souce Campaign for the Prospective Student Lead.</description>
        <inlineHelpText>Acquisition source campaign for the Prospective Student Lead.</inlineHelpText>
        <label>Acquisition Source Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Staged Prospective Students</relationshipLabel>
        <relationshipName>Staged_Prospective_Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enquiry_Description__c</fullName>
        <description>Contains the details regarding the enquiry</description>
        <inlineHelpText>Contains the details regarding the enquiry.</inlineHelpText>
        <label>Enquiry Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Enquiry_Subject__c</fullName>
        <description>Subject line of enquiry</description>
        <inlineHelpText>Subject line of enquiry.</inlineHelpText>
        <label>Enquiry Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Campaigns__c</fullName>
        <description>List of Event Campaigns to add Prospective Student as Campaign members. Expected format : Line separated Campaign IDs.</description>
        <inlineHelpText>List of Event Campaigns to add Prospective Student as Campaign members.</inlineHelpText>
        <label>Event Campaigns</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exploded_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated to this exploded Staged Lead</description>
        <inlineHelpText>Contact associated to this exploded Staged Lead.</inlineHelpText>
        <label>Exploded Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Staged Prospective Students</relationshipLabel>
        <relationshipName>Staged_Prospective_Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_Course_List__c</fullName>
        <description>List of course IDs or Course Code that the Prospective Student is interested in</description>
        <inlineHelpText>Course IDs or Course Code that the Prospective Student is interested in.</inlineHelpText>
        <label>Interested Course List</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subscription_Lists__c</fullName>
        <description>Subscriptions Lists to subscribe the Prospective Student Lead with as Subscription Member. 
Expected format : Line separated Campaign IDs.</description>
        <inlineHelpText>Subscriptions Lists to subscribe the Prospective Student Lead with as Subscription Member.</inlineHelpText>
        <label>Subscription Lists</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Staged Prospective Student</label>
    <nameField>
        <displayFormat>SPS-{0}</displayFormat>
        <label>Staged Prospective Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Prospective Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/StagedProspectiveStudentServices_Test.cls
/**
 * @File Name          : StagedProspectiveStudentServices_Test.cls
 * @Description        : Test class for StagedProspectiveStudentServices.
 * @Author             : Nick Guia
 * @Group              : Lead Management
 */
@IsTest(isParallel=true)
private class StagedProspectiveStudentServices_Test {

	@TestSetup
	static void setup(){
		//Turn on environment settings - Exploding Leads Active
		Environment_Settings__c envSettings = new Environment_Settings__c();
		envSettings.Exploding_Leads_Active__c = true;
		insert envSettings;

		//create a Monash University Global Account record and use ID in custom setting
		Id globalMonashId = CommonUtilities.GLOBAL_MONASH_ACCOUNT_ID;

		//create Course Masters
		List<Course__c> courseList = new List<Course__c>();
		for(Course__c iCourse : TestHelper.createCourses(1)) {
			iCourse.Type__c = Label.Course_Type_Course_All;
			iCourse.Course_Code__c = iCourse.Name;
			courseList.add(iCourse);
		}
		insert courseList;

		//create Campaigns
		List<Campaign> campaignList = new List<Campaign>();

		//get non montrack record type ID
		Id nonMonRT = Schema.SObjectType.Campaign
		              .getRecordTypeInfosByDeveloperName()
		              .get('Non_Montrack')
		              .getRecordTypeId();
		//get subscription list record type ID
		Id subsListRT = Schema.SObjectType.Campaign
		                .getRecordTypeInfosByDeveloperName()
		                .get('Subscription_List')
		                .getRecordTypeId();

		//acquisition campaign
		Campaign acquisition = new Campaign(Name = 'AcquisitionCampaign');
		campaignList.add(acquisition);

		//Subscription Campaign
		Campaign subscriptionCampaign = new Campaign(Name = 'SubscriptionCampaign',
		                                             Channel_Type__c = 'Email;SMS',
		                                             RecordTypeId = subsListRT);
		campaignList.add(subscriptionCampaign);

		//Event Campaigns
		Campaign eventCampaign = new Campaign(Name = 'EventCampaign');
		campaignList.add(eventCampaign);

		//insert campaigns
		insert campaignList;
	}

	/**
	 * @description test coverage for different constructor parameters
     * 1: List parameter
     * 2: single record parameter
	 */
	@isTest
	static void testConstructors() {
		List<Staged_Prospective_Student__c> spsList = TestHelper.createSPS(3);
		Staged_Prospective_Student__c spsRec = TestHelper.createSPS(1)[0];

		StagedProspectiveStudentServices service1;
		StagedProspectiveStudentServices service2;

		Test.startTest();

		service1 = new StagedProspectiveStudentServices(spsList);
		service2 = new StagedProspectiveStudentServices(spsRec);

		Test.stopTest();

		System.assert (!service1.spsList.isEmpty(),
		               'Unable to initiaise StagedProspectiveStudentServices properly');
        System.assert (!service2.spsList.isEmpty(),
		               'Unable to initiaise StagedProspectiveStudentServices properly');
    }

	/**
	 * @description test service class logic for creating/finding existing
	 *  Contact records based on SPS first name + last name + email
	 */
	@isTest
	static void processProspectiveStudentContactTest() {
		List<Staged_Prospective_Student__c> spsList = TestHelper.createSPS(1);

		Test.startTest();

		StagedProspectiveStudentServices service = new StagedProspectiveStudentServices(spsList);
		spsList = service.processProspectiveStudentContact();

		Test.stopTest();

		for(Staged_Prospective_Student__c iSps : spsList) {
			System.assert (iSps.Exploded_Target__c != null,
			               'Exploding Leads Service Unable to create Contact for SPS');
		}
	}

	/**
	 * @description test all exploding leads processes post-creation of Contact
	 *  The process should create the following if the data exists in the SPS
	 *      - Contacts
	 *      - Roles
	 *      - Channels
	 *      - Leads
	 *      - Lead Course Association
	 *      - Campaign Members
	 *      - Contact Qualification
	 *      - Cases
	 */
	@isTest
	static void runExplodingLeadsTest() {
		List<Staged_Prospective_Student__c> spsList = TestHelper.createSPS(1);
		spsList = setupSPSDependencies(spsList);

		//first, explode this SPS to create a contact
		ExplodingLeadsService exLeads = new ExplodingLeadsService(spsList);
		List<StagedProspectiveStudentDAO> processedSpsDAO = exLeads.buildPSContact();
		List<Staged_Prospective_Student__c> spsWithContactIds = exLeads.upsertProspectiveStudentContact(processedSpsDAO);

		//switch off exploding leads so it won't process post-contact objects yet
		Environment_Settings__c envSettings = Environment_Settings__c.getOrgDefaults();
		envSettings.Exploding_Leads_Active__c = false;
		update envSettings;

		//insert sps with IDs so that they'll be eligible for updates
		insert spsWithContactIds;

		//switch on Exploding Leads again
		envSettings.Exploding_Leads_Active__c = true;
		update envSettings;

		Test.startTest();
        
        StagedProspectiveStudentServices service2 = new StagedProspectiveStudentServices(spsList);
		service2.runExplodingLeads();

		Test.stopTest();

        Contact con = [SELECT Id FROM Contact LIMIT 1];
		//verify that Contact is created
		System.assert (con != null,
		               'Unable to generate a Contact record for SPS');

		Roles__c role = [SELECT Id FROM Roles__c WHERE Contact__c = :con.Id LIMIT 1];
		//verify that Role was created
		System.assert (role != null,
		               'Unable to generate a Role record for SPS');

		Channel__c channel = [SELECT Id FROM Channel__c WHERE Contact__c = :con.Id LIMIT 1];
		//verify that Channel was created
		System.assert (channel != null,
		               'Unable to generate a Channel record for SPS');

		Lead leadRec = [SELECT Id FROM Lead WHERE Contact__c = :con.Id LIMIT 1];
		//verify that Lead is created
		System.assert (leadRec != null,
		               'Unable to generate a Lead record for SPS');

		List<Lead_Course_Association__c> lcaList = [SELECT Id FROM Lead_Course_Association__c WHERE Lead__c = :leadRec.Id];
		//verify that Lead Course Association was created
		System.assert (!lcaList.isEmpty(),
		               'Unable to generate Lead Course Association records for SPS');

		List<CampaignMember> cmList = [SELECT Id FROM CampaignMember WHERE ContactId = :con.Id];        //verify that Campaign Members were created
		System.assert (!cmList.isEmpty(),
		               'Unable to generate Campaign Member records for SPS');

		List<Contact_Qualification__c> cqList = [SELECT Id FROM Contact_Qualification__c WHERE Contact__c = :con.Id];
		//verify that Contact Qualification Qualifications were created
		System.assert (!cqList.isEmpty(),
		               'Unable to generate Contact Qualification records for SPS');

		List<Case> caseList = [SELECT Id FROM Case WHERE ContactId = :con.Id];
		//verify that Case was created
		System.assert (!caseList.isEmpty(),
		               'Unable to generate Cases for SPS');
    }

    /**
	 * @description sets up the following additional data for SPS:
	 * 	- Acquisition Source Campaign
	 * 	- Event Campaign
	 * 	- Subscription List Campaign
	 * 	- Interested Course List (Course Master)
	 * 	- Case details
	 */
    private static List<Staged_Prospective_Student__c> setupSPSDependencies(List<Staged_Prospective_Student__c> spsList) {
		//get course master records
		Map<String, Course_Master__c> cmMap = new Map<String, Course_Master__c>([SELECT Id FROM Course_Master__c]);
		//join Ids by ',' delimiter
		String cmIds = String.join(new List<String>(cmMap.keySet()), ',');

		Campaign acq; //acquisition source campaign
		Campaign event; //Event campaign
		Campaign subList; //subscription list campaign

		//get Campaigns
		for(Campaign iCamp : [SELECT Id, Name FROM Campaign]) {
			if(iCamp.Name == 'AcquisitionCampaign') {
				acq = iCamp;
			} else if(iCamp.Name == 'SubscriptionCampaign') {
				event = iCamp;
			} else if(iCamp.Name == 'EventCampaign') {
				subList = iCamp;
			}
		}

		System.assert (acq != null, 'No setup Acquisition Source Campaign found!');
		System.assert (event != null, 'No setup Subscription List Campaign found!');
		System.assert (subList != null, 'No setup Event Campaign found!');

		//now, populate out setup SPS records with these values
		for(Staged_Prospective_Student__c iSps : spsList) {
			//for LCA
			iSps.Interested_Course_List__c = cmIds;
			//for Campaign Members
			iSps.Acquisition_Source_Campaign__c = acq.Id;
			iSps.Event_Campaigns__c = '' + event.Id;
			iSps.Subscription_Lists__c = '' + subList.Id;
			//for Cases
			iSps.Enquiry_Subject__c = 'Test Case Subject';
			iSps.Enquiry_Description__c = 'Test Case Description';
		}
		return spsList;
    }
}