force-app/main/default/objects/Channel__c.object
<CustomObject>
    <description>Communication Channels</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Channels</relationshipLabel>
        <relationshipName>Channels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System Field - indicates that the record was processed into Contact Point records</description>
        <inlineHelpText>System Field - indicates that the record was processed into Contact Point records</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Channel (which maps to Callista Address Type)
it supports Callista types + the &quot;MAILING&quot; type (which is used by the Lead Management).</description>
        <inlineHelpText>Type of Channel - CRM Users are not expected to select Callista values</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HOME</fullName>
                    <label>Home</label>
                </value>
                <value>
                    <fullName>MAILING</fullName>
                    <label>Mailing</label>
                </value>
                <value>
                    <fullName>POSTAL</fullName>
                    <label>Postal</label>
                </value>
                <value>
                    <fullName>POSTAL-EXT</fullName>
                    <label>Postal Extended</label>
                </value>
                <value>
                    <fullName>OS-POSTAL</fullName>
                    <label>Overseas Postal</label>
                </value>
                <value>
                    <fullName>OS-HOME</fullName>
                    <label>Overseas Home</label>
                </value>
                <value>
                    <fullName>AP-EMAIL</fullName>
                    <label>Application Email</label>
                </value>
                <value>
                    <fullName>GRADUATION-APPL</fullName>
                    <label>Graduation Email</label>
                </value>
                <value>
                    <fullName>EMERCONT</fullName>
                    <label>Emergency Contact</label>
                </value>
                <value>
                    <fullName>BILLING</fullName>
                    <isActive>false</isActive>
                    <label>Billing</label>
                </value>
                <value>
                    <fullName>BUSINESS</fullName>
                    <isActive>false</isActive>
                    <label>Business</label>
                </value>
                <value>
                    <fullName>DEFAULT</fullName>
                    <isActive>false</isActive>
                    <label>Default</label>
                </value>
                <value>
                    <fullName>LEGAL</fullName>
                    <isActive>false</isActive>
                    <label>Legal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Channel</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Event__e.object
<CustomObject>
    <description>When a Channel__c object record is inserted, updated, or deleted event is dispatched to process unprocessed channel records to invoke Channel to Contact Point break-up</description>
    <fields>
        <fullName>Channel_Id__c</fullName>
        <description>The Channel__c record id this event is raised for (to be broken up into contact points)</description>
        <label>Channel Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <description>The contact the Channel__c record had a lookup to (Contact__r)</description>
        <label>Contact Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Channel Event</label>
    <pluralLabel>Channel Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Email__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Channel lookup field for the Contact Point object record</description>
        <inlineHelpText>Lookup to Channel for Callista sourced records</inlineHelpText>
        <label>Channel</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Email channels must be for the same Contact record</errorMessage>
            <filterItems>
                <field>Channel__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contact__c</valueField>
            </filterItems>
            <filterItems>
                <field>Channel__c.Type__c</field>
                <operation>notEqual</operation>
                <value>EMERCONT</value>
            </filterItems>
            <infoMessage>Search for all non-emergency contact channels for this contact</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Emails</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this email address is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Email Addresses</relationshipLabel>
        <relationshipName>Emails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Email</label>
    <nameField>
        <label>Email Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c.object
<CustomObject>
    <description>Store states information. Source: shop.monash</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Country_List_1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Samoa, American</fullName>
        <label>American Samoa</label>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
        <label>Bahamas (the)</label>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
        <label>Bolivia (Plurinational State of)</label>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <description>As per ISO 3166</description>
    <masterLabel>Country List 1</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PlatformEventTrigger_Test.cls
/**
 * @description       : Test class for the Platform Event Trigger (framework) class
 * @author            : Stefan Scheit
 * @group             : Test
 * @last modified on  : 2020-10-22
 * @last modified by  : Stefan Scheit
 * Modifications Log 
 * Ver   Date         Author          Modification
 * 1.0   2020-10-15   Stefan Scheit   Initial Version with comments
**/
@isTest(isParallel=true)
private class PlatformEventTrigger_Test {
    static Channel_Event__e channelEvent;
    static Channel__c channelRecord;

    /**
     * Test disable / enable the batch size control
     */
    @isTest
    static void testBindInsert() {
        // GIVEN: The trigger handler is initialised (for a particular type)
        PlatformEventTrigger trg = new PlatformEventTrigger();
        
        // WHEN: Batch size control is disabled
        Test.startTest();
        trg.disablePlatformEventControl();
        // THEN: It's flagged as disabled
        Assert.isFalse(trg.applyBatchSize, 'Disabling the batch-size failed.');

        // WHEN: Batch size control is enabled
        trg.enablePlatformEventControl();
        // THEN: It's flagged as re-enabled
        Assert.isTrue(trg.applyBatchSize, 'Re-enable the batch-size failed.');
        Test.stopTest();
    }
    /**
     * Dispatch platform event and validate execution of trigger handler.
     */
    @isTest
    static void testDispatchEvent() {
        // GIVEN: Data is present in the system (Contact, Channel)
        setupTestData();
        
        // WHEN: Platform event is inserted and published
        Test.startTest();
        Channel_Event__e v1 = channelEvent;
        EventBus.publish(v1);
        Test.getEventBus().deliver();
        
        // THEN: The Channel records is marked as processed
        Test.stopTest();
        Channel__c chTest = [SELECT Id, Is_Processed__c FROM Channel__c WHERE Id =: channelRecord.Id LIMIT 1].get(0);
        Assert.isTrue(chTest.Is_Processed__c, 'Channel platform event did not process.');
    }
    /**
     * Set up test data (Contact, Channel, Contact Point event)
     */
    private static void setupTestData() {
        // Create Comtact
        Contact contactRecord = new Contact();
        contactRecord.Person_ID_unique__c = '12345';
        contactRecord.Birthdate = Date.today().addYears(- 20);
        contactRecord.Citizenship__c = 'INTERNATIONAL';
        contactRecord.Citizenship_Code__c = '4';
        contactRecord.Residency_Status__c = 'Australian Permanent Resident';
        contactRecord.Email = 'test@test.com';
        contactRecord.Personal_Email__c = 'test@test.com';
        contactRecord.Monash_Email_Address__c = 'test@test.com';
        contactRecord.Business_Email_Address__c = 'test@test.com';
        contactRecord.Title = 'OAM';
        contactRecord.Salutation = 'Mr.';
        contactRecord.FirstName = 'testFirstName';
        contactRecord.MiddleName = 'testMiddleName';
        contactRecord.LastName = 'testLastName';
        contactRecord.Suffix = 'testSuffix';
        contactRecord.Gender__c = 'None';
        contactRecord.Phone = '+61390008000';
        contactRecord.MobilePhone = '+61400111222';
        contactRecord.HomePhone = '+61390008001';
        contactRecord.OtherPhone = '+61390008002';
        contactRecord.AssistantPhone = '+61390008003';
        contactRecord.Fax = '+61390008999';
        contactRecord.MailingStreet = '350 Bourke Street';
        contactRecord.MailingCity = 'Melbourne';
        contactRecord.MailingState = 'Victoria';
        contactRecord.MailingPostalCode = '3000';
        contactRecord.MailingCountry = 'Australia';
        contactRecord.OtherStreet = '111 Bourke Street';
        contactRecord.OtherCity = 'Melbourne';
        contactRecord.OtherState = 'Victoria';
        contactRecord.OtherPostalCode = '3000';
        contactRecord.OtherCountry = 'Australia';
        insert contactRecord;
        Assert.isNotNull(contactRecord.Id, 'Contact Record Insert Failed');

        // Create Channel
        channelRecord = new Channel__c(
            type__c = 'POSTAL',
            Contact__c = contactRecord.Id,
            Street__c = '55 Collin St',
            Post_Code__c = '3000',
            State__c = 'Vic',
            City__c = 'Melbourne',
            email__c='postal@email.com.au',
            Country__c = 'Australia');
        insert channelRecord;

        // Create contact point (but don't insert (yet))
        channelEvent = new Channel_Event__e();
        channelEvent.Channel_Id__c = channelRecord.Id;
        channelEvent.Contact_id__c = contactRecord.Id;
    }
}