force-app/main/default/objects/Channel__c.object
<CustomObject>
    <description>Communication Channels</description>
    <label>Channel</label>
    <nameField>
        <displayFormat>CK-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat_365_Log__c.object
<CustomObject>
    <description>Log of all the chat into the system</description>
    <fields>
        <fullName>Session_Id__c</fullName>
        <description>Session Unique Id for the Conversation.</description>
        <externalId>true</externalId>
        <label>Session Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Chat 365 Log</label>
    <nameField>
        <displayFormat>CL-{0000000}</displayFormat>
        <label>Chat 365 Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat 365 Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat_365_Log_Detail__c.object
<CustomObject>
    <description>Detailed log of conversation happened during a session of a chat log.</description>
    <fields>
        <fullName>Chat_365_Log__c</fullName>
        <description>Chat Log Parent Record</description>
        <label>Chat 365 Log</label>
        <referenceTo>Chat_365_Log__c</referenceTo>
        <relationshipLabel>Chat 365 Log Details</relationshipLabel>
        <relationshipName>Chat_365_Log_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Chat 365 Log Detail</label>
    <nameField>
        <displayFormat>CLD-{00000000}</displayFormat>
        <label>Chat 365 Log Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat 365 Log Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Letter_Log__c.object
<CustomObject>
    <description>Stores Student Letter&apos;s transaction log details</description>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chatbot</fullName>
                    <default>true</default>
                    <label>Chatbot</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Chat_365_Log_Detail__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Chat 365 Log Detail record</description>
        <label>Chat 365 Log Detail</label>
        <referenceTo>Chat_365_Log_Detail__c</referenceTo>
        <relationshipLabel>Student Letter Logs</relationshipLabel>
        <relationshipName>Student_Letter_Logs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chat_365_Log__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Links to chat 365 log record</description>
        <label>Chat 365 Log</label>
        <referenceTo>Chat_365_Log__c</referenceTo>
        <relationshipLabel>Student Letter Logs</relationshipLabel>
        <relationshipName>Student_Letter_Logs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Letter_Description__c</fullName>
        <label>Letter Description</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MYEQ0202_ENROLMENT_VERIFICATION</fullName>
                    <label>Enrolment Verification</label>
                </value>
                <value>
                    <fullName>MYEQ0206_PROOF_OF_QUALIFICATION</fullName>
                    <label>Proof of Qualification</label>
                </value>
                <value>
                    <fullName>MYEQ0207_PROOF_OF_GRADUATION</fullName>
                    <label>Proof of Graduation</label>
                </value>
                <value>
                    <fullName>MYEQ0210_FORECAST_COMPLETION_DATE</fullName>
                    <label>Forecast Completion Date</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Letter_Status__c</fullName>
        <description>Status of the letter requested.</description>
        <label>Letter Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Payment Completed</fullName>
                </value>
                <value>
                    <fullName>Pending Date Update</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>Sent to Callista</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Contains the Message from Payment gateway</description>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <description>Payment Method</description>
        <label>Payment Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Id__c</fullName>
        <description>Contains Session Id + Letter Code</description>
        <label>Session Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student Letter Log</label>
    <nameField>
        <displayFormat>SLL{0000000}</displayFormat>
        <label>Student Letter Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Letter Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StudentLettersHelper_Test.cls
/**
@author Cartick Sub
@date 11 August 2020
@group Student Letters
@description Test class for StudentLettersHelper
@revision Initial version 11 August 2020
          Cartick Sub - 1 October 2020 - Add test method for Student Letter Log query
**/

@isTest(isParallel=true)
public class StudentLettersHelper_Test {
    
    /**
    @description Mock tests the HTTP callout to get student letter entitlements
    **/
    @isTest
    public static void validateGetEntitlementsFromAPI() {

        // Insert test Contact
        Contact testContact = (Contact)MonConTestDataFactory.createSObject(new Contact(), true);

        Test.startTest();

        // Ensure HTTP callout in next block is handled by mock response generator
        Test.setMock(HttpCalloutMock.class, new StudentLettersMockResponseGenerator());

        // Call method being tested
        String response = StudentLettersHelper.getEntitlementsFromAPI(testContact.Person_ID_unique__c);

        // Response should be that hard coded in mock response generator
        String actualValue = response;
        String expectedValue = '{"_links": {"_self": {"href": ""}},"entitlements": []}'; 
        System.assertEquals(actualValue, expectedValue);
        
        Test.stopTest();
    }

    @isTest
    public static void validateGetStudentLetterLogsFromSF() {

        Test.startTest();

        // Insert Contact
        Contact testContact = (Contact)MonConTestDataFactory.createSObject(new Contact(), true);

        // Insert Chat 365 Log - should auto-link to Contact under its trigger
        Chat_365_Log__c testChat365Log = (Chat_365_Log__c)MonConTestDataFactory.createSObject(new Chat_365_Log__c(), true);

        // Insert Chat 365 Detail Log
        Chat_365_Log_Detail__c testChat365LogDetail = (Chat_365_Log_Detail__c)MonConTestDataFactory.createSObject(new Chat_365_Log_Detail__c(), false);
        testChat365LogDetail.Chat_365_Log__c = testChat365Log.Id;
        insert testChat365LogDetail;

        // Insert Student Letter Log - should auto-link to same Contact as parent Chat 365 Log under trigger
        Student_Letter_Log__c testStudentLetterLog = new Student_Letter_Log__c(
            Chat_365_Log__c = testChat365Log.Id,
            Chat_365_Log_Detail__c = testChat365LogDetail.Id,
            Session_Id__c = testChat365Log.Session_Id__c,
            Channel__c = 'Chatbot',
            Letter_Description__c = 'MYEQ0202_ENROLMENT_VERIFICATION',
            Message__c = 'Test',
            Payment_Method__c = 'Test',
            Letter_Status__c = 'Completed'
        );
        insert testStudentLetterLog;

        // Call method being tested
        List<Student_Letter_Log__c> listStudentLetterLogsFromMethod = new List<Student_Letter_Log__c>();
        listStudentLetterLogsFromMethod = StudentLettersHelper.getStudentLetterLogsFromSF(testContact.Id);

        Test.stopTest();

        List<Student_Letter_Log__c> listStudentLetterLogsFromDB = new List<Student_Letter_Log__c>();
        listStudentLetterLogsFromDB = [SELECT Id FROM Student_Letter_Log__c];

        System.assertEquals(listStudentLetterLogsFromDB.size(), listStudentLetterLogsFromMethod.size(), 'Incorrect number of Student Letter Logs found in DB');
    }
}