force-app/main/default/objects/Chat_365_Log__c.object
<CustomObject>
    <description>Log of all the chat into the system</description>
    <label>Chat 365 Log</label>
    <nameField>
        <displayFormat>CL-{0000000}</displayFormat>
        <label>Chat 365 Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat 365 Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat_365_Log_Detail__c.object
<CustomObject>
    <description>Detailed log of conversation happened during a session of a chat log.</description>
    <fields>
        <fullName>Chat_365_Log__c</fullName>
        <description>Chat Log Parent Record</description>
        <label>Chat 365 Log</label>
        <referenceTo>Chat_365_Log__c</referenceTo>
        <relationshipLabel>Chat 365 Log Details</relationshipLabel>
        <relationshipName>Chat_365_Log_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intent__c</fullName>
        <description>1 - Submit Enquiry
2 - Interaction
3 - Submit Feedback
4 - Request Chat - Agent Online
5 - Request Chat - Agent Offline</description>
        <label>Intent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Chat 365 Log Detail</label>
    <nameField>
        <displayFormat>CLD-{00000000}</displayFormat>
        <label>Chat 365 Log Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat 365 Log Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Chat365LogDetailTriggerHandler_Test.cls
/**
* @author Angelo Rivera
* @date 19.12.19
* @group Test Class
* @description  Test Class to test the functionality of Chat365LogDetailTriggerHandler
* @revision     15/12/2019 - Creation <br/>
*/

@isTest(isParallel=true)
private class Chat365LogDetailTriggerHandler_Test {

	/**
	 * This is to test insert event on the triggerhandler
	 */
	@IsTest
	static void testInsert() {
		Chat_365_Log__c chat365Log = (Chat_365_Log__c)MonConTestDataFactory.createSObject(new Chat_365_Log__c(), true);
		Chat_365_Log_Detail__c chat365DetailLog1 = (Chat_365_Log_Detail__c)MonConTestDataFactory.createSObject(new Chat_365_Log_Detail__c());
		Chat_365_Log_Detail__c chat365DetailLog2 = (Chat_365_Log_Detail__c)MonConTestDataFactory.createSObject(new Chat_365_Log_Detail__c());
		chat365DetailLog1.Chat_365_Log__c = chat365Log.Id;
		chat365DetailLog2.Chat_365_Log__c = chat365Log.Id;
		chat365DetailLog1.Intent__c = 1;
		chat365DetailLog2.Intent__c = 4;
		Test.startTest();
			insert chat365DetailLog1;
			insert chat365DetailLog2;
		Test.stopTest();
		Chat_365_Log__c chat365Log2 = [SELECT Id, (SELECT Id FROM Enquiries__r) from Chat_365_Log__c where Id=: chat365Log.Id];
		System.assertEquals(2,chat365Log2.Enquiries__r.size());
	}
}