force-app/main/default/objects/Clause_Filtering_Criteria__c.object
<CustomObject>
    <description>Used to capture conditions that need to be met so the clause is automatically added to the offer (quote)</description>
    <fields>
        <fullName>Clause__c</fullName>
        <description>Link to the clause using this criteria</description>
        <label>Clause</label>
        <referenceTo>APXT_Redlining__Clause__c</referenceTo>
        <relationshipName>Filtering_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Clause Filtering Criteria</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>Criteria Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clause Filtering Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mirror_Clause__c.object
<CustomObject>
    <fields>
        <fullName>Clause__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clause</label>
        <referenceTo>APXT_Redlining__Clause__c</referenceTo>
        <relationshipLabel>Mirror Clauses</relationshipLabel>
        <relationshipName>Mirror_Clauses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mirror Clause</label>
    <nameField>
        <label>Mirror Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mirror Clauses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ClauseTriggerHandler_Test.cls
@isTest(isParallel=true)
public with sharing class ClauseTriggerHandler_Test {
    
    @isTest static void test_clause_upsert(){
        APXT_Redlining__Clause__c clause = (APXT_Redlining__Clause__c) TestDataFactory.createSObject(new APXT_Redlining__Clause__c(Selection_Type__c = 'Manual'), true);
        TestDataFactory.createSObject(new Clause_Filtering_Criteria__c(Clause__c = clause.Id), 'TestDataFactorySettings.ClauseFilteringCriteriaForContainsDefaults', true);
        
        Integer count = [select COUNT() FROM Mirror_Clause__c WHERE External_ID__c =: clause.Id];
        System.assert(count == 1, 'Mirror Clause should be in sync');
        
        clause.Name = 'Test 1';
        update clause;
        count = [select COUNT() from Mirror_Clause__c WHERE External_ID__c =: clause.Id AND Name = 'Test 1'];
        System.assert(count == 1, 'Mirror Clause should be in sync');
    }
    @isTest static void test_clause_delete(){
        APXT_Redlining__Clause__c clause = (APXT_Redlining__Clause__c) TestDataFactory.createSObject(new APXT_Redlining__Clause__c(Selection_Type__c = 'Manual'), true);

        delete clause;
        Integer count = [select COUNT() from Mirror_Clause__c WHERE External_ID__c =: clause.Id];
        System.assert(count == 0, 'Mirror Clause should be deleted');
    }
    @isTest static void test_clause_auto(){
        APXT_Redlining__Clause__c clause = (APXT_Redlining__Clause__c) TestDataFactory.createSObject(new APXT_Redlining__Clause__c(), true);
        Integer count = [select COUNT() FROM Mirror_Clause__c WHERE External_ID__c =: clause.Id];
        System.assert(count == 0, 'No mirror Clause for auto clause');
    }
}