force-app/main/default/objects/Community_Experience_Site_Banner__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Site banner used for announcements in My Application</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Feature switch</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of the announcement</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message shown in the banner</description>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date of the announcement</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Community Experience Site Banner</label>
</CustomObject>

force-app/main/default/classes/HDRGraduateResearchBannerCC_Test.cls
/*******************************************************************************
* @author		Davey Yu
* @date         11/1/2024   
* @description  Test class for HDRGraduateResearchBannerCC
* @revision     11/1/2024 - Initial Version
*******************************************************************************/
@IsTest
public class HDRGraduateResearchBannerCC_Test {
    @testSetup static void setup() {
        //create values for my app custom settings
        Community_Experience_Site_Banner__c siteBanner = new Community_Experience_Site_Banner__c();
        siteBanner.message__c = 'Banner Announcement';
        siteBanner.Start_Date__c = Date.Today();
        siteBanner.End_Date__c = Date.Today().addDays(1);
        siteBanner.Active__c = true;
        insert siteBanner;
    }

     /**
     * @author      Davey YU
     * @description Tests to get banner details
     * @revision    17/07/24 updated
     *
     * GIVEN when there is an announcement made for HDR e.g. No Shcolarship rounds available
     * WHEN student is logged in to my.app
     * THEN the Announcement should display in My.App
     */
    @isTest
    public static void testBannerDetail() {
        Community_Experience_Site_Banner__c banner  = HDRGraduateResearchBannerCC.getBannerDetail();
        Assert.areEqual('Banner Announcement', banner.Message__c, 'Banner details successfully retrieved');

    }
}