force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>deleted_on_source__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag indicates if the qualification is currently active</description>
        <label>Deleted on Source</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purge_Recs__mdt.object
<CustomObject>
    <description>Custom metadata to purge records that are no longer needed in Production.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BatchSize__c</fullName>
        <description>Batch size for the purge record</description>
        <label>BatchSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Filter_By_Date__c</fullName>
        <label>Filter By Date</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CreatedDate</fullName>
                    <default>true</default>
                    <label>Created Date</label>
                </value>
                <value>
                    <fullName>LastModifiedDate</fullName>
                    <label>Last Modified Date</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Filter_Criteria__c</fullName>
        <label>Filter Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <description>Limited applied to the SOQL prior to the delete</description>
        <label>Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Job_Control__c</fullName>
                    <label>Job Control</label>
                </value>
                <value>
                    <fullName>PE_Business_Exception__c</fullName>
                    <label>Business Exceptions</label>
                </value>
                <value>
                    <fullName>Exception_Log__c</fullName>
                    <label>Exception Logs</label>
                </value>
                <value>
                    <fullName>Stg_CRICOS_Code__c</fullName>
                    <label>CRICOS Staging</label>
                </value>
                <value>
                    <fullName>Stg_Calendar__c</fullName>
                    <label>Calendar Staging</label>
                </value>
                <value>
                    <fullName>Stg_Calendar_Dates__c</fullName>
                    <label>Calendar Dates Staging</label>
                </value>
                <value>
                    <fullName>Stg_Course__c</fullName>
                    <label>Course Staging</label>
                </value>
                <value>
                    <fullName>Channel__c</fullName>
                    <label>Channel Staging</label>
                </value>
                <value>
                    <fullName>Encumbrance__c</fullName>
                    <label>Encumbrances</label>
                </value>
                <value>
                    <fullName>Contact</fullName>
                    <label>Contacts</label>
                </value>
                <value>
                    <fullName>Unit_Set_Attempt__c</fullName>
                    <label>Unit Set Attempts</label>
                </value>
                <value>
                    <fullName>Unit_Attempt__c</fullName>
                    <label>Unit Attempts</label>
                </value>
                <value>
                    <fullName>Course_Attempt__c</fullName>
                    <label>Course Attempts</label>
                </value>
                <value>
                    <fullName>contact_qualification__c</fullName>
                    <label>Contact Qualifications</label>
                </value>
                <value>
                    <fullName>DuplicateRecordSet</fullName>
                    <label>Duplicate Record Sets</label>
                </value>
                <value>
                    <fullName>Case</fullName>
                    <label>Enquiries</label>
                </value>
                <value>
                    <fullName>EmailMessage</fullName>
                </value>
                <value>
                    <fullName>ucinn_ascendv2__Automated_Process_Log__c</fullName>
                    <label>Ascend Automated Process Logs</label>
                </value>
                <value>
                    <fullName>ucinn_ascendv2__Log__c</fullName>
                    <label>Ascend Logs</label>
                </value>
                <value>
                    <fullName>Address__c</fullName>
                    <label>Addresses</label>
                </value>
                <value>
                    <fullName>Phone__c</fullName>
                    <label>Phones</label>
                </value>
                <value>
                    <fullName>Name__c</fullName>
                    <label>Names</label>
                </value>
                <value>
                    <fullName>Email__c</fullName>
                    <label>Emails</label>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Application__c</fullName>
                    <label>Applications</label>
                </value>
                <value>
                    <fullName>Chat_356_Log__c</fullName>
                    <isActive>false</isActive>
                    <label>Chat_356_Log__c</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Older_than__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Older than is the number of days - To be used in the query to delete all the records before that time</description>
        <inlineHelpText>In Days</inlineHelpText>
        <label>Older than</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_By__c</fullName>
        <description>Prioritise records base on the order</description>
        <label>Order By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Purge Records</label>
    <pluralLabel>Purge Records</pluralLabel>
</CustomObject>

force-app/main/default/classes/PurgeRecordsBatch_Test.cls
/*
 * @author          Shalini Mendu
 * @date			23/03/2020
 * @group			Test
 * @description     Test class for batch job to run query on all the purge Custom Metadata types and purge data
 * @revision         
 *                  23/03/2020 - Stefan Scheit - Updated method name & ddescriptions
 * 					06/05/2019 - Shalini Mendu - Initial version	
 *                  03/02/2022 - Shalini Mendu - Rewriting unit code to cover new solution -  SFTG-2366 
 *
 */
@isTest(isParallel=true)
public class PurgeRecordsBatch_Test {

   
    @isTest
    static void testPurgeRecordsBatch() {
        // GIVEN, a contact qualification is defined
        Contact testContact = StudFirst_TestHelper.createInternationalApplicant();
        testContact.FirstName = 'PurgeRecordsBatch';
        testContact.LastName = 'Test';
        insert testContact;
        Contact_Qualification__c cq1 = new Contact_Qualification__c(Contact__c=testContact.Id, Deleted_on_Source__c= true);
        insert cq1;

        // WHEN, run the batch job
        Test.startTest();
        List<Purge_Recs__mdt> mdtList = [SELECT Id,Object__c, Older_than__c,BatchSize__c, Filter_Criteria__c,Filter_By_Date__c, label, order_by__c, limit__c  FROM Purge_Recs__mdt
        WHERE Label='Contact Qual Purge' and Active__c = true];
        if(!mdtList.isEmpty())
            Database.executeBatch(new PurgeRecordsBatch(mdtList[0], mdtList));
        Test.stopTest();

        // THEN, the records (Contact Qualification record(s)) should be purged
        List<Contact_Qualification__c> cq = [SELECT Id FROM Contact_Qualification__c WHERE Contact__c = :testContact.Id];
        if(!mdtList.isEmpty()){
            Assert.areEqual(0, cq.size(), 'Records not deleted.');
        }else 
        {
            Assert.areEqual(1, cq.size(), 'Records deleted.');

        }
    }
}