force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Achieved__c</fullName>
        <label>Date Achieved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Faculty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>(Managing/owning) faculty of the qualification (for university degrees).
Note: relevant for Monash Tertiary Education only.</description>
        <label>Faculty</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Faculty</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Qualifications (Organization)</relationshipLabel>
        <relationshipName>Contact_Qualifications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Graduation_Date__c</fullName>
        <description>This field captures graduation date</description>
        <label>Graduation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Institution_Code__c</fullName>
        <description>This is referencing the Institution_Code__c field of the Callista_Institutions__c Custom Setting</description>
        <label>Institution Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution_Name__c</fullName>
        <description>This is referencing the Institution_Name__c field of the Callista_Institutions__c Custom Setting</description>
        <label>Awarding Body/Institution Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instruction_in_English__c</fullName>
        <defaultValue>false</defaultValue>
        <label>English Language of Instruction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name_at_Completion__c</fullName>
        <description>Name of the person when they received the qualification, e.g. maiden name etc.</description>
        <label>Name at Completion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Obtained_Status__c</fullName>
        <label>Obtained Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MONASH-OBTAINED</fullName>
                    <label>Monash Obtained</label>
                </value>
                <value>
                    <fullName>NON-MONASH-OBTAINED</fullName>
                    <label>Non-Monash Obtained</label>
                </value>
                <value>
                    <fullName>NOT-OBTAINED</fullName>
                    <label>Not Obtained</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Qualification__c</fullName>
        <label>Other Qualification</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <label>Person ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Code__c</fullName>
        <description>This field captures qualificaiton code</description>
        <label>Qualification Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Grade__c</fullName>
        <description>This field captures qualificaiton grade</description>
        <label>Qualification Grade</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Mark__c</fullName>
        <description>This field captures qualification mark</description>
        <label>Qualification Mark</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Name__c</fullName>
        <formula>if (ISBLANK(Qualification__r.Qualification_Name__c)
  , if (ISBLANK( Other_Qualification__c), Title__c,Other_Qualification__c)
 , HYPERLINK(&apos;/&apos;+Id, Qualification__r.Qualification_Name__c,&apos;_self&apos;))</formula>
        <label>Qualification Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Qualification Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Testamur_Type__c</fullName>
        <description>This field captures testamur type</description>
        <label>Testamur Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thesis_Title__c</fullName>
        <label>Thesis Title</label>
        <length>350</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The Qualificaiton Title</description>
        <label>Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_External_Id__c</fullName>
        <description>The unique external id for Contact Qualification Object</description>
        <externalId>true</externalId>
        <label>Unique_External_Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verification_Status__c</fullName>
        <description>Default is UNKNOWN. If an external verification is done for that qualification, assessors update this field.While exchanging information with Callista, values will be as follows: Verified = VERIFIED, Unknown = UNKNOWN, Invalid OR Expired OR Unverified = UNVERIFIED</description>
        <label>Verification Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                    <default>true</default>
                    <label>Unknown</label>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Unverified</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Score Verified</fullName>
                </value>
                <value>
                    <fullName>Fraudulent</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>deleted_on_source__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag indicates if the qualification is currently active</description>
        <label>Deleted on Source</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attempt__c.object
<CustomObject>
    <description>Course attempt represents the courses a Contact is related to.</description>
    <fields>
        <fullName>Callista_External_Id__c</fullName>
        <description>Holds a concatenation of the Callista Person Id (from &apos;Contact.Person_Id_unique__c&apos;), and underscore(&apos;_&apos;), and the Course Code (from &apos;Course__c.Name&apos;). This is a unique combination (for academic courses).</description>
        <externalId>true</externalId>
        <inlineHelpText>This field is evaluated and set by the system.</inlineHelpText>
        <label>Callista_External_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Reference to the contact who pursues this course</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Contains the course code (without the version). It is derived from the Course lookup relationship.</description>
        <formula>Course__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Version__c</fullName>
        <description>Version of the course being attempted.</description>
        <formula>Course__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <label>Person Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Course Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Attempts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IbdQualification__e.object
<CustomObject>
    <description>Inbound qualifications and awards</description>
    <fields>
        <fullName>Award_Faculty_Code__c</fullName>
        <label>Award Faculty Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Faculty_Name__c</fullName>
        <label>Award Faculty Name</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Award_Faculty_Start_Date__c</fullName>
        <label>Award Faculty Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Award_Institution_Code__c</fullName>
        <label>Award Institution Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Institution_Name__c</fullName>
        <label>Award Institution Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>This field captures the course code of the course attempt</description>
        <label>Course_Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Version__c</fullName>
        <description>This field captures course version number</description>
        <label>Course Version</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Achieved__c</fullName>
        <description>This field captures qualification/award date achieved</description>
        <label>Date_Achieved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This filed is to capture the type of event example INSERT, UPDATE and DELETE</description>
        <label>Event_Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Graduation_Date__c</fullName>
        <description>This field captures the graduation date</description>
        <label>Graduation_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name_at_Completion__c</fullName>
        <label>Name at Completion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Obtained_Status__c</fullName>
        <label>Obtained Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <description>This field captures person id</description>
        <label>Person_ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Code__c</fullName>
        <description>This field describes the SMS award code</description>
        <label>Qualification_Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Grade__c</fullName>
        <description>This field captures the qualification/award grade</description>
        <label>Qualification_Grade</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Mark__c</fullName>
        <description>This field captures the marks on the qualification/award</description>
        <label>Qualification_Mark</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Name__c</fullName>
        <description>This field captures the name of the award/qualification in SMS</description>
        <label>Qualification_Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Type__c</fullName>
        <label>Qualification_Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Testamur_Type__c</fullName>
        <description>This field captures the testamur type for the qulification</description>
        <label>Testamur_Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Thesis_Title__c</fullName>
        <label>Thesis Title</label>
        <length>350</length>
        <type>LongTextArea</type>
    </fields>
    <label>Inbound Qualification</label>
    <pluralLabel>Inbound Qualifications</pluralLabel>
</CustomObject>

force-app/main/default/classes/IbdQualificationServices.cls
/**
* @author Ravi Nukala
* @date 26.04.2019
*
* @group Qualification
*
* @description 
* Platform Event handler for contact qualification. Call from subscribing trigger on the IbdQualification__e object.</br>
*
* Contact Qualifications handled by this integration are Monash Teritary quals. They exist with the context of a Course Attempt. 
* Unit Set Attempts are linked to a qualification when the qualification is awarded.<br/>
*
* Retry exceptions are raised for various criteria. There are risks.
* https://developer.salesforce.com/docs/atlas.en-us.platform_events.meta/platform_events/platform_events_subscribe_apex_refire.htm
*
* Delete events set a deleted_in_source flag wich can be used as a filter criteria in the record purge scheduled job.
*
* Supporting test class: IbdQualificationServices_Test<br/>
*
* @revision
* 26.04.2019 Ravi Nukala - Initial version<br/>
* 01.08.2019 Martin Cadman - Added various field mapping changes.<br/>  
* 01.09.2019 Martin Cadman - Added retry exception handling.<br/>
* 07.09.2019 Martin Cadman - Extended retry exception handling to include parental record locking. <br/>
* 31.12.2019 Martin Cadman - Allowed inserts to undelete (unset the flag) a record. <br/>
* 11.11.2020 Martin Cadman - Aligned code with other inbound classes to ensure deletes are handled correctly with a batch. <br/>
*
*/
public class IbdQualificationServices {
    private static final Integer MAXRETRIES = 3;

    // Exception to allow an eventbus retry to be bubbled up
    public class MyRetryException extends Exception {}

    private static final String SCENARIO = 'Inbound Awards';
    
    // Different log message formats    
    private static String msgfmt0 = '{0} {1}';
    private static String msgfmt1 = '{0} - {1}';
    private static String msgfmt2 = '{0}\r\r{1}';
    private static String msgfmt3 = '{0} - {1}\r\r{2}';    

    public class EventHandler extends TriggerAbstract {

        public override void execute() {
        	// The unique map of the records to be processed        
	        Map<String,IbdQualification__e> aDeleteMap = new Map<String, IbdQualification__e>();
    	    Map<String,IbdQualification__e> aUpsertMap = new Map<String, IbdQualification__e>();
            List<Contact_Qualification__c> upsertList = new List<Contact_Qualification__c>();
            List<Contact_Qualification__c> deleteList = new List<Contact_Qualification__c>();
            String jsonEvent;
            nebula.LogMessage logMsg;
        	String tId;

            // Set logging to the inbound event scenario, which controls the default logging level etc.
			// See the Logger Scenario Rules custom metadata
            nebula.Logger.setScenario(SCENARIO);       

			// Allow for logs to be linked across event retired by inserting the initial transaction id in the error message
            tId = nebula.Logger.getTransactionId();
            if (EventBus.TriggerContext.currentContext().lastError != null) {
                tId = EventBus.TriggerContext.currentContext().lastError.subStringBetween('[[',']]');
                if (String.isNotEmpty(tId)) {
	                nebula.Logger.setParentLogTransactionId(tId);
                }
            } 
            
			nebula.logger.debug('Award Batchsize ' + trigger.size);
            for (sObject record : trigger.new) {
                IbdQualification__e iEvent = (IbdQualification__e)record;
				jsonEvent = JSON.serializePretty(iEvent);
                try {
                    if(!String.isBlank(iEvent.Person_ID__c) && !String.isBlank(iEvent.Course_Code__c) && !String.isBlank(iEvent.Course_Version__c)&& !String.isBlank(iEvent.Qualification_Code__c )) {
                        Switch on (iEvent.Event_Type__c!=null?iEvent.Event_Type__c.touppercase():'UNKNOWN') {
                            when 'INSERT','UPDATE' {aUpsertMap.put(getUniquekey(iEvent), iEvent);}
                            when 'DELETE' {aDeleteMap.put(getUniqueKey(iEvent), iEvent); }
                            when else {
                                logMsg = new nebula.LogMessage(msgfmt3, iEvent.Person_ID__c,'Invalid Event Type', jsonEvent);
			                    nebula.logger.ERROR(logMsg);
                            }
                        }
                    } else {
                        logMsg = new nebula.LogMessage(msgfmt3, iEvent.Person_ID__c,'Mandatory field not included\rPerson_ID__c, Course_Code__c, Course_Version__c and Qualification_Code__c must be specified', jsonEvent);
	                    nebula.logger.ERROR(logMsg);
                    }
                } catch (Exception ex) {
					nebula.logger.exception(ex.getMessage(), ex);
                } 
            }

            nebula.logger.debug('Awards for processing: ' + Integer.valueOf(aUpsertMap.size() + aDeleteMap.size()));
            try {
                if (aUpsertMap.size() + aDeleteMap.size() > 0) {
                    if (aUpsertMap.size() > 0) {
                        for (IbdQualification__e iEvent : aUpsertMap.values()) {          
							jsonEvent = JSON.serializePretty(iEvent);
                            logMsg = new nebula.LogMessage(msgfmt3, iEvent.Person_ID__c+'/'+iEvent.Qualification_Code__c, 'Award Upsert', jsonEvent);
                            nebula.logger.info(logMsg);
                            upsertList.add(this.mapEventToObject(iEvent));
                        }
                    }
                    
                    if (aDeleteMap.size() > 0) {
                        for (IbdQualification__e iEvent : aDeleteMap.values()) {          
							jsonEvent = JSON.serializePretty(iEvent);
                            logMsg = new nebula.LogMessage(msgfmt3, iEvent.Person_ID__c+'/'+iEvent.Qualification_Code__c, 'Award Delete', jsonEvent);
                            nebula.logger.info(logMsg);
                            deleteList.add(this.mapDeleteEventToObject(iEvent));
                        }
                    }                
                }

				nebula.logger.debug('Awards to be upserted: '+upsertList.size());
                if (upsertList.size() > 0) {
                	Database.UpsertResult [] upsertResults = Database.upsert(upsertList, Contact_Qualification__c.Fields.Unique_External_Id__c , false);
                    Database.UpsertResult aResult = null;
                    for (Integer i=0; i<upsertResults.size(); i++) {
                        aResult = upsertResults[i];
                        if (!aResult.isSuccess()) {
                            for (Database.Error err : aResult.getErrors()) {
                                Switch on (err.getStatusCode()) {
                                    when UNABLE_TO_LOCK_ROW, INVALID_FIELD {
                                        if (EventBus.TriggerContext.currentContext().retries < MAXRETRIES) {
                                            logMsg = new nebula.LogMessage(msgfmt1, upsertList[i].Person_ID__c, 'Retry Award ' + String.valueOf(EventBus.TriggerContext.currentContext().retries+1) + ' - ' + err.getMessage());
	                                        nebula.logger.warn (logMsg, aResult);
                                            throw new MyRetryException(err.getMessage());
                                        } else {
                                            logMsg = new nebula.LogMessage(msgfmt1,upsertList[i].Person_ID__c,'Maximum retries (' + MAXRETRIES + ') reached for Award - ' + err.getMessage());
                                            nebula.logger.error (logMsg, aResult);
                                        }
                                    }
                                    when else {
                                        logMsg = new nebula.LogMessage(msgfmt1,upsertList[i].Person_ID__c, 'Award upsert error - ' + err.getMessage());
                                        nebula.logger.error(LogMsg, aResult);
                                    }
                                }                                
                            }
                        } else {
                            nebula.logger.fine('Award successfully ' + String.valueOf(aResult.isCreated()?'created':'updated') ,aResult.getId());
                        }
                    }
                } 
                    
                // Process the deletes in this batch last
				nebula.logger.debug('Awards to be deleted: ' + deleteList.size());
                if (deleteList.size() > 0) {
                    Database.UpsertResult [] deleteResults = Database.upsert(deleteList, Contact_Qualification__c.Fields.Unique_External_Id__c, false);
                    Database.UpsertResult aDelResult = null;
                    for (Integer i=0; i<deleteResults.size(); i++) {
                        aDelResult = deleteResults[i];
                        if (!aDelResult.isSuccess()) {
                            for (Database.Error err : aDelResult.getErrors()) {
                                Switch on (err.getStatusCode()) {
                                    when UNABLE_TO_LOCK_ROW, INVALID_FIELD {
                                        if (EventBus.TriggerContext.currentContext().retries < MAXRETRIES) {
                                            logMsg = new nebula.LogMessage(msgfmt1, deleteList[i].Person_ID__c, 'Retry Award (soft delete) ' + String.valueOf(EventBus.TriggerContext.currentContext().retries+1) + ' - ' + err.getMessage());
	                                        nebula.logger.warn (logMsg, aDelResult);
                                            throw new MyRetryException(err.getMessage());
                                        } else {
                                            logMsg = new nebula.LogMessage(msgfmt1,deleteList[i].Person_ID__c, 'Maximum retries (' + MAXRETRIES + ') reached for Award - ' + err.getMessage());
                                            nebula.logger.error (logMsg, aDelResult);
                                        }
                                    }
                                    when else {
                                        logMsg = new nebula.LogMessage(msgfmt1,deleteList[i].Person_ID__c, 'Award upsert (delete) error - ' + err.getMessage());
                                        nebula.logger.error(LogMsg, aDelResult);
                                    }
                                }                                
                            }
                        } else {
                            nebula.logger.fine('Award successfully (soft) deleted',aDelResult.getId());
                        }
                    }
                } 
            } catch (MyRetryException mex) {
				// A retry replays the entire batch, so there is no need to duplicate the logs for each.
				// This does delay when the first message is avaliable in the logs
                if (!nebula.logger.isDebugEnabled()) {nebula.logger.flushBuffer();}
                throw new EventBus.RetryableException('Award Retry ' + (EventBus.TriggerContext.currentContext().retries + 1) + ' of ' + MAXRETRIES +'\r' + mex.getMessage() + '\r[[' + tId + ']]'); // add logger transaction id
            } catch (Exception e) { 
                nebula.logger.exception(e.getMessage() ,e);
            } finally {
                nebula.logger.saveLog();                
            }
        }

        /**
        @description Builds the UK for the Object
        @param iEvent An individual inbound event
        @return A String representations of the UK 
        */
        private string getUniqueKey(IbdQualification__e iEvent) {
            return iEvent.Person_ID__c + '_' + iEvent.Course_Code__c + '_' +iEvent.Course_Version__c + '_' + iEvent.Qualification_Code__c;
        }

        /**
        @description Builds a individual CQ - field mappings, including lookups and literals, go here.
        @param iEvent An individual inbound event
        @return A populated base-object with values mapped from the inbound event

		{
		"Course_Version__c" : "2",
        "Qualification_Code__c" : "9080",
        "Award_Faculty_Name__c" : "Monash University English Language Centre",
        "Award_Faculty_Code__c" : "50028341",
        "Award_Faculty_Start_Date__c" : "2004-01-01",
        "Award_Institution_Name__c" : "MONASH COLLEGE",
        "Event_Type__c" : "DELETE",
        "Qualification_Name__c" : "Certificate of English (Customised Study Groups)",
        "Award_Institution_Code__c" : "4340",
        "Date_Achieved__c" : "2016-08-02",
        "Obtained_Status__c" : "NON-MONASH-OBTAINED",
        "Testamur_Type__c" : "COMPCSP",
        "Graduation_Date__c" : "2016-07-15",
        "Qualification_Type__c" : "awards",
        "Course_Code__c" : "3649",
        "Person_ID__c" : "28233948"
        }

		For a delete event we do not demand a valid course attempt lookup, just the miniumum fields.

		*/
        private Contact_Qualification__c mapDeleteEventToObject(IbdQualification__e iEvent) {
            Contact_Qualification__c qualification = new Contact_Qualification__c();

            // Unique Key
            qualification.Unique_External_Id__c = getUniqueKey(iEvent);

            // FK
			qualification.Contact__r = new Contact(Person_id_unique__c = iEvent.Person_ID__c);

			// Record Type
            qualification.RecordTypeId = Schema.SObjectType.Contact_Qualification__c.getRecordTypeInfosByName().get('Tertiary Education').getRecordTypeId();

            // Fields Mappings
            qualification.Qualification_Code__c = iEvent.Qualification_Code__c;
            qualification.Obtained_Status__c = iEvent.Obtained_Status__c;
            qualification.Name_at_Completion__c = iEvent.Name_at_Completion__c;
            qualification.Person_id__c = iEvent.Person_ID__c;
			qualification.deleted_on_source__c = true;            

            return qualification;
        }
 
		/*
		* @description Returns a populated contact qualification object
		* @param iEvent A single inbound event record
		* @return A contact qualification record populated from the inbound event, including calculated lookups and composite fields. 

		{
        "Course_Version__c" : "5",
        "Qualification_Code__c" : "3007",
        "Award_Faculty_Name__c" : "Faculty of Science",
        "Award_Faculty_Code__c" : "50000570",
        "Award_Faculty_Start_Date__c" : "1985-01-01",
        "Award_Institution_Name__c" : "MONASH UNIVERSITY",
        "Event_Type__c" : "INSERT",
        "Qualification_Name__c" : "Doctor of Philosophy",
        "Award_Institution_Code__c" : "3035",
        "Date_Achieved__c" : "2020-11-10",
        "Obtained_Status__c" : "MONASH-OBTAINED",
        "Testamur_Type__c" : "DEGREE",
        "Thesis_Title__c" : "The Water-energy Nexus Framework in Urban Water Management at Precinct Scale",
        "Qualification_Type__c" : "awards",
        "Course_Code__c" : "0057",
        "Person_ID__c" : "25377647"
        }

		*/        
        private Contact_Qualification__c mapEventToObject(IbdQualification__e iEvent) {
            Contact_Qualification__c qualification = new Contact_Qualification__c();

            // Unique Key
            qualification.Unique_External_Id__c = getUniqueKey(iEvent);

            // FK
            qualification.Contact__r = new Contact(Person_id_unique__c = iEvent.Person_ID__c);
            if (iEvent.Person_ID__c != null && iEvent.Course_Code__c != null) { qualification.Course_Attempt__r = new Course_Attempt__c (Callista_External_Id__c = iEvent.Person_ID__c + '_' + iEvent.Course_Code__c);}
            if (iEvent.Award_Faculty_Code__c != null) { qualification.Faculty__r = new Account (Callista_Org_Unit_code__c = iEvent.Award_Faculty_Code__c );}
            
            // Record Type
            qualification.RecordTypeId = Schema.SObjectType.Contact_Qualification__c.getRecordTypeInfosByName().get('Tertiary Education').getRecordTypeId();
            
            // Fields Mappings
            qualification.Person_id__c = iEvent.Person_ID__c;
            qualification.Testamur_Type__c = iEvent.Testamur_Type__c;
            qualification.Qualification_Code__c = iEvent.Qualification_Code__c;
            qualification.Qualification_Mark__c = iEvent.Qualification_Mark__c;
            qualification.Qualification_Grade__c = iEvent.Qualification_Grade__c;
            qualification.Title__c = iEvent.Qualification_Name__c;
            qualification.Other_Qualification__c = iEvent.Qualification_Name__c;
            qualification.Name_at_Completion__c = iEvent.Name_at_Completion__c;
            qualification.Obtained_Status__c = iEvent.Obtained_Status__c;
            
            qualification.Date_Achieved__c = iEvent.Date_Achieved__c;
            qualification.Graduation_Date__c = iEvent.Graduation_Date__c;
            qualification.Thesis_Title__c = iEvent.Thesis_Title__c;
            qualification.Institution_Name__c= iEvent.award_institution_name__c;
            qualification.Institution_Code__c= iEvent.award_institution_Code__c;
            qualification.Verification_Status__c='Verified'; // These are qualifications from Monash and 
            qualification.Instruction_in_English__c=true;

            if (iEvent.Event_Type__c.touppercase() == 'INSERT') {
                qualification.deleted_on_source__c = false;
            }

            return qualification;
        }
    }
}