force-app/main/default/objects/Contact_Relationship__c.object
<CustomObject>
    <description>used to join contacts to contacts, and describe the link between them</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>the student side of the relationship being described</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reciprocal_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup field which links the current relationship record to the reciprocal relationship record.</description>
        <label>Reciprocal Relationship</label>
        <referenceTo>Contact_Relationship__c</referenceTo>
        <relationshipLabel>Contact Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>the relation side of the relationship being described</description>
        <label>To Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Relationships (Relation)</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Effective from/start date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The Type of the relationship, i.e. describing the connection between contacts/persons.</description>
        <inlineHelpText>Describe this person&apos;s relationship to the new related contact</inlineHelpText>
        <label>Has this relationship</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Grandchild</fullName>
                    <label>Grand Child</label>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                    <label>Grand Parent</label>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Aunt/Uncle</fullName>
                </value>
                <value>
                    <fullName>Great Aunt/Uncle</fullName>
                </value>
                <value>
                    <fullName>Great Grand Child</fullName>
                </value>
                <value>
                    <fullName>Great Grand Parent</fullName>
                </value>
                <value>
                    <fullName>Great Niece/Nephew</fullName>
                </value>
                <value>
                    <fullName>Mother/Father in Law</fullName>
                </value>
                <value>
                    <fullName>Niece/Nephew</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Sister/Brother in Law</fullName>
                </value>
                <value>
                    <fullName>Son/Daughter in Law</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Step Child</fullName>
                </value>
                <value>
                    <fullName>Step Mother/Father</fullName>
                </value>
                <value>
                    <fullName>Widow</fullName>
                    <label>Widow/Widower</label>
                </value>
                <value>
                    <fullName>Deceased Spouse</fullName>
                    <label>Spouse (Deceased)</label>
                </value>
                <value>
                    <fullName>Colleague</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Estate Executor</fullName>
                </value>
                <value>
                    <fullName>Estate Testator</fullName>
                </value>
                <value>
                    <fullName>Guardian</fullName>
                </value>
                <value>
                    <fullName>Ward</fullName>
                </value>
                <value>
                    <fullName>Advisee</fullName>
                    <isActive>false</isActive>
                    <label>Advisee</label>
                </value>
                <value>
                    <fullName>Advisor</fullName>
                    <isActive>false</isActive>
                    <label>Advisor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <displayFormat>REL-{000000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Name__c.object
<CustomObject>
    <description>Name of a person (Contact)</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Relationship to Contact.</description>
        <inlineHelpText>Please provide the contact record this name is linked to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Names</relationshipLabel>
        <relationshipName>Names</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This defines the date until the name is valid for.</description>
        <inlineHelpText>Please provide the date the name is valid through, or leave it empty if it is not known or not end dated.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First (given) name.</description>
        <inlineHelpText>Please provide the first (given) name.</inlineHelpText>
        <label>First name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name.</description>
        <inlineHelpText>Please provide the last (family) name.</inlineHelpText>
        <label>Last name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date the name is valid from.</description>
        <inlineHelpText>Please provide a date indicating the valid from for the name.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the name.</description>
        <inlineHelpText>Please enter the name type</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Common</fullName>
                    <default>true</default>
                    <label>Common name</label>
                </value>
                <value>
                    <fullName>Maiden</fullName>
                    <label>Maiden name</label>
                </value>
                <value>
                    <fullName>Legal</fullName>
                    <label>Legal name</label>
                </value>
                <value>
                    <fullName>Non_Anglicised</fullName>
                    <label>Non-anglicised name</label>
                </value>
                <value>
                    <fullName>Birth name</fullName>
                </value>
                <value>
                    <fullName>Student name</fullName>
                </value>
                <value>
                    <fullName>Stage name</fullName>
                </value>
                <value>
                    <fullName>Other name</fullName>
                </value>
                <value>
                    <fullName>Anglicised</fullName>
                    <isActive>false</isActive>
                    <label>Anglicised</label>
                </value>
                <value>
                    <fullName>Artist</fullName>
                    <isActive>false</isActive>
                    <label>Artist</label>
                </value>
                <value>
                    <fullName>Full name</fullName>
                    <isActive>false</isActive>
                    <label>Full name</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Name</label>
    <nameField>
        <displayFormat>NAM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactRelationshipServices_Test.cls
/**
* @author          Ajitabh
* @description     This class contains unit tests for validating the behavior of ContactRelationshipServices methods.
* @revision 
*/
@isTest(isParallel=true)
private class ContactRelationshipServices_Test{
    
    @testSetup
    static void setup() {
        
        // create four contacts - two pairs
        List<Contact> testContacts = TestHelper.createOrphanContactRecords(4);
        testContacts[0].Person_Id_unique__c = 'Man Partnered';
        testContacts[1].Person_Id_unique__c = 'Woman Partnered';
        testContacts[2].Person_Id_unique__c = 'Man unPartnered';
        testContacts[3].Person_Id_unique__c = 'Woman unPartnered';
        insert testContacts;
        // Create name entries
        List<Name__c> testNames = new List<Name__c>();
        testNames.add(new Name__c(Contact__c = testContacts[0].id, First_Name__c = 'Man', Last_Name__c ='Partnered'));
        testNames.add(new Name__c(Contact__c = testContacts[1].id,First_Name__c = 'Woman', Last_Name__c ='Partnered'));
        testNames.add(new Name__c(Contact__c = testContacts[2].id,First_Name__c = 'Man', Last_Name__c ='unPartnered'));
        testNames.add(new Name__c(Contact__c = testContacts[3].id,First_Name__c = 'Woman', Last_Name__c ='unPartnered'));
        insert testNames;
		// Create relationships  
		List<Contact_Relationship__c> relationships = new List<Contact_Relationship__c>();      
		// Partnered relationship
        relationships.add (new Contact_Relationship__c(
        	Contact__c=testContacts[0].Id,
        	Related_Contact__c=testContacts[1].Id,
      		Start_Date__c = System.today().addDays(-45),
        	Type__c ='Spouse'));

        // unpartnered relationship
        relationships.add(new Contact_Relationship__c(
        Contact__c=testContacts[2].Id,
        Related_Contact__c=testContacts[3].Id,
        Start_Date__c = System.today().addDays(-45),
        Type__c ='Friend'));
        // Insert
        insert relationships;
    }
    
    @isTest
    static void testCreateReciprocalRelationship() {
        // Given
        Contact originalContact = [SELECT id FROM Contact WHERE Person_Id_unique__c = 'Man Partnered'];
        Contact_Relationship__c originalContactRelationship = [SELECT Id, Reciprocal_Relationship__c FROM Contact_Relationship__c WHERE Contact__c =:originalContact.Id AND Type__c ='Spouse'];
        Contact_Relationship__c reciprocalRelationship = [SELECT Id, Start_Date__c, Type__c, Reciprocal_Relationship__c, Contact__c
                                                          FROM Contact_Relationship__c
                                                          WHERE Reciprocal_Relationship__c = :originalContactRelationship.Id
                                                          LIMIT 1];
        // Then
        System.assertEquals('Spouse',reciprocalRelationship.Type__c ,'Recipical relationship of type Spouse exists');
    }
    
    @isTest
    static void testUpdateReciprocalRelationship() {

        Contact originalContact = [SELECT id FROM Contact WHERE Person_Id_unique__c = 'Man Partnered'];
        Contact_Relationship__c originalContactRelationship = [SELECT Id, Reciprocal_Relationship__c FROM Contact_Relationship__c WHERE Contact__c =:originalContact.Id AND Type__c ='Spouse'];

        originalContactRelationship.Type__c = 'Friend';
        originalContactRelationship.Start_Date__c = System.today();
        originalContactRelationship.End_Date__c = System.today().addDays(1);
        Test.startTest();
        update originalContactRelationship;
        Contact_Relationship__c reciprocalRelationship = [SELECT Id, Start_Date__c,End_Date__c, Type__c, Reciprocal_Relationship__c, Contact__c
                                                          FROM Contact_Relationship__c
                                                          WHERE Reciprocal_Relationship__c =:originalContactRelationship.Id
                                                          LIMIT 1];
        Test.stopTest();
        System.assertEquals('Friend', reciprocalRelationship.Type__c,'Reciprocal Relationship Type should reflect the Relationship Type ');	
        System.assertEquals(originalContactRelationship.Start_Date__c, reciprocalRelationship.Start_Date__c,'Start Date should be the same as the Relationship Type');
        System.assertEquals(originalContactRelationship.End_Date__c, reciprocalRelationship.End_Date__c,'End Date should be the same as the Relationship Type');
    }
    
    @isTest
    static void testUpdateRelationshipWithEndDate() {

        Contact originalContact = [SELECT id FROM Contact WHERE Person_Id_unique__c = 'Man Partnered'];
        Contact_Relationship__c originalContactRelationship = [SELECT Id, Reciprocal_Relationship__c FROM Contact_Relationship__c WHERE Contact__c =:originalContact.Id LIMIT 1];
		
        originalContactRelationship.End_Date__c = System.today();
        Test.startTest();
        update originalContactRelationship;
        Test.stopTest();
        Contact_Relationship__c reciprocalRelationship = [SELECT Id, Start_Date__c, End_Date__c, Type__c, Reciprocal_Relationship__c, Contact__c
                                                          FROM Contact_Relationship__c
                                                          WHERE Reciprocal_Relationship__c =:originalContactRelationship.Id
                                                          LIMIT 1];
        System.assertEquals(originalContactRelationship.End_Date__c, reciprocalRelationship.End_Date__c,'End Date should be the same as the Relationship Type');
        
        List<ucinn_ascendv2__Salutation__c> jointSalutations = 
            [SELECT id 
            FROM ucinn_ascendv2__Salutation__c
            WHERE ucinn_ascendv2__Salutation_Record_Type_Formula__c = 'Joint'
            And ucinn_ascendv2__Contact__c = :originalContact.id];
        
        System.assertEquals(0, jointSalutations.size(),'Joint salutation should be removed after end date is updated');
        
    }
    
    @isTest
    static void testUpdateRelationshipTypeSpouse() {
        Contact originalContact = [SELECT id FROM Contact WHERE Person_Id_unique__c = 'Man unPartnered'];
        Contact_Relationship__c originalContactRelationship = [SELECT Id, Reciprocal_Relationship__c FROM Contact_Relationship__c WHERE Contact__c =:originalContact.Id AND Type__c ='Friend'];
        originalContactRelationship.Type__c = 'Spouse';
        Test.startTest();
        update originalContactRelationship;
        Test.stopTest();
        System.assertEquals(originalContactRelationship.Type__c, 'Spouse' ,'Relation Type changed to Spouse.');
    }
    
    @isTest
    static void testUpdateRelationshipTypePartner() {
   		Contact originalContact = [SELECT id FROM Contact WHERE Person_Id_unique__c = 'Man Partnered'];



        Contact_Relationship__c originalContactRelationship = [SELECT id, Reciprocal_Relationship__c FROM Contact_Relationship__c WHERE Contact__c =:originalContact.Id AND Type__c ='Spouse'];

        originalContactRelationship.Type__c = 'Partner';
        Test.startTest();
        update originalContactRelationship;
        Test.stopTest();
        System.assertEquals(originalContactRelationship.Type__c, 'Partner' ,'Relation Type changed to Partner.');
        
                List<ucinn_ascendv2__Salutation__c> jointSalutations = 
            [SELECT id,ucinn_ascendv2__Contact__c ,ucinn_ascendv2__Contact_2__c 
             FROM ucinn_ascendv2__Salutation__c
             WHERE ucinn_ascendv2__Salutation_Record_Type_Formula__c = 'Joint'
             And ucinn_ascendv2__Contact__c = :originalContact.id];
        
        System.assertEquals(2, jointSalutations.size(),'Joint Sal should be maintained when changing from Spouse to Partner');

    }
    
    @isTest
    static void testUpdateRelationshipTypeWidow() {

        Contact originalContact = [SELECT id FROM Contact WHERE Person_Id_unique__c = 'Woman Partnered'];
        Contact_Relationship__c originalContactRelationship = [SELECT id, Reciprocal_Relationship__c FROM Contact_Relationship__c WHERE Contact__c =:originalContact.Id AND Type__c ='Spouse'];

        originalContactRelationship.Type__c = 'Widow';
        Test.startTest();
        update originalContactRelationship;
        Test.stopTest();
        System.assertEquals(originalContactRelationship.Type__c, 'Widow' ,'Relation Type changed to Widow.');
        
        List<ucinn_ascendv2__Salutation__c> jointSalutations = 
            [SELECT id 
            FROM ucinn_ascendv2__Salutation__c
            WHERE ucinn_ascendv2__Salutation_Record_Type_Formula__c = 'Joint'
            And ucinn_ascendv2__Contact__c = :originalContact.id];
        
        System.assertEquals(0, jointSalutations.size(),'Joint salutation should be removed after partner is widowed');
        
        
        
    }
    
    @isTest
    static void testUpdateRelationshipTypeDeceasedSpouse() {

        Contact originalContact = [SELECT id FROM Contact WHERE Person_Id_unique__c = 'Man Partnered'];
        Contact_Relationship__c originalContactRelationship = [SELECT id, Reciprocal_Relationship__c FROM Contact_Relationship__c WHERE Contact__c =:originalContact.Id AND Type__c ='Spouse'];

        originalContactRelationship.Type__c = 'Deceased Spouse';
        Test.startTest();
        update originalContactRelationship;
        Test.stopTest();
        System.assertEquals(originalContactRelationship.Type__c, 'Deceased Spouse' ,'Relation Type changed to Deceased Spouse.');
        
                List<ucinn_ascendv2__Salutation__c> jointSalutations = 
            [SELECT id 
            FROM ucinn_ascendv2__Salutation__c
            WHERE ucinn_ascendv2__Salutation_Record_Type_Formula__c = 'Joint'
            And ucinn_ascendv2__Contact__c = :originalContact.id];
        
        System.assertEquals(0, jointSalutations.size(),'Joint salutation should be removed after partner is deceased');
    }
    
    @isTest
    static void testMixedUpdateRelationships() {
		// get two different relationship types
        Contact friendContact = [SELECT id FROM Contact WHERE Person_Id_unique__c = 'Man unPartnered'];
        Contact_Relationship__c friendContactRelationship = [SELECT Id, Reciprocal_Relationship__c FROM Contact_Relationship__c WHERE Contact__c =:friendContact.Id AND Type__c ='Friend'];
        Contact partneredContact = [SELECT id FROM Contact WHERE Person_Id_unique__c = 'Man Partnered'];
        Contact_Relationship__c partneredContactRelationship = [SELECT id, Reciprocal_Relationship__c FROM Contact_Relationship__c WHERE Contact__c =:partneredContact.Id AND Type__c ='Spouse'];
		// Add joint salutaiton
          

        
        friendContactRelationship.Type__c = 'Spouse';
        partneredContactRelationship.Type__c = 'Friend';
        
        Test.startTest();
         update new List<Contact_Relationship__c>{friendContactRelationship,partneredContactRelationship};
        Test.stopTest();
        
        List<ucinn_ascendv2__Salutation__c> jointSalutationsNew = 
            [SELECT id,ucinn_ascendv2__Contact__c ,ucinn_ascendv2__Contact_2__c 
            FROM ucinn_ascendv2__Salutation__c
            WHERE ucinn_ascendv2__Salutation_Record_Type_Formula__c = 'Joint'
            And (ucinn_ascendv2__Contact__c = :friendContact.id OR ucinn_ascendv2__Contact__c = :partneredContact.id)
            ORDER BY ucinn_ascendv2__Contact__r.Person_Id_unique__c];
        
        System.assertEquals(2, jointSalutationsNew.size(),'There should be an inner and outer joint salutation for a new relationship and removed for the old relationship');
        System.assertEquals(friendContact.id, jointSalutationsNew[0].ucinn_ascendv2__Contact__c,'Joint salutation should belong to the new relationship');
        System.assertEquals(friendContact.id, jointSalutationsNew[1].ucinn_ascendv2__Contact__c,'Joint salutation should belong to the new relationship');
    }
    
    @isTest
    static void testQueryCustomMetaData(){
        Test.startTest();
        Map<String,String> relationTypeMap = ContactRelationshipServices.getReciprocalRelationshipMap();
        Test.stopTest();
    }
    
    @isTest
    static void testDeleteReciprocalRelationship() {
        Contact originalContact = [SELECT id FROM Contact WHERE Person_Id_unique__c = 'Man Partnered'];
        Contact_Relationship__c originalContactRelationship = [SELECT id, Reciprocal_Relationship__c FROM Contact_Relationship__c WHERE Contact__c =:originalContact.Id AND Type__c ='Spouse'];
        Contact_Relationship__c reciprocalRelationship = [SELECT Id, Start_Date__c, Type__c, Reciprocal_Relationship__c, Contact__c
                                                          FROM Contact_Relationship__c
                                                          WHERE Reciprocal_Relationship__c =:originalContactRelationship.Id
                                                          LIMIT 1];
        Test.startTest();
        delete reciprocalRelationship;
        // System.assert(caRec.Id != null, 'Course could not be inserted.');
        // retrieve result record
        List<Contact_Relationship__c> reciprocalRels = [SELECT Id, Start_Date__c, Type__c, Reciprocal_Relationship__c
                                                        FROM Contact_Relationship__c
                                                        WHERE Reciprocal_Relationship__c =:reciprocalRelationship.Id
                                                        LIMIT 1];
        Test.stopTest();
        System.assertEquals(0, reciprocalRels.size(),'record is deleted');
        
    }
}