force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <label>Person ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Level of Completion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ATTEMPTED BUT WAS NOT COMPLETED</fullName>
                </value>
                <value>
                    <fullName>CURRENTLY STUDYING</fullName>
                </value>
                <value>
                    <fullName>DISCONTINUED</fullName>
                </value>
                <value>
                    <fullName>SUCCESSFULLY COMPLETED AND OBTAINED</fullName>
                </value>
                <value>
                    <fullName>Completed Alternative Exit</fullName>
                    <isActive>false</isActive>
                    <label>Completed Alternative Exit</label>
                </value>
                <value>
                    <fullName>Completed not graduated</fullName>
                    <isActive>false</isActive>
                    <label>Completed not graduated</label>
                </value>
                <value>
                    <fullName>Graduated</fullName>
                    <isActive>false</isActive>
                    <label>Graduated</label>
                </value>
                <value>
                    <fullName>Graduated but no Grad Date in Callista</fullName>
                    <isActive>false</isActive>
                    <label>Graduated but no Grad Date in Callista</label>
                </value>
                <value>
                    <fullName>Study Abroad/CIC</fullName>
                    <isActive>false</isActive>
                    <label>Study Abroad/CIC</label>
                </value>
                <value>
                    <fullName>WILL BE COMPLETED BY ADMISSION</fullName>
                    <isActive>false</isActive>
                    <label>WILL BE COMPLETED BY ADMISSION</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The Qualificaiton Title</description>
        <label>Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The Qualificaiton Type</description>
        <label>Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_External_Id__c</fullName>
        <description>The unique external id for Contact Qualification Object</description>
        <externalId>true</externalId>
        <label>Unique_External_Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Used to force uniqueness on course code. Updated from workflow.</description>
        <externalId>true</externalId>
        <label>Course Code Unique</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Course is Active ? Active/Inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Course full title</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of course being offered</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Academic_Course</fullName>
                    <label>Academic Course</label>
                </value>
                <value>
                    <fullName>Short_Course</fullName>
                    <label>Professional Development</label>
                </value>
                <value>
                    <fullName>Course-All</fullName>
                </value>
                <value>
                    <fullName>Unit Set</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attempt__c.object
<CustomObject>
    <description>Course attempt represents the courses a Contact is related to.</description>
    <fields>
        <fullName>Callista_External_Id__c</fullName>
        <description>Holds a concatenation of the Callista Person Id (from &apos;Contact.Person_Id_unique__c&apos;), and underscore(&apos;_&apos;), and the Course Code (from &apos;Course__c.Name&apos;). This is a unique combination (for academic courses).</description>
        <externalId>true</externalId>
        <inlineHelpText>This field is evaluated and set by the system.</inlineHelpText>
        <label>Callista_External_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Reference to the contact who pursues this course</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Contains the course code (without the version). It is derived from the Course lookup relationship.</description>
        <formula>Course__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to the course (incl. version) of the course attempt</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Value does not match the type of allowed courses an attempt record can be related to.</errorMessage>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Course-All</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short Course</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short_Course</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <label>Person Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Course Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Attempts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IbdUnitSetAttempt__e.object
<CustomObject>
    <description>Inbound student unit set attempts - major/minor/specialisations</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>This field captures the category</description>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>This field captures the course code of the course attempt</description>
        <label>Course_Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This filed is to capture the type of event example INSERT, UPDATE and DELETE</description>
        <label>Event_Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <description>Person Id</description>
        <label>Person ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_List__c</fullName>
        <description>A comma delimited list of Contact Qual unique keys</description>
        <label>Qualification List</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>This field captures the rank</description>
        <label>Rank</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>This field captures the sequence number of unit set attempt</description>
        <label>Sequence Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>This field captures title</description>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Set_Code__c</fullName>
        <description>This field captures the category</description>
        <label>Unit Set Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <description>This field captures version</description>
        <label>Course Version</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Inbound Unit Set Attempt</label>
    <pluralLabel>Inbound Unit Set Attempts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Unit_Set_Attempt__c.object
<CustomObject>
    <description>Majors, minors and specialisations. When seen against a Course Attempt, consider them inflight. Against a Contact Qualification, they are part of the award.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>This field captures category</description>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Unit Set Attempt</relationshipLabel>
        <relationshipName>Unit_Set_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>The course this unit set is attached to. System field, used to name the record.</description>
        <label>Course Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <label>Person ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>This field captures rank</description>
        <label>Rank</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>This field captures title</description>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_External_Id__c</fullName>
        <description>This field captures category</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <description>This field captures unit set version</description>
        <label>Version</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Unit Set Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Set Attempts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/IbdUnitSetAttemptTrigger_Test.cls
/**
* @author Jackie Ho
* @date   29-07-2025
* @group  Qualification
* @description Test class for IbdUnitSetAttemptTrigger
*
* @revision
* 29.07.2025 Jackie Ho - Initial version
**/
@isTest(isParallel=true)
private class IbdUnitSetAttemptTrigger_Test {
    
    /**
    * @description Test method to verify the trigger handles platform event publishing
    */
    @isTest
    static void testTriggerExecution() {
        // GIVEN: Setup test data
        // Disable some of the automation that occurs when contacts are created
        triggerCommon.disableTrigger('Contact');
        ucinn_ascendv2__Trigger_Handler__c disableEngageTrig = new ucinn_ascendv2__Trigger_Handler__c(ucinn_ascendv2__Object__c ='Contact',ucinn_ascendv2__Is_Active__c=False,ucinn_ascendv2__class__c='ascend_TRIG_Contact');
        insert disableEngageTrig;

        // Create test contact
        Contact iContact = new Contact();
        iContact.Person_Id_unique__c = '98765432';
        iContact.LastName = 'USALastname';
        iContact.FirstName = 'USAFirstname';
        iContact.SAP_Staff_Id__c = 'NoDupRules'; // this will filter the contact out of the most of the duplicate rules
        insert icontact;
        
        // Create test course         
        Course__c iCourse = new Course__c(Name='USACourseName', Course_Code__c = 'USACourseName_1', Version__c='1',Type__c = 'Course-All', Status__c='Active');
        insert iCourse;
        Course__c iUnitSet = new Course__c(Name='USAUnitSetName', Course_Code__c = 'USAUnitSetName_1', Version__c='1',Type__c = 'Unit Set', Status__c='Active');
        insert iUnitSet;

        // Create test course Attempt         
        Course_Attempt__c iCourseAttempt = new Course_Attempt__c();
        iCourseAttempt.Name = iContact.Person_Id_unique__c + '/USACourseName';
        iCourseAttempt.Contact__c = iContact.Id;
        iCourseAttempt.Course__c = iCourse.Id;
        String caCourseAttemptId = iContact.Person_Id_unique__c + '_USACourseName';
        iCourseAttempt.Callista_External_Id__c = caCourseAttemptId;
        insert iCourseAttempt;
         
         
        Contact_Qualification__c cq = new Contact_Qualification__c();
        cq.Contact__c = iContact.id;
        cq.Course_Attempt__c = iCourseAttempt.id;
        cq.Unique_External_Id__c = '98765432_1250_4208_7';
        insert cq;
        
        cq = new Contact_Qualification__c();
        cq.Contact__c = iContact.id;
        cq.Course_Attempt__c = iCourseAttempt.id;
        cq.Unique_External_Id__c = '98765432_1250_5482_7';
        insert cq;

        cq = new Contact_Qualification__c();
        cq.Contact__c = iContact.id;
        cq.Course_Attempt__c = iCourseAttempt.id;
        cq.Unique_External_Id__c = '98765432_1250_6042_7';
        insert cq;
        
        // Create Inbound Event Object
        IbdUnitSetAttempt__e inEvent = new IbdUnitSetAttempt__e();
        inEvent.Event_Type__c = 'INSERT';
        inEvent.Person_ID__c = '98765432';
        inEvent.Course_Code__c='USACourseName';
        inEvent.Title__c='USATitle';
        inEvent.Rank__c='TEST_QAL';
        inEvent.Category__c='1';
        inEvent.Unit_Set_Code__c='USAUnitSetName';
        inEvent.Version_Number__c='1';
        inEvent.Sequence_Number__c='12345';
        inEvent.Qualification_List__c = '98765432_1250_4208_7, 98765432_1250_6042_7';
        
        // WHEN: Publish the platform event
        Test.startTest();
        Database.SaveResult sr = EventBus.publish(inEvent);
        Test.stopTest();
        
        // THEN: Verify the event was published successfully
        Assert.isTrue(sr.isSuccess(), 'Failed to publish platform event');

        List<Unit_Set_Attempt__c> test = [SELECT Id FROM Unit_Set_Attempt__c order by CreatedDate desc limit 1];
        
        // THEN: Verify the trigger executed and processed the event through the service
        String uniqueExtId = inEvent.Person_ID__c + '_' + inEvent.Course_Code__c + '_' + 
                           inEvent.Unit_Set_Code__c + '_' + inEvent.Sequence_Number__c;
        
        List<Unit_Set_Attempt__c> results = [
            SELECT Id 
            FROM Unit_Set_Attempt__c 
            WHERE Unique_External_Id__c = :uniqueExtId
        ];
        
        // THEN: The service should have created a record
        Assert.areEqual(1, results.size(), 'Expected one Unit_Set_Attempt__c record to be created');
    }
    
    /**
    * @description Test method to verify the trigger handles bulk events
    */
    @isTest
    static void testBulkTriggerExecution() {
        // GIVEN: Setup test data
        // Disable some of the automation that occurs when contacts are created
        triggerCommon.disableTrigger('Contact');
        ucinn_ascendv2__Trigger_Handler__c disableEngageTrig = new ucinn_ascendv2__Trigger_Handler__c(ucinn_ascendv2__Object__c ='Contact',ucinn_ascendv2__Is_Active__c=False,ucinn_ascendv2__class__c='ascend_TRIG_Contact');
        insert disableEngageTrig;

        // Create test contacts
        List<Contact> testContacts = new List<Contact>();
        for (Integer i = 0; i < 5; i++) {
            Contact c = new Contact();
            c.Person_Id_unique__c = '9876543' + i;
            c.LastName = 'BulkTest' + i;
            c.FirstName = 'Test';
            c.SAP_Staff_Id__c = 'NoDupRules' + i;
            testContacts.add(c);
        }
        insert testContacts;
        
        // Create test course         
        Course__c iCourse = new Course__c(Name='BulkCourse', Course_Code__c = 'BULK123', Version__c='1', Type__c = 'Course-All', Status__c='Active');
        insert iCourse;
        
        // Create test unit set
        Course__c iUnitSet = new Course__c(Name='BulkUnitSet', Course_Code__c = 'BULKUS', Version__c='1', Type__c = 'Unit Set', Status__c='Active');
        insert iUnitSet;
        
        // Create test course attempts
        List<Course_Attempt__c> testCourseAttempts = new List<Course_Attempt__c>();
        for (Integer i = 0; i < testContacts.size(); i++) {
            Course_Attempt__c ca = new Course_Attempt__c();
            ca.Name = testContacts[i].Person_Id_unique__c + '/BulkCourse';
            ca.Contact__c = testContacts[i].Id;
            ca.Course__c = iCourse.Id;
            ca.Callista_External_Id__c = testContacts[i].Person_Id_unique__c + '_BulkCourse';
            testCourseAttempts.add(ca);
        }
        insert testCourseAttempts;
        
        // Create test Contact_Qualification__c records for each contact
        List<Contact_Qualification__c> quals = new List<Contact_Qualification__c>();
        
        for (Integer i = 0; i < testContacts.size(); i++) {
            // Add three qualifications per contact (matching the pattern in testTriggerExecution)
            quals.add(new Contact_Qualification__c(
                Contact__c = testContacts[i].Id,
                Course_Attempt__c = testCourseAttempts[i].Id,
                Unique_External_Id__c = testContacts[i].Person_Id_unique__c + '_1250_4208_7'
            ));
            
            quals.add(new Contact_Qualification__c(
                Contact__c = testContacts[i].Id,
                Course_Attempt__c = testCourseAttempts[i].Id,
                Unique_External_Id__c = testContacts[i].Person_Id_unique__c + '_1250_5482_7'
            ));
            
            quals.add(new Contact_Qualification__c(
                Contact__c = testContacts[i].Id,
                Course_Attempt__c = testCourseAttempts[i].Id,
                Unique_External_Id__c = testContacts[i].Person_Id_unique__c + '_1250_6042_7'
            ));
        }
        insert quals;
        
        // Create test platform events
        List<IbdUnitSetAttempt__e> testEvents = new List<IbdUnitSetAttempt__e>();
        for (Integer i = 0; i < testContacts.size(); i++) {
            testEvents.add(new IbdUnitSetAttempt__e(
                Event_Type__c = 'INSERT',
                Person_ID__c = testContacts[i].Person_Id_unique__c,
                Course_Code__c = 'BulkCourse',
                Title__c = 'BulkTestTitle',
                Rank__c = 'BULK_RANK',
                Category__c = '1',
                Unit_Set_Code__c = 'BulkUnitSet',
                Version_Number__c = '1',
                Sequence_Number__c = '100' + i,
                Qualification_List__c = testContacts[i].Person_Id_unique__c + '_1250_4208_7, ' + 
                                      testContacts[i].Person_Id_unique__c + '_1250_5482_7, ' +
                                      testContacts[i].Person_Id_unique__c + '_1250_6042_7'
            ));
        }
        
        // WHEN: Publish the platform events
        Test.startTest();
        List<Database.SaveResult> results = EventBus.publish(testEvents);
        Test.stopTest();
        
        // THEN: Verify all events were published successfully
        for (Database.SaveResult sr : results) {
            Assert.isTrue(sr.isSuccess(), 'Failed to publish platform event: ' + sr.getErrors());
        }
        
        // THEN: Verify the trigger executed and processed all events through the service
        List<Unit_Set_Attempt__c> createdAttempts = [
            SELECT Id, Unique_External_Id__c 
            FROM Unit_Set_Attempt__c 
            WHERE Rank__c = 'BULK_RANK'
        ];
        
        // THEN: Assert the number of Unit_Set_Attempt__c records created
        Assert.areEqual(testEvents.size(), createdAttempts.size(), 
                          'Expected ' + testEvents.size() + ' Unit_Set_Attempt__c records to be created');
    }
}