force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Achieved__c</fullName>
        <label>Date Achieved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Faculty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>(Managing/owning) faculty of the qualification (for university degrees).
Note: relevant for Monash Tertiary Education only.</description>
        <label>Faculty</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Faculty</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Qualifications (Organization)</relationshipLabel>
        <relationshipName>Contact_Qualifications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Graduation_Date__c</fullName>
        <description>This field captures graduation date</description>
        <label>Graduation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Institution_Name__c</fullName>
        <description>This is referencing the Institution_Name__c field of the Callista_Institutions__c Custom Setting</description>
        <label>Awarding Body/Institution Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Obtained_Status__c</fullName>
        <label>Obtained Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MONASH-OBTAINED</fullName>
                    <label>Monash Obtained</label>
                </value>
                <value>
                    <fullName>NON-MONASH-OBTAINED</fullName>
                    <label>Non-Monash Obtained</label>
                </value>
                <value>
                    <fullName>NOT-OBTAINED</fullName>
                    <label>Not Obtained</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The Qualificaiton Title</description>
        <label>Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Used to force uniqueness on course code. Updated from workflow.</description>
        <externalId>true</externalId>
        <label>Course Code Unique</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Course_Description__c</fullName>
        <externalId>true</externalId>
        <label>Course Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Faculty_Description__c</fullName>
        <externalId>true</externalId>
        <label>Faculty Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Faculty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Faculty record (via Org Unit)</description>
        <label>Faculty</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Account.Callista_Org_Unit_Code__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Faculty</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Monash Organisation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Course start date</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Level__c</fullName>
        <description>Course Sub-Level e.g. PG Diploma, PG Certificate, etc</description>
        <label>Sub Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PG Diploma</fullName>
                </value>
                <value>
                    <fullName>42</fullName>
                </value>
                <value>
                    <fullName>41</fullName>
                </value>
                <value>
                    <fullName>78</fullName>
                </value>
                <value>
                    <fullName>77</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>76</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>06G</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>07PG</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>09-1</fullName>
                </value>
                <value>
                    <fullName>09-4</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>07G</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>06PG</fullName>
                </value>
                <value>
                    <fullName>50PG</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>56</fullName>
                </value>
                <value>
                    <fullName>55</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Course full title</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attempt__c.object
<CustomObject>
    <description>Course attempt represents the courses a Contact is related to.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Reference to the contact who pursues this course</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Attempt_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Discontin</fullName>
                    <label>Discontinued</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>Unconfirm</fullName>
                    <label>Unconfirmed</label>
                </value>
                <value>
                    <fullName>Intermit</fullName>
                    <label>Intermission</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Contains the course code (without the version). It is derived from the Course lookup relationship.</description>
        <formula>Course__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to the course (incl. version) of the course attempt</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Value does not match the type of allowed courses an attempt record can be related to.</errorMessage>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Course-All</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short Course</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short_Course</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Attempts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Monash_Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global Monash Account record where Prospective Student&apos;s Roles will be associated with.</description>
    <fields>
        <fullName>Id__c</fullName>
        <description>Id of Global Monash Account</description>
        <label>Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Global Monash Account</label>
</CustomObject>

force-app/main/default/classes/ContactQualificationChangeEvent_Test.cls
/**
 * @author			Ajitabh
 * @group           Test Class
 * @description		Unit test for Contact_Qualification__ChangeEvent class
* @revision		8/12/2021 Ken McGuire added condition that course must be completed for specified locations in order to be Alumni
 */
@isTest(isParallel=false) // In parallel Apex tests, DML operations aren't permitted on this type of object: SourceMember:
public class ContactQualificationChangeEvent_Test {
   
    // test method to test contact profile field update on Contact
    @isTest static void testenableAlumniFlagOnContact() {
        Test.enableChangeDataCapture();
        string testname= 'name '+String.valueOf(System.now());
        id recordtypeids = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Faculty').getRecordTypeId();
        Account testaccount = new Account(name=testname,recordtypeid=recordtypeids);
        insert testaccount;

        String testLastname = 'Lastname ' + String.valueOf(System.now());
        Contact testContact = new Contact(Firstname='Test', Lastname=testLastname,contact_profile__c='');
        insert testContact;
       
        Course_Attempt__c ca = new Course_Attempt__c(
            	Course__c=createCourse(testaccount.id), 
            	Contact__c=testContact.Id
            	);
		insert ca;

        id recordTypeConQual = Schema.SObjectType.Contact_Qualification__c.getRecordTypeInfosByName().get('Tertiary Education').getRecordTypeId();
        insert new Contact_Qualification__C(
            	contact__c=testContact.id,
            	Obtained_status__c = ContactQualificationChangeEvent.OBTAINED_STATUS_MONASH,
            	faculty__c=testaccount.id,
            	Date_Achieved__c=system.today()-5,
            	Course_Attempt__c = ca.id,
                Institution_Name__c = ContactQualificationChangeEvent.INSTITUTION_MONASH,
                RecordTypeId = recordTypeConQual);
        Test.getEventBus().deliver();

        Contact [] conList=[select id,Study_at_Monash__c,contact_profile__c from contact];
        System.assertEquals('Alumni', conList[0].contact_profile__c,'The change event trigger did update contact');
        System.assertEquals(true, conList[0].Study_at_Monash__c,'The change event trigger updated contact preference');
    }
     // test method to test contact profile field update on Contact when the course attempt must be completed for new alumni
    @isTest static void testEnableAlumniFlagOnContactWhenCourseCompleted() {
        if(ContactQualificationChangeEvent.COURSE_MUST_BE_COMPLETED_LOCATIONS.size()==0) return;
        Test.enableChangeDataCapture();
        string testname= 'name '+String.valueOf(System.now());
        id recordtypeids = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Faculty').getRecordTypeId();
        Account testaccount = new Account(name=testname,recordtypeid=recordtypeids);
        insert testaccount;

        String testLastname = 'Lastname ' + String.valueOf(System.now());
        Contact testContact = new Contact(Firstname='Test', Lastname=testLastname,contact_profile__c='');
        insert testContact;
   		
        Course_Attempt__c ca = new Course_Attempt__c(
            	Course__c=createCourse(testaccount.id), 
            	Contact__c=testContact.Id,
            	Location__c = ContactQualificationChangeEvent.COURSE_MUST_BE_COMPLETED_LOCATIONS[0],
            	Course_Attempt_Status__c = ContactQualificationChangeEvent.COURSE_ATTEMPT_STATUS_COMPLETED);
		insert ca;
        id recordTypeConQual = Schema.SObjectType.Contact_Qualification__c.getRecordTypeInfosByName().get('Tertiary Education').getRecordTypeId();
        insert new Contact_Qualification__C(
            	contact__c=testContact.id,
            	Obtained_status__c = ContactQualificationChangeEvent.OBTAINED_STATUS_MONASH,
            	faculty__c=testaccount.id,
            	Date_Achieved__c=system.today()-5,
                Graduation_Date__c = system.today(),
        		Course_Attempt__c = ca.id,
                Institution_Name__c = ContactQualificationChangeEvent.INSTITUTION_MONASH,
                RecordTypeId = recordTypeConQual);
        Test.getEventBus().deliver();

        Contact [] conList=[select id,Study_at_Monash__c,contact_profile__c from contact];
        System.assertEquals('Alumni', conList[0].contact_profile__c,'The change event trigger did update contact');
        System.assertEquals(true, conList[0].Study_at_Monash__c,'The change event trigger updated contact preference');
    }
    // test method to test contact profile field update on Contact when the course attempt must be completed for new alumni but has not been.
    @isTest static void testEnableAlumniFlagOnContactWhenCourseNotCompleted() {
        if(ContactQualificationChangeEvent.COURSE_MUST_BE_COMPLETED_LOCATIONS.size()==0) return;
        Test.enableChangeDataCapture();
        string testname= 'name '+String.valueOf(System.now());
        id recordtypeids = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Faculty').getRecordTypeId();
        Account testaccount = new Account(name=testname,recordtypeid=recordtypeids);
        insert testaccount;

        String testLastname = 'Lastname ' + String.valueOf(System.now());
        Contact testContact = new Contact(Firstname='Test', Lastname=testLastname,contact_profile__c='');
        insert testContact;
       
        Course_Attempt__c ca = new Course_Attempt__c(Course__c= createCourse(testaccount.id), Contact__c=testContact.Id,Location__c = ContactQualificationChangeEvent.COURSE_MUST_BE_COMPLETED_LOCATIONS[0]);
        insert ca;
        id recordTypeConQual = Schema.SObjectType.Contact_Qualification__c.getRecordTypeInfosByName().get('Tertiary Education').getRecordTypeId();
        insert new Contact_Qualification__C(
            	contact__c=testContact.id,
            	Obtained_status__c = ContactQualificationChangeEvent.OBTAINED_STATUS_MONASH,
            	faculty__c=testaccount.id,
            	Date_Achieved__c=system.today()-5,
        		Course_Attempt__c = ca.id,
                Institution_Name__c = ContactQualificationChangeEvent.INSTITUTION_MONASH,
                RecordTypeId = recordTypeConQual);
        Test.getEventBus().deliver();

        Contact [] conList=[select id,(select id,name,Account__r.name,Start_Date__c  from Affiliations__r),contact_profile__c from contact];
        System.assertNotEquals(ContactQualificationChangeEvent.CONTACT_PROFILE_ALUMNI, conList[0].contact_profile__c,'The change event trigger did not updated contact');
    }
    // test method to test contact profile field update and affiliation creation 
    // when faculty is missing
    @isTest static void testenableAlumniFlagWithNoFaculty() {
        Test.enableChangeDataCapture();
        string testname= 'Monash University Global';
        id recordtypeids = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization').getRecordTypeId();
        Account testaccount = new Account(name=testname,recordtypeid=recordtypeids);
        insert testaccount;

        Global_Monash_Account__c cusSet = new Global_Monash_Account__c();
        cusSet.id__c= string.valueOf(testaccount.Id);
        Insert cusSet;

        String testLastname = 'Lastname ' + String.valueOf(System.now());
        Contact testContact = new Contact(Firstname='Test', Lastname=testLastname,contact_profile__c='');
        insert testContact;
        Course_Attempt__c ca = new Course_Attempt__c(
            	Course__c=createCourse(testaccount.id), 
            	Contact__c=testContact.Id,
            	Location__c = 'AU'
            	);
		insert ca;
        id recordTypeConQual = Schema.SObjectType.Contact_Qualification__c.getRecordTypeInfosByName().get('Tertiary Education').getRecordTypeId();
        insert new Contact_Qualification__C(
            contact__c=testContact.id,
            Obtained_status__c=ContactQualificationChangeEvent.OBTAINED_STATUS_MONASH,
            Date_Achieved__c=Date.newInstance(2016, 12, 9),
            Course_Attempt__c = ca.id,
            Institution_Name__c = ContactQualificationChangeEvent.INSTITUTION_MONASH,
            RecordTypeId = recordTypeConQual);
        Test.getEventBus().deliver();

        Contact [] conList=[select id,(select id,name,Account__r.name,Start_Date__c  from Affiliations__r),contact_profile__c from contact];
        System.assertEquals(ContactQualificationChangeEvent.CONTACT_PROFILE_ALUMNI, conList[0].contact_profile__c,'The change event trigger did updated contact');
        System.assertEquals('Monash University Global', conList[0].Affiliations__r[0].Account__r.name,'The change event trigger did updated contact');
        System.assertEquals(Date.newInstance(2016, 12, 9), conList[0].Affiliations__r[0].Start_Date__c,'Start date as achieved date');

    }
    // test method to test skipping trigger execution for automated process
    @isTest static void testenableSkippingAlumniFlag(){
        	
            List<user> userList =[select id,username from User where Name = 'Automated Process'];
        
            system.runAs(userList[0]){
            
            TriggerMuteRequest__c disableTrigger = new TriggerMuteRequest__c();
        	disableTrigger.TriggersList__c ='Contact_Qualification__ChangeEvent';
        	disableTrigger.Name=userList[0].username;
        	insert disableTrigger;
            
            String testLastname = 'Lastname ' + String.valueOf(System.now());
            Contact testContact = new Contact(Firstname='Test', Lastname=testLastname,contact_profile__c='');
            insert testContact;
           string testname= 'Monash University Global';
        	id recordtypeids = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization').getRecordTypeId();
        	Account testaccount = new Account(name=testname,recordtypeid=recordtypeids);
            insert testaccount;
            Course_Attempt__c ca = new Course_Attempt__c(
            	Course__c=createCourse(testaccount.id), 
            	Contact__c=testContact.Id,
            	Location__c = 'AU'
            	);
            insert ca;
            id recordTypeConQual = Schema.SObjectType.Contact_Qualification__c.getRecordTypeInfosByName().get('Tertiary Education').getRecordTypeId();
            insert new Contact_Qualification__C(
                contact__c=testContact.id,
                Obtained_status__c=ContactQualificationChangeEvent.OBTAINED_STATUS_MONASH,
                Date_Achieved__c=Date.newInstance(2016, 12, 9),
                Course_Attempt__c = ca.id,
                Institution_Name__c = ContactQualificationChangeEvent.INSTITUTION_MONASH,
                RecordTypeId = recordTypeConQual);
            Test.getEventBus().deliver();
            Contact [] conList=[select id,(select id,name,Account__r.name,Start_Date__c  from Affiliations__r),contact_profile__c from contact];
            System.assertNotEquals(ContactQualificationChangeEvent.CONTACT_PROFILE_ALUMNI, conList[0].contact_profile__c,'The change event trigger did not updated contact');
        }
            
    }
    
    // creates a test course object
    private static id createCourse(Id accountId) {
        Course__c course = new Course__c();
        course.Name = 'CrsNme';
        course.Course_Description__c = 'CourseDescription-1';
        course.Course_Code__c = 'CourseCode-1';
        course.Version__c = '1';
        course.Faculty_Description__c = 'FacultyDescription-1';
        course.Sub_Level__c = '41';//DOCTORATE BY RESEARCH';
        course.Title__c = 'Course Title';
        course.Managing_Faculty__c = 'Faculty of Engineering';
        course.Faculty_Code__c = 'FacCode';
        course.Type__c = 'Course-All';
        course.Faculty__c = accountId;
        insert course;  
        return course.id;
    }
}