force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <description>Monash internal award code (Callista reference data) or external course code (license number etc.)</description>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <label>Person ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The Qualificaiton Title</description>
        <label>Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_External_Id__c</fullName>
        <description>The unique external id for Contact Qualification Object</description>
        <externalId>true</externalId>
        <label>Unique_External_Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>deleted_on_source__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag indicates if the qualification is currently active</description>
        <label>Deleted on Source</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Used to force uniqueness on course code. Updated from workflow.</description>
        <externalId>true</externalId>
        <label>Course Code Unique</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date for the course</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Course full title</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Attempt__c.object
<CustomObject>
    <description>Course attempt represents the courses a Contact is related to.</description>
    <fields>
        <fullName>Callista_External_Id__c</fullName>
        <description>Holds a concatenation of the Callista Person Id (from &apos;Contact.Person_Id_unique__c&apos;), and underscore(&apos;_&apos;), and the Course Code (from &apos;Course__c.Name&apos;). This is a unique combination (for academic courses).</description>
        <externalId>true</externalId>
        <inlineHelpText>This field is evaluated and set by the system.</inlineHelpText>
        <label>Callista_External_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Contains the course code (without the version). It is derived from the Course lookup relationship.</description>
        <formula>Course__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to the course (incl. version) of the course attempt</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Value does not match the type of allowed courses an attempt record can be related to.</errorMessage>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Course-All</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short Course</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short_Course</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <label>Person Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Course Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Attempts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IbdUnitSetAttempt__e.object
<CustomObject>
    <description>Inbound student unit set attempts - major/minor/specialisations</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>This field captures the category</description>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>This field captures the course code of the course attempt</description>
        <label>Course_Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>This filed is to capture the type of event example INSERT, UPDATE and DELETE</description>
        <label>Event_Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <description>Person Id</description>
        <label>Person ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_List__c</fullName>
        <description>A comma delimited list of Contact Qual unique keys</description>
        <label>Qualification List</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>This field captures the rank</description>
        <label>Rank</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requirements_Complete_Date__c</fullName>
        <label>Requirements Complete  Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Selection_Date__c</fullName>
        <label>Selection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>This field captures the sequence number of unit set attempt</description>
        <label>Sequence Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>This field captures title</description>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Set_Code__c</fullName>
        <description>This field captures the category</description>
        <label>Unit Set Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <description>This field captures version</description>
        <label>Course Version</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Inbound Unit Set Attempt</label>
    <pluralLabel>Inbound Unit Set Attempts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Unit_Set_Attempt__c.object
<CustomObject>
    <description>Majors, minors and specialisations. When seen against a Course Attempt, consider them inflight. Against a Contact Qualification, they are part of the award.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>This field captures category</description>
        <label>Category</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>This field captures unit set code</description>
        <label>Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Unit Set Attempt</relationshipLabel>
        <relationshipName>Unit_Set_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>The course this unit set is attached to. System field, used to name the record.</description>
        <label>Course Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <label>Person ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>This field captures rank</description>
        <label>Rank</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requirements_Complete_Date__c</fullName>
        <label>Requirements Complete Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Selection_Date__c</fullName>
        <label>Selection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>This field captures title</description>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_External_Id__c</fullName>
        <description>This field captures category</description>
        <externalId>true</externalId>
        <label>Unique External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Set__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Lookup to course object</description>
        <label>Unit Set</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Unit Set</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Unit Set Attempts</relationshipLabel>
        <relationshipName>Unit_Set_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <description>This field captures unit set version</description>
        <label>Version</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>deleted_on_source__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag indicates if the qualification is currently active</description>
        <label>Deleted on Source</label>
        <type>Checkbox</type>
    </fields>
    <label>Unit Set Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Set Attempts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Set_Attempt_Qualification__c.object
<CustomObject>
    <description>Junction object between a Contact Qual and Unit Set Attempt</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Unit Set Attempt Category</description>
        <formula>Unit_Set_Attempt__r.Category__c</formula>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Qualification</label>
        <referenceTo>Contact_Qualification__c</referenceTo>
        <relationshipLabel>Unit Set Attempts</relationshipLabel>
        <relationshipName>Unit_Set_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Qualification Title</description>
        <formula>Contact_Qualification__r.Qualification_Name__c</formula>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unit_Set_Attempt__c</fullName>
        <label>Unit Set Attempt</label>
        <referenceTo>Unit_Set_Attempt__c</referenceTo>
        <relationshipLabel>Qualifications</relationshipLabel>
        <relationshipName>Qualificarions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Set__c</fullName>
        <description>Unit Set Name</description>
        <formula>Unit_Set_Attempt__r.Title__c</formula>
        <label>Unit Set</label>
        <type>Text</type>
    </fields>
    <label>Unit Set Attempt Qualification</label>
    <nameField>
        <displayFormat>USAQ-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Set Attempt Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/IbdUnitSetAttemptServices.cls
/**
* @author Ravi Nukala
* @date 26.04.2019
*
* @group Qualification
*
* @description 
* Platform Event handler for contact qualification. Call from subscribing trigger on the IbdUnitSetAttempt__e object.</br>
*
* Process platform events for unit set attempts. <br/>
* USA records are linked to the [student] course attempt record, and should be considered 'inflight' study until there is also a link to a qualification, in which case they have been completed.<br/>
* The link to quaification is only sent when study has completed. This process expects the contact qualification record to exist already and creates/updates an entry in the junction object.<br/>
*
* Retry exceptions are raised for various criteria. There are risks.<br/>
* https://developer.salesforce.com/docs/atlas.en-us.platform_events.meta/platform_events/platform_events_subscribe_apex_refire.htm<br/>
*
* Delete events set a deleted_in_source flag wich can be used as a filter criteria in the record purge scheduled job.<br/>
*
* Supporting test class: IdbUnitSetAttemptServices_Test<br/>
*
* @revision
* 26.04.2019 Ravi Nukala - Initial version<br/>
* 11.07.2019 Martin Cadman - Added capability for the unit set attempt qualification junction object to allow major/minor to be represented against a qualification. Supports 1 USA to be linked to multiple qualifcations.<br/>
* 01.08.2019 Martin Cadman - Added various field mapping changes.<br/>  
* 01.09.2019 Martin Cadman - Added retry exception handling.<br/>
* 07.09.2019 Martin Cadman - Extended retry exception handling to include parental record locking.<br/>
* 23.09.2019 Martin Cadman - Move to standardised event naming convention and new trigger framework.<br/>
*
**/
public without sharing class IbdUnitSetAttemptServices {
    private static final Integer MAXRETRIES = 3; // Shared between the USA insert and the USA Qual.

    // Exception to allow an eventbus retry to be bubbled up
    public class MyRetryException extends Exception {}
    
    private static final String SCENARIO = 'Inbound Unit Set Attempt';
    
	// Different log message formats    
    private static String msgfmt0 = '{0} {1}';
    private static String msgfmt1 = '{0} - {1}';
    private static String msgfmt2 = '{0}\r\r{1}';
    private static String msgfmt3 = '{0} - {1}\r\r{2}';    
 
    public class EventHandler extends TriggerAbstract {

        // The unique map of the records to be processed        
        private Map<String, IbdUnitSetAttempt__e> aDeleteMap = new Map<String, IbdUnitSetAttempt__e>();
        private Map<String, IbdUnitSetAttempt__e> aUpsertMap = new Map<String, IbdUnitSetAttempt__e>();
        
        // Process the unique map of records
        public override void execute() {
            List<Unit_Set_Attempt__c> upsertList = new List<Unit_Set_Attempt__c>();
            List<Unit_Set_Attempt__c> deleteList = new List<Unit_Set_Attempt__c>();
            List<String> qualList = new List<String>();
            List<Unit_Set_Attempt_Qualification__c> upsertQList = new List<Unit_Set_Attempt_Qualification__c>();
            String jsonEvent;
            nebula.LogMessage logMsg;
        	String tId;

			// Set logging to the inbound event scenario, which controls the default logging level etc.
			// See the Logger Scenario Rules custom metadata
            nebula.Logger.setScenario(SCENARIO);       

			// Allow for logs to be linked across event retired by inserting the initial transaction id in the error message
            tId = nebula.Logger.getTransactionId();
            if (EventBus.TriggerContext.currentContext().lastError != null) {
                tId = EventBus.TriggerContext.currentContext().lastError.subStringBetween('[[',']]');
                if (String.isNotEmpty(tId)) {
	                nebula.Logger.setParentLogTransactionId(tId);
                }
            } 
            
			nebula.logger.debug('Unit Set Attempt Batchsize ' + trigger.size);
            for (sObject record : trigger.new) {
                IbdUnitSetAttempt__e iEvent = (IbdUnitSetAttempt__e)record;
	            jsonEvent = JSON.serializePretty(iEvent);
                try {
                    if (!String.isBlank(iEvent.Person_ID__c) && !String.isBlank(iEvent.Course_Code__c) && !String.isBlank(iEvent.Unit_Set_Code__c) && !String.isBlank(iEvent.Sequence_Number__c)) {
                        Switch on (iEvent.Event_Type__c!=null?iEvent.Event_Type__c.touppercase():'UNKNOWN') {
                            when 'INSERT','UPDATE' {aUpsertMap.put(getUniquekey(iEvent), iEvent);}
                            when 'DELETE' {aDeleteMap.put(getUniqueKey(iEvent), iEvent);}
                            when else {
                                logMsg = new nebula.LogMessage(msgfmt3, iEvent.Person_ID__c,'Invalid Event Type', jsonEvent);
			                    nebula.logger.ERROR(logMsg);
                            }
                        }
                    } else {
                        logMsg = new nebula.LogMessage(msgfmt3, iEvent.Person_ID__c,'Mandatory field not included\rPerson_ID__c, Course_Code__c, Unit_Set_Code__c and Sequence_Number__c must be specified', jsonEvent);
	                    nebula.logger.ERROR(logMsg);
                    }
                } catch (Exception ex) {
					nebula.logger.exception(ex.getMessage(), ex);
                } 
            }
            
			nebula.logger.debug('Unit Set Attempts for processing: ' + Integer.valueOf(aUpsertMap.size() + aDeleteMap.size()));
            try {
                if (aUpsertMap.size() + aDeleteMap.size() > 0) {
                    if (aUpsertMap.size() > 0) {
                        for (IbdUnitSetAttempt__e iEvent : aUpsertMap.values()) { 
                            jsonEvent = JSON.serializePretty(iEvent);
							logMsg = new nebula.LogMessage(msgfmt3, getName(iEvent, False), 'Unit Set Attempt Upsert', jsonEvent);
	                        nebula.logger.info(logMsg);
                            upsertList.add(this.mapEventToObject(iEvent));
		                    qualList.add(iEvent.Qualification_List__c); // Inserts null if empty
                        }
                    }
                    
                    if (aDeleteMap.size() > 0) {
                        for (IbdUnitSetAttempt__e iEvent : aDeleteMap.values()) {          
							jsonEvent = JSON.serializePretty(iEvent);
                            logMsg = new nebula.LogMessage(msgfmt3, getName(iEvent, False), 'Unit Set Attempt Delete', jsonEvent);
	                        nebula.logger.info(logMsg);
                            deleteList.add(this.mapDeleteEventToObject(iEvent));
                        }
                    }                
                }

				nebula.logger.debug('Unit Set Attempts to be upserted: '+upsertList.size());
                if (upsertList.size() > 0) {
                	Database.UpsertResult [] upsertResults = Database.upsert(upsertList, Unit_Set_Attempt__c.Fields.Unique_External_Id__c , false);
                    Database.UpsertResult aResult = null;
                    for (Integer i=0; i<upsertResults.size(); i++) {
                        aResult = upsertResults[i];
                        if (!aResult.isSuccess()) {
                            for (Database.Error err : aResult.getErrors()) {
                                Switch on (err.getStatusCode()) {
                                    when UNABLE_TO_LOCK_ROW, INVALID_FIELD {
                                        if (EventBus.TriggerContext.currentContext().retries < MAXRETRIES) {
                                            logMsg = new nebula.LogMessage(msgfmt1, upsertList[i].Person_ID__c, 'Retry SUSA ' + String.valueOf(EventBus.TriggerContext.currentContext().retries+1) + ' - ' + err.getMessage());
	                                        nebula.logger.warn (logMsg, aResult);
                                            throw new MyRetryException(err.getMessage());
                                        } else {
                                            logMsg = new nebula.LogMessage(msgfmt1,upsertList[i].Person_ID__c,'Maximum retries (' + MAXRETRIES + ') reached for Unit Set Attempt - ' + err.getMessage());
                                            nebula.logger.error (logMsg, aResult);
                                        }
                                    }
                                    when else {
                                        logMsg = new nebula.LogMessage(msgfmt1,upsertList[i].Person_ID__c,'Unit Set Attempt upsert error - ' + err.getMessage());
	                                    nebula.logger.error(logMsg, aResult);
                                    }
                                }                                
                            }
                        } else {
                            // Note that if a retry happens for SUSA or SUSA Quals, the record link in this log entry may be invalid as any inserts are rolled back
                            nebula.logger.fine('Unit Set Attempt successfully ' + String.valueOf(aResult.isCreated()?'created':'updated') ,aResult.getId());

                            // For each successfully saved SUSA, see if there was an association with a qualification. This happens in Callista at course completion.
                            if (qualList[i] != null ) { 
                                for (String qpk : qualList[i].split(',')) {
                                    // Build the junction object record
                                    upsertQList.add(mapEventToJunction(upsertList[i], qpk.trim()));
                                }                
                            }
                        }
                    }
                } 
                    
                // Process the deletes in this batch last
                nebula.logger.debug('Unit Set Attempts to be deleted: ' + deleteList.size());
                if (deleteList.size() > 0) {
                    Database.UpsertResult [] deleteResults = Database.upsert(deleteList, Unit_Set_Attempt__c.Fields.Unique_External_Id__c, false);
                    Database.UpsertResult aDelResult = null;
                    for (Integer i=0; i<deleteResults.size(); i++) {
                        aDelResult = deleteResults[i];
                        if (!aDelResult.isSuccess()) {
                            for (Database.Error err : aDelResult.getErrors()) {
                                Switch on (err.getStatusCode()) {
                                    when UNABLE_TO_LOCK_ROW, INVALID_FIELD {
                                        if (EventBus.TriggerContext.currentContext().retries < MAXRETRIES) {
                                            logMsg = new nebula.LogMessage(msgfmt1, deleteList[i].Person_ID__c, 'Retry SUSA (soft delete) ' + String.valueOf(EventBus.TriggerContext.currentContext().retries+1) + ' - ' + err.getMessage());
                                            nebula.logger.warn (logMsg, aDelResult);
                                            throw new MyRetryException(err.getMessage());
                                        } else {
                                            logMsg = new nebula.LogMessage(msgfmt1,deleteList[i].Person_ID__c, 'Maximum retries (' + MAXRETRIES + ') reached for Unit Set Attempt - ' + err.getMessage());
                                            nebula.logger.error (logMsg, aDelResult);
                                        }
                                    }
                                    when else {
                                        logMsg = new nebula.LogMessage(msgfmt1,deleteList[i].Person_ID__c, 'Unit Set Attempt upsert (Delete) error - ' + err.getMessage());
                                        nebula.logger.error(logMsg, aDelResult);
                                    }
                                }                                
                            }
                        } 
                        else {
                            nebula.logger.fine('Unit Set Attempt successfully (soft) deleted',aDelResult.getId());
                        }
                    }
                } 
                    
                // We don't expect the junction record to change after it has been created but upsert is much easier to deal with.
                // It does mean having to have an external key on the junction object.
                // This uses the upsertlist from the initial upsert to log the person id errors.
                nebula.logger.debug('Unit Set Attempt Qualification links to be inserted: ' + upsertQList.size());
                if (upsertQList.size() > 0) {
                    Database.UpsertResult [] upsertResults = Database.upsert(upsertQList,unit_set_attempt_qualification__c.Fields.Unique_Key__c,false);
                    Database.UpsertResult aResultQ = null;
                    for (Integer i=0; i<upsertResults.size(); i++) {
                        aResultQ = upsertResults[i];
                        if (!aResultQ.isSuccess()) {
                            for (Database.Error err : aResultQ.getErrors()) {
                                Switch on (err.getStatusCode()) {
                                    when UNABLE_TO_LOCK_ROW, INVALID_FIELD {
                                        if (EventBus.TriggerContext.currentContext().retries < MAXRETRIES) {
                                            logMsg = new nebula.LogMessage(msgfmt1, upsertQList[i].Unique_Key__c.substring(0,8), 'Retry SUSA Qual ' + String.valueOf(EventBus.TriggerContext.currentContext().retries+1) + ' - ' + err.getMessage());
                                            nebula.logger.warn (logMsg, aResultQ);
                                            throw new MyRetryException(err.getMessage());
                                        } else {
                                            logMsg = new nebula.LogMessage(msgfmt1,upsertQList[i].Unique_Key__c.substring(0,8), 'Maximum retries (' + MAXRETRIES + ') reached for Unit Set Attempt Qualification - ' + err.getMessage());
                                            nebula.logger.error (logMsg, aResultQ);
                                        }
                                    }
                                    when else {
                                        logMsg = new nebula.LogMessage(msgfmt1,upsertQList[i].Unique_Key__c.substring(0,8), 'Unit Set Attempt Qualification upsert error - ' + err.getMessage());
                                        nebula.logger.error(logMsg, aResultQ);
                                    }
                                }                                
                            }
                        } 
                        else {
                            nebula.logger.fine('Unit Set Attempt Qualification successfully ' + String.valueOf(aResultQ.isCreated()?'created':'updated') ,aResultQ.getId());
                        }
                    } 
                }
            } catch (MyRetryException mex) {
                // A retry replays the entire batch, so there is no need to duplicate the logs for each.
				// This does delay when the first message is avaliable in the logs
                if (!nebula.logger.isDebugEnabled()) {nebula.logger.flushBuffer();}
                throw new EventBus.RetryableException('Unit Set Attempt Retry ' + (EventBus.TriggerContext.currentContext().retries + 1) + ' of ' + MAXRETRIES +'\r' + mex.getMessage()+ '\r[[' + tId + ']]'); // add logger transaction id
            } catch (Exception ex) { 
                nebula.logger.exception(ex.getMessage(), ex);
            } finally {
                nebula.logger.saveLog();                
            }
        }
        
        /**
        @description Builds the UK for the Object
        @param iEvent An individual inbound event
        @return A String representations of the UK 
        */
        private string getUniqueKey(IbdUnitSetAttempt__e iEvent) {
            return iEvent.Person_ID__c + '_' + iEvent.Course_Code__c + '_'+ iEvent.Unit_Set_Code__c + '_' +iEvent.Sequence_Number__c;
        }

        /**
        @description Builds a individual USA - field mappings, including lookups and literals, go here.
        @param iEvent An individual inbound event
        @return A populated base-object with values mapped from the inbound event

		{
        "CreatedById" : "0054a000000IwVbAAK",
        "CreatedDate" : "2020-06-16T00:53:37.000+0000",
        "Unit_Set_Code__c" : "PSYCHOL01",
        "Event_Type__c" : "DELETE",
        "Sequence_Number__c" : "778151",
        "Course_Code__c" : "A2000",
        "Person_ID__c" : "28115120"
        }
        */
        private Unit_Set_Attempt__c mapDeleteEventToObject(IbdUnitSetAttempt__e iEvent) {
            Unit_Set_Attempt__c unitSetAttempt = new Unit_Set_Attempt__c();
            
            unitSetAttempt.deleted_on_source__c = true;
            
            // Fields
            unitSetAttempt.Person_ID__c = iEvent.Person_ID__c;
            unitSetAttempt.Code__c = iEvent.Unit_Set_Code__c;
            unitSetAttempt.Name = iEvent.Person_ID__c + '/' + iEvent.Course_Code__c + '/' + iEvent.Unit_Set_Code__c;
            
            unitSetAttempt.Unique_External_Id__c = getUniqueKey(iEvent);
            
            return unitSetAttempt;
        }

        /**
        @description Builds a individual USA - field mappings, including lookups and literals, go here.
        @param iEvent An individual inbound event
        @return A populated base-object with values mapped from the inbound event

		{
        "Qualification_List__c" : "28115120_A2000_1_1011",
        "Event_Type__c" : "UPDATE",
        "Title__c" : "Philosophy",
        "Rank__c" : "2",
        "CreatedById" : "0054a000000IwVbAAK",
        "Requirements_Complete_Date__c" : "2019-07-15",
        "Selection_Date__c" : "2017-10-31",
        "Category__c" : "EXTENDED MAJOR",
        "CreatedDate" : "2020-06-16T01:11:52.000+0000",
        "Unit_Set_Code__c" : "PHILSPHY03",
        "Version_Number__c" : "1",
        "Sequence_Number__c" : "794954",
        "Course_Code__c" : "A2000",
        "Person_ID__c" : "28115120"
        }

        */
        private Unit_Set_Attempt__c mapEventToObject(IbdUnitSetAttempt__e iEvent) {
            Unit_Set_Attempt__c unitSetAttempt = new Unit_Set_Attempt__c();
            
            // Lookups - Both should be considered mandatory
            unitSetAttempt.Course_Attempt__r = new Course_Attempt__c (Callista_External_Id__c = iEvent.Person_ID__c + '_' + iEvent.Course_Code__c);
            unitSetAttempt.Unit_Set__r = new Course__c(Course_Code__c=iEvent.Unit_Set_Code__c + '_' + iEvent.Version_Number__c);
            
            // Fields
            unitSetAttempt.Person_ID__c = iEvent.Person_ID__c;
            unitSetAttempt.Code__c = iEvent.Unit_Set_Code__c;
            unitSetAttempt.Version__c = iEvent.Version_Number__c;
            unitSetAttempt.Course_Code__c = iEvent.Course_Code__c;
            unitSetAttempt.Title__c = iEvent.Title__c;
            unitSetAttempt.Rank__c = iEvent.Rank__c;
            unitSetAttempt.Category__c = iEvent.Category__c;
            unitSetAttempt.Selection_Date__c = iEvent.Selection_Date__c;
            unitSetAttempt.End_Date__c = iEvent.End_Date__c;
            unitSetAttempt.Requirements_Complete_Date__c = iEvent.Requirements_Complete_Date__c;
            unitSetAttempt.Name = getName(iEvent, False);

            unitSetAttempt.Unique_External_Id__c = getUniqueKey(iEvent);
            
            if (iEvent.Event_Type__c.touppercase() == 'INSERT') {
                unitSetAttempt.deleted_on_source__c = false;
            }
            
            return unitSetAttempt;
        }
        
        /*
        * @description Builds the name for the Object
        * @param iEvent An individual inbound event
        * @return A String representations of the name
        */
        private string getName(IbdUnitSetAttempt__e iEvent, Boolean Deleted) {
            return UnitSetAttemptServices.getUniqueName(iEvent.Person_ID__c, iEvent.Course_Code__c, iEvent.Unit_Set_Code__c, Deleted);
        }

        /**
        @description Builds a individual USAQ (juntion record between USA and CQ) - field mappings, including lookups and literals, go here.
        @param aUSA The parent USA record
        @param qualPK An individual Contact Qualification external key 
        @return A populated base-object with values mapped from the inbound event
        */
        private Unit_Set_Attempt_Qualification__c mapEventToJunction (Unit_Set_Attempt__c aUSA,  String qualPK) {
            Unit_Set_Attempt_Qualification__c aUSAQ = new Unit_Set_Attempt_Qualification__c();
            
            // External key to support upsert
            aUSAQ.Unique_Key__c = qualPK + '_' + aUSA.Code__c ;
            aUSAQ.Contact_Qualification__r = new Contact_Qualification__c(Unique_External_Id__c = qualPK);                
            aUSAQ.Unit_Set_Attempt__c = aUSA.id;
            
            return aUSAQ;
        }
        
    }
}