force-app/main/default/objects/Contact_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <label>Person ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the country at which the qualification is obtained</description>
        <label>Qualification Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>Contact Qualifications</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qualification_Name__c</fullName>
        <formula>if (ISBLANK(Qualification__r.Qualification_Name__c)
  , if (ISBLANK( Other_Qualification__c), Title__c,Other_Qualification__c)
 , HYPERLINK(&apos;/&apos;+Id, Qualification__r.Qualification_Name__c,&apos;_self&apos;))</formula>
        <label>Qualification Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Qualification Lookup</label>
        <referenceTo>Qualification__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Contact_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Qualification</label>
    <nameField>
        <displayFormat>CNQL-{000000}</displayFormat>
        <label>Contact Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Attribute__c.object
<CustomObject>
    <description>This allows the definition of various country attributes (e.g. mapping to ISO codes, ABS codes, Australian border, department of education codes, restricted countries, flags for different user groups which can be used to drive sharing of records etc.)</description>
    <fields>
        <fullName>Callista_Code__c</fullName>
        <description>The unique identifier for the country record in Callista</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier for a country record in Callista</inlineHelpText>
        <label>Callista Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Callista_Code__c</fullName>
        <externalId>true</externalId>
        <label>Callista Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Name__c</fullName>
        <label>Qualification Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <displayFormat>QUAL-{000}</displayFormat>
        <label>Qualification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ATARSendScoreToCallistaService_Test.cls
/*****************************************************************************************************************
* @author      : Sethu Venna
* @date        : 18/03/2025
* @description : Test class for ATARSendScoreToCallistaService
* @revision    : 18/03/2025 - Initial Version
*****************************************************************************************************************/
@IsTest(isParallel=true)
public class ATARSendScoreToCallistaService_Test {
    
    @IsTest
    public static void testATARSendScoreToCallistaService() {
        // Create test data

        // Create test data

        Country_Attribute__c ca = new Country_Attribute__c(Name = 'AUSTRALIA');
        insert ca;

        Contact newContact = new Contact();
        newContact.FirstName = 'FN in testATARCalloutFromTrigger';
        newContact.LastName = 'LN in testATARCalloutFromTrigger';
        newContact.Person_ID_unique__c = '123456';
        insert newContact;

        Qualification__c qual = new Qualification__c();
        qual.Callista_Code__c = 'Y12';
        qual.Qualification_Name__c = 'Year 12 All Australia';
        insert qual;

        Contact_Qualification__c conQual = new Contact_Qualification__c();
        conQual.Person_ID__c = '123456';
        conQual.Qualification__c = qual.Id;
        conQual.Contact__c = newContact.Id;
        conQual.Qualification_Country__c = ca.Id;
        conQual.RecordTypeId = ContactQualificationServices.SECONDARY_EDU_RECORD_TYPE_ID;
        insert conQual;
        
        // Create a mock response
        ATARScoreHTTPCalloutMock mockResp = new ATARScoreHTTPCalloutMock();
        mockResp.responseCode = 200;
        
        Test.setMock(HttpCalloutMock.class, mockResp);
        
        // Execute the service
        Test.startTest();
        ATARSendScoreToCallistaService service = new ATARSendScoreToCallistaService(conQual);
        service.createRequestBody();
        service.sendMessage();
        service.handleResponse();
        Test.stopTest();
        
        // Verify the response
        Assert.areEqual(
            200,
            service.httpResponseCode, 
            'Expecting a 200 STATUS OK'
        );
        
    }
}