force-app/main/default/objects/Country_Attribute__c.object
<CustomObject>
    <description>This allows the definition of various country attributes (e.g. mapping to ISO codes, ABS codes, Australian border, department of education codes, restricted countries, flags for different user groups which can be used to drive sharing of records etc.)</description>
    <fields>
        <fullName>Callista_Country__c</fullName>
        <description>The Callista country name. The value set should contain the SACC standard list of names.</description>
        <inlineHelpText>The Callista country name</inlineHelpText>
        <label>Callista Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The ISO country name</description>
        <inlineHelpText>The ISO country name</inlineHelpText>
        <label>ISO Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List_1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ISO_Alpha_2__c</fullName>
        <description>The two-letter ISO alpha country representation.

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2</description>
        <inlineHelpText>The two-letter ISO alpha country representation.</inlineHelpText>
        <label>ISO Alpha-2</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_Alpha_3__c</fullName>
        <description>These codes are three-letter country codes defined in ISO 3166-1

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3</description>
        <inlineHelpText>The three-letter country code defined in ISO</inlineHelpText>
        <label>ISO Alpha-3</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numeric_Country_Code__c</fullName>
        <description>The codes are three-digit country codes defined in ISO. While numeric, they do contain leading &apos;0&apos;s.</description>
        <inlineHelpText>The three-digit country code defined in ISO</inlineHelpText>
        <label>Numeric Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Country_List_1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Samoa, American</fullName>
        <label>American Samoa</label>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
        <label>Bahamas (the)</label>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
        <label>Bolivia (Plurinational State of)</label>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>United States of America</fullName>
        <label>United States of America (the)</label>
    </customValue>
    <description>As per ISO 3166</description>
    <masterLabel>Country List 1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Country_List_2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Adelie Land (France)</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua And Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Argentinian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Antarctic Territory</fullName>
    </customValue>
    <customValue>
        <fullName>Australian External Territories, NEC</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius And Saba</fullName>
        <label>Bonaire, Sint Eustatius and Saba</label>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <description>As per Callista</description>
    <masterLabel>Country List 2</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CountryServices_Test.cls
/* @description       : Provides test coverage to CuntryServices class.
 * @author            : Ken McGuire
 * Modifications Log 
 * Ver   Date         Author          Modification
 * 1.0   2023-02-12   Ken McGuire    Created
 * 20.3.2023	Ken McGuire - country of birth replace ISO with SAAC
 * 
**/
@isTest(isParallel=true)
private class CountryServices_Test {
    @testSetup
    static void setup() {
        // insert test country attribute records
		createTestCountryAttributes();
    }
    
    private static void createTestCountryAttributes() {
   		List<Country_Attribute__c> countryAttributes = new List<Country_Attribute__c>{
            new Country_Attribute__c(
                Country__c = 'United States of America',
                Callista_Country__c = 'United States of America',
                ISO_Alpha_2__c = 'US',
                ISO_Alpha_3__c = 'USA',
                Numeric_Country_Code__c = '001'
            ),
                new Country_Attribute__c(
                    Country__c = 'Australia',
                     Callista_Country__c = 'Australia',
                    ISO_Alpha_2__c = 'AU',
                    ISO_Alpha_3__c = 'AUS',
                    Numeric_Country_Code__c = '002'
                ),
                new Country_Attribute__c(
                    Country__c = 'India',
                    Callista_Country__c = 'India',
                    ISO_Alpha_2__c = 'IN',
                    ISO_Alpha_3__c = 'IND',
                    Numeric_Country_Code__c = '003'
                )
                };
    	insert countryAttributes;
    }

    @isTest
    static void testSearchCountry() {
        // given
        String testCountry = 'INDIA';
        // when
        String foundCountry = CountryServices.getCountryName(testCountry,CountryServices.FORMAT_ISO);
        // then
        System.assertEquals('India', foundCountry,'should find India');
    }
    
    @isTest
    static void testSearchCountryByCode() {
        // given
        String testCountry = '003';
        // when
        String foundCountry = CountryServices.getCountryName(testCountry,CountryServices.FORMAT_ISO);
        // then
        System.assertEquals('India', foundCountry,'should find India');
    }    
    
    @isTest
    static void testSearchCountryBySAAC() {
        // given
        String testCountry = '003';
        // when
        String foundCountry = CountryServices.getCountryName(testCountry,CountryServices.FORMAT_SAAC);
        // then
        System.assertEquals('India', foundCountry,'should find India');
    }  
    
    @isTest
    static void testGetCountryOptionsSAAC() {
        // when
        List<Map<String,String>> options = CountryServices.getCountryAttributeOptions(CountryServices.FORMAT_SAAC,false);
        // then
        System.assertEquals(3, options.size(),'Should be three options');
        System.AssertEquals('Australia',options[0].get(CountryServices.FIELD_LABEL),'First option should be Australia');
    }
        
    @isTest
    static void testGetCountryOptionsISO() {
        // when
        List<Map<String,String>> options = CountryServices.getCountryAttributeOptions(CountryServices.FORMAT_ISO,false);
        // then
        System.assertEquals(3, options.size(),'Should be three options');
        System.AssertEquals('Australia',options[0].get(CountryServices.FIELD_LABEL),'First option should be Australia');
    }
    
    @isTest
    static void testGetCountryOptionsWithEmptyOption() {
        // when
        List<Map<String,String>> options = CountryServices.getCountryAttributeOptions(CountryServices.FORMAT_ISO,true);
        // then
        System.assertEquals(4, options.size(),'Should be three options');
        System.AssertEquals(CountryServices.EMPTY_OPTION,options[0].get(CountryServices.FIELD_LABEL),'First option should be the empty option');
    }
    
    
    @isTest
    static void testGetCountry() {
        // given
        String testCountry = 'united states of america';
        // when
        Country_Attribute__c foundCountry = CountryServices.getCountry(testCountry);
        // then 
        System.assertEquals('United States of America', foundCountry.country__c,'should find United States of America');
    }
    
    @isTest
    static void testSearhMustStartWithString() {
        // given
        String testCountry = 'States';
        // when
        Country_Attribute__c foundCountry = CountryServices.getCountry(testCountry);
        // then 
        System.assertEquals(null, foundCountry,'should not search for containment');
    }
    
    @isTest
    static void getCountryId() {
        // given
         String testCountry = 'united states of america';
        // when
        Id foundCountryId = CountryServices.getCountryId(testCountry);
        // then 
        System.assertNotEquals(null, foundCountryId,'should find country Id');
    }
    
    @isTest
    static void getCountryIdForFormat() {
        // given
         String testCountry = 'united states of america';
        // when
        Id foundCountryId = CountryServices.getCountryId(testCountry,CountryServices.FORMAT_ISO);
        // then 
        System.assertNotEquals(null, foundCountryId,'should find country Id');
    }
}