force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <label>Academic Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Campus__c</fullName>
        <description>[PD] Same list Case &gt; Course_Location__c | Make sure to sync</description>
        <label>Campus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ballarat</fullName>
                </value>
                <value>
                    <fullName>Bendigo</fullName>
                </value>
                <value>
                    <fullName>Berwick</fullName>
                </value>
                <value>
                    <fullName>Broadmeadows</fullName>
                </value>
                <value>
                    <fullName>Brunswick</fullName>
                </value>
                <value>
                    <fullName>Caroline Springs</fullName>
                </value>
                <value>
                    <fullName>Caulfield</fullName>
                </value>
                <value>
                    <fullName>Clayton</fullName>
                </value>
                <value>
                    <fullName>Croydon</fullName>
                </value>
                <value>
                    <fullName>Doncaster</fullName>
                </value>
                <value>
                    <fullName>Ferntree Gully</fullName>
                </value>
                <value>
                    <fullName>Footscray</fullName>
                </value>
                <value>
                    <fullName>Frankston North</fullName>
                </value>
                <value>
                    <fullName>Geelong</fullName>
                </value>
                <value>
                    <fullName>Gippsland</fullName>
                </value>
                <value>
                    <fullName>Ivanhoe</fullName>
                </value>
                <value>
                    <fullName>Knox</fullName>
                </value>
                <value>
                    <fullName>Melbourne</fullName>
                </value>
                <value>
                    <fullName>Melbourne CBD</fullName>
                </value>
                <value>
                    <fullName>Mill Park</fullName>
                </value>
                <value>
                    <fullName>Moorabbin</fullName>
                </value>
                <value>
                    <fullName>Narre Warren</fullName>
                </value>
                <value>
                    <fullName>Northcote</fullName>
                </value>
                <value>
                    <fullName>Notting Hill</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pakenham</fullName>
                </value>
                <value>
                    <fullName>Parkville</fullName>
                </value>
                <value>
                    <fullName>Peninsula</fullName>
                </value>
                <value>
                    <fullName>Prato</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship_Type__c</fullName>
        <label>Citizenship Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DOM-AUS</fullName>
                </value>
                <value>
                    <fullName>DOM-HV</fullName>
                </value>
                <value>
                    <fullName>DOM-NZ</fullName>
                </value>
                <value>
                    <fullName>DOM-PR</fullName>
                </value>
                <value>
                    <fullName>DOMESTIC</fullName>
                </value>
                <value>
                    <fullName>DOM-SA</fullName>
                </value>
                <value>
                    <fullName>INT-SA</fullName>
                </value>
                <value>
                    <fullName>INT-TEP</fullName>
                </value>
                <value>
                    <fullName>INTRNTNL</fullName>
                </value>
                <value>
                    <fullName>DOM-SUN</fullName>
                </value>
                <value>
                    <fullName>INT-SUN</fullName>
                </value>
                <value>
                    <fullName>INT-SUN-P</fullName>
                </value>
                <value>
                    <fullName>DOM-IDN</fullName>
                </value>
                <value>
                    <fullName>DOM-IDN-PR</fullName>
                </value>
                <value>
                    <fullName>INT-IDN-P</fullName>
                </value>
                <value>
                    <fullName>INT-IDN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <externalId>true</externalId>
        <label>Course Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Title__c</fullName>
        <label>Course Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Faculty__c</fullName>
        <label>Faculty</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <externalId>true</externalId>
        <label>Location Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mix_Unique_Id__c</fullName>
        <description>Unique Key populated by the MIX API used as an External Id for delta upload</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Key populated by the MIX API used as an External Id for delta upload</inlineHelpText>
        <label>Mix Unique Id</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CourseOfferingsWebService_Test.cls
/**
* @description       : Course Offerings Web Service Test Class
* @author            : rajesh.punjabi@monash.edu
* @group             : 
* @last modified on  : 12-03-2024
* @last modified by  : rajesh.punjabi@monash.edu
**/
@isTest(IsParallel=true)
public class CourseOfferingsWebService_Test {
    /**
    * @description test data
    * @author rajesh.punjabi@monash.edu | 08-03-2024 
    **/
    @testSetup static void setup() {
        //.. Create Course Offerings
        List<Course_Offering__c> lstCourseOfferings = new List<Course_Offering__c>();
        Course_Offering__c oCourse_Offering1 = new Course_Offering__c();
        oCourse_Offering1.Course_Code__c = 'B1899-test';
        oCourse_Offering1.Academic_Year__c = 2018;
        oCourse_Offering1.Campus__c = 'Malaysia';
        oCourse_Offering1.Location_Code__c = 'Malaysia';
        oCourse_Offering1.Course_Title__c = 'Faculty of Business and Economics';
        oCourse_Offering1.Faculty__c = 'Master of Project Management';
        oCourse_Offering1.Mix_Unique_Id__c = 'B1899-test|1|CAULFIELD|IN|FT|8619|8638|NULL|NULL|NULL|NULL';
        oCourse_Offering1.Citizenship_Type__c = 'INT-SUN-P';
        lstCourseOfferings.add(oCourse_Offering1);

        Course_Offering__c oCourse_Offering2 = new Course_Offering__c();
        oCourse_Offering2.Course_Code__c = 'B1900-test';
        oCourse_Offering2.Academic_Year__c = 2018;
        oCourse_Offering2.Campus__c = 'Malaysia';
        oCourse_Offering2.Location_Code__c = 'Malaysia';
        oCourse_Offering2.Course_Title__c = 'Faculty of Business and Economics';
        oCourse_Offering2.Faculty__c = 'Master of Project Management';
        oCourse_Offering2.Mix_Unique_Id__c = 'B1900-test|1|CAULFIELD|IN|FT|8619|8638|NULL|NULL|NULL|NULL';
        oCourse_Offering2.Citizenship_Type__c = 'DOM-SUN';
        lstCourseOfferings.add(oCourse_Offering2);
        insert lstCourseOfferings;   
    }
    
    /**
    * @description Query with record found.
    * @author rajesh.punjabi@monash.edu | 08-03-2024 
    **/
    @isTest
    public static void getOfferedCourses_Test(){
        //.. GIVEN  .. Query the Course Offering Record.
        Course_Offering__c oCourse_Offering = [SELECT Id, Campus__c, Academic_Year__c FROM Course_Offering__c WHERE Course_Code__c = 'B1899-test' LIMIT 1];
        RestRequest req = new RestRequest();
        req.httpMethod = 'GET';
        req.params.put('campusCountry', oCourse_Offering.Campus__c);
        req.params.put('courseYear', String.valueOf(oCourse_Offering.Academic_Year__c));
        req.params.put('citizenshipTypeCodes','DOM-SUN,INT-SUN-P' );
        req.params.put('pageSize', String.valueOf(1));

        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        //.. WHEN  .. Call get courseoffering function
        Test.startTest();
        CourseOfferingsWebService.getOfferedCourses();
        Test.stopTest();
        CourseOfferingsResponseWrapper result = (CourseOfferingsResponseWrapper)
        JSON.deserialize(res.responseBody.toString(), CourseOfferingsResponseWrapper.class);
        //.. THEN .. verify the response
        //noOfRecords must be the size of the total number of records when pageSiae=1
        Assert.isTrue(result.noOfRecords==2, 'The number of total records should be 2');
        Assert.isTrue(result.pageSize=='1', 'The pageSize must be 1');
        Assert.isNotNull(String.isBlank(res.responseBody.toString()), 'Record Found.');
    }
    
    /**
    * @description Query with No Record result.
    * @author rajesh.punjabi@monash.edu | 08-03-2024 
    **/
    @isTest
    public static void getOfferedCoursesNoRecord_Test(){
        //.. GIVEN  .. Test no record found.
        RestRequest req = new RestRequest();
        req.httpMethod = 'GET';
        req.params.put('campusCountry', 'Australia');
        req.params.put('courseYear', '2090');
        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        //.. WHEN .. Call get courseoffering function
        Test.startTest();
        CourseOfferingsWebService.getOfferedCourses();
        Test.stopTest();
        
        //.. THEN  .. Response should contain no record found.
        Assert.isTrue(res.responseBody.toString().containsIgnoreCase('No record found.') , 'No Record Found.');
    }
    
    /**
    * @description Validate Missing Params Test
    * @author rajesh.punjabi@monash.edu | 08-03-2024 
    **/
    @isTest
    public static void getOfferedCoursesMissingParam_Test(){
        //.. GIVEN .. validate if params are null
        RestRequest req = new RestRequest();
        req.httpMethod = 'GET';
        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        //.. WHEN  .. call the function
        Test.startTest();
        CourseOfferingsWebService.getOfferedCourses();
        Test.stopTest();
        
        //.. THEN .. response contains missing params.
        Assert.isTrue(res.responseBody.toString().containsIgnoreCase('Missing Parameter') , 'Missing Params.');
    }
    
    /**
    * @description Exception test method
    * @author rajesh.punjabi@monash.edu | 08-03-2024 
    **/
    @isTest
    public static void getCourseOfferings_ExceptionTest(){
        //..GIVEN  .. Exception Test Data not required
        
        //.. WHEN  .. Call the function
        Test.startTest();
        CourseOfferingsWebService.getOfferedCourses();
        Test.stopTest();
        
        //.. THEN  .. Assert for succesful exception test.
        Assert.isTrue (true, 'Exception Testing Successful.');
    }
}