force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Used to force uniqueness on course code. Updated from workflow.</description>
        <externalId>true</externalId>
        <label>Course Code Unique</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Course_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the parent course master to group all courses with the same Course Code</description>
        <label>Course Master</label>
        <referenceTo>Course_Master__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of course being offered</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Academic_Course</fullName>
                    <label>Academic Course</label>
                </value>
                <value>
                    <fullName>Short_Course</fullName>
                    <label>Professional Development</label>
                </value>
                <value>
                    <fullName>Course-All</fullName>
                </value>
                <value>
                    <fullName>Unit Set</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Master__c.object
<CustomObject>
    <description>custom object to group all Courses with the same course code</description>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>A unique (case insensitive) string to group all Courses by Code</description>
        <label>Course Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Course Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Masters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c.object
<CustomObject>
    <label>Email</label>
    <nameField>
        <label>Email Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the phone number.

The order of the values is important as it drives some of the primary record selection behaviour.</description>
        <inlineHelpText>Please enter the phone number type</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Landline</fullName>
                </value>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Undefined</fullName>
                    <default>true</default>
                    <label>Undefined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Phone</label>
    <nameField>
        <label>Phone Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Staged_Prospective_Student__c.object
<CustomObject>
    <description>Staging object to capture prospective student data in a de-normalised form, which would be normalised into the Contact 360 data model through further processing post insertion.</description>
    <fields>
        <fullName>Acquisition_Source_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Acquisition Souce Campaign for the Prospective Student Lead.</description>
        <inlineHelpText>Acquisition source campaign for the Prospective Student Lead.</inlineHelpText>
        <label>Acquisition Source Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Staged Prospective Students</relationshipLabel>
        <relationshipName>Staged_Prospective_Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the Prospective Student Contact.</description>
        <inlineHelpText>Email of the Prospective Student Contact.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Event_Campaigns__c</fullName>
        <description>List of Event Campaigns to add Prospective Student as Campaign members. Expected format : Line separated Campaign IDs.</description>
        <inlineHelpText>List of Event Campaigns to add Prospective Student as Campaign members.</inlineHelpText>
        <label>Event Campaigns</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exploded_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated to this exploded Staged Lead</description>
        <inlineHelpText>Contact associated to this exploded Staged Lead.</inlineHelpText>
        <label>Exploded Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Staged Prospective Students</relationshipLabel>
        <relationshipName>Staged_Prospective_Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name of the Prospective Student Contact.</description>
        <inlineHelpText>First Name of the Prospective Student Contact.</inlineHelpText>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interested_Course_List__c</fullName>
        <description>List of course IDs or Course Code that the Prospective Student is interested in</description>
        <inlineHelpText>Course IDs or Course Code that the Prospective Student is interested in.</inlineHelpText>
        <label>Interested Course List</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last Name of the Prospective Student Contact.</description>
        <inlineHelpText>Last Name of the Prospective Student Contact.</inlineHelpText>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone Number of the Prospective Student Contact.</description>
        <inlineHelpText>Phone Number of the Prospective Student Contact.</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Subscription_Lists__c</fullName>
        <description>Subscriptions Lists to subscribe the Prospective Student Lead with as Subscription Member. 
Expected format : Line separated Campaign IDs.</description>
        <inlineHelpText>Subscriptions Lists to subscribe the Prospective Student Lead with as Subscription Member.</inlineHelpText>
        <label>Subscription Lists</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Staged Prospective Student</label>
    <nameField>
        <displayFormat>SPS-{0}</displayFormat>
        <label>Staged Prospective Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staged Prospective Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/StagedProspectiveStudentDAOV2_Test.cls
/**
 * @description       : test class for StagedProspectiveStudentDAOV2 
 * @author            : Nick Guia
 * @date              : 06-10-2020
 * @group             : Lead Management
 * @last modified on  : 05-07-2023
 * @last modified by  : Nick Guia
**/
@isTest(isParallel=true)
private class StagedProspectiveStudentDAOV2_Test {

    @TestSetup
    static void makeData(){
        Contact con = new Contact(
            FirstName = 'StagedProspectiveStudentDAOV2_Test',
            LastName = 'test',
            Email = 'test@test.org'
        );
        insert con;

        //create test courses
        List<Course__c> courseList = new List<Course__c>();
		for(Course__c iCourse : TestHelper.createCourses(1)) {
			iCourse.Type__c = Label.Course_Type_Course_All;
			iCourse.Course_Code__c = iCourse.Name;
			courseList.add(iCourse);
		}
		insert courseList;

        List<Campaign> campaignList = new List<Campaign>();
        
        //get non montrack record type ID
        Id nonMonRT = Schema.SObjectType.Campaign
                        .getRecordTypeInfosByDeveloperName()
                        .get('Non_Montrack')
                        .getRecordTypeId();
        //get subscription list record type ID
        Id subsListRT = Schema.SObjectType.Campaign
                        .getRecordTypeInfosByDeveloperName()
                        .get('Subscription_List')
                        .getRecordTypeId();

        //acquisition campaign
        Campaign acquisition = new Campaign(Name = 'AcquisitionCampaign');
        campaignList.add(acquisition);

        //Subscription Campaign
        Campaign subscriptionCampaign = new Campaign(Name = 'SubscriptionCampaign',
                                                    Channel_Type__c = 'Email;SMS',
                                                    RecordTypeId = subsListRT);
        campaignList.add(subscriptionCampaign);
        
        //Event Campaigns
        Campaign eventCampaign = new Campaign(Name = 'EventCampaign');
        campaignList.add(eventCampaign);
        
        //insert campaigns
        insert campaignList;
    }

    /**
     * @desription test all collection methods of the dao class
     * validate that all necessary information are properly collected within the dao instance
     */
    @isTest
    static void shouldCollectSpsDetails() {
        //given
        List<String> courseCodes = new List<String>();
        for(Course_Master__c iCM : [SELECT Id, Course_Code__c FROM Course_Master__c LIMIT 100]) {
            courseCodes.add(iCM.Course_Code__c);
        }
        Map<String, Campaign> campMap = new Map<String, Campaign>();
        for(Campaign iCamp : [SELECT Id, Name FROM Campaign LIMIT 10]) {
            campMap.put(iCamp.Name, iCamp);
        }
        List<Staged_Prospective_Student__c> spsList = TestHelper.createSps(2);
        for(Staged_Prospective_Student__c iSps : spsList) {
            iSps.Event_Campaigns__c = ''+campMap.get('EventCampaign').Id;
            iSps.Subscription_Lists__c = ''+campMap.get('SubscriptionCampaign').Id;
            iSps.Acquisition_Source_Campaign__c = ''+campMap.get('AcquisitionCampaign').Id;
            iSps.Interested_Course_List__c = String.join(courseCodes, ',');
        }
        StagedProspectiveStudentDAOV2 dao;

        Test.startTest();

        //when
        dao = new StagedProspectiveStudentDAOV2(spsList[0]);
        dao.addSps(spsList[1]);

        Test.stopTest();

        //then
        System.assert(dao.cqMap != null, 'Unable to collect SPS Contact Qualilfication details');
        System.assert(dao.cqQualNameSet != null, 'Unable to collect SPS Contact Qualilfication details');
        System.assert(dao.cqInsNameSet != null, 'Unable to collect SPS Contact Qualilfication details');
        System.assert(dao.interestedCourseCodes != null, 'Unable to collect SPS Course Interest details');
        System.assert(dao.subscriptionListIDs != null, 'Unable to collect SPS Subscription List details');
        System.assert(dao.eventCampaignIDs != null, 'Unable to collect SPS Event Campaign details');
        System.assert(dao.aSourceCampaignIDs != null, 'Unable to collect SPS Acquisition Source details');
    }

    /**
     * @desription test getters
     */
    @isTest
    static void shouldReturnCollectionFromGetters() {
        //given
        List<Staged_Prospective_Student__c> spsList = TestHelper.createSps(1);
        StagedProspectiveStudentDAOV2 dao;
        Campaign campRec = [SELECT Id, Name FROM Campaign LIMIT 1];

        Test.startTest();

        //when
        dao = new StagedProspectiveStudentDAOV2(spsList[0]);
        dao.cachedPhoneRecord = new Phone__c();
        dao.interestedCourseCodes = new List<String> { 'A0001', 'A0002', 'A0003' };
        dao.subscriptionListIDs = new Set<Id> { campRec.Id };
        dao.eventCampaignIDs = new Set<Id> { campRec.Id };
        dao.aSourceCampaignIDs = new Set<Id> { campRec.Id };

        //then
        System.assert(dao.getCachedPhone() != null, 'Unable to get cached Phone from DAO class');
        System.assert(dao.getSpsList().size() == 1, 'Unexpected number of SPS records found within the DAO class');
        System.assert(dao.getCourseInterests().size() == 3, 'Unexpected number of Course Codes found within the DAO class');
        System.assert(dao.getQualificationNames().size() == 2, 'Unexpected number of Contact Qualification Names found within the DAO class');
        System.assert(dao.getQualificationInstitutionNames().size() == 2, 'Unexpected number of Contact Qualification Names found within the DAO class');
        System.assert(dao.getContactQualificationMap().size() != null, 'Unexpected number of Contact Qualifications found within the DAO class');
        System.assert(dao.getSubscriptionListIds().size() == 1, 'Unexpected number of subscription list Ids found!');
        System.assert(dao.getEventCampaignIds().size() == 1, 'Unexpected number of event campaign Ids found!');
        System.assert(dao.getAcquisitionSourceIds().size() == 1, 'Unexpected number of acquisition campaign Ids found!');
        System.assert(dao.getmergedSps() != null, 'Unexpected null value for Merged SPS');

        Test.stopTest();
    }

    /**
     * @desription test setters
     */
    @isTest
    static void shouldSetValues() {
        Contact con = [SELECT Id 
                        FROM Contact 
                        WHERE FirstName = 'StagedProspectiveStudentDAOV2_Test' 
                        LIMIT 1];

        Staged_Prospective_Student__c sps = TestHelper.createSps(1)[0];
        sps.Exploded_Target__c = con.Id;

        Campaign campRec = [SELECT Id, Name FROM Campaign LIMIT 1];
        
        StagedProspectiveStudentDAOV2 dao = new StagedProspectiveStudentDAOV2(sps);
        dao.cachedPhoneRecord = new Phone__c();
        dao.interestedCourseCodes = new List<String> { 'A0001', 'A0002', 'A0003' };
        dao.subscriptionListIDs = new Set<Id> { campRec.Id };
        dao.eventCampaignIDs = new Set<Id> { campRec.Id };
        dao.aSourceCampaignIDs = new Set<Id> { campRec.Id };

        Test.startTest();

        //when
        dao.setAffiliation(null)
            .setAddress()
            .setEmail()
            .setMobile()
            .setPhone();
        dao.buildPerson360();

        Test.stopTest();

        //then
        Person360 p360 = dao.p360;
        System.assert(p360 != null, 'Unexpected null value for DAO Person 360');
        System.assert(p360.getAccount() != null, 'Unexpected null value for DAO Account');
        System.assert(p360.getContact() != null, 'Unexpected null value for DAO Contact');
        System.assert(p360.getAffiliation() != null, 'Unexpected null value for DAO Affiliation');
        System.assert(p360.getContactPointMap() != null, 'Unexpected null value for DAO Contact Points');
    }

    /**
     * @desription should add Campaign Members within the DAO instance
     */
    @isTest
    static void shouldAddCampaignMembersToDAO() {
        //given
        Contact con = [SELECT Id 
                        FROM Contact 
                        WHERE FirstName = 'StagedProspectiveStudentDAOV2_Test' 
                        LIMIT 1];
        //create test campaign member to be added to dao later
        CampaignMember subListMember;
        CampaignMember evMember;
        CampaignMember acqMember;
        //get campaign IDs
        String eventId;
        String subId;
        Id acqId;
        for(Campaign iCamp : [SELECT Id, Name FROM Campaign LIMIT 10]) {
            if(iCamp.Name == 'AcquisitionCampaign') {
                acqId = iCamp.Id;
                acqMember = new CampaignMember(CampaignId = iCamp.Id, ContactId = con.Id);
            } else if(iCamp.Name == 'SubscriptionCampaign') {
                subId = (String) iCamp.Id;
                subListMember = new CampaignMember(CampaignId = iCamp.Id, ContactId = con.Id);
            } else if(iCamp.Name == 'EventCampaign') {
                eventId = (String) iCamp.Id;
                evMember = new CampaignMember(CampaignId = iCamp.Id, ContactId = con.Id);
            }
        }
        //add campaign IDs to SPS
        Staged_Prospective_Student__c sps = TestHelper.createSPS(1)[0];
        sps.First_Name__c = 'StagedProspectiveStudentDAOV2_Test';
        sps.Last_Name__c = 'Test';
        sps.Email__c = 'test@test.org';
        sps.Exploded_Target__c = con.Id;
        sps.Event_Campaigns__c = eventId;
        sps.Subscription_Lists__c = subId;
        sps.Acquisition_Source_Campaign__c = acqId;

        StagedProspectiveStudentDAOV2 dao = new StagedProspectiveStudentDAOV2(sps);
        ProspectiveStudentCampaignDAO campaignDAO;

        Test.startTest();

        //when
        dao.addCampaignMember(subListMember);
        dao.addCampaignMember(evMember);
        dao.addCampaignMember(acqMember);
        campaignDAO = dao.campaignDAO;

        Test.stopTest();


        //then
        System.assert(campaignDAO.subscriptionListMembers.containsKey(subId),
            'Unable to add Subscription Member to DAO');
        System.assert(campaignDAO.eventMembers.containsKey(eventId),
            'Unable to add Event Member to DAO');
        System.assert(campaignDAO.acquisitionSourceMembers.containsKey(acqId),
            'Unable to add Acquisition Member to DAO');
    }
}