force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Used to force uniqueness on course code. Updated from workflow.</description>
        <externalId>true</externalId>
        <label>Course Code Unique</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Job_Code__c</fullName>
        <label>Job Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CRICOS_Code__c.object
<CustomObject>
    <fields>
        <fullName>Course_Version_Key__c</fullName>
        <label>Course Version Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>CRICOS Codes</relationshipLabel>
        <relationshipName>CRICOS_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Unit_Set_Version_Key__c</fullName>
        <label>Unit Set Version Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Set</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>CRICOS Codes (Unit Set)</relationshipLabel>
        <relationshipName>Unit_Set_CRICOS_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRICOS Code</label>
    <nameField>
        <label>CRICOS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRICOS Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Control__c.object
<CustomObject>
    <fields>
        <fullName>Job_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Job Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Number_of_Records_Processed__c</fullName>
        <label>Number of Records Processed</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Loading Target In Progress</fullName>
                </value>
                <value>
                    <fullName>Target Load Completed</fullName>
                </value>
                <value>
                    <fullName>CRM Ready to Process</fullName>
                </value>
                <value>
                    <fullName>Staging Load Started</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Update_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>To find the number of times the record was updated in salesforce</description>
        <label>Record Update Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job Control</label>
    <nameField>
        <displayFormat>J-{0000000}</displayFormat>
        <label>Job Control Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/jobTriggerMapping__mdt.object
<CustomObject>
    <description>Created to generic mapping of the staging tables to target objects</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <metadataRelationshipControllingField>jobTriggerMapping__mdt.Source_Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>jobTriggerMapping</relationshipLabel>
        <relationshipName>jobTriggerMapping</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <label>Source Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>jobTriggerMapping</relationshipLabel>
        <relationshipName>jobTriggerMapping</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <label>Target Field</label>
        <metadataRelationshipControllingField>jobTriggerMapping__mdt.Target_Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>jobTriggerMapping1</relationshipLabel>
        <relationshipName>jobTriggerMapping1</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Target_Object__c</fullName>
        <label>Target Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>jobTriggerMapping1</relationshipLabel>
        <relationshipName>jobTriggerMapping1</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>jobTriggerMapping</label>
    <pluralLabel>jobTriggerMapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Stg_CRICOS_Code__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Course Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Version_Key__c</fullName>
        <label>Course Version Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Code__c</fullName>
        <label>Job Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Status__c</fullName>
        <label>Record Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Set_Version_Key__c</fullName>
        <label>Unit Set Version Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Stg CRICOS Code</label>
    <nameField>
        <label>CRICOS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stg CRICOS Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/JobTriggerHandlerCriCodeHelper.cls
/*******************************************************************************
* @author       Nitin Khandelwal
* @date         7.June.2018        
* @description  Helper class for jobtriggerhandler. It will process the records from staging CRICOS Code object to
CRICOS Code object
* @revision     07 June 2018

*******************************************************************************/

public class JobTriggerHandlerCriCodeHelper {
    
    private static List<jobTriggerMapping__mdt> lstFieldMapping = null;
    private static Schema.SObjectType sobType = null;
    
    public static void initializeJobControlRecord(Schema.SObjectType sobTypePar, List<jobTriggerMapping__mdt> lstFieldMappingPar)
    {
        lstFieldMapping = lstFieldMappingPar;
        sobType = sobTypePar;
    }
    
    public static void processJobControlRecord(String sUniqueId, String sObjectName, String sType)
    {
        if(lstFieldMapping ==null)
            lstFieldMapping = [SELECT Source_Field__r.QualifiedApiName, Source_Object__c, Target_Field__r.QualifiedApiName, Target_Object__r.QualifiedApiName 
                               FROM jobTriggerMapping__mdt WHERE Target_Object__r.DeveloperName =:sObjectName AND IsActive__c = true];
        if(sobType == null)
            sobType = Schema.getGlobalDescribe().get(lstFieldMapping[0].Target_Object__r.QualifiedApiName);
        String sQueryForUniqueId = getQuery(sObjectName, sUniqueId);
        List<Stg_CRICOS_Code__c> lstStaging = Database.query(sQueryForUniqueId);
        List<sObject> lstSObject = new List<sObject>();
        for(Stg_CRICOS_Code__c oStag: lstStaging)
        {
            lstSObject.add(createNewRecordFromMappingStgCriCode(oStag, sObjectName));
            oStag.Record_Status__c = 'Completed';
        }
        lstSObject = addCourseIds(lstSObject);
        lstSObject = addUnitSetIds(lstSObject);
        system.debug('lstSObject' + lstSObject.size());
        
        //split the list for insert and update 
        
        Map<String,SObject> extIdMap = new Map<String,SObject>();
        for(SObject so : lstSObject){
            extIdMap.put((String)so.get('Unique_Key__c'),so);
        }
        system.debug('extIdMap' + extIdMap);
        Set<String> extIdSet = extIdMap.keyset();
        String splitQuery = 'SELECT Id,Unique_Key__c FROM '+String.valueOf(sobType) +' WHERE Unique_Key__c in :extIdSet';
        system.debug(splitQuery);
        List<SObject> insertList = new List<SObject>();
        Map<Id,SObject> updateMap = new Map<Id,SObject>();
        Map<String,Id> queryMap = new Map<String,Id>();
        for(SObject so : database.query(splitquery)){
            queryMap.put((String)so.get('Unique_Key__c'), so.Id);
        }
        for(SObject so : lstSObject){
            Id theId = queryMap.get((String)so.get('Unique_Key__c'));
            if(theId != null){
                so.Id = theId;
                updateMap.put(theId,so);
            }
            else{
                insertList.add(so);
            }
        }
        system.debug('insertList' + insertList.size());
        system.debug('Update' + updateMap.values().size());
        // lstSObject =addUnitIds(lstSObject);
        Database.SaveResult[] srStagingList = Database.update(lstStaging, false);
        
        // Iterate through each returned result
        for (Database.SaveResult srStag : srStagingList) {
            if (srStag.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : srStag.getErrors()) {
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Staging fields that affected this error: ' + err.getFields());
                }
            }
        }
        Database.SaveResult[] srInsertList = Database.insert(insertList, false);
        
        // Iterate through each returned result
        for (Database.SaveResult srInsert : srInsertList) {
            if (srInsert.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : srInsert.getErrors()) {
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Course fields that affected this error: ' + err.getFields());
                }
            }
        }
        Database.SaveResult[] UpdateList = Database.update(updateMap.values(), false);
        
        // Iterate through each returned result
        for (Database.SaveResult srUpdate : UpdateList) {
            if (srUpdate.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : srUpdate.getErrors()) {
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Course fields that affected this error: ' + err.getFields());
                }
            }
        }

        // updating the job control table record after the processing of records is complete
        List<Job_Control__c> jobList = new List<Job_Control__c>();
        for(Job_Control__c  obj : [Select Id,Processing_Status__c,Record_Update_Count__c,Number_of_Records_Processed__c from Job_Control__c where Job_Code__c = :sUniqueId]){
            obj.Processing_Status__c = 'Target Load Completed' ; 
            if( obj.Number_of_Records_Processed__c == null){
                obj.Number_of_Records_Processed__c = lststaging.size();
            }
            else  
                obj.Number_of_Records_Processed__c = lststaging.size() + obj.Number_of_Records_Processed__c.intValue();
            obj.Record_Update_Count__c = obj.Record_Update_Count__c.intValue() + 1;
            jobList.add(obj);
        }
        if(!jobList.isEmpty()){
            update jobList;
        }
    }
    private static String getQuery(String sObjectName, String sUniqueId)
    {
        String sQuery = 'SELECT Id ';
        for(jobTriggerMapping__mdt oMDT: lstFieldMapping)
        {
            sQuery += ',' + oMDT.Source_Field__r.QualifiedApiName;   
        }
        sQuery += ' FROM Stg_CRICOS_Code__c' + ' WHERE Job_Code__c =: sUniqueId AND Record_Status__c !=  \'' + 'Completed' + '\'limit 2000';
        return sQuery;
    }
    
    private static sObject createNewRecordFromMappingStgCriCode(Stg_CRICOS_Code__c oStag, String sObjectName)
    {
        sObject sObjectNew = sobType.newSObject();
        for(jobTriggerMapping__mdt oMDT: lstFieldMapping)
        {
            sObjectNew.put(oMDT.Target_Field__r.QualifiedApiName, oStag.get(oMDT.Source_Field__r.QualifiedApiName));
        }
        return sObjectNew;
    }
    
    
    private static List<CRICOS_Code__c> addCourseIds(List<CRICOS_Code__c> listOfCRICOSCodes)
    {
        List<String> CRICOSCodes = new List<String>();
        for(CRICOS_Code__c CRICOSObj: listOfCRICOSCodes)
        {
            CRICOSCodes.add(CRICOSObj.Course_Version_key__c);
        }
        system.debug('course ver keys' + CRICOSCodes);
        Map<String, id> calCodeCalIdMap = new Map<String, id>();
        if(CRICOSCodes.size() > 0)
        {
            List<Course__c > listOfCRICOSCodes1= [select id,Course_Code__c from Course__c where Course_Code__c IN :CRICOSCodes and course_code__c != null];
            for(Course__c courseObj: listOfCRICOSCodes1)
            {
                calCodeCalIdMap.put(courseObj.Course_Code__c, courseObj.id);
            }
            system.debug('course list' + listOfCRICOSCodes1);
            for(CRICOS_Code__c calDateObj: listOfCRICOSCodes)
            {
                calDateObj.course__c = calCodeCalIdMap.get(calDateObj.Course_Version_key__c);
            }
            Set<Course__c> listOfNewCRICOSCodes = new Set<Course__c >();
            Course__c newCal;
            for(CRICOS_Code__c CRICOSObj: listOfCRICOSCodes)
            {
                if(CRICOSObj.Course__c == null)
                {
                    newCal = new Course__c();
                    newCal.name = 'N/A';
                    newCal.Course_Code__c = CRICOSObj.Course_Version_key__c;
                    listOfNewCRICOSCodes.add(newCal);
                }
            }
            if(listOfNewCRICOSCodes.size() > 0)
                Insert new List<Course__c>(listOfNewCRICOSCodes);
            system.debug('stub Course records' + listOfNewCRICOSCodes);
            List<String> CRICOSCodes2 = new List<String>();
            for(CRICOS_Code__c CRICOSObj: listOfCRICOSCodes)
            {
                CRICOSCodes2.add(CRICOSObj.Course_Version_key__c);
            }
            
            List<Course__c > listOfCalendars2 = [select id,Course_Code__c from Course__c where Course_Code__c IN :CRICOSCodes2 and course_code__c != null];
            for(Course__c CRICOSObj: listOfCalendars2)
            {
                calCodeCalIdMap.put(CRICOSObj.Course_Code__c, CRICOSObj.id);
            }
            for(CRICOS_Code__c calDateObj: listOfCRICOSCodes)
            {
                calDateObj.course__c = calCodeCalIdMap.get(calDateObj.Course_Version_key__c);
            }
        }
        return listOfCRICOSCodes;
    }
    private static List<CRICOS_Code__c> addUnitSetIds(List<CRICOS_Code__c> listOfCRICOSCodes2)
    {
        List<String> CRICOSCodes1 = new List<String>();
        for(CRICOS_Code__c CRICOSObj: listOfCRICOSCodes2)
        {
            CRICOSCodes1.add(CRICOSObj.Unit_Set_Version_key__c);
        }
        
        Map<String, id> calCodeCalIdMap1 = new Map<String, id>();
        
        List<Course__c > listOfCRICOSCodes1 = [select id,Course_Code__c from Course__c where Course_Code__c IN :CRICOSCodes1 and course_code__c != null];
        for(Course__c CRICOSObj: listOfCRICOSCodes1)
        {
            calCodeCalIdMap1.put(CRICOSObj.Course_Code__c, CRICOSObj.id);
        }
        for(CRICOS_Code__c calDateObj: listOfCRICOSCodes2)
        {
            calDateObj.unit_set__c = calCodeCalIdMap1.get(calDateObj.Unit_Set_Version_key__c);
        }
        
        return listOfCRICOSCodes2;
    }
    
}