force-app/main/default/objects/Course_Attempt__c.object
<CustomObject>
    <description>Course attempt represents the courses a Contact is related to.</description>
    <fields>
        <fullName>Callista_External_Id__c</fullName>
        <description>Holds a concatenation of the Callista Person Id (from &apos;Contact.Person_Id_unique__c&apos;), and underscore(&apos;_&apos;), and the Course Code (from &apos;Course__c.Name&apos;). This is a unique combination (for academic courses).</description>
        <externalId>true</externalId>
        <inlineHelpText>This field is evaluated and set by the system.</inlineHelpText>
        <label>Callista_External_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to the course (incl. version) of the course attempt</description>
        <label>Course</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>Value does not match the type of allowed courses an attempt record can be related to.</errorMessage>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Course-All</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short Course</value>
            </filterItems>
            <filterItems>
                <field>Course__c.Type__c</field>
                <operation>equals</operation>
                <value>Short_Course</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Attempts</relationshipLabel>
        <relationshipName>Course_Attempts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Attempts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Attempt__c.object
<CustomObject>
    <description>Unit (Subject) enrolment of the student.</description>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <description>The academic year which the unit is attempted (started) in.</description>
        <label>Academic Year</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI_Sequence_Number__c</fullName>
        <description>Calendar sequence number</description>
        <label>CI Sequence Number</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calendar_Type__c</fullName>
        <description>Type of the academic calendar associated with the unit attempt. This is referrenced in forming the External ID of Unit Attempt.</description>
        <label>Calendar Type</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Attempt__c</fullName>
        <description>Parent course attempt which the unit attempt is associated with.</description>
        <label>Course Attempt</label>
        <referenceTo>Course_Attempt__c</referenceTo>
        <relationshipLabel>Unit Attempts</relationshipLabel>
        <relationshipName>Unit_Attempts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Teaching location code of the unit attempt.</description>
        <label>Location</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teaching_Period__c</fullName>
        <label>Teaching Period</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Class__c</fullName>
        <label>Unit Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DAY</fullName>
                </value>
                <value>
                    <fullName>EVENING</fullName>
                </value>
                <value>
                    <fullName>ESP-EC</fullName>
                    <label>ESP ENHANCEMENT CENTRE</label>
                </value>
                <value>
                    <fullName>ESP-TC</fullName>
                    <label>ESP DISTANCE TUTORIAL CENTRE</label>
                </value>
                <value>
                    <fullName>WEEKEND</fullName>
                </value>
                <value>
                    <fullName>RES-DAY</fullName>
                    <label>DAY RESIDENTIAL</label>
                </value>
                <value>
                    <fullName>RES-EVEN</fullName>
                    <label>EVENING RESIDENTIAL</label>
                </value>
                <value>
                    <fullName>BLOCK</fullName>
                </value>
                <value>
                    <fullName>BLOCK-ON</fullName>
                    <label>BLOCK OF ON CAMPUS CLASSES</label>
                </value>
                <value>
                    <fullName>DE</fullName>
                    <label>DISTANCE EDUCATION</label>
                </value>
                <value>
                    <fullName>OFF-EVEN</fullName>
                    <label>OFF CAMPUS EVENING CLASS</label>
                </value>
                <value>
                    <fullName>OFF-DAY</fullName>
                    <label>OFF CAMPUS DAY CLASS</label>
                </value>
                <value>
                    <fullName>OPEN-LEARN</fullName>
                    <label>OPEN LEARNING</label>
                </value>
                <value>
                    <fullName>BLOCK-OFF</fullName>
                    <label>BLOCK OF OFF CAMPUS CLASSES</label>
                </value>
                <value>
                    <fullName>FLEXIBLE</fullName>
                    <label>FLEXIBLE CLASS WITH ON AND OFF CAMPUS LEARNING</label>
                </value>
                <value>
                    <fullName>SPLIT-ON</fullName>
                    <label>SPLIT BLOCK ON CAMPUS CLASSES</label>
                </value>
                <value>
                    <fullName>SPLIT-OFF</fullName>
                    <label>SPLIT BLOCK OFF CAMPUS CLASSES</label>
                </value>
                <value>
                    <fullName>EXT-CAND</fullName>
                    <label>EXTERNAL RESEARCH CANDIDATURE</label>
                </value>
                <value>
                    <fullName>WEEKEND-ON</fullName>
                    <label>WEEKEND ON CAMPUS CLASSES</label>
                </value>
                <value>
                    <fullName>WEEKEND-OF</fullName>
                    <label>WEEKEND OFF CAMPUS CLASSES</label>
                </value>
                <value>
                    <fullName>DAY-OFF</fullName>
                </value>
                <value>
                    <fullName>EVEN-OFF</fullName>
                </value>
                <value>
                    <fullName>OPEN-ONLIN</fullName>
                    <label>OPEN LEARNING - ONLINE DELIVERY ONLY</label>
                </value>
                <value>
                    <fullName>EXAMCLIENT</fullName>
                    <label>COMMERCIAL CLIENT - EXAM ONLY</label>
                </value>
                <value>
                    <fullName>OCL</fullName>
                    <label>OFFCAMPUS LEARNING - PRINT DELIVERY</label>
                </value>
                <value>
                    <fullName>OCL-ONLINE</fullName>
                    <label>OFFCAMPUS LEARNING - PRINT &amp; ONLINE DELIVERY</label>
                </value>
                <value>
                    <fullName>OCL-RESBLK</fullName>
                    <label>OFFCAMPUS LEARNING - WITH RESIDENTIAL BLOCK</label>
                </value>
                <value>
                    <fullName>ONLINE</fullName>
                    <label>FULLY ELECTRONIC DELIVERY</label>
                </value>
                <value>
                    <fullName>ONLINE-DAY</fullName>
                    <label>ELECTRONIC DELIVERY FOR DAY STUDENTS</label>
                </value>
                <value>
                    <fullName>DE-ONLINE</fullName>
                    <label>DISTANCE EDUCATION - PRINT &amp; ONLINE DELIVERY</label>
                </value>
                <value>
                    <fullName>ON-CAMPUS</fullName>
                    <label>ON-CAMPUS BETWEEN 8AM AND 9PM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Code__c</fullName>
        <description>Code of the attempted unit.</description>
        <label>Unit Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to Unit Offering for the Unit Attempt</description>
        <inlineHelpText>Link to Unit Offering for the Unit Attempt</inlineHelpText>
        <label>Unit Offering</label>
        <referenceTo>Unit_Offering__c</referenceTo>
        <relationshipLabel>Unit Attempts</relationshipLabel>
        <relationshipName>Unit_Attempts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Version__c</fullName>
        <description>Version of the attempted unit.</description>
        <label>Unit Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Unit Attempt</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Offering__c.object
<CustomObject>
    <description>Unit offering table to hold the data at a unit level</description>
    <fields>
        <fullName>Academic_Year__c</fullName>
        <label>Academic Year</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active_Ind__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active Ind</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CI_Sequence_Number__c</fullName>
        <label>CI Sequence Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calendar_Type__c</fullName>
        <label>Calendar Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Campus</description>
        <label>Location</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teaching_Period__c</fullName>
        <label>Teaching Period</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Code__c</fullName>
        <description>Code of the attempted unit.</description>
        <label>Unit Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Version__c</fullName>
        <description>Unit Version</description>
        <label>Unit Version</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Unit Offering</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Offerings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/UnitAttemptServices_Test.cls
/**
 * @author Nick Guia
 * @description Test class for UnitAttemptServices
 * @revision
 * 	DEC.06.2018 	Nick Guia 	- Initial version
 */
@isTest(isParallel=true)
private class UnitAttemptServices_Test {

	private final static String PERSON_ID = '12345678';
	private final static String COURSE_CODE = 'CODE01';
	private final static Integer MAX_SETUP_RECORDS = 1; //max number for bulk test
	private final static Integer MAX_BULK_TEST = 200; //max number for bulk test

	@testSetup
	static void setup() {
		//create contact
		Contact con = TestHelper.createOrphanContactRecords(MAX_SETUP_RECORDS)[0];
		con.Person_ID_unique__c = PERSON_ID;
		insert con;
		Assert.areEqual(MAX_SETUP_RECORDS, [SELECT COUNT() FROM Contact], 'An error occurred while creating setup Contact');

		//create course
		Course__c courseRec = TestHelper.createCoursesWithType(MAX_SETUP_RECORDS, 'Course-All')[0];
		courseRec.Name = COURSE_CODE;
		insert courseRec;
		Assert.areEqual(MAX_SETUP_RECORDS, [SELECT COUNT() FROM Course__c], 'An error occurred while creating setup Course');

		//create course attempt
		Course_Attempt__c ca = TestHelper.createCourseAttempts(MAX_SETUP_RECORDS, con.Id, courseRec.Id)[0];
		//set external id
		ca.Callista_External_Id__c = PERSON_ID + '_' + COURSE_CODE;
		insert ca;
		Assert.areEqual(MAX_SETUP_RECORDS, [SELECT COUNT() FROM Course_Attempt__c], 'An error occurred while creating setup Course Attempt');      
        
        Unit_Offering__c uo = new Unit_Offering__c(Academic_Year__c = '2021'
                                                  , Active_Ind__c = true
                                                  , Location__c = 'Clayton'
                                                  , Unit_Version__c = '1'
                                                  , Unit_Code__c = 'UnitXYZ'
                                                  , Calendar_Type__c = 'S0-1' 
                                                  , Teaching_Period__c = 'S0-1'
                                                  , CI_Sequence_Number__c = '10001'
                                                  , Unit_Class__c = 'ON-CAMPUS');
		
        insert uo;
	}

	/**
	 * Test Scenario:
     *  Insert new Unit Attempt. Name should be pre-populated with format as follows:
     *  PERSON_ID/COURSE_CD/UNIT_CD/CAL_TYPE/ACADEMIC_YEAR
	 */
	@isTest
	static void test_populateUnitAttemptName() {
		Contact con = [SELECT Id FROM Contact LIMIT 1];
		Course_Attempt__c ca = [SELECT Id FROM Course_Attempt__c LIMIT 1];

		//create test unit attempt
		Unit_Attempt__c ua = TestHelper.createUnitAttempts(1, ca.Id, con.Id)[0];
		
		Test.startTest();
		insert ua;
		Test.stopTest();

        ua = [SELECT Id, Name, Student_Person_ID__c, Course_Code__c, Unit_Code__c, Teaching_Period__c, Academic_Year__c, deleted_in_source__c
                FROM Unit_Attempt__c
                WHERE Id = :ua.Id
                LIMIT 1];
        
        String uniqueName = UnitAttemptServices.getUniqueName(ua);
        Assert.areEqual(uniqueName, ua.Name);
	}

    /**
     * Test Scenario:
     *  Insert new Unit Attempt. SUA_External_ID__c should be pre-populated with format as follows:
     *  PERSON_ID-COURSE_CD-UNIT_CD-CAL_TYPE-CI_SEQUENCE_NUMBER
     */
    @isTest
    static void test_populateUnitAttemptExt() {
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Course_Attempt__c ca = [SELECT Id FROM Course_Attempt__c LIMIT 1];

        //create test unit attempt
        Unit_Attempt__c ua = TestHelper.createUnitAttempts(1, ca.Id, con.Id)[0];
        
        Test.startTest();
            insert ua;
        Test.stopTest();

        ua = [SELECT Id, Student_Person_ID__c, Course_Code__c, Unit_Code__c, 
                Calendar_Type__c, CI_Sequence_Number__c, SUA_External_ID__c
                FROM Unit_Attempt__c
                WHERE Id = :ua.Id
                LIMIT 1];
        String uniqueExt = UnitAttemptServices.getUniqueExt(ua);
        Assert.areEqual(uniqueExt, ua.SUA_External_ID__c);
    }

    /**
     * Test Scenario:
     *  getUniqueName() method should return the following name format:
     *  PERSON_ID/COURSE_CD/UNIT_CD/CAL_TYPE/ACADEMIC_YEAR
     */
    @isTest
    static void test_getUniqueName() {
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Course_Attempt__c ca = [SELECT Id FROM Course_Attempt__c LIMIT 1];

        //create test unit attempt
        Unit_Attempt__c ua = TestHelper.createUnitAttempts(1, ca.Id, con.Id)[0];
        
        Test.startTest();
            insert ua;
            ua = [SELECT Id, Name, Student_Person_ID__c, Course_Code__c, Unit_Code__c, Teaching_Period__c, Academic_Year__c, deleted_in_source__c
                    FROM Unit_Attempt__c
                   WHERE Id = :ua.Id
                   LIMIT 1];
            String uniqueName = UnitAttemptServices.getUniqueName(ua);
        Test.stopTest();

        String expected = ua.Student_Person_ID__c + '/' + 
                        ua.Course_Code__c + '/' + 
                        ua.Unit_Code__c + '/' + 
                        ua.Academic_Year__c + '-' + ua.Teaching_Period__c  ;
        Assert.areEqual(expected, uniqueName);
    }

     /**
     * Test Scenario:
     *  getUniqueExt() method should return the following name format:
     *  PERSON_ID-COURSE_CD-UNIT_CD-CAL_TYPE-CI_SEQUENCE_NUMBER
     */
    @isTest
    static void test_getUniqueExt() {
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Course_Attempt__c ca = [SELECT Id FROM Course_Attempt__c LIMIT 1];

        //create test unit attempt
        Unit_Attempt__c ua = TestHelper.createUnitAttempts(1, ca.Id, con.Id)[0];
        
        Test.startTest();
            insert ua;
            String uniqueExt = UnitAttemptServices.getUniqueExt(ua);
        Test.stopTest();

        ua = [SELECT Id, Student_Person_ID__c, Course_Code__c, Unit_Code__c, 
                Calendar_Type__c, CI_Sequence_Number__c, SUA_External_ID__c
                FROM Unit_Attempt__c
                WHERE Id = :ua.Id
                LIMIT 1];

        String expected = ua.Student_Person_ID__c + '-' + 
                        ua.Course_Code__c + '-' + 
                        ua.Unit_Code__c + '-' + 
                        ua.Calendar_Type__c + '-' + 
                        ua.CI_Sequence_Number__c;
        Assert.areEqual(expected, ua.SUA_External_ID__c);
    }

	/**
	 * For testing bulkified logic. Should be capable of inserting at least
	 * 200 records at a time.
	 */
	@isTest
	static void test_bulk_insert() {
		Contact con = [SELECT Id FROM Contact LIMIT 1];
		Course_Attempt__c ca = [SELECT Id FROM Course_Attempt__c LIMIT 1];

		//create unit attempt for 'update' and 'delete' scenario
		List<Unit_Attempt__c> uaList = TestHelper.createUnitAttempts(MAX_BULK_TEST, ca.Id, con.Id);
		Test.startTest();
			insert uaList;
		Test.stopTest();
		Assert.areEqual(MAX_BULK_TEST, 
							[SELECT COUNT() FROM Unit_Attempt__c], 
							'An error occurred while creating bulk Unit Attempts. size : ' + MAX_BULK_TEST);
	}

    
    /**
     * 
     * If a SUA is received from Callista before the unit offering is received, the field remains empty unless it's reimported.
     * We can now simply update to SUA to attach it with the correct UO
     * 
     * GIVEN
     * An existing unit attempt with a null unit_offering__c field
     * WHEN
     * Its updated and has the correct data to match a unit offering
     * THEN
     * The unit offering field is populated
     **/
  	@isTest
	static void test_assignUnitOffering() {
		Contact con = [SELECT Id FROM Contact LIMIT 1];
		Course_Attempt__c ca = [SELECT Id FROM Course_Attempt__c LIMIT 1];

		//create unit attempt for 'update' and 'delete' scenario
		Unit_Attempt__c ua = TestHelper.createUnitAttempts(1, ca.Id, con.Id)[0];
		ua.Academic_Year__c = '2021';
        ua.Location__c = 'Clayton';
        ua.Unit_Version__c = 1;
        ua.Unit_Code__c = 'UnitXYZ';
        ua.Calendar_Type__c = 'S0-1' ;
        ua.Teaching_Period__c = 'S0-1';
        ua.CI_Sequence_Number__c = '10001';
		insert ua;
        
        Test.startTest();
        ua.Unit_Class__c = 'ON-CAMPUS';
        update ua;
		Test.stopTest();

        ua = [select unit_offering__c from unit_attempt__c where id = :ua.id];
		Assert.isNotNull(ua.unit_offering__c);        
	}

}