force-app/main/default/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Managing_Faculty__c</fullName>
        <label>Managing Faculty/School/Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>a</fullName>
                </value>
                <value>
                    <fullName>Faculty of Art, Design &amp; Architecture</fullName>
                </value>
                <value>
                    <fullName>Faculty of Arts</fullName>
                </value>
                <value>
                    <fullName>Faculty of Business &amp; Economics</fullName>
                </value>
                <value>
                    <fullName>Faculty of Education</fullName>
                </value>
                <value>
                    <fullName>Faculty of Engineering</fullName>
                </value>
                <value>
                    <fullName>Faculty of Information Technology</fullName>
                </value>
                <value>
                    <fullName>Faculty of Law</fullName>
                </value>
                <value>
                    <fullName>Faculty of Medicine, Nursing &amp; Health Sciences</fullName>
                </value>
                <value>
                    <fullName>Faculty of Pharmacy &amp; Pharmaceutical Sciences</fullName>
                </value>
                <value>
                    <fullName>Faculty of Science</fullName>
                </value>
                <value>
                    <fullName>Monash Centre for Professional Development</fullName>
                </value>
                <value>
                    <fullName>Monash College</fullName>
                </value>
                <value>
                    <fullName>Monash College Diplomas</fullName>
                </value>
                <value>
                    <fullName>Monash Injury Research Institute</fullName>
                </value>
                <value>
                    <fullName>Monash Sustainable Development Institute</fullName>
                </value>
                <value>
                    <fullName>Monash University English Language Centre</fullName>
                </value>
                <value>
                    <fullName>Monash University Foundation Year</fullName>
                </value>
                <value>
                    <fullName>Monash University Foundation Year MUFY</fullName>
                </value>
                <value>
                    <fullName>PPA</fullName>
                </value>
                <value>
                    <fullName>School of Clinical Sciences (SCS)</fullName>
                </value>
                <value>
                    <fullName>Monash Centre for Health Research and Implementation (MCHRI)</fullName>
                </value>
                <value>
                    <fullName>MNHS Student Academic Support Unit (SASU)</fullName>
                </value>
                <value>
                    <fullName>The School of Public Health and Preventive Medicine (SPHPM)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Offering__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Offering</label>
    <nameField>
        <displayFormat>CrOf-{0000}</displayFormat>
        <label>Course Offering Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Faculty_Custom_Data__mdt.object
<CustomObject>
    <description>Created for: PD | Holds: Faculty specific contact details to use in email templates | Match &apos;Faculty Name&apos; to Course object&apos;s picklist &apos;Managing Faculty&apos;</description>
    <fields>
        <fullName>Managing_Faculty__c</fullName>
        <label>Managing Faculty</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Faculty Custom Data</label>
    <pluralLabel>Faculty Custom Data</pluralLabel>
</CustomObject>

force-app/main/default/classes/CourseLookupController_Test.cls
/**
* @author Vineeth Batreddy
* @date 2017
* @group Professional Development
* @description Test class for CourseLookupController
* @revision Nadula karunaratna | 14-02-2020 | Refactored test class by seperating test methods, adding System.assertEquals and added a new test method testRetrieveFacultyData.
*/
@isTest(isParallel=true)
private class CourseLookupController_Test {
	
    @isTest static void testGetCourseOffering() {        
       	Course__c course = PDTestHelper.createCourse();
       	Course_Offering__c co = PDTestHelper.createCourseOffering();
       	co.Course__c = course.Id;
       	update co;		
		String courseName = course.Name;
        String courseFaculty = course.Managing_Faculty__c;
        System.DEBUG('courseName='+courseName);        
        
        Test.startTest();
       	//Positive test
        List<Course_Offering__c> courseOfferingsTrue = CourseLookupController.getCourseOffering(courseName);
        //Negative test
        List<Course_Offering__c> courseOfferingsFalse = CourseLookupController.getCourseOffering('courseNameTestText');
        Test.stopTest();       
	}

	@isTest static void testGetCourseDetails() {        
       	Course__c course = PDTestHelper.createCourse();
       	Course_Offering__c co = PDTestHelper.createCourseOffering();
       	co.Course__c = course.Id;
       	update co;		
		String courseName = course.Name;
        Test.startTest();
        //Positive test
       	Course__c courseDetailsTrue = CourseLookupController.getCourseDetails(courseName);
        //Negative test
        Course__c courseDetailsFalse = CourseLookupController.getCourseDetails('courseNameTestText');
        Test.stopTest();
        System.assertEquals(courseName, courseDetailsTrue.Name);  
        System.assert(courseDetailsFalse == null);
	}    
    
	@isTest static void testRetrieveFacultyEmail(){        
       	Course__c course = PDTestHelper.createCourse();	
		String courseName = course.Name; 
       	
        Test.startTest(); 
        //Positive test
        String facultyEmailTrue = CourseLookupController.retrieveFacultyEmail(courseName);        
        //Negative test
        String facultyEmailFalse = CourseLookupController.retrieveFacultyEmail('courseNameTestText');
        Test.stopTest();
        
        System.assert(facultyEmailTrue != null);
        System.assert(facultyEmailFalse == null);
    }

	@isTest static void testRetrieveFacultyData(){        
       	Course__c course = PDTestHelper.createCourse();	
		String courseName = course.Name;
        String courseFaculty = course.Managing_Faculty__c;
       	
        Test.startTest();
        //Positive test
        List<Faculty_Custom_Data__mdt> facultyDataTrue = CourseLookupController.retrieveFacultyData(courseName);
        //Negative test
        List<Faculty_Custom_Data__mdt> facultyDataFalse = CourseLookupController.retrieveFacultyData('courseNameTestText');
        Test.stopTest();        
        System.assertEquals(courseFaculty, facultyDataTrue[0].Managing_Faculty__c);  
        System.assert(facultyDataFalse == null);
    }
}