force-app/main/default/objects/CustomURLs__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to hold configuration for ask Monash community</description>
    <fields>
        <fullName>replacement_url_suffix__c</fullName>
        <label>replacement url suffix</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>standard_url_suffix__c</fullName>
        <label>standard url suffix</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Community Settings</label>
</CustomObject>

force-app/main/default/objects/Knowledge_Article__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Public facing only</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Australia_Staff__c</fullName>
        <description>Please enter information useful for Australia Staff</description>
        <label>Australian Staff</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Australia_Student__c</fullName>
        <label>Australian Students, Staff &amp; Public</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge/Article</label>
    <pluralLabel>Knowledge/Articles</pluralLabel>
    <recordTypes>
        <fullName>FAQ</fullName>
        <active>true</active>
        <label>FAQ</label>
    </recordTypes>
    <recordTypes>
        <fullName>Knowledge</fullName>
        <active>true</active>
        <label>Knowledge</label>
    </recordTypes>
</CustomObject>

force-app/main/default/classes/LightningArticleDetailController.cls
public with sharing class LightningArticleDetailController {
    
    @AuraEnabled
    public static sobject getArticleDetail(Id ArticleId) {
        sobject articleDetail = null;
        string articleType;
        system.debug('>>>>>'+articleId);
        String profileName=[select id,Name from profile where id=:userInfo.getProfileId()].Name;
        // Fix for Staff Profile to see Staff related articles
        PermissionSetAssignment psa;
        for(PermissionSetAssignment loopPSA : [SELECT Id, PermissionSet.Name, AssigneeId  
                                               FROM PermissionSetAssignment
                                               WHERE AssigneeId = :Userinfo.getUserId() 
                                               		AND PermissionSet.Name = :Label.Community_Staff_Permissions_Name]){
            psa = loopPSA;
        }
        
        Set<String> studentProfiles=new Set<String>();
        studentProfiles.addAll(Label.Student_Profiles.split(','));
        Set<String> staffProfiles=new Set<String>();
        staffProfiles.addAll(Label.Community_Staff_Profile.split(','));
        if(articleId != null) {
            string knowledgeArticletype = string.valueof(ArticleId.getSObjectType());
            string articleNumberQuery ='Select ArticleNumber from '+knowledgeArticletype+' where id =\''+articleId+'\' LIMIT 1';
            sobject kaArticleRecord = database.query(articleNumberQuery);
            string articleNumber = string.valueof(kaArticleRecord.get('ArticleNumber'));
            
            if(knowledgeArticletype.right(3) != 'kav') {
                articleType = knowledgeArticletype+'v'; 
            } else {
                articleType = knowledgeArticletype;
            }
            
            /* Temporarily Increase Code Coverage */
            String query;
            query ='Select Title,Summary,Answer__c,Australia_Staff__c,Australia_Student__c,RecordTypeId from '+articleType+' where ArticleNumber =\''+articleNumber+'\' and PublishStatus=\'Online\' LIMIT 1';
            articleDetail = database.query(query);
            
            Id faqRecordTypeId = Schema.SObjectType.Knowledge_Article__kav.getRecordTypeInfosByName().get('FAQ').getRecordTypeId();
            /* Fix for lightning knowledge migration - all contents are pushed to Australia_Student__c field*/
            if(articleDetail.get('RecordTypeId') == faqRecordTypeId){
            	/* Logic to run on FAQ articles */
                if(staffProfiles.contains(profileName) || psa!=null) {
                    articleDetail.put('Australia_Staff__c',convertSmartLink((String)articleDetail.get('Australia_Staff__c')));
                }else{
                    articleDetail.put('Australia_Staff__c',null);                   
                }
                
            	articleDetail.put('Australia_Student__c', convertSmartLink((String)articleDetail.get('Australia_Student__c')));	
            	articleDetail.put('Answer__c',null);
            	/* Temporarily Increase Code Coverage */
            }else{
            	/* Logic to run on non-FAQ articles */
	            if(Label.Guest_User_Profile_Name==profileName)
	            {
	                articleDetail.put('Australia_Staff__c',null);
	                articleDetail.put('Australia_Student__c',null);
	                articleDetail.put('Answer__c',convertSmartLink((String)articleDetail.get('Answer__c')));
	            }
	            else if(studentProfiles!=null && studentProfiles.contains(profileName))
	            {
	                articleDetail.put('Australia_Staff__c',null);
	                articleDetail.put('Australia_Student__c',convertSmartLink((String)articleDetail.get('Australia_Student__c')));
	                articleDetail.put('Answer__c',null);
	            }
	            else
	            {
	                articleDetail.put('Australia_Staff__c',convertSmartLink((String)articleDetail.get('Australia_Staff__c')));
	                articleDetail.put('Australia_Student__c',convertSmartLink((String)articleDetail.get('Australia_Student__c')));
	                articleDetail.put('Answer__c',null);
	            }
            }
            
            system.debug('>>>>'+articleDetail);
        }
        
        return articleDetail;
    }
   
    public static String convertSmartLink(String data)
    {
        if(data==null)
            return data;
        CustomURLs__c urls=CustomURLs__c.getInstance();
        return data.replaceAll(urls.standard_url_suffix__c,urls.replacement_url_suffix__c);
    }
}