force-app/main/default/objects/Designation_Detail_Portal__c.object
<CustomObject>
    <description>This object holds information about how a pledge&apos;s allocations of money in different designations</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The total amount of payments going into one designation.</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Designation</label>
        <referenceTo>Designation_Portal__c</referenceTo>
        <relationshipName>Designation_Details_Designation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <description>Transaction Summary Record</description>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipName>Designation_Details_Transaction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Designation Detail (Portal)</label>
    <nameField>
        <label>Designation Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designation Details (Portal)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Designation_Portal__c.object
<CustomObject>
    <label>Designation (Portal)</label>
    <nameField>
        <label>Designation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designations (Portal)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Portal__c.object
<CustomObject>
    <description>Payment details of a pledge / gift</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Payment amount</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Designation_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Designation Detail</label>
        <referenceTo>Designation_Detail_Portal__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments_Portal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Designation</label>
        <referenceTo>Designation_Portal__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments_Designation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <description>The pledge of gift the payment is paying to</description>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipName>Payments_Transaction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment (Portal)</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments (Portal)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>Tracks the total amount that a donor made in one portal transaction</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiration_Date__c</fullName>
        <label>Credit Card Expiration Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <description>Encrypted credit card number for data security</description>
        <label>Credit Card Number</label>
        <length>19</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credit_Card_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Date__c</fullName>
        <description>The date that the transaction is created and credited</description>
        <label>Credit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <description>The file entry date of the transaction</description>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Online_Payment_Charge_ID__c</fullName>
        <label>Online Payment Charge ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unassigned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <description>Pledge payment / gift payment</description>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Credit_Card_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Express</fullName>
    </customValue>
    <customValue>
        <fullName>Discover</fullName>
    </customValue>
    <customValue>
        <fullName>MasterCard</fullName>
    </customValue>
    <customValue>
        <fullName>Visa</fullName>
    </customValue>
    <description>Credit Card Types</description>
    <masterLabel>Credit Card Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PORTAL_TRIG_DesignationDetailPortal_Test.cls
/*
 * Copyright (c) 2019, UC Innovation, Inc.  All Rights Reserved.
 *                     http://www.ucinnovation.com
 *
 * This source code is licensed, not sold, and is subject to a written
 * license agreement.  Among other things, no portion of this source
 * code may be copied, transmitted, disclosed, displayed, distributed,
 * translated, used as the basis for a derivative work, or used, in
 * whole or in part, for any program or purpose other than its intended
 * use in compliance with the license agreement as part of UC Innovation's
 * software.  This source code and certain of the algorithms contained
 * within it are confidential trade secrets of UC Innovation, Inc.
 * and may not be used as the basis for any other
 * software, hardware, product or service.
 */
 
 @isTest(isParallel=true)
public class PORTAL_TRIG_DesignationDetailPortal_Test {
    static testMethod void createDesignationDetail() {
        
        Designation_Portal__c design = new Designation_Portal__c();
        design.Name = 'School of Computer Science';
        insert design;
        
        Transaction__c trans = new Transaction__c();
        trans.Status__c = 'Unassigned';
        trans.Credit_Card_Type__c = 'Visa';
        trans.Credit_Card_Expiration_Date__c = '11/50';
        trans.Entry_Date__c = Date.today();
        trans.Credit_Date__c = Date.today();
        trans.Credit_Card_Number__c = '4242424242424242';
        trans.Online_Payment_Charge_ID__c = 'test123456';
        insert trans;
        
        Designation_Detail_Portal__c designDetail = new Designation_Detail_Portal__c();
        designDetail.Designation__c = design.Id;
        designDetail.Amount__c = 100000;
        designDetail.Transaction__c = trans.Id;
        insert designDetail;

        Payment_Portal__c payment = new Payment_Portal__c();
        payment.Amount__c = 100000;
        payment.Designation__c = design.Id;
        payment.Designation_Detail__c = designDetail.Id;
        payment.Transaction__c = trans.Id;
        insert payment;
    }
}