force-app/main/default/objects/Fields_of_Research__c.object
<CustomObject>
    <description>ANZSRC Fields of Research (FoR) Codes (https://www.arc.gov.au/sites/default/files/minisite/static/10419/ERA2015/app-3_appendix-2.html)</description>
    <fields>
        <fullName>ERA_Cluster_Name__c</fullName>
        <description>ERA Cluster Name</description>
        <inlineHelpText>ERA Cluster Name</inlineHelpText>
        <label>ERA Cluster Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERA_Cluster__c</fullName>
        <description>ANZSRC Fields of Research (FoR) Category</description>
        <inlineHelpText>ANZSRC Fields of Research (FoR) Category</inlineHelpText>
        <label>ERA Cluster</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01 Mathematical Sciences</fullName>
                </value>
                <value>
                    <fullName>02 Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>03 Chemical Sciences</fullName>
                </value>
                <value>
                    <fullName>04 Earth Sciences</fullName>
                </value>
                <value>
                    <fullName>05 Environmental Sciences</fullName>
                </value>
                <value>
                    <fullName>06 Biological Sciences</fullName>
                </value>
                <value>
                    <fullName>07 Agricultural and Veterinary Sciences</fullName>
                </value>
                <value>
                    <fullName>08 Information and Computing Sciences</fullName>
                </value>
                <value>
                    <fullName>09 Engineering</fullName>
                </value>
                <value>
                    <fullName>10 Technology</fullName>
                </value>
                <value>
                    <fullName>11 Medical and Health Sciences</fullName>
                </value>
                <value>
                    <fullName>12 Built Environment and Design</fullName>
                </value>
                <value>
                    <fullName>13 Education</fullName>
                </value>
                <value>
                    <fullName>14 Economics</fullName>
                </value>
                <value>
                    <fullName>15 Commerce, Management, Tourism and Services</fullName>
                </value>
                <value>
                    <fullName>16 Studies in Human Society</fullName>
                </value>
                <value>
                    <fullName>17 Psychology and Cognitive Sciences</fullName>
                </value>
                <value>
                    <fullName>18 Law and Legal Studies</fullName>
                </value>
                <value>
                    <fullName>19 Studies in Creative Arts and Writing</fullName>
                </value>
                <value>
                    <fullName>20 Language, Communication and Culture</fullName>
                </value>
                <value>
                    <fullName>21 History and Archaeology</fullName>
                </value>
                <value>
                    <fullName>22 Philosophy and Religious Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FoR_Code__c</fullName>
        <description>FoR Code stating the code/number linked to the Field of Research</description>
        <externalId>true</externalId>
        <inlineHelpText>FoR Code - https://www.arc.gov.au/sites/default/files/minisite/static/10419/ERA2015/app-3_appendix-2.html</inlineHelpText>
        <label>FoR Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FoR_Name__c</fullName>
        <description>FoR Name</description>
        <inlineHelpText>FoR Name</inlineHelpText>
        <label>FoR Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Fields of Research</label>
    <nameField>
        <label>FoR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields of Research</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_FoR__c.object
<CustomObject>
    <description>FoRs Linked to Opportunities</description>
    <fields>
        <fullName>Fields_of_Research__c</fullName>
        <description>Links to the associated Field Of Research</description>
        <inlineHelpText>Links to the associated Field Of Research</inlineHelpText>
        <label>Fields of Research</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Fields_of_Research__c.Hierarchical_level__c</field>
                <operation>notEqual</operation>
                <value>Division</value>
            </filterItems>
            <filterItems>
                <field>Fields_of_Research__c.Inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Fields_of_Research__c</referenceTo>
        <relationshipLabel>Opportunity FoR</relationshipLabel>
        <relationshipName>Opportunity_FoRs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Links to the associated Opportunity</description>
        <inlineHelpText>Links to the associated Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Fields of Research</relationshipLabel>
        <relationshipName>Opportunity_FoRs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <description>Percentage allocated to this FoR</description>
        <inlineHelpText>Percentage allocated to this FoR</inlineHelpText>
        <label>Percentage</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UID__c</fullName>
        <description>Unique Id for FoR/Opportunity combination</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Id for FoR/Opportunity combination</inlineHelpText>
        <label>UID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Opportunity FoR</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Opportunity FoR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity FoRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityFoRTriggerHandler_Test.cls
/**
* @description       : Test class for OpportunityFoRTriggerHandler
* @author            : Inderpal Dhanoa
* @date              : 2022-05-18
* @group             : Enterprise
**/
@isTest(isParallel=false) // Test.getStandardPricebookId() cannot be called from parallel Apex tests
public with sharing class OpportunityFoRTriggerHandler_Test {
    /*******************************************************************************
    * @author       Inderpal Dhanoa
    * @date         18/05/2022
    * @description  Test Setup Method for SyncRefreshPureOpportunityController
    * @revision     1.0
    *******************************************************************************/
    @testSetup
    static void setup() {
        List<Account> relatedAccounts = new List<Account>();
        List<Opportunity> relatedOpportunity = new List<Opportunity>();
        List<Fields_of_Research__c> relatedFoRList = new List<Fields_of_Research__c>();

        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Monash Organisation').getRecordTypeId();

        Account accountRecord = (Account)TestDataFactory.createSObject(new Account(Name = 'AccountTest', NumberOfEmployees = 1, RecordTypeId = recordTypeId), false);
        relatedAccounts.add(accountRecord); 
        
        insert relatedAccounts;

        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Enterprise').getRecordTypeId();
        Opportunity opportunityRecord = (Opportunity)TestDataFactory.createSObject(new Opportunity(name ='OpportunityTest', RecordTypeId = oppRecordTypeId, AccountId = accountRecord.Id, Source__c = 'PURE', StageName = 'Identification', CloseDate = Date.today().addDays(10)),true);

        Fields_of_Research__c testFoR1 = (Fields_of_Research__c)TestDataFactory.createSObject(new Fields_of_Research__c(name ='Test FoR', FoR_Code__c = '123456', ERA_Cluster_Name__c = '123456', ERA_Cluster__c = '01 Mathematical Sciences', FoR_Name__c = '123456'),false);
        Fields_of_Research__c testFoR2 = (Fields_of_Research__c)TestDataFactory.createSObject(new Fields_of_Research__c(name ='Test FoR2', FoR_Code__c = '234567', ERA_Cluster_Name__c = '234567', ERA_Cluster__c = '01 Mathematical Sciences', FoR_Name__c = '234567'),false);

        relatedFoRList.add(testFoR1);
        relatedFoRList.add(testFoR2);

        insert relatedFoRList;

        Opportunity_FoR__c relOpptyFoR = (Opportunity_FoR__c)TestDataFactory.createSObject(new Opportunity_FoR__c(Opportunity__c = opportunityRecord.Id, Fields_of_Research__c = testFoR1.Id, Percentage__c = 10),true);

    }

    /*******************************************************************************
    * @author       Inderpal Dhanoa
    * @date         18/05/2022
    * @description  Test Method for ValidateOwnership Method Failure 
    * @revision     1.0
    *******************************************************************************/
    @isTest 
    public static void ValidateOwnership_Failure_Test(){

        // given : We are inserting the new FoR linked to the Oppty 
        Opportunity linkedOppty = [SELECT Id FROM Opportunity WHERE name ='OpportunityTest' LIMIT 1];

        Fields_of_Research__c linkedFoR2 = [SELECT Id FROM Fields_of_Research__c WHERE name ='Test FoR2' LIMIT 1];
        
        Test.startTest();
        // when: the get Oppty method is initiated 
        try{
            Opportunity_FoR__c relOpptyFoR2 = (Opportunity_FoR__c)TestDataFactory.createSObject(new Opportunity_FoR__c(Opportunity__c = linkedOppty.Id, Fields_of_Research__c = linkedFoR2.Id, Percentage__c = 100),true);
        }catch(Exception ex){
            //then: Get a Validation Error
            string message = ex.getMessage();
            String error = Label.ResearchCollaboratorsExceeded;
         	system.assert(message.contains(error));
        }
        Test.stopTest(); 
    }


    /*******************************************************************************
    * @author       Inderpal Dhanoa
    * @date         18/05/2022
    * @description  Test Method for ValidateOwnership Method Success 
    * @revision     1.0
    *******************************************************************************/
    @isTest 
    public static void ValidateOwnership_Success_Test(){

        // given : The Surviving and target delete Opportunities exist 
        Opportunity linkedOppty = [SELECT Id FROM Opportunity WHERE name ='OpportunityTest' LIMIT 1];

        Fields_of_Research__c linkedFoR2 = [SELECT Id FROM Fields_of_Research__c WHERE name ='Test FoR2' LIMIT 1];
        
        Test.startTest();
        // when: the get Oppty method is initiated 
        Opportunity_FoR__c relOpptyFoR2 = (Opportunity_FoR__c)TestDataFactory.createSObject(new Opportunity_FoR__c(Opportunity__c = linkedOppty.Id, Fields_of_Research__c = linkedFoR2.Id, Percentage__c =90),true);

        Test.stopTest(); 

        Decimal totalPerc = 0;

        for(Opportunity_FoR__c lnkFoR : [SELECT Id, Percentage__c FROM Opportunity_FoR__c]){
            totalPerc = totalPerc + lnkFoR.Percentage__c;
        }
        // then : the total percentage gets added
        system.assertEquals(100.00, totalPerc);
    }

    /*******************************************************************************
    * @author       Inderpal Dhanoa
    * @date         18/05/2022
    * @description  Test Method for setupUID Method 
    * @revision     1.0
    *******************************************************************************/
    @isTest 
    public static void setupUID_Test(){

        // given : The linked Opportunities and FoR's exist 
        Opportunity linkedOppty = [SELECT Id FROM Opportunity WHERE name ='OpportunityTest' LIMIT 1];

        Fields_of_Research__c linkedFoR2 = [SELECT Id FROM Fields_of_Research__c WHERE name ='Test FoR2' LIMIT 1]; 
        
        Test.startTest();
        // when: the get Oppty method is initiated 
        Opportunity_FoR__c relOpptyFoR2 = (Opportunity_FoR__c)TestDataFactory.createSObject(new Opportunity_FoR__c(Opportunity__c = linkedOppty.Id, Fields_of_Research__c = linkedFoR2.Id, Percentage__c =90),true);
        Test.stopTest(); 

        Opportunity_FoR__c lnkFoR = [SELECT Id, UID__c FROM Opportunity_FoR__c WHERE Opportunity__c = :linkedOppty.Id AND Fields_of_Research__c = :linkedFoR2.Id LIMIT 1];

        // then : the total percentage gets added
        system.assertEquals(lnkFoR.UID__c, String.Valueof(linkedFoR2.Id)+String.Valueof(linkedOppty.Id));
    } 
}