force-app/main/default/objects/Graduation_Application__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current state of Application</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Internal Draft</fullName>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Graduation Application</label>
    <nameField>
        <displayFormat>GAPP-{0000000}</displayFormat>
        <label>Graduation Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduation Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Graduation_Award__c.object
<CustomObject>
    <fields>
        <fullName>Callista_Writeback_Requested_Time__c</fullName>
        <description>Time of change that has triggered a writeback</description>
        <label>Callista Writeback Requested Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Graduation_Application__c</fullName>
        <description>Parent Graduation Application</description>
        <label>Graduation Application</label>
        <referenceTo>Graduation_Application__c</referenceTo>
        <relationshipLabel>Graduation Awards</relationshipLabel>
        <relationshipName>Graduation_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Writeback_Apex_Job_Id__c</fullName>
        <description>Id of Async context that is currently processing this Award for writeback</description>
        <label>Writeback Apex Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Writeback_Requested_Age_Minutes__c</fullName>
        <description>Minutes since the last writeback was requested. Blank if no writeback is pending</description>
        <formula>IF(
  ISBLANK(Last_Callista_Writeback_Success_Time__c) || Callista_Writeback_Requested_Time__c &gt; Last_Callista_Writeback_Success_Time__c,
  (NOW() - Callista_Writeback_Requested_Time__c) * 1440,
  NULL
)</formula>
        <label>Writeback Requested Age (Minutes)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Writeback_Retry_Attempt__c</fullName>
        <description>Number of writeback attempts made by GradsCallistaSyncBatch (set to 0 on success)</description>
        <label>Writeback Retry Attempt</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Graduation Award</label>
    <nameField>
        <displayFormat>GAWARD-{0000000}</displayFormat>
        <label>Graduation Award Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduation Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/GradsCallistaSyncBatch.cls
/**
 * @description Batch job for syncing Graduation Awards with Callista.
 *              - Scheduled batch picks up stuck awards
 *              - Manual batch can be used to process a specific set of awards
 * @group       Grads
 * @revision    2024-09-23 - Tom Gangemi - Initial version
 * @revision    2025-08-18 - Tom Gangemi - Avoid retrying in progress writebacks
 */
public with sharing class GradsCallistaSyncBatch implements Database.AllowsCallouts, Database.Stateful, Database.Batchable<Id>, Schedulable {

    public Id[] suppliedAwardIds;

    /**
     * Process retries (awards with Writeback_Requested_Age_Minutes__c >= calculateBackoffMinutes(retryAttempt))
     */
    public GradsCallistaSyncBatch() {}

    /**
     * Process a specific set of awards
     */
    public GradsCallistaSyncBatch(Id[] awardIds) {
        suppliedAwardIds = awardIds;
    }

    /**
     * Calculate minimum age in minutes based on retry attempt count using exponential backoff
     * @param retryAttempt Number of retry attempts
     * @return Minimum age in minutes before next retry
     */
    public static Integer calculateBackoffMinutes(Integer retryAttempt) {
        if(retryAttempt == null || retryAttempt == 0) {
            return 2; // small delay to avoid race condition on new requests
        }
        if(retryAttempt > 6) {
            return 2147483647; // no more retries after 6 (max int value)
        }
        // 60 minutes * 2^(retryAttempt)
        // e.g. 1 = 2h, 2 = 4h, 3 = 8h, 4 = 16h, 5 = 32h, 6 = 64h
        return 60 * Integer.valueOf(Math.pow(2, retryAttempt));
    }

    public Iterable<Id> start(Database.BatchableContext context) {

        Graduation_Award__c[] awards = new Graduation_Award__c[0];
        if(suppliedAwardIds != null) {
            for(Id awardId : suppliedAwardIds) {
                awards.add(new Graduation_Award__c(Id = awardId));
            }
        } else {
            // throw in SystemModstamp for performance since Writeback_Requested_Age_Minutes__c is a formula
            awards = [
                SELECT Writeback_Retry_Attempt__c, Writeback_Requested_Age_Minutes__c, Writeback_Apex_Job_Id__c
                FROM Graduation_Award__c
                WHERE Writeback_Requested_Age_Minutes__c > 0
                    AND SystemModstamp = LAST_N_DAYS:7
                    AND Graduation_Application__r.Status__c IN ('Applied', 'Cancelled')
                ORDER BY Callista_Writeback_Requested_Time__c ASC
                LIMIT 4000
            ];
            // filter awards based on exponential backoff
            List<Graduation_Award__c> eligibleAwards = new List<Graduation_Award__c>();
            for(Graduation_Award__c award : awards) {
                Decimal age = award.Writeback_Requested_Age_Minutes__c;

                if(String.isNotBlank(award.Writeback_Apex_Job_Id__c) && age < 30) {
                    continue; // Wait 30 minutes before assuming job id is stale
                }

                if(age >= calculateBackoffMinutes(Integer.valueOf(award.Writeback_Retry_Attempt__c))) {
                    eligibleAwards.add(award);
                }
            }
            awards = eligibleAwards;
        }

        for(Graduation_Award__c award : awards) {
            award.Writeback_Retry_Attempt__c = (award.Writeback_Retry_Attempt__c ?? 0) + 1; // cleared on success
            award.Writeback_Apex_Job_Id__c = context.getJobId();
        }
        update awards;

        return new List<Id>(new Map<Id,Graduation_Award__c>(awards).keySet());
    }

    public void execute(Database.BatchableContext context, Id[] awardIds) {
        Nebula.Logger.setAsyncContext(context);
        GradsCallistaSyncService.processAwards(new Set<Id>(awardIds), true);
    }

    public void finish(Database.BatchableContext context) {}

    public void execute(SchedulableContext context) {
        if(GradsUtils.getSyncConfig().scheduledBatchEnabled == true) {
            Database.executeBatch(new GradsCallistaSyncBatch(), GradsUtils.getSyncConfig().retryBatchSize);
        }
    }
}