force-app/main/default/objects/Graduation_Application__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Id__c</fullName>
        <description>External Id used by GCP</description>
        <externalId>true</externalId>
        <label>Integration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Pending_State_Expiry__c</fullName>
        <description>Once this has passed, Payment Pending State is considered stale</description>
        <label>Payment Pending State Expiry</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Payment_Pending_State__c</fullName>
        <description>Internal state tracking for GCP</description>
        <label>Payment Pending State</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Staff_Comments__c</fullName>
        <description>Comments from staff</description>
        <label>Staff Comments</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current state of Application</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Internal Draft</fullName>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Person_Id__c</fullName>
        <description>Contact&apos;s Student ID</description>
        <formula>Student__r.Person_ID_unique__c</formula>
        <label>Student Person Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Student contact associated with the Application</description>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Graduation Applications</relationshipLabel>
        <relationshipName>Graduation_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Graduation Application</label>
    <nameField>
        <displayFormat>GAPP-{0000000}</displayFormat>
        <label>Graduation Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduation Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Graduation_Award__c.object
<CustomObject>
    <fields>
        <fullName>Award_Code_1__c</fullName>
        <label>Award Code 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Code_2__c</fullName>
        <label>Award Code 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Course_Code__c</fullName>
        <label>Award Course Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Course_Title__c</fullName>
        <label>Award Course Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Course_Version__c</fullName>
        <label>Award Course Version</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Award_Title_1__c</fullName>
        <label>Award Title 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Title_2__c</fullName>
        <label>Award Title 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Type__c</fullName>
        <label>Award Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alternative Exit</fullName>
                </value>
                <value>
                    <fullName>Combined</fullName>
                </value>
                <value>
                    <fullName>Single</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bypass_Writeback_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, a platform event won&apos;t be fired when a watched field changes. Automatically cleared on writeback</description>
        <label>Bypass Writeback Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Callista_Transaction_Number__c</fullName>
        <description>Id returned by Callista once the application has been created</description>
        <label>Callista Transaction Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <description>Date the award was cancelled</description>
        <label>Cancellation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Cancellation_Succeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the cancellation request successfully posted to Callista</description>
        <label>Cancellation Succeeded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Course code for the Award</description>
        <label>Course Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Title__c</fullName>
        <description>Course title for the Award</description>
        <label>Course Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Version_Number__c</fullName>
        <description>Course version number for the Award</description>
        <label>Course Version Number</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Graduation_Application__c</fullName>
        <description>Parent Graduation Application</description>
        <label>Graduation Application</label>
        <referenceTo>Graduation_Application__c</referenceTo>
        <relationshipLabel>Graduation Awards</relationshipLabel>
        <relationshipName>Graduation_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Attendance_Fee_Waiver__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When true, this Award does not require payment</description>
        <label>Has Attendance Fee Waiver</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integration_Id__c</fullName>
        <description>External Id used by GCP</description>
        <externalId>true</externalId>
        <label>Integration Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Attending_Ceremony__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Student is attending this ceremony</description>
        <label>Is Attending Ceremony</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Receipt_Number_External_System__c</fullName>
        <description>Receipt number from payment in an external system</description>
        <label>Receipt Number (External System)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Comments__c</fullName>
        <description>Comments from staff</description>
        <label>Staff Comments</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Student_Person_Id__c</fullName>
        <description>Person Id from the student&apos;s contact record</description>
        <formula>Graduation_Application__r.Student__r.Person_ID_unique__c</formula>
        <label>Student Person Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Writeback_Requested_Age_Minutes__c</fullName>
        <description>Minutes since the last writeback was requested. Blank if no writeback is pending</description>
        <formula>IF(
  ISBLANK(Last_Callista_Writeback_Success_Time__c) || Callista_Writeback_Requested_Time__c &gt; Last_Callista_Writeback_Success_Time__c,
  (NOW() - Callista_Writeback_Requested_Time__c) * 1440,
  NULL
)</formula>
        <label>Writeback Requested Age (Minutes)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Graduation Award</label>
    <nameField>
        <displayFormat>GAWARD-{0000000}</displayFormat>
        <label>Graduation Award Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduation Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/GradsAwardFormController.cls
/**
 * @description Controller for the Graduation Award Form Lightning Web Component
 * @group       Grads
 * @revision    2024-11-12 - Tom Gangemi - Initial version
 *
 */
public with sharing class GradsAwardFormController {

    public class Application {
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public Boolean hasPaymentPendingState { get; set; }
        @AuraEnabled public String paymentPendingStateExpiry { get; set; }
    }

    /**
     * Award data class for passing back and forth between LWC and Apex
     */
    public class Award {
        @AuraEnabled public Id existingRecordId { get; set; }
        @AuraEnabled public String existingRecordName { get; set; }
        @AuraEnabled public Boolean isCurrentRecord { get; set; }
        @AuraEnabled public Boolean onlyExistsInCallista { get; set; }

        @AuraEnabled public String transactionNumber { get; set; }
        @AuraEnabled public String awardTypeIndicator { get; set; }
        @AuraEnabled public String courseCode { get; set; }
        @AuraEnabled public String awardCourseCode { get; set; }
        @AuraEnabled public Integer awardCourseVersionNumber { get; set; }
        @AuraEnabled public String awardCourseTitle { get; set; }
        @AuraEnabled public String awardCode1 { get; set; }
        @AuraEnabled public String awardTitle1 { get; set; }
        @AuraEnabled public String awardCode2 { get; set; }
        @AuraEnabled public String awardTitle2 { get; set; }
        @AuraEnabled public String receiptNumber { get; set; }
        @AuraEnabled public Boolean isCancelled { get; set; }

        @AuraEnabled public Integer courseVersionNumber { get; set; }
        @AuraEnabled public String courseTitle { get; set; }
        @AuraEnabled public Boolean hasFeeWaiver { get; set; }

        // Fields only used for input (new awards)
        @AuraEnabled public Boolean isAttendingCeremony { get; set; }
        @AuraEnabled public String staffComments { get; set; }

        public Award(GradsCallistaCalloutService.EligibilityGraduationAvailableSelection gas, GradsCallistaCalloutService.EligibilityCourseAttempt eca) {
            this.awardTypeIndicator = gas.awardDetails.awardTypeIndicator;
            this.courseCode = eca.courseCode;
            this.awardCourseCode = gas.awardDetails.awardCourseCode;
            this.awardCourseVersionNumber = gas.awardDetails.awardCourseVersionNumber;
            this.awardCourseTitle = gas.awardDetails.awardCourseTitle;
            this.awardCode1 = gas.awardDetails.awardCode1;
            this.awardTitle1 = gas.awardDetails.awardTitle1;
            this.awardCode2 = gas.awardDetails.awardCode2;
            this.awardTitle2 = gas.awardDetails.awardTitle2;
            this.courseVersionNumber = eca.courseVersionNumber;
            this.courseTitle = eca.courseTitle;
        }

        public Award(Graduation_Award__c record) {
            this.transactionNumber = record.Callista_Transaction_Number__c;
            this.awardTypeIndicator = GradsUtils.getCallistaAwardType(record.Award_Type__c);
            this.courseCode = record.Course_Code__c;
            this.awardCourseCode = record.Award_Course_Code__c;
            this.awardCourseVersionNumber = Integer.valueOf(record.Award_Course_Version__c);
            this.awardCourseTitle = record.Award_Course_Title__c;
            this.awardCode1 = record.Award_Code_1__c;
            this.awardTitle1 = record.Award_Title_1__c;
            this.awardCode2 = record.Award_Code_2__c;
            this.awardTitle2 = record.Award_Title_2__c;
            this.courseVersionNumber = Integer.valueOf(record.Course_Version_Number__c);
            this.courseTitle = record.Course_Title__c;
            this.receiptNumber = record.Receipt_Number_External_System__c;
            this.isCancelled = record.Cancellation_Date__c != null && (record.Cancellation_Succeeded__c || String.isBlank(record.Callista_Transaction_Number__c));
        }

        public Award() {}
    }

    /**
     * Container for all form data
     */
    public class AwardFormData {
        @AuraEnabled public Award[] awards;
        @AuraEnabled public Application application;
        @AuraEnabled public Map<String,String[]> courseWarnings = new Map<String,String[]>();
        @AuraEnabled public Award currentAward;
        @AuraEnabled public String personId;
        @AuraEnabled public String formType; // 'application' or 'award'
    }

    /**
     * Retrieves form data for either a Graduation Application or Award
     * @param recordOrStudentId The Id of the record or the Person ID of the student
     * @return AwardFormData containing awards and related information
     * @throws AuraHandledException if eligibility check fails
     */
    @AuraEnabled
    public static AwardFormData getFormData(String recordOrStudentId) {
        Id recordId;
        String personId;
        try {
            // if it is an Id, get the Person ID from the record
            recordId = (Id)recordOrStudentId;
            personId = getPersonId(recordId);
        } catch (Exception e) {
            // if it is not an Id, assume it is a Person ID
            personId = recordOrStudentId;
        }

        if(personId == null) throw new AuraHandledException('UniCRM data not found');

        String formType = recordId?.getSobjectType() == Graduation_Award__c.SObjectType ? 'award' : 'application';

        AwardFormData formData = getStudentsAwards(personId, recordId);
        formData.personId = personId;
        formData.formType = formType;

        if(recordId != null) {
            if(formType == 'application') {
                Graduation_Application__c app = [
                    SELECT Status__c, Payment_Pending_State__c, Payment_Pending_State_Expiry__c
                    FROM Graduation_Application__c WHERE Id = :recordId
                ];
                formData.application = new Application();
                formData.application.status = app.Status__c;
                formData.application.hasPaymentPendingState = String.isNotBlank(app.Payment_Pending_State__c) &&
                    (app.Payment_Pending_State_Expiry__c == null || app.Payment_Pending_State_Expiry__c > Datetime.now());
                formData.application.paymentPendingStateExpiry = app.Payment_Pending_State_Expiry__c?.format();
            } else {
                formData.application = new Application();
                formData.application.status = [
                    SELECT Graduation_Application__r.Status__c
                    FROM Graduation_Award__c WHERE Id = :recordId
                ].Graduation_Application__r.Status__c;
            }
        }

        return formData;
    }

    /**
     * Retrieves the Person ID of the student from a Graduation_Application__c or Graduation_Award__c
     */
    private static String getPersonId(Id recordId) {
        if (recordId.getSobjectType() == Graduation_Application__c.SObjectType) {
            return [
                SELECT Student_Person_Id__c FROM Graduation_Application__c WHERE Id = :recordId
            ]?.Student_Person_Id__c;
        } else if (recordId.getSobjectType() == Graduation_Award__c.SObjectType) {
            return [
                SELECT Graduation_Application__r.Student_Person_Id__c FROM Graduation_Award__c WHERE Id = :recordId
            ]?.Graduation_Application__r.Student_Person_Id__c;
        }
        throw new AuraHandledException('Invalid record sobject type');
    }

    private static String[] getCourseWarningText(GradsCallistaCalloutService.EligibilityCourseAttempt ca) {
        String[] warnings = new String[0];
        if(ca.meetCPRequirement == 'N') {
            warnings.add('Credit point requirement not met');
        }
        if(ca.meetCourseStatusRequirement == 'N') {
            warnings.add('Course status requirement not met');
        }
        if(ca.graduateStudentIndicator == 'N') {
            warnings.add('Student not eligible to graduate');
        }
        if(ca.graduateModuleEnabled == 'N') {
            warnings.add('Graduate module not enabled');
        }
        return warnings;
    }

    /**
     * Retrieves awards for student from CRM and Eligibility API
     * @param personId The Person ID of the student
     * @param awardId The Id of the award to highlight
     * @return AwardFormData
     */
    private static AwardFormData getStudentsAwards(String personId, Id awardId) {
        if (personId == null) return null;

        AwardFormData formData = new AwardFormData();
        formData.awards = new List<Award>();

        // Get awards from CRM - Create a key for each award to match with Eligibility API data
        Map<String, Graduation_Award__c> awardsByKey = new Map<String, Graduation_Award__c>();
        for (Graduation_Award__c ga : [
            SELECT Name, Course_Code__c, Course_Title__c, Award_Type__c, Award_Course_Code__c,
                Course_Version_Number__c, Award_Course_Version__c, Award_Course_Title__c,
                Award_Code_1__c, Award_Title_1__c, Award_Code_2__c, Award_Title_2__c,
                Callista_Transaction_Number__c, Receipt_Number_External_System__c,
                Cancellation_Date__c, Cancellation_Succeeded__c
            FROM Graduation_Award__c
            WHERE Graduation_Application__r.Student__r.Person_ID_unique__c = :personId AND Cancellation_Date__c = NULL
        ]) {
            awardsByKey.put(
                createAwardKey(ga.Course_Code__c, ga.Award_Course_Code__c, ga.Award_Code_1__c, ga.Award_Code_2__c),
                ga
            );

            if(awardId != null && ga.Id == awardId) {
                formData.currentAward = new Award(ga);
            }
        }

        // Get awards from Eligibility API
        GradsCallistaCalloutService.EligibilityCalloutResult eligibility = GradsCallistaCalloutService.getEligibility(personId);
        if (!eligibility.success) {
            if (eligibility.ex != null) {
                throw eligibility.ex;
            }
            throw new AuraHandledException('Eligibility API error: ' + eligibility.errorMessage);
        }

        if(eligibility.eligibilityDetails == null || eligibility.eligibilityDetails.courseAttempts == null) {
            throw new AuraHandledException('No course attempts found');
        }

        // Create return data from mix of Existing Awards and Eligibility API data
        for (GradsCallistaCalloutService.EligibilityCourseAttempt ca : eligibility.eligibilityDetails.courseAttempts) {
            if (ca.graduationAvailableSelections == null) continue;

            String[] warnings = getCourseWarningText(ca);
            if(warnings.size() > 0) {
                formData.courseWarnings.put(ca.courseCode, warnings);
            }

            // Create a lookup of existing applications from the Eligibility API data
            Map<String,String> callistaExistingAppsByAwardKey = new Map<String,String>();
            if(ca.graduationApplications != null) {
                for (GradsCallistaCalloutService.EligibilityGraduationApplication ga : ca.graduationApplications) {
                    GradsCallistaCalloutService.EligibilityAppAward aa = ga.awardDetails;
                    callistaExistingAppsByAwardKey.put(
                        createAwardKey(ca.courseCode, aa.awardCourseCode1, aa.awardCode1, aa.awardCode2),
                        ga.transactionNo
                    );
                }
            }

            for (GradsCallistaCalloutService.EligibilityGraduationAvailableSelection gas : ca.graduationAvailableSelections) {
                // For each available award from Eligibility API
                Award award = new Award(gas, ca);

                String key = createAwardKey(award.courseCode, award.awardCourseCode, award.awardCode1, award.awardCode2);
                Graduation_Award__c existingCrmAward = awardsByKey.get(key);

                if (existingCrmAward != null) {
                    award.existingRecordName = existingCrmAward.Name;
                    award.existingRecordId = existingCrmAward.Id;
                    award.isCurrentRecord = existingCrmAward.Id == awardId;
                    award.onlyExistsInCallista = false;
                } else {
                    award.transactionNumber = callistaExistingAppsByAwardKey.get(key);
                    award.onlyExistsInCallista = String.isNotBlank(award.transactionNumber);
                }

                formData.awards.add(award);
            }
        }

        return formData;
    }

    /**
     * Updates an award record
     * @param awardId The Id of the award to update
     * @param award The updated award data
     */
    @AuraEnabled
    public static void updateAward(Id awardId, Award award, Boolean clearTransactionNumber) {
        Graduation_Award__c existingAward = [
            SELECT Cancellation_Date__c, Cancellation_Succeeded__c,
                Writeback_Requested_Age_Minutes__c, Graduation_Application__c,
                Callista_Transaction_Number__c
            FROM Graduation_Award__c WHERE Id = :awardId
        ];
        String errorMessage = null;
        if(existingAward.Callista_Transaction_Number__c != null) {
            if(existingAward.Cancellation_Date__c != null && !existingAward.Cancellation_Succeeded__c) {
                errorMessage = 'Cannot update award that is pending cancellation';
            }
            else if(existingAward.Writeback_Requested_Age_Minutes__c != null) {
                errorMessage = 'Cannot update award that is pending writeback';
            }
        }
        if(errorMessage != null) {
            AuraHandledException ex = new AuraHandledException(errorMessage);
            ex.setMessage(errorMessage);
            throw ex;
        }

        Graduation_Award__c updatedAward = new Graduation_Award__c(
            Id = awardId,
            Course_Code__c = award.courseCode,
            Course_Version_Number__c = award.courseVersionNumber,
            Course_Title__c = award.courseTitle,
            Award_Type__c = GradsUtils.getCrmAwardType(award.awardTypeIndicator),
            Award_Course_Code__c = award.awardCourseCode,
            Award_Course_Version__c = award.awardCourseVersionNumber,
            Award_Course_Title__c = award.awardCourseTitle,
            Award_Code_1__c = award.awardCode1,
            Award_Title_1__c = award.awardTitle1,
            Award_Code_2__c = award.awardCode2,
            Award_Title_2__c = award.awardTitle2,
            Cancellation_Date__c = null,
            Cancellation_Succeeded__c = false
        );

        if(clearTransactionNumber) {
            // For creating new app after cancellation
            updatedAward.Callista_Transaction_Number__c = null;
        }
        if(String.isNotBlank(award.transactionNumber)) {
            // For selecting an award that already exists in Callista
            updatedAward.Callista_Transaction_Number__c = award.transactionNumber;
        }

        updatedAward.Integration_Id__c = GradsUtils.createAwardIntegrationId(
            updatedAward,
            existingAward.Graduation_Application__c
        );
        update updatedAward;
    }

    /**
     * Creates new awards for a Graduation Application
     * @param applicationId The Id of the Graduation_Application__c record
     * @param awards List of awards to create
     * @return List of created award Ids
     */
    @AuraEnabled
    public static List<Id> createAwards(Id applicationId, List<Award> awards) {
        List<Graduation_Award__c> newAwards = new List<Graduation_Award__c>();

        for(Award award : awards) {
            Graduation_Award__c newAward = new Graduation_Award__c(
                Graduation_Application__c = applicationId,
                Course_Code__c = award.courseCode,
                Award_Type__c = GradsUtils.getCrmAwardType(award.awardTypeIndicator),
                Award_Course_Code__c = award.awardCourseCode,
                Award_Course_Version__c = award.awardCourseVersionNumber,
                Award_Course_Title__c = award.awardCourseTitle,
                Award_Code_1__c = award.awardCode1,
                Award_Title_1__c = award.awardTitle1,
                Award_Code_2__c = award.awardCode2,
                Award_Title_2__c = award.awardTitle2,
                Is_Attending_Ceremony__c = award.isAttendingCeremony,
                Receipt_Number_External_System__c = award.receiptNumber,
                Staff_Comments__c = award.staffComments,
                Course_Title__c = award.courseTitle,
                Course_Version_Number__c = award.courseVersionNumber,
                Has_Attendance_Fee_Waiver__c = award.hasFeeWaiver ?? false,
                Callista_Transaction_Number__c = award.transactionNumber
            );
            newAward.Integration_Id__c = GradsUtils.createAwardIntegrationId(newAward, applicationId);
            newAwards.add(newAward);
        }

        insert newAwards;
        return new List<Id>(new Map<Id,SObject>(newAwards).keySet());
    }


    public static String createAwardKey(String courseCode, String awardCourseCode, String awardCode1, String awardCode2) {
        return courseCode + '-' + awardCourseCode + '-' + awardCode1 + '-' + (awardCode2 ?? '');
    }

    @AuraEnabled
    public static void cancelAward(Id awardId) {
        update new Graduation_Award__c(
            Id = awardId, Cancellation_Date__c = Datetime.now(), Bypass_Writeback_Trigger__c = true
        );
    }

}