force-app/main/default/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Areas_of_Interest__c</fullName>
        <label>Areas of Interest</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Art and Design</fullName>
                </value>
                <value>
                    <fullName>Business and Economy</fullName>
                </value>
                <value>
                    <fullName>Career Development and Planning Opportunities</fullName>
                </value>
                <value>
                    <fullName>Culture, Recreation and Sport</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Engineering and Science</fullName>
                </value>
                <value>
                    <fullName>Entrepreneurship, Start Ups &amp; Innovation</fullName>
                </value>
                <value>
                    <fullName>Indigenous Communities and Culture</fullName>
                </value>
                <value>
                    <fullName>Law, Politics and Society</fullName>
                </value>
                <value>
                    <fullName>Medicine and Health (includes Mental Health and Aging)</fullName>
                </value>
                <value>
                    <fullName>Sustainable Development and Environment</fullName>
                </value>
                <value>
                    <fullName>Technology, AI &amp; Data Science</fullName>
                </value>
                <value>
                    <fullName>Women&apos;s Rights</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Associated_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Event</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Body_Content__c</fullName>
        <inlineHelpText>The body text or description to display</inlineHelpText>
        <label>Body Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employment Services</fullName>
                </value>
                <value>
                    <fullName>Recruitment Services</fullName>
                </value>
                <value>
                    <fullName>Talent To Solve Business Problems</fullName>
                </value>
                <value>
                    <fullName>Get A Fresh Perspective</fullName>
                </value>
                <value>
                    <fullName>Home Header - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Header - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Header - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Header - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Home Top Left - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Top Left - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Top Left - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Top Left - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Left - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Left - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Left - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Left - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Right - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Right - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Right - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Right - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Get Involved Header - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Header - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Header - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Header - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Get Involved Feature - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Feature - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Feature - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Feature - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Events Header - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Events Header - Established Alumni</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_URL__c</fullName>
        <label>Event URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Header_Content__c</fullName>
        <inlineHelpText>Title or Header text to show at the top of the listing</inlineHelpText>
        <label>Header Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Header_Image_from_URL__c</fullName>
        <inlineHelpText>The URL of the image to be displayed</inlineHelpText>
        <label>Header Image from URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Header_Video_URL__c</fullName>
        <inlineHelpText>Enter embed video link here to display embed video on community.</inlineHelpText>
        <label>Header Video URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Online_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Online Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_URL__c</fullName>
        <inlineHelpText>Destination for &apos;Find out more&apos; button on some pages (e.g. Careers &amp; Skills)</inlineHelpText>
        <label>Title URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Event type brought over from campaign</description>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c.object
<CustomObject>
    <description>Store states information. Source: shop.monash</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country_Attribute__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/URLs__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>A generic hierarchy custom setting to house URLs for any need.</description>
    <fields>
        <fullName>Login_Anyone_SSO_ACS_URL__c</fullName>
        <description>ACS URL used for Alumni portal library access</description>
        <inlineHelpText>ACS URL used for Alumni portal library access</inlineHelpText>
        <label>Login Anyone SSO ACS URL</label>
        <type>Url</type>
    </fields>
    <label>URLs</label>
</CustomObject>

force-app/main/default/classes/PORTAL_UCIN_ListingController.cls
/**
 * @author Sulung Chandra, UC Innovation
 * @date 8/28/2019
 * @group PORTAL_UCIN
 * @group-content 
 * @description Controller for PORTAL_UCIN Listing components
 */
public without sharing class PORTAL_UCIN_ListingController {
    
    
    public class MyEventWrapper {
        @AuraEnabled
        public Listing__c eventDetails{ get; set; }
        @AuraEnabled
        public String status{ get; set; }

        public MyEventWrapper(Listing__c eventDetails, String status) {
            this.eventDetails = eventDetails;
            this.status = status;
        }
    }
    
        /**
    * Retrieve a list of Listing given a record type, a Category, 
    * sorting criteria and the maximum number of records to be returned
    *
    * @param: recordTypeDeveloperName       The record type of the listing being searched for
    * @param: category                      The Category of the listing being searched for
    * @param: maxNumberOfRecords            The maximum number of Listings to be returned
    */
    @AuraEnabled
    public static List<Listing__c> getListings(String recordTypeDeveloperName, String category, Integer maxNumberOfRecords) {
        List<Listing__c> listingList = new List<Listing__c>();
        List<String> SelectList = new List<String>();
        List<String> wheresList = new List<String>();
        String query = '';
        String orderByString = 'LastModifiedDate Desc';
        
        SelectList.add('Id');
        SelectList.add('Name');
        SelectList.add('Title_URL__c');
        SelectList.add('Header_Content__c');
        SelectList.add('Header_Image_from_URL__c');
        SelectList.add('Header_Video_URL__c');
        SelectList.add('Category__c');
        SelectList.add('Body_Content__c');
        
        wheresList.add('RecordType.DeveloperName=:recordTypeDeveloperName');
        wheresList.add('Category__c=:category');
        
        query = 'Select ' + String.join(SelectList, ',') + ' From Listing__c Where ' + String.join(wheresList, ' And ') + ' Order By ' + orderByString + ' Limit :maxNumberOfRecords';
        
        listingList = Database.query(query);
        
        for(Listing__c li : listingList) {
            li.Header_Content__c = PORTAL_UCIN_Utils.replaceSelectedText(li.Header_Content__c);
            li.Body_Content__c = PORTAL_UCIN_Utils.replaceSelectedText(li.Body_Content__c);
        }
        
        return listingList;
    }


        /**
    * Retrieve a map of Listing given a record type, a list of keys/Categories, 
    * and the maximum number of records to be returned
    *
    * @param: recordTypeAPIName     The record type of the listings being searched for
    * @param: keys                  A list of comma seperated categories which are also used as keys in the return map
    * @param: maxRecords            The maximum number of Listings to be returned
    */
    @AuraEnabled
    public static Map<String, Listing__c> getListingMap(String recordTypeAPIName, String keys, Integer maxRecords) {
        Map<String, Listing__c> listingMap = new Map<String, Listing__c>();
        List<Listing__c> listings = new List<Listing__c>();
        List<String> keyList = new List<String>();
        String query = '';
        keyList = keys.split(',');
        query = 'SELECT Name, Header_Content__c, Header_Image_from_URL__c, Header_Video_URL__C, Body_Content__c, Category__c FROM Listing__c WHERE ' + 
            'RecordType.DeveloperName=:recordTypeAPIName AND Category__c IN :keyList Order By LastModifiedDate Desc LIMIT :maxRecords';
        
        listings = Database.query(query);

        //Remove extraneous tags added in Rich text and the resulting Listing to the return map associated with appropriate category
        for(Listing__c listing : listings) {
            for(Integer i = 0; i < keyList.size(); i++) {
                if(!listingMap.containsKey(keyList.get(i)) && listing.Category__c.equals(keyList.get(i))) {
                    listing.Header_Content__c = PORTAL_UCIN_Utils.replaceSelectedText(listing.Header_Content__c);
                    listing.Body_Content__c = PORTAL_UCIN_Utils.replaceSelectedText(listing.Body_Content__c);
                    listingMap.put(keyList.get(i), listing);
                    break;
                }
            }
        }
        return listingMap;
    }
    
    /**
    * Retrieve a list of event Listings given the record type and the maximum number to display
    *
    * @param: recordTypeAPIName       		The record type of the listing being searched for
    * @param: maxRecords            The maximum number of Listings to be returned
    */
    @AuraEnabled
    public static List<Listing__c> getEventList(String recordTypeAPIName, Integer maxRecords) {
        List<Listing__c> listings = new List<Listing__c>();
        List<String> areasOfInterest;
        DateTime dtTwoHours = System.now().addHours(2);
        String query = '';

        Id contactId = getContactId();
        areasOfInterest = getAreasOfInterest(contactId);
               

        query = 'SELECT Name, Header_Content__c, Header_Image_from_URL__c, Header_Video_URL__C, Body_Content__c, ' + 
            	'City__c, Country__c, Postal_Code__c, State__c, Street__c, Areas_of_Interest__c, Online_Event__c, ' +
            	'Start_Date_Time__c, End_Date_Time__c, Event_URL__c, Type__c FROM Listing__c WHERE ' + 
            'RecordType.DeveloperName=:recordTypeAPIName AND (End_Date_Time__c > :dtTwoHours OR End_Date_Time__c = null) Order By Start_Date_Time__c Asc LIMIT :maxRecords';
        
        listings = Database.query(query);
		
        
        return organizeListings(listings, areasOfInterest);
    }

    /**
    * Retrieve a list of event Listings and their status for a user given the record type and the maximum number to display
    *
    * @param: recordTypeAPIName       		The record type of the listing being searched for
    * @param: maxRecords            The maximum number of Listings to be returned
    */
    @AuraEnabled
    public static List<MyEventWrapper> getMyEventList(String recordTypeAPIName, Integer maxRecords) {
        List<CampaignMember> campaignMemberList = new List<CampaignMember>();
         List<String> areasOfInterest;
        List<MyEventWrapper> returnList = new List<MyEventWrapper>();
        List<Id> eventIds = new List<Id>();
        DateTime dtTwoHours = System.now().addHours(2);
        
        Id contactId = getContactId();        
        if(contactId == null) {
            return null;
        }
        areasOfInterest = getAreasOfInterest(contactId);

        //Retrieve the list of events a user has signed up for
        campaignMemberList = [SELECT id, Contact.Name, Campaign.Parent_ERDA_Event__r.Name, Campaign.Parent_ERDA_Event__r.Id, Status 
                    FROM CampaignMember
                    WHERE Status IN ('Confirmed', 'Unconfirmed', 'CheckedIn') AND ContactId = :contactId];
        for(CampaignMember mem : campaignMemberList) {
            eventIds.add(mem.Campaign.Parent_ERDA_Event__r.Id);
        }
        //Retrieve the listings for the Events the user has signed up for


        List<Listing__c> beforeToday = new List<Listing__c>();
        List<Listing__c> afterToday = new List<Listing__c>();
        Boolean isBefore = true;
        for(Listing__c evnt : [SELECT Id, Name, Body_Content__c, City__c, Country__c, State__c, Street__c, Areas_of_Interest__c, 
                                     Online_Event__c, Start_Date_Time__c, End_Date_Time__c, Associated_Event__c, Event_URL__c, Type__c
                                     FROM Listing__c 
                                     WHERE Associated_Event__c IN :eventIds ORDER BY Start_Date_Time__c Asc]) {
            if(isBefore && (evnt.End_Date_Time__c < dtTwoHours)) {
                beforeToday.add(evnt);
            } else {
                isBefore = false;
                afterToday.add(evnt);
            }
        }  
        List<Listing__c> tempList = organizeListings(beforeToday, areasOfInterest);
        tempList.addAll(organizeListings(afterToday, areasOfInterest));


        //listings = organizeListings(listings, areasOfInterest);
        //Construct the list of Event Listings and associated user status to be returned
        for(Listing__c lis : tempList) {
            for(CampaignMember m : campaignMemberList) {
                if(m.Campaign.Parent_ERDA_Event__r.Id == lis.Associated_Event__c) {
                    MyEventWrapper eventToAdd = new MyEventWrapper(lis, m.Status);
                    returnList.add(eventToAdd);
                    break;
                }
            }
        }
        
        return returnList;
    }
    
    /**
    * Search for a list of events based on areas of interest being searched for
    *
    * @param: searchTerms       		The areas of interest being searched for 
    */
    @AuraEnabled
    public static List<Listing__c> SERVER_searchEvents(String searchTerms){
        List<Listing__c> returnList = new List<Listing__c>();
        DateTime dtTwoHours = System.now().addHours(2);
        Set<String> aoiToQuerySet = new Set<String>();
        Set<String> namestoQuerySet = new Set<String>();

        //seperate the search string into a list of individual words to search for
        searchTerms = searchTerms.replaceAll(',', '');
        searchTerms = String.escapeSingleQuotes(searchTerms);
        searchTerms = searchTerms.toLowerCase();
        String[] splitTerms = searchTerms.split(' ');

        List<Schema.PicklistEntry> pleList = Contact.Volunteer_Areas_of_Interest__c.getDescribe().getPicklistValues();

        for (string searchTerm: splitTerms) {
            // for each search term, look for all applying picklist entries that match and add to set of AOIs to query for
            for(Schema.PicklistEntry picklistEntry : pleList) {
                if(picklistEntry.getLabel().toLowerCase().contains(searchTerm)) {
                    aoiToQuerySet.add('\'' + picklistEntry.getLabel() + '\'');
                }
            }

            // For each search term, search for name to match it
            namestoQuerySet.add('%' + searchTerm + '%');
        }

        String whereClause = 'RecordType.DeveloperName=\'Event\' AND (End_Date_Time__c >  :dtTwoHours  OR End_Date_Time__c = null) AND ';

        whereClause += '(Name LIKE: namesToQuerySet';
        if (!aoiToQuerySet.isEmpty()) {
            whereClause += ' OR Areas_of_Interest__c includes (' + String.Join(new List<String>(aoiToQuerySet), ',') + ')';
        }
        whereClause += ')';

        system.debug('whereclause' + whereClause);
        
        String eventListingQuery = 'SELECT Id, Name, Body_Content__c, City__c, Country__c, State__c, Street__c, Areas_of_Interest__c, '
                        + 'Online_Event__c, Start_Date_Time__c, End_Date_Time__c, Associated_Event__c, Event_URL__c , Type__c '
                        + 'FROM Listing__c WHERE '
                        + whereClause
                        + ' ORDER BY Start_Date_Time__c Asc LIMIT 999';
        returnList = Database.query(eventListingQuery);

        Id contactId = getContactId();

        return organizeListings(returnList, getAreasOfInterest(contactId));
    }

    /**
    * Retrieve map of event types to the picture associated to the type.
    * Assumption is that all files will live under a listing of name 'Event Pictures'
    * Name of the picture must be equal to the type of event
    *
    * @return: Map of event type string to content version id
    */
    @AuraEnabled
    public static Map<String, ID> SERVER_searchEventPicture(){
        Map<String, ID> eventTypeToContentVersionIDMap = new Map<String, ID>();

        List<Listing__c> eventPictureListing = [SELECT ID FROM Listing__c WHERE name = 'Event Pictures' LIMIT 1];

        if (!eventPictureListing.isEmpty()) {
            // Get all files linked to this specific listing
            List<ContentDocumentLink> cdlList = [SELECT ID, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =:eventPictureListing[0].Id];
            Set<Id> contentDocumentIdSet = new Set<Id>();

            for (ContentDocumentLink eachLink: cdlList) {
                contentDocumentIdSet.add(eachLink.ContentDocumentId);
            }

            // Get all of the latest content versions for each file
            List<ContentVersion> cvList = [SELECT ID, ContentDocument.Title FROM ContentVersion WHERE ContentDocumentID IN: contentDocumentIDSet AND IsLatest = true];

            // Construct map of file record's title to ID of latest version
            for (ContentVersion eachCV: cvList) {
                eventTypeToContentVersionIDMap.put(eachCV.ContentDocument.Title, eachCV.ID);
            }
        }

        // Will return empty map if there are no listings
        return eventTypeToContentVersionIDMap;
    }

    @AuraEnabled
    public static String SERVER_getBaseUrl () {
        return PORTAL_CommunityUtils.getBaseUrl();
    } 

    /**
    * Retrieve the ACS URL stored in the URLs custom setting
    *
    * @return: String - ACS URL stored in the URLs custom setting
    */
    @AuraEnabled
    public static String getACSURL () {
        return URLs__c.getOrgDefaults().Login_Anyone_SSO_ACS_URL__c;
    } 

    private static List<Listing__c> organizeListings(List<Listing__c> listings, List<String> areasOfInterest) {
        List<Listing__c> noAreaOfInterestListings = new List<Listing__c>();
        List<Listing__c> returnList = new List<Listing__c>();
        Map<String, List<Listing__c>> areaOfInterestToListingListMap = new Map<String, List<Listing__c>>();
        for(Listing__c listing : listings) {
            listing.Body_Content__c = PORTAL_UCIN_Utils.replaceSelectedText(listing.Body_Content__c);
        }

        if(areasOfInterest == null) {
            return listings;
        }

        for(String area : areasOfInterest) {
            areaOfInterestToListingListMap.put(area, new List<Listing__c>());
        }     

        for(Listing__c listing : listings) {
            Boolean isAreaOfInterestFound = false;
            for(String area : areasOfInterest) {
                if(listing.Areas_of_Interest__c != null && listing.Areas_of_Interest__c.contains(area)){
                    areaOfInterestToListingListMap.get(area).add(listing);
                    isAreaOfInterestFound = true;
                    break;
                }
            }
            if(!isAreaOfInterestFound) {
                noAreaOfInterestListings.add(listing);
            }
        }

        for(String area : areasOfInterest) {
            returnList.addAll(areaOfInterestToListingListMap.get(area));
        }
        returnList.addAll(noAreaOfInterestListings);
        return returnList;
    }

    private static List<String> getAreasOfInterest(Id contactId) {
        List<String> areasOfInterest;
        if(contactId != null) {
            Contact cont = [SELECT Id, Volunteer_Areas_of_Interest__c FROM Contact WHERE Id = :contactId];
            if(cont.Volunteer_Areas_of_Interest__c != null) {
                areasOfInterest = cont.Volunteer_Areas_of_Interest__c.split(';');
            }
        }
        return areasOfInterest;

    }

    private static Id getContactId() {
        Id userId = UserInfo.getUserId();
        
        User usr = [SELECT Id,
                    ContactId, 
                    Name
                    FROM User
                    WHERE Id = :userId];
        
        return usr.ContactId; 
    }
}