force-app/main/default/objects/List_of_Values__c.object
<CustomObject>
    <description>Generic container for Callista Reference Data

When querying, check active flags and record type for records relevant to the usage.</description>
    <fields>
        <fullName>Category_Level_1__c</fullName>
        <label>Category Level 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Level_2__c</fullName>
        <label>Category Level 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enquiry_Type__c</fullName>
        <label>Enquiry Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Code_Description__c</fullName>
        <description>Description of the system code value</description>
        <label>System Code Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Code__c</fullName>
        <description>Field to describe Main Category</description>
        <label>System Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>A record type for each list of values

Lookups to this table should filter on type, as well as the active flag</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change Of Residency Faculty Name</fullName>
                </value>
                <value>
                    <fullName>Change Of Residency Visa Subclass</fullName>
                </value>
                <value>
                    <fullName>ADM_CNDTNL_OFFER_STATUS</fullName>
                    <label>Conditional Offer Response</label>
                </value>
                <value>
                    <fullName>ADM_DOC_STATUS</fullName>
                    <label>Documentation</label>
                </value>
                <value>
                    <fullName>ADM_ENTRY_QUAL_STATUS</fullName>
                    <label>Entry Qualification</label>
                </value>
                <value>
                    <fullName>ADM_OFFER_RESP_STATUS</fullName>
                    <label>Offer Response</label>
                </value>
                <value>
                    <fullName>ADM_OFFER_DFRMNT_STATUS</fullName>
                    <label>Offer Deferment</label>
                </value>
                <value>
                    <fullName>ADM_OUTCOME_STATUS</fullName>
                    <label>Outcome</label>
                </value>
                <value>
                    <fullName>Intermission Reason</fullName>
                </value>
                <value>
                    <fullName>SS_DiscontinuationReason</fullName>
                    <label>Discontinuation Reason</label>
                </value>
                <value>
                    <fullName>CaseCategorisation</fullName>
                    <default>true</default>
                    <label>CaseCategorisation</label>
                </value>
                <value>
                    <fullName>Reason for COE</fullName>
                </value>
                <value>
                    <fullName>Student Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <description>Non user field
Combination of Value and System Code to allow upserts</description>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value supplied to Callista via the integrations

Unique within a type</description>
        <label>Value</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/LOV_AS_UpdateFields_FT.cls
/**
 * @author          Matthew Maramot
 * @description     Test class for List_of_Values_AS_Update_Fields flow
 * @revision
 * 	2025-05-06 - Matthew Maramot - Created class
 */
    
@isTest(isParallel=true)
public with sharing class LOV_AS_UpdateFields_FT {
    //Standard
    static final string value = 'SATISFIED';
    static final string sysCode = 'COND-OFFER';
    static final string type = 'ADM_OUTCOME_STATUS';

    //CaseCategorisation
    static final string enqType = 'Future Course Test';
    static final string catOne = 'Supervisor Accreditation Test' ;
    static final string catTwo = 'Other Test';
    static final string typeCase = 'CaseCategorisation';
    
    /*******************************************************************************
     * @author       Matthew Maramot
     * @date         06.May.2025
     * @description  Test that name and unique key are correctly set when inserting List of Values record
    *******************************************************************************/
	@isTest 
    static void lovInsert() {
        //GIVEN: We have new LOV records
        List<List_of_Values__c> lovList = new List<List_of_Values__c>{
        new List_of_Values__c(
            Unique_Key__c = 'OFFER-G-CO',
            Value__c = value,
            System_Code__c = sysCode,
            Name = 'TESTNAME',
            Type__c = type),
            
        new List_of_Values__c(
                Unique_Key__c = 'FutureCourse',
                Value__c = value,
                System_Code__c = sysCode,
                Name = 'TESTNAME',
                Type__c = typeCase,
                Enquiry_Type__c = enqType,
                Category_Level_1__c = catOne,
                Category_Level_2__c = catTwo
        )};

        //WHEN: It is inserted
        Test.startTest();
        insert lovList;
        Test.stopTest();

        //THEN: Name and Unique Key should be properly formatted;
        List_Of_Values__c lovStandard = [SELECT Name, Unique_Key__c FROM List_Of_Values__c WHERE Type__c =: type LIMIT 1];
        String expectedName = value + ' (' + sysCode + ')';
        String expectedKey =  value + '-' + type;
        Assert.areEqual(lovStandard.Name, expectedName, 'LOV Name did not get properly set');
        Assert.areEqual(lovStandard.Unique_Key__c, expectedKey, 'LOV Unique Key did not get properly set');

        List_Of_Values__c lovCC = [SELECT Name, Unique_Key__c FROM List_Of_Values__c WHERE Type__c =: typeCase LIMIT 1];
        String expectedCaseName =  catOne + '>' + catTwo;
        String expectedCaseKey =  enqType + '-' + catOne + '-' + catTwo;
        Assert.areEqual(lovCC.Name, expectedCaseName, 'CaseCategorisation LOV Name did not get properly set');
        Assert.areEqual(lovCC.Unique_Key__c, expectedCaseKey, 'CaseCategorisation LOV Unique Key did not get properly set');
    }

    /*******************************************************************************
     * @author       Matthew Maramot
     * @date         06.May.2025
     * @description  Test that name and unique key are correctly set when updating List of Values record
    *******************************************************************************/
	@isTest 
    static void lovUpdate() {
        //GIVEN: We have existing LOV records
        List<List_of_Values__c> lovList = new List<List_of_Values__c>{
            new List_of_Values__c(
            Unique_Key__c = 'OFFER-G-CO',
            Value__c = 'DOC-ENROL',
            System_Code__c = 'SATISFIED',
            Name = 'TESTNAME',
            Type__c = type
            ),
                
            new List_of_Values__c(
                    Unique_Key__c = 'Current Course',
                    Value__c = 'MGRO00523',
                    System_Code__c = 'MGRO00523',
                    Name = 'TESTNAME',
                    Type__c = typeCase,
                    Enquiry_Type__c = 'Current Course',
                    Category_Level_1__c = 'MGE Admissions',
                    Category_Level_2__c = 'Other',
                    System_Code_Description__c = 'testDescription'
        )};
        insert lovList;

        //WHEN: they are updated
        List<List_of_Values__c> updateLOVList = new List<List_of_Values__c>();

        List_Of_Values__c lovUpdate = [SELECT Value__c, System_Code__c, Type__c  FROM List_Of_Values__c WHERE Type__c =: type LIMIT 1];
        lovUpdate.value__c = value;
        lovUpdate.system_Code__c = sysCode;
        updateLOVList.add(lovUpdate);

        List_Of_Values__c lovCCUpdate = [SELECT System_Code_Description__c, Enquiry_Type__c, Category_Level_1__c, Category_Level_2__c  FROM List_Of_Values__c WHERE Type__c =: typeCase LIMIT 1];
        lovCCUpdate.System_Code_Description__c = 'updatedDescription';
        lovCCUpdate.Enquiry_Type__c = enqType;
        lovCCUpdate.Category_Level_1__c = catOne;
        lovCCUpdate.Category_Level_2__c = catTwo;
        updateLOVList.add(lovCCUpdate);

        Test.startTest();
        update updateLOVList;
        Test.stopTest();

        //THEN: Name and Unique Key should be properly formatted;
        String expectedName = value + ' (' + sysCode + ')';
        String expectedKey =  value + '-' + type;
        List_Of_Values__c lovStandard = [SELECT Name, Unique_Key__c FROM List_Of_Values__c WHERE Type__c =: type LIMIT 1];
        Assert.areEqual(lovStandard.Name, expectedName, 'LOV Name did not get properly set');
        Assert.areEqual(lovStandard.Unique_Key__c, expectedKey, 'LOV Unique Key did not get properly set');

        List_Of_Values__c lovCC = [SELECT Name, Unique_Key__c FROM List_Of_Values__c WHERE Type__c =: typeCase LIMIT 1];
        String expectedCaseName =  catOne + '>' + catTwo;
        String expectedCaseKey =  enqType + '-' + catOne + '-' + catTwo;
        Assert.areEqual(lovCC.Name, expectedCaseName, 'CaseCategorisation LOV Name did not get properly set');
        Assert.areEqual(lovCC.Unique_Key__c, expectedCaseKey, 'CaseCategorisation LOV Unique Key did not get properly set');
    }
}