force-app/main/default/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Employment Services</fullName>
                </value>
                <value>
                    <fullName>Recruitment Services</fullName>
                </value>
                <value>
                    <fullName>Talent To Solve Business Problems</fullName>
                </value>
                <value>
                    <fullName>Get A Fresh Perspective</fullName>
                </value>
                <value>
                    <fullName>Home Header - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Header - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Header - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Header - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Home Top Left - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Top Left - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Top Left - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Top Left - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Left - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Left - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Left - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Left - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Right - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Right - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Right - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Home Bottom Right - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Get Involved Header - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Header - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Header - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Header - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Get Involved Feature - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Feature - Established Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Feature - Career Peak Alumni</fullName>
                </value>
                <value>
                    <fullName>Get Involved Feature - Planning or Enjoying Retirement</fullName>
                </value>
                <value>
                    <fullName>Events Header - New Alumni</fullName>
                </value>
                <value>
                    <fullName>Events Header - Established Alumni</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PORTAL_UCIN_ListingCategoryPickList.cls
/**
 * @author Sulung Chandra, UC Innovation
 * @date 8/29/2019
 * @group PORTAL_UCIN
 * @group-content 
 * @description Dynamic picklist values for Listing__c.Category__c
 */
global class PORTAL_UCIN_ListingCategoryPickList extends VisualEditor.DynamicPickList {
    global override VisualEditor.DataRow getDefaultValue() {
        VisualEditor.DataRow dv = new VisualEditor.DataRow('', '');
        return dv;
    }
    
    global override VisualEditor.DynamicPickListRows getValues() {
        VisualEditor.DynamicPickListRows values = new VisualEditor.DynamicPickListRows();
        Schema.DescribeFieldResult fr = Listing__c.Category__c.getDescribe();
        for (Schema.PicklistEntry pe : fr.getPicklistValues()) {
            VisualEditor.DataRow dr = new VisualEditor.DataRow(pe.getLabel(), pe.getValue());
            values.addRow(dr);
        }
        return values;
    }
}