force-app/main/default/objects/List_of_Values__c.object
<CustomObject>
    <description>Generic container for Callista Reference Data

When querying, check active flags and record type for records relevant to the usage.</description>
    <fields>
        <fullName>Enquiry_Type__c</fullName>
        <label>Enquiry Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Code__c</fullName>
        <description>Field to describe Main Category</description>
        <label>System Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>A record type for each list of values

Lookups to this table should filter on type, as well as the active flag</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change Of Residency Faculty Name</fullName>
                </value>
                <value>
                    <fullName>Change Of Residency Visa Subclass</fullName>
                </value>
                <value>
                    <fullName>ADM_CNDTNL_OFFER_STATUS</fullName>
                    <label>Conditional Offer Response</label>
                </value>
                <value>
                    <fullName>ADM_DOC_STATUS</fullName>
                    <label>Documentation</label>
                </value>
                <value>
                    <fullName>ADM_ENTRY_QUAL_STATUS</fullName>
                    <label>Entry Qualification</label>
                </value>
                <value>
                    <fullName>ADM_OFFER_RESP_STATUS</fullName>
                    <label>Offer Response</label>
                </value>
                <value>
                    <fullName>ADM_OFFER_DFRMNT_STATUS</fullName>
                    <label>Offer Deferment</label>
                </value>
                <value>
                    <fullName>ADM_OUTCOME_STATUS</fullName>
                    <label>Outcome</label>
                </value>
                <value>
                    <fullName>Intermission Reason</fullName>
                </value>
                <value>
                    <fullName>SS_DiscontinuationReason</fullName>
                    <label>Discontinuation Reason</label>
                </value>
                <value>
                    <fullName>CaseCategorisation</fullName>
                    <default>true</default>
                    <label>CaseCategorisation</label>
                </value>
                <value>
                    <fullName>Reason for COE</fullName>
                </value>
                <value>
                    <fullName>Student Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value supplied to Callista via the integrations

Unique within a type</description>
        <label>Value</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Support_Options__c.object
<CustomObject>
    <description>Object to save the mapping between OutBound Call Result with List Of Values options</description>
    <fields>
        <fullName>List_of_Values__c</fullName>
        <complianceGroup>GDPR</complianceGroup>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to map to List of Values object</description>
        <label>List of Values</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>List_of_Values__c.Type__c</field>
                <operation>equals</operation>
                <value>Student Support</value>
            </filterItems>
            <filterItems>
                <field>List_of_Values__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>List Of Values</relationshipLabel>
        <relationshipName>List_of_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outbound_Call__c</fullName>
        <complianceGroup>GDPR</complianceGroup>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to link to OutBound Call result option</description>
        <label>Outbound Call</label>
        <referenceTo>Outbound_Call_Result__c</referenceTo>
        <relationshipLabel>Student Support Options</relationshipLabel>
        <relationshipName>Student_Support_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student Support Options</label>
    <nameField>
        <displayFormat>SSO-{000000}</displayFormat>
        <label>Student Support Options Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Support Options</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateStudSupptOptionController.cls
/*******************************************************************************
* @author       Inderpal Dhanoa
* @date         17/06/2024
* @description  Class that will create Student Support Options
* @revision     17/06/2024 - Initial Version
*******************************************************************************/
public with sharing class CreateStudSupptOptionController {
    public static string ENQ_TYPE_STUD_SUPPORT = 'Student Support';
    /*******************************************************************************
     * @author       Inderpal Dhanoa
     * @date         8.June.2024
     * @description  Method to fetch the mapping from the List of Values Object
    *******************************************************************************/ 
    @AuraEnabled
    public static List<CreateStudSupptOptionController.SupportOptionWrapper> fetchSupportOptionMappings() {
        CreateStudSupptOptionController.SupportOptionWrapper obj;
        List<CreateStudSupptOptionController.SupportOptionWrapper> supportOptionComb = new List<CreateStudSupptOptionController.SupportOptionWrapper>();
        List<String> mappedValues;
        for(List_of_Values__c val : [SELECT Value__c, System_Code__c 
                                    FROM List_of_Values__c 
                                    WHERE Is_Active__c = true AND Enquiry_Type__c = :ENQ_TYPE_STUD_SUPPORT
                                    AND Type__c = :ENQ_TYPE_STUD_SUPPORT]){
            obj = new CreateStudSupptOptionController.SupportOptionWrapper();
            obj.supportArea = val.System_Code__c;
            obj.supportOption = val.Value__c;
            supportOptionComb.add(obj);
        }
        return supportOptionComb;
    }

    /*******************************************************************************
     * @author       Inderpal Dhanoa
     * @date         8.June.2024
     * @description  Method to save the mapping from the List of Values Object
     * and save fresh records on the Junction object 
    *******************************************************************************/ 
    @AuraEnabled
    public static String saveMappings(String mapping, String recordId) {
        Set<String> s_supportAreaSupportOption = new Set<String>();
        for(String eachMapping : mapping.split(';')){
            s_supportAreaSupportOption.add(eachMapping);
        }
        Map<String, Id> listOfValuesMappings = new Map<String, Id>();
        Map<String, Id> exisitngStudSupptOptionsRecds = new Map<String, Id>();
        CreateStudSupptOptionController.SupportOptionWrapper obj;
        List<CreateStudSupptOptionController.SupportOptionWrapper> supportOptionComb = new List<CreateStudSupptOptionController.SupportOptionWrapper>();
        List<String> mappedValues;
        String existingKey;
        for(List_of_Values__c val : [SELECT Id, Value__c, System_Code__c 
                                    FROM List_of_Values__c 
                                    WHERE Is_Active__c = true AND Enquiry_Type__c = :ENQ_TYPE_STUD_SUPPORT
                                    AND Type__c = :ENQ_TYPE_STUD_SUPPORT]){
            listOfValuesMappings.put(val.System_Code__c + '-' + val.Value__c, val.Id);
        }
        // CHeck for Existing values mapped
        for(Student_Support_Options__c rec : [SELECT List_of_Values__r.Value__c, List_of_Values__r.System_Code__c 
                                              FROM Student_Support_Options__c 
                                              WHERE Outbound_Call__c = :Id.ValueOf(recordId)]){
            exisitngStudSupptOptionsRecds.put(rec.List_of_Values__r.System_Code__c + '-' + rec.List_of_Values__r.Value__c, rec.Id);
        }
        // Remove duplicates
        List<Student_Support_Options__c> newMapping = new List<Student_Support_Options__c>();
        Student_Support_Options__c rec;
        for(String key : s_supportAreaSupportOption){
            if(!exisitngStudSupptOptionsRecds.containsKey(key) && listOfValuesMappings.containsKey(key)){
                rec = new Student_Support_Options__c();
                rec.List_of_Values__c = listOfValuesMappings.get(key);
                rec.Outbound_Call__c = Id.ValueOf(recordId);
                newMapping.add(rec);
            }
        }
        // Insert fresh Mapping
        try{
            insert newMapping;
            return 'Success';
        }catch(Exception ex){
            Nebula.Logger.error(ex.getMessage(), ex);Nebula.Logger.saveLog();return ex.getMessage(); 
        }
    }

    public class SupportOptionWrapper{
        @AuraEnabled
        public String supportArea;
        @AuraEnabled
        public String supportOption;
    }
}