force-app/main/default/objects/LoginAsEventProxy__e.object
<CustomObject>
    <description>Proxy for standard LoginAsEventStream event. Since the native LoginAsEventStream does not support Apex or Flow subscribers we use this object as a proxy. An external Cometd client subscribes to LoginAsEventStream and republishes events verbatim to this object so they can be consumed on-platform by Apex and Flow subscribers. It&apos;s a workaround!</description>
    <fields>
        <fullName>DelegatedUsername__c</fullName>
        <description>Username of the admin who is logging in as another user. For example, admin@company.com</description>
        <label>DelegatedUsername</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <description>Unique ID that identifies the user who is being logged in as by the admin. For example, 005000000000123.</description>
        <label>UserId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>Username of the user who is being logged in as by the admin, in the format of admin@company.com.</description>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>LoginAsEventProxy</label>
    <pluralLabel>LoginAsEventProxy</pluralLabel>
</CustomObject>

force-app/main/default/classes/LoginAsEventProxyTrigger_Test.cls
/**
 * @description       : Test class for LoginAsEventProxyTrigger trigger on LoginAsEventProxy__e platform events.
 * @author            : Jackie Ho
 * @group             : Test
 * @last modified on  : 05-08-2025
 * @last modified by  : Jackie Ho
 * Modifications Log 
 * Ver   Date         Author          Modification
 * 1.0   05-08-2025   Jackie Ho       Initial Version
**/
@isTest(isParallel=true)
private class LoginAsEventProxyTrigger_Test {
    @IsTest
    static void testTriggerExecution() {
        // GIVEN: Create 2 users, one with elevated privs CP assigned
        String random = String.valueOf(System.currentTimeMillis());
        User thisUser = [SELECT Id, Username FROM User WHERE Id = :UserInfo.getUserId()];

        //Create user assigned ElevatedPrivilegesUser CP/PS
        Profile internalProfile = [SELECT Id FROM Profile WHERE name = 'System Administrator'];
        User elevatedPrivsUser = new User(
                ProfileId = internalProfile.Id,
                Username = random + 'testing@monash.edu',
                Alias = 'test_ao',
                Email='test_ao@monash.edu',
                EmailEncodingKey='UTF-8',
                Firstname='Firstname' + random,
                Lastname='Lastname' + random,
                LanguageLocaleKey='en_US',
                LocaleSidKey='en_US',
                TimeZoneSidKey='Australia/Sydney'
        );
        
        System.runAs(thisUser) {
            Database.insert(elevatedPrivsUser);
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = :LoginAsEventProxyTriggerHandler.ELEVATED_PRIVILEGES_CP_NAME];
            PermissionSetAssignment psa = new PermissionSetAssignment(
                PermissionSetId = ps.Id, 
                AssigneeId = elevatedPrivsUser.Id);
            Database.insert(psa);  
        }

        // WHEN: Create platform event record
        LoginAsEventProxy__e pe = new LoginAsEventProxy__e (
            DelegatedUsername__c = thisUser.Username,
            Username__c = elevatedPrivsUser.Username,
            UserId__c = elevatedPrivsUser.Id
        );

        Test.startTest();
        // WHEN: Publish the platform event which will invoke the trigger
        Database.SaveResult eventResult = EventBus.publish(pe);
        Test.stopTest();

        // THEN: Verify the event was published successfully
        Assert.isTrue(eventResult.isSuccess(), 'Unable to save platform event');
    }
}