force-app/main/default/objects/Mentee__c.object
<CustomObject>
    <description>This object contains the mentee application.</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>This lists the status of the mentee application.</description>
        <inlineHelpText>This lists the status of the mentee application.</inlineHelpText>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mentee_Name__c</fullName>
        <formula>Mentee__r.FirstName + &apos; &apos; + Mentee__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mentee Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mentee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mentee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mentees</relationshipLabel>
        <relationshipName>Mentees_Mentee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mentor_Name__c</fullName>
        <formula>Mentor__r.CreatedBy.FirstName +  Mentor__r.CreatedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mentor Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <description>This is the description of the Job Shadow Opportunity.</description>
        <inlineHelpText>This is the description of the Job Shadow Opportunity.</inlineHelpText>
        <label>Mentor</label>
        <referenceTo>Mentor__c</referenceTo>
        <relationshipLabel>Mentees</relationshipLabel>
        <relationshipName>Mentees_Mentor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Topics_of_Interest__c</fullName>
        <description>This is where the mentee applicant can list the various areas they would like to discuss with the mentor.</description>
        <inlineHelpText>Please list any topics you specifically like to discuss with the potential mentor.</inlineHelpText>
        <label>Topics of Interest</label>
        <type>TextArea</type>
    </fields>
    <label>Mentee</label>
    <nameField>
        <displayFormat>MENTEE-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mentees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mentor__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Role_Details_and_Notes__c</fullName>
        <label>Additional Role Details and Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Available__c</fullName>
        <formula>IF((Total_Openings__c - Number_of_Mentees_Accepted__c)&gt;0, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Responsibilities__c</fullName>
        <description>The dependent picklist from the job category</description>
        <label>Job Responsibilities</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Mentoring_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition integration</fullName>
                </value>
                <value>
                    <fullName>Application management</fullName>
                </value>
                <value>
                    <fullName>Build customer demos</fullName>
                </value>
                <value>
                    <fullName>Build customer proposals</fullName>
                </value>
                <value>
                    <fullName>Build sound financial plans</fullName>
                </value>
                <value>
                    <fullName>Campaign creation</fullName>
                </value>
                <value>
                    <fullName>Capacity planning</fullName>
                </value>
                <value>
                    <fullName>Coach new hires</fullName>
                </value>
                <value>
                    <fullName>Create internal marketing campaigns</fullName>
                </value>
                <value>
                    <fullName>Create marketing collateral</fullName>
                </value>
                <value>
                    <fullName>Create strategic reports</fullName>
                </value>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>Customer visits</fullName>
                </value>
                <value>
                    <fullName>Develop code</fullName>
                </value>
                <value>
                    <fullName>Develop HR policy</fullName>
                </value>
                <value>
                    <fullName>Develop product roadmaps</fullName>
                </value>
                <value>
                    <fullName>Drive customer adoption</fullName>
                </value>
                <value>
                    <fullName>Drive sales productivity</fullName>
                </value>
                <value>
                    <fullName>Engage with non profits</fullName>
                </value>
                <value>
                    <fullName>Engineering management</fullName>
                </value>
                <value>
                    <fullName>Evaluate contracts</fullName>
                </value>
                <value>
                    <fullName>Feature prioritization</fullName>
                </value>
                <value>
                    <fullName>Field event organization</fullName>
                </value>
                <value>
                    <fullName>Financial analysis</fullName>
                </value>
                <value>
                    <fullName>Handle customer objections</fullName>
                </value>
                <value>
                    <fullName>Hiring</fullName>
                </value>
                <value>
                    <fullName>Manage a distributed team</fullName>
                </value>
                <value>
                    <fullName>Manage a team</fullName>
                </value>
                <value>
                    <fullName>Manage badging</fullName>
                </value>
                <value>
                    <fullName>Manage business processes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mentor_Name__c</fullName>
        <description>The Job Shadow Host&apos;s name</description>
        <formula>CreatedBy.FirstName+&quot; &quot;+CreatedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mentor Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mentoring_Category__c</fullName>
        <label>Mentoring Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Administration and Operations</fullName>
                </value>
                <value>
                    <fullName>Corporate Development</fullName>
                </value>
                <value>
                    <fullName>Enterprise Strategy</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Foundation</fullName>
                </value>
                <value>
                    <fullName>Human Resources</fullName>
                </value>
                <value>
                    <fullName>Information Technology/Security</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Product Engineering</fullName>
                </value>
                <value>
                    <fullName>Product Management</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Sales Engineering</fullName>
                </value>
                <value>
                    <fullName>Technical Operations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Mentees_Accepted__c</fullName>
        <label>Number of Mentees_Accepted</label>
        <summaryFilterItems>
            <field>Mentee__c.Application_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>Mentee__c.Mentor__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Openings__c</fullName>
        <defaultValue>3</defaultValue>
        <description>The amount of available mentee slots the mentor has available.</description>
        <inlineHelpText>The amount of available mentee slots the mentor has available.</inlineHelpText>
        <label>Total Openings</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Mentor</label>
    <nameField>
        <label>Mentor Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PORTAL_MentorListController.cls
/*
 * Copyright (c) 2019, UC Innovation, Inc.  All Rights Reserved.
 *                     http://www.ucinnovation.com
 *
 * This source code is licensed, not sold, and is subject to a written
 * license agreement.  Among other things, no portion of this source
 * code may be copied, transmitted, disclosed, displayed, distributed,
 * translated, used as the basis for a derivative work, or used, in
 * whole or in part, for any program or purpose other than its intended
 * use in compliance with the license agreement as part of UC Innovation's
 * software.  This source code and certain of the algorithms contained
 * within it are confidential trade secrets of UC Innovation, Inc.
 * and may not be used as the basis for any other
 * software, hardware, product or service.
 */
 
 /**
 * Handles methods related to mentor/mentee.
 *
 * @author:  Ken Tang
 * @version: 1.0
 * @since:   1.0
 */
global without sharing class PORTAL_MentorListController {

    /**
     * Get a list of mentors.
     *
     * @param: sharing     	'All, 'Me', 'My Request'
     * @param: relevance   	'All', 'Recommended', 'Non-Recommended'
     * @param: maxItems    	Maximum number of mentors to return.  It's a string since Salesforce has issues with passing
     *                     	integers from Lightning Component controller to Apex controller.
     * @return:            	List of mentors.
     * @since: 				1.0
     */
    @AuraEnabled
    global static List<Mentor__c> SERVER_getMentorList(String sharing, String relevance, String maxItems, String searchText) {
        
        Integer maxItemsInt = Integer.valueOf(maxItems);
        
        if (!String.isBlank(searchText)) {
            searchText = '%' + searchText + '%';
        }                                                          
        
        Id userId = UserInfo.getUserId();
        
        System.debug('userId: ' + userId);
        
        User usr = PORTAL_CommunityUtils.getLoggedInUserInfo(userId);
        
        Id contactId = usr.ContactId;
        
        System.debug('contactId: ' + contactId);
        
        // If not contact, then must be a regular Salesforce user.
        if (contactId == null) {
            return new List<Mentor__c>();
        }
        
        system.debug('searchText: ' + searchText);
        system.debug('maxItemsInt: ' + maxItemsInt);
        
        List<Mentor__c> mentorList = new List<Mentor__c>();
        
        String queryString = 'SELECT Id, Name, CreatedById, Application_Status__c, Is_Available__c, Mentor_Name__c, Additional_Role_Details_and_Notes__c, Number_of_Mentees_Accepted__c, Mentoring_Category__c, Total_Openings__c, Job_Responsibilities__c, ' +
            '(SELECT Id, Name, Mentor__c, Mentee__c, Mentee__r.FirstName, Mentee__r.LastName, Mentee_Name__c, Application_Status__c, Topics_of_Interest__c FROM Mentees_Mentor__r) ' +
            'FROM Mentor__c ';
        
        if (!String.isBlank(searchText)) {
            queryString = queryString + 'WHERE Name LIKE :searchText';
        }
        
        mentorList = Database.query(queryString);                  
        
        System.debug('mentorList: ' + mentorList);
        
        List<Mentor__c> myMentorList = new List<Mentor__c>();
        List<Mentor__c> notMyMentorList = new List<Mentor__c>();
        List<Mentor__c> myMentorRequestList = new List<Mentor__c>();
        
        for (Mentor__c mentorRec : mentorList) {
            // I'm the mentor...
            if (mentorRec.CreatedById == userId) {
                myMentorList.add(mentorRec);
            }
            // Check for my list of mentors I applied for.
            else if (mentorRec.Mentees_Mentor__r != null && !mentorRec.Mentees_Mentor__r.isEmpty()) {
                Boolean found = false;
                
                for (Mentee__c menteeRec : mentorRec.Mentees_Mentor__r) {
                    
                    // If I'm a mentee, then must be my mentor.
                    if (menteeRec.Mentee__c == contactId) {
                        myMentorRequestList.add(mentorRec);
                        found = true;
                        break;
                    }
                }
                
                if (!found && mentorRec.Application_Status__c == 'Approved') {
                    notMyMentorList.add(mentorRec);
                }
            }            
            else if (mentorRec.Application_Status__c == 'Approved') {
                notMyMentorList.add(mentorRec);
            }
        }
        
        System.debug('myMentorList: ' + myMentorList);
        System.debug('notMyMentorList: ' + notMyMentorList);
        System.debug('myMentorRequestList: ' + myMentorRequestList);
        
        List<Mentor__c> resultMentorList = new List<Mentor__c>();
        List<Mentor__c> tempMentorList = new List<Mentor__c>();
        
        if (sharing == 'Me') {
            tempMentorList = myMentorList;
        }
        else if (sharing == 'My Request') {
            tempMentorList = myMentorRequestList;
        }
        else {
            tempMentorList = notMyMentorList;
        }
        
        System.debug('tempMentorList: ' + tempMentorList);
        
        for (Mentor__c mentorRec : tempMentorList) {
            resultMentorList.add(mentorRec);
            
            if (resultMentorList.size() >= maxItemsInt) {
                break;
            }
        }
        
        System.debug('resultMentorList: ' + resultMentorList);
        
        return resultMentorList;
    }

    /**
     * Get contact information associated with the logged in user.
     *
     * @return:	Contact associated with the logged in user.
     * @since: 	1.0
     */
    @AuraEnabled
    public static Contact SERVER_getContactInfo() {
		return PORTAL_CommunityUtils.getContactInfoFromUser(UserInfo.getUserId());
    }

    /**
     * Update the application status of the mentee.
     *
     * @param: menteeRec    Mentee to be updated.
     * @param: status     	Status to update the application status to.
     * @since: 1.0
     */
    @AuraEnabled
    public static void SERVER_updateMenteeApplicationStatus(Mentee__c menteeRec, String status) {
        menteeRec.Application_Status__c = status;
        update menteeRec;
    }

    /**
     * Update the application status of the mentee.
     *
     * @param: mentorRecId  Record ID of the mentor.
     * @param: contactId    Record ID of the contact associated with the logged in user.
     * @return: Mentee associated with the mentor and logged in user (contact).
     * @since: 	1.0
     */
    @AuraEnabled
    global static Mentee__c SERVER_getMentee(Id mentorRecId, Id contactId) {
        
		Mentee__c mentee = [SELECT Id FROM Mentee__c WHERE Mentor__c = :mentorRecId AND Mentee__c = :contactId];

        System.debug('mentee: ' + mentee);
        
        return mentee;
    }    
}