force-app/main/default/objects/Offer_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>DocuSign_Base_Return_URL__c</fullName>
        <description>The base URL for when DocuSign completes the embedded process and redirects the user back</description>
        <inlineHelpText>This should not end with &quot;/&quot;.
An example of this value &quot;
https://sfcpq2dev-monashpartner.cs152.force.com&quot;</inlineHelpText>
        <label>DocuSign Base Return URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>DocuSign_Return_URL_Path__c</fullName>
        <description>The path of the DocuSign return URL. This should be used with the DocuSign Base Return URL to form the complete URL for the redirection of the user. Should not start with &quot;/&quot;.</description>
        <inlineHelpText>Should not start with &quot;/&quot;</inlineHelpText>
        <label>DocuSign Return URL Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Offer Setting</label>
</CustomObject>

force-app/main/default/classes/OffersDocuSignSigningUrlConfig_Test.cls
/**
 * @description Test class for OffersDocuSignSigningUrlConfig
 */
@isTest(isParallel=true)
public class OffersDocuSignSigningUrlConfig_Test {
    
    private static final String EXPECTED_RETURN_URL = 'https://sfcpqqa-monashpartner.cs152.force.com/admissions';
    private static final String BASE_RETURN_URL = 'https://sfcpqqa-monashpartner.cs152.force.com';
    private static final String URL_PATH = 'admissions';

    @testSetup
    static void makeData(){
        Offer_Setting__c offerSetting = new Offer_Setting__c();
        offerSetting.DocuSign_Base_Return_URL__c = BASE_RETURN_URL;
        offerSetting.DocuSign_Return_URL_Path__c = URL_PATH;
        insert offerSetting;
    }

    @isTest
    static void shouldReturnADocuSignReturnUrl() {
        OffersDocuSignSigningUrlConfig config = 
            new OffersDocuSignSigningUrlConfig();
        String result = config.getDocuSignReturnUrl();
        System.assertEquals(EXPECTED_RETURN_URL, result, 
            'Expected URL returned to match expected result');
    }

}