force-app/main/default/objects/Offer_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>DocuSign_Base_Return_URL__c</fullName>
        <description>The base URL for when DocuSign completes the embedded process and redirects the user back</description>
        <inlineHelpText>This should not end with &quot;/&quot;.
An example of this value &quot;
https://sfcpq2dev-monashpartner.cs152.force.com&quot;</inlineHelpText>
        <label>DocuSign Base Return URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>DocuSign_Return_URL_Path__c</fullName>
        <description>The path of the DocuSign return URL. This should be used with the DocuSign Base Return URL to form the complete URL for the redirection of the user. Should not start with &quot;/&quot;.</description>
        <inlineHelpText>Should not start with &quot;/&quot;</inlineHelpText>
        <label>DocuSign Return URL Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Offer Setting</label>
</CustomObject>

force-app/main/default/classes/OffersDocuSignSigningUrlConfig.cls
/**
 * @description Configuration for Offer's DocuSign Get Signing URL
 * @group Offers Get Signing URL
 */
public inherited sharing class OffersDocuSignSigningUrlConfig {

    /**
     * @description Returns the DocuSign Return URL that is used for the 
     * docuSign Signer redirection back to Salesforce communities
     * @return DocuSign return URL as a string
     */
    public String getDocuSignReturnUrl() {
        Offer_Setting__c offerSetting = Offer_Setting__c.getOrgDefaults();
        // Return URL Path could be optional
        // This ensures null is not appended if the value was not set
        String returnUrlPath = String.isBlank(offerSetting.DocuSign_Return_URL_Path__c) ? '' : offerSetting.DocuSign_Return_URL_Path__c;
        return offerSetting.DocuSign_Base_Return_URL__c + '/' + returnUrlPath;
    }

}