force-app/main/default/objects/Offers_Recipient_Signed_Event__e.object
<CustomObject>
    <description>Platform event which indicates when a person for an offer has signed an offer document.</description>
    <fields>
        <fullName>Envelop_Id__c</fullName>
        <label>Envelop Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Offers Recipient Signed Event</label>
    <pluralLabel>Offers Recipient Signed Events</pluralLabel>
</CustomObject>

force-app/main/default/classes/OffersRecipientSignedEventTrigger_Test.cls
/**
 * @description Test class for OffersRecipientSignedEventTrigger
 */
@isTest(isParallel=true)
public class OffersRecipientSignedEventTrigger_Test {
    @isTest
    static void shouldInsertEvent() {
        Test.startTest();
        Offers_Recipient_Signed_Event__e recipientSignedEvent = new Offers_Recipient_Signed_Event__e();
        recipientSignedEvent.Envelop_Id__c = 'abc-123';
        EventBus.publish(recipientSignedEvent);
        Test.getEventBus().deliver();
        System.assert(true, 'Expected insert to work');
        Test.stopTest();
    }

    @isTest
    static void shouldNotThrowExceptionWhenTriggerIsDisabled() {
        TriggerCommon.disableTrigger('Offers_Recipient_Signed_Event__e');

        Test.startTest();
        Offers_Recipient_Signed_Event__e recipientSignedEvent = new Offers_Recipient_Signed_Event__e();
        recipientSignedEvent.Envelop_Id__c = 'abc-123';
        EventBus.publish(recipientSignedEvent);
        Test.getEventBus().deliver();
        System.assert(true, 'Expected insert to work when trigger is disabled');
        Test.stopTest();
    }
}