force-app/main/default/objects/Outbound_Call_Result__c.object
<CustomObject>
    <fields>
        <fullName>Call_Result__c</fullName>
        <label>Call Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Callback Requested</fullName>
                </value>
                <value>
                    <fullName>Enquiry Created</fullName>
                </value>
                <value>
                    <fullName>Follow-up Required</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>No Follow-up Required</fullName>
                </value>
                <value>
                    <fullName>No - No Answer</fullName>
                </value>
                <value>
                    <fullName>No - Not Applicable</fullName>
                </value>
                <value>
                    <fullName>No - Not Available</fullName>
                </value>
                <value>
                    <fullName>No - Wrong Number</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Call_Status__c</fullName>
        <label>Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Outbound Calls</relationshipLabel>
        <relationshipName>Outbound_Calls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Outbound Calls</relationshipLabel>
        <relationshipName>Outbound_Calls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Outbound Calls</relationshipLabel>
        <relationshipName>Outbound_Calls</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Time_Closed__c</fullName>
        <label>Date/Time Closed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Engagement</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>Unrelated</fullName>
                </value>
                <value>
                    <fullName>Student Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Lead Object - Used in case of PreApp Domestic and International</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Outbound Calls</relationshipLabel>
        <relationshipName>Outbound_Calls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_Of_Attempts__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <inlineHelpText>Make this value +1 with each call attempt. (Note: Leave this as 0 for &quot;Not Available&quot;)</inlineHelpText>
        <label>Number Of Attempts</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0</label>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Person_ID__c</fullName>
        <formula>Contact__r.Person_ID_unique__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Person ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Risk_Category_V2__c</fullName>
        <label>Risk Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Academic Progress</fullName>
                </value>
                <value>
                    <fullName>Can&apos;t Study Online</fullName>
                </value>
                <value>
                    <fullName>COVID-19</fullName>
                </value>
                <value>
                    <fullName>COVID-19 Victoria</fullName>
                </value>
                <value>
                    <fullName>Dislike Online Study</fullName>
                </value>
                <value>
                    <fullName>Employment/Internship</fullName>
                </value>
                <value>
                    <fullName>Family Support</fullName>
                </value>
                <value>
                    <fullName>Financial Considerations</fullName>
                </value>
                <value>
                    <fullName>IT/Technology Constraints</fullName>
                </value>
                <value>
                    <fullName>Medical/Health</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Military Service</fullName>
                </value>
                <value>
                    <fullName>Needs To Secure Placement</fullName>
                </value>
                <value>
                    <fullName>Other Study Conflicts</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Study Break</fullName>
                </value>
                <value>
                    <fullName>Studying Elsewhere</fullName>
                </value>
                <value>
                    <fullName>Travel/Pursue Travel</fullName>
                </value>
                <value>
                    <fullName>Travel Restrictions</fullName>
                </value>
                <value>
                    <fullName>Undecided About Finishing Study</fullName>
                </value>
                <value>
                    <fullName>Units Not Available Next Semester</fullName>
                </value>
                <value>
                    <fullName>Wants To Stay In Online Mode</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk_Category__c</fullName>
        <description>Field to describe the Risk Category for OCR records</description>
        <label>Risk Category (multi)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Academic progress</fullName>
                </value>
                <value>
                    <fullName>Can&apos;t Study Online</fullName>
                </value>
                <value>
                    <fullName>COVID-19</fullName>
                </value>
                <value>
                    <fullName>Dislike Online Study</fullName>
                </value>
                <value>
                    <fullName>Employment/Internship</fullName>
                </value>
                <value>
                    <fullName>Family Support</fullName>
                </value>
                <value>
                    <fullName>Financial Considerations</fullName>
                </value>
                <value>
                    <fullName>IT/Technology Constraints</fullName>
                </value>
                <value>
                    <fullName>Medical/Health</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Military Service</fullName>
                </value>
                <value>
                    <fullName>Other Study Conflicts</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Study Break</fullName>
                </value>
                <value>
                    <fullName>Travel/Pursue Travel</fullName>
                    <label>Travel</label>
                </value>
                <value>
                    <fullName>Travel Restrictions</fullName>
                </value>
                <value>
                    <fullName>Undecided About Finishing Study</fullName>
                </value>
                <value>
                    <fullName>Units Not Available Next Semester</fullName>
                </value>
                <value>
                    <fullName>Does not wish to disclose reason</fullName>
                </value>
                <value>
                    <fullName>Parental / Carer&apos;s leave</fullName>
                </value>
                <value>
                    <fullName>Unhappy With Monash Experience</fullName>
                </value>
                <value>
                    <fullName>Needs To Secure Placement</fullName>
                </value>
                <value>
                    <fullName>Studying Elsewhere</fullName>
                </value>
                <value>
                    <fullName>Studying another Monash course</fullName>
                </value>
                <value>
                    <fullName>Wants To Stay In Online Mode</fullName>
                </value>
                <value>
                    <fullName>Assessment Fails</fullName>
                </value>
                <value>
                    <fullName>Consecutive Assessment Fails</fullName>
                </value>
                <value>
                    <fullName>Employment/Internship/Placement</fullName>
                </value>
                <value>
                    <fullName>First Assessment Failed</fullName>
                </value>
                <value>
                    <fullName>Low Moodle Engagement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk_Summary__c</fullName>
        <label>Risk Summary</label>
        <type>TextArea</type>
    </fields>
    <label>Outbound Call</label>
    <nameField>
        <displayFormat>OCR-{0}</displayFormat>
        <label>Outbound Call Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Calls</pluralLabel>
    <recordTypes>
        <fullName>Domestic_Pre_App</fullName>
        <active>true</active>
        <label>Domestic Pre App</label>
    </recordTypes>
    <recordTypes>
        <fullName>MonCon_Support</fullName>
        <active>true</active>
        <label>MonCon Support</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/OutboundCallResultServices.cls
/**
 * @author			ayush.agrawal@monash.edu
 * @group			SRA (Student Recruitment and Admissions) - BabyShark
 * @description		Handlers for Outbound_Call_Result__c object operations primarily designed
 * 					for SRA Outbound Call console and Monash Connect Console.
 * @revision		ayush.agrawal@monash.edu - EPBBS-1220 Track 'Date/Time Closed' for outbound calls.
 * @revision		ayush.agrawal@monash.edu - EPBBS-1252 Retention outbound calls.
 * @revision		ayush.agrawal@monash.edu - RW2-267 Handle Call Result = 'Wrong Number'.
 * @revision		ayush.agrawal@monash.edu - RW2-331 Retention Statuses Roll-up to Contact.
 * @revision		ayush.agrawal@monash.edu - RW2-358 Pre-populate retention fields on enquiry generation.
 * @revision		ayush.agrawal@monash.edu - RW2-374 Move from Risk_Category__c (multi-picklist) to Risk_Category_V2__c (picklist).
 * @revision		ayush.agrawal@monash.edu - RW2-445 Bypass retention roll-up logic for Archived OCRs.
 * @revision        ayush.agrawal@monash.edu - SA-1664 Deprecate MonCon_Support_Case_Owner_Mapping__mdt.
 * @revision        inderpal.dhanoa@monash.edu - MCT-414 Add Logic to craete MC Campaign Members.
 * @revision        inderpal.dhanoa@monash.edu - MCT-456 Add Logic to close linked MC Cases.
 * @revision        inderpal.dhanoa@monash.edu - MCT-504 Add Exclusion Logic for Student Support Cases.
 */

public class OutboundCallResultServices {
    /**
     * @author			Ayush Agarwal
     * @description		Assigns Owner to Queue
     */
    public class unassignedQueueOwnerAssignment implements Triggers.Handler {
        /**
         * @description		method to initiate execution
         */
        public void run() {
            List<Outbound_Call_Result__c> outboundCallResults = Trigger.new;
            
            Group unassignedQueue = [SELECT Id FROM Group WHERE DeveloperName = 'Outbound_Call_Unassigned' AND Type = 'Queue' LIMIT 1];
            
            for(Outbound_Call_Result__c ocr : outboundCallResults) {
                    ocr.OwnerId = unassignedQueue.Id;
            }
        }
    }

    /**
     * @author			Ibrahim Rumi
     * @description		updates Lead if there is an active ocr related to the lead when an ocr is created or updated
     */
    public class SetOutboundCallStatus extends TriggerAbstract {
    
        Set<Id> leadsToProcess = new Set<Id>();

        public override void process(SObject sobj) {
            Outbound_Call_Result__c newOCRRec = (Outbound_Call_Result__c) sobj;
            if((newOCRRec.RecordTypeId == OutboundCallResultUtility.DOMESTIC_PRE_APP ||
                newOCRRec.RecordTypeId == OutboundCallResultUtility.INTL_PRE_APP) && 
                newOCRRec.Lead__c != null && newOCRRec.Call_Status__c == 'Open'){
                leadsToProcess.add(newOCRRec.Lead__c);
            }
        }

        public override void process(SObject sobj, SObject oldRec) {
            Outbound_Call_Result__c newOCRRec = (Outbound_Call_Result__c) sobj;
            Outbound_Call_Result__c oldOCRRec = (Outbound_Call_Result__c) oldRec;
            if((newOCRRec.RecordTypeId == OutboundCallResultUtility.DOMESTIC_PRE_APP ||
                newOCRRec.RecordTypeId == OutboundCallResultUtility.INTL_PRE_APP) && 
                newOCRRec.Lead__c != null && 
                oldOCRRec.Call_Status__c != newOCRRec.Call_Status__c)
                {
                    leadsToProcess.add(newOCRRec.Lead__c);
                }
            }
        
            public override void execute() {
                try {
                   if(!leadsToProcess.isEmpty()){
                        OutboundCallResultUtility.processLead(leadsToProcess);    
                   }
               } catch(Exception ex) {
                   Nebula.Logger.error(ex.getMessage(), ex);Nebula.Logger.saveLog(); 
               } 
           }

    }

    /**
     * @author			Inderpal Dhanoa
     * @description		Close linked MC Enquiries
     */
    public class closeLinkedMCEnquiries extends TriggerAbstract{
        
        Id monConSuppRecTypeId = Schema.SObjectType.Outbound_Call_Result__c.getRecordTypeInfosByDeveloperName().get('MonCon_Support')?.getRecordTypeId();
        Set<Id> linkedEnquiries = new Set<Id>();
        
        public override void process(SObject newRecord, SObject oldRecord) {
            Outbound_Call_Result__c newOCRRec = (Outbound_Call_Result__c) newRecord;
            Outbound_Call_Result__c oldOCRRec = (Outbound_Call_Result__c) oldRecord;
            if(newOCRRec.RecordTypeId == monConSuppRecTypeId && newOCRRec.Case__c != null && 
                oldOCRRec.Call_Status__c != newOCRRec.Call_Status__c && newOCRRec.Call_Status__c == 'Closed' ){
                linkedEnquiries.add(newOCRRec.Case__c);
            }
        }
        public override void execute() {
            try {
               if(!linkedEnquiries.isEmpty()){
                    OutboundCallResultUtility.closeMCEnquiry(linkedEnquiries); 
               }
           } catch(Exception ex) {
               Nebula.Logger.error(ex.getMessage(), ex);Nebula.Logger.saveLog(); 
           } finally {
               LogUtilityException.getLimits();
           }
       }
    }

    /**
     * @author			Inderpal Dhanoa
     * @description		Assigns the ContactId and linked it to the Campaign Member
     */
    public class createMCCampaignMember extends TriggerAbstract{
        
        Id monConSuppRecTypeId = Schema.SObjectType.Outbound_Call_Result__c.getRecordTypeInfosByDeveloperName().get('MonCon_Support')?.getRecordTypeId();
        List<Outbound_Call_Result__c> ocrsToProcess = new List<Outbound_Call_Result__c>();
        Set<Id> linkedCampaigns = new Set<Id>();
        
        public override void process(SObject sobj) {
            Outbound_Call_Result__c newOCRRec = (Outbound_Call_Result__c) sobj;
            if(newOCRRec.RecordTypeId == monConSuppRecTypeId && newOCRRec.Contact__c != null && newOCRRec.Campaign__c != null){
                ocrsToProcess.add(newOCRRec);
                linkedCampaigns.add(newOCRRec.Campaign__c);
            }
        }
		public override void execute() {
             try {
                if(!ocrsToProcess.isEmpty()){
                    Map<Id, Set<Id>> campMembByContacts = getExistingLinkedCampaignMembers(linkedCampaigns);
                    Set<Id> linkedCampaignContacts;
                    List<CampaignMember> freshCampaignMembrs = new List<CampaignMember>();
                    // Navigate across the list and check if there is already a Campaign Member created against the linked Campaign.
                    for(Outbound_Call_Result__c ocr : ocrsToProcess){
                        // Check if the OCR is linked to a running campaign
                        if(campMembByContacts.containsKey(ocr.Campaign__c)){
                            // Check if a Contact already exists as a Camp Membr 
                            linkedCampaignContacts = campMembByContacts.get(ocr.Campaign__c);
                            // If the Incoming Contact does not exists as a COntact on the linked Campaign then add it as a fresh entry
                            if(!linkedCampaignContacts.contains(ocr.Contact__c)){
                                freshCampaignMembrs.add(new CampaignMember(ContactId = ocr.Contact__c, campaignId = ocr.Campaign__c));        
                            } 
                        }else{
                            freshCampaignMembrs.add(new CampaignMember(ContactId = ocr.Contact__c, campaignId = ocr.Campaign__c));
                        }                       
                    }
                    if(!freshCampaignMembrs.isEmpty()){
                        // Create the Campaign Membrs
                        insert freshCampaignMembrs;
                    }  
                }
            } catch(Exception ex) {
                Nebula.Logger.error(ex.getMessage(), ex);Nebula.Logger.saveLog(); 
            } finally {
                LogUtilityException.getLimits();
            }
        }
        
        /**
        * @author			Inderpal Dhanoa
        * @description		Fetches the ContactId and retrieves the linked Campaign Members
        * @param            linkedCampaigns Set of linked Campaign Ids
        * @return           Map of Campaign Ids and the linked Contact Ids
        */
        public Map<Id, Set<Id>> getExistingLinkedCampaignMembers(Set<Id> linkedCampaigns){
            Set<Id> contactIds;
            Map<Id, Set<Id>> campMembByContacts = new Map<Id, Set<Id>>();
            for(CampaignMember cmpMbr : [SELECT Id, ContactId FROM CampaignMember WHERE CampaignId IN : linkedCampaigns]){
                if(campMembByContacts.containsKey(cmpMbr.Id)){
                    contactIds = campMembByContacts.get(cmpMbr.Id);
                }else{
                    contactIds = new Set<Id>();
                }
                contactIds.add(cmpMbr.ContactId);
                campMembByContacts.put(cmpMbr.Id, contactIds);
            }
            return campMembByContacts;
        }
    }
    
    /**
    * @author			Ayush Agarwal
    * @description		class to link Cases And Close Mon Con Support Outbound Calls
    */
    public class linkCasesAndCloseMonConSupportOutboundCalls implements Triggers.Handler {
        /**
         * @description		method to initiate execution
         */
        public void run() {
            List<Outbound_Call_Result__c> outboundCallResults = new List<Outbound_Call_Result__c>();
            
            Id monConSupportOutboundCallRecordTypeId = Schema.SObjectType.Outbound_Call_Result__c.getRecordTypeInfosByDeveloperName().get('MonCon_Support').getRecordTypeId();
            
            Set<Id> campaignIDs = new Set<Id>();
            
            for(Outbound_Call_Result__c ocr : (List<Outbound_Call_Result__c>) Trigger.new) {
                if(ocr.RecordTypeId == monConSupportOutboundCallRecordTypeId) {
                    outboundCallResults.add(ocr);
                    
                    campaignIDs.add(ocr.Campaign__c);
                }
            }
            
            if(outboundCallResults.isEmpty()) {
                return;
            }
            
            Map<Id, Outbound_Call_Result__c> outboundCallResultsOldMap = (Map<Id, Outbound_Call_Result__c>) Trigger.oldMap;
            
            Id monConSupportCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('MonCon_Support').getRecordTypeId();
            
            Group intermissionQueue = [SELECT Id, DeveloperName FROM Group WHERE Type = 'Queue' AND DeveloperName = 'Intermission' LIMIT 1];
            
            List<Case> casesToCreate = new List<Case>();
            List<Case> casesToUpdate = new List<Case>();
            
            List<Case> existingCases = [SELECT
                                        Id,
                                        Description,
                                        Outbound_Call_Result__c,
                                        Risk_Summary__c
                                        FROM Case
                                        WHERE
                                        Outbound_Call_Result__c IN :outboundCallResults
                                       	AND
                                       	IsClosed = false];
            
            Map<Id, List<Case>> mapOfOutboundCallResultIdToCases = new Map<Id, List<Case>>();
            
            for(Case c : existingCases) {
                List<Case> cases = mapOfOutboundCallResultIdToCases.get(c.Outbound_Call_Result__c);
                if(cases == null) {
                    cases = new List<Case>();
                }
                cases.add(c);
                mapOfOutboundCallResultIdToCases.put(c.Outbound_Call_Result__c, cases);
            }
            
            Map<Id, Campaign> mapOfCampaignIdToCampaign = new Map<Id, Campaign>([SELECT Id, Name FROM Campaign WHERE Id IN :campaignIDs]);
            
            for(Outbound_Call_Result__c ocr : outboundCallResults) {
                List<Case> cases = mapOfOutboundCallResultIdToCases.get(ocr.Id);
                
                if(cases != null) {
                    for(Case existingCase : cases) {
                        Boolean updateCase = false;
                        
                        if(ocr.Comments__c != existingCase.Description) {
                            existingCase.Description = ocr.Comments__c;
                            
                            updateCase = true;
                        }
                        if(ocr.Risk_Summary__c != existingCase.Risk_Summary__c) {
                            existingCase.Risk_Summary__c = ocr.Risk_Summary__c;
                            
                            updateCase = true;
                        }
                        
                        if(updateCase == true) {
                            casesToUpdate.add(existingCase);
                        }
                    }
                }
                
                if(ocr.Call_Result__c == 'Enquiry Created' || ocr.Call_Result__c == 'No Follow-up Required' || ocr.Call_Result__c == 'Wrong Number' || ocr.Number_Of_Attempts__c == '3') {
                    ocr.Call_Status__c = 'Closed';
                }
                
                if(ocr.Engagement_Type__c != 'Student Support'){
                    if(
                        (ocr.Call_Result__c == 'Enquiry Created' && outboundCallResultsOldMap.get(ocr.Id).Call_Result__c != ocr.Call_Result__c)
                        ||
                        (ocr.Call_Result__c == 'Wrong Number' && outboundCallResultsOldMap.get(ocr.Id).Call_Result__c != ocr.Call_Result__c)
                        ||
                        (ocr.Call_Result__c == 'No Answer' && ocr.Number_Of_Attempts__c == '2' && (ocr.Call_Result__c != outboundCallResultsOldMap.get(ocr.Id).Call_Result__c || ocr.Number_Of_Attempts__c != outboundCallResultsOldMap.get(ocr.Id).Number_Of_Attempts__c))
                    ) {
                        Case c = new Case();
                        c.Campaign__c = ocr.Campaign__c;
                        c.Category_Level_1__c = ocr.Engagement_Type__c;
                        c.ContactId = ocr.Contact__c;
                        c.Description = ocr.Comments__c;
                        c.Enquiry_Type__c = 'Retention';
                        c.Origin = 'Phone - MonCon Support';
                        c.Outbound_Call_Result__c = ocr.Id;
                        c.RecordTypeId = monConSupportCaseRecordTypeId;
                        c.Risk_Category__c = ocr.Risk_Category__c;
                        
                        if(ocr.Call_Result__c == 'Enquiry Created' && outboundCallResultsOldMap.get(ocr.Id).Call_Result__c != ocr.Call_Result__c) {
                            c.OwnerId = ocr.OwnerId;
                            c.Subject = ocr.Person_ID__c + ' - ' + mapOfCampaignIdToCampaign.get(ocr.Campaign__c).Name;
                        } else if(ocr.Call_Result__c == 'Wrong Number' && outboundCallResultsOldMap.get(ocr.Id).Call_Result__c != ocr.Call_Result__c) {
                            c.OwnerId = ocr.OwnerId;
                            c.Subject = ocr.Person_ID__c + ' - ' + mapOfCampaignIdToCampaign.get(ocr.Campaign__c).Name + ' - Wrong Number';
                            c.Engagement_Type__c = 'Unrelated';
                        } else {
                            c.OwnerId = ocr.OwnerId;
                            c.Subject = ocr.Person_ID__c + ' - ' + mapOfCampaignIdToCampaign.get(ocr.Campaign__c).Name + ' - No Answer';
                            c.Engagement_Type__c = 'Unrelated';
                        }
                        
                        if(c.OwnerId == null) {
                            c.OwnerId = intermissionQueue.Id;
                        }
                        
                        casesToCreate.add(c);
                    }
                }
            }
            
            if(!casesToCreate.isEmpty()) {
                insert casesToCreate;
            }
            
            if(!casesToUpdate.isEmpty()) {
                update casesToUpdate;
            }
        }
    }
    
    /**
    * @author			Ayush Agarwal
    * @description		class to track Outbound Calls as DateTime Closed
    */
    public class trackOutboundCallsDateTimeClosed implements Triggers.Handler {
        /**
         * @description		method to initiate execution
         */
        public void run() {
            List<Outbound_Call_Result__c> outboundCallResults = (List<Outbound_Call_Result__c>) Trigger.new;
            
            Map<Id, Outbound_Call_Result__c> outboundCallResultsOldMap = (Map<Id, Outbound_Call_Result__c>) Trigger.oldMap;
            
            for(Outbound_Call_Result__c ocr : outboundCallResults) {
                if(ocr.Call_Status__c == 'Closed' && outboundCallResultsOldMap.get(ocr.Id).Call_Status__c == 'Open') {
                    ocr.Date_Time_Closed__c = DateTime.now();
                }
            }
        }
    }
}