force-app/main/default/objects/Outbound_Call_Result__c.object
<CustomObject>
    <fields>
        <fullName>Call_Result__c</fullName>
        <label>Call Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Callback Requested</fullName>
                </value>
                <value>
                    <fullName>Enquiry Created</fullName>
                </value>
                <value>
                    <fullName>Follow-up Required</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>No Follow-up Required</fullName>
                </value>
                <value>
                    <fullName>No - No Answer</fullName>
                </value>
                <value>
                    <fullName>No - Not Applicable</fullName>
                </value>
                <value>
                    <fullName>No - Not Available</fullName>
                </value>
                <value>
                    <fullName>No - Wrong Number</fullName>
                </value>
                <value>
                    <fullName>Wrong Number</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Call_Status__c</fullName>
        <label>Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Outbound Calls</relationshipLabel>
        <relationshipName>Outbound_Calls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Outbound Calls</relationshipLabel>
        <relationshipName>Outbound_Calls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Outbound Calls</relationshipLabel>
        <relationshipName>Outbound_Calls</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Conversion</fullName>
                </value>
                <value>
                    <fullName>Engagement</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>Unrelated</fullName>
                </value>
                <value>
                    <fullName>Student Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Lead Object - Used in case of PreApp Domestic and International</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Outbound Calls</relationshipLabel>
        <relationshipName>Outbound_Calls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_Of_Attempts__c</fullName>
        <defaultValue>&quot;0&quot;</defaultValue>
        <inlineHelpText>Make this value +1 with each call attempt. (Note: Leave this as 0 for &quot;Not Available&quot;)</inlineHelpText>
        <label>Number Of Attempts</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0</label>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>IF(Owner:Queue.QueueName = &quot;&quot;, (Owner:User.FirstName + &quot; &quot; + Owner:User.LastName), Owner:Queue.QueueName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retention_Status__c</fullName>
        <label>Decision</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Engagement_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CoP</fullName>
                </value>
                <value>
                    <fullName>COVID-19 Victoria</fullName>
                </value>
                <value>
                    <fullName>Declined Offer</fullName>
                </value>
                <value>
                    <fullName>Deferred Offer</fullName>
                </value>
                <value>
                    <fullName>Enrolled (New Student)</fullName>
                </value>
                <value>
                    <fullName>Firm Discontinue</fullName>
                </value>
                <value>
                    <fullName>Firm Intermission</fullName>
                </value>
                <value>
                    <fullName>Going Ok / Likely To Stay</fullName>
                </value>
                <value>
                    <fullName>Plans To Accept</fullName>
                </value>
                <value>
                    <fullName>Plans To Continue</fullName>
                </value>
                <value>
                    <fullName>Plans to Enrol</fullName>
                </value>
                <value>
                    <fullName>Retained</fullName>
                </value>
                <value>
                    <fullName>Some Difficulties / Could Be At Risk</fullName>
                </value>
                <value>
                    <fullName>Still Deciding</fullName>
                </value>
                <value>
                    <fullName>Unrelated to Retention</fullName>
                </value>
                <value>
                    <fullName>Unsatisfied / Likely To Leave</fullName>
                </value>
                <value>
                    <fullName>Already Enrolled</fullName>
                </value>
                <value>
                    <fullName>Currently receiving additional support</fullName>
                </value>
                <value>
                    <fullName>Does not require additional support</fullName>
                </value>
                <value>
                    <fullName>Going OK / Back on Track</fullName>
                </value>
                <value>
                    <fullName>Reconsidering study / Likely to leave</fullName>
                </value>
                <value>
                    <fullName>Requires additional support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk_Category_V2__c</fullName>
        <label>Risk Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Academic Progress</fullName>
                </value>
                <value>
                    <fullName>Can&apos;t Study Online</fullName>
                </value>
                <value>
                    <fullName>COVID-19</fullName>
                </value>
                <value>
                    <fullName>COVID-19 Victoria</fullName>
                </value>
                <value>
                    <fullName>Dislike Online Study</fullName>
                </value>
                <value>
                    <fullName>Employment/Internship</fullName>
                </value>
                <value>
                    <fullName>Family Support</fullName>
                </value>
                <value>
                    <fullName>Financial Considerations</fullName>
                </value>
                <value>
                    <fullName>IT/Technology Constraints</fullName>
                </value>
                <value>
                    <fullName>Medical/Health</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Military Service</fullName>
                </value>
                <value>
                    <fullName>Needs To Secure Placement</fullName>
                </value>
                <value>
                    <fullName>Other Study Conflicts</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Study Break</fullName>
                </value>
                <value>
                    <fullName>Studying Elsewhere</fullName>
                </value>
                <value>
                    <fullName>Travel/Pursue Travel</fullName>
                </value>
                <value>
                    <fullName>Travel Restrictions</fullName>
                </value>
                <value>
                    <fullName>Undecided About Finishing Study</fullName>
                </value>
                <value>
                    <fullName>Units Not Available Next Semester</fullName>
                </value>
                <value>
                    <fullName>Wants To Stay In Online Mode</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Outbound Call</label>
    <nameField>
        <displayFormat>OCR-{0}</displayFormat>
        <label>Outbound Call Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Calls</pluralLabel>
    <recordTypes>
        <fullName>Domestic_Pre_App</fullName>
        <active>true</active>
        <label>Domestic Pre App</label>
    </recordTypes>
    <recordTypes>
        <fullName>MonCon_Support</fullName>
        <active>true</active>
        <label>MonCon Support</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/OutboundCallResultServices_Test.cls
/**
 * @author	Ayush Agrawal (ayush.agrawal@monash.edu)
 * @group	SRA (Student Recruitment and Admissions) - BabyShark
 * @revision        inderpal.dhanoa@monash.edu - MCT-414 Add Logic to craete MC Campaign Members.
 * @revision        inderpal.dhanoa@monash.edu - MCT-456 Add Logic to close MC cases.
 * @revision        inderpal.dhanoa@monash.edu - MCT-504 Add Exclusion Logic for Student Support Cases.
 */
 @isTest //(isParallel=true) : In parallel Apex tests, DML operations aren't permitted on this type of object: User: []
private class OutboundCallResultServices_Test {
    /**
     * @description test method to setup data
     */
    @testSetup
    static void setup() {
         Date futureDate;
         Date todayDate = Date.today();
         futureDate = todayDate.addDays(5);
        // Contact
        List<Contact> contacts = new List<Contact>();
        
         Contact contact1 = new Contact();
         contact1.LastName = 'LastName';
         contact1.Person_Id_Unique__c = '1';
         Contact contact2 = (Contact)TestDataFactory.createSObject(new Contact(LastName = 'LastName2', Person_Id_Unique__c = '2'), false);
         contacts.add(contact1);
         contacts.add(contact2);
        insert contacts;
            
        // Campaign
        List<Campaign> campaigns = new List<Campaign>();
        
         Campaign campaign1 = new Campaign();
         campaign1.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('MonCon_Support').getRecordTypeId();
         campaign1.CampaignMemberRecordTypeId = Schema.SObjectType.CampaignMember.getRecordTypeInfosByDeveloperName().get('Outbound_Call').getRecordTypeId();
         campaign1.Name = 'MonCon Support Outbound Call Campaign';
         campaign1.StartDate = Date.today();
         campaign1.EndDate = futureDate;
         campaigns.add(campaign1);
        
        insert campaigns;
        
        // Outbound_Call_Result__c
        List<Outbound_Call_Result__c> outboundCallResults = new List<Outbound_Call_Result__c>();
        
         Outbound_Call_Result__c outboundCallResult1 = new Outbound_Call_Result__c();
         outboundCallResult1.Campaign__c = campaign1.Id;
         outboundCallResult1.Contact__c = contact1.Id;
         outboundCallResult1.RecordTypeId = Schema.SObjectType.Outbound_Call_Result__c.getRecordTypeInfosByDeveloperName().get('MonCon_Support').getRecordTypeId();
         outboundCallResults.add(outboundCallResult1);
        
        insert outboundCallResults;
       
        //create a test Contact
		List<Contact> conList = TestHelper.createProspectiveStudentContact(1);
		Contact con = conList[0];
		con.FirstName = 'setupPS';
		con.LastName = 'setupPS';
		con.Email = 'setupPS@test.org';
		insert con;
        
        //create setup Lead
		Lead setupLead = TestHelper.createLeads(1)[0];
        setupLead.Contact__c = con.Id;
		setupLead.Active_Lead_Contact_Id__c = con.Id;
		setupLead.RecordTypeId = Schema.SObjectType.Lead
		                         .getRecordTypeInfosByName()
		                         .get(Label.Lead_Rectype_ProspectiveStudent)
		                         .getRecordTypeId();

        insert setupLead;
        
        // User
        User u = new User(
            LastName = 'LN',
            FirstName='FN',
            Alias = 'Alias',
            Email = 'be12145f057545f8ba195fd2889b2121@monash.edu',
            Username = 'be12145f057545f8ba195fd2889b2121@monash.edu',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id,
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US'
        );
        
        insert u;
    }

    /**
     * @description : Test the "closeLinkedMCEnquiries" method if the Contact gets linked as a Campaign Member
     */
    @isTest
    static void testCloseLinkedMCEnquiries() {
        // GIVEN: A Case linked exists
        Contact con = [SELECT Id FROM Contact WHERE LastName = 'LastName' AND Person_Id_Unique__c = '1' ORDER By CreatedDate DESC LIMIT 1];
        // Create Enquiry
        Case relEnq = (Case)TestDataFactory.createSObject(new Case(ContactId = con.Id, Subject = 'Test OutboundCallResultServices_Test', Status = 'Open', 
                                                RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Monash_Connect_Enquiry').getRecordTypeId(), 
                                                 Category_Level_2__c = 'Welfare meetings', Enquiry_Type__c = 'Current Course', Category_Level_1__c = 'Under 18s'), true);

        Outbound_Call_Result__c ocr = (Outbound_Call_Result__c)TestDataFactory.createSObject(new Outbound_Call_Result__c(Contact__c = con.Id, Call_Result__c = 'No Answer', 
                                        Case__c = relEnq.Id,
                                        RecordTypeId = Schema.SObjectType.Outbound_Call_Result__c.getRecordTypeInfosByDeveloperName().get('MonCon_Support').getRecordTypeId()), true);
        
        ocr = [SELECT Id,Call_Status__c FROM Outbound_Call_Result__c WHERE Case__c = :relEnq.Id];
        
        //Run as Admin, as code runs in without sharing mode
        User adminUser = [SELECT Id, UserRoleId 
                            From User 
                            WHERE Profile.Name='System Administrator'
                            AND Username = 'be12145f057545f8ba195fd2889b2121@monash.edu'
                            AND isActive = TRUE
                            Limit 1];

        System.runAs(adminUser) {
            Test.startTest();
            // WHEN: An OCR record is updated
            ocr.Call_Status__c = 'Closed';
            update ocr;    
            Test.stopTest();
            // THEN: The Case is solved
            ocr = [SELECT Id, Case__r.Status FROM Outbound_Call_Result__c WHERE Id = :ocr.Id];
            Assert.areEqual(ocr.Case__r.Status, 'Solved', 'Linked Case not closed');
        }
    }

    @isTest
    static void testSetOutboundCallStatus(){
        //GIVEN: a lead exists
        lead l = [SELECT id,Contact__c FROM Lead WHERE name != null Limit 1];
        Test.startTest();
        Outbound_Call_Result__c ocr = (Outbound_Call_Result__c)TestDataFactory.createSObject(new Outbound_Call_Result__c(Lead__c = l.Id, call_Status__c = 'Open',
            RecordTypeId = OutboundCallResultUtility.DOMESTIC_PRE_APP, Contact__c = l.Contact__c),true);
        Test.stopTest();

        l = [SELECT id,Outbound_Call_Status__c FROM Lead];
        Assert.areEqual(l.Outbound_Call_Status__c, 'In Progress', 'OutboundCall status not updated');
    }
    
    /**
     * @description : Test the "createCampaignMember" method if the Contact gets linked as a Campaign Member
     */
    @isTest
    static void testCreateMCCampaignMember() {
        // GIVEN: A Campaign and COntact exists
        Date futureDate;
        Date todayDate = Date.today();
        futureDate = todayDate.addDays(5);
        Contact con = [SELECT Id FROM Contact WHERE LastName = 'LastName2' AND Person_Id_Unique__c = '2' ORDER By CreatedDate DESC LIMIT 1];
        Campaign camp = [SELECT Id FROM Campaign WHERE Name = 'MonCon Support Outbound Call Campaign' ORDER By CreatedDate DESC LIMIT 1];

        //Run as Admin, as code runs in without sharing mode
        User adminUser = [SELECT Id, UserRoleId 
                            From User 
                            WHERE Profile.Name='System Administrator'
                            AND Username = 'be12145f057545f8ba195fd2889b2121@monash.edu'
                            AND isActive = TRUE
                            Limit 1];

        System.runAs(adminUser) {
            Test.startTest();
            // WHEN: An OCR record is created
            TestDataFactory.createSObject(new Outbound_Call_Result__c(Contact__c = con.Id, Campaign__c = camp.Id, 
                                        RecordTypeId = Schema.SObjectType.Outbound_Call_Result__c.getRecordTypeInfosByDeveloperName().get('MonCon_Support').getRecordTypeId()), true);
                    
            Test.stopTest();
            // THEN: The campaign Memb is created
            List<CampaignMember> linkedRecds = [SELECT Id FROM CampaignMember WHERE CampaignId = :camp.Id AND ContactId = :con.Id];
            Assert.areEqual(linkedRecds.size(), 1, 'Campaign Member not mapped');
        }
    }
    
    static testMethod void testUnassignedQueueOwnerAssignment() {
        Test.startTest();
        
        Outbound_Call_Result__c ocr = [SELECT Owner_Name__c FROM Outbound_Call_Result__c LIMIT 1];
        
        Test.stopTest();
        
        System.assertEquals('Outbound Call: Unassigned', ocr.Owner_Name__c);
    }

    /*******************************************************************************
     * @author       Inderpal Dhanoa
     * @date         26.Aug.2024
     * @description  Tests updation of Student Support OCR records
    *******************************************************************************/
	@isTest 
    static void testCallResultEnquiryNotCreated() {
        
        // GIVEN: A User already exists
        Test.startTest();
        User u = [SELECT Id FROM User WHERE UserName = 'be12145f057545f8ba195fd2889b2121@monash.edu' ORDER BY CreatedDate DESC LIMIT 1];
        
        System.runAs(u) {
            Outbound_Call_Result__c ocr = [SELECT Id, Call_Result__c, Comments__c, Engagement_Type__c, Retention_Status__c, Risk_Category_V2__c, Number_Of_Attempts__c, OwnerId FROM Outbound_Call_Result__c LIMIT 1];
            
            ocr.OwnerId = u.Id;
            ocr.Comments__c = 'Comments';
            ocr.Engagement_Type__c = 'Student Support';
            ocr.Risk_Category__c = 'COVID-19';
            ocr.Number_Of_Attempts__c = '1';
            // WHEN: An OCR is updated
            update ocr;
        }
        
        Test.stopTest();
        // THEN: The field is updated
        Assert.areEqual(0, [SELECT Id FROM Case].size(), 'Case creation not working for Call Result = Student Support');
    }
    
    static testMethod void testCallResultEnquiryCreated() {
        
        // GIVEN: A User already exists
        Test.startTest();
        User u = [SELECT Id FROM User WHERE UserName = 'be12145f057545f8ba195fd2889b2121@monash.edu' ORDER BY CreatedDate DESC LIMIT 1];
        
        System.runAs(u) {
            Outbound_Call_Result__c ocr = [SELECT Id, Call_Result__c, Comments__c, Engagement_Type__c, Retention_Status__c, Risk_Category_V2__c, Number_Of_Attempts__c, OwnerId FROM Outbound_Call_Result__c LIMIT 1];
            
            ocr.OwnerId = u.Id;
            ocr.Call_Result__c = 'Enquiry Created';
            ocr.Comments__c = 'Comments';
            ocr.Engagement_Type__c = 'Conversion';
            ocr.Retention_Status__c = 'Declined Offer';
            ocr.Risk_Category__c = 'COVID-19';
            ocr.Number_Of_Attempts__c = '1';
            // WHEN: An OCR is updated
            update ocr;
        }
        
        Test.stopTest();
        // THEN: The field is updated
        System.assertEquals(1, [SELECT Id FROM Case].size(), 'Case creation not working for Call Result = Enquiry Created');
    }
    
    static testMethod void testCallResultNoAnswer() {
        
        // GIVEN: A User already exists
        User u = [SELECT Id FROM User WHERE UserName = 'be12145f057545f8ba195fd2889b2121@monash.edu' ORDER BY CreatedDate DESC LIMIT 1];
        Test.startTest();
        System.runAs(u) {
            Outbound_Call_Result__c ocr = [SELECT Id, Call_Result__c, Number_Of_Attempts__c, OwnerId FROM Outbound_Call_Result__c LIMIT 1];
            
            ocr.Call_Result__c = 'No Answer';
            ocr.Number_Of_Attempts__c = '2';
            ocr.OwnerId = u.Id;
            // WHEN: An OCR is updated
            update ocr;
        }
        
        Test.stopTest();
        // THEN: The field is updated
        System.assertEquals(1, [SELECT Id FROM Case].size(), 'Case creation not working for Call Result = No Answer');
    }
    
    static testMethod void testCallResultWrongNumber() {
                
        User u = [SELECT Id FROM User WHERE UserName = 'be12145f057545f8ba195fd2889b2121@monash.edu' ORDER BY CreatedDate DESC LIMIT 1];
        Test.startTest();
        // GIVEN: A User already exists
        System.runAs(u) {
            Outbound_Call_Result__c ocr = [SELECT Id, Call_Result__c, Number_Of_Attempts__c, OwnerId FROM Outbound_Call_Result__c LIMIT 1];
            
            ocr.Call_Result__c = 'Wrong Number';
            ocr.Number_Of_Attempts__c = '1';
            ocr.OwnerId = u.Id;
            // WHEN: An OCR is updated
            update ocr;
        }
        
        Test.stopTest();
        // THEN: The field is updated
        System.assertEquals(1, [SELECT Id FROM Case].size(), 'Case creation not working for Call Result = Wrong Number');
    }
    
    static testMethod void testTrackOutboundCallsDateTimeClosed() {
        User u = [SELECT Id FROM User WHERE UserName = 'be12145f057545f8ba195fd2889b2121@monash.edu' ORDER BY CreatedDate DESC LIMIT 1];
        
        Test.startTest();
        // GIVEN: A User already exists
        Outbound_Call_Result__c ocr = [SELECT Id, Call_Result__c, Call_Status__c, Date_Time_Closed__c FROM Outbound_Call_Result__c LIMIT 1];
        
        System.assert(ocr.Date_Time_Closed__c == null, 'Test data setup is not correct.');
        
        ocr.Call_Result__c = 'No - Not Applicable';
        ocr.Call_Status__c = 'Closed';
        ocr.OwnerId = u.Id;
        // WHEN: An OCR is updated
        update ocr;
        
        ocr = [SELECT Id, Call_Status__c, Date_Time_Closed__c FROM Outbound_Call_Result__c LIMIT 1];
        
        Test.stopTest();
        // THEN: The field is updated
        System.assert(ocr.Date_Time_Closed__c != null, 'Date/Time Closed tracking is not working.');
    }
}