force-app/main/default/objects/Payment_Portal__c.object
<CustomObject>
    <description>Payment details of a pledge / gift</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Payment amount</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Name_Auto_Number__c</fullName>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Payment Name Auto Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <description>The pledge of gift the payment is paying to</description>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipName>Payments_Transaction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment (Portal)</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments (Portal)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>Tracks the total amount that a donor made in one portal transaction</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <description>Pledge payment / gift payment</description>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PORTAL_TRIG_PaymentPortal_Test.cls
/*
 * @author Ajitabh
 * @date 23/01/2020
 * @group PORTAL_UCIN
 * @description Test class for portal payment
 */
@isTest(isParallel=true)
public class PORTAL_TRIG_PaymentPortal_Test {
    
    @testSetup static void setup(){
        Transaction__c  tran = new Transaction__c();
        insert tran;
     	List<Payment_Portal__c> paymentList = new List<Payment_Portal__c>();
        Payment_Portal__c payment = new Payment_Portal__c();
        payment.Transaction__c = tran.Id;
        payment.Amount__c=848;
        paymentList.add(payment);
        insert paymentList;   
    }    
    @IsTest
    public static void test_first_methods()
    {
        
        List<Payment_Portal__c> paymentList = [select id from Payment_Portal__c];
        test.startTest();
        delete paymentList;
        test.stopTest();
        
    }
	@IsTest
    public static void test_second_methods()
    {
        
        List<Payment_Portal__c> paymentList = [select id,name,Payment_Name_Auto_Number__c from Payment_Portal__c];
        test.startTest();
        PORTAL_TRIG_PaymentPortal.run(false,true,true,false,false,false,paymentList,paymentList);
        test.stopTest();
        System.assertEquals(paymentList[0].name,paymentList[0].Payment_Name_Auto_Number__c);

        
    }
    @IsTest
    public static void test_third_methods()
    {
        
        List<Payment_Portal__c> paymentList = [select id from Payment_Portal__c];
        delete paymentList;
        test.startTest();
        undelete paymentList;
        test.stopTest();
        
    }
}