force-app/main/default/objects/Product_Fee__c.object
<CustomObject>
    <description>This object is used to hold pricing data for products which is mastered externally and does not map to provided pricing methods appropriately.</description>
    <fields>
        <fullName>Migration_Id__c</fullName>
        <description>This field is used to migrate records between environments</description>
        <externalId>true</externalId>
        <inlineHelpText>This field is used to migrate records between environments</inlineHelpText>
        <label>Migration Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Period_Cover__c</fullName>
        <label>Period Cover</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prov_Amount__c</fullName>
        <label>Prov Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Product External Fee</label>
    <nameField>
        <displayFormat>FN-{00000000}</displayFormat>
        <label>Fee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product External Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductFeeBISetExternalID_FT.cls
/**
 * @description :   Test class for Product Fee : BI : Set External ID Flow
 * @author      :   Vinothraja
 * @date        :   08-04-2025
 * @group       :   Platforms
 * @revision
 *   08-04-2025 Vinothraja - EPCP-4551 created test class to test the Product Fee : BI : Set External ID Flow
 */ 
@isTest (isParallel = true)
public with sharing class ProductFeeBISetExternalID_FT {
    /**
     * @description test setting the external id for a product fee
     */
    @isTest
    static void shouldSetExternalId() {
        // Disable Trigger
        TriggerCommon.disableTrigger('Product_Fee__c');

        // GIVEN
        // A test Product Fee 
        Product_Fee__c testProductFee = new Product_Fee__c(Period_Cover__c = 12, Prov_Amount__c = 1000);

        // WHEN
        // A Product Fee is created
        Test.startTest();
            insert testProductFee;
        Test.stopTest();

        // THEN
        // Verify that the product fee's external id is set
        List<Product_Fee__c> updatedProductFees = [SELECT Id, Migration_Id__c FROM Product_Fee__c WHERE Id = :testProductFee.Id];
        Assert.areEqual(((Id) UserInfo.getOrganizationId()).to15() + '_' + testProductFee.Id, updatedProductFees[0].Migration_Id__c);

        // Enable Trigger
        TriggerCommon.enableTrigger('Product_Fee__c');
    }
}