force-app/main/default/objects/Volunteer_Hours__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer_Shift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Shift</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Volunteer_Shift__c.Volunteer_Job__c</field>
                <operation>equals</operation>
                <valueField>$Source.Volunteer_Job__c</valueField>
            </filterItems>
            <infoMessage>You can only pick a Shift which belongs to the current Job.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Volunteer_Shift__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Hours</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>HoursID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Job__c.object
<CustomObject>
    <fields>
        <fullName>Areas_of_Interest__c</fullName>
        <label>Areas of Interest</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Art and Design</fullName>
                </value>
                <value>
                    <fullName>Business and Economy</fullName>
                </value>
                <value>
                    <fullName>Career Development and Planning Opportunities</fullName>
                </value>
                <value>
                    <fullName>Culture, Recreation and Sport</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Engineering and Science</fullName>
                </value>
                <value>
                    <fullName>Entrepreneurship, Start Ups &amp; Innovation</fullName>
                </value>
                <value>
                    <fullName>Indigenous Communities and Culture</fullName>
                </value>
                <value>
                    <fullName>Law, Politics and Society</fullName>
                </value>
                <value>
                    <fullName>Medicine and Health (includes Mental Health and Aging)</fullName>
                </value>
                <value>
                    <fullName>Sustainable Development and Environment</fullName>
                </value>
                <value>
                    <fullName>Technology, AI &amp; Data Science</fullName>
                </value>
                <value>
                    <fullName>Arts, Design &amp; Performance</fullName>
                    <isActive>false</isActive>
                    <label>Arts, Design &amp; Performance</label>
                </value>
                <value>
                    <fullName>Business</fullName>
                    <isActive>false</isActive>
                    <label>Business</label>
                </value>
                <value>
                    <fullName>Communications &amp; Media</fullName>
                    <isActive>false</isActive>
                    <label>Communications &amp; Media</label>
                </value>
                <value>
                    <fullName>Entrepreneurship</fullName>
                    <isActive>false</isActive>
                    <label>Entrepreneurship</label>
                </value>
                <value>
                    <fullName>Environment</fullName>
                    <isActive>false</isActive>
                    <label>Environment</label>
                </value>
                <value>
                    <fullName>Health &amp; Wellness</fullName>
                    <isActive>false</isActive>
                    <label>Health &amp; Wellness</label>
                </value>
                <value>
                    <fullName>Inclusion and Diversity</fullName>
                    <isActive>false</isActive>
                    <label>Inclusion and Diversity</label>
                </value>
                <value>
                    <fullName>Issues in the law</fullName>
                    <isActive>false</isActive>
                    <label>Issues in the law</label>
                </value>
                <value>
                    <fullName>Performing Arts</fullName>
                    <isActive>false</isActive>
                    <label>Performing Arts</label>
                </value>
                <value>
                    <fullName>Philanthropy</fullName>
                    <isActive>false</isActive>
                    <label>Philanthropy</label>
                </value>
                <value>
                    <fullName>Public, Social &amp; Human Services</fullName>
                    <isActive>false</isActive>
                    <label>Public, Social &amp; Human Services</label>
                </value>
                <value>
                    <fullName>Research</fullName>
                    <isActive>false</isActive>
                    <label>Research</label>
                </value>
                <value>
                    <fullName>Science, Technology, Engineering &amp; Mathematics</fullName>
                    <isActive>false</isActive>
                    <label>Science, Technology, Engineering &amp; Mathematics</label>
                </value>
                <value>
                    <fullName>Sports</fullName>
                    <isActive>false</isActive>
                    <label>Sports</label>
                </value>
                <value>
                    <fullName>Sustainability, Environmental &amp; Natural Resources</fullName>
                    <isActive>false</isActive>
                    <label>Sustainability, Environmental &amp; Natural Resources</label>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                    <isActive>false</isActive>
                    <label>Talent Management</label>
                </value>
                <value>
                    <fullName>Visual Arts</fullName>
                    <isActive>false</isActive>
                    <label>Visual Arts</label>
                </value>
                <value>
                    <fullName>Women&apos;s Rights</fullName>
                    <isActive>false</isActive>
                    <label>Women&apos;s Rights</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Volunteer Jobs</relationshipLabel>
        <relationshipName>Volunteer_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Volunteer Job End Date</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Externally_Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this field if this Volunteer Job should be included in the Get Involved Alumni Portal page.</inlineHelpText>
        <label>Externally Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Skills_Needed__c</fullName>
        <inlineHelpText>the skills the volunteer should have to do this job</inlineHelpText>
        <label>Skills Needed</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Administration &amp; Office Support</fullName>
                </value>
                <value>
                    <fullName>Advertising, Arts &amp; Media</fullName>
                </value>
                <value>
                    <fullName>Banking &amp; Financial Services</fullName>
                </value>
                <value>
                    <fullName>Call Centre &amp; Customer Service</fullName>
                </value>
                <value>
                    <fullName>CEO &amp; General Management</fullName>
                </value>
                <value>
                    <fullName>Community Services &amp; Development</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting &amp; Strategy</fullName>
                </value>
                <value>
                    <fullName>Design &amp; Architecture</fullName>
                </value>
                <value>
                    <fullName>Education &amp; Training</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Farming, Animals &amp; Conservation</fullName>
                </value>
                <value>
                    <fullName>Government &amp; Defence</fullName>
                </value>
                <value>
                    <fullName>Healthcare &amp; Medical</fullName>
                </value>
                <value>
                    <fullName>Hospitality &amp; Tourism</fullName>
                </value>
                <value>
                    <fullName>Human Resources &amp; Recruitment</fullName>
                </value>
                <value>
                    <fullName>Information &amp; Communication Technology</fullName>
                </value>
                <value>
                    <fullName>Insurance &amp; Superannuation</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Manufacturing, Transport &amp; Logistics</fullName>
                </value>
                <value>
                    <fullName>Marketing &amp; Communications</fullName>
                </value>
                <value>
                    <fullName>Mining, Resources &amp; Energy</fullName>
                </value>
                <value>
                    <fullName>Real Estate &amp; Property</fullName>
                </value>
                <value>
                    <fullName>Retail &amp; Consumer Products</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Science &amp; Technology</fullName>
                </value>
                <value>
                    <fullName>Self Employment</fullName>
                </value>
                <value>
                    <fullName>Sport &amp; Recreation</fullName>
                </value>
                <value>
                    <fullName>Trades &amp; Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Type__c</fullName>
        <label>Volunteer Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advisor</fullName>
                </value>
                <value>
                    <fullName>Event Organiser</fullName>
                </value>
                <value>
                    <fullName>Feedback to Monash</fullName>
                </value>
                <value>
                    <fullName>General Interest</fullName>
                </value>
                <value>
                    <fullName>Mentor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Share Story</fullName>
                </value>
                <value>
                    <fullName>Social moderator</fullName>
                </value>
                <value>
                    <fullName>Speaker - Advanced</fullName>
                </value>
                <value>
                    <fullName>Speaker - Beginner</fullName>
                </value>
                <value>
                    <fullName>Speaker - Intermediate</fullName>
                </value>
                <value>
                    <fullName>Student Host</fullName>
                </value>
                <value>
                    <fullName>Thought Leadership</fullName>
                </value>
                <value>
                    <fullName>Mentee</fullName>
                    <isActive>false</isActive>
                    <label>Mentee</label>
                </value>
                <value>
                    <fullName>Student Participant</fullName>
                    <isActive>false</isActive>
                    <label>Student Participant</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Shift__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Job_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>ShiftID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PORTAL_UCIN_GetInvolvedController_Test.cls
/*
 * @author Charlie Park, UC Innovation
 * @date 11/10/2019
 * @group PORTAL_UCIN
 * @group-content 
 * @description Test class for get involved page
 */
@IsTest //(IsParallel=true) System.DmlException: Insert failed. First exception on row 0; first error: APEX_DATA_ACCESS_RESTRICTION, In parallel Apex tests, DML operations aren't permitted on this type of object: User: []
public class PORTAL_UCIN_GetInvolvedController_Test {
    @testSetup
    static void setupData() {
        Campaign camp = new Campaign();
        camp.isActive = true;
        camp.Name = 'test';
        insert camp;

        List<Volunteer_Job__c> volJobs = new List<Volunteer_Job__c>();
        Volunteer_Job__c job = new Volunteer_Job__c();
        job.Campaign__c = camp.Id;
        job.Externally_Visible__c = true;
        job.Areas_of_Interest__c = 'Education';
        volJobs.add(job);
        
        Volunteer_Job__c job2 = new Volunteer_Job__c();
        job2.Campaign__c = camp.Id;
        job2.Externally_Visible__c = true;
        job2.Areas_of_Interest__c = 'Art and Design';
        job2.Volunteer_Type__c = 'Other';
        volJobs.add(job2);

        Volunteer_Job__c job3 = new Volunteer_Job__c();
        job3.Campaign__c = camp.Id;
        job3.Externally_Visible__c = true;
        job3.Areas_of_Interest__c = 'Art and Design';
        job3.Skills_Needed__c = 'Sales';
        volJobs.add(job3);
        
         Volunteer_Job__c job4 = new Volunteer_Job__c();
        job4.Name = 'Interesting Job';
        job4.Campaign__c = camp.Id;
        job4.Externally_Visible__c = true;
        job4.End_Date__c = Date.today().addDays(10);
        volJobs.add(job4);
        
        insert volJobs;
        
        /*
        Volunteer_Shift__c shift = new Volunteer_Shift__c();
        shift.Volunteer_Job__c = job.Id;
        shift.Start_Date_Time__c = system.today();
        shift.Duration__c = 8;
        insert shift;*/
    }

    @isTest
    public static void test_SERVER_getVolunteerJobs() {
        test.startTest();
        list<Volunteer_Job__c> jobList = PORTAL_UCIN_GetInvolvedController.SERVER_getVolunteerJobs('', '', '', '10');
        test.stopTest();

        // Retrieve jobs successfully
        System.assertNotEquals(jobList.size(), 0); 
    }



    @isTest
    public static void test_SERVER_searchVolunteerJob() {
        test.startTest();
        List<Volunteer_Job__c> jobList = PORTAL_UCIN_GetInvolvedController.SERVER_searchVolunteerJob('rt and design');
        test.stopTest();

        // Should find based on Art and Design search 
        System.assertNotEquals(jobList.size(), 0);
    }

    @isTest
    public static void test_SERVER_expressInterest() {
        Volunteer_Job__c thisJob = [select id, Start_Date__c from Volunteer_Job__c WHERE Name = 'Interesting Job'  LIMIT 1];

        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];

        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
            UserRoleId = portalRole.Id,
            ProfileId = profile1.Id,
            Username = System.now().millisecond() + 'test2@test.com',
            Alias = 'batman',
            Email='bruce.wayne@wayneenterprises.com',
            EmailEncodingKey='UTF-8',
            Firstname='Bruce',
            Lastname='Wayne',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago'
        );
        Database.insert(portalAccountOwner1);

        Id contactId;
        String username =  System.now().millisecond() + 'testEmail925@gmail.com';
        System.runAs ( portalAccountOwner1 ) {
            //Create account
            Account portalAccount1 = new Account(
            Name = 'TestAccount',
            OwnerId = portalAccountOwner1.Id);
            Database.insert(portalAccount1);       

            //create contact (needed by user)
            Contact contact = new contact(LastName = 'LastName', Firstname = 'FirstName');
            contact.Birthdate =  Date.valueOf('2019-09-24');
            contact.AccountId = portalAccount1.Id;
            contact.Volunteer_Areas_of_Interest__c = 'Education';
            contact.Volunteer_Roles__c = 'Mentor';
            contact.Volunteer_Skills__c = 'Sales';
            insert contact;

            User user = new User();
            user.FirstName = 'Customer';
            user.LastName = 'User';
            user.Alias = 'test';
            user.CommunityNickname = 'Test1';
            user.TimeZoneSidKey = 'America/New_York';
            user.LocaleSidKey = 'en_US';
            user.EmailEncodingKey = 'UTF-8';
            user.Email = 'testEmail925@gmail.com';
            user.Username =  username;
            user.IsActive = true;
            user.LanguageLocaleKey = 'en_US';
            user.App_Birthdate__c = Date.valueOf('2019-09-24');        
            
            List<Profile> profiles = [SELECT Id FROM Profile WHERE Name ='Customer Community General User']; 
            system.debug('PROFILES SIZE: ' + profiles.size());
            if(profiles.size() > 0)
            {
                
                user.ProfileID = profiles[0].Id;       		
                user.ContactId = contact.Id;
                insert user;
                PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Alumni_Portal_Permission_Set'];
                insert new PermissionSetAssignment(AssigneeId = user.id, PermissionSetId = ps.Id);
            }     
            Volunteer_Hours__c volHours = new Volunteer_Hours__c(Contact__c = contact.Id, Volunteer_Job__c = thisJob.Id, Status__c = 'Web Sign Up', 
                                                                Start_Date__c = thisJob.Start_Date__c, Number_of_Volunteers__c = 1);
            insert volHours;
        }

        test.startTest();
        User portalUser = [SELECT ID FROM User WHERE Username   = :username LIMIT 1];
        
        system.runAs(portalUser) {
            PORTAL_UCIN_GetInvolvedController.SERVER_expressInterest(thisJob.Id);
            List<Volunteer_Job__c> volPrint = PORTAL_UCIN_GetInvolvedController.SERVER_getVolunteerJobs('', '', '', '10');
            for(Volunteer_Job__c v :volPrint) {
                System.assertNotEquals(thisJob.Id, v.Id);
            }
            List<Volunteer_Job__c> myJobs = PORTAL_UCIN_GetInvolvedController.SERVER_getVolunteerJobs('', 'Me', '', '10');
            System.assert(myJobs.size() > 0);
            
            System.assertNotEquals(PORTAL_UCIN_GetInvolvedController.SERVER_getContactInfo(), null);
        }
        
        test.stopTest();
    }
}