force-app/main/default/objects/Volunteer_Hours__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Volunteers__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Defaults to 1. Increase if this person is bringing additional people whom you are not directly tracking as contacts, and won&apos;t be logging individual volunteer hours against.</inlineHelpText>
        <label>Number of Volunteers</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date_Time__c</fullName>
        <inlineHelpText>The actual date &amp; time the volunteer is planning on starting.</inlineHelpText>
        <label>Planned Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shift_Start_Date_Time__c</fullName>
        <formula>Volunteer_Shift__r.Start_Date_Time__c</formula>
        <label>Shift Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Web Sign Up</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No-Show</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer_Shift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Shift</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Volunteer_Shift__c.Volunteer_Job__c</field>
                <operation>equals</operation>
                <valueField>$Source.Volunteer_Job__c</valueField>
            </filterItems>
            <infoMessage>You can only pick a Shift which belongs to the current Job.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Volunteer_Shift__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Volunteer Hours</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>HoursID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Job__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Volunteer Jobs</relationshipLabel>
        <relationshipName>Volunteer_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Volunteer Job End Date</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Volunteers__c</fullName>
        <inlineHelpText>The total number of volunteers whose Hours Status = Completed or Confirmed.</inlineHelpText>
        <label>Number of Volunteers</label>
        <summarizedField>Volunteer_Hours__c.Number_of_Volunteers__c</summarizedField>
        <summaryFilterItems>
            <field>Volunteer_Hours__c.Status__c</field>
            <operation>equals</operation>
            <value>Confirmed, Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Volunteer_Hours__c.Volunteer_Job__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Volunteer Job Start Date</description>
        <inlineHelpText>Volunteer Job Start Date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Shift__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>How many hours long is the shift?</inlineHelpText>
        <label>Duration (Hours)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Job_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>ShiftID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VolunteerHoursASUpdateFields_FT.cls
/**
 * @description     :   Test class for Volunteer Hours : AS : Update Fields flow
 * @author          :   Sachin Shetty
 * @date            :   29-05-2025
 * @group           :   Platforms
 * @revision
 *  29-05-2025      Sachin Shetty    - EPCP-4512  created test class to test the Volunteer Hours : AS : Update Fields Flow
 */ 
@isTest (isParallel = true)
public class VolunteerHoursASUpdateFields_FT {
    @TestSetup
    static void makeData() {
        Account acc = new Account(
            name='Individual Test Account');
        insert acc;
        
        Contact con = new Contact(
            Lastname='Testy', 
            AccountId=acc.Id, 
            Volunteer_Status__c='Available');
        insert con;
        
        Campaign cmp = new Campaign(
            name='Test Campaign', 
            IsActive=true);
        insert cmp;
        
        Volunteer_Job__c job = new Volunteer_Job__c(
            name='Job1', 
            campaign__c=cmp.Id);
        insert job;
    }
    
    @isTest
    static void testSetEndDateInsert() {
        // GIVEN : Test contact, volunteer job, volunteer shift
        Contact con = [SELECT ID, Lastname, Volunteer_Status__c FROM Contact LIMIT 1];
        Volunteer_Job__c job = [SELECT ID, Name, campaign__c FROM Volunteer_Job__c limit 1];
        Volunteer_Shift__c shift = new Volunteer_Shift__c(
            Volunteer_Job__c=job.Id, 
            Duration__c=1,
        	Start_Date_Time__c=Datetime.now());
        insert shift;
        
        Date todayDate = System.today();

        // Test inserting new hours
        list<Volunteer_Hours__c> listHours = new list<Volunteer_Hours__c>();
        for (integer i = 0; i < 10; i++) {
            Volunteer_Hours__c hours = new Volunteer_Hours__c(
                Volunteer_Job__c=job.id,
                Volunteer_Shift__c=shift.Id,
                Contact__c=con.Id,
                Number_of_Volunteers__c=3,
                Start_Date__c=todayDate,
                Status__c='Qualified');
            listHours.add(hours);
        }

        // WHEN : Volunteer Hour records are inserted
        test.startTest();
        	insert listHours;
        test.stopTest();

        // THEN : The End Date on the Volunteer Hours are populated with Start Date
        for(Volunteer_Hours__c hour : [SELECT Start_Date__c, End_Date__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id]){
            Assert.isTrue(hour.Start_Date__c==hour.End_Date__c, 'End Date should be same as Start Date');
        }
    }
    
    @isTest
    static void testSetEndDateUpdate() {
        // GIVEN : Test contact, volunteer job, volunteer shift
        Contact con = [SELECT ID, Lastname, Volunteer_Status__c FROM Contact LIMIT 1];
        Volunteer_Job__c job = [SELECT ID, Name, campaign__c FROM Volunteer_Job__c limit 1];
        Volunteer_Shift__c shift = new Volunteer_Shift__c(
            Volunteer_Job__c=job.Id, 
            Duration__c=1,
        	Start_Date_Time__c=Datetime.now());
        insert shift;

        // Test inserting new hours
        list<Volunteer_Hours__c> listHours = new list<Volunteer_Hours__c>();
        for (integer i = 0; i < 10; i++) {
            Volunteer_Hours__c hours = new Volunteer_Hours__c(
                Volunteer_Job__c=job.id,
                Volunteer_Shift__c=shift.Id,
                Contact__c=con.Id,
                Number_of_Volunteers__c=3,
                Status__c='Qualified');
            listHours.add(hours);
        }
        insert listHours;
        
        listHours = [SELECT Id, Start_Date__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id];
		Date todayDate = System.today();
        for(Volunteer_Hours__c hour : listHours){
            hour.Start_Date__c = todayDate;
        }

        // WHEN : Volunteer Hour records are updated
        test.startTest();
        	update listHours;
        test.stopTest();

        // THEN : The End Date on the Volunteer Hours are populated with Start Date
        for(Volunteer_Hours__c hour : [SELECT Start_Date__c, End_Date__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id]){
            Assert.isTrue(hour.Start_Date__c==hour.End_Date__c, 'End Date should be same as Start Date');
        }
    }
    
    @isTest
    static void testSetEndDateNotUpdated() {
        // GIVEN : Test contact, volunteer job, volunteer shift
        Contact con = [SELECT ID, Lastname, Volunteer_Status__c FROM Contact LIMIT 1];
        Volunteer_Job__c job = [SELECT ID, Name, campaign__c FROM Volunteer_Job__c limit 1];
        Volunteer_Shift__c shift = new Volunteer_Shift__c(
            Volunteer_Job__c=job.Id, 
            Duration__c=1,
        	Start_Date_Time__c=Datetime.now());
        insert shift;
		Date todayDate = System.today();
        
        // Test inserting new hours
        list<Volunteer_Hours__c> listHours = new list<Volunteer_Hours__c>();
        for (integer i = 0; i < 10; i++) {
            Volunteer_Hours__c hours = new Volunteer_Hours__c(
                Volunteer_Job__c=job.id,
                Volunteer_Shift__c=shift.Id,
                Contact__c=con.Id,
                Number_of_Volunteers__c=3,
                Start_Date__c=todayDate,
                Status__c='Qualified');
            listHours.add(hours);
        }
        insert listHours;
        
        listHours = [SELECT Id, Start_Date__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id];
		Date newDate = System.today().addMonths(-3);
        for(Volunteer_Hours__c hour : listHours){
            hour.Start_Date__c = newDate;
        }

        // WHEN : Volunteer Hour records are updated
        test.startTest();
        	update listHours;
        test.stopTest();

        // THEN : The End Date on the Volunteer Hours are not updated as they were already populated
        for(Volunteer_Hours__c hour : [SELECT Start_Date__c, End_Date__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id]){
            Assert.isFalse(hour.Start_Date__c==hour.End_Date__c, 'End Date should not be same as Start Date');
        }
    }
    
    @isTest
    static void testSetPlannedStartDateInsert() {
        // GIVEN : Test contact, volunteer job, volunteer shift
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Volunteer_Job__c job = [SELECT Id FROM Volunteer_Job__c limit 1];

        DateTime timeNow = Datetime.now();
        Volunteer_Shift__c shift = new Volunteer_Shift__c(
            Volunteer_Job__c=job.Id, 
            Duration__c=1,
        	Start_Date_Time__c=timeNow);
        insert shift;

        // Test inserting new hours
        list<Volunteer_Hours__c> listHours = new list<Volunteer_Hours__c>();
        for (integer i = 0; i < 10; i++) {
            Volunteer_Hours__c hours = new Volunteer_Hours__c(
                Volunteer_Job__c=job.id,
                Volunteer_Shift__c=shift.Id,
                Contact__c=con.Id,
                Number_of_Volunteers__c=3,
                Status__c='Qualified');
            listHours.add(hours);
        }

        // WHEN : Volunteer Hour records are inserted
        test.startTest();
        	insert listHours;
        test.stopTest();

        // THEN : The Planned Start Date Time on the Volunteer Hours are populated with Shift Start Date Time
        for(Volunteer_Hours__c hour : [SELECT Planned_Start_Date_Time__c, Shift_Start_Date_Time__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id]){
            Assert.isTrue(hour.Planned_Start_Date_Time__c==hour.Shift_Start_Date_Time__c, 'Planned Start Date Time should be same as Shift Start Date Time');
        }
    }
    
    @isTest
    static void testSetPlannedStartDateUpdate() {
        // GIVEN : Test contact, volunteer job, volunteer shift
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Volunteer_Job__c job = [SELECT Id FROM Volunteer_Job__c limit 1];

        // Test inserting new hours
        list<Volunteer_Hours__c> listHours = new list<Volunteer_Hours__c>();
        for (integer i = 0; i < 10; i++) {
            Volunteer_Hours__c hours = new Volunteer_Hours__c(
                Volunteer_Job__c=job.id,
                //Volunteer_Shift__c=shift.Id,
                Contact__c=con.Id,
                Number_of_Volunteers__c=3,
                Status__c='Qualified');
            listHours.add(hours);
        }
        insert listHours;
        
        DateTime timeNow = Datetime.now();
        Volunteer_Shift__c shift = new Volunteer_Shift__c(
            Volunteer_Job__c=job.Id, 
            Duration__c=1,
        	Start_Date_Time__c=timeNow);
        insert shift;

        
        listHours = [SELECT Id, Number_of_Volunteers__c, Volunteer_Shift__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id];
        for(Volunteer_Hours__c hour : listHours){
            hour.Number_of_Volunteers__c = 4;
            hour.Volunteer_Shift__c=shift.Id;
        }

        // WHEN : Volunteer Hour records are updated
        test.startTest();
        	update listHours;
        test.stopTest();

        // THEN : The Planned Start Date Time on the Volunteer Hours are populated with Shift Start Date Time
        for(Volunteer_Hours__c hour : [SELECT Planned_Start_Date_Time__c, Shift_Start_Date_Time__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id]){
            Assert.isNotNull(hour.Planned_Start_Date_Time__c, 'Planned Start Date is populated');
            Assert.isTrue(hour.Planned_Start_Date_Time__c==hour.Shift_Start_Date_Time__c, 'End Date should be same as Start Date');
        }
    }
    
    @isTest
    static void testSetPlannedStartDateNotUpdated() {
        // GIVEN : Test contact, volunteer job, volunteer shift
        Contact con = [SELECT ID, Lastname, Volunteer_Status__c FROM Contact LIMIT 1];
        Volunteer_Job__c job = [SELECT ID, Name, campaign__c FROM Volunteer_Job__c limit 1];

        // Test inserting new hours
        list<Volunteer_Hours__c> listHours = new list<Volunteer_Hours__c>();
        for (integer i = 0; i < 10; i++) {
            Volunteer_Hours__c hours = new Volunteer_Hours__c(
                Volunteer_Job__c=job.id,
                Contact__c=con.Id,
                Number_of_Volunteers__c=3,
                Status__c='Qualified');
            listHours.add(hours);
        }
        insert listHours;
        
        DateTime timeNow = Datetime.now();
        Volunteer_Shift__c shift = new Volunteer_Shift__c(
            Volunteer_Job__c=job.Id, 
            Duration__c=1,
        	Start_Date_Time__c=timeNow);
        insert shift;
        
        listHours = [SELECT Id, Number_of_Volunteers__c, Volunteer_Shift__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id];
        for(Volunteer_Hours__c hour : listHours){
            hour.Number_of_Volunteers__c = 4;
            hour.Volunteer_Shift__c=shift.Id;
        }
        update listHours; // Should populate Planned_Start_Date_Time__c
        
        for(Volunteer_Hours__c hour : [SELECT Planned_Start_Date_Time__c, Shift_Start_Date_Time__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id]){
            Assert.isNotNull(hour.Planned_Start_Date_Time__c, 'Planned Start Date is populated');
            Assert.isTrue(hour.Planned_Start_Date_Time__c==hour.Shift_Start_Date_Time__c, 'End Date should be same as Start Date');
        }
        
        shift = [SELECT ID, Volunteer_Job__c, Duration__c, Start_Date_Time__c FROM Volunteer_Shift__c LIMIT 1];
        DateTime newtime = Datetime.now().addDays(-3);
        shift.Start_Date_Time__c = newtime;
        update shift;
        
        listHours = [SELECT Id, Status__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id];
        for(Volunteer_Hours__c hour : listHours){
            hour.Status__c='In Progress';
        }

        // WHEN : Volunteer Hour records are updated
        test.startTest();
        	update listHours;
        test.stopTest();

        // THEN : The Planned Start Date Time on the Volunteer Hours are not updated as they were already populated
        for(Volunteer_Hours__c hour : [SELECT Planned_Start_Date_Time__c, Shift_Start_Date_Time__c FROM Volunteer_Hours__c WHERE Contact__c=:con.Id]){
            Assert.isFalse(hour.Planned_Start_Date_Time__c==hour.Shift_Start_Date_Time__c, 'End Date should not be same as Start Date');
        }
    }
}